### PR TITLE
Switch to markdown extension for an Important note

### PR DESCRIPTION
**Pull request by Duncanma**

### CODE REVIEW

**Comment by mairaw** [comment]
LGTM. However, we do have other instances of notes, etc. that are not using the same syntax and we were planning to scrub that after the release. Not using this syntax causes any issues?

**Comment by DuncanmaMSFT** [comment]
That's fine, it just looks nicer to use this syntax :)

**Comment by mairaw** [comment]
Ok, thanks for confirming that.

**Comment by mairaw** [comment]
@DuncanmaMSFT, build reports are now complaining about this note:
A ' ' should be appended after the first line of NOTE/WARNING/CAUTION/IMPORTANT syntax.

Do you know what this is about?

**Comment by DuncanmaMSFT** [comment]
Nope, the IMPORTANT syntax that I added to that one page did work, so the warning doesn’t seem to be causing a problem. Adam, perhaps you can check the syntax

**Comment by mairaw** [comment]
from what I'm seeing in the EMS docs, the syntax is a bit different @DuncanmaMSFT 
`> [!IMPORTANT] `
`> This is very preliminary documentation for the .NET Standard Library. Because the standard has not been formalized yet, it is subject to change.`
Since Ron has a PR for this same file, I'm asking him to fix this.

**Pull request merged**
