### PR TITLE
M25917: Possible missing verb

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @ardalis, 

Translator has reported possible source content issue.  

Please, help to check my comment tag added into the article and reply with explanation if source text should be fixed, or it is by design. If fix is needed, please, let me know either if you would like me to fix it in this PR, or if you will fix it in another PR. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR. 

Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by mairaw** [comment]
@ardalis @CESARDELATORRE @rachelappel can you guys with this fix? Not sure what we'd like to say here. 
Should we say "that makes it simple to add real-time"?

The sentence does read a bit weird:
"ASP.NET Core SignalR is a library that makes it simple to kind of real-time server-to-client communication functionality to your applications."

**Comment by rachelappel** [comment]
@mairaw  "ASP.NET Core SignalR is a library that makes it simple to add real-time server-to-client communication functionality to your applications."

**Review by rachelappel — COMMENTED** [review]
"ASP.NET Core SignalR is a library that makes it simple to add real-time server-to-client communication functionality to your applications."

**Comment by ardalis** [comment]
Rachel's update is good. Not sure where "kind of" came from...

**Review by mairaw — CHANGES_REQUESTED** [review]
Please remove the Loc comment and replace "to kind of" with "to add". Thanks!

**Review by mairaw — APPROVED** [review]
I've made the changes on your behalf @carolinacmoravia.

**Pull request merged**
