### PR TITLE
Change library package manager -> nuget package manager

### PR DESCRIPTION
**Pull request by gewarren**
Library Package Manager (VS 2013) is now NuGet Package Manager (>= VS 2015).
Also cleaned up whitespace and a few headings.
(Recommend hiding whitespace changes in the diff.)

### CODE REVIEW

**Review by mairaw — COMMENTED** [review]
LGTM @gewarren. Feel free to merge when you're ready. I feel like your changes warrant a change in ms.date.

**Review by mairaw — APPROVED** [review]
Actually approving it 😄

**Comment by mairaw** [comment]
@gewarren something looks odd here. Let me merge master.

**Comment by mairaw** [comment]
Rebase got rid of the extra PRs. You can squash and merge when ready,

**Comment by gewarren** [comment]
@mairaw Thank you!

**Pull request merged**
