### PR TITLE
Welcome page: updated news links

### PR DESCRIPTION
**Pull request by pkulikov**

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for updating the Welcome page, @pkulikov. With the additions, though, it's beginning to look like a laundry list. It strikes me that we should begin to categorize the items so that the list is more structured. I think that a good start would be to place the items in order (most recent, later version first) in the following categories:
- .NET implementations
- .NET Standard
- .NET application frameworks
- ML.NET
- Languages
- Visual Studio
- Other 
   Microsoft Build 2018 is the only item here

What do you think?

**Comment by pkulikov** [comment]
@rpetrusha I agree with you. Moreover, I don't think those links should be on this page at all.

If it's about *news*, then the better solution might be to provide the links to the *sources* of news. Almost all the links now send to the following blogs:
https://blogs.msdn.microsoft.com/dotnet/  
https://blogs.msdn.microsoft.com/webdev/
https://blogs.msdn.microsoft.com/visualstudio/
https://blogs.msdn.microsoft.com/vbteam/

So, what do you think about replacing all the links with the following text:
> For news about .NET, check the following blogs:
> - [.NET blog](...)
> - [ASP.NET blog](...)
> ...

**Comment by rpetrusha** [comment]
I think that's a great idea, @pkulikov. That's especially true since this is an article we're likely to forget to update on a regular basis. The one exception to the news-related links is the link to Microsoft Build 2018, which has gotten a significant number of clicks. That suggests we should add a section for Resources.

**Comment by pkulikov** [comment]
@rpetrusha I've replaced the links as discussed, also added the links to the "What's new in..." articles. I've tried to avoid to add the **Resources** section. Please tell if it worked out; if not, I'll make a correction.

**Comment by rpetrusha** [comment]
I think it looks really good, @pkulikov. And I really liked the handling of Microsoft Build 2018 and .NET Conf. I'll merge your PR.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
