### PR TITLE
fixed broken link

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
LGTM. This should be OK to merge after the build completes.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
@mairaw, would you mind changing the reference to VB into a link? So instead of "VB.NET 15 Tuples", `[Visual Basic 2017 Tuples](../../visual-basic/programming-guide/language-features/data-types/tuples.md)`. Thanks.

**Comment by mairaw** [comment]
Done @rpetrusha

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
@mairaw, this looks good. I'll merge now.

**Pull request merged**
