### PR TITLE
[CLEANUP] Fix method name trimInput

### PR DESCRIPTION
**Pull request by kahveci**
## Summary

The method 'trimInput' does not follow [Microsoft naming conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) for method names. This will fix it using PascalCasing convention.

### CODE REVIEW

**Comment by mairaw** [comment]
@KrzysztofCwalina @terrajobst the conventions only talk about public methods but it seems the .NET team also uses the same conventions for private methods as shown here: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

So, would you say that private methods should also use PascalCasing?

**Comment by kahveci** [comment]
Any updates on this pull request? Thanks,

**Comment by terrajobst** [comment]
@mairaw is correct. The FDG specifically only prescribe naming conventions for public APIs. Naming of privates is considered code style.

However, I think we can still take this PR because camelCasing for private methods (while being used) isn't exactly mainstream. To my knowledge, none of our OSS code bases use that.

**Comment by mairaw** [comment]
Thanks for the feedback @terrajobst. I'll approve this PR then.

**Review by mairaw — APPROVED** [review]

**Pull request merged**
