### PR TITLE
Use the GetConnectionString method

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by mairaw** [comment]
@nishanil @mvelosop can you please review this suggestion?

**Review by mvelosop — COMMENTED** [review]
Hi @vanillajonathan, in this case, the correct code is to use `Configuration["ConnectionString"]`, just the way it is now in the guide, since it references this value in [`appsettings.json`](https://github.com/dotnet-architecture/eShopOnContainers/blob/5b9692cb2e0dfd718c684a5c23c31bcd7043b7bf/src/Services/Catalog/Catalog.API/appsettings.json):

image

The change you propose would get this value from `appsettings.json`:

```json
{
    "ConnectionStrings": {
        "ConnectionString": "The connection string you'd get"
    }
}
```
That could be a valid option, and it's probably what's commonly used, but it's not correct for the current `appsettings.json` in Catalog.API.

Cheers 😊

**Comment by vanillajonathan** [comment]
True. It should probably be named from "ConnectionString" to "DefaultConnection" anyway.

**Comment by vanillajonathan** [comment]
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/appsettings.json#L2
Would also needed to be changed.

**Comment by mvelosop** [comment]
Hi @vanillajonathan, 

Actually it doesn't need to be changed either, because that's working code and, since there's no need to handle several "ConnectionStrings", it's perfectly fine to use a single "ConnectionString" in `appsettings.json`.

It's perhaps different from what you see most of the time, but it's correct anyway. IMHO it's just a matter of style and that's not really a reason to change it.

Cheers 😊

**Comment by vanillajonathan** [comment]
Okay, I was thinking it would be good to follow common conventions.

**Comment by mvelosop** [comment]
Hi @vanillajonathan,

This is the kind of issue that can be approached with several valid criteria.

If I were to code this from zero, I'd probably use "ConnectionStrings:DefaultConnection" but since this is working code and changing it would mean updating several places (docs, code repo), with their own process pipelines (PRs, reviews), and not really add any significant value, then I would just leave it this way.

Even more, it could be argued that leaving the code the way it is now, might help someone realize the configuration system is more flexible than it may seem.

So I'm closing this issue now.

**Pull request closed without merging**
