### PR TITLE
remove duplicate line

### LINKED ISSUE #40758: Unnecessary repetition of array items in example code
### Type of issue

Typo

### Description

In the example code, the second and last items in the array are repeated (`\\127.0.0.1\c$\temp\test-file.txt`):
```csharp
string[] filenames = {
    @"c:\temp\test-file.txt",
    @"\\127.0.0.1\c$\temp\test-file.txt",
    @"\\LOCALHOST\c$\temp\test-file.txt",
    @"\\.\c:\temp\test-file.txt",
    @"\\?\c:\temp\test-file.txt",
    @"\\.\UNC\LOCALHOST\c$\temp\test-file.txt",
    @"\\127.0.0.1\c$\temp\test-file.txt" };
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/io/file-path-formats.md

### Document Version Independent Id

716a28dc-360e-2964-47f5-0ff18bb00b1c

### Article author

@adegeo

### Metadata

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e 
* Service: **dotnet-fundamentals**

### PR DESCRIPTION
**Pull request by gabbersepp**
## Summary

remove duplicate lines

Fixes #40758

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs/blob/6922643c5cc002763d39de9826fa847ed1ed983b/docs/standard/io/file-path-formats.md) | [File path formats on Windows systems](https://review.learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats?branch=pr-en-us-40777) |

### CODE REVIEW

**Comment by gabbersepp** [comment]
@dotnet-policy-service agree

**Comment by gabbersepp** [comment]
> @gabbersepp please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
> Note
> 
> This content was automatically updated to _filter out profanity_. If you feel as though this was done in error, please [file an issue with the details](https://github.com/IEvangelist/profanity-filter/issues/new).

@dotnet-policy-service agree

**Comment by gabbersepp** [comment]
OK i think I have to create a project file. Will do my best :)

**Review by gewarren — APPROVED** [review]
Thanks @gabbersepp

**Pull request merged**
