### PR TITLE
Fix up xref.xref instances

### PR DESCRIPTION
**Pull request by gewarren**
Replace `<xref:...>.<xref:...>` with `<xref:...?displayProperty=nameWithType>`.
(Diff without whitespace changes.)

### CODE REVIEW

**Comment by Thraka** [comment]
I'm just curious what this change is to accomplish?

**Comment by gewarren** [comment]
@thraka A better way to get the Type.Name display for the link is to add ?displayProperty=nameWithType to the end of a single xref.

**Comment by mairaw** [comment]
That’s our standard way of doing xref links. I’d approve it @Thraka.

**Comment by Thraka** [comment]
But why? Is the context of the paragraph clearer at some point with that? Did the original author write it in a specific way for a reason? Changing link text does alter the reading flow of the paragraph. So I'm just curious why these specific ones were chosen? :)

`displayProperty=nameWithType` shouldn't be mandatory as a way to display a link, it changes how the link is presented so it's a choice to make when needed, right?

**Comment by gewarren** [comment]
I don't think any of the link text changed, just the way the link is coded in the markdown.

**Comment by Thraka** [comment]
OGHHHHHHHHH I'm sorry, I totally missed that you were converting the `xref.xref` format!. OK thanks!

**Review by Thraka — APPROVED** [review]

**Comment by gewarren** [comment]
LOL thanks for the review!

**Pull request merged**
