### PR TITLE
Improve coverage on channel and version for dotnet-install scripts

### LINKED ISSUE #2509: Document and clarify the parameters for dotnet-install
Opened from https://github.com/dotnet/cli/issues/6344

@JohnRusk @WernerMairl I'm going to begin working on this soon. I'll reach out with any questions/discussion on this issue as I work it forward. If you've thought of anything since the OP, please feel free to comment here.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #2509 

cc/ @JohnRusk @WernerMairl

See if this would have been enough to not make the docs a giant pain the neck! lol :grinning: We can mod further if this wouldn't have put the right info in your hands.

### CODE REVIEW

**Comment by JohnRusk** [comment]
Hi @GuardRex  That's certainly a big improvement.  I think, if I was installing today from these new revised instructions, I would still get stuck on two things: 

1. Which values am I allowed to pick, for those things such as branch name or a two-part version number.  I.e. what is the current set of allowable values AND what human-friendly version number do they map to (if the mapping is not direct).  Build numbers are a classic one like that, since I found it impossible to ever figure out how to specify 1.1.1. in the form of a build number.
2. What are the valid _combinations_ of those values - e.g. for channel and version.

Perhaps the idea way to address the above would be to have a table, listing all the official releases that have been released so far, and the combination of channel and version necessary to install them. First column of the table would be 1.0.0, 1.1.1, 1.1.2 etc.  Any such table may need to be co-ordinated with the resolution of the "version numbering issues" as per https://github.com/dotnet/cli/issues/3773  - i.e. the table I propose would need to make it very clear whether its talking about .NET Core version, tooling version or what ever.

**Review by WernerMairl — COMMENTED** [review]
Hi, 
some feedback/suggestion focusing on arguments about Channel and Version.

Please explain better what "coherent" means 
i see that it helps to solve some requirement but
for me it is a new wording in this context.

Please add some sample about working Channel/Version tuples (including regression tests for that ?)

usecases for samples that i can see:

current stable LTS (Channel="LTS" Version = "latest")

current beta/preview :at this point in time probably the "Release 2.0.0" Branch

newest code (2.1.0 probably currently on master)

requirement: there should be Channel/Version tuple samples for specially this usecase that must not be updated every few weeks (out of date branches)!
So values like "LTS", "Current" "Latest" are better then absolute values for branches/release like "Release/2.0.0"....

i hope this helps
 
regards
Werner

**Comment by GuardRex** [comment]
@JohnRusk @WernerMairl Thanks for that excellent feedback. I agree that we need more here.

I spent some time today with the install script (the Windows version from the [`release/2.0.0` branch](https://github.com/dotnet/cli/tree/release/2.0.0/scripts/obtain)) just to see if it does what I think it will do 🤔.

[All links below have the base URL of `https://dotnetcli.azureedge.net/dotnet/Sdk/`.]

## Script: Set the Channel
`-Version` defaults to `latest`.

| Channel | Link |
| :---: | --- |
| Current | Cannot download: 1.0.4/dotnet-sdk-1.0.4-win-x64.zip<br>Downloading legacy link: 1.0.4/dotnet-dev-win-x64.1.0.4.zip |
| LTS | Cannot download: 1.0.4/dotnet-sdk-1.0.4-win-x64.zip<br>Downloading legacy link: 1.0.4/dotnet-dev-win-x64.1.0.4.zip |
| 1.0 | Cannot download: 1.0.4/dotnet-sdk-1.0.4-win-x64.zip<br>Downloading legacy link: 1.0.4/dotnet-dev-win-x64.1.0.4.zip |
| 2.0 | 2.0.0-preview2-006497/dotnet-sdk-2.0.0-preview2-006497-win-x64.zip |
| release/2.0.0-preview2 | 2.0.0-preview2-006502/dotnet-sdk-2.0.0-preview2-006502-win-x64.zip |
| release/2.0.0 | 2.0.0-preview3-006607/dotnet-sdk-2.0.0-preview3-006607-win-x64.zip |
| master | 2.1.0-preview1-006626/dotnet-sdk-2.1.0-preview1-006626-win-x64.zip |

## Script: Set the Version
`-Channel` defaults to `LTS`.

| Version | Link |
| :---: | --- |
| `latest` | Cannot download: 1.0.4/dotnet-sdk-1.0.4-win-x64.zip<br>Downloading legacy link: 1.0.4/dotnet-dev-win-x64.1.0.4.zip<br>or it states "1.0.4 is already installed" |
| `coherent` | FAIL (with LTS See Note*)  |
| `1.0.0` | Cannot download: 1.0.0/dotnet-sdk-1.0.0-win-x64.zip<br>Downloading legacy link: 1.0.0/dotnet-dev-win-x64.1.0.0.zip<br>200 Ok |
| `1.0.1` | Cannot download: 1.0.1/dotnet-sdk-1.0.1-win-x64.zip<br>Downloading legacy link: 1.0.1/dotnet-dev-win-x64.1.0.1.zip<br>200 Ok |
| `1.0.3` | Cannot download: 1.0.3/dotnet-sdk-1.0.3-win-x64.zip<br>Downloading legacy link: 1.0.3/dotnet-dev-win-x64.1.0.3.zip<br>200 Ok |
| `1.0.4` | Cannot download: 1.0.4/dotnet-sdk-1.0.4-win-x64.zip<br>Downloading legacy link: 1.0.4/dotnet-dev-win-x64.1.0.4.zip<br>200 Ok |
| `2.0.0-preview2-006502` | 2.0.0-preview2-006502/dotnet-sdk-2.0.0-preview2-006502-win-x64.zip |
| `2.0.0-preview3-006607` | 2.0.0-preview3-006607/dotnet-sdk-2.0.0-preview3-006607-win-x64.zip |
| `2.1.0-preview1-006626` | 2.1.0-preview1-006626/dotnet-sdk-2.1.0-preview1-006626-win-x64.zip |

*Note: A `-Version` of `coherent` fails with anything except a `-Channel` set to a branch:

| Channel | Version | Link |
| :---: | --- | --- |
| `release/2.0.0-preview2` | `coherent` | 2.0.0-preview2-006502/dotnet-sdk-2.0.0-preview2-006502-win-x64.zip |
| `release/2.0.0` | `coherent` | 2.0.0-preview2-006479/dotnet-sdk-2.0.0-preview2-006479-win-x64.zip |

### Helpful version pages

[.NET Core Runtime and SDK download archive](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md)
[.NET Core Releases](https://github.com/dotnet/core/releases)
[.NET Core SDK (contains .NET Core 1.0 and 1.1)](https://www.microsoft.com/net/download/core#/sdk)
[.NET Core 1.0.5 runtime (LTS) and .NET Core 1.1.2 runtime (Current)](https://www.microsoft.com/net/download/core#/runtime)

### Observations

So the script settings do make sense (thus far 😅) ...

| `-Channel` | Result |
| :---: | --- |
| `Current`, `LTS`, and `1.0` | I do expect to get 1.0.4 SDK, which has .NET Core 1.0.5 (i.e, latest of 1.0) and .NET Core 1.1.2 (i.e., latest of 1.1). The 1.0.5 runtime and the 1.1.2 runtimes are in there. |
| `release/2.0.0` | I get the `preview3` SDK. |
| `release/2.0.0-preview2` | I get the `preview2` SDK. |
| `master` | *The wild one!* That's `2.1.0-preview1-006626` right now, and that's bleeding edge bits. |

What I find a little unsettling about this is that these values of `Current` and `LTS` are referring to the SDK in the same place you're setting values of `1.0` and `2.0`, which have more direct meaning for your request.

With `Current` and `LTS`, you're **NOT** asking for a "Current SDK" or "LTS SDK" ... To quote the great [@]davidfowl, "That's not a thing. You just made that up!" :grinning:

The terms "Current" and "LTS" don't have any tangible meaning with regard to the SDK ... 1.0.4 SDK has *BOTH* 1.0.5 (LTS) and 1.1.2 (Current) inside of it. The prior SDK ... 1.0.3 SDK has *BOTH* 1.0.4 (the prior LTS) and 1.1.1 (the prior Current) inside of it.

The `-Version` results are ok as well. Although, it looks like some things moved around a bit (i.e., "legacy link" language). Setting an explicit value (e.g., `2.0.0-preview3-006607`) brought the specific version right down (when you know of course what to ask for and it exists).

Now, none of that is new or very shocking or anything. The point here is just to get on to your, @JohnRusk, points on (a) what can be provided to each option, and (b) what combos are good/useful; then to your, @WernerMairl, points on the most common use cases and how `coherent` fits into the picture.

My gut tells me that listing the specific versions (all of them) will get heavy as time goes by. They may utterly depreciate versions, which would be tough to maintain. On the other hand, .NET needs some love with new users. Not showing a clear table (or tables) of values as you suggested could be downright harmful! The suggested use cases should be spelled out clearly for the really obvious downloads that devs will want to configure the script for. I totally agree.

Let me chew on this for a bit. We're definitely moving the right direction to get some very helpful guidance in the doc. Think that over :point_up: ... that :book: BOOK I just wrote 😏 ... and let me know your thoughts.

**Comment by JohnRusk** [comment]
That's an awesome bit of analysis @GuardRex!  

Several points come to mind:

1. Your list of "cannot download" errors reminds me of my own attempts to find some way, any way, to install my desired version (which was 1.1, at that time). To me, it just felt like fruitless guessing when I was doing that.
2. What about solving this issue _not_ by making a new list, but instead by including the relevant script command lines in at least one of the _existing lists_? E.g. add a column, called "script command line" or something, and put into it the script to install each version.  The column could be added to one or more of these tables:
    - https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
    - https://www.microsoft.com/net/download/linux  (particularly important here, because the main tables don't mention the scripts, and when you see the bit about scripts at the bottom, you can't relate it back to the particular version that you want)
    - https://www.microsoft.com/net/download/core#/runtime
3. This issue is loosely related to https://github.com/dotnet/cli/issues/6345 in which I've argued that its confusing that there are script-based and non-script based ways to install the framework, and they all do different things, and the places that document them tend to either talk _only_ about the scripted ones or _only_ about the non-scripted ones, with very few places mentioning both, and no page ever describing the differences.  The above suggestion about adding a column to an existing table would help.

**Comment by GuardRex** [comment]
> to install my desired version (which was 1.1, at that time)

... so part of whatever we do with this topic, it should reinforce the point that the .NET Core versions are embedded within the same SDK. The versions are different numbers and representing different things **but sure do sound similar** making it slightly confusing. This will improve a bit with 2.0 generally, but it won't change what we'll have to figure out here for this topic to clarify.

> instead by including the relevant script command lines in at least one of the existing lists

Great idea ... and I took a look at the issue u opened ... excellent. [@]mairaw saw that and this, and she'll help here when we have some kind of decent draft text in place. AFAIK those three pages you cited are owned by the dev team ... not by the docs cats. However, [@]mairaw has :sparkles: magic powers :sparkles:, so something may happen.

For the changes here, I'm approaching this from the standpoint that nothing will change elsewhere and that we can't link to anything that will make the options for `-Channel` and `-Version` clear only by virtue of linking. We'll prob end up using some/all of the links that I listed in the *Helpful version links* section :point_up:, even if they're only listed down in a *See also* section.

**Comment by GuardRex** [comment]
@JohnRusk @WernerMairl Slight delay on working on this one. We have some high priority tasks we need to burn through. I think I'll be back on it ~July 7. Stand-by! ... and have a great weekend! :sunny:

**Comment by GuardRex** [comment]
@JohnRusk @WernerMairl ei ei ei ... I was just about to get back into this and one more priority issue hit. Stand-by ... I'll get back to this asap.

**Comment by GuardRex** [comment]
@JohnRusk @WernerMairl I did have time to look at this and work on it today. We're dogged here a bit by my desire to not show specific versions of things given how they're packaged. We also have some legal factors affecting the language used here.

I definitely feel that https://www.microsoft.com/net/core/support was left out of the presentation, so I mention their doc on support because it so clearly explains what the dev should expect from the two channels `LTS` and `Current`. I added some text and example versions to show possible values that can be provided to `-Channel` and `-Version`.

I also tried to address the definition of `coherent` here by saying that this should be a more stable (tested) combination of packages than what `latest` has to offer.

**Review by WernerMairl — APPROVED** [review]

**Review by BillWagner — APPROVED** [review]
This LGTM.  I'll :shipit: now.

**Comment by JohnRusk** [comment]
Nice!  Your addition of the explanation about "e.g. 1.0.x where x is the patch release" looks like it addresses the specific problem that I originally had.  That should prevent other people from having the same problem.

**Comment by JohnRusk** [comment]
@guardrex I'm trying this today, to install shared-runtime only version 1.1.2.  I'm right back in the same situation as before, in that _nothing_ works.

**Comment by guardrex** [comment]
@JohnRusk I'm sorry to hear that. By "nothing works," you mean u can't get the install script to install the tooling?

I recently had luck using the defaults and only supplying the version to the rel/2.0.0 branch 

... and it :sparkles: JustWorks:tm: :sparkles:!
```
https://raw.githubusercontent.com/dotnet/cli/release/2.0.0/scripts/obtain/dotnet-install.ps1
```
```
dotnet-install.ps1 -Version <CLI_VERSION>
```
... where CLI_VERSION = 2.0.1-servicing-006924

**Comment by JohnRusk** [comment]
I specifically need 1.1.2, on Linux, and nothing that I tried would work.

**Comment by JohnRusk** [comment]
Ok, it's all good now (*)

I'm not sure what I was doing wrong before (maybe I was using the 2.0 script to try to install 1.1.2???) In any case, now, this sequence of commands works fine:
1.`wget https://dot.net/v1/dotnet-install.sh`
1. `chmod 700 dotnet-install.sh `
1. `source dotnet-install.sh --shared-runtime --version 1.1.2`  

(*) Except for this unrelated issue where it was failing on Ubuntu: https://github.com/dotnet/cli/issues/7588

**Pull request merged**
