### PR TITLE
Update NUnit fsharp doc

### LINKED ISSUE #7204: Update NUnit .NET Core get started
# NUnit template is now in dotnet CLI

Update https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit#install-the-nunit-project-template

# General

Adding the package ```dotnet new -i NUnit3.DotNetNew.Template``` is no longer required since the template is pre-installed.

## Issues with Existing Topics

- Will probably need the screen shot discussed in https://github.com/dotnet/docs/issues/5293 updated anyway.

### Suggest reviewers

@mairaw

### PR DESCRIPTION
**Pull request by kendrahavens**
## Summary

Applying C# doc changes to VB doc. (C# PR #7318)

Fixes #7204

### CODE REVIEW

**Comment by kendrahavens** [comment]
Following @mairaw's work on the vb and C# samples, I updated the package versions in the F# sample and the snippet tag #358.

**Comment by kendrahavens** [comment]
@cartermp for F# doc review.

**Review by cartermp — APPROVED** [review]
:shipit: 🚢 🇮🇹

**Comment by kendrahavens** [comment]
@mairaw Does this look okay to merge? Thank you!

**Pull request merged**
