### PR TITLE
PreserveCompilationContext breaking change

### PR DESCRIPTION
**Pull request by gewarren**
Addresses https://github.com/aspnet/Announcements/issues/460.

[Internal preview](https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/preservecompilationcontext-not-set-by-default?branch=pr-en-us-23881)

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by gewarren** [comment]
Thanks Rick! Could you label all except the first announcement (# 461) as documented? https://github.com/aspnet/Announcements/issues

**Comment by Rick-Anderson** [comment]
All as in 458-460? If so, done.

**Comment by gewarren** [comment]
Thank you! Can you also label 454 and 457?

**Comment by Rick-Anderson** [comment]
Done.

**Pull request merged**
