### PR TITLE
Cross updating with Microservices eBook v2.1.02 - Dropped sections

### PR DESCRIPTION
**Pull request by mvelosop**
## Summary

Drop section removed from the e-book:
- Deploying Single-Container-Based .NET Core Web Applications on Linux or Windows Nano Server Hosts
- Migrating Legacy Monolithic .NET Framework Applications to Windows Containers

No issues fixed here

### CODE REVIEW

**Review by BillWagner — CHANGES_REQUESTED** [review]
There are a couple other locations in this eBook where the removed files were referenced.  Can you remove these links:


Warning | Unspecified | InvalidFileLink | docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md | Invalid file link:(~/docs/standard/microservices-architecture/net-core-single-containers-linux-windows-server-hosts/index.md). | BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save | 445 | 09/28/2018 15:52:53
-- | -- | -- | -- | -- | -- | -- | --
Warning | Unspecified | InvalidFileLink | docs/standard/microservices-architecture/multi-container-microservice-net-applications/index.md | Invalid file link:(~/docs/standard/microservices-architecture/containerize-net-framework-applications/index.md). | BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save | 18 | 09/28/2018 15:52:53

After that, it's ready to merge.

**Comment by mvelosop** [comment]
Hi @BillWagner,

Those have been addressed already, just waiting to be merged:

1. First in commit 16af73fb2225957e83e13f37890593e348988c1c
2. Second in commit 21ab90d6d306ebd56cd49833a31112e515b35041 ([here](https://github.com/dotnet/docs/pull/8018/commits/21ab90d6d306ebd56cd49833a31112e515b35041#diff-4))

Best.

**Comment by BillWagner** [comment]
Thanks for the note @mvelosop 

Is the first one part of a PR?  I'll review that as well, and get all of them merged.

**Comment by mvelosop** [comment]
Yes @BillWagner, the first one is part of chapter 5's PR: #7943

**Comment by BillWagner** [comment]
@mvelosop I apologize for dropping the ball on this one.  

Is this ready to merge?

**Comment by mvelosop** [comment]
Hi @BillWagner, no problem. Yep, it's ready to merge, this is also linked to PR #7943 for the right next/previous links.

**Review by BillWagner — APPROVED** [review]

**Pull request merged**
