### PR TITLE
Removing "see remarks" language

### LINKED ISSUE #2031: Removing "see remarks" language
Per https://github.com/dotnet/docs/pull/2003#discussion_r113123751: Language for "see remarks" in various forms are in dozens of files.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #2031 

Per https://github.com/dotnet/docs/pull/2003#discussion_r113123751: Language for "see remarks" in various forms are in dozens of files for `<summary>`, `<param>`, and `<returns>`. This PR removes that language.

@rpetrusha @mairaw Do we also need to remove this language from `<value>` and/or `<exception>` tags?

### CODE REVIEW

**Comment by mairaw** [comment]
I like this change. @rpetrusha what do you think? We could check if we have that in value or exception @GuardRex, if Ron agrees.

**Comment by GuardRex** [comment]
Yes, there are uses of "see remarks" language in both `<value>` and `<exception>` tags. I don't have an exact count, but IIRC there are at least a few dozen cases.

**Comment by rpetrusha** [comment]
@mairaw, @GuardRex, yes, I like the change as well. I think it's worthwhile removing it from the other tags.

**Comment by GuardRex** [comment]
@mairaw @rpetrusha Last commit removes "see remarks" lingo from `<value>` and `<exceptions>` tags. I also caught a handful more to address with a "see **the** remarks" search. This round should get most instances covered. The ones that remain are in the *Remarks* sections themselves (e.g., "... see the Remarks of {some other API} ...").

It's ready for another look. :eyes:

**Comment by rpetrusha** [comment]
@GuardRex, is this ready to merge? If sop, there are two merge conflicts that have to be resolved.

**Comment by GuardRex** [comment]
@rpetrusha Sure .... I'll square those away right now.

**Comment by rpetrusha** [comment]
Unfortunately, @GuardRex, there are additional merge conflicts.

**Review by rpetrusha — APPROVED** [review]
LGTM. You can merge it when you want, @GuardRex.

**Pull request merged**
