### PR TITLE
Remove empty .resx, Part 1

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Comment by NextTurn** [comment]
Nothing to do.

**Comment by NextTurn** [comment]
> ##[error]MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
##[error]MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
##[error]MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.

I didn't find anything wrong with these three project files.

> ##[error]D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\ExtraSnippets.vb(10,36): error BC30002: Type 'Workflow1' is not defined. [D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\WorkflowConsoleApplication1\WorkflowConsoleApplication1.vbproj]
##[error]D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\ExtraSnippets.vb(18,50): error BC30002: Type 'Workflow1' is not defined. [D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\WorkflowConsoleApplication1\WorkflowConsoleApplication1.vbproj]
##[error]D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\ExtraSnippets.vb(56,50): error BC30002: Type 'Workflow1' is not defined. [D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\WorkflowConsoleApplication1\WorkflowConsoleApplication1.vbproj]
##[error]D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\Module1.vb(24,50): error BC30002: Type 'Workflow1' is not defined. [D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_CFX\cfx_wf_gettingstarted\vb\WorkflowConsoleApplication1\WorkflowConsoleApplication1.vbproj]

I've no idea how to fix this. `Workflow1` should be generated based on `Workflow1.xaml`.

**Comment by BillWagner** [comment]
assigning to @adegeo for review.

I looked at the VBProj files as well, and I don't see anything invalid in the project files either.

**Comment by adegeo** [comment]
The items from `Workflow1` error are .NET Framework projects. The need to be converted or the `snippets.5000.json` settings file needs to be added to the project directory to have Visual Studio compile the project.

```json
{
    "host": "visualstudio"
}
```

The `MSB4025` error is from the SLN file it found in a parent directory is referencing a csharp project that doesn't exist. I would delete the SLN file.

**Comment by NextTurn** [comment]
> ##[error]C:\Program Files\dotnet\sdk\5.0.100-preview.6.20325.9\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v3.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [D:\a\docs\docs\samples\snippets\visualbasic\VS_Snippets_ADO.NET\DP LINQ to DataSet Examples\VB\LINQtoDataSetExamplesVB.vbproj]

@adegeo I've added *snippets.5000.json* in an earlier commit.

**Comment by NextTurn** [comment]
I've excluded the `Workflow1` project from this PR.

**Comment by adegeo** [comment]
@BillWagner Hrmmm the sln files deleted here are triggering the validation.

**Comment by BillWagner** [comment]
I'm going to propose that we call this case (deleting an sln) a known false positive and merge on a case-by-case basis.

In this PR, the deleted SLN isn't needed because these were single project solutions. Fixing this would introduce an issue where deleting an SLN with multiple projects won't trigger a build.

Thoughts @NextTurn @adegeo

**Comment by adegeo** [comment]
I'm fine with merging SLN deletion for now. We should add to the todo list for the projects tool these two new scenarios:

1. A deleted SLN file isn't reported.
2. When a SLN file is deleted, all projects under that folder structure are automatically reported for testing.

**Comment by BillWagner** [comment]
closing and reopening for a new CI build.

**Comment by BillWagner** [comment]
@adegeo We're still getting some build errors on the Visual Basic Workflow samples. 

I'll let you investigate.

**Comment by adegeo** [comment]
@NextTurn Can you fix the merge conflict? I'm going to accept this PR as is. After looking at it, the error is due to the lack of the snippets json file to force visual studio to build the projects. However, those folders aren't in good shape and need to be restructured (there are code files in the same folder as the sln) so I don't want these passing validation until that is addressed ina future PR.

**Review by adegeo — APPROVED** [review]

**Pull request merged**
