### PR TITLE
Adding Azure Service Fabric to modernization table

### PR DESCRIPTION
**Pull request by masnider**
Added Service Fabric to the modernize w/ containers table as it was missing. 

## Summary

Adding Azure Service Fabric to this guidance table based on functionality and customer experience.

Related to https://github.com/dotnet/docs/issues/15055

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=21258) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=21258) before we can accept your contribution.<br/><br/>:x: masnider [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=21258)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=21258) it.</sub>

**Comment by nishanil** [comment]
Thanks for the PR. Waiting on marketing approval.

**Comment by BillWagner** [comment]
Ping @nishanil for review and merging.

**Comment by nishanil** [comment]
cc @BethMassi

**Comment by BillWagner** [comment]
closing per editor.

**Pull request closed without merging**
