### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by dend**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by mairaw** [comment]
@dend selecting a different language on the API is not making the syntax switch the language.
e.g. https://review.docs.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.7.1&branch=pr-en-us-4689

**Comment by mairaw** [comment]
@dend I think we'll need to do a force build from the portal but I'm having issues. Can you try? The language switch is still not working for me.

**Comment by dend** [comment]
@mairaw I see that the languages now properly switch the samples, but I don't get the same behavior for signatures. Investigating.

**Comment by dend** [comment]
@mairaw kicked off a new forced build. Let's see what happens.

**Comment by mairaw** [comment]
@dend that was the behavior last week already. I'd do a full rebuild to make sure settings are applied and such but the portal is not letting me select branches on manual publish,

**Comment by mairaw** [comment]
> @mairaw kicked off a new forced build. Let's see what happens.
Cool. Thanks @dend!

**Comment by mairaw** [comment]
@dend build has finished but syntax still doesn't change when you select a different language 😢

**Comment by dend** [comment]
@mairaw following up on a separate internal thread to diagnose the root cause of the issue.

**Comment by mairaw** [comment]
@rpetrusha and I decided we were going to merge this since this solves a bunch of broken links and we'll see the behavior on production. Not having the switch working is no different than the current behavior.

**Review by mairaw — APPROVED** [review]

**Comment by dend** [comment]
@mairaw I see that there is still no change. I kicked off a force build on `master`. Otherwise, we'll need to escalate.

**Pull request merged**
