### PR TITLE
Followed coding conventions

### PR DESCRIPTION
**Pull request by Youssef1313**
"Use implicit typing for local variables when the type of the variable is obvious from the right side of the assignment"
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by BillWagner** [comment]
This current initialization does follow our coding conventions. The right hand side as `new Customer` makes its type clear. 

Closing this.

**Comment by Youssef1313** [comment]
> 
> 
> This current initialization does follow our coding conventions. The right hand side as `new Customer` makes its type clear.
> 
> Closing this.

from the coding conventions mentioned here:
"https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions"
It says:

> // When the type of a variable is clear from the context, use var in the declaration.

And as you said, **the right hand side makes the type clear**, and that's why I used var instead of Customer

**Comment by BillWagner** [comment]
@Youssef1313 I apologize. I read the diff backwards.  Thank you for pointing it out.

**Review by BillWagner — APPROVED** [review]
Thank you for making the fix, and for pointing out my earlier mistake @Youssef1313 

My :eyes: are failing me this morning.

I will :shipit: this now.

Again, I appreciate your understanding, and I apologize.

**Pull request merged**
