### PR TITLE
Fix rendering issues with ported base types topics

### LINKED ISSUE #217: Porting .NET MSDN docs to Core - Base Types
We need to port the relevant content from MSDN that applies to .NET Core.

The base types docs are still applicable to .NET Core. This is the starting point for base types:
https://msdn.microsoft.com/en-us/library/7wchwf6k(v=vs.110).aspx

### PR DESCRIPTION
**Pull request by stevehoag**
Previously reviewed; adding a few files at a time to try and isolate
issue. Fixes #217

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040)  
  Please see 5 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/grouping.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 162...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C19%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609192225331482-1040%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040)  
  Please see 5 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/customnumeric.md)...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201627477839-1040%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040)  
  Please see 5 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/quickref.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201647178299-1040%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040)  
  Please see 5 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201720054418-1040%5Cworkflow_report.html).

**Comment by stevehoag** [comment]
Sample build failed - closing and reopening to trigger another build.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1040)  
  Please see 5 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201738378882-1040%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/basicstringoperations?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/basicstringoperations?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/bestpractices?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/bestpractices?branch=pr-en-us-1040)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/bestpracticesstrings?branch=pr-en-us-1040](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/bestpracticesstrings?branch=pr-en-us-1040)  
  Please see 5 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/quickref.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201755020520-1040%5Cworkflow_report.html).

**Comment by stevehoag** [comment]
Failed when adding last batch of files (after index.md)

**Pull request closed without merging**
