### PR TITLE
erikre-docs-9315145

### PR DESCRIPTION
**Pull request by Erikre**
Adding video to tutorial content. @tdykstra - Please review.

### CODE REVIEW

**Review by tdykstra — COMMENTED** [review]
The video link isn't working in staging:  https://review.docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code?branch=pr-en-us-23116

**Comment by Erikre** [comment]
I have an updated video link. I'll add it.

**Review by tdykstra — COMMENTED** [review]
Still not working. Staging shows

```
> [!VIDEO https://www.microsoft.com/en-us/videoplayer/embed/RWyXba]
```

**Comment by Erikre** [comment]
@tdykstra - Fixed and ready to go. If you see any issues, let me know. Thanks

**Comment by tdykstra** [comment]
The video is well done but it's just a 34 second reading of the intro -- it doesn't go through the steps of the tutorial. I'm afraid most of those who would play the video would be disappointed, as the expectation would be the video would guide you through the tutorial.

**Comment by Erikre** [comment]
@tdykstra - Yes, I see your point. I can look into adding video steps using Camtasia and then integrating it into the video. If I am able to do this, I can then review it with you to see if it seems right for this content when it is complete. I'll go ahead and close this PR now.

**Pull request closed without merging**
