### PR TITLE
Update sn-exe-strong-name-tool.md

### LINKED ISSUE #9958: Inconsistent formatting of command line flags
**Issue description**

The [Sn.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool) docs have inconsistent formatting of the command line flags.

image

Looking around, this seems inconsistent through all the [.NET Framework Tools](https://docs.microsoft.com/en-us/dotnet/framework/tools/) docs. If the team can add what _should_ be the standard, I thought this might make a good 'first-contribution' issue. 🙂

### PR DESCRIPTION
**Pull request by leonpw**
Fix Inconsistent formatting of command line flags #9958

## Summary

Formatted -TS and -TSc command for the SN.exe tool.

Contributes to #9958

edit by @mairaw: removed the keyword fixes since the feedback was for the entire tools area

### CODE REVIEW

**Comment by Thraka** [comment]
@leonpw Thank you for opening this PR! We're glad to have you contribute to the docs!

However, we're actually moving away from theat `**-t** **value**` markdown style of parameter. We're moving to a pure inline code block that represents the whole parameter:

These are porting issues from the original documents on MSDN. We've standardized on using the code style for the whole parameter: \`-TS assembly container\`

Would you be willing to update all of the parameters with this style? If not, I can follow up and do it myself.

**Comment by leonpw** [comment]
Sure, I'll change the code style.

**Comment by leonpw** [comment]
Should be done now!

**Review by Thraka — APPROVED** [review]

**Comment by Thraka** [comment]
The markdownlint check crashed. I reran and it succeeded. The old crash is still listed for some reason.

**Pull request merged**
