### PR TITLE
Updates for the new dotnet/runtime repo

### PR DESCRIPTION
**Pull request by Youssef1313**
Contributes to #15982

### CODE REVIEW

**Comment by Youssef1313** [comment]
Can you review the current changes before I go with any further updates ?

**Review by tdykstra — COMMENTED** [review]
I don't know if it's premature to make these changes - I'll defer to @mairaw or @BillWagner

**Comment by Youssef1313** [comment]
@tdykstra, The repos are now completely empty. so it's required to update any links to those repos.

**Comment by Youssef1313** [comment]
I've removed the WIP to allow you to merge it for now until I get some time to work more on this issue.

**Review by tdykstra — APPROVED** [review]
@Youssef1313 Thanks for following up on this.

**Pull request merged**
