### PR TITLE
Update string.md

### PR DESCRIPTION
**Pull request by doctordns**
Added in some PowerShell samples.

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @doctordns. As we saw in the PowerShell thread, I think there's great demand for adding PowerShell examples to our docs. But I think the best place to add them would be the API reference docs like your wiki contributions did or articles that are not language specific like articles under the .NET Guide or .NET Framework guide. We can work with you to guide you on how we go about adding those.

I think adding PowerShell examples to the C# Guide doesn't seem the right approach. Thoughts @BillWagner @rpetrusha?

**Comment by rpetrusha** [comment]
@doctordns, we appreciate your opening this PR (and we enormously appreciate all the work that you had done in adding PowerShell examples to MSDN), but adding PowerShell examples to the C# reference doesn't seem like a good idea, nor are the examples likely to be noticed. We would welcome them in the [.NET API reference](https://docs.microsoft.com/en-us/dotnet/api/), if you would like to open PRs to contribute them there.
I'm going to close this PR. If you disagree, please respond to let us know. In the meantime, we look forward to your adding PowerShell examples to the API documentation.
//cc @BillWagner @mairaw

**Comment by doctordns** [comment]
Ron and all - I agree with this decision.

The new API documents use a different method of addign in samples. In some of the PowerShell documentation, examples/samples are inline - to add/update I'd just modify one page. But the examples I've looked at so far use a separate file to hold each sample, with the actual document just pointing to that sample.  If that's the way to go then let's try it!

Thanks for closing the RP/

**Comment by mairaw** [comment]
Let’s do one as an example so you can see how that would work @doctordns. I’m out for a few days and can help with that when I’m back. Or the guys can probably help you in the meantime.

**Comment by BillWagner** [comment]
As @mairaw says, we'll help with anything.  Thanks for all your contributions.

**Comment by doctordns** [comment]
Thanks guys for all the support. I really believe adding PowerShell examples into the API documentation is a good thing and am happy to help.

In looking at a 1st attempt, I see some bits of MarkDown I do not understand how to replicate for PowerShell. Can someone connect offline (DoctorDNS@Gmail.Com) where I can explain and get some answers rather than doing it here? Of course happy to do it in public on GitHub if you all feel that's better.

**Comment by rpetrusha** [comment]
@doctordns, I'll email you now.

**Pull request closed without merging**
