### PR TITLE
Fixed VB snippets mixup

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/docs/issues/2526, replaces https://github.com/dotnet/docs/pull/2525.

The commits in this PR are:

* Moving `index_1.vb` to `index_7.vb` snippets from `visual-basic/programming-guide/language-features/arrays` to `visual-basic/programming-guide/language-features/collection-initializers`.
* Fixing links in `visual-basic/programming-guide/language-features/arrays/index.md` after the move.
* Restoring  `index_1.vb` to `index_7.vb` snippets from `visual-basic/programming-guide/language-features/arrays` from [MSDN version of this article](https://msdn.microsoft.com/library/wak0wfyt(v=vs.100).aspx).

Since git doesn't handle moves well, it might be easier to review this commit by commit.

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @svick! We'll eventually remove the internal codesnippet folders. This was a bug on the migration tool that existed when we migrated the C# and VB content and we still haven't been able to fix it, but we're working on it.

They just did a new text export that had some issues, but I've modified the collection initializers topic there to what the topic should look like when the issue is fixed globally:
https://github.com/dotnet/docs/blob/migration_csharpvb_reexport/docs/visual-basic/programming-guide/language-features/collection-initializers/index.md

Do you want to bring the changes to that topic only into this PR? Or I can submit a new PR. Please let me know.

I'll take a look at the arrays topic now to see the issue with that one.

**Comment by mairaw** [comment]
And here you can see how I'd fix the arrays topic:
https://github.com/dotnet/docs/commit/e92033038798c075526da48f8c3b3e26065e43f3#diff-262759351589b1a4a2b5c5acdfb4e90c

The difficulty with this is that it has to be a data fix and not simply a global replace since a lot has changed since we've migrated the topics.

We could then remove the internal code snippet folders for those two topics. I'm happy to do a new PR to fix at least these two topics for now.

**Comment by svick** [comment]
@mairaw Done. Apart from the snippet changes, I also took VB comment fixes in the Array article from the reexport branch.

Also, I didn't delete the local snippets folders, because they are still used by subtopics of these two topics.

**Review by mairaw — APPROVED** [review]
@svick sounds good. We'll delete them once we do the whole data fix. thank you!

**Pull request merged**
