### PR TITLE
fix: MD027/no-multiple-space-blockquote

### PR DESCRIPTION
**Pull request by nschonni**
ultiple spaces after blockquote symbol.
```
Find:> \[!NOTE\]
> \s+
Replace:> [!NOTE]
> 
```

### CODE REVIEW

**Comment by BillWagner** [comment]
@nschonni I gave this a quick look this morning. Overall, it looks good.

Can you rebase to fix the conflicts? Once that's done, I can check the build report, and look at the review site to make sure it's ready to merge.  Thank you.

**Review by mairaw — CHANGES_REQUESTED** [review]
Marking as request changes based on @BillWagner's comments

**Comment by nschonni** [comment]
rebased and re-did the find/replace.
Note: there are others like this with different levels on indentation, so I didn't re-enable the rule yet.

**Review by BillWagner — APPROVED** [review]
Thanks @nschonni 

I did several spot checks on the review site,  in addition to spot checks on the source.

This LGTM, and I'll :shipit: now.

Thanks again for helping us work on improving our markdown.

**Comment by BillWagner** [comment]
@mairaw This LGTM. Can you approve and :shipit:?

**Review by mairaw — APPROVED** [review]
Just resolved some merge conflicts...

**Pull request merged**
