### PR TITLE
fix: MD022 space around headers

### PR DESCRIPTION
**Pull request by nschonni**
## Summary

Trying out the experimental --fix flag on the VB docs after enabling the MD022 rule. Actual diff was 2K documents for that folder so just added a small subset.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Looks good. Thanks @nschonni.

**Review by mairaw — CHANGES_REQUESTED** [review]
Argh, just noticed there are some merge conflicts. Can you fix those? Thanks.

**Comment by nschonni** [comment]
@mairaw I can fix this by re-running it, but do you want to fix the (whole) repo yourself now that the `--fix` option has landed in the published release of https://github.com/igorshubovych/markdownlint-cli
1. Run `npm install -g markdownlint-cli` to install the latest CLI
1. Remove the "MD022" line from the .markdownlint.json
1. Run `markdownlint --fix "**/*.md"`
1. Profit 💰

**Comment by mairaw** [comment]
Neat idea but I'm a bit on the fence if I really wanna do this global change like this. @dotnet/docs any thoughts?

**Comment by nschonni** [comment]
You can do it in pieces by changing the glob pattern too. EX: `markdownlint --fix "doc/visual-basic/**/*.md"` fave ~2K changes, and this PR was just staging and committing the first 100 files

**Comment by mairaw** [comment]
I get that and I usually submit global changes piecemeal. My point is more: I'll gladly review and accept PRs for this kind of change, but this is not a high priority for our team to go do it at this moment, given the size of our backlog. I hope it makes sense.

**Comment by nschonni** [comment]
@tdykstra this rule does affect rendering on GitHub, but AFAIK, docfx didn't tighten its rendering at the same time a year ago

**Comment by Thraka** [comment]
@nschonni Can you show an example; screenshot perhaps? I don't see any difference in rendering. :)

**Comment by nschonni** [comment]
Sorry, I think I'm mixing up the rule where the hash is stuck at the beginning of the heading. EX:
```md
##Not rendered as heading
```

**Comment by mairaw** [comment]
I think we've started adding them as part of the heading title. Let me see if I can find an example.

**Review by mairaw — APPROVED** [review]
Thanks @nschonni!

**Pull request merged**
