### PR TITLE
Fix mismatching count of -module switch options

### PR DESCRIPTION
**Pull request by jnm2**
Each time it says there are four or five options, it proceeds to list six options.

### CODE REVIEW

**Comment by BillWagner** [comment]
@jnm2 Thanks for spotting this and fixing it.

I looked at the changes, and they are all good. This PR now has conflicts with the base branch. Can you fix those, and then I'll approve this and :shipit:.

Thanks for contributing to docs! 🎆

**Comment by jnm2** [comment]
Oh my, looks like I didn't delete the master branch in my fork to prevent this from happening. I'm having trouble pushing, but I'll figure it out:

```
 ! [remote rejected]       mismatching_count -> mismatching_count (refusing to allow an OAuth App to create or update workflow `.github/workflows/bcnotify.yaml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/jnm2/dotnet-docs'
```

**Comment by jnm2** [comment]
Gave up and used the GitHub website to fix merge conflicts.

**Comment by jnm2** [comment]
Hey, why did dependabot just open 12 PRs in my fork to this PR branch?

https://github.com/jnm2/dotnet-docs/pulls

**Review by BillWagner — APPROVED** [review]
Thanks for the extra updates @jnm2 

I'll approve this, and :shipit: now.

**Comment by BillWagner** [comment]
> Hey, why did dependabot just open 12 PRs in my fork to this PR branch?

@jnm2 We've configured dependabot to help us keep our samples up to date. One of the packages we use in samples got updated yesterday.

There's a couple things we're doing to make this less of a concern:
- We're going to change the frequency that dependabot checks for updates. That should help most people with their forks (including us on the team).
- We've submitted some features requests to the dependabot team, including not opening PRs on forks. Those are under discussion by the team.

Thanks again for your help.

**Comment by jnm2** [comment]
That's great, thank you!

**Comment by jnm2** [comment]
@BillWagner Nothing happened for 18 days, then I got another wave of PRs two days ago, and then yet another wave a few hours ago. Would you recommend I delete my fork, or do you know of something I could do to preserve history while avoiding getting these dependabot PRs?

**Comment by BillWagner** [comment]
@jnm2 

You can safely delete this branch, `mismatching_count`, because this PR has been merged.

Then, to update your fork, I usually do the following:

```console
> git checkout master
> git fetch upstream 
> git rebase upstream/master
> git push
```

Those four commands do the following:
1. Switch to your local `master` branch.
1. Fetch all changes from `upstream`, which should be `dotnet/docs` (see note)
1. update your local master branch to match the upstream master
1. push your master branch to your fork on GitHub.

After that, you can create a new branch for any new work.

Note: If `upstream` isn't a valid remote, use the command `git remote -v`.  That command will list all the configured remotes. One should be yours (`jnm2/docs`), one should be the upstream remote (`dotnet/docs`)

Let us know if you have any further questions.

**Comment by jnm2** [comment]
@BillWagner I don't like to have a master branch in any of my forks because it has only ever been a confusing factor for me. (I started recommending this to others based on the number of times it confused them, too.) So my fork currently only has the branch `mismatching_count`, set as default.

Would having a forked master branch alleviate the problem though, or would that just catch me up to today and leave me open for dependabot to send more waves of PRs next week etc?

**Comment by BillWagner** [comment]
@jnm2 That's a different workflow than I use. It's certainly valid.

The concern is the same: your current default branch is out of date. I'd consider making a new branch for new work, starting from upstream/master. Or, if you want to reuse the mismatching_count branch, just rebase that one.

**Comment by jnm2** [comment]
Would that just catch me up to today and leave me open for more PR waves in the future?

**Comment by BillWagner** [comment]
> Would that just catch me up to today and leave me open for more PR waves in the future?

Yes, but there's no way around that. We're constantly working on updating and adding content.

**Comment by jnm2** [comment]
That's the part I want to prevent. Hmm, maybe if I set the default branch to `dependabot_bait` and had no files in it...

**Comment by jnm2** [comment]
Got 16 more PRs today, so I did this:

```
git checkout --orphan dependabot_bait
git rm --cached *
git commit --allow-empty -m 'Empty default branch to avoid waves of Dependabot PRs'
git push -u origin dependabot_bait
```

And then set the repo's default branch to `dependabot_bait`.

**Pull request merged**
