### PR TITLE
Update ebook-dapr-for-net-devs branch

### PR DESCRIPTION
**Pull request by amolenk**
Merges the latest master changes back into the Dapr e-book branch

### CODE REVIEW

**Comment by amolenk** [comment]
@IEvangelist @nishanil
 
I've created this PR to merge the master changes back into our ebook-dapr-for-net-devs branch.

It's currently in draft mode. I believe it will automatically add all the authors of the commits to the reviewers list. Any way to avoid that and still get our branch up to date with master?

**Comment by IEvangelist** [comment]
> @IEvangelist @nishanil
> 
> I've created this PR to merge the master changes back into our ebook-dapr-for-net-devs branch.
> 
> It's currently in draft mode. I believe it will automatically add all the authors of the commits to the reviewers list. Any way to avoid that and still get our branch up to date with master?

Hi @amolenk - Ah, I see the problem here.

I think the correct thing to do, is to rebase with master. So, locally you'd have both branches - `master` and `ebook-dapr-for-net-devs`. Then you'd switch to the master branch, pull the latest changes from upstream, switch back to the `ebook-dapr-for-net-devs` branch and perform a rebase command:

```git
git rebase master
```

This would avoid this chaotic merge and instead, correctly rebase the feature branch.

**Comment by amolenk** [comment]
@IEvangelist @nishanil 

Ah yes, that should work. Unfortunately, I don't have the rights to push to the `ebook-dap-for-net-devs` branch. 

Can either you or Nish perform the steps?

**Comment by IEvangelist** [comment]
> @IEvangelist David Pine FTE @nishanil Nish Anil FTE
> 
> Ah yes, that should work. Unfortunately, I don't have the rights to push to the `ebook-dap-for-net-devs` branch.
> 
> Can either you or Nish perform the steps?

Hi @amolenk - you do not need push rights, you could do a PR into the `ebook-dap-for-net-devs` branch that does the rebase.

**Comment by amolenk** [comment]
@IEvangelist not getting this to work :-( 

Here's what I tried:
- Synced fork with upstream (both the `master` and the `ebook-dapr-for-net-devs` branches.
- At this point, the forked branches are even with the upstream branches according to the GitHub UI.
- Then I rebase the `ebook-dapr-for-net-devs` branch: `git rebase master` (some conflicts come up, which I solve and then continue rebase)
- Now if I compare the rebased `ebook-dapr-for-net-devs` branch with the upstream one, GitHub shows me 5000+ changed files, which I really don’t understand.
- Comparing the rebased `ebook-dapr-for-net-devs` branch to the upstream `master` does only show the 39 actually changed files though.

**Pull request closed without merging**
