### PR TITLE
Re-add L2 nav header

### PR DESCRIPTION
**Pull request by mairaw**
Adam ended up merging my PR for the new L2. Creating the PR here for us to share a review link with others.

We can make further adjustments if needed.

### CODE REVIEW

**Comment by adegeo** [comment]
@mcleblanc fyi

**Comment by mcleblanc** [comment]
Implements the header as we proposed and this LGTM.

**Comment by BillWagner** [comment]
Adding an [internal review link](https://review.docs.microsoft.com/en-us/dotnet/?branch=pr-en-us-19663)

**Review by BillWagner — APPROVED** [review]
LGTM. I've approved, and you can :shipit: when ready.

**Pull request merged**
