### PR TITLE
move core brand suffix to docfx.json

### PR DESCRIPTION
**Pull request by mairaw**
This PR attempts to add .NET Core as a suffix for all the content under the core folder, except for the tools folder, which should have .NET Core CLI.

We might end up with a couple of redundancies where we'd have to override the suffix in the topic to remove it. But Carolyn suggested to leave the brand even in cases such as What's new in .NET Core 2.2 - .NET Core.

Thoughts?

Contributes to #9440

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
This approach of using global metadata makes a lot of sense, and produces much cleaner titles. I'll approve your PR, @mairaw.

**Comment by Thraka** [comment]
Personally I don't like this; I'm on the fence. It's convenient and nice to do it blankly across things, but I think it hides the fact that for a full title you have X characters for space and branding counts against that. Also, when designing a title, if you have to put the brand in, you know you have that product listed, so you don't need to repeat it in the title if you could safely omit it and still communicate intent properly.

**Comment by BillWagner** [comment]
@Thraka I actually like using the global or folder based changes as much as we can.  Things change, and this make is much easier to make those changes in one place.

Whether it's a brand name, the responsible author, or other values, the ability to update on a scale that fixes several files with one small edit is a win.

**Comment by mairaw** [comment]
The ordering seems to matter as well from the more global to the more specialized. So for example, if we don't want to add .NET Core to the what's new, I can probably add a blank suffix. I'll test that now.

**Comment by Thraka** [comment]
I had asked a question during the training session that didn't really get answered. Is the brand identifier still looked at for ranking even if it is off the page after the ... on a long title. 

If so, then it's useful to just have it on everything. I do know that the SEO validation will ding your article if it missing the - brand.

**Comment by mairaw** [comment]
Not sure. @cjgronlund can you help us here with that question?

**Comment by Thraka** [comment]
Why is `ms.custom: "seodec18"` being added or removed? I dont think we should alter that unless the article was hand edited for titles, h1, and description?

**Comment by BillWagner** [comment]
@Thraka if we add the titleSuffix through docfx.json, that changes the title for every article in the effected folder. So the tag should be added.

**Comment by mairaw** [comment]
We're impacting SEO for those pages that didn't have the brand before. For the ones where I'm just moving the brand to docfx.json instead of directly in the title, I'm not adding. Makes sense?

**Comment by mairaw** [comment]
I found a bug with the titlesuffix logic. I can't remove the suffix by setting it to empty. So I might be configure the changes a bit differently. 

See https://review.docs.microsoft.com/en-us/dotnet/core/get-started?branch=pr-en-us-9464&tabs=macos

Title is "Get started with .NET Core - "

**Pull request merged**
