### PR TITLE
Add remark to ICryptoTransform.TransformBlock

### LINKED ISSUE #1828: ICryptoTransform.TransformBlock does not mention that inputCount has to be a multiple of InputBlockSize
I think it's pretty important information, because the method throws exeption if the condition is not satisfied. The only place you can find out about it is in the [ICryptoTransform source](https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/ICryptoTransform.cs/#L29).

I wasn't able to locate the correct .md doccument with the docs, so that's why I'm not sending a PR (I assume this page is generated from the old docs).

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #1828 

Adds remark to `ICryptoTransform.TransformBlock`.

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
@GuardRex, LGTM, except that the build report is reporting invalid cross references: 
```
Invalid cross reference "&lt;xref:System.Security.Cryptography.I​Crypto​Transform.​Output​Block​Size%2A&gt;", "&lt;xref:System.Security.Cryptography.I​Crypto​Transform.​Can​Transform​Multiple​Blocks%2A&gt;", "&lt;xref:System.Security.Cryptography.ICrypto​Transform.​Input​Block​Size%2A&gt;".
```
Since this build result isn't reported here, I'll let you address them, close, and then reopen the PR.

**Comment by GuardRex** [comment]
@rpetrusha I can't detect the prob with those. They exist but surely don't care to transform into links ...

* [OutputBlockSize](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.icryptotransform.outputblocksize?view=netframework-4.7#System_Security_Cryptography_ICryptoTransform_OutputBlockSize)
* [CanTransformMultipleBlocks](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.icryptotransform.cantransformmultipleblocks?view=netframework-4.7#System_Security_Cryptography_ICryptoTransform_CanTransformMultipleBlocks)
* [InputBlockSize](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.icryptotransform.inputblocksize?view=netframework-4.7#System_Security_Cryptography_ICryptoTransform_InputBlockSize)

https://review.docs.microsoft.com/en-us/dotnet-new/api/system.security.cryptography.icryptotransform.transformblock?view=netframework-4.7&branch=pr-en-us-2096#System_Security_Cryptography_ICryptoTransform_TransformBlock_System_Byte___System_Int32_System_Int32_System_Byte___System_Int32_

**Comment by rpetrusha** [comment]
@GuardRex, I think that I would try removing %2A and see if the links resolve. If that fails, then probably bold them as a short-term fix, and we'll open a bug. It also seems to me that I've seen this issue elsewhere.

**Comment by GuardRex** [comment]
@rpetrusha Tried that already. No 🎲 🎲 .

How about I open internally for investigation (APEX SiteHelp) while we have the review page handy. That might be good for them to see ... so they don't think I'm nuts. lol

**Comment by rpetrusha** [comment]
@GuardRex, that sounds like a plan.

**Comment by GuardRex** [comment]
## DO NOT MERGE

Build issue under investigation. TFS: 991477

**Comment by GuardRex** [comment]
@rpetrusha Interesting! I found offensive characters in the file when I opened it in good 'ole Notepad that VSC wasn't revealing to me. I guesstimate a cut-and-paste disaster happened here. We're already aware that the BOM can enter these files when saved out of some text editors in UTF8. VSC doesn't reveal those either. This might have been something similar ... I cut-and-paste from a UTF source with the chars present and they landed in the file ... well ... either that or :alien:!!! Latest commit removes "%2A" as well. If this builds out ok, I'll merge it.

capture

**Pull request merged**
