### PR TITLE
Metadata updates

### PR DESCRIPTION
**Pull request by tompratt-AQ**
# Title
Update metadata for migrated content.

## Summary
Updated metadata by making the following changes:

- In docs/csharp, replaced all instances of (author: stevehoag, ms.author: shoag) with (author: BillWagner, ms.author: wiwagn).
- In docs/visual-basic, replaced all instances of (author: stevehoag, ms.author: shoag) with (author: dotnet-bot, ms.author: dotnetcontent).
- In docs/framework, replaced all instances of (ms.prod: ".net-framework-4.6") with (ms.prod: ".net"), and (author: stevehoag, ms.author: shoag) with (author: dotnet-bot, ms.author: dotnetcontent).
- In docs/standard, replaced all instances of (ms.prod: ".net-framework-4.6") with (ms.prod: ".net"), ms.technology: "<whatever_value>") with (ms.technology: dotnet-standard), and (author: stevehoag, ms.author: shoag) with (author: dotnet-bot, ms.author: dotnetcontent).

## Suggested Reviewers
@rpetrusha

### CODE REVIEW

**Comment by tompratt-AQ** [comment]
@rpetrusha Did I try and do too much with this PR?  If you think I should cancel it and submit smaller PR's for each subdirectory, I can do that. Since I'm touching so many files here - there will inevitably be merge conflicts. However, since I'm only changing the metadata, they should be easy conflicts to fix.

**Comment by rpetrusha** [comment]
@tompratt-AQ, let me review the PR in a little bit and decide. As long as you're comfortable with the merge conflicts, it should be OK -- though there's a potential for a huge number of merge conflicts.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
This looks really good, @tompratt-AQ. I just approved it, so it's ready to merge. Hopefully, the merge conflicts will be manageable.

**Comment by tompratt-AQ** [comment]
Only 50 or so merge conflicts and they were fairly manageable ones. I did have some trouble pushing the changes, though, so I've got my fingers crossed that this fixed them all.

**Pull request merged**
