### PR TITLE
Remove incorrect indentation from remarks

### PR DESCRIPTION
**Pull request by svick**
This PR removes one leading space from all lines that have them in CDATA blocks in API reference.

The code used to generate it is [here](https://github.com/svick/ApiReferenceCleanup/blob/fix-lists/Program.cs).

This PR is one possible solution to https://github.com/dotnet/docs/issues/1951, and is meant for discussion.

### CODE REVIEW

**Comment by mairaw** [comment]
@dend @wh-alice @yishengjin1413 what do you guys thing? I've also noticed the extra spacing on the migrated conceptual topics as well.

/cc @BillWagner @rpetrusha

**Comment by mairaw** [comment]
And BTW @svick, thank you so much for doing this! I'll wait for the build to finish to see the results. But you've got some conflicts to resolve since there was a big change on reference that got merged last night.

**Comment by svick** [comment]
@mairaw You're welcome. I've rerun the code on top of the current master. I expect more conflicts will appear over time, so I'll rerun it again when and if it's agreed to do it this way.

**Comment by mairaw** [comment]
We'd like to merge this @svick but again we have merge conflicts. Do you mind running on top of master again? Thanks!

**Comment by svick** [comment]
@mairaw Done.

**Comment by svick** [comment]
I just figured out that this incorrectly changes code blocks, so don't merge it yet. E.g. here is part of the diff for xml/Microsoft.CSharp/CSharpCodeProvider.xml (the changes at the start and end are correct, the changes to the xml code block are not):

````diff
 ## Examples  
- The following configuration file example demonstrates how to specify that version 3.5 of the C# code provider should be used.  
-  
+The following configuration file example demonstrates how to specify that version 3.5 of the C# code provider should be used.  
+ 
 ```  
 <configuration>  
-  <system.codedom>  
-    <compilers>  
-      <!-- zero or more compiler elements -->  
-      <compiler  
-        language="c#;cs;csharp"  
-        extension=".cs"  
-        type="Microsoft.CSharp.CSharpCodeProvider, System,   
-          Version=2.0.3600.0, Culture=neutral,   
-          PublicKeyToken=b77a5c561934e089"  
-        compilerOptions="/optimize"  
-        warningLevel="1" >  
-          <providerOption  
-            name="CompilerVersion"  
-            value="v3.5" />  
-      </compiler>  
-    </compilers>  
-  </system.codedom>  
+ <system.codedom>  
+   <compilers>  
+     <!-- zero or more compiler elements -->  
+     <compiler  
+       language="c#;cs;csharp"  
+       extension=".cs"  
+       type="Microsoft.CSharp.CSharpCodeProvider, System,   
+         Version=2.0.3600.0, Culture=neutral,   
+         PublicKeyToken=b77a5c561934e089"  
+       compilerOptions="/optimize"  
+       warningLevel="1" >  
+         <providerOption  
+           name="CompilerVersion"  
+           value="v3.5" />  
+     </compiler>  
+   </compilers>  
+ </system.codedom>  
 </configuration>  
 ```  
-  
- The following example shows how to specify the compiler version when you create a new instance of the <xref:Microsoft.CSharp.CSharpCodeProvider> class.  
-  
- [!code-csharp[CSProvider.ProviderOptions#1](~/samples/snippets/csharp/VS_Snippets_CLR/csprovider.provideroptions/cs/program.cs#1)]  
-  
+ 
+The following example shows how to specify the compiler version when you create a new instance of the <xref:Microsoft.CSharp.CSharpCodeProvider> class.  
+ 
+[!code-csharp[CSPr
````

**Comment by svick** [comment]
@mairaw Fixed, code blocks should now be correct.

**Pull request closed without merging**
