### PR TITLE
CLI updates for preview 6 - Part 2

### LINKED ISSUE #7146: Push multiple package is not supprted
It appears that NuGet currently not support pushing multiple packages by using a glob pattern. Don't know if this is a bug or intentional. `dotnet nuget push *.nupkg` should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-core**
* GitHub Login: @karann-msft
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #7146 
Contributes to #9893

### CODE REVIEW

**Comment by mairaw** [comment]
@@karann-msft please review!

**Comment by karann-msft** [comment]
@mairaw - we don't need to change the `dotnet nuget push *.nupkg` 
see https://github.com/dotnet/docs/issues/7146#issuecomment-506918400

**Review by BillWagner — APPROVED** [review]
This LGTM @mairaw 

You can :shipit: now.

**Comment by karann-msft** [comment]
Please see my comments on the related issue. The current doc is accurate.

**Comment by mairaw** [comment]
@karann-msft added the note. Does it look good to you?

**Comment by karann-msft** [comment]
lgtm 🚢

**Pull request merged**
