### PR TITLE
reviewed for FY23 freshness

### PR DESCRIPTION
**Pull request by alexwolfmsft**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by CamSoper — COMMENTED** [review]
Looks fine, but we should check one thing...

@IEvangelist -- I thought there was a place to specify the author for an entire folder. I can't seem to find it. Am I hallucinating?

**Comment by IEvangelist** [comment]
> Looks fine, but we should check one thing...
> 
> @IEvangelist -- I thought there was a place to specify the author for an entire folder. I can't seem to find it. Am I hallucinating?

You're not hallucinating, it can be done with the _docfx.json_ file, [see `fileMetadata`](https://github.com/dotnet/docs/blob/main/docfx.json#L172). You can specify each desired metadata value there, in fact Alex is already set as [`author`](https://github.com/dotnet/docs/blob/main/docfx.json#L295). Using the Metadata Explorer that @gewarren and I wrote, you can see this value in place.

image

Ideally, we'd remove the explicit `author` and `ms.author` values from each article and declaratively update the _docfx.json_.

**Comment by alexwolfmsft** [comment]
Thanks @IEvangelist I remember this now from a long time ago. I removed all of the individual file updates for the author and adjusted the docfx file.

**Review by CamSoper — APPROVED** [review]
Thank you, @IEvangelist! 

Looks good to me, @alexwolfmsft!

**Pull request merged**
