### PR TITLE
fix: Underscore astoria snippet paths

### PR DESCRIPTION
**Pull request by nschonni**
I'll be submitted https://github.com/dotnet/samples/pull/810 in the samples repo to match

### CODE REVIEW

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
@nschonni, the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C11%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201904112122566148-11784%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9EW0zJ%2Fh%2BYOjTx5UQSyd2e9ZqoNN%2F5j7lQe4TAMQjkY%3D&st=2019-04-11T21%3A21%3A59Z&se=2019-05-12T21%3A26%3A59Z&sp=r) shows 19 warnings because of unresolved code references.

**Comment by nschonni** [comment]
Looks like I missed some under "xml", I only renamed them under visualbasic and csharp. Not sure about the few csharp ones that are still erroring

**Comment by mairaw** [comment]
Starting a new build...

**Comment by mairaw** [comment]
6 more warnings...

**Comment by nschonni** [comment]
@mairaw thanks for fixing those up, I was just checking again to see if it was the samples again, but it looks like I messed up a a find/replace somewhere

**Review by mairaw — APPROVED** [review]
It's good now. Thanks @nschonni!

**Pull request merged**
