### PR TITLE
Fixed links in samples

### PR DESCRIPTION
**Pull request by svick**

### CODE REVIEW

**Comment by svick** [comment]
Some of the links go to docs.microsoft.com, some are relative links inside the repo. Should they be consistent?

**Comment by BillWagner** [comment]
@svick Thanks for fixing these. It looks great. Merging now.

I just wrote Issue #756 to track finding absolute links where relative links would be appropriate. We should standardize on relative links.

cc @mairaw : Can you add the guidance to use relative links to the current PR for the contributing guide (PR #668?)

**Comment by mairaw** [comment]
I missed this question earlier, but I'll add. Thanks @BillWagner!

**Pull request merged**
