### PR TITLE
Revised thread pool topics

### PR DESCRIPTION
**Pull request by pkulikov**
This PR deletes duplicate thread pool topics (which are partly outdated) from the language-specific guides:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/thread-pooling
https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/threading/thread-pooling  

That makes the thread pool topic in the .NET Guide main one about the thread pool in the conceptual docs:
https://docs.microsoft.com/en-us/dotnet/standard/threading/the-managed-thread-pool

That topic is revised as well:
- reordered sections
- removed code examples, as the related API pages contain either the same or better code examples.

Contributes to #6180

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for doing this @pkulikov 

I'll approve this PR, but I'll let @rpetrusha take a look before :shipit:.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thank you so much for continuing to work on consolidating the threading docs, @pkulikov. You've done a really fine job with these topics. I do have a number of comments and suggestions.

**Comment by pkulikov** [comment]
@rpetrusha thank you for review; I've addressed all your feedback.

**Review by rpetrusha — APPROVED** [review]
Thanks, @pkulikov, for making the additional set of changes. I'll merge your PR now.

**Pull request merged**
