### PR TITLE
Add missing alt text

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
The text under images is inconsistent. 
There are 3 different styles there:
1. As a quote with bold **Figure x-y.**
image

2. Normal text
image

3. Normal text with bold **Figure x-y.**
image

I can update them to be consistent, but which style should I use ?

**Comment by mairaw** [comment]
Thanks for your attention to detail @Youssef1313. I think the one used by https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles is better (option 3).

**Comment by Youssef1313** [comment]
> 
> 
> Thanks for your attention to detail @Youssef1313. I think the one used by https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles is better (option 3).

@mairaw, I've updated the files to use that third option.

**Review by rpetrusha — APPROVED** [review]
Thank you, @Youssef1313, for adding missing alt text and standardizing the presentation of images. I'll merge your PR now.

**Pull request merged**
