### PR TITLE
fixing GH alias

### PR DESCRIPTION
**Pull request by mairaw**
/cc @bleroy

I'm adding myself as the ms.author so I get the incoming feedback and so forth. let me know if you disagree with that.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/preview3/tutorials/index.md](https://github.com/dotnet/docs/blob/mairaw-patch-1/docs/core/preview3/tutorials/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/index?branch=pr-en-us-1260) | [Details](#user-content-docs/core/preview3/tutorials/index.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C17%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611170254373977-1260%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/preview3/tutorials/index.md](https://github.com/dotnet/docs/blob/mairaw-patch-1/docs/core/preview3/tutorials/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/index?branch=pr-en-us-1260) | [Details](#user-content-docs/core/preview3/tutorials/index.md)
[docs/core/preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/mairaw-patch-1/docs/core/preview3/tutorials/using-on-windows-vs-2017.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/using-on-windows-vs-2017?branch=pr-en-us-1260) | [Details](#user-content-docs/core/preview3/tutorials/using-on-windows-vs-2017.md)



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C17%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611170301195118-1260%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/preview3/tutorials/index.md](https://github.com/dotnet/docs/blob/mairaw-patch-1/docs/core/preview3/tutorials/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/index?branch=pr-en-us-1260) | [Details](#user-content-docs/core/preview3/tutorials/index.md)
[docs/core/preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/mairaw-patch-1/docs/core/preview3/tutorials/using-on-windows-vs-2017.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/using-on-windows-vs-2017?branch=pr-en-us-1260) | [Details](#user-content-docs/core/preview3/tutorials/using-on-windows-vs-2017.md)
[docs/toc.md](https://github.com/dotnet/docs/blob/mairaw-patch-1/docs/toc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/toc.json?branch=pr-en-us-1260) | [Details](#user-content-docs/toc.md)




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C17%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611170338147852-1260%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
Merging this to unlock builds from master.

**Pull request merged**
