### PR TITLE
Redirect add-ins URLs to previous-versions

### PR DESCRIPTION
**Pull request by rpetrusha**
## Redirect add-ins URLs to previous-versions

This PR:

- Removes three add-in extensibility topics from our documentation set.
- Deletes the node from the main TOC.
- Redirects requests to the archived content for .NET 4.
- Incidentally, replaces a surfeit of tokens in the WPF documentation with their text.

//cc @karelz @danmosemsft

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
System.Addin docs will still be available, right? Just not in the front and center set of docs.

**Review by BillWagner — APPROVED** [review]
This LGTM @rpetrusha 

You can :shipit: when ready.

**Comment by rpetrusha** [comment]
Yes, @danmosemsft. it continues to be available in https:\\docs.microsoft.com\previous-versions

**Comment by mairaw** [comment]
But they're no longer going to be crawled/indexed by search engines, if that's ok.

**Pull request merged**
