### PR TITLE
Fix snippets workflow for latest preview sdk

### PR DESCRIPTION
**Pull request by adegeo**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]

**Review by BillWagner — APPROVED** [review]
This LGTM.

Verified by building #29526

**Review by salifs — COMMENTED** [review]
GFJDHJDJHZS4EERGHGGGDGSSRSRRZRSRTAE56EREZE

**Comment by salifs** [comment]
ERJJZYEYEYTYZTZTTTEZZGSRRSR1GGAZ.DKKIRTIUUDEQZQDDZ4

**Comment by salifs** [comment]
****343JU44Y

### **_`rrnfjdajuzu"éu"i"iieezzerezzzeezjrjur`_**
TLLLLRLRLTTOYTT @jye578 EZKRK'o'o(o'é @salifs rkkrkske
r

**Comment by salifs** [comment]
GHRDDZEDDD
RRARMGLH
GMHMHMHMH`

**Comment by salifs** [comment]
Screenshot_20220613-220606

**Comment by salifs** [comment]
@tfosma
Huhhgv

**Pull request merged**
