### PR TITLE
fixed toc entry

### PR DESCRIPTION
**Pull request by mairaw**
Fixing dupe TOC entry for https://docs.microsoft.com/en-us/dotnet/framework/app-domains/application-domains

### CODE REVIEW

**Review by jzeferino — APPROVED** [review]
This LGTM, but I think that `use.md` should have a better name, like `using-application-domains.md`.

**Review by rpetrusha — APPROVED** [review]
LGTM. You can merge this when ready, @mairaw.
Completely unrelated to your PR, though, is that the TOC is very poorly organized -- you'd expect all app domain and all assembly topics to be together, but they're not. I think that we should address this eventually -- do you want to open an issue, or should I?

**Comment by mairaw** [comment]
Thanks @rpetrusha. Just opened an issue: #4415.  

@jzeferino yeah, we could have added that, but the full url (https://docs.microsoft.com/en-us/dotnet/framework/app-domains/use) has the word app domain in there, so I don't feel so strongly about changing that. But let me know otherwise.

**Comment by jzeferino** [comment]
I understand your point @mairaw but there are already others .md with the word app domain like `application-domains-and-assemblies-how-to-topics.md`. Anyway its ok for me.

**Comment by mairaw** [comment]
I know @jzeferino. 😢 When we migrated the content over, we didn't have too much time to do a full URL review. There are a lot of URLs that don't follow our guidelines. We'll fix those over time as appropriate.

**Pull request merged**
