### PR TITLE
Collapse relative links in standard/

### PR DESCRIPTION
**Pull request by nxtn**
Contributes to #10653

@IEvangelist It looks like this just removes a bunch of `./`.

### CODE REVIEW

**Comment by IEvangelist** [comment]
> @IEvangelist It looks like this just removes a bunch of `./`.

Hi @NextTurn - you're right... I have a fix in for that and let's see if this change will make this [experience better](https://github.com/microsoft/vscode-docs-authoring/pull/603).

You can close this PR as it doesn't really add value. Thank you for your patience and understanding :pray:

**Comment by NextTurn** [comment]
It's OK @IEvangelist. It's fun to see something evolve. 🚀

I'll refresh this PR after the extension is updated.

**Comment by NextTurn** [comment]
@IEvangelist I found something new for you! See the image links in the second commit.

**Comment by IEvangelist** [comment]
> @IEvangelist I found something new for you! See the image links in the second commit.

Awesome... Did the tool handle the image links?

**Comment by NextTurn** [comment]
> Did the tool handle the image links?

No. I guess it's because the tool checked file existence but the image title isn't part of the path.

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Comment by IEvangelist** [comment]
> > Did the tool handle the image links?
> 
> No. I guess it was because the tool checked file existence but the image title isn't part of the path.

Hmmm, I guess we'll have to update our TypeScript `RegExp` to catpure those too. It should handle any markdown link. Thanks for calling attention to that.

**Comment by NextTurn** [comment]
@IEvangelist You didn't squash and merge this. Did the team change the branch ~~policy~~ conventions?

**Comment by IEvangelist** [comment]
> @IEvangelist You didn't squash and merge this. Did the team change the merge ~policy~ conventions?

I noticed that too, not the end of the world - it was supposed to be squashed... but it's early Monday morning for me and the coffee is still brewing. Not a big deal, but thanks for keeping me honest. :)

**Pull request merged**
