### PR TITLE
Standardize sample projects, Part 1

### PR DESCRIPTION
**Pull request by nxtn**
This series aims to touch all project files and find existing problems.

---

Upgrades `<TargetFramework>` to `netcoreapp3.1` in *.csproj*.

### CODE REVIEW

**Comment by NextTurn** [comment]
How do deal with projects that demonstrate compile errors?

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Comment by NextTurn** [comment]
Done.

>  ##[error]D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\src\NativeHost\NativeHost.csproj(44,5): error MSB3073: The command "cl.exe nativehost.cpp /I "C:\Program Files\dotnet\packs/Microsoft.NETCore.App.Host.win-x64/3.1.5/runtimes/win-x64/native" /I inc /D WINDOWS /EHsc /Od /GS /sdl /Zi /Fo"D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\bin/Debug\\" /Fd"D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\bin/Debug\nativehost.pdb" /link "C:\Program Files\dotnet\packs/Microsoft.NETCore.App.Host.win-x64/3.1.5/runtimes/win-x64/native\nethost.lib" /out:"D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\bin/Debug\nativehost.exe"" exited with code 9009.
##[error]D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\src\NativeHost\NativeHost.csproj(44,5): error MSB3073: The command "cl.exe nativehost.cpp /I "C:\Program Files\dotnet\packs/Microsoft.NETCore.App.Host.win-x64/3.1.5/runtimes/win-x64/native" /I inc /D WINDOWS /EHsc /Od /GS /sdl /Zi /Fo"D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\bin/Debug\\" /Fd"D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\bin/Debug\nativehost.pdb" /link "C:\Program Files\dotnet\packs/Microsoft.NETCore.App.Host.win-x64/3.1.5/runtimes/win-x64/native\nethost.lib" /out:"D:\a\docs\docs\samples\snippets\core\tutorials\netcore-hosting\csharp\HostWithHostFxr\bin/Debug\nativehost.exe"" exited with code 9009.

This requires "Developer Command Prompt"/"Developer PowerShell".

> ##[error]😕 Too many projects found. A single project or solution must existing in this directory or one of the parent directories.
##[error]😕 Too many projects found. A single project or solution must existing in this directory or one of the parent directories.

These two projects have explicit `Remove=` and `Include=`.

> ##[error]D:\a\docs\docs\samples\snippets\desktop-guide\wpf\data-binding-overview\DataBindingOverview.sln : Solution file error MSB5004: The solution file has two projects named "bindings".

Handled in Part 2.

**Comment by IEvangelist** [comment]
> How do we deal with projects that demonstrate compile errors?
> 
> https://github.com/dotnet/docs/blob/db79624a588849a42027deb0d3e1a15b7fa71cda/samples/snippets/csharp/roslyn-sdk/Tutorials/MakeConstTestProject/MakeConstTestProject/Program.cs#L13
> 
> https://github.com/dotnet/docs/blob/db79624a588849a42027deb0d3e1a15b7fa71cda/samples/snippets/csharp/tutorials/attributes/Program.cs#L128

That's a really good question. The **Snippets 5000 &trade;** build validator doesn't filter those out yet, and I'm not sure the best way to do so. I suppose, we could label PRs that have intentional compiler errors... and then ignore those. Or maybe it's better to embed these snippets into the docs, and remove them from the source code itself.

Curious what @BillWagner and @adegeo think?

**Comment by BillWagner** [comment]
We've discussed two different plans for code that doesn't compile by design. I've logged #19265 to continue and resolve that discussion.

**Comment by BillWagner** [comment]
I'm also good with the progress here.  I'll :shipit:

**Comment by NextTurn** [comment]
@IEvangelist @BillWagner Do you have any suggestions to make the *cl.exe* commands succeed?

**Comment by adegeo** [comment]
Tomorrow I'll be looking at writing a config file that can be included with a project to control the build environment (choose VS Build over .NET Core build among other things)

**Pull request merged**
