### PR TITLE
[2.0] CLI command 2.0 updates

### LINKED ISSUE #1780: [2.0] Revert note on regression of CLI for dotnet run "-p" option
Note added with https://github.com/dotnet/docs/pull/1779

> It can be a path to a [csproj](csproj.md) file or to a directory containing a [csproj](csproj.md) file

### LINKED ISSUE #2139: [2.0] Create CLI command preview topics
Follow the repo TOC structure when creating the topics in the *preview* folder.

### LINKED ISSUE #2388: CLI commands topics: Can these be improved?
This started as a discussion with @mairaw on Slack pertaining to the CLI command docs.

* Dashes in command names are 😖 very confusing.
* Do our definitions of "arguments," "options," and "parameters" make sense in light of commonly-used definitions of these terms? (i.e., Should we organize the sections of these docs a bit differently?)

## Dashes in command names (e.g., "dotnet-restore" vs. "dotnet restore")

I was informed that this was done to follow the way that Git shows its commands, but dashes in commands aren't used anywhere: They aren't shown this way in topics outside of the command topics. They aren't described this way among devs in chat rooms. They don't appear this way in GH issue/PR discussions. *Most importantly*, they aren't used this way on the command line. The result of having dashes in the commands is only one thing imo: *confusing.* Is there support for removing the dashes from commands in the CLI command docs?

## "Arguments," "options," and "parameters" 

Conventional definitions AFAICT are:

* **Argument:** *Anything* after the command. I think it's fair to say that anything separated by a space after invoking the command is "an argument." I didn't think of this at the time I was discussing with @mairaw on Slack, but later it occurred to me that `public static void Main(string[] args)` means exactly this is the case. It's just a string array of whatever is fed into the app.
* **Option:** Modifies a command. Might be a "required option" or an "optional option." Often requires a parameter to supply additional information to the option.
* **Parameter:** Anything that provides information to a command or option.

Currently, we're doing this ...

* Name
* Synopsis
* Description
* Arguments (which are more explicitly "command parameters" AFAICT)
* Options (These are actually also "arguments," sometimes with parameters and sometimes without them. Since they're "arguments," it doesn't make much sense to show them under a 2nd level heading along side our "Arguments" section, which is also a 2nd level heading in the topics.)
* Examples

There are a few options (pardon the pun :grinning:) that would potentially improve things here:

### Bring "arguments" in line with current definitions by re-labeling them "Command parameters," which is probably what they really are.

* Name
* Synopsis
* Description
* Command parameters
* Options
* Examples

### Since "command parameters" and "options" are all arguments, they could all fall under the "Arguments" heading.

* Name
* Synopsis
* Description
* Arguments
  - Command parameters
  - Options
* Examples

### Since options are easily split into *required* and *optional* categories, they can be split out. This would be helpful to devs to know which ones are absolutely required versus those are are truly optional.

* Name
* Synopsis
* Description
* Arguments
  - Command parameters
  - Required options
  - Optional options
* Examples

### Examples

To show a few examples of how the last two scenarios would look, here's sample layout for `dotnet publish`:

* Arguments
   - Command parameters
      * `PROJECT`
   - Required options
      * None
   -  Optional options
      * `-c|--configuration <CONFIGURATION>`
      * `-f|--framework <FRAMEWORK>`
      * `-h|--help`
      * `--manifest <MANIFEST_FILE>`
      * `-o|--output <OUTPUT_DIRECTORY>`
      * `-r|--runtime <RUNTIME_IDENTIFIER>`
      * `--self-contained [<true|false>]`
      * `-v|--verbosity <LEVEL>`
      * `--version-suffix <VERSION_SUFFIX>`

For `dotnet store` ...

* Arguments
   - Command parameters
      * None
   - Required options
      * `-f|--framework <FRAMEWORK>`
      * `-m|--manifest <MANIFEST_FILE>`
      * `-r|--runtime <RUNTIME_IDENTIFIER>`
    - Optional options
      * `--framework-version <FRAMEWORK_VERSION>`
      * `-h|--help`
      * `-o|--output <OUTPUT_DIRECTORY>`
      * `--skip-optimization`
      * `--skip-symbols`
      * `-v|--verbosity <LEVEL>`
      * `--working-dir <INTERMEDIATE_WORKING_DIRECTORY>`

## Empty (or "None") sections shown

There's a tendency to not show a heading when no entries exist under it (i.e., the section heading is just left out of the topic); however, I think that's unhelpful in this case. I understand well the concept of "economy" in technical documentation, but anything can be taken too far, and I think this is one of those cases. If there are no command parameters, or no required options, or no optional options, nothing makes it more clear than going ahead and showing the section with the entry of "None." For example ...

* Arguments
  - Command parameters
    * Parameter1
    * Parameter2
  - Required options
    * None
  - Optional options
    * Option1
    * Option2

## Thoughts on changes?

I made one (probably) helpful change for the 2.0 round of updates to alphabetize the options. Are there opportunities here to make further improvements?

### LINKED ISSUE #2405: [2.0] New content for templating: Create custom templates for dotnet new
Title: *Create custom templates for dotnet new*
Area: *docs/core/tools*

Reference
* [How to create your own templates for dotnet new](https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/)
* [dotnet/templating Wiki](https://github.com/dotnet/templating/wiki)

### LINKED ISSUE #2461: Inaccurate documentation for PackageReference tag
# Inaccurate documentation for PackageReference tag

# General

[Version](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md#version) element of PackageReference is described as "respects the rules of the [NuGet versioning scheme](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges)", but in fact if you supply Version="1.0" the behavior is as though it's version="[1.0]" for NuGet, that is even if 1.1 is available, `dotnet restore` command will install `1.0`.

# Steps to reproduce
```bash
mkdir test
cd test
dotnet new console
$EDITOR test.csproj
# Add the following section to the file
# <ItemGroup>
#     <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.3" />
# </ItemGroup>

dotnet restore
grep -A3 Jwt obj/project.assets.json
# the output will indicate the version 5.1.3 is chosen even though there's version 5.1.4 of this library
```

### LINKED ISSUE #2479: Make it clear when the changes for csproj was introduced
Topic: https://docs.microsoft.com/en-us/dotnet/core/tools/cli-msbuild-architecture

LiveFyre comment indicates that the topic doesn't make a good job of letting users know when the change happened and which version of VS/tooling they can get the "new" behavior.

### PR DESCRIPTION
**Pull request by guardrex**
**WIP** Hold review for final checks and touch-ups.
**BLOCKED** until new content is merged.

Fixes #1780
Fixes #2388

As @cartermp stated, there weren't a large number of updates for command deltas. However ...

* There were many *guidelines-adherence* problems to address.
* Passive voice required significant updates.
* "Command x is a 'convenient way' of doing y." language only made sense relative to hand-editing project files, so those instances were converted to simply "Command x does y."
* Some of the examples were updated: Instead of only showing a single section of a project file to illustrate a command's effect, the entire console app project file is shown, which seems to provide a better frame of reference for the change produced by the command. This change didn't add much length to those docs.
* Some additional cross-reference links are added, sometimes added to external resources that devs will likely find helpful.
* In addition to adding new 2.0 options, options are alphabetized. This makes it easier to track down an option with commands that have many options.
* *Dashes removed from CLI commands!* Thank the :pray: server gods :pray:!
* I moved the macOS/Linux coverage above the Windows coverage in the `dotnet install scripts` command seeking parity between showing the Windows-way first and showing the macOS/Linux-way first.
* Reverts regression content for `dotnet run`.
* I cleaned up tables and lists.
* 😅

### CODE REVIEW

**Comment by GuardRex** [comment]
Note: I'm fixing little TOC issues on my next review pass. I see 'um, and I'll work on them on my next round of updates.

**Comment by GuardRex** [comment]
Leaving this on **WIP** until https://github.com/dotnet/docs/pull/2493, https://github.com/dotnet/docs/pull/2494, https://github.com/dotnet/docs/pull/2495, and https://github.com/dotnet/docs/pull/2496 go in.

blood
*There Will Be Blood*, &copy; 2007 [Paramount](http://www.paramount.com/movies/there-will-be-blood)/[Miramax](https://www.miramax.com/movie/there-will-be-blood/)

**Comment by guardrex** [comment]
@mairaw It doesn't look too bad ... In the vast majority of cases here, it looks like it takes the master change. Would u like me to make a quick conflicts pass and see how it goes?

**Comment by mairaw** [comment]
@guardrex If it's not a problem for you, sure!

**Comment by guardrex** [comment]
Sure ... I'll be free in 30 minutes after dinner. 🍗 I run thru and ping u back.

**Comment by guardrex** [comment]
@mairaw Didn't work out. Many conflicts were easy to fix. Others were 😵. The main prob was simply that when I did this I alphabetized the options, which does work and prob is helpful on the ones that have a rather long list of them ... then you did tabs ... and GH had a near meltdown trying to figure out what goes where. I think you should close this. There were some phrasing updates here and there but nothing all that pressing.

**Comment by mairaw** [comment]
No problem. Do you want to grab your non-CLI commands updates and send them on a new PR then?

**Comment by guardrex** [comment]
@mairaw I'm not going to have time in the foreseeable future ... food ain't free and rent ain't cheap! lol ... I have to work and make some money, so my time is somewhat limited. I don't think there was much there really. I think it was mostly just minor grammar and guidelines touch-ups, and I think those changes only applied to two topics. I'm going to go ahead and close this one down.

**Pull request closed without merging**
