### PR TITLE
Fix xml Blocks

### LINKED ISSUE #8125: Broken syntax block
A lot of articles in this section such as https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/tracking-of-wcf have broken syntax blocks.

Others also have typos like missing closing ">" such as https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/nettcpbinding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec96ac8-bd4a-a946-339f-6ec48c0952f0
* Version Independent ID: 22fdf757-11e7-99c4-2311-66ec5d556db7
* Content: [&lt;system.serviceModel&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/system-servicemodel)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/system-servicemodel.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/system-servicemodel.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### PR DESCRIPTION
**Pull request by msschl**
## Summary

Contributes to #8125

Fixes #8125

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thank you so much for addressing #8125 and fixing the broken XML syntax blocks. Your changes look really good, except that the two spaces at the end of a line in a fenced code block are not necessary. If it is easy for you to revert those changes, we'd appreciate it. If not, we'll merge your PR as is.

**Comment by msschl** [comment]
@rpetrusha I think this is all :-)

**Comment by NextTurn** [comment]
There are more broken XML code blocks in #9744 .

You could also fix them if you are interested.

**Comment by msschl** [comment]
Sure, I'll take a look. :-)

**Comment by NextTurn** [comment]
Would you like to share your codes used to fix there code blocks? I was about to write them.

**Comment by msschl** [comment]
@NextTurn See https://gist.github.com/msschl/fdfc2b5f4e1ab5ae9d4429849d2bd894

I used this to remove all the spaces at the end of a line inside a xml code block. All other XML formatting was done by hand. But I wanted to start working on a littel tool to format the xml code blocks inside a markdown file :)

**Comment by NextTurn** [comment]
Thanks for your hard work!

I am going to develop such a tool after fixing that issue so that it won't be blocked by the exceptions.

**Comment by NextTurn** [comment]
As for the spaces, they are everywhere so you don't need to be limited to code blocks.

See #9755

**Comment by msschl** [comment]
Oh ok, thanks that's good to know.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
