### PR TITLE
Adding scenario-based modifications to scaling sections

### PR DESCRIPTION
**Pull request by ardalis**
Also pulled the book title out of the descriptions.

### CODE REVIEW

**Comment by ardalis** [comment]
This should hopefully be good to merge, @nishanil

**Comment by nishanil** [comment]
@ardalis This file `scale-containers-serverless` has gone unlinked. Can you fix this asap? I think, this should be after "Other deployment options". Fix Prev and Next links too.

**Comment by nishanil** [comment]
Fix all figure numbers. There's an issue with Figure 1-13. Image isn't rendering and I can't find the images before this one.

**Comment by ardalis** [comment]
> Fix all figure numbers. There's an issue with Figure 3-13. Image isn't rendering and I can't find the images before this one i.e. 3-10 to 3-13?

Fixed. Renumbered. The one you referenced was this one: Cold versus warm start
**Figure 3-10**. Monolithic architecture.

which looks fine to me. Did it not render because it's a jpg not a png?

**Comment by nishanil** [comment]
@ardalis Yeah, that one isn't rendering on the review site. It seems to be working locally.

**Review by nishanil — APPROVED** [review]
I'll go ahead and merge this. We will check the missing image issue again after the merge.

**Pull request merged**
