### PR TITLE
Change Library to library

### PR DESCRIPTION
**Pull request by badersur**
Above **Debugging your application** section, there is:

> You'll need to add a couple using directives to the top of the file:
> 
> ``` c#
> using static System.Console;
> using Library;
> ```

Maybe using should be formatted: `using`?

And inside the section:

> You can debug your code in VS Code using the C# extension. You install this extension by pressing `F1` to open the VS Code palette. Type `ext install` to see the list of extensions. Select the `C#` extension.

Maybe the 2<sup>nd</sup> C# shouldn't be formatted?

cc: @bleroy

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos?branch=pr-en-us-1072](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos?branch=pr-en-us-1072)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C24%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609241624227902-1072%5Cworkflow_report.html).

**Review by stevehoag — APPROVED** [review]
Thanks for catching this!

**Comment by mairaw** [comment]
Thanks @badersur. The change LGTM.

> Maybe using should be formatted: using?

Yes, the using statement should be formatted as inline code. 

> Maybe the 2nd C# shouldn't be formatted?
I think it's ok either way.

Do you want to make those changes too? Otherwise, I can take care of that for you.

**Comment by badersur** [comment]
I'll submit the changes; removing the 2nd `C#`

**Comment by badersur** [comment]
You are welcome @stevehoag & @mairaw :)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos?branch=pr-en-us-1072](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos?branch=pr-en-us-1072)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C26%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609261810552550-1072%5Cworkflow_report.html).

**Comment by mairaw** [comment]
One of the CI builds has failed. I'll close and reopen this issue.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos?branch=pr-en-us-1072](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos?branch=pr-en-us-1072)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C3%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610032237165843-1072%5Cworkflow_report.html).

**Pull request merged**
