### PR TITLE
Update pointer-types.md

### PR DESCRIPTION
**Pull request by ghost**
Link not working.

Can I use ~ to reference the root directory?

We would get: (~/samples/snippets/csharp/keywords/FixedKeywordExamples.cs#5)
instead of
(../../../../samples/snippets/csharp/keywords/FixedKeywordExamples.cs#5)

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks, @johnnyagerard, for correcting the link. Yes, the correct way to link to a file in the samples repo is with ~. So  (~/samples/snippets/csharp/keywords/FixedKeywordExamples.cs#5) should work.

**Comment by johnnyagerard** [comment]
@rpetrusha I'm not sure I understood you correctly. Is this correct now?

**Comment by pkulikov** [comment]
@johnnyagerard what makes you think that the link is broken? The published version contains the referenced snippet from the samples repo.

Though I agree that `~` syntax looks better than a lot of dots.

**Comment by johnnyagerard** [comment]
@pkulikov Well, I wanted to edit this example actually. So I clicked "edit" in the upper right corner which brings me here: [Pointer types (C# Programming Guide)](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/unsafe-code-pointers/pointer-types.md).

And when I click on "[!code-csharpUsing pointer types]", I get a page not found.

**Comment by pkulikov** [comment]
That's because the snippet is at another repo, not this one.

**Pull request closed without merging**
