### PR TITLE
Testing with no-loc md extension syntax

### PR DESCRIPTION
**Pull request by JasonCard**
## Summary

Testing with no-loc md extension syntax as discussed in [https://github.com/dotnet/docs/pull/15689](https://github.com/dotnet/docs/pull/15689).

@mairaw could you please help to review and merge?

### CODE REVIEW

**Comment by mairaw** [comment]
That didn't work
https://review.docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings?branch=pr-en-us-16079

image

**Comment by JasonCard** [comment]
Thanks to suggestion from OPS team, I tested the suggested syntax and it seems to work now: [https://review.docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings?branch=pr-en-us-16079](https://review.docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings?branch=pr-en-us-16079)

**Comment by tdykstra** [comment]
@JasonCard Since this is a test PR and the testing is done, can we close it?  This issue #15689 remains open for applying these changes to all relevant articles.

**Comment by JasonCard** [comment]
Yes, thank you for the reminder and closing it now.

**Pull request closed without merging**
