### PR TITLE
update zone pivot group yaml mime header

### PR DESCRIPTION
**Pull request by jdanyow**
workaround for a bug in the localization pipeline
https://ceapex.visualstudio.com/Engineering/_workitems/edit/167502

### CODE REVIEW

**Comment by Thraka** [comment]
@jdanyow 

Did someone in the org approve this? We were guided to this specific format, including the `# GitHub repository = 'dotnet/docs'` line which you removed.

Additionally, why are we implementing workarounds instead of fixing the problem in the loc pipeline?

**Comment by jdanyow** [comment]
@Thraka we hit this bug in the localization once before, back in December. When we discovered it I created [a work item for the localization team](https://ceapex.visualstudio.com/Engineering/_workitems/edit/156212). Until they've fixed the underlying issue, we need to normalize the yaml mime header in the content (this PR).

Who advised you to add `# GitHub repository = 'dotnet/docs'`? I do not know what that comment is for. It's not something we're using in Docs build or templating afaik.

**Comment by Thraka** [comment]
@jdanyow Internal link: https://mseng.visualstudio.com/TechnicalContent/_wiki/wikis/Applied_AI_Docs_Wiki/11711/Zone-Pivots

This was (is still?) the guidance I used and it had that header in there.

**Comment by bodhigautam** [comment]
@Thraka We have a plan to accommodate the # YamlMime syntax in the loc pipeline in future. 
Besides ### YamlMime is not a workaround, its a valid syntax being used across many repos for example [learn-pr](https://github.com/MicrosoftDocs/learn-pr/blob/master/learn-pr/zone-pivot-groups.yml#L1) , [azure-docs-pr](https://github.com/MicrosoftDocs/azure-docs-pr/blob/live/articles/mariadb/index.yml#L1) etc. 
Why we don't need repository name is because then it will be bound to a locale. For example here if we use # GitHub repository = 'dotnet/docs' then the zone pivots of 'dotnet/docs' will only be considered. On loc someone will have to manually add the locales like dotnet/docs.de-de , dotnet/docs.ja-jp which is not optimal for an automated loc pipeline. Hence its advised to not keep the repo names in the content files. cc @jdanyow

**Review by Thraka — APPROVED** [review]

**Pull request merged**
