### PR TITLE
Revised C# Visual Studio getting started for .NET Core 2.0

### PR DESCRIPTION
**Pull request by rpetrusha**
# Revised C# Visual Studio getting started for .NET Core 2.0

## Summary
1. Moved getting started tutorials from csharp/getting-started folder to core/tutorials folder
2. Revised coding, debugging, and publishing topics for .NET Core 2.0.
3. Modified C# code slightly to use an interpolated string rather than a composite format string, necessitating new screen captures.
4. Checked screen shots for accuracy.

## Remarks
I've labeled this a work in progress, since I'm going to add a VB coding topic and revise the debugging and publishing topics to cover both VB and C#. The latter two topics will use tabs.

## Suggested Reviewers
@BillWagner @mairaw

### CODE REVIEW

**Comment by rpetrusha** [comment]
@BillWagner, @mairaw, @AnthonyDGreen, this is ready for review. I've revised the C# Hello World app/debugging/publishing topics, and added a VB app topic. The debugging and publishing topics cover both C# and VB. (Hopefully, I've gotten the tab syntax right, and tabs work as I'm expecting them to.)

**Review by BillWagner — CHANGES_REQUESTED** [review]
@rpetrusha Overall, this LGTM.  

I do see a few OPS build warnings on the files changed in this PR. Once those are fixed, let's :shipit:

**Comment by rpetrusha** [comment]
Thanks, @BillWagner. I've fixed the broken links.

**Review by BillWagner — APPROVED** [review]

**Comment by mairaw** [comment]
I've just resolved some merge conflicts. Please take a look.

**Comment by mairaw** [comment]
Now I forgot the name of the feature in VS that shows the references and stuff, but at one point I remember @Rick-Anderson saying we should turn that off for screenshots.

**Comment by Rick-Anderson** [comment]
It's called code lens and you should turn it off. Folks with community edition don't have it and are confused. 

Tool > Options 
search for code lens
image

uncheck it
image

**Pull request merged**
