### PR TITLE
CC56863 Changing Link location

### PR DESCRIPTION
**Pull request by gosali**
Hello, @maira,
This proposed file change comes from https://github.com/dotnet/docs.ru-ru/pull/75/files?utf8=%E2%9C%93&diff=split&w=1 . 
Line #98

Could you review this contribution and help to merge if agreed?
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
If you change the location, you also have to change the preceding text. Instead of image above on line 96, it should be following image @gosali.

**Comment by gosali** [comment]
@mairaw Thank you a lot for your reply. But I'm confused, Should I makefurther changes?
@carolinacmoravia 
BR

**Comment by mairaw** [comment]
@gosali we can't accept this as-is. So please change the following sentence:
"You can see this relationship in the image above." to
"You can see this relationship in the following image."

You just have to click the pencil on the [files view](https://github.com/dotnet/docs/pull/5531/files):
image

**Comment by carolinacmoravia** [comment]
Hello, @gosali, 
You'll need to make a new commit with the change requested by @mairaw. 
Thanks in advance for your support. :)

**Comment by gosali** [comment]
@mairaw  Please see the last commit and help to merge.
Thank you a lot!

**Review by mairaw — APPROVED** [review]
Thanks for making the requested changes @gosali.

**Pull request merged**
