### PR TITLE
Update implement-value-objects.md

### PR DESCRIPTION
**Pull request by vkhorikov**
Additional reference for the base value object class.

### CODE REVIEW

**Comment by IEvangelist** [comment]
Hi @vkhorikov - I cannot accept this PR. While this implementation of a Value Object seems like a good one, the following reasons are standing in the way:

- The site that it links to immediately starts pushing for subscription, and sign up
- The implementation differs nearly entirely from the one covered in the article, thus deemphasizing it's relevancy dramatically

I would be okay with adding a link to the source code itself, like some of the other examples there?

**Comment by vkhorikov** [comment]
> The implementation differs nearly entirely from the one covered in the article, thus deemphasizing it's relevancy dramatically

Do you mean the difference between the article and the [implementation in the CSharpFunctionalExtensions library](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ValueObject/ValueObject.cs#L62)? I wouldn't say it's drastically different. Over the years, there were added some minor improvements, such as:

* Check for lazy loaded proxies
* Hash code caching
* `IComparable` implementation in base class

But fair enough, a link to https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ValueObject/ValueObject.cs#L62 is good too.

> But I'd want it listed under the one the others as they take precedence based on relevancy -- is that fair, and does that make sense?

How is it less relevant? AFAIK, eShopOnContainers's version was merged years after the article and it's not as complete as the version from CSharpFunctionalExtensions (e.g. it doesn't have `IComparable` implementation).

**Comment by IEvangelist** [comment]
> How is it less relevant? AFAIK, eShopOnContainers's version was merged years after the article and it's not as complete as the version from CSharpFunctionalExtensions (e.g. it doesn't have `IComparable` implementation).

The article is part of eShopOnContainers's, the implementation exists in eShopOnContainers's, your implementation is not - though it is more complete, and probably better. It might make sense to have PR into the eShopOnContainers's repo and propose updating the impl to more closely align with yours -- what do you think?

**Comment by vkhorikov** [comment]
Ok, I see what you mean. The ordering doesn't matter (to me), feel free to put it where it makes the most sense. Though, could you make the link https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ValueObject/ValueObject.cs (without the reference to a specific line)? I'll be moving the `ValueObject<T>` version to a separate file, the fact that both version live in the same file has been the source of confusion. I can make an update to this PR if you'd like.

**Comment by IEvangelist** [comment]
> Ok, I see what you mean. The ordering doesn't matter (to me), feel free to put it where it makes the most sense. Though, could you make the link https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ValueObject/ValueObject.cs (without the reference to a specific line)? I'll be moving the `ValueObject<T>` version to a separate file, the fact that both version live in the same file has been the source of confusion. I can make an update to this PR if you'd like.

Yes, please update the PR. Thank you

**Comment by vkhorikov** [comment]
@IEvangelist Updated the PR. Please take a look.

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Comment by vkhorikov** [comment]
Thanks much!

**Pull request merged**
