### PR TITLE
Collection Types

### PR DESCRIPTION
**Pull request by stevehoag**
Fixed missing title

### CODE REVIEW

**Comment by mairaw** [comment]
I'd review all of your collection topics to make sure the generic parameter is showing up correctly

**Comment by stevehoag** [comment]
So I'm not following - given a link label like `[List<T>]`, how would I format this so that the `<T>` shows up?

**Comment by mairaw** [comment]
Like this [List\<T\>](http://link)

**Comment by mairaw** [comment]
with backslash

**Comment by stevehoag** [comment]
That isn't working for me (using VS Code). If I enter `[List\<T\>] `it renders as `[List\]`'

**Comment by mairaw** [comment]
@cartermp do you have any suggestions on how to fix this?

**Comment by stevehoag** [comment]
Maybe we shouldn't be using brackets at all. The .NET conceptual docs on MSDN use parentheses instead of brackets, even though reference docs use the brackets. Does anyone know the history behind this?

**Comment by cartermp** [comment]
Unsure how to handle this w.r.t how DocFX will render it.

**Comment by mairaw** [comment]
The conceptual docs will use parentheses if you have VB selected. If you change your page to C#, it will show the brackets. Since we only have C# now, we should show brackets until they create a way for us to use a tag to reference to APIs by using their AssetID or something.

**Comment by mairaw** [comment]
@chenkennt do you know how we can render brackets with docfx?

**Comment by stevehoag** [comment]
Okay, that's really strange behavior. Unless the topic includes a code block there is no way to change the language setting, so the page rendering depends on whatever language you were last viewing. I guess that really only matters for those of us that use both languages, but I could see where it might confuse customers as well.

**Comment by mairaw** [comment]
Yep, I noticed that too.

**Comment by stevehoag** [comment]
Canceled; fixed in new branch

**Pull request closed without merging**
