### PR TITLE
Correct typo

### LINKED ISSUE #11866: path typo in add reference command line and xml
"dotnet add reference ../../NewTypes/NewTypes.csproj"

should be "dotnet add reference ../../src/NewTypes/NewTypes.csproj"

same issue in xml part, but it is correct in xml of NewTypesTests.csproj 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b54562-9072-a864-be3d-44ed7965c798
* Version Independent ID: a69ec985-ed05-90dd-a686-dc956b0cf5df
* Content: [Organizing and testing projects with the .NET Core command line - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli#feedback)
* Content Source: [docs/core/tutorials/testing-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes #11866

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @mikkelbu. Let me check if this is the only change needed. As I'm reading this section (https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli#testing-the-sample), it seems that this wouldn't be the only change needed to fix this article.

**Comment by Thraka** [comment]
@mairaw I don't see what you're seeing. Can you point it out?

**Comment by mairaw** [comment]
I think the flow of the steps might be wrong. I'll need to go through the whole thing to confirm.

**Comment by Thraka** [comment]
@mairaw I just looked through this again and it seems correct. The steps for creating the `test` and `NewTypesTests` folders are sort of jammed in a paragraph right before the create a new test project step. 

I think we can merge this PR.

**Review by Thraka — APPROVED** [review]
Looks good. I read through the whole article and all of the paths match up. Thanks!

**Pull request merged**
