### PR TITLE
C53994: "|" is breaking formatting

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @cartermp, @mairaw,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by cartermp — CHANGES_REQUESTED** [review]
This change turns the symbol into raw HTML:
image

**Comment by mairaw** [comment]
This is not a source issue but a translation issue so I'll be closing. FYI @JasonCard @nokura 

See how the translated version doesn't contain the first backtick and is using a single quote instead:
image

I've opened https://github.com/dotnet/docs.pt-br/pull/98 to fix this for pt-br as an example.

**Comment by JasonCard** [comment]
@mairaw I also looked into this and it appears to be MD transformer issue rather than source issue. I'll follow up on this bug and agree for this PR to be closed. cc @v-makoud @nokura

**Comment by v-maudel** [comment]
Thanks @mairaw and @JasonCard

**Pull request closed without merging**
