### PR TITLE
Move e-books to its own folder and section

### LINKED ISSUE #9233: Defining "Standard" content
I was looking at some of the content that is now in the "standard" directory. The original intent of that directory was to define the most basic and timeless aspects of .NET that are meaningful for any .NET implementation. Implementation-specific content would go into the "core" and "framework" directories, for example. Or scenario specific content would go in the "machinelearning" directory, for example. I think that vision remains a good one.

These directories give me pause. Let's discuss.

- https://github.com/dotnet/docs/tree/master/docs/standard/containerized-lifecycle-architecture
- https://github.com/dotnet/docs/tree/master/docs/standard/microservices-architecture
- https://github.com/dotnet/docs/tree/master/docs/standard/modern-web-apps-azure-architecture
- https://github.com/dotnet/docs/tree/master/docs/standard/modernize-with-azure-and-containers
- https://github.com/dotnet/docs/tree/master/docs/standard/serverless-architecture

cc @mairaw @CESARDELATORRE

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #9233

### CODE REVIEW

**Comment by mairaw** [comment]
This is ready to review @nishanil @CESARDELATORRE @BillWagner 

Here's what was done:
1. The TOC now has an entry for the architecture guides. You can see in the following page:
https://review.docs.microsoft.com/en-us/dotnet/welcome?branch=pr-en-us-12804
2. I've created a new landing page for the architecture guides
https://review.docs.microsoft.com/en-us/dotnet/architecture/?branch=pr-en-us-12804
3. I've renamed the folder paths as shown in the following tables. Please let me know what you think.

| Old path | New path |
| containerized-lifecycle-architecture | containerized-lifecycle |
| microservices-architecture | microservices |
| modern-web-apps-azure-architecture | modern-web-apps-azure|
| modernize-with-azure-and-containers | modernize-azure-containers |
| serverless-architecture | serverless |

In most cases, I just removed the architecture from the folder name to avoid introducing a new SEO issue in our content about duplicate words in the URL: https://review.docs.microsoft.com/en-us/new-hope/quality/catstestcases/seo-rule?branch=master#url-structure---duplicated-words
For the other, I've removed what would be considered unnecessary words.

Still marked as WIP so we don't merge accidentally. I need to coordinate with our engineering team to make the redirects via the back end.

**Comment by nishanil** [comment]
@mairaw Quick qn:
I tried to navigate from dot.net website, then to docs and I landed on this page below: 
https://review.docs.microsoft.com/en-us/dotnet/?branch=pr-en-us-12804 
We don't have a path from there. Maybe we can add a section there too?
```
.NET Application Architecture Guides
 - Ebooks 
```
Other changes look good to me.

**Review by BillWagner — APPROVED** [review]
This LGTM @mairaw 

Once everyone is happy and the redirects are configured, you can :shipit:

**Comment by BillWagner** [comment]
@mairaw There is also one conflict to fix.

**Pull request merged**
