### PR TITLE
Add NET to preprocessor symbols

### LINKED ISSUE #21520: Missing "NET symbol
Section: `How to specify a target framework`
Last paragraph: `The complete list of preprocessor symbols for .NET target frameworks is:`

Symbol `NET` is missing in the table for .NET 5 Target framework. Only `NET5_0` is present.

`NET` is listed in See section / [Target framework names in .NET 5](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md) document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
## Summary

Add missing `NET` preprocessor symbol.

Fixes #21520

### CODE REVIEW

**Comment by gewarren** [comment]
I only see that `NET` is defined as a preprocessor symbol, not as a TFM. Am I missing something @adegeo?

**Review by jeffhandley — APPROVED** [review]
This looks right to me. @sfoslund, could you confirm too please?

**Review by sfoslund — APPROVED** [review]
Yes this is right. 

@jeffhandley FYI with .NET 6 this will change again, this spec shows the updated symbols that will be available: https://github.com/dotnet/designs/blob/be793b557255c9ed1276ecdd23119b64f45453bf/accepted/2020/or-greater-defines/or-greater-defines.md#doc-changes

**Comment by pavel-mikula-sonarsource** [comment]
Hi @sfoslund, should the design page you mentioned be updated not to loose the `NET` symbol later? This detail seems easy to miss.

**Comment by sfoslund** [comment]
That doc assumes we're keeping all symbols that it doesn't mention, it's only focused on adding the _OR_GREATER symbols.

**Pull request merged**
