### PR TITLE
Use https instead of http for links

### PR DESCRIPTION
**Pull request by nemrism**
Also contributes to #4504

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
This is a hard PR to review and includes a lot of changes that we probably shouln't make like the namespaces used in code. One thing you could do when doing this kind of work is to use regular expressions in VS Code to detect http links after [ or \<, for example. I also pasted in issue #4504 a spreadsheet with the offending links from our report. I'll try to run it again to see if I get different results after a few fixes.

**Comment by nemrism** [comment]
Hi @mairaw
Don't review it for the moment, I'll have a look and rollback changes linked to namespaces  before pushing back this PR to you.
It might be much simpler to review without those changes.

**Comment by nemrism** [comment]
Ready for review with some fixes and less impacts @mairaw

**Comment by mairaw** [comment]
Thank you @nemrism. I'll get started on this review now.

**Review by mairaw — APPROVED** [review]
Thanks @nemrism for all these changes. They look great!

@mvelosop - this PR touches on a number of e-book articles that were not using https links.

**Comment by nemrism** [comment]
Good to see this latest version did not need any change! \o/

**Pull request merged**
