### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by tdykstra**

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for spotting this and fixing it @tdykstra 

You can :shipit: anytime.

**Comment by tdykstra** [comment]
Looks like I no longer have permissions to this repo, I'm not getting a merge button.

**Comment by BillWagner** [comment]
I merged it. We can fix the other problem, if you want.

**Comment by tdykstra** [comment]
Yes, let's fix it, thanks.

**Comment by BillWagner** [comment]
Done.

**Pull request merged**
