### PR TITLE
Update package explorer screenshot

### LINKED ISSUE #18778: Screen Shot update needed / enhanced diagnostics
NuGet Package Explorer now shows more information about Source Link status. We should probably update the screen shot and possibly mention something about the different states (no sourcelink, contains untracked sources).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db5ae44-5ee9-ed62-7355-7c0cbc1bfc07
* Version Independent ID: f54c98e2-bbae-42c6-2103-e94d6ec0e931
* Content: [Source Link and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
* Content Source: [docs/standard/library-guidance/sourcelink.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/sourcelink.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

Update package explorer screenshot

Fixes #18778

### Preview

✔️ [Source Link](https://review.docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink?branch=pr-en-us-18792)

### CODE REVIEW

**Comment by gewarren** [comment]
How come it has a red theme?

**Comment by IEvangelist** [comment]
> How come it has a red theme?

That's my windows theme. That shouldn't be a problem, right?

**Comment by gewarren** [comment]
> > How come it has a red theme?
> 
> That's my windows theme. That shouldn't be a problem, right?

Screenshots should use the default theme - https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-create-screenshot?branch=master#create-screenshots.

**Review by gewarren — APPROVED** [review]
Looks better, thanks!

**Pull request merged**
