### PR TITLE
[WIP] CI Update

### PR DESCRIPTION
**Pull request by dend**
Re-run the CI with the latest version of `mdoc`

### CODE REVIEW

**Comment by dend** [comment]
@mairaw @rpetrusha @cartermp can you please check the PR? This should cover a lot of changes from the Blockers bucket, and the OPS build is now successful.

**Comment by BillWagner** [comment]
Here's the link to [the internal review site](https://review.docs.microsoft.com/en-us/dotnet/api/index?branch=pr-en-us-4017)

**Comment by cartermp** [comment]
The language selectors don't seem to work on the staging site, so I can't look at signatures for F# as it would appear on the site.

**Comment by dend** [comment]
@mairaw @BillWagner ignore the VSTS failures. The branch did not yet pick up the updated script, therefore for this PR we will skip sample validation.

**Comment by dend** [comment]
@mairaw the build error was an intermittent issue.

**Comment by dend** [comment]
@mairaw @BillWagner @rpetrusha any movement on this PR? :)

**Comment by mairaw** [comment]
@dend we're waiting on @adkinn's fix, no?

**Comment by dend** [comment]
@mairaw yes, but even before that I want to make sure that there are no other content/quality issues 💯 

Can you please confirm that other than @adkinn's fix, this PR is good?

**Comment by mairaw** [comment]
That was the only issue I found. I can try to squeeze another test but I'd like others to take a look too.

**Comment by mairaw** [comment]
@dend we should resolve the merge conflict here and I noticed after checking docs-internal CI job that the number of warnings have increased a lot with this change (from 70 to 306 warnings).
They look like the following:
"Model "W:\0u0m-o-a7210ed5\raw-\vk15bxrk.24j\viewmodel\api\System.Windows.Controls.ContextMenuService.Placement.html.raw.json" is transformed to empty string with template "ManagedReference.html.primary""

Do you know what this warning is about and how we can solve it?

Thanks!

**Comment by dend** [comment]
@mairaw I believe @TianqiZhang and @adkinn can help with the warnings issue, since it seems to be a template one.

**Comment by mairaw** [comment]
@dend @adkinn @TianqiZhang build has failed with an error. Who can take a look?

**Comment by dend** [comment]
@mairaw build is successful. Can we merge?

**Comment by mairaw** [comment]
We need to look at the duplicate warnings that are in the build report @dend

**Comment by mairaw** [comment]
@dend I made a new commit to remove the duplicates and merged the master branch to make sure we had the latest version and no conflicts. I'll start testing the last built version.

@rpetrusha @BillWagner @JRAlexander @cartermp please help test this.

**Comment by mairaw** [comment]
@dend I'm still seeing the F# signatures here. Weren't we removing them in order to merge this PR?

**Comment by dend** [comment]
@mairaw waiting for the next CI to complete - once done, the F# signatures will be removed and this PR can be merged.

**Comment by dend** [comment]
Closing this PR to make sure we re-run with latest changes.

**Pull request closed without merging**
