### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by lemonez**
fix a few typos

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/07d8bc4ef7298161d7046fd5a8cd72bb31ee2764/docs/csharp/language-reference/operators/member-access-operators.md) | [Member access operators and expressions - the dot, indexer, and invocation operators.](https://review.learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators?branch=pr-en-us-37253) |
| [docs/csharp/programming-guide/classes-and-structs/using-properties.md](https://github.com/dotnet/docs/blob/07d8bc4ef7298161d7046fd5a8cd72bb31ee2764/docs/csharp/programming-guide/classes-and-structs/using-properties.md) | ["Using Properties - C# Programming Guide"](https://review.learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties?branch=pr-en-us-37253) |

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for spotting these and submitting the fix @lemonez 

These changes look great, and I'll :shipit: now.

You should see the changes on the live site in the next day or two, on our regular publishing cycle.

**Comment by lemonez** [comment]
@microsoft-github-policy-service agree

**Comment by BillWagner** [comment]
closing and reopening to ping the CLA bot again.

**Comment by BillWagner** [comment]
@lemonez 

For dotnet docs, it's a different CLA bot ID. It should be "dotnet-policy-service".

Sorry about that.

> @microsoft-github-policy-service agree

**Comment by lemonez** [comment]
@dotnet-policy-service agree

**Pull request merged**
