### PR TITLE
Clarify nesting of config switch

### PR DESCRIPTION
**Pull request by gewarren**
Related to #27713.

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
LGTM, Thanks!

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

Let's :shipit:

**Comment by filipnavara** [comment]
Why was ImageSharp removed from the recommendations? There's no explanation in the commit info or in the PR.

**Comment by tarekgh** [comment]
CC @richlander for the question https://github.com/dotnet/docs/pull/31509#issuecomment-1336190476.

**Comment by terrajobst** [comment]
@filipnavara 

There is a follow up regarding this policy here: https://github.com/dotnet/docs/issues/32861

**Comment by terrajobst** [comment]
We have provided a rationale in the corresponding PR in dotnet-api-docs: https://github.com/dotnet/dotnet-api-docs/pull/8577

**Comment by terrajobst** [comment]
Locking this thread as the discussing should be happening in any of the linked conversations above. Thanks!

**Pull request merged**
