### PR TITLE
Edits to improve SEO and usability

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
## Summary

- Metadata title
- Text edits for readability and style guide
- Link text
- Alt text for accessibility

Fixes [611305](https://dev.azure.com/ceapex/Contributor%20Success/_workitems/edit/611305)

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
Troubleshooting graphic.

**Comment by TimShererWithAquent** [comment]
@LakshanF These changes are ready for review - details in email -

**Review by agocke — APPROVED** [review]
LGTM

**Comment by TimShererWithAquent** [comment]
#sign-off per email from Lakshan -

**Comment by TimShererWithAquent** [comment]
@LakshanF - Do I need to reach out to someone to get this merged? Thanks -

**Comment by TimShererWithAquent** [comment]
Hi @BillWagner - Saw your name above - Is there anything else I need to do to get this PR merged? Thanks -

**Comment by BillWagner** [comment]
tagging @adegeo for final review and merging.

**Comment by TimShererWithAquent** [comment]
@adegeo I reached out to our team about making additional changes to the article, based on your comments. @msarts should be reaching out to you shortly.

In the meantime, we'd like to get this PR merged. Can you help?

**Comment by TimShererWithAquent** [comment]
@adegeo I've reorganized the topic. I included some material in tabs and folded other sections as H3 into a lower H2. As I discussed, this topic is a little long and I don't want to overwhelm the reader with H2s. 

Please give it a read - moving things around can lead to small inconsistencies: 

https://review.docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?branch=pr-en-us-29646&tabs=cli




cc @mSarts

**Review by adegeo — APPROVED** [review]

**Pull request merged**
