### PR TITLE
Fix inconsistent brackets

### LINKED ISSUE #23574: Inconsistant brackets
The brackets in the code snippets on this page are inconsistently on the same line as the statement when they should be on the new line. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d79f0472-2434-9724-979f-2d5eb281dd67
* Version Independent ID: 6c665c3e-93ac-cc9e-4d68-91e8cf285ed5
* Content: [throw - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/throw)
* Content Source: [docs/csharp/language-reference/keywords/throw.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/throw.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by BenjaminMichaelis**
## Summary

Fix three sample files brackets.

Fixes #23574

### CODE REVIEW

**Comment by BenjaminMichaelis** [comment]
Not sure why build isn't working unless I accidently fixed the wrong files. Will see if I can look over it again tomorrow maybe.

**Comment by Youssef1313** [comment]
> Not sure why build isn't working unless I accidently fixed the wrong files and don't know where the right ones are. Will see if I can look over it again tomorrow maybe.

@BenjaminMichaelis You need to add a csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by BenjaminMichaelis** [comment]
@Youssef1313 
> You need to add a csproj file:

Why would it be the case that a csproj file needs to be added for existing files that are just having small modifications done to them? Seems like if that was the case they would of been failing already before the modifications and that would be an issue of its own.

**Comment by Youssef1313** [comment]
> @Youssef1313
> 
> > You need to add a csproj file:
> 
> Why would it be the case that a csproj file needs to be added for existing files that are just having small modifications done to them? Seems like if that is the case the build would of been failing already before the modifications in this PR and that would be an issue of its own or the case in previous modifications to these files.

The build is only triggered for modified files since not all code files in the repository have project files, and it's still a ton of work.

**Comment by BillWagner** [comment]
Thanks for making these changes @BenjaminMichaelis 

As @Youssef1313 pointed out, many of our older samples didn't have projects ported over when they were migrated from MSDN. To fix this error, add a .csproj file as shown above.

One different recommendation:  

> If the build failed due to multiple entry points, consider splitting into different projects.

Another alternative is to specify the startup object in the project file. That's covered here: https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/advanced#mainentrypoint-or-startupobject

**Review by BillWagner — APPROVED** [review]
This looks great @BenjaminMichaelis 

I'll :shipit: now.

**Pull request merged**
