### PR TITLE
Fix typo in wget syntax

### LINKED ISSUE #18094: wget syntax is wrong
The troubleshooting section shows the command `wget O- https://packages.microsoft.com/keys/microsoft.asc`. That syntax is incorrectly (specifically the `O-` switch), I believe it should be `wget -O - https://packages.microsoft.com/keys/microsoft.asc`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by Marusyk**
Fix typo in wget syntax

Fixes #18094

### CODE REVIEW

**Review by Thraka — APPROVED** [review]
Thanks for fixing this.

**Comment by billti** [comment]
I believe it should be a capital O, not lowercase.

**Comment by Marusyk** [comment]
@billti, why do you think so?

Screenshot_2

from https://www.gnu.org/software/wget/manual/wget.html

**Comment by billti** [comment]
Note the fact this is for a "logfile" and the "normally reported to standard error" outlined there. This is for logging messages resulting from running the command.

See also on that page:

image

**Comment by Marusyk** [comment]
agree, thanks

**Comment by Thraka** [comment]
@Marusyk I already fixed it a few hours ago in another PR. 😁

**Pull request merged**
