### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes a broken link on https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-using-dataflow-in-a-windows-forms-application

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for correcting this link, @ChrisMaddock. If you could change it to `(/visualstudio/ide/reference/build-page-project-designer-csharp)`, the link will also work with our offline documentation.

**Comment by ChrisMaddock** [comment]
No problem, sorted! 😄 

@rpetrusha - would you mind updating the contributing guide with guidance here? I wasn't sure if the link should be relative or not when I added it, so I checked - but the [contributing guide](https://github.com/dotnet/docs/blob/master/styleguide/template.md#links) only says to use relative links for topics in the same repo. So I assumed links to the VS docs should be fully qualified. (Also, I see other relative links use the tilde - but is that an old convention, and no longer preferred?)

Something else which I don't think is written down is removing the locale from docs.microsoft.com links, but I've been corrected on that one before, so knew what to do. 😄 Apologies if this is already all written down somewhere I just haven't come across yet!

**Comment by mairaw** [comment]
That's good feedback @ChrisMaddock. I'll get this added to the style guide. ~ is also accepted but we tend to use if less often since the link doesn't work on GitHub if you click on it.

**Comment by ChrisMaddock** [comment]
Great - thanks @mairaw 😄

**Comment by rpetrusha** [comment]
Thanks for making the additional change, @ChrisMaddock, and I apologize that our contributor's guide wasn't clear on the proper form of intersite URLs. This looks good, so we'll merge your PR once a successful internal build completes.

**Review by rpetrusha — APPROVED** [review]

**Comment by ChrisMaddock** [comment]
Thanks @rpetrusha 😄

**Pull request merged**
