### PR TITLE
MyGet Plan&Link Change

### PR DESCRIPTION
**Pull request by giotavekiari**
Url and description of MyGet, changed

Fixes Issue #8386

### CODE REVIEW

**Review by Thraka — CHANGES_REQUESTED** [review]
Hi! Thank you very much for this pull request. Please see the discussion in the linked issue #8386 but I'm thinking we should simplify this paragraph:

1. We should probably remove the ! in the first sentence and just use a period.
2. I think we should remove the link entirely (since the link at the start of the bullet point works just fine) and just state that public and private feeds are available.

Let's see what everyone else thinks on the issue though.

**Comment by giotavekiari** [comment]
Actually it's kind of confusing, because they don't state anything about the free plan, even in their pricing page: https://www.myget.org/pricing

Do they really support free plans? How can we redirect people there stating that they do have a free plan if MyGet doesn't even mention it on their site...

**Comment by Thraka** [comment]
@giotavekiari According to the post by someone associated with MyGet (in the linked issue) they do convert trial accounts to free accounts. I agree it does not make that clear on their website, but I don't see why we can't link to it. Even if it was a pay-only service, I don't think it matters. We're just letting users know the options they can use. This is why I was suggesting we simplify the text for MyGet and not mention the free option.

**Comment by giotavekiari** [comment]
Made some changes as discussed! Please check again! Thank you!

**Review by Thraka — APPROVED** [review]

**Pull request merged**
