### PR TITLE
:bookmark: readding asp.net samples

### PR DESCRIPTION
**Pull request by mairaw**
This PR fixes the comment styles in aspx files to the ones accepted by OPS and bring back to the asp.net APIs.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7&branch=pr-en-us-3091)

### CODE REVIEW

**Comment by mairaw** [comment]
@JRAlexander @rpetrusha @BillWagner this is ready for review.

@Rick-Anderson @scottaddie since this is related to asp.net, not sure if you guys want to check this one. This is to bring ASP.NET snippets into our docs (they weren't supported before).

Known issue: the asp.net snippets don't attach to the C# and VB selectors so both versions are always shown. There's an issue filed for this already.

**Comment by Rick-Anderson** [comment]
@mairaw  what's an easy way to find these from the internal review link?

**Comment by mairaw** [comment]
Go to any ASP.NET API. None of them have samples today @Rick-Anderson.

**Comment by mairaw** [comment]
And just to be clear, I'm not asking you to review the whole thing but maybe you spot some problems?

**Review by rpetrusha — APPROVED** [review]
I just spot-checked, but this looks really good, @mairaw. It's ready to merge when you want. 
I just looked at some of the metadata, but they were all missing ms.devlang metadata.

**Comment by mairaw** [comment]
Not sure what you mean about the ms.devlang @rpetrusha. The APIs have the filter set on a global level. 
I'm actually asking them to clarify the whole metadata for devlangs because there are at least 3 different values supported.

**Comment by rpetrusha** [comment]
@mairaw, what I meant is that conceptual topics using ASP.NET examples don't have a devlangs metadata element.

**Comment by mairaw** [comment]
Ah ok @rpetrusha. I'm taking care of devlangs in a separate giant PR. 😄

**Pull request merged**
