### PR TITLE
Add section to install a specific tool version - Global Tool

### PR DESCRIPTION
**Pull request by tasdevani21**
## Summary

Adding a section to show examples on how to install a specific version or a pre-release version of the global tool. The section has 2 examples: 
- How to install a specific version 
- How to install a version using the wildcard

### CODE REVIEW

**Comment by tdykstra** [comment]
Thank you for this submission. The information is useful, and the best place for it is in the [**Install a specific tool version section** of the How to manage .NET tools article](https://docs.microsoft.com/dotnet/core/tools/global-tools#install-a-specific-tool-version). It doesn't fit here because this is a tutorial that works specifically with the tool created in the previous tutorial in the series.

My suggestion is to change this PR so that it updates the "How to manage .NET tools" article (by adding the preview info, as it already has the specific-version info).  This PR could still update this tutorial as well, by adding something like "For more information about how to install and use global tools, see [link to the how-to article]" in the "Next steps" section between the two sentences that are already there.

**Review by adegeo — DISMISSED** [review]
Setting to "Request changes" per @tdykstra feedback

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=26768) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=26768) before we can accept your contribution.<br/><br/>:x: tasdevani21 [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=26768)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=26768) it.</sub>

**Comment by tasdevani21** [comment]
> Thank you for this submission. The information is useful, and the best place for it is in the [**Install a specific tool version** section of the How to manage .NET tools article](https://docs.microsoft.com/dotnet/core/tools/global-tools#install-a-specific-tool-version). It doesn't fit here because this is a tutorial that works specifically with the tool created in the previous tutorial in the series.
> 
> My suggestion is to change this PR so that it updates the "How to manage .NET tools" article (by adding the preview info, as it already has the specific-version info). This PR could still update this tutorial as well, by adding something like "For more information about how to install and use global tools, see [link to the how-to article]" in the "Next steps" section between the two sentences that are already there.

Updated this PR to incorporate the feedback. Thank you!

**Review by tdykstra — APPROVED** [review]
@tasdevani21 thank you, looks great!

**Pull request merged**
