### PR TITLE
Move media to correct location for wcf/feature-details

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Comment by pkulikov** [comment]
@gewarren I don't the reason of hanging but what usually helps in such cases (when neither PR title nor commit messages contain "wip") is wip-reboot: rename PR to contain "wip" and then rename it back. So, it's like close/reopen flow for wip.

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

You can :shipit: when ready.

**Comment by BillWagner** [comment]
@gewarren 

> Do you know why the WIP item is getting hung up on this PR?

It looks like the service was down yesterday. I editing the title to make it re-evaluate this PR.

**Comment by gewarren** [comment]
@BillWagner Thanks so much!

**Pull request merged**
