### PR TITLE
Cleanup unnecessary files

### LINKED ISSUE #488: Methods and Lambda Expressions
Issue tracking new topic at https://github.com/dotnet/docs/blob/master/docs/csharp/methods-lambda-expressions.md

### LINKED ISSUE #491: Learn C#: Parallel programming
Issue tracking new topic at https://github.com/dotnet/core-docs/blob/master/docs/csharp/parallel.md

### PR DESCRIPTION
**Pull request by BillWagner**
This PR removes the blank "wrench" topics that aren't written, and aren't linked to the TOC

Fixes #488 
Fixes #491

### CODE REVIEW

**Comment by BillWagner** [comment]
I added the WIP label.  I want to check the build before we review this.

**Comment by mairaw** [comment]
Please add the redirections too at https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json

**Comment by BillWagner** [comment]
@mairaw redirects are added.

**Comment by BillWagner** [comment]
@mairaw I think this is ready for another review.

**Review by rpetrusha — APPROVED** [review]
LGTM. Once you address the merge conflict, this is ready to merge when you want, @BillWagner.

**Pull request merged**
