### PR TITLE
Correct some problems in the unit testing tutorial

### PR DESCRIPTION
**Pull request by inlineHamed**
I just fixed some minor problems

### CODE REVIEW

**Comment by hmdhasani** [comment]
also there is a rendering problem at the end of the document that I did not figure out the reason.

capture

**Review by cartermp — APPROVED** [review]
Thanks, @hmdhasani.

As for the markdown problem at the bottom, you're right that it's quite strange.  The markup is correct.  @mairaw would you know how to contact on the docfx side to make sure this is correct?  I can't see a problem in it.

**Comment by mairaw** [comment]
I've fixed that issue already with https://github.com/dotnet/docs/commit/15451ddbbbce939ddd9e84b8f40fb8daacd9413a#diff-5e8d0a13b2a5cefde17e365e4aa81953. It should be live shortly.

**Review by mairaw — APPROVED** [review]

**Comment by mairaw** [comment]
Thank you @hmdhasani!

**Comment by hmdhasani** [comment]
your welcome!

**Pull request merged**
