### PR TITLE
C76762: Removing all "\" at the end of lines and adding two spaces in…

### PR DESCRIPTION
**Pull request by v-makoud**
…stead

Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by v-makoud** [comment]
#sign-off

**Comment by mairaw** [comment]
I'd like to understand why we're doing this @v-makoud. Is this breaking for Loc?
As I said in the other PR, we don't want to add the two spaces back in the end because some editors will trim white spaces automatically when saving a file.

/cc @JasonCard

**Comment by v-maudel** [comment]
Hi @mairaw , these strings as they are, are breaking the localized content. Bill wagner proposed a fix here and I also left a comment. https://github.com/dotnet/docs/pull/11515

regards.

**Comment by mairaw** [comment]
Ah sorry, missed the reply there and couldn't find that PR this morning. 

Yes, his solution to code fence is a good workaround. Eventually, I'd like to fix all those sections to add the links and formatting as we used to have in MSDN back in the day like we did here:
https://raw.githubusercontent.com/dotnet/docs/master/docs/framework/configure-apps/file-schema/runtime/index.md

For that, I guess we'd have to use explicit \<br /> tags. This is related to this discussion: https://github.com/MicrosoftDocs/feedback/issues/1264

I'll have to review all the uses of that \ at the end of a line because we have other places we've been using that.

**Review by mairaw — CHANGES_REQUESTED** [review]
Can you use the ``` syntax here then @v-makoud? It would be preferable vs. adding spaces. 

If this could match what we had on MSDN before (indentation and node names, except the last one shouldn't say element), even better:
image

**Review by mairaw — APPROVED** [review]

**Comment by v-makoud** [comment]
@mairaw yes we can use this.

**Comment by nemrism** [comment]
Too bad I didn't read this thread before pushing the PRs to fix #2038!
I did use a \ in most or every files I've changed... how/when could I check if it breaks the localization of those pages?

/cc @mairaw / @v-makoud / @v-maudel

**Comment by JasonCard** [comment]
@nemrism Those affected files under subfolder [https://github.com/dotnet/docs/blob/live/docs/framework/configure-apps/](https://github.com/dotnet/docs/blob/live/docs/framework/configure-apps/) are machine translated and should be localized by Monday morning. Then you can check how it's displayed in live page.
cc @mairaw @v-makoud @v-maudel

**Comment by nemrism** [comment]
Thanks @JasonCard 

I already see some issues with the automated translation, here:
https://docs.microsoft.com/fr-fr/dotnet/framework/configure-apps/file-schema/wcf/issuerchannelbehaviors-element

Some elements get translated which is something incorrect as configuration file schema is not meant to be translated.

Is there a way to tell the automatic translation to avoid this?
It already seems to ignore the `<add>` child element tag but translate other tags in the hierarchy at the top of the article... due to the bold formatting?

**Comment by JasonCard** [comment]
@nemrism Thank you for checking. 
Code block syntax can be used to block text from getting localized. 
For example, words surrounded by backtick quotes (`) become code block and will not be localized like `<clientCredentials>`. 
And as fixed in this PR, if you can block multiple lines from localization by surrounding the section with 3 backtick quotes (```) to make them a code block.
Text between <> brackets are being localized according to translation memory and/or machine translation.

**Comment by mairaw** [comment]
Let me test something else with the no-loc feature @nemrism. 

@JasonCard but there was also a question about being able to use \ as the new line at the end of sentences. We got some PRs from the loc team telling us that this would cause issues for Loc. 

Related discussion: https://github.com/MicrosoftDocs/feedback/issues/1264

**Comment by nemrism** [comment]
Actually there is already another paragraph using code block to present the syntax of the configuration files XML.

The goal of the lines at the beginning of the article, the ones you can see in the screenshot, is to respect the hierarchy while linking to the pages of the parent elements.

So we should find a solution to have them presented like this, with links on almost each lines. And the best solution would also allow us to tell the automatic translation to leave those links not translated.

**Comment by JasonCard** [comment]
@mairaw @nemrism I see, yes, the [no-loc feature](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings) can also be used to block text from localization. 
Regarding the use of \ as new line at the end of sentences, I'm not sure why it was causing issue for loc, but it seems to be working now in [this page](https://docs.microsoft.com/de-de/dotnet/framework/configure-apps/file-schema/wcf/issuerchannelbehaviors-element), so we just need to block the text from localization by adding the no-loc syntax.

**Comment by nemrism** [comment]
Thanks, I'll check the documentation of the no-loc if I can find some. Or will wait for @mairaw's sample/test results.

**Pull request merged**
