### PR TITLE
Correct variable naming in code sample

### PR DESCRIPTION
**Pull request by maxarndt**
# Title

Fixed variable naming in _nosql-database-persistence-infrastructure.md_.

## Summary

Fixed variable naming in the parameter list fo `CreateDocumentAsync()`. Makes the example easier understandable.

### CODE REVIEW

**Comment by pkulikov** [comment]
@m4xy good catch! 
Related to the same code sample: it contains the line `orderAggregate.AddOrderItem(orderItem2);` However, there is no `orderItem2` instantiation. Should we remove the line or create another order item?

**Comment by m4xy** [comment]
@pkulikov Cheers!
I think through instantiating `orderItem1` this is clear and saves some lines of code. So from my point of view this should be fine.

**Comment by BillWagner** [comment]
ping @CESARDELATORRE to review. This is part of the microservices eBook

**Review by jzeferino — APPROVED** [review]
LGTM.

**Comment by CESARDELATORRE** [comment]
I just reviewed the change. It is a good/better name for the variable since it is an Entity Aggregate and also an Order. :)

**Review by BillWagner — APPROVED** [review]
Thanks for making this improvement.  I'll :shipit: now.

You should see the change on the live site in the next day or two. 

Thanks again!  We really appreciate your involvement in making a better experience for everyone.

**Pull request merged**
