### PR TITLE
Updated Taxi Fare Predictor tutorial topic for SEO Report Items

### PR DESCRIPTION
**Pull request by JRAlexander**
Updated Taxi Fare Predictor tutorial topic for SEO Report Items for hackadoc

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
LGTM, except that there is a build warning for  "<xref:Microsoft.MLRuntime.Data.PredictionFunction%602>". No idea why, though.

**Comment by JRAlexander** [comment]
Hmmm. ok. Fixing. Thanks!

**Comment by rpetrusha** [comment]
Also, @jralexander, you didn't add the ms.custom attribube.

**Comment by JRAlexander** [comment]
Thanks, @rpetrusha! Was missing a period in the xref. I believe all your changes have been addressed.

**Comment by JRAlexander** [comment]
Clean build! yay!

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
