### PR TITLE
Add .NET Core app preprocessor symbols to the list

### PR DESCRIPTION
**Pull request by guardrex**
Adding the `NETCOREAPPX_Y` ones to the list.

### CODE REVIEW

**Comment by mairaw** [comment]
Do we also support 2.0 values already?

**Comment by GuardRex** [comment]
@mairaw Yes :+1: I tested that. It works. I just held off because 2.0 hasn't shipped.

**Comment by GuardRex** [comment]
Do u want to go ahead and add that now? ..... one less thing to think about later?

**Comment by GuardRex** [comment]
@rpetrusha btw -- this can go anytime. It isn't tied to 2.0, and the topics where used are currently incorrect until this gets merged.

**Review by rpetrusha — APPROVED** [review]
@GuardRex, in that case, let's merge.

**Comment by GuardRex** [comment]
Thanks Ron ... I'll put up a 2.0 PR for this file shortly to add the new ones for 2.0.

**Pull request merged**
