### PR TITLE
Add syslib0038 and syslib0039

### LINKED ISSUE #28475: [Breaking change]: Mark SslProtocols.Tls and SslProtocols.Tls11 as obsolete
### Description

https://github.com/dotnet/runtime/pull/65773 marks `SslProtocols.Tls` and `SslProtocols.Tls11` as obsolete.

Original issue: https://github.com/dotnet/runtime/issues/65546

### Version

.NET 7 Preview 3

### Previous behavior

No warnings when `SslProtocols.Tls` and `SslProtocols.Tls11` were used in code.

### New behavior

Using `SslProtocols.Tls` or `SslProtocols.Tls11` produces `SYSLIB039` warning

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

With the recent push for more secure defaults and behavior and with recent Azure and CipherSuitePolicy changes we feel it is time to mark TLS 1.0 and 1.1 as obsolete since the industry no longer considers them as safe.

### Recommended action

Use a higher TLS protocol version, or use `SslProtocol.None` to defer to system defaults.

Otherwise, the warning can be silenced using `#pragma warning disable`:

```cs
#pragma warning disable SYSLIB0039 // TLS 1.0 and 1.1 are obsolete
                    protocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
#pragma warning restore SYSLIB0039
```

### Feature area

Networking

### Affected APIs

`SslProtocols` enum.

### LINKED ISSUE #28726: [Breaking change]: obsoletion of SerializationFormat.Binary
### Description

SerializationFormat.Binary is obsolete in .NET 7 for DataTable/DataSet, because it relies on BinaryFormatter which is insecure (see https://github.com/dotnet/runtime/issues/39289), and code using it will start to get an exception unless a special AppContext switch is used. The plan is to remove the code entirely in .NET 8, at which point the AppContext switch will stop working as well (https://github.com/dotnet/runtime/issues/65140).

### Version

.NET 7 Preview 2

### Previous behavior

DataTable and DataSet could be serialized and deserialized with their RemotingFormat property set to SerializationFormat.Binary, which used BinaryFormatter under the hood.

### New behavior

Attempting to serialize or deserialize DataTable and DataSet with their RemotingFormat property set to SerializationFormat.Binary now throws.

A new AppContext switch has been introduced (Switch.System.Data.AllowUnsafeSerializationFormatBinary) which allows opt back into allowing SerializationFormat.Binary again, so that code can work as before. We plan to remove the switch in .NET 8.

### Type of breaking change

- [X] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

SerializationFormat.Binary is implemented via BinaryFormatter, which is insecure and being obsoleted across the entire .NET stack.

### Recommended action

Code currently using SerializationFormat.Binary should switch to using SerializationFormat.Xml, or use another method of serialization.

### Feature area

Core .NET libraries

### Affected APIs

* The [SerializationFormat.Binary](https://docs.microsoft.com/en-us/dotnet/api/system.data.serializationformat?view=net-6.0#system-data-serializationformat-binary) enum member is now obsolete.
* [DataSet.RemotingFormat](https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset.remotingformat?view=net-6.0#system-data-dataset-remotingformat) and [DataTable.RemotingFormat](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.remotingformat?view=net-6.0#system-data-datatable-remotingformat): These now throw when set to SerializationFormat.Binary (unless the Switch.System.Data.AllowUnsafeSerializationFormatBinary AppContext switch is specified).
* The deserialization constructors for [DataTable](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.-ctor?view=net-6.0#system-data-datatable-ctor(system-runtime-serialization-serializationinfo-system-runtime-serialization-streamingcontext)) and DataSet ([1](https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset.-ctor?view=net-6.0#system-data-dataset-ctor(system-runtime-serialization-serializationinfo-system-runtime-serialization-streamingcontext)), [2](https://docs.microsoft.com/en-us/dotnet/api/system.data.dataset.-ctor?view=net-6.0#system-data-dataset-ctor(system-runtime-serialization-serializationinfo-system-runtime-serialization-streamingcontext-system-boolean))) now throw if given binary data (unless the Switch.System.Data.AllowUnsafeSerializationFormatBinary AppContext switch is specified).

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #28475 and fixes #28726.

Previews:

- [SYSLIB0038](https://review.docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0038?branch=pr-en-us-28734)
- [SYSLIB0039](https://review.docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0039?branch=pr-en-us-28734)
- [Obsoletion of binary serialization](https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/serializationformat-binary?branch=pr-en-us-28734)

### CODE REVIEW

**Review by roji — APPROVED** [review]
For SerializationFormat.Binary

**Review by rzikm — APPROVED** [review]
LGTM for SYSLIB0039

**Review by BillWagner — APPROVED** [review]
This looks great @gewarren 

You can :shipit: when ready.

**Comment by gewarren** [comment]
Thanks for the reviews!

**Pull request merged**
