### PR TITLE
remove zip files

### PR DESCRIPTION
**Pull request by mairaw**
Apparently, for any API published under https://docs.microsoft.com/en-us/dotnet/api, xref links should just work now. Removing some of the zip files to see if we get any broken links in our content without these support files.

### CODE REVIEW

**Comment by BillWagner** [comment]
@mairaw What should we be looking for to review this one? Are there specific pages that might have broken links?

**Comment by mairaw** [comment]
I was expecting to see some broken links on the build report when I did this, so it seems that xref service is really working. Need to test more before merging this one though. I'll try to find some pages where we link to either Roslyn APIs or VS SDK APIs.

**Comment by BillWagner** [comment]
@mairaw [This page](https://review.docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/work-with-syntax?branch=pr-en-us-4396) is a good start for the Roslyn APIs. The xrefs look good, but go to the live site not the review site.

**Comment by mairaw** [comment]
Cool @BillWagner. I think that's expected. The xref service only knows the public version of the link when the docs are not part of the repo.

See https://xref.docs.microsoft.com/query?uid=Microsoft.CodeAnalysis.SyntaxNode

**Review by BillWagner — APPROVED** [review]
Based on the tests we've run, you can merge this when ready @mairaw

**Pull request merged**
