### PR TITLE
remove inner snippets + formatting

### PR DESCRIPTION
**Pull request by mairaw**
C# operators 1/2

Contributes to #1255

### CODE REVIEW

**Comment by pkulikov** [comment]
@mairaw this PR and #9936 touch the same files.

**Comment by mairaw** [comment]
Thanks for the heads-up @pkulikov. I'll mark this as hold for related PR, so I can sort out the merge conflicts after yours is merged.

**Comment by pkulikov** [comment]
> I'll mark this as hold for related PR, so I can sort out the merge conflicts after yours is merged.

Cool, thanks!

**Review by BillWagner — APPROVED** [review]
This LGTM @mairaw 

You can :shipit: when ready.

**Review by rpetrusha — APPROVED** [review]
There's one additional dependency on the code snippets that you've removed, @mairaw -- in docs/csharp/language-reference/operators/left-shift-operator.md.

**Comment by mairaw** [comment]
Good catch! Thanks @rpetrusha.

**Comment by pkulikov** [comment]
@mairaw thanks for letting my PR go first into the master; it has been merged.

**Comment by mairaw** [comment]
Thanks @pkulikov. I've grabbed your version and updated this PR.

**Pull request merged**
