### PR TITLE
disable MD Lint rule 37

### PR DESCRIPTION
**Pull request by BillWagner**
This rule is generating a number of false positives.

It appears to be whenever a paragraph contains a mix of bold an italic, or a `*` in a code fence.

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
LGTM

**Comment by nschonni** [comment]
Think it is a bug with the underscores and asterisks parsing in `*word_reader*`. Probably the better issue to follow is https://github.com/DavidAnson/markdownlint/issues/286.
You can either disable the rule, or pin the markdownlint-cli version being used temorarily

**Comment by BillWagner** [comment]
Thanks for the background @nschonni 

For now, we'll disable that rule. I'll watch the tagged issue and re-enable when it's fixed.

**Comment by DavidAnson** [comment]
@BillWagner, could you please give some examples where this is not working correctly? Scenarios like the one @nschonni shows above should be fine in the current releases of the library and CLI. For example:
https://dlaa.me/markdownlint/#%25m%23%20dotnet%2Fdocs%0A%0AThis%20is%20fine%3A%20*word_reader*.%0A

There is only one valid bug scenario I know of right now (https://github.com/DavidAnson/markdownlint/issues/286#issuecomment-624161089) - and I would like to know if there are others so I can fix them.

**Comment by nschonni** [comment]
@DavidAnson you can see the files in the repo that started getting flagged in here https://github.com/dotnet/docs/runs/647383455?check_suite_focus=true#step:4:8
My minimal example might not be right, but it isn't the same bullet list issue

**Comment by DavidAnson** [comment]
Good! All the ones in `docs/docs/core/deploying/index.md` seem to be this (new) flavor:
https://dlaa.me/markdownlint/#%25m%23%20docs%2Fdocs%2Fcore%2Fdeploying%2Findex.md%0A%0A**word_reader**%20text%20*word_reader.dll*%0A

**Comment by DavidAnson** [comment]
@BillWagner / @nschonni: This project is using an anti-pattern by installing the *latest* CLI during CI. Here's a bug for that which includes info on how to fix it: https://github.com/dotnet/docs/issues/18275

**Comment by DavidAnson** [comment]
@BillWagner / @nschonni: I've got good news and bad news. :) It looks like this repo started with 68 warnings. With the change to ignore emphasis markers in links, that drops to 65. Addressing the `**text_text**` issue you point out above gets rid of 8 more of those 65 warnings.

I'll need to go through the rest, but I've peeked at the first two so far.

1. ``test-repos/dotnet-docs/docs/machine-learning/automate-training-with-cli.md: 44: MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "*macOS/Linux bash, or *"]`` is valid, there's a missing emphasis marker and the docs repo should be updated to fix it - the problem is visible at https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-cli.
2. ``test-repos/dotnet-docs/docs/standard/language-independence.md: 339: MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "* named `Value`. Because an `i..."]`` is valid to a computer that doesn't know `int*` means something and that two of them nearby aren't a problematic emphasis. Escaping the `*` with `\` addresses the issue.

There may be more `MD037` bugs here, but there'll need to be at least a few updates to the `docs` repo to get back to 0 issues reported. I'll send a PR once I go through all of these, I guess. If you could please help get that merged, that'd be great.

**Comment by DavidAnson** [comment]
@BillWagner / @nschonni, here's a commit to fix the remaining bogus issues reported by `markdownlint` for this repo: https://github.com/DavidAnson/markdownlint/commit/f607a49a5bd4c8d8dae635a8de4ad6a27fee3dc5

PR to fix the valid issues in this repo will be posted shortly.

**Comment by DavidAnson** [comment]
PR for this repo: https://github.com/dotnet/docs/pull/18341

**Pull request merged**
