### PR TITLE
Update infrastructure-persistence-layer-design.md

### PR DESCRIPTION
**Pull request by meMuszr**
# Removed a word

## Summary

DDD stands for Domain Driven Design. Removed 'design' from 'DDD design' because it is redundant.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks, @meMuszr. Your change looks good. Would you mind making one more change? DDD is used 4 times in this topic, but the acronym is not clearly defined (except perhaps in the Additional resources section). Would you mind making the following change on line 25:
based on DDD patterns --> based on domain-driven design patterns
If you'd prefer, we can also make the change before accepting your PR. 
Again, thanks for making this correction.

**Review by meMuszr — COMMENTED** [review]
update accordingly

**Review by rpetrusha — APPROVED** [review]
Thanks for making the additional change, @meMuszr. We'll merge your PR now.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Pull request merged**
