### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ricardodsanchez**
# Title

This repo needs a Code of Conduct.

## Summary

Added a Code of Conduct based on a template for large projects/communities.

### CODE REVIEW

**Comment by svick** [comment]
As specified in [the README](https://github.com/dotnet/docs/blob/master/README.md), this repo already adopted [the .Net Foundation Code of Conduct](https://dotnetfoundation.org/code-of-conduct). I don't think it makes sense to adopt a second CoC or to have a different CoC than every other .Net Foundation project.

**Comment by rpetrusha** [comment]
//cc @richlander

**Comment by ricardodsanchez** [comment]
@svick I missed the link in the README, and since the CoC is not actually part of the repository, it shows as missing.

**Comment by jongalloway** [comment]
As noted, all .NET Foundation projects reference the same common Code of Conduct. There are obvious benefits to referencing a common Code of Conduct, especially being able to make updates in one place.

One option would be to add a CODE_OF_CONDUCT.md that would just include a link to the standard .NET Foundation Code of Conduct. That would show up in the recently added Community link. Thoughts?

**Comment by mairaw** [comment]
@BillWagner we discussed the plan for the code of conduct last week. Do you wanna share the resolution here?

**Review by BillWagner — CHANGES_REQUESTED** [review]
@ricardomlourenco Thanks for submitting this. Also, thanks for bringing to our attention how GItHub is surfacing the community page. That really helped us determine what to do. The .NET Foundation Advisory Council discussed the strategy for publicizing that each .NET Foundation project incorporates the .NET Foundation Code of Conduct by reference.

We agreed to create a CODE_OF_CONDUCT.md in each project with the following text (taken from our Readme.md):

> This project has adopted the code of conduct defined by the Contributor Covenant
to clarify expected behavior in our community.
For more information, see the [.NET Foundation Code of Conduct](https://dotnetfoundation.org/code-of-conduct).

Do you want to update this PR with that text? Then, we'll merge it.

**Review by ricardomlourenco — APPROVED** [review]

**Comment by ricardodsanchez** [comment]
@BillWagner Did you meant to send the following message to me instead of @ricardomlourenco? I am confused as I was the person who suggested to create the CODE_OF_CONDUCT.md:
"@ricardomlourenco Thanks for submitting this. Also, thanks for bringing to our attention how GItHub is surfacing the community page. That really helped us determine what to do. The .NET Foundation Advisory Council discussed the strategy for publicizing that each .NET Foundation project incorporates the .NET Foundation Code of Conduct by reference." 

I am glad the resolution was to add this file to each project, as it wasn't showing in the community pages.

**Comment by BillWagner** [comment]
@ricardodsanchez I'm sorry.  I looked as GitHub auto-filled the response, and I must not have been looking closely enough. Yes, I did mean that message for you. Let us know if you want to update the PR, or if you want us  to make the change. Either way, thank you for raising this and working to fix it.

**Comment by ricardodsanchez** [comment]
@BillWagner @mairaw I updated the PR with the suggestions. Thanks!

**Review by BillWagner — APPROVED** [review]

**Pull request merged**
