### PR TITLE
Update cs5001.md

### PR DESCRIPTION
**Pull request by pkulikov**
Reference to [Main() and command-line arguments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/) for the rules that apply to the `Main` method and do not duplicate them in the compiler error topic.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks, @pkulikov, for enhancing this compiler error documentation. I've left just one minor nit, then the PR is ready to merge.

**Comment by pkulikov** [comment]
@rpetrusha GitHub swallowed your feedback message. My guess is that "For the information..." should be "For information...". The latest commit fixes that. If I'm wrong, please correct me.

**Comment by rpetrusha** [comment]
Yes, that was the nit, @pkulikov. GitHub seems to swallow my feedback messages with some regularity...

**Review by rpetrusha — APPROVED** [review]
Thanks for surmising what my comment was and making the change, @pkulikov. I'll merge your PR now.

**Pull request merged**
