### PR TITLE
C26941: Escaping '@' character

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @mairaw  ,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM as well. I'll let @mairaw :shipit: when ready

**Comment by mairaw** [comment]
@v-maudel this topic also presents other @ symbols. don't they also have to be escaped for loc?

**Comment by v-maudel** [comment]
Hi @mairaw  ,
This was the only change reported by the production team, I think it is because the other @ characters that appears are well displayed because they are inside a link.
Although, I'm checking it with them.

regards.

**Comment by mairaw** [comment]
I can accept as is and then you file a new PR if the other ones cause issues @v-maudel. Let me know!

**Comment by v-maudel** [comment]
Hi @mairaw , I confirm that @ inside links doesn't affect the localization process.

**Comment by v-maudel** [comment]
Thanks @mairaw

**Pull request merged**
