### PR TITLE
Improve TOC for Preview 3

### PR DESCRIPTION
**Pull request by svick**
* Added missing CI article
* No need to repeat ".NET Core Tools Preview 3" in TOC

cc: @blackdwarf

### CODE REVIEW

**Comment by blackdwarf** [comment]
@svick thanks for this. I left out the CI on purpose, since there are not many differences between Preview 2 and Preview 3 tooling in that regard.

**Comment by svick** [comment]
But the article still exists and is linked from the main Preview 3 article, so I think it makes sense to include it in the TOC too.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.md](https://github.com/svick/core-docs/blob/patch-1/docs/toc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/toc.json?branch=pr-en-us-1272) | [Details](#user-content-docs/toc.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C19%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611191723187574-1272%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
I agree with the changes to the TOC titles. @blackdwarf, should we remove the CI article then? Or is there any difference between the two?

**Comment by blackdwarf** [comment]
@mairaw there is one difference, actually, that is the version that is needed. I cannot remember if I changed it when I did the Preview 3 docs, but if I missed it, we should add that change to this PR and then merge it.

**Comment by blackdwarf** [comment]
It seems that I didn't. @enricosada since you added the Travis example, a question: looking at the current set of instructions in this document, it seems that you are installing the CLI jsut by specifying the version in the yaml file. This means that Travis has made that version available in their service, right? 

If so, this would mean that they would need to do the same for Preview 3 bits in order for the instructions to work?

**Comment by enricosada** [comment]
Yes, in Travis the `csharp` language (community maintained) support sdk. But I don't know what script is run to install, so maybe already works. I'll check later tonight.

**Comment by BillWagner** [comment]
I think this got lost for a bit.

@blackdwarf @mairaw Is this ready to go?

**Comment by BillWagner** [comment]
It would seem that this is ready to go.  @svick do you want to fix the merge conflicts? If not, we can push this forward in another PR

**Comment by mairaw** [comment]
I've resolved the conflicts in this PR since @svick gave us permissions, @BillWagner. Let's wait for CI to finish and merge this. Thanks @svick!

**Pull request merged**
