### PR TITLE
.NET9 What's new - Runtime - align name with sample code snippet

### PR DESCRIPTION
**Pull request by hakenr**
The `ForLoop` snippet uses `arr` array, not `nums`.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/whats-new/dotnet-9/runtime.md](https://github.com/dotnet/docs/blob/dcea0a8c1c16bac28946ef30a00cdf9c4dda8522/docs/core/whats-new/dotnet-9/runtime.md) | [docs/core/whats-new/dotnet-9/runtime](https://review.learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/runtime?branch=pr-en-us-42427) |

### CODE REVIEW

**Comment by gewarren** [comment]
@hakenr Thanks for catching that! Given that the last example uses a pointer to a `Span<int>` and it wouldn't make sense to rename that collection to `arr`, I think it's better to rename the variable in the code files to `num` so that name can rename consistent between the examples. Do you want to make those changes instead?

**Comment by hakenr** [comment]
@gewarren OK, I'll change the naming in opposite direction, give me a minute to update the PR.

**Comment by hakenr** [comment]
@gewarren Ready for rereview.

**Review by gewarren — APPROVED** [review]

**Comment by gewarren** [comment]
Thank you @hakenr!

**Pull request merged**
