### PR TITLE
Updating the TOC to create placeholders for porting documents

### LINKED ISSUE #231: Rework the TOC to fit in the ported docs from MSDN
Given the recent influx of issues that will result in a lot of docs being ported over from MSDN, we need to figure out where each of them fits in.

/cc @mairaw @richlander @BillWagner

### PR DESCRIPTION
**Pull request by thesmithee**
This TOC update introduces placeholders for various porting documents that @mairaw opened issues for.

Fix #231 

/cc @mairaw @richlander

### CODE REVIEW

**Comment by blackdwarf** [comment]
Another version is up. Can we please review and then merge, since I would like to get the TOC ready for our next sprint of writing?

/cc @mairaw @cartermp @BillWagner

**Comment by cartermp** [comment]
LGTM

**Comment by mairaw** [comment]
We should also remove the wrench from the TOC for the tooling topic under Porting

**Comment by BillWagner** [comment]
:shipit:

**Comment by blackdwarf** [comment]
@mairaw what do you mean, the porting docs are not complete. When I click on the links, there is nothing there (apart from the tools one, will remove that one).

**Comment by mairaw** [comment]
That's what I meant. To remove the wrench from that topic only.

**Comment by blackdwarf** [comment]
@mairaw done. I will merge.

**Pull request merged**
