### PR TITLE
Format codes based on .editorconfig, Part 21

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Comment by adegeo** [comment]
@NextTurn We've introduced PR checking where it tries to determine the project associated with the changed file and then compile it. All snippets must have a project file right now. There are some files you've changed that don't have a project. It doesn't look like many. Do you want to:

- Add a project file for each of the modified files (one per folder I mean)
- Remove those files from the PR

It's going to be a bit harder to do mass updates in specific areas of the snippets repo, so be aware.

**Comment by NextTurn** [comment]
I'll revert those files for now (and in future PRs in this wave).

**Comment by NextTurn** [comment]
@adegeo What kind of project file share I add? `netcoreapp3.1` with `<PackageReference>`?

**Comment by BillWagner** [comment]
> What kind of project file shall I add? `netcoreapp3.1` with `<PackageReference>`?

@NextTurn Yes, that would be correct.

**Review by adegeo — APPROVED** [review]

**Pull request merged**
