### PR TITLE
Update unit-testing-with-nunit.md

### LINKED ISSUE #15623: Code error in TestCase
PrimeService need to be instanced. You need an additional line to instance it before called it with `var result`.
`PrimeService _primeService = CreatePrimeService();`
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit#feedback)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-core**
* GitHub Login: @rprouse
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by Youssef1313**
Supported by https://github.com/dotnet/samples/pull/1690
Fixes #15623

### CODE REVIEW

**Comment by Youssef1313** [comment]
@mairaw, Samples PR is merged. This is ready for review.

**Comment by Youssef1313** [comment]
Ping, @mairaw

**Comment by mairaw** [comment]
Thanks for the ping @Youssef1313.

**Comment by mairaw** [comment]
Let me try rebuilding this. Want to confirm what I'm seeing is just outdated or bad references.

image

**Review by mairaw — APPROVED** [review]
I'm approving assuming is just an outdated reference. If there's something wrong, we can check after we get a new build report. Thanks!

**Comment by mairaw** [comment]
Humm, I find it a bit weird that now the sample looks incomplete because we're trying to hide the additional tests. @BillWagner what do you think?

https://review.docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit?branch=pr-en-us-15628#creating-the-first-test

**Comment by Youssef1313** [comment]
@mairaw, Just to make sure, you're talking about adding the following comment under the test in the sample ?:

```csharp
        /*
        More tests
        */
```

**Comment by BillWagner** [comment]
@mairaw @Youssef1313 I agree with Maira that the first sample looks confusing because it's not a complete class.  It's taken from [this snippet](https://github.com/dotnet/samples/blob/master/core/getting-started/unit-testing-using-nunit/PrimeService.Tests/PrimeService_IsPrimeShould.cs#L1-L25).  

I've started adding a new file with examples representing code that is between the starter code and final code so I can include snippets, but still have complete sample code. An example is [here](https://github.com/dotnet/samples/blob/master/csharp/tutorials/mixins-with-interfaces/UnusedExampleCode.cs)

Then, those examples are extended with more code before becoming part of the "final" example.

We can merge this, but I'd like to address the sample code promptly.

**Review by mairaw — DISMISSED** [review]
I think we should address the sample code before merging this.

**Comment by Youssef1313** [comment]
@mairaw, I missed this one. What exactly needs to be done to the sample ?

**Comment by BillWagner** [comment]
@Youssef1313 Sorry, I missed your question.  I'd update the sample as I mentioned in https://github.com/dotnet/docs/pull/15628#issuecomment-557139770

**Review by BillWagner — APPROVED** [review]
I apologize for all the delays. This is ready to merge.

Thanks @Youssef1313

**Pull request merged**
