### PR TITLE
moved fsharp library reference

### PR DESCRIPTION
**Pull request by kexugit**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by cartermp** [comment]
The markdownlint failures are...enormous. @mairaw what are your thoughts on that, should they all be addressed?

**Comment by mairaw** [comment]
Should we merge this to a migration branch so we can party on this? I think some of the linting errors are probably easy to fix with search and replace on VS Code.

**Comment by mairaw** [comment]
Some things I'm noticing though that would be good to fix since it impacts redirection:
- filenames with special characters. We don't need that -[fsharp] on each file name plus some other characters I'm seeing.
- repeated words on the file path

**Comment by mairaw** [comment]
Also snippets should have been moved to https://github.com/dotnet/samples/tree/master/snippets/fsharp instead.

**Comment by cartermp** [comment]
Yeah I think a migration branch makes sense.

**Comment by mairaw** [comment]
Migration branch created. Target changed.

**Comment by kexugit** [comment]
@mairaw for updating file names, I think given the amount of files and the requirement, CPS might be a better resource to use. Also is "-[fsharp]" the only thing that needs to be changed? I see other strings in buckets in the file names.

**Comment by kexugit** [comment]
> Also snippets should have been moved to https://github.com/dotnet/samples/tree/master/snippets/fsharp instead.

@mairaw can you specify what folder should the snippets be moved to?

**Comment by mairaw** [comment]
I think the snippets could be moved under https://github.com/dotnet/samples/tree/master/snippets/fsharp following as similar name as here

so the file that here is under
docs/fsharp/library-reference/snippets/fsarrays/

would go to snippets/fsharp/fsarrays

**Comment by mairaw** [comment]
@cartermp I'm also wondering if these don't already exist in samples. For example
Is https://github.com/dotnet/samples/tree/master/snippets/fsharp/arrays
the same as https://github.com/kexugit/docs/tree/master/docs/fsharp/library-reference/snippets/fsarrays?

**Comment by mairaw** [comment]
@kexugit given this is a different migration, I'd be open to just drop "-[fsharp]" from the file names if that would make things easier.

**Comment by kexugit** [comment]
> @kexugit given this is a different migration, I'd be open to just drop "-[fsharp]" from the file names if that would make things easier.

OK. BTW, is '.' allowed in md file names? a lot of files have '.' in the names.

**Comment by cartermp** [comment]
@mairaw I think all of the snippets already exist in dotnet/samples. In fact, I think I remember importing them and removing the "fs" at the beginning of the name! So they probably don't need to be migrated.

**Comment by cartermp** [comment]
Hey folks, how can we get this to where we can merge it into the migration branch? I'd love to get started on fixing things up, but I first want to make sure it's in a good enough state to live in that branch.

**Comment by mairaw** [comment]
You should be able to merge it @cartermp at any point. Given it's a working branch, there are no requirements. I believe we only need @kexugit to sign the CLA first.

If you have the snippets already, that makes things easier. So you just need to search and replace to fix the paths.

@kexugit periods on the file names are not ideal but are allowed.

**Comment by mairaw** [comment]
@cartermp the CLA is signed. Feel free to merge.

**Review by cartermp — APPROVED** [review]

**Comment by hickford** [comment]
Community docs link https://fsharp.github.io/fsharp-core-docs/

**Pull request merged**
