### PR TITLE
Fixed link to the section

### PR DESCRIPTION
**Pull request by pkulikov**
In the [current version](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1021) generated link doesn't bring to the section needed.

### CODE REVIEW

**Comment by BillWagner** [comment]
@pkulikov Even after your change, the link doesn't go to the anchor tag on the review site.

@mairaw @rpetrusha Do you know how to achieve this?

**Comment by rpetrusha** [comment]
@mairaw may know, but the only way that I can think of is to supply the actual link: \[System.Numerics.BigInteger](https://docs.microsoft.com/dotnet/api/System.Numerics.BigInteger#instantiating-a-biginteger-object)

**Comment by pkulikov** [comment]
@rpetrusha thank you, I've updated the link following your suggestion
If that's fine with @mairaw, let's merge it?

**Comment by pkulikov** [comment]
@mairaw thank you for feedback, I've updated the link text as you suggested

**Review by BillWagner — APPROVED** [review]
Thanks for the tips @mairaw and @rpetrusha 

I've reviewed this, and I'll :shipit: now.

Thanks again @pkulikov

**Pull request merged**
