### PR TITLE
Adding DBNull as serializabe type

### PR DESCRIPTION
**Pull request by ViktorHofer**
We will add serialization support for System.DBNull timed with the next servicing release (2.0.2).

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
LGTM. I'll just wait for green builds to merge this,

**Comment by ViktorHofer** [comment]
Should we mention that it was added in 2.0.2? e.g. System.DBNull (added in 2.0.2)

**Comment by mairaw** [comment]
It's up to you. Given that it's a patch, customers have a short time to upgrade no?

**Comment by ViktorHofer** [comment]
I added the version info to be explicit :)

**Comment by mairaw** [comment]
@ViktorHofer can we change that to say "available in .NET Core 2,0,2 and later versions"?

**Comment by ViktorHofer** [comment]
Of course :)

**Pull request merged**
