### PR TITLE
chore: Unpin markdownlint

### PR DESCRIPTION
**Pull request by nschonni**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by IEvangelist — CHANGES_REQUESTED** [review]
Hi @nschonni,
We made this change just recently, as it was described as an anti-pattern. It is my understanding that we should be pinning the version, see #18275 (and resolved in #18280). I'll let @BillWagner chime in.

**Comment by BillWagner** [comment]
If possible, I like unpinning and using the latest version.

Is the issue that caused us to pin this fixed? If so, once the merge conflicts are resolved, we can merge this.

**Comment by nschonni** [comment]
Yeah, the MD037 stuff is addressed. The Markdownlint library is also using this repo in the CI for regression checks now

**Comment by BillWagner** [comment]
@IEvangelist I'd say :shipit:.  Do you want to do the approval?

And, thanks again @nschonni

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Pull request merged**
