### PR TITLE
[F#] Correcting light syntax for the code block

### PR DESCRIPTION
**Pull request by realvictorprm**
I'm not sure whether this fits here but I couldn't find a better place for this. Actually I even think we should outline the usage of `(...)` more. It wasn't obvious to me before.

## Summary

I've changed the description of a code block for the light syntax.

## Suggested Reviewers
What do you think @cartermp ?

### CODE REVIEW

**Comment by realvictorprm** [comment]
Just to note down. The code formatting on this page doesn't work for me. cc @cartermp 
image

**Comment by cartermp** [comment]
Not sure I understand the significance of the change here.  As for the code block rendering, that looks like a separate issue - the flavor of markdown used for docs here requires the use of `<code>` blocks in HTML inside of tables.  Looks like this one slipped past me.

**Comment by realvictorprm** [comment]
It's just about correcting the content for declaring separate blocks in the light syntax.
e.g. look here:
Light syntax
```fsharp
(
 use foo = { new with System.IDisposable member self.Dispose () = printfn "disposing" }
)
```
same in verbose syntax would be:
```fsharp
begin
 use foo = { new with System.IDisposable member self.Dispose () = printfn "disposing" }
end
```

**Comment by mairaw** [comment]
@cartermp any follow-up here?

**Review by cartermp — APPROVED** [review]
Seems fine after a second look.

**Comment by mairaw** [comment]
Thanks @realvictorprm. Your updates should go live later today or tomorrow.

**Comment by realvictorprm** [comment]
Many thanks both @cartermp and @mairaw.

Also thanks mairaw for keeping always an eye on this!

**Pull request merged**
