### PR TITLE
adding new APIs under System.Linq.* namespaces

### PR DESCRIPTION
**Pull request by mairaw**
@VSadov, @OmarTawfik who should review these new methods under the Enumerable class?

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
@mairaw I just reviewed this, and pending product team review, this LGTM.

:shipit: when you are ready.

**Review by OmarTawfik — APPROVED** [review]
These LGTM. @VSadov / @karelz does this need to go through dotnet API review?

**Review by VSadov — APPROVED** [review]
LGTM

**Comment by VSadov** [comment]
This is a documentation improvement. 
The APIs themselves are not very new now. I think we have reviewed them long time ago.

**Comment by karelz** [comment]
Yeah, API review is needed only for new API in the code, not for docs.

**Comment by mairaw** [comment]
Yes, we're only catching up with the docs now. @OmarTawfik @VSadov 

Thank you for your review!

**Pull request merged**
