### PR TITLE
Add F# to IDE0005 and IDE0059

### LINKED ISSUE #36552: Update the docs for some IDE diagnostics to reflect F#
Related to [this PR](https://github.com/dotnet/roslyn/pull/69313).

The following diagnostics are also used in F#:
- https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0001
- https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0005 - probably the title should be renamed as F# uses "open" instead of "using", so the word "import" is more correct (and that's the term used internally as well)
- https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0059 - once the referenced PR is merged

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e48732b-1857-b369-201f-a4bd1a030456
* Version Independent ID: 3574cfdd-180f-f263-542b-32695333e4a3
* Content: [IDE0001: Simplify name - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0001)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0001.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0001.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 166835](https://dev.azure.com/msft-skilling/Content/_workitems/edit/166835)

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #36552.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/fundamentals/code-analysis/style-rules/ide0001.md](https://github.com/dotnet/docs/blob/6d86e634f13027314463c476f7f51fd142b440a8/docs/fundamentals/code-analysis/style-rules/ide0001.md) | [Simplify name (IDE0001)](https://review.learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0001?branch=pr-en-us-38765) |
| [docs/fundamentals/code-analysis/style-rules/ide0005.md](https://github.com/dotnet/docs/blob/6d86e634f13027314463c476f7f51fd142b440a8/docs/fundamentals/code-analysis/style-rules/ide0005.md) | ["IDE0005"](https://review.learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0005?branch=pr-en-us-38765) |
| [docs/fundamentals/code-analysis/style-rules/ide0059.md](https://github.com/dotnet/docs/blob/6d86e634f13027314463c476f7f51fd142b440a8/docs/fundamentals/code-analysis/style-rules/ide0059.md) | [Remove unnecessary value assignment (IDE0059)](https://review.learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0059?branch=pr-en-us-38765) |

### CODE REVIEW

**Comment by gewarren** [comment]
@psfinaki Could you review this? Also, I couldn't get IDE0001 to fire. Can you help me with that? This is what I tried:

`let sentence = System.String.Empty`

**Comment by psfinaki** [comment]
@gewarren thanks for this - looks good. 

As for IDE0001, here in an example:
```fsharp
open System

let yesterday = DateTime.Now.AddDays(-1)
let now = System.DateTime.Now // IDE0001: Name can be simplified.

```

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

Once you've resolved the other conversations, you can :shipit:

**Comment by gewarren** [comment]
> @gewarren thanks for this - looks good.
> 
> As for IDE0001, here in an example:
> 
> ```fsharp
> open System
> 
> let yesterday = DateTime.Now.AddDays(-1)
> let now = System.DateTime.Now // IDE0001: Name can be simplified.
> ```

@psfinaki I'm still not seeing IDE0001. @BillWagner Could you try?

image

**Comment by psfinaki** [comment]
Ohhh I know what's going on. This code fix is off by default @gewarren.

Devs need to enable it in the settings: 
image

We hope it will be on by default soon - but one never knows. For now it might be worth adding a note about this.

**Comment by psfinaki** [comment]
Thanks @gewarren :)

**Pull request merged**
