### PR TITLE
Update interpolated-strings.md

### PR DESCRIPTION
**Pull request by iiinnniii**
Correct interpolated-string-syntax.

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thank you @gernotpokorny for making this fix. Awesome to see your first PR on GitHub! The fix will go live probably later today or tomorrow.

**Comment by gernotpokorny** [comment]
:) Great.

Maira Wenzel <notifications@github.com> schrieb am Mo., 11. Sep. 2017 um
02:36 Uhr:

**Comment by gernotpokorny** [comment]
Hello,

I saw another issue on the c#-docu, but I do not know where to report it:

https://msdn.microsoft.com/en-us/library/system.string.format(v=vs.110).aspx

This is the documentation of the String.Format Method.

Have a look at the Controlling spacing example:

int[] years = { 2013, 2014, 2015 };
int[] population = { 1025632, 1105967, 1148203 };
String s = String.Format("{0,6} {1,15}\n\n", "Year", "Population");
for(int index = 0; index<years.Length; index++)
   s += String.Format("{0,6} {1,15:N0}\n",
                      years[index], population[index]);


This is extremely bad practice. I think it is not good to bring examples
with very bad practices. Have a look at this video, it explains why it is
bad practice:

https://www.youtube.com/watch?v=4lFAs6FYTXg

So in a loops always use a StringBuilder.

Do you know where I can report this?

thx


Gernot Pokorny <gernot.pokorny.github@gmail.com> schrieb am Mo., 11. Sep.
2017 um 03:04 Uhr:

**Comment by mairaw** [comment]
Please open a new issue here @gernotpokorny and we'll triage it. We're moving all the documentation to docs, so most likely the fix is going to be made on docs (we'll soon redirect the msdn docs to docs.ms). And if you want to open a PR, you can go to https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7#Remarks and click the Edit button.

**Comment by gernotpokorny** [comment]
Ok cool. I've created a pull request.

https://github.com/dotnet/docs/pulls

Update starting1.cs <https://github.com/dotnet/docs/pull/3154>  #3154

ty

Maira Wenzel <notifications@github.com> schrieb am Sa., 16. Sep. 2017 um
01:07 Uhr:

**Comment by gernotpokorny** [comment]
If I make any mistake with git and github please tell me, because I'm
realively new to git and github and I think it is not easy to learn,
because it is written in C and Unix shell.

thx

Gernot Pokorny <gernot.pokorny.github@gmail.com> schrieb am Sa., 16. Sep.
2017 um 01:41 Uhr:

**Comment by mairaw** [comment]
No worries @gernotpokorny. We'll help you and give you feedback if needed. We really appreciate you taking the time to contribute to our docs. We all started not knowing git and GitHub as well. It takes time. Thanks!

**Pull request merged**
