### PR TITLE
Remove duplicate uid entries

### LINKED ISSUE #2243: Remove duplicate uid entries
Migration activity duplicated some uid entries in meta docs.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #2243 

[Change Script](https://gist.github.com/GuardRex/34bbb6a2856b952ed463dc173509678a)

I spot-checked a handful ... but please ...

## *Review with extreme prejudice!* :grinning:

### CODE REVIEW

**Comment by mairaw** [comment]
Builds seem to like this change. Warnings dropped considerably. But there are still 282 duplicate uid warnings. Can you take a look @GuardRex?

**Comment by GuardRex** [comment]
Sure ... I'll take a look. :eyes:

**Comment by GuardRex** [comment]
@mairaw It didn't match those because the entries aren't identical. For example ...

*docs/add/metadata/Microsoft.Build.BuildEngine/BuildPropertyGroup.meta.md*

Choking on: `Microsoft.Build.BuildEngine.BuildPropertyGroup.#ctor`

... but the entries in the file are ...

```
---
uid: Microsoft.Build.BuildEngine.BuildPropertyGroup.#ctor
ms.author: "susanno"
manager: "douge"
---
```

... and ...

```
---
uid: Microsoft.Build.BuildEngine.BuildPropertyGroup.#ctor
---
```

... since I used a LINQ expression to exactly match for dups, these 282 didn't make the cut.

Gut feeling: 282 is too many for manual mods. I'll bust out some **mad scripts**:tm: on it. I'm almost done with the netfx PR. I'll get this done right after dinner. I'm marking WIP for now.

**Comment by mairaw** [comment]
gotcha! well, anyway the script already saved us from 2k+ manual fixes, which is awesome.

**Comment by GuardRex** [comment]
Closing to work on a different branch.

**Pull request closed without merging**
