### PR TITLE
Fix #24823

### LINKED ISSUE #24823: Not clear how to specify named tuples in a type declaration
Inspired by [this StackOverflow question](https://stackoverflow.com/q/68111045/111794).

How do you specify named tuples as part of a type declaration? For instance, how do I declare a variable of a named tuple type?

```vb
Dim t As (LastName As String, FirstName As String, DOB As Date)
```

or initialize a collection of named tuples:

```vb
Dim lst As New List(Of (LastName As String, FirstName As String, DOB As Date)) From {
    ("Smith", "John", #1/1/2001#)
}
```
Now there is a section on returning named tuples from functions, which does show this syntax; but I don't think it's prominent enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936fd464-c238-3352-c260-da97c3deaeef
* Version Independent ID: 876d507e-a0d9-c36e-2647-7caa5f685861
* Content: [Tuples - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/tuples)
* Content Source: [docs/visual-basic/programming-guide/language-features/data-types/tuples.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/language-features/data-types/tuples.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

### PR DESCRIPTION
**Pull request by zspitz**
## Summary

Expands on how to include tuple names as part of the type declaration.

Fixes #24823

### CODE REVIEW

**Comment by BillWagner** [comment]
These changes look great @zspitz 

Since these samples were last updated, we've added the snippets CI build. The code folder did not have a project, so that is failing.  It should pass by adding a default `vbproj` file in the samples folder. Once you do that, I'll merge this.

**Comment by BillWagner** [comment]
@zspitz 

Thanks for pointing that out. Yes, adding a new project would conflict with the existing one. The right plan is for all of this code to be in the same folder. While moving it, that will introduce build OPS build errors on the related pages. Those are generally quick to fix as well.

If you're interested in doing that, I appreciate it. If not, I can merge and create a new PR to fix the samples. Let me know you're preference.

**Comment by zspitz** [comment]
@BillWagner OK, I'll do it.

**Comment by zspitz** [comment]
@BillWagner How do I resolve the conflicts?

**Comment by BillWagner** [comment]
@zspitz Looking....

**Comment by BillWagner** [comment]
@zspitz 

I've resolved the conflicts on my local copy. I don't have rights to push to your PR.  Can you check the box in the lower right pane for "allow edits by maintainers". Then, I can push the updates and it's all set.

**Comment by zspitz** [comment]
@BillWagner "Allow edits by maintainers" is checked. I unchecked and checked it; perhaps that might make a difference.

**Comment by BillWagner** [comment]
@zspitz Your branch is now up to date. Thanks for helping us work through all these hurdles.

**Comment by BillWagner** [comment]
@zspitz Here are the warnings from the current build:



File | Status | Preview URL | ms.author | ms.prod | ms.technology | ms.service | ms.subservice | Details
-- | -- | -- | -- | -- | -- | -- | -- | --
docs/visual-basic/programming-guide/language-features/data-types/tuples.md | Warning | View | kdollard | dotnet-visualbasic |   |   |   | Line 155: [Warning] It looks like your code snippet was not rendered. Try range instead.Line 159: [Warning] It looks like your code snippet was not rendered. Try range instead.
docs/visual-basic/whats-new/index.md | Warning | View | kdollard | dotnet-visualbasic |   |   |   | Line 170: [Warning] Invalid code snippet link: '../../../samples/snippets/visualbasic/programming-guide/language-features/data-types/tuple-returns.vb'.Line 174: [Warning] Invalid code snippet link: '../../../samples/snippets/visualbasic/programming-guide/language-features/data-types/tuple-returns.vb'.

**Comment by BillWagner** [comment]
woot!  Thank you @zspitz

**Review by BillWagner — APPROVED** [review]
Thanks for all the work here @zspitz 

I've given this a final review, and I'll :shipit: now.

**Pull request merged**
