### PR TITLE
WIP - Interactive Sample

### PR DESCRIPTION
**Pull request by luisquintanilla**
Testing interactive samples for ML.NET

[Preview Link](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net?branch=pr-en-us-14073)

### CODE REVIEW

**Comment by mairaw** [comment]
It will be hard to make the online version of Try .NET work @luisquintanilla without the scaffolding feature that should come soon. Try .NET in docs only has built-in support for a couple of namespaces, so you'd have to fully qualify your APIs and still might not work because you also need the data for this to work.
I think you should look into the local Try .NET experience with @BillWagner and that would go to https://github.com/dotnet/try-samples and run on the user's machine.

**Comment by luisquintanilla** [comment]
Thanks @mairaw . I'm planning on closing this PR. I was only testing what the integration might look like for the online version but will look at try-samples and work with Bill to explore how Try fits into our content.

**Comment by BillWagner** [comment]
@luisquintanilla Are you still planning to close this one?

**Comment by luisquintanilla** [comment]
@BillWagner yep. Closed.

**Pull request closed without merging**
