### PR TITLE
Update csharp compiler options pages for VS 2019

### PR DESCRIPTION
**Pull request by BillWagner**
Contributes to #16046

### CODE REVIEW

**Comment by mairaw** [comment]
Changed the base here

**Review by mairaw — APPROVED** [review]
LGTM

**Comment by BillWagner** [comment]
Thanks @mairaw 

I hate that it chooses the default branch, and not branch I started from.

**Comment by BillWagner** [comment]
Thanks @mairaw I'll merge once the build finishes.

**Pull request merged**
