### PR TITLE
readded Docs to breadcrumb

### PR DESCRIPTION
**Pull request by mairaw**
We still need to keep Docs on the breadcrumb for now.

### CODE REVIEW

**Comment by mairaw** [comment]
Looking at the staging site, I'm wondering if we still wanna keep the Documentation entry. Shouldn't we just have Docs / .NET / ,NET Core Guide, for example?

Here's how it looks now:
image

/cc @rpetrusha @BillWagner

**Comment by rpetrusha** [comment]
`Documentation` certainly doesn't add anything, and merely states the obvious. I'd be in favor of eliminating it.

**Comment by BillWagner** [comment]
It looks cluttered to me. I'd be in favor of removing it.

**Comment by mairaw** [comment]
Ok, good. We're all in the same page. I'll change that.

**Pull request merged**
