### PR TITLE
Fix typo in dependabot configuration

### PR DESCRIPTION
**Pull request by jurre**
Hi, the property to configure the max number of PR's Dependabot will open is `open-pull-requests-limit`. This should fix the CI failure here: https://github.com/dotnet/docs/runs/797022875

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=19068) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=19068) before we can accept your contribution.<br/><br/>:x: jurre [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=19068)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=19068) it.</sub>

**Comment by jurre** [comment]
(Double checking with our legal team that I can sign the CLA, feel free to re-apply the changes in this PR under your own name if it's taking too long)

**Comment by BillWagner** [comment]
Thank you @jurre 

I'll start by making the corresponding changes in our other repositories, and then come back to this one.

**Review by BillWagner — APPROVED** [review]
Thanks for your help @jurre 


I'll :shipit: now.

**Pull request merged**
