### PR TITLE
changing link of cloud native page

### PR DESCRIPTION
**Pull request by intrepidsoldier**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mvelosop — COMMENTED** [review]
Hi @intrepidsoldier, I think the change is relevant, considering too that the original takes to a Gartner publication that's not freely available.

However, there are five more cloud-native links that should point to the same site.

Thanks

**Comment by mairaw** [comment]
You have a good point @intrepidsoldier. I'd remove the links from the other occurrences.

**Comment by intrepidsoldier** [comment]
Is there anything else required from me?

**Comment by mairaw** [comment]
@mvelosop if I merge this as-is can you take care of removing the other occurrences of that same link on this topic afterward?

**Comment by mvelosop** [comment]
Sure!

**Comment by mvelosop** [comment]
Done right here @mairaw.

**Review by BillWagner — APPROVED** [review]
Reading through all the comments and updates, this is ready to :shipit:

Thanks for your patience @intrepidsoldier  We appreciate your contribution to Docs.

**Pull request merged**
