### PR TITLE
fix image problem + some editing

### LINKED ISSUE #7744: Figure 2-3 doesn't fit on my screen and there's no horizontal scroll bars.
Figure 2-3 doesn't fit on my screen and there's no horizontal scroll bars. I tried it on recent versions of Chrome and Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3befff27-c4fc-a699-90b3-903ce60234af
* Version Independent ID: 71ff10df-c0b0-9497-e448-82388ef1b1a1
* Content: [What is Docker?](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined)
* Content Source: [docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #7744

### CODE REVIEW

**Comment by mairaw** [comment]
@CESARDELATORRE this still doesn't solve the image problem. Can I resize the images to make them fit better?

**Comment by CESARDELATORRE** [comment]
Sure! No issues at all about re-sizing the images! :)

**Review by rpetrusha — APPROVED** [review]
Other than resizing the image, @mairaw, this looks good. I'll approve and you can merge once the image is resized.

**Comment by mvelosop** [comment]
I'll try to fix it adding some responsiveness, so it fits better to the device's screen.

**Comment by mvelosop** [comment]
@mairaw it's actually a css problem from the table the current markup generates, it can be solved with a little html/css and it would also be responsive, so the table would colapse to a single column for small devices.

NOW:
image

FIXED:
image

Is it ok to have html/css in docs? (ask because I saw the submitted one was removed)

**Comment by mvelosop** [comment]
BTW, this markup is different from the original one,

**Comment by mairaw** [comment]
Thanks @mvelosop but that didn't fix the issue. See the page at https://review.docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined?branch=pr-en-us-7777.

We avoid HTML as much as we can in the articles and I think resizing would probably be better in this case.

**Comment by mvelosop** [comment]
Couldn't get to see the preview (unauthorized). 🙁

Anyway, resized the images an reverted to regular markdown. If this doesn't work we could just go to a two rows table, instead of a two column one.

Best.

**Review by mvelosop — APPROVED** [review]
I just resized the images to half  size, this should fix it.

**Comment by mairaw** [comment]
Yep, thanks @mvelosop!

image

**Pull request merged**
