### PR TITLE
Add documentation about new ReadyToRun publish options

### PR DESCRIPTION
**Pull request by davidwrighton**
- Composite R2R
- Symbol generation
- Exclusion from R2R
- Updated cross-targetting details

### CODE REVIEW

**Comment by davidwrighton** [comment]
@mangod9, @trylek

I think documenting the composite, symbol generation and r2r excludes features are the right ones to doc at this time. @trylek, can you tell me if there are any other details about symbol publishing that I should be documenting?

**Review by trylek — DISMISSED** [review]
LGTM, thanks for improving the documentation David! AFAIK you've covered the important bits, I'm not aware of any other user-facing SDK capabilities regarding Crossgen2. At some point it might be useful to document the E2E symbol-related scenarios but that's beyond the scope of your pending change.

**Comment by davidwrighton** [comment]
@trylek, could you review the additional change I made about the symbol generation?

**Review by trylek — APPROVED** [review]
The additional delta looks good to me too, thanks David!

**Review by trylek — APPROVED** [review]
Thanks for adding the clarifying comment!

**Pull request merged**
