### PR TITLE
Porting from MSDN

### PR DESCRIPTION
**Pull request by stevehoag**
Previously reviewed for content

### CODE REVIEW

**Comment by stevehoag** [comment]
@mairaw  Build is complete and now showing up on stage. All previous issues addressed. Finally ready to merge?

**Comment by mairaw** [comment]
Ok, things are looking good now. But I do have anoother question now:
-  You moved the content of the gc-overview file to the index one inside garbagecollection right?
So now we have two topics with the same GUID. You should apply the redirection metadata to the original one since folks could have links to that.

**Comment by stevehoag** [comment]
@mairaw  Shouldn't be a problem - I found one topic that was linking to it and fixed the broken link.

**Comment by mairaw** [comment]
But you now have two valid topics with the same GUID and the old one is still searchable and reachable, just not on the TOC. You need to apply the redirect on the old one.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.version?branch=pr-en-us-975)

**Comment by mairaw** [comment]
LGTM

**Comment by stevehoag** [comment]
Closes #228

**Pull request merged**
