### PR TITLE
fix: HTTP -> HTTPS for go.microsoft links

### PR DESCRIPTION
**Pull request by nschonni**
## Summary

Contributes to #4504

edit by @mairaw: added issue number

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
LGTM. Thanks @nschonni!

**Comment by mairaw** [comment]
Something went wrong with the build. Trying again.

**Comment by nschonni** [comment]
Random guess would be something in the branch naming like the arrow is messing it up, but I can't see if there is anything in the logs

**Comment by mairaw** [comment]
Oh good point @nschonni! I was looking at the logs and this was the error message:
An exception occurred during the build process. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot, exception details: Message id: RepoId: a3bda507-3390-de91-8f7f-26f90f4e5fc8, BuildId: 201910290606117496-15491, BuildType: PullRequest, Action: Publish (correlation id: F26D393F-4904-47F0-A9CA-464266267700.6.50), details: System.ArgumentException: Illegal characters in path. at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) at System.IO.Path.Combine(String path1, String path2, String path3, String path4) at Microsoft.OpenPublishing.Build.DataAccessor.Git.GitHubAccessor.GetContentGitUriCoreAsync(GitGetContentUriRequest request) in d:\a\1\s\Libraries\DataAccessor.Git\GitHubAccessor.cs:line 128 at Microsoft.OpenPublishing.Build.MessageProcessors.ChangedFileInfoResolver.<QueryFileInfoAsync>d__6.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\Components\ChangedFileInfoResolver.cs:line 67 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.Common.TaskHelper.<SelectCoreAsync>d__7`2.MoveNext() in d:\a\1\s\Libraries\Common\TaskHelper.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.Common.TaskHelper.<SelectInParallelAsync>d__6`2.MoveNext() in d:\a\1\s\Libraries\Common\TaskHelper.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.MessageProcessors.ChangedFileInfoResolverHelper.<QueryFilesInfoAsync>d__0.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\Components\ChangedFileInfoResolverHelper.cs:line 19 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.MessageProcessors.ResolveFileInfoHelper.<ResolveFileInfosToDisplayAsync>d__0.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\Components\ResolveFileInfoHelper.cs:line 80 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.MessageProcessors.HostedEnvironmentMessageProcessorWithReportGeneration.<ProcessInHostedEnvironmentAsync>d__4.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\HostedEnvironmentMessageProcessorWithReportGeneration.cs:line 175 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.MessageProcessors.HostedEnvironmentMessageProcessor.<ProcessAsync>d__10.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\HostedEnvironmentMessageProcessor.cs:line 95 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.MessageProcessors.MessageProcessorWithCachedRepository.<ProcessAsync>d__5.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\MessageProcessorWithCachedRepository.cs:line 49 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.MessageProcessors.MessageProcessorWithForceCancellation.<>c__DisplayClass1_0.<<ProcessAsync>b__0>d.MoveNext() in d:\a\1\s\Libraries\MessageProcessors\MessageProcessorWithForceCancellation.cs:line 28 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OpenPublishing.Build.Common.TaskHelper.<RunTaskWithCancellationTokenAsync>d__16.MoveNext() in d:\a\1\s\Libraries\Common\TaskHelper.cs:line 286 --- End of stac

**Comment by mairaw** [comment]
Can you create a new branch based on this one and resubmit?

**Comment by nschonni** [comment]
@mairaw created #15552 without the > in the branch name to see if that fixes it

**Comment by mairaw** [comment]
Lesson learned!

**Comment by nschonni** [comment]
Don't know if there is a repo you can file a bug on for it. It's likely because Windows doesn't like that as a character in paths, but OSX/Linux doesn't mind.

**Pull request closed without merging**
