### PR TITLE
Remove wrench/unwritten topics from the published docs

### LINKED ISSUE #1990: Remove wrench/unwritten topics from the published docs
We have a few "wrench" topics (such as https://docs.microsoft.com/en-us/dotnet/articles/core/versions/servicing) or some unwritten topics like https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/.

We need to:
1 - Remove the topics from the repo
2 - Redirect them to a similar topic or a generic place a similar one cannot be found
3 - Make sure we have issues opened tracking the topics we were planning to do (some of them have links to the issue already)
4 - Remove them from the TOC file(s)

The F# tutorials one could probably be transformed in just a TOC node without content associated with it for now.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #1990
* Metadata redirects in the topics. Topics remain, except for two that were explicitly called out for deletion (see below). Redirects are usually to the nearest active *index.md* page.
* Comment out topics in TOC
* Confirm open issue exists for each. Two missing (see below).

Removed:
* *C# Concepts*
   https://github.com/dotnet/docs/blob/master/docs/csharp/concepts.md
   See: https://github.com/dotnet/docs/issues/608#issuecomment-264216732

* *Using Visual Studio to create, debug, and deploy applications*
   https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/create-debug-deploy.md
   See: https://github.com/dotnet/docs/issues/948#issuecomment-282825300

New content issues created for:
* *Writing .NET Core console apps using the CLI tools: An advanced step-by-step guide*
   https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-console-app-tutorial-advanced.md
   Tracking issue: https://github.com/dotnet/docs/issues/1994

* *Methods and Lambda Expressions*
   https://github.com/dotnet/docs/blob/master/docs/csharp/methods-lambda-expressions.md
   Tracking issue: https://github.com/dotnet/docs/issues/1995

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @GuardRex.
 
For the two you've created issues, they were originally tracking the following issues:
1 - https://github.com/dotnet/docs/issues/180
2 - https://github.com/dotnet/docs/issues/488

IMO we don't need https://github.com/dotnet/docs/issues/1994 any longer (although we can later think of other CLI topics we still need) and https://github.com/dotnet/docs/issues/1995 is a duplicate of 488

**Comment by GuardRex** [comment]
@mairaw Ah ... thanks. Those were hard to spot b/c the names didn't match the latest topic names and there wasn't a "new content" label on one of them. I made their titles match and fixed the missing label. I closed the two that I opened. I think the build will be good now that the C# Interactive TOC is removed. I'll keep an :eye: on it.

**Comment by mairaw** [comment]
Should we also include this one: https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/? It's not actually a "wrench" topic but it doesn't have any content. /cc @cartermp

**Comment by GuardRex** [comment]
@cartermp, do you want the *F# Tutorials* topic pointed down to *Getting Started* or up to *F# Guide*?

Looks like there are five total:

* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/
* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/asynchronous-and-concurrent-programming/
* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/introduction-to-functional-programming/
* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/using-fsharp-in-visual-studio/
* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/using-fsharp-on-azure/using-fsharp-on-azure-service-fabric

**Comment by cartermp** [comment]
@GuardRex Let's point it up for now.  I think I intended on writing a blurb about what to choose there, but at this point it's just unneeded nesting.

**Comment by GuardRex** [comment]
@cartermp I didn't see *new-content* issues for the F# doc stubs. There's only one that has links that will require updating when the doc is created (outside of the TOC). I created https://github.com/dotnet/docs/issues/2016 to cover it. If you want stub issues for the other four, let me know, and I'll whip them right up.

I have a concern about removing 2nd level headings from the TOC like this: I'm concerned that orphaned 3rd level headings will group incorrectly with the prior 2nd level headings (or orphan 4th level topics might group with the prior 3rd level). It might be ok, but it could :boom:, too. I'll check the review site TOC to see how things fared after the build runs.

**Comment by cartermp** [comment]
Sounds good.  I think stubbing is a fine solution.

**Comment by GuardRex** [comment]
Issues tracking stubs generated:
* F# Tutorials
  - https://github.com/dotnet/docs/blob/master/docs/fsharp/tutorials/index.md
  - https://github.com/dotnet/docs/issues/2018
* Asynchronous and Concurrent Programming in F#
  - https://github.com/dotnet/docs/blob/master/docs/fsharp/tutorials/asynchronous-and-concurrent-programming/index.md
  - https://github.com/dotnet/docs/issues/2019
* Using F# in Visual Studio
  - https://github.com/dotnet/docs/blob/master/docs/fsharp/using-fsharp-in-visual-studio/index.md
  - https://github.com/dotnet/docs/issues/2020
* Using F# on Azure Service Fabric
  - https://github.com/dotnet/docs/blob/master/docs/fsharp/using-fsharp-on-azure/using-fsharp-on-azure-service-fabric.md
  - https://github.com/dotnet/docs/issues/2021

**Comment by GuardRex** [comment]
@mairaw I think with the F# round of updates, it's ready for another look. :eyes:

**Review by mairaw — APPROVED** [review]

**Pull request merged**
