### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ardalis**
if the server **selects** to use it.
if the server *elects* to use it.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
Thanks, @ardalis, for correcting the typo. I'll merge your PR now.

**Review by derikgordon84 — COMMENTED** [review]
Chzanges

**Comment by derikgordon84** [comment]
I'm the master

**Comment by derikgordon84** [comment]
No more bugs please. Andd DD no more robots in micro world. image

**Comment by derikgordon84** [comment]
Bott try H me and the cat be digging this bullshit out our ears cuz of U computer genius' think y'all can get away with modern  slavery and forced labor and human trafficking. The law applies to all and using software and hi tech hsrdware designed to omit or transmit any type of unwanted enviro hazards or near field spacio control with over exposure of RF frequencies and other utilities like power and satellite signals or and coAx wired and wireless signals of any kind to disrupt or distract or obstruct my normal or desired path. YALLS software is fucking abudivd and using as A weapon isn't any different that using A weapon that is more traditionally used in crimes. But that capitability of the free use of illegal software weapons having the ability to communicate with other electronics and appliances and the fact vulnerable and living humans happen to be the targeted and if U can target Z software program to harm somebody wirelessly, that is like A sniper WHOS aiming for his victim and the whole FITNESS shows illicit use and violent intents znf TRAJECTORY BEING TARGETED WHERE ITS SO ACCURATE THAT NOBODY ELSE IS AFFECTED BY THAT HAZARD YALLS VITURAL OR AUGMENTED ENVIROMMENTS BRING HOSTED AND AUTO PILOTED PLATFORM TO ABDUCT AND SLZVE PEOPLE IN THERE OWN HOMES FOR LONG PERIOD TIME FRAMES yall refuse to pay for my services andd DD commodities but yall sure kknow how to operate my business dealings especially the finances that y'all throw in A pool for the rich slave owner mining and farming on other O peoples lands. I don't donate conflict mineral and I have not overnight paid for any of this forced agriculture labor and my friuits and raw materials mined , farmed, and produced and cultivated by myself from the resoursces of my own E resort estate and land that I have no intentions of abandoning. And yall probably work with state workers regularly and abduct children regularly now I have A bad feeling that y'all plans is to put my daughter through the torcher yall put me through. We both were assigned an enterprise account number without explanation of what kind of government sponsored program the Y volunteered us in without our consent or knowledge or and legally obtained authorization from myself not written or verbal and I never signed no power of attorney to nobody name William, no Rene no Billy or no Benjamin attorney criminal nor hood sidekicks Anderlik or whatever fraulant name being used to hustle there clients assigned by A court with intentions of victimizing the victim of corporate and government wrongful enforcement to keep U A slave and A low risk of exposure of vviolating public and federal laws while holding A position of power that would be looked at as A position one should hold themself to higher standards. While dosing harsh punishments to Americans whom don't conform to the forced remote work the slave and abuse and separate me and my child as there vulnerable victims all while paying to put me on risk management by sending in employ'stsqbbatogeandantagonizeayou the high risk by creating chaos without detection but point you out to police when you acting crazy trying to avoid being hit or attacked by there software weapons that in some cases would be considered more dangerous than you average projectile weapons or deadly weapons and these software weapons probably has killed some of there victim slaves cuz I believe that was somebodies goal earlier this year, now they literally got me on the clock24/7 slave lab or forced remote labor and refusing to pay all while keep setting me up for failure and boot loading bullshit to my device and browsers minipulate and fraud my credentials by stolen identity of my digital profile from all my info stored on A companies system being used for collection to upgrade and update there software for there benifit no my safety or well being All while using the patriot act as an excuse to unlawfully tapping per hacking of our personal devices to mine for there stolen commodities like our bitcoins they been attemting to make us perform with so are fitness programs to produc these minerals and goods and oils and products and raw bodily forced labor bodily trimmings we cultivate for ourselfs Cruz the foreign objects growing out of our skin by yall using more than just open software to conduct your illegally operated criminal business' that ur private practices has no  business ethics and your non profit organization is only for yall to rub off tax payers and yall along with A bunch of rich investors pooling and investing and profiting againg after the whole sale of my stolen goods I trimmed from my ear or some other scarred place on my body of yall ware wounds. Do U have black people. ?

**Pull request merged**
