### PR TITLE
Changed wrong installation path in documentation.

### PR DESCRIPTION
**Pull request by pavinan**
Changed  %LocalAppData%\.dotnet to  %LocalAppData%\Microsoft\dotnet.

### CODE REVIEW

**Comment by BillWagner** [comment]
@blackdwarf Can you verify the change in directory?

**Comment by blackdwarf** [comment]
LGTM

**Comment by BillWagner** [comment]
closing and reopening to kick off a build.

**Comment by mairaw** [comment]
Thanks @pavinan for your contribution!

**Pull request merged**
