### PR TITLE
Add content for config source gen with interceptors

### LINKED ISSUE #36939: Extend config extensions doc with binding source generator info
- https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-6/#configuration-binding-source-generator-improvements
- https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration
- https://github.com/dotnet/docs/blob/b8f805b78dc90ca6339d18d0d404a3fff9c01453/docs/core/extensions/configuration.md
- ASP.NET https://github.com/dotnet/AspNetCore.Docs/issues/30215

---
[Associated WorkItem - 317207](https://dev.azure.com/msft-skilling/Content/_workitems/edit/317207)

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

- Extend config extensions doc with binding source generator info

Fixes #36939, /cc @ericstj

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/extensions/configuration-generator.md](https://github.com/dotnet/docs/blob/3d6d3bb5553b98aeb81eb925269f01da5b8ec55c/docs/core/extensions/configuration-generator.md) | [docs/core/extensions/configuration-generator](https://review.learn.microsoft.com/en-us/dotnet/core/extensions/configuration-generator?branch=pr-en-us-42994) |
| [docs/core/extensions/configuration.md](https://github.com/dotnet/docs/blob/3d6d3bb5553b98aeb81eb925269f01da5b8ec55c/docs/core/extensions/configuration.md) | [docs/core/extensions/configuration](https://review.learn.microsoft.com/en-us/dotnet/core/extensions/configuration?branch=pr-en-us-42994) |

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet/area-extensions-configuration @tarekgh @eiriktsarpalis cc @eerhardt @steveharter

**Review by tarekgh — APPROVED** [review]
The changes LGTM. Thanks @IEvangelist!

I have a suggestion but I'm not sure if it is worth adding. The provided sample is good, we can show a sample of the generated source too with warning the users may not get exact generated code as the source gen is evolving.

Also, using `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` in the project will make the build process keep the generated code that allow users to inspect it.

**Comment by IEvangelist** [comment]
> EmitCompilerGeneratedFiles

Hi @tarekgh - thanks for the quick review. I just tried adding the `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` but even after multiple forced clean/builds, it is not working.

Here's the error I'm seeing:

<details>
<summary>Exception details</summary>
```
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error : Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\david\source\repos\docs\docs\core\extensions\snippets\configuration\console-binder-gen\obj\Debug\net8.0\generated\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator'.
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

</details>

**Comment by tarekgh** [comment]
> I just tried adding the <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles> but even after multiple forced clean/builds, it is not working.

`EmitCompilerGeneratedFiles` is documented  here https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview and worked all the time for me. Could your machine not be enabled for long paths? https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

**Pull request merged**
