### PR TITLE
Publish the VB Language spec

### LINKED ISSUE #1562: Publish VB Spec in Markdown
This is a sub-issue for #1561 

The VB Team has published the language specification in markdown format [here](https://github.com/dotnet/vblang/tree/master/spec)

We should publish this version in docs.microsoft.com

/cc @stevehoag @AnthonyDGreen

### PR DESCRIPTION
**Pull request by BillWagner**
Fixes #1562

This publishes the markdown source from the vblang repository on docs.

The content is from the dependent repo, so reviews will need to happen on the review site.

/cc @AnthonyDGreen

### CODE REVIEW

**Comment by rpetrusha** [comment]
Closing and reopening to trigger new build.

**Comment by BillWagner** [comment]
I looked at the generated markdown this morning, and it looks good on the review site.  

Comments on the metadata or other sections?

**Comment by AnthonyDGreen** [comment]
How do I view this as externals would see it rendered?

**Comment by BillWagner** [comment]
@AnthonyDGreen The build from this PR is on the review site. That's currently internal only. I sent you the link in email this morning.

**Comment by rpetrusha** [comment]
@AnthonyDGreen, the "All checks..." section below includes an "OpenPublishing.Build" validation stage. Its Details link opens a page that has a list of URLs of the pages built as a result of the PR. They're preview rather than production pages, but they are identical to the production pages that will be built if the PR in its current state is merged and promoted to live.

**Comment by AnthonyDGreen** [comment]
I followed the links. LGTM. I had hoped to break out Overload resolution into its own page since that topic gets a lot of interest. But I don't imagine that would be a problem to add later, right?

**Review by AnthonyDGreen — APPROVED** [review]

**Comment by BillWagner** [comment]
@AnthonyDGreen You are correct, responding to changes will be easy.  I'm watching the VBLang repo, so I should see when you make that update. Just to be sure, if you @ mention me, I'll make sure to update the published spec when I see it.

**Pull request merged**
