### PR TITLE
Update portability-analyzer.md

### PR DESCRIPTION
**Pull request by chenyu777**

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer?branch=pr-en-us-1155](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer?branch=pr-en-us-1155)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C16%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610161602456391-1155%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer?branch=pr-en-us-1155](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer?branch=pr-en-us-1155)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C21%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610212315593834-1155%5Cworkflow_report.html).

**Comment by rpetrusha** [comment]
@mairaw LGTM

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer?branch=pr-en-us-1155](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer?branch=pr-en-us-1155)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C22%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610220643539237-1155%5Cworkflow_report.html).

**Pull request merged**
