### PR TITLE
unity does .net standard 2.0

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
https://docs.unity3d.com/Manual/dotnetProfileSupport.html

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by terrajobst** [comment]
This looks like a great addition to me but I'm not an expert in Unity to check this.

@JonathanHUnity, @joncham, @joshpeterson: does this look right to you?

**Review by terrajobst — APPROVED** [review]
LGTM, but @dotnet/nsboard-unity needs to sign off here too.

**Comment by joncham** [comment]
We currently do not expose a TFM. Right now we expose two profiles that users can target: .NET Framework 4.x (right now 4.7.1) and .NET Standard 2.0.

**Comment by joncham** [comment]
In that case then yes, 2018.1 was first version where we officially supported .NET Standard 2.0.

**Comment by mairaw** [comment]
What about the other versions of .NET Standard @joncham as the changes in this PR indicate?

**Comment by terrajobst** [comment]
@joncham can correct me but I believe .NET Standard 2.0 is the first version of .NET Standard that Unity supports (as .NET Standard 1.x uses the `System.Runtime` assemblies which even Mono supported fairly late only, so I don't think Unity had this before they moved to a later build of Mono).

**Review by terrajobst — APPROVED** [review]

**Comment by mairaw** [comment]
If that's the case, then let's update the PR to just include that version starting with 2.0.

**Comment by mairaw** [comment]
I might be giving the wrong suggestion here then. I think you're right @dzmitry-lahoda.

**Comment by terrajobst** [comment]
I wouldn't do blank cells to the left. We used to do that and it confused everyone.

**Comment by mairaw** [comment]
I'll be merging this then. @terrajobst are you going to implement the same changes in the other assets that show this table?

**Comment by terrajobst** [comment]
Good call. I've just pushed https://github.com/dotnet/standard/commit/b3ff6ec4c3336478edf21dd872904693755644db.

**Pull request merged**
