### PR TITLE
move f# to root folder

### PR DESCRIPTION
**Pull request by tdykstra**

### CODE REVIEW

**Comment by tdykstra** [comment]
/cc: @BillWagner @richlander - moved F# to root folder and renamed Learn F# to F# Guide in toc

**Comment by BillWagner** [comment]
Looks good.

I think there is a tooling issue with the '#' character in the metadata.  @bradygaster Can you advise how we handle that? (It applies to the C# content as well)

**Comment by BillWagner** [comment]
Let's merge this now, and handle the meta data as a separate PR.

**Comment by BillWagner** [comment]
Merged as #647 (after rebase)

**Pull request closed without merging**
