### PR TITLE
Add new help page for WCF trace: warnservicehealthenablednobaseaddress

### PR DESCRIPTION
**Pull request by jiayi11**
@Lxiamail @mconnew

### CODE REVIEW

**Comment by yujayee** [comment]
@rpetrusha @mairaw Do you happen to know what is "ms.assetid" and how is it generated? Thanks!

**Comment by rpetrusha** [comment]
Yes, @yujayee ms.assetid is a GUID that identifies the article. It's a legacy setting that lets us more easily identify a topic in our old publishing system. It's not used for new topics.

**Review by mconnew — APPROVED** [review]

**Review by rpetrusha — CHANGES_REQUESTED** [review]
@yujayee This looks good. It needs to have an entry in the table of contents, though. The TOC file at docs/framework/wcf/diagnostics/tracing/toc.md. And it also needs to have an entry in the Traces Reference at docs/framework/wcf/disagnostics/tracing/traces-reference.md.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
Thanks for adding the two additional files to your PR, @yujayee. I'll merge your PR now. The article should be live sometime tomorrow morning.

**Pull request merged**
