### PR TITLE
Added missing articles to TOCs

### LINKED ISSUE #625: Articles not in the TOC, round 2
After recent changes to the TOC and before Monday's launch, it seems it's time to revisit #514 again.

So, articles that I believe should be in the TOC but aren't:

* [core/app-types.md](https://github.com/dotnet/core-docs/tree/master/docs/core/app-types.md),  [core/packages.md](https://github.com/dotnet/core-docs/tree/master/docs/core/packages.md),  [core/sdk.md](https://github.com/dotnet/core-docs/tree/master/docs/core/sdk.md) 
* [scenarios/solution-authoring/target-dotnetcore-with-msbuild.md](https://github.com/dotnet/core-docs/tree/master/docs/scenarios/solution-authoring/target-dotnetcore-with-msbuild.md) 
* [standard/porting/tooling.md](https://github.com/dotnet/core-docs/tree/master/docs/standard/porting/tooling.md)

I'm not sure where in the TOC do these articles belong now, or whether to include some of them at all, so I won't be creating a PR for this.

### PR DESCRIPTION
**Pull request by svick**
Fixes  #625.

The only remaining article that's not in the TOC is [`core/deploying/reducing-dependencies`](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/reducing-dependencies), but that's intentional per #767.

### CODE REVIEW

**Comment by BillWagner** [comment]
Thank you again @svick 

The additions look great.

/cc @mairaw One of the additions (core/sdk.md) looks like one you are working on, but might not be finished. Can you review and suggest the right next steps?

**Comment by mairaw** [comment]
Thanks @svick. I inherited that topic like this when I took over the tools section. Let's not add this back until I have time to look at that topic. I'll create an issue to keep track of that. Would you mind removing that one for now?

**Comment by mairaw** [comment]
Issue created: https://github.com/dotnet/core-docs/issues/781

**Comment by svick** [comment]
@mairaw Done.

**Comment by BillWagner** [comment]
Thanks @svick :shipit:

**Pull request merged**
