### PR TITLE
VS ref updates to WCF topics

### PR DESCRIPTION
**Pull request by gewarren**
Lots of whitespace removal - recommend viewing diff in CodeFlow.

Preview urls:

[Controlling Resource...](https://review.docs.microsoft.com/en-us/dotnet/framework/wcf/controlling-resource-consumption-and-improving-performance?branch=pr-en-us-7032)
[Core communications...](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fdotnet%2Fframework%2Fwcf%2Fdiagnostics%2Fexceptions-reference%2Fcore-communications-webhost-support%3Fbranch%3Dpr-en-us-7032&data=02%7C01%7C%7C3b6ef68a8a1140aefd3d08d602eb5df4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636699607241482105&sdata=%2BkztOQZcZmfNPLaU%2B9GJVF6Qvk%2BnNfjaKcCB62kEIT0%3D&reserved=0)
[Adopting WCF](https://review.docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/adopting-wcf?branch=pr-en-us-7032)
[Configuring IIS...](https://review.docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-iis-for-wcf?branch=pr-en-us-7032)
[ServiceModel...](https://review.docs.microsoft.com/en-us/dotnet/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe?branch=pr-en-us-7032)

Contributes to #7172

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

You can :shipit: when ready.

**Comment by mairaw** [comment]
Does this warrant a change on ms.date?

**Comment by gewarren** [comment]
@mairaw No, I don't think ms.date should be updated. This PR contains very minor changes and I didn't verify the rest of the topics.

**Comment by gewarren** [comment]
@BillWagner Thank you!

**Pull request merged**
