### PR TITLE
add Microsoft Open Source CoC to our Readme

### PR DESCRIPTION
**Pull request by BillWagner**
Following the instructions here;
https://opensource.microsoft.com/codeofconduct/faq/

cc @mairaw

### CODE REVIEW

**Comment by mairaw** [comment]
The change LGTM. But the page states this:
> Projects in the .NET Foundation are already covered by the [.NET Foundation Contributors Code of Conduct](https://dotnetfoundation.org/code-of-conduct). As such, there is no need for .NET Foundation projects to make any changes.

So do we need to add this here?

**Comment by martinwoodward** [comment]
Agree with @mairaw - as this is a .NET Foundation repo then the [.NET Foundation Code of Conduct](https://dotnetfoundation.org/code-of-conduct) should apply.  Guidance on how to apply the code in your readme is given [here](https://github.com/dotnet/home/blob/master/guidance/readme-guide.md) but basically its:

```
This project has adopted the code of conduct defined by the Contributor Covenant
to clarify expected behavior in our community.
For more information see the 
[.NET Foundation Code of Conduct](https://dotnetfoundation.org/code-of-conduct). 
```

**Comment by mairaw** [comment]
Thanks @martinwoodward. @BillWagner, I've addressed the feedback for you.

**Comment by BillWagner** [comment]
Thanks @mairaw I'll :shipit:

**Pull request merged**
