### PR TITLE
Update source.cs

### PR DESCRIPTION
**Pull request by DiskCrasher**
Renamed dataAdpater variable to dataAdapter.

## Summary

Fixed misspellings.

### CODE REVIEW

**Comment by BillWagner** [comment]
Thanks for making this change @DiskCrasher 

This is one of our older samples that was migrated from an internal system. Now that everything is in GitHub, we've added a CI system for our samples. That CI build is failing because this code doesn't have a .csproj file associated with. If you add a default project file in the same folder, that should fix the error.

Let me know if you can do that. If you don't have time, I'll add it and then merge this PR.

Thanks again for improving our samples.

**Comment by DiskCrasher** [comment]
Please do.

**Comment by BillWagner** [comment]
@DiskCrasher I don't have write access to your fork. So, I made this PR: https://github.com/DiskCrasher/docs/pull/1

If you merge that, this PR will update and I'll merge it.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=27427) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=27427) before we can accept your contribution.<br/><br/>:x: DiskCrasher [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=27427)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=27427) it.</sub>

**Review by BillWagner — APPROVED** [review]
Thanks again @DiskCrasher 

The build is clean, and I'll :shipit: now.

**Pull request merged**
