### PR TITLE
fixed broken links and other minor issues

### PR DESCRIPTION
**Pull request by mairaw**
Added alt text to images, fixed broken links to samples folder, removed unused link, fixed typo 

/cc @conniey

### CODE REVIEW

**Comment by conniey** [comment]
Thanks for the fixes. Now I know relative links do not work.

**Comment by mairaw** [comment]
Just the ones to samples since they're not part of our documentation set, so they need to be absolute URLs. Links to other topics work!

**Comment by BillWagner** [comment]
Looks good (thanks for adding the clarification in which links can be relative and which must be absolute.)

:shipit:

**Comment by mairaw** [comment]
BTW, I left the links pointing to master @BillWagner as the other topics seem to be pointing to master too!

**Comment by BillWagner** [comment]
I think we want to leave the links pointing to master, because that's the direction we're going (and hopefully quickly).

**Comment by mairaw** [comment]
That's what I thought! Just waiting for the build to finish before merging. See if I haven't missed anything else.

**Pull request merged**
