### PR TITLE
eShopOnWeb eBook Update

### PR DESCRIPTION
**Pull request by ardalis**
## Summary

- Adding Web App for Containers
- Removing Service Fabric
- Removing Feature Comparison

### CODE REVIEW

**Comment by ardalis** [comment]
@nishanil this one should be fine to merge.

**Review by nishanil — COMMENTED** [review]
Looks good to me.

**Comment by ardalis** [comment]
Can you approve it as a reviewer, @nishanil

**Comment by BillWagner** [comment]
I can approve. Thanks @nishanil and @ardalis

**Review by BillWagner — APPROVED** [review]
Approving based on @nishanil 's review.

**Pull request merged**
