### PR TITLE
Remove transparent background from images

### LINKED ISSUE #6547: Don't use transparent backgrounds in images
The diagrams are impossible to read in Dark mode because they contain black text and shapes on a transparent background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: fa6385e8-91ad-7949-382f-ca8e03f8201c
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by mvelosop**
## Summary

Set white background and remove alpha channel from images, to remove transparency

Fixes https://github.com/dotnet/docs/issues/6547

### CODE REVIEW

**Comment by mairaw** [comment]
In some cases the ones with transparent background actually looked better:
https://review.docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications?branch=pr-en-us-10451#kubernetes
vs.
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications?branch=pr-en-us-10451#kubernetes

Should we review how they look in dark mode before and after to see which images should keep the transparent background?

**Comment by mvelosop** [comment]
@mairaw, I can't get to see the first link, my MS credentials don't work anymore 😔, anyway I don't think keeping transparent background is an option, because of dark themes.

Anyway, could you add a print screen here to take a look?

**Comment by mairaw** [comment]
Ah sorry!

Current:
image

With this PR:
image

**Comment by mvelosop** [comment]
You're right @mairaw it looks horrible 😝

Ok, but the only "solution" I see is reverting canges for images like this one, that don't have black text.

I think this applies only to logo images in this pages.

Do you think that would be enough?

**Comment by mairaw** [comment]
Yes @mvelosop! I think that sounds great!

**Comment by mvelosop** [comment]
Done @mairaw

**Comment by mairaw** [comment]
Weird, I'm still seeing the kubernetes one with the white background on dark mode and the same number of files changes from commit 1 to commit 2.

**Comment by mvelosop** [comment]
Yep, weird indeed, this is what I see:

image

The new one is on the right, investigating...

**Comment by mvelosop** [comment]
Even clicking on the "View File" button on the second commit shows this:

image

However, it's not shown when viewing the consolidated changes, which is right, just because the second commit reverted the change on those files.

Could that be the reason somehow?

**Comment by Thraka** [comment]
[Internal contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-create-conceptual-art?branch=master) says that conceptual art like diagrams with text should not be transparent and should have a border on the image. It says that transparency is useful for branded icons (such as the icon of an azure service or product) and other non-text artwork

**Comment by mvelosop** [comment]
Thanks @Thraka,

@mairaw, found the reason for that recommendation some days ago 😉

The problem we have now is that even though I reverted to transparent background logos, she still sees them white. Do you have and idea of what could be happening?

Cheers.

**Comment by mairaw** [comment]
I have good instincts 😄 thanks for linking to the official guidelines @Thraka. I'll see if I can revert that image myself.

**Comment by mairaw** [comment]
Let's try a rebuild first.

**Review by mairaw — APPROVED** [review]
When I squashed the commits, it seems to force a rebuild and logo looks normal now.

**Comment by mvelosop** [comment]
😅

**Pull request merged**
