### PR TITLE
:space_invader: Remove unnecessary spaces (#2664)

### LINKED ISSUE #2664: Knock one space off of non-bullet link lists
Per https://github.com/dotnet/docs/pull/2662 ...

@svick has shown us that two spaces at the ends of lines on non-bullet lists will result in line breaks. We've been using three. This is a candidate for a script to run thru the repo and fix all of them in one shot.

### PR DESCRIPTION
**Pull request by mjhoffman65**
## Summary

Removes unnecessary space off of non-bullet link lists.

Fixes #2664

## Suggested Reviewers

@guardrex

### CODE REVIEW

**Comment by dnfgituser** [comment]
Hi, I am closing and re-opening this PR to bump the CLA service. Sorry for the inconvenience!

**Comment by rpetrusha** [comment]
Thank you so much for contributing to the dotnet/docs repo, @mjhoffman65. Your first contribution is a mammoth one! To help us evaluate the changes, would you mind posting the script you ran to trim whitespace as a gist and link it to your PR? Then we can run the script on a smaller subset of files in the repo for testing purposes. Again, thanks.

**Comment by mjhoffman65** [comment]
@rpetrusha, posted the script at https://gist.github.com/mjhoffman65/c992d187ae7ae94511e4e113eb569ad5.  I originally ran it on my Mac, but I also tested running it inside an ubuntu container using docker.  Both returned the same results.  Let me know if you have any questions!

**Comment by mjhoffman65** [comment]
@rpetrusha, I did a rebase to fix a merge conflict last week.  The OpenPublishing.Build check has been waiting for a status to be reported for quite some time now.  Is there anything I can do to resolve this check?

**Comment by rpetrusha** [comment]
@mjhoffman65, unfortunately, no, there's nothing that you can do. We've been having some build issues, which we're hoping to have resolved today.

**Comment by mjhoffman65** [comment]
@rpetrusha, thanks for the update

**Comment by mairaw** [comment]
CI build has had issues for the past few days. Closing and reopening to kick off a new build.

**Comment by mairaw** [comment]
Resolved merge conflicts

**Comment by mjhoffman65** [comment]
Thanks for resolving the merge conflicts @mairaw!

**Review by mairaw — APPROVED** [review]
Thank you for addressing the up-for-grabs issue @mjhoffman65 and sorry for the delay in reviewing it! Your changes look good. Your fix will show up live in the next day or so. My only advice before jumping into new issues is to let us know you're planning on working on that and we can let you know if anything changed,

**Comment by mjhoffman65** [comment]
Thanks @mairaw!  Will do.

**Pull request merged**
