### PR TITLE
Configure titles

### PR DESCRIPTION
**Pull request by BillWagner**
The language specs and proposals did not have titles configured in metadata. This adds them to docfx.json.

It addresses the suggestion report in the OPS build.

This PR gives me feelings of ingenuity, and incredible sadness. It feels like a glorious and necessary hack, but there is a certain ugliness to the solution.

### CODE REVIEW

**Comment by mairaw** [comment]
I was thinking of discussing that with @meganbradley first.

**Comment by mairaw** [comment]
Also, it doesn't seem this worked.

**Comment by BillWagner** [comment]
I see that it's not working the way I'd hoped.

@meganbradley I would think this would have fixed the issue with no title metadata on files that we're incorporating from another repo. Should the validation tool be updated for this type of change?

**Comment by BillWagner** [comment]
I reported this from the build report. See MicrosoftDocs/Feedback#1403

**Comment by BillWagner** [comment]
Since this didn't work, I'm just closing this PR.

**Pull request closed without merging**
