### PR TITLE
See Also links should be on separate lines

### PR DESCRIPTION
**Pull request by svick**

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks, @svick. Could you also fix the typo/spelling error in the last paragraph? (specifiction --> specification, though specifiction could be a great new word). Thanks.

**Comment by GuardRex** [comment]
@rpetrusha Interesting! ... so two spaces will do the trick there. I've been using three; I never checked to see if two would work.

**Comment by svick** [comment]
@rpetrusha https://github.com/dotnet/docs/pull/2659 is already fixing that, see https://github.com/dotnet/docs/pull/2659/files#diff-0814e54d6129ff7ae4ed68f30d815608R41.

**Review by rpetrusha — APPROVED** [review]
Thanks, @svick. And thanks for pointing out that two+ spaces cause a line break, rather than three+.

**Comment by GuardRex** [comment]
Ah! PetrHacks:tm:! lol :grinning:

This is another candidate for a mAd sCrIpT 😵 that would run thru the repo and on these lines that are just one link (no bullet; a topic link, include, or sample) knock that extra space off the end. https://github.com/dotnet/docs/issues/2664

**Pull request merged**
