### PR TITLE
Update Ubuntu install documentation (Ubuntu 24.04 LTS Noble Numbat - Cycle)

### PR DESCRIPTION
**Pull request by dviererbe**
## Summary

* Microsoft package repository:
  - stops shipping .NET staring with Ubuntu 24.04 (see https://github.com/dotnet/core/discussions/9258)
* .NET backports package repository (https://launchpad.net/~dotnet/+archive/ubuntu/backports):
  - add support information
  - list supported versions
  - add (un)install instructions
  - add & change troubleshooting instructions
* Update outdated ARM information
* Update IBM System Z platform support infromation
* Update Dependencies:
  - add ca-certificates (see https://bugs.launchpad.net/ubuntu/+source/dotnet6/+bug/2057982 & https://github.com/dotnet/sdk/issues/39544)
  - change libicu to version 74 for Ubuntu 24.04+ (see https://launchpad.net/ubuntu/noble/+source/icu)

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/install/linux-package-mixup.md](https://github.com/dotnet/docs/blob/023a17fd9339da1820f1c801d0b0b9c02f26a9e0/docs/core/install/linux-package-mixup.md) | [Troubleshoot .NET errors related to missing files on Linux](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?branch=pr-en-us-40612) |
| [docs/core/install/linux-ubuntu-install.md](https://github.com/dotnet/docs/blob/023a17fd9339da1820f1c801d0b0b9c02f26a9e0/docs/core/install/linux-ubuntu-install.md) | [[.NET 8](#tab/dotnet8)](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?branch=pr-en-us-40612) |
| [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/023a17fd9339da1820f1c801d0b0b9c02f26a9e0/docs/core/install/linux-ubuntu.md) | [Get OS version info](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu?branch=pr-en-us-40612) |

### CODE REVIEW

**Comment by dviererbe** [comment]
Force pushed to [fix linting errors](https://github.com/dotnet/docs/compare/db8abd99dce2ccff0e1d73d288ad278ddd850506..1997b5f32a44d736efaa6342aaecd9e48e78c352) and [do minor fixup](https://github.com/dotnet/docs/compare/1997b5f32a44d736efaa6342aaecd9e48e78c352..023a17fd9339da1820f1c801d0b0b9c02f26a9e0).

**Comment by MichaelSimons** [comment]
FYI @richlander, @NikolaMilosavljevic

**Comment by richlander** [comment]
LGTM

Thanks! This is great to see.

There must be an include somewhere that is causing this misleading text with MS to show.

image

In a future revision, I'd like to remove all those dependency lists from the install docs and move them elsewhere. We should make every effort to simplify these docs. That is not today and thanks for updating them!

I noticed a glitch in "[R|r]untime" and "command[s]".

Look carefully at .NET 8

image


And then .NET 6

image

I realize that these are not related to the PR. I'm noticing them for the first time with the new version widget we have, which makes this type of inspection much easier.

**Comment by richlander** [comment]
@adegeo -- Is it possible to get this PR merged and live for tomorrow? We'd like it to be live for Ubuntu 24.04 launch, which (AFAIK) is 4/25.

**Comment by adegeo** [comment]
Sounds good. I'll follow up with fixes for any nits I find. Content looks great though! Thanks @dviererbe

**Review by adegeo — APPROVED** [review]

**Comment by richlander** [comment]
Great. Can we push to live either today or in the morning?

**Comment by adegeo** [comment]
That happens automatically overnight or tomorrow morning, I can't remember which. We can force it at early afternoon if for some reason it didn't do it.

**Comment by adegeo** [comment]
Well it created the PR but didn't merge automatically, so I just merged it. Give it <30 and it will be live.

**Comment by richlander** [comment]
Thanks!

**Pull request merged**
