### PR TITLE
Fixed signature of Where

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/docs/issues/5318.

### CODE REVIEW

**Comment by imba-tjd** [comment]
Hi. Are you a member of MS? If not, so is @CFhM. It's a small change but perhaps he would be happy if this PR were created by him. I didn't do this either. Besides, we havn't finish the discussion yet.

**Comment by svick** [comment]
> Are you a member of MS?

I'm not a Microsoft employee, no. (If you're confused by the "Member" mark, that just means I'm member of the dotnet organization on GitHub, it doesn't signify any formal relationship between me and MS.)

> It's a small change but perhaps he would be happy if this PR were created by him. I didn't do this either. Besides, we havn't finish the discussion yet.

I thought there is nothing to discuss, since it's clear that the current code is wrong and what the code should be.

I also thought that the discussion went on long enough without action and that with the possibility of language barrier, it makes sense for me to create the PR.

**Comment by imba-tjd** [comment]
Yes, you are experienced, but your action is unfriendly to a beginner. Anyway, there aren't any laws fobbid you from doing that and I don't want to argue.

**Comment by BillWagner** [comment]
First of all, thanks to @svick @imba-tjd and @CFhM for reporting and fixing this.

I am one of the Microsoft employees responsible for this project. We're still learning about working with our community and customers in the open. That's especially true when we work with localized versions of the docs. We know we can get better.

I don't think @svick was trying to be unfriendly. That's not our experience when he has contributed in the past. 

I'll chat with others on the docs team, and the international docs teams, and we'll figure out what to do.

Thank you for your patience, and everyone for all the help to make the experience better.

**Comment by imba-tjd** [comment]
Fine. I'll try to be more active next time. @svick I'm sorry.

**Comment by svick** [comment]
@imba-tjd No need to apologize. It's not always clear what the right approach is and questioning is how we as a community learn that.

**Comment by BillWagner** [comment]
Thanks everyone.

I'll :shipit: today.  

We'll figure out ways to get better communicating intent as new issues get created.  We appreciate everyone's patience as we learn.

**Review by BillWagner — APPROVED** [review]
This is the correct prototype. I've approved this change.

**Comment by CFhM** [comment]
Hi，
Thank you for all of you.
Thank you @imba-tjd<https://github.com/imba-tjd>, for helping a freshman, my sincerely.
I’m very happy for my issue was accepted, for the first time, which will encourage me to keep moving on this way.
Thanks again.



----------------------------
CFhM_R [cid:image001.png@01D3EC69.DDDD37A0]
CFhM_R@outlook.com<mailto:CFhM_R@outlook.com> | cfhm.github.io
Beijing Institute of Technology | Sensetime

________________________________

**Pull request merged**
