### PR TITLE
Update dotnet.md

### PR DESCRIPTION
**Pull request by thesmithee**
Removing some erroneous stuff from CLI docs.

### CODE REVIEW

**Comment by stevehoag** [comment]
LGTM

**Comment by mairaw** [comment]
I know you already merged but wouldn't be better to say "Initializes a C# or F# console application project."?

**Comment by blackdwarf** [comment]
@mairaw too late!! :)

**Comment by mairaw** [comment]
:cry:

**Comment by blackdwarf** [comment]
😄

**Comment by BillWagner** [comment]
@mairaw you could make a new issue to drive the fix. 😉

**Comment by blackdwarf** [comment]
Or you could? 😉

**Comment by mairaw** [comment]
This is taking longer than actually making the fix. If you guys agree with my suggestion, I'll make the fix. No problem.

**Comment by blackdwarf** [comment]
@mairaw don't get upset. :)

**Comment by mairaw** [comment]
I'm not upset! :smile: 
But do you agree with my suggestion? Yes or No?

**Comment by blackdwarf** [comment]
Yes.

**Pull request merged**
