### PR TITLE
Updated microservice tutorial

### LINKED ISSUE #1669: NET Core Version Issues
I am running Windows 10 Pro and I am attempting to complete the 'Microservices hosted in Docker' (command-line based) tutorial located at:  
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/microservices  

When I entered 'dotnet restore' I get an error -- warn : The folder ... does not contain a project to restore. 
When I entered 'dotnet run'  I get an error -- error DOTNET1017: Project file does not exist  

While looking for answers (Google search), I realized it might be a versioning issue, so I checked my installation and got the following (seemingly) contradictory information ?  

Can someone tell me how to fix this ?  

When I enter 'dotnet --info' in the project directory, I get 

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

The global.json file contains:  (NOTE:  there is no project.json file)....
{
  "sdk": {
    "version": "1.0.0-rc4-004771"
  }
}

When I enter 'dotnet --info' from another directory, I get 

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

### LINKED ISSUE #2648: Update C# Docker Tutorial
This doc is quite out of date: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/microservices

The yeoman generators are out of date, the docker images are out of date, and the commands are out of date.

### LINKED ISSUE #5700: Docker setup and file
Thought it would run me through the entire process with docker commands. Where is the dockerfile you speak of?  Surely a few extra steps for pulling the docker image and finding this dockerfile would be helpful.  Code wise all worked, i'm currently wondering "The Dockerfile created by the ASP.NET template will serve for our purposes. Let's go over its contents" where this file you speak of is located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948bdbcf-e49f-bd3a-89c4-d83f86cfddc5
* Version Independent ID: 5c6e688e-7afa-1201-2887-e3cae35abe54
* Content: [Microservices hosted in Docker - C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/microservices)
* Content Source: [docs/csharp/tutorials/microservices.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/microservices.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/docs/issues/5700.
Fixes https://github.com/dotnet/core/issues/1669.
Fixes https://github.com/dotnet/docs/issues/2648.

Companion PR that updates samples: https://github.com/dotnet/samples/pull/114.

### CODE REVIEW

**Comment by pkulikov** [comment]
@svick does it also fix #2648?

**Comment by svick** [comment]
@pkulikov Thanks, I didn't know about that issue. Yeah, I think this PR should cover that issue too, I have added it to the "fixes" list.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by mairaw** [comment]
I see that the companion PR was merged and I was planning to push the samples live now, but I won't do that until this is merged. When we merge companion PRs, we should be ready to merge both as soon as builds pass.

**Comment by svick** [comment]
@mairaw If it helps, feel free to revert that PR and I can recreate it.

**Comment by mairaw** [comment]
Don't worry @svick. There weren't any high-pri changes to push so we can wait until next week.

**Review by BillWagner — APPROVED** [review]
This is a really good set of changes @svick 
I'll :shipit: now.  

Thanks for all your contributions to docs.

**Pull request merged**
