### PR TITLE
Standardize sample projects, Part 8

### PR DESCRIPTION
**Pull request by nxtn**
Migrates VB projects...

### CODE REVIEW

**Comment by BillWagner** [comment]
Can you look at this PR @adegeo ?

The build report is clean, but there are two compile errors (I think for outdated APIs)

**Comment by Youssef1313** [comment]
> (I think for outdated APIs)

The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.conflictmode?view=netframework-4.8) for .NET Framework 4.8 shows that the members reported in the compile error exists.

**Comment by Youssef1313** [comment]
https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30456

The third point under "To correct this error" might be relevant.

**Comment by adegeo** [comment]
@BillWagner I'm not sure what is going on with this. It's very odd. The LocateProjects tool is returning this information: (I broke it into multiple lines)

```
0
samples/snippets/visualbasic/VS_Snippets_Data/system.data.linq.conflictmodeenumeration/vb/conflictmodeenum.vbproj
./samples/snippets/visualbasic/VS_Snippets_Data/system.data.linq.conflictmodeenumeration/vb/conflictmode.vbproj
```
conflictmode.vbproj doesn't exist in master or the pull request, I'm unsure where it's finding that file. And even odder, the `dotnet build` command says it ran on that file, producing the error.

**Comment by Youssef1313** [comment]
> conflictmode.vbproj doesn't exist in master or the pull request

Could it be because `proj-8` branch in the fork is behind the master here?

**Comment by adegeo** [comment]
I think you're right. @NextTurn it looks like you've already addressed that project specifically in [part 7](https://github.com/dotnet/docs/pull/19299). @BillWagner I think the LocateProjects tool isn't discovering two project files in the same folder.

**Comment by NextTurn** [comment]
I renamed _**s**nip**d**ump.vbproj_ to _**c**onflict**m**ode.vbproj_ then to _**c**onflict**m**ode**e**num.vbproj_. LocateProjects remembered the previous state (_**c**onflict**m**ode.vbproj_), so I reopened the PR to restart the build.

**Review by BillWagner — APPROVED** [review]
This LGTM. I'll :shipit:

**Pull request merged**
