### PR TITLE
fix toc/breadcrumb issue option #1

### LINKED ISSUE #2263: TOC issue for live site
TOC on live site is sometimes loading the breadcrumb file instead. When I followed up on this issue before, I was told that it was due to an incremental build issue that is being fixed. However, even after a full run with force publish on it's still showing the breadcrumb.  @herohua told me there is a conflict with the TOC.md file and toc.yml file output paths.

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #2263

### CODE REVIEW

**Review by guardrex — APPROVED** [review]

**Comment by mairaw** [comment]
I wanna make sure this works before merging.

**Comment by GuardRex** [comment]
Being Friday, I didn't know if :eyes: were on it, so I did the approval so u wouldn't get held up.

**Comment by mairaw** [comment]
I'm pushing a full build on that branch to see if it's an issue with incremental builds.

**Comment by mairaw** [comment]
and we do work on Fridays and I have special powers if I need to merge 😉

**Comment by mairaw** [comment]
This one seems to remove the breadcrumb: https://review.docs.microsoft.com/en-us/dotnet-new/core/?branch=mairaw-patch-4

**Comment by mairaw** [comment]
Although now I'm not sure if the breadcrumb is not loading because our review site is dotnet-new instead of just dotnet.

**Pull request merged**
