### PR TITLE
Include Windows 10 Version numbers

### PR DESCRIPTION
**Pull request by robertmuehsig**
## Summary

The version namings and version numbers of Windows 10 is not really descriptive, because on some sites (e.g. the [lifecycle description](https://support.microsoft.com/de-ch/help/13853/windows-lifecycle-fact-sheet) page ) the version number is used. The get a better sense what is included or not I added the version number.

Sorry for the huge "diff" - I just added the version numbers in ( ) behind the windows versions.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for contributing to the dotnet/docs repo and adding version numbers, @robertmuehsig. For clarity, could you add "Version" before the version numbers? If you'd like, we can make this change for you.

The overall formatting of this topic is problematic. We'll address it in our next scheduled sprint, which begins on Monday, June 11.

**Comment by robertmuehsig** [comment]
Yeah - the formatting is quite bad, but I added "version" in front of the number.

**Review by rpetrusha — APPROVED** [review]
Thank you, @robertmuehsig, for making the additional changes. We'll merge your PR now. Changes should appear live on docs.microsoft.com in the next day or two.

**Comment by robertmuehsig** [comment]
Thanks!

**Pull request merged**
