### PR TITLE
CC179791: Replacing HTML code by | inside codeblock

### PR DESCRIPTION
**Pull request by v-maudel**
Github contributor reported visible HTML code inside codeblock.

### CODE REVIEW

**Comment by v-maudel** [comment]
Hi @KathleenDollard, @mairaw , can you please help us by approving and merging this PR?
Regards

**Comment by mairaw** [comment]
Thanks @v-maudel.  This is not the right fix and it's duplicate of #16526.

**Comment by v-maudel** [comment]
Thanks @mairaw , actually, now I see that PR, it was created byt the same contributor that submitt the changes in a locale repo. 
Although, I proposed the change from HTML code to | only because it is inside codeblock and it shouldn't be escaped.

**Comment by v-maudel** [comment]
Thanks @mairaw , actually, now I see that PR, it was created byt the same contributor that submitted the changes in a locale repo.
Although, I proposed the change from HTML code to | only because it is inside codeblock and it shouldn't be escaped.

**Pull request closed without merging**
