### PR TITLE
Update VS refs in data/wcf folder

### PR DESCRIPTION
**Pull request by gewarren**
- deletes low PV windows store app topic
- adds note about template availability in VS 2017
- add Next Step buttons to quickstart topics
- improve project template instructions
- split split Add New Item into Add > New Item (same for Add Service Reference)

Contributes to #6923 
Contributes to #7172

### CODE REVIEW

**Review by douglaslMS — APPROVED** [review]
Since the diff is a bit overwhelming, I'm going to trust your subject matter expertise!

**Comment by gewarren** [comment]
@douglaslMS Thank you!

**Comment by mairaw** [comment]
@gewarren is this one still WIP?

**Comment by gewarren** [comment]
@mairaw Yes, I haven't figured out what to do about the WCF Data Services template that's not in VS 2017 any more.

**Comment by mairaw** [comment]
ah gotcha @gewarren!

**Comment by gewarren** [comment]
I am OOF next week but this is ready to go from my POV.

**Pull request merged**
