### PR TITLE
Trim redirects

### PR DESCRIPTION
**Pull request by gewarren**
Removes 1561 redirects of about 3150 total.

The first commit formats the redirection file without deleting anything. The [2nd](https://github.com/dotnet/docs/pull/21789/commits/75f6eea758d30a83c8ccb1ce7e2ea99a65e9654e) and [3rd](https://github.com/dotnet/docs/pull/21789/commits/7fbee750643d17f05eb3d3850de8ab3f224767f8) commits, which were limited to checking 50 redirects each, provide the best diffs. The 4th commit is for all remaining redirects.

The attached file shows the number of page views for each in the last 90 days. (-1 means the URL was invalid for some reason; in this case, the redirect was not deleted.)

[dotnet-page-views.txt](https://github.com/dotnet/docs/files/5631331/dotnet-page-views.txt)

This PR replaces #21779, which was reverted in #21784.

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
LGTM

**Comment by gewarren** [comment]
Thanks again Tom!

**Comment by xtqqczze** [comment]
@gewarren How was dotnet-page-views.txt collected? As explained in https://github.com/dotnet/docs/issues/21816#issuecomment-738872603 I don't how these statistics can be accurate.

**Comment by gewarren** [comment]
@xtqqczze I queried Azure Data Explorer for page views for the URLs (in any locale). I'll revert the changes I made to the redirection file and see if I can improve the query.

**Pull request merged**
