### PR TITLE
C57279: Correcting bold format and escaping square brackets

### PR DESCRIPTION
**Pull request by v-maudel**
Hi @rpetrusha , Just adding an additional small fix to this previous [PR](https://github.com/dotnet/docs/pull/9871) we made. 
Regards.
@mairaw

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
Thanks for making the additional change, @v-maudel. I'll merge your PR now.

**Comment by v-maudel** [comment]
Thanks to you @rpetrusha

**Comment by mairaw** [comment]
@v-makoud please remember to target the master branch when creating these PRs. It's our default branch.

**Comment by v-maudel** [comment]
Hi @mairaw , @rpetrusha 
My apologies for creating the PR in the live branch instead of master. 

Regards.

**Pull request merged**
