### PR TITLE
Update live with current Master

### PR DESCRIPTION
**Pull request by BillWagner**
One more time today...

/cc @mairaw

### CODE REVIEW

**Comment by mairaw** [comment]
LGTM. Let's just wait for CI to finish.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.media.matrix?branch=pr-en-us-994)

**Comment by BillWagner** [comment]
I think the Windows build is stuck. closing and reopening.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.security.cryptography.cngexportpolicies?branch=pr-en-us-994)

**Pull request merged**
