### PR TITLE
Fixing errors in the docs for basicHttpBinding

### PR DESCRIPTION
**Pull request by mconnew**
## Summary
The attribute envelopeVersion does not existing in BasicHttpBindingElement so removed.
The attribute namespace does not exist in BasicHttpBindingElement so removed from attribute description table.
Fixed description of name attribute as it was incorrectly describing Binding.Name (the runtime binding property) and not StandardBindingElement.Name (the configuration element property).

Fixes [Feedback ticket 1001709](https://developercommunity.visualstudio.com/content/problem/776274/ide-y-documentacion-soap-desactualizados.html)

### CODE REVIEW

**Comment by mconnew** [comment]
The feedback ticket is for the Spanish translation of these documents. How soon will these changes be translated to the various languages so that I can update the feedback ticket once that's done?

**Comment by mairaw** [comment]
@JasonCard can you comment on how long it takes from when a change is published for en-us until it shows up in the localized versions?

**Review by mairaw — APPROVED** [review]
LGTM. Let me know if I can just go ahead and merge.

**Comment by JasonCard** [comment]
@mconnew @mairaw Since this particular article is set to be Machine Translated, updates should be localized and published live within 1 or 2 days after English version is published live. (For articles set to be Human Translated, it could take up to two weeks depending on timing of source commit and volume of updates. For .NET Docs, we have weekly cadence starting Sundays, so localized updates should be published by following Fridays.)

**Comment by mconnew** [comment]
@mairaw, you can go ahead and merge this.

**Pull request merged**
