### PR TITLE
Add Ubuntu 22.04

### PR DESCRIPTION
**Pull request by richlander**
- Add Ubuntu 22.04
- Simplify table
- Remove unsupported versions

### CODE REVIEW

**Review by MichaelSimons — APPROVED** [review]
I like the simplification to the table.

**Comment by richlander** [comment]
I will work on the `linux.md` file next, but separate from this PR.

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Comment by adegeo** [comment]
Fixes #29273

**Pull request merged**
