### PR TITLE
change text block formatting

### PR DESCRIPTION
**Pull request by tdykstra**
cc @cartermp @richlander

### CODE REVIEW

**Comment by tdykstra** [comment]
@mairaw looks good to me in staging, please review

**Comment by cartermp** [comment]
This is still showing syntax coloring for me.

screen shot 2016-07-06 at 9 43 30 am

**Comment by tdykstra** [comment]
@cartermp Did you go to https://stage.docs.microsoft.com/en-us/dotnet/articles/core/tools/telemetry?branch=tdykstra-patch-1

**Comment by mairaw** [comment]
yes, it's still highlighting for me too.

**Comment by tdykstra** [comment]
Now I see what you're talking about, I didn't retag the second block, I'll do that and it won't highlight either.

**Comment by richlander** [comment]
When I look at that link above, the second block is still doing the wrong thing. I assume that change was staged.

**Comment by tdykstra** [comment]
I never got an email about the change being staged; @mairaw is restaging automatic when you add commits to a PR?

**Comment by mairaw** [comment]
It should. And you can check the builds on the portal. I'll send you an email with the link.

**Comment by tdykstra** [comment]
@richlander Restaging completed and the second block now looks good

**Comment by mairaw** [comment]
Now it's not highlighting anymore! :+1:

**Comment by richlander** [comment]
LGTM

**Pull request merged**
