### PR TITLE
C18342: Missing asterisk on target version

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @rpetrusha,

Localization team has reported source content issue that causes issue for localization. We need to escape the asterisk to avoid loc problems.

Please review the comment tag added and reply with explanation if fix is needed or not. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
@carolinacmoravia please take a look at my comment

**Comment by carolinacmoravia** [comment]
Hello, @mairaw, 
I've just commited the changes requested. Could you check if everything is okay and help yo merge?
Thank you.

**Review by rpetrusha — APPROVED** [review]
Thanks for opening this PR to correct the formatting issue, @carolinacmoravia. I'll merge your PR now.

**Comment by rpetrusha** [comment]
Sorry, @mairaw. I didn't notice that you'd already reviewed the PR. In any case, @carolinacmoravia addressed the formatting issue.

**Review by mairaw — APPROVED** [review]
No worries @rpetrusha. This is good to merge now @carolinacmoravia. Thanks!

**Pull request merged**
