### PR TITLE
Update Matrix4x4.xml

### PR DESCRIPTION
**Pull request by geoeo**
It is not documented that this is stored as row major, nor is any reference given to Direct X conventions.

# Title

Matrix4x4 Docs

## Summary

Added the specification that Matrix4x4 is row major

## Details

It is not documented that this is row major.
Nor is any reference given to Direct X.

For the seasoned Direct X veteran this may be evident, but it is never stated.
For newcomers to graphics programming, making this explicit avoids unnecessary mistakes.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by pkulikov** [comment]
@geoeo what makes you think that any reference should be given to Direct X? This type is a [SIMD-enabled type](https://docs.microsoft.com/en-us/dotnet/standard/numerics#simd-enabled-vector-types). It might be used not only for graphics programming.
What mistakes does notion of column major help to avoid? It looks that [methods](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4?view=netcore-2.0) of that type provide enough functionality, so users don't need to know about implementation details, but select a proper method for their wish.

At last, if suggested change is necessary, [Matrix3x2](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix3x2?view=netcore-2.0) might need update as well.

**Comment by geoeo** [comment]
It makes a big difference for combinations of transformations. 
Since a transformation chain with row major matrices, produces a different outcome than column major.

**Comment by pkulikov** [comment]
@geoeo that looks we talk about different things. When I see *column major* or *row major*, I think about [how matrix is stored in memory](https://en.wikipedia.org/wiki/Row-_and_column-major_order) (so, I become puzzled how that influences calculations). While you talk about another question: given `transform` matrix and `world` matrix, how do I transform the world: by `transform * world` or `world * transform` multiplication? Do I understand you correctly? Where can I read more about your meanings of *column major* and *row major*?

I'm afraid, simple mention of row major would not be enough, since it is not that clear.

**Comment by geoeo** [comment]
That is true. There is the memory layout and the interpretation of said layout in a mathematical sense. The memory layout is what it is.

However the mathematical interpretation of the matrix is row major, meaning a vertex V, has to be transformed via Matricies M_1 and M_2:

    v' = v*M_1*M_2 

Which is in contrast to (mathematical) column major:

    v' = M_2*M_1*v

Posts of this can be found:

[gamedev](https://www.gamedev.net/forums/topic/682063-vector-and-matrix-multiplication-order-in-directx-and-opengl/)
[scratchapixel](https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/row-major-vs-column-major-vector)

It is a confusing topic. But being explicit about this important when performing transformations on verticies as the order matters very much!

**Comment by pkulikov** [comment]
@geoeo aha, that's clear now! Thanks a lot for clarification and the links.

So, when you talk about row/column major you mean the way how a single point is written down: as a row or as a column. From the [scratchpixel](https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/row-major-vs-column-major-vector)
>In the first example ([1x3] matrix) we have expressed our vector or point in what we call the **row-major** order: the vector (or point) is written as a row of three numbers. In the second example, we say that that points or vectors are written in **column-major** order: we write the three coordinates of the vector or point vertically, as a column.

The thread by the [gamedev link](https://www.gamedev.net/forums/topic/682063-vector-and-matrix-multiplication-order-in-directx-and-opengl/) has a very good remark:
>...I personally try to avoid using the terms row-major and column-major with matrices, because they mean different things to mathematicians and computer science people...
Maths people think that you're talking about whether you've got a matrix that's made up of basis vectors that are row-vectors / column-vectors, and comp-sci people think you're talking about the 2D-to-1D array indexing scheme. These are two very different things :(

@geoeo I agree with you that documentation should mention what convention (point-as-a-row or point-as-a-column) is used. At the same time I suggest not to use *row major* and *column major* phrases as they are confusing.

As for the [Matrix4x4](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4?view=netcore-2.0), you are right: points are written down as rows. Check the [source code for the translation component](https://github.com/dotnet/corefx/blob/221950b31c1057b040670936519ddbc13f893062/src/System.Numerics.Vectors/src/System/Numerics/Matrix4x4.cs#L118): the fourth row is updated. By the way, if we look at the [translation-related code for Matrix3x2](https://github.com/dotnet/corefx/blob/221950b31c1057b040670936519ddbc13f893062/src/System.Numerics.Vectors/src/System/Numerics/Matrix3x2.cs#L73), we see one more time that points are written down as rows. Just realized now that existence of Matrix**3x2** instead of Matrix**2x3** means that point-as-a-row convention is used throughout the `System.Numerics` namespace :)

Nevertheless, an explicit remark about convention in use would be helpful. I would put such a remark into its own NOTE section and show it on the all relevant pages: [Matrix4x4](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4?view=netcore-2.0), [Matrix3x2](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix3x2?view=netcore-2.0), [Vector4](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector4?view=netcore-2.0), etc. What do you think of that?

**Comment by geoeo** [comment]
That would be very much appreciated!

> At the same time I suggest not to use row major and column major phrases as they are confusing.

Yes, that makes sense. The important part ist to highlight that the translation vector is stored in the last "row". Maybe an example matrix would help

Thank you for taking the time to discuss this with me

Best,
Marc

**Comment by pkulikov** [comment]
@geoeo that was a good time, thank you.

Then—if you are not against—I suggest to close this PR, after that I'll create a new issue and try (if nobody else would jump on it) to fix it this month.

**Comment by geoeo** [comment]
Sure

**Pull request closed without merging**
