### PR TITLE
[2.0] Remove OpenSSL prereq from macOS topics

### LINKED ISSUE #2144: [2.0] OpenSSL install no longer required for macOS
Ref: https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0-preview1.md

docs/core/macos-prerequisites.md
docs/core/tutorials/using-on-mac-vs.md
docs/core/deploying/index.md
docs/core/tutorials/using-on-mac-vs-full-solution.md

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #2144

### CODE REVIEW

**Comment by mairaw** [comment]
Maybe we should do these changes in a way that is clear that 2.0 doesn't need OpenSSL but 1.0 does require that. Both will be supported for a while so...

**Comment by GuardRex** [comment]
@mairaw I think leaving the prereqs out of the tutorials makes sense. I revert the change in the topic that explains what prereqs are needed. The tutorials just say, basically, 'make sure the prereqs are good' and link to the prereq topic. This hardens things a bit for the future so we're not updating three docs every time prepreqs change.

**Comment by GuardRex** [comment]
Stand-by a sec tho .... I need to check something in the release notes.

**Comment by GuardRex** [comment]
@mairaw Ok ... I express a bit more explicitly that OpenSSL is replaced by native deps on macOS.

**Review by BillWagner — APPROVED** [review]
After the changes @mairaw requested, this looks great.

I'll :shipit: now.

**Pull request merged**
