### PR TITLE
Cleanup xml

### PR DESCRIPTION
**Pull request by dpaoliello**
# Title

Cleanup (some) invalid XML for API docs

## Summary

Attempting to parse a (subset) of the API docs with Roslyn produced a number of errors:
* Switched to using `typeparamref` instead of `paramref` for type parameters.
* Removed the invalid `<see cref="Overload:..." />` attributes and replaced with DocFx `xref` links.
* In `System.Object.GetHashCode` removed `<paramref name="n" />`, since GetHashCode has no parameters.
* For some overloads of `System.String`, removed `<paramref name="comparisonType" />` since these overloads do not have a parameter with that name.

### CODE REVIEW

**Comment by mairaw** [comment]
Thank you @dpaoliello. Sorry for the delay. We'll review this shortly.

**Review by BillWagner — APPROVED** [review]
Thanks for fixing these for us @dpaoliello We really appreciate it.

@mairaw The changes look fine to me from the standpoint of the tags specified in the C# spec. I'm ready to merge this. Do we need to check with the MDOC tools team first?

**Comment by mairaw** [comment]
You say because of the changes from `paramref` to `typeparamref` @BillWagner? If so, I don't think there should be any issues with mdoc because:
1 - the changes are in authored content
2 - typeparamref should be supported

We should probably create an issue for this change globally because our previous tool didn't make any distinctions between paramref and typeparamref.

@joelmartinez @dend can you guys confirm? and where we can find all the valid tags for ECMAXML?

**Comment by joelmartinez** [comment]
You can find the supported tags in the [XSD for EcmaXML](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd) ... `typeparamref` is there and valid :)

**Comment by mairaw** [comment]
Thank you for confirming, @joelmartinez. Appreciate the link! @dpaoliello  I'll merge this now and the update should go live in the next day or so. Thanks for the updates!

**Pull request merged**
