### PR TITLE
Moved app compat item

### PR DESCRIPTION
**Pull request by rpetrusha**
## Moved app compat item

This category assigned to this file in the Microsoft/dotnet repo was "Web application" rather than the expected "Web applications", which caused it to be placed in a different directory when migrated to the dotnet/docs repo. It also causes it to appear in a separate category.

The change also corrects the incorrect rendering of app compat issue (see the image below).

image

//cc @mairaw @chlowell

### CODE REVIEW

**Comment by chlowell** [comment]
Links to the include file need updates as well. I ran the generator again, you can see the changes on my fork at chlowell/docs-1#32.

**Comment by rpetrusha** [comment]
Thanks, @chlowell. I updated the links to the include file as well, and it looks as if the local changes from this PR have addressed all of the issues. Do you think that you should open a PR for your migration, or go with what we have here? Basically, the two versions are in sync, since these are the only changes that have been made to the Microsoft/dotnet repo since the 4.7.2 migration.

**Comment by chlowell** [comment]
This one's already here, so if they're equivalent, I'd say there's no value in retargeting the one on my fork.

**Review by BillWagner — APPROVED** [review]
This LGTM, and the build is clean, so :shipit: when ready.

**Comment by rpetrusha** [comment]
I thought that I'd responded to you, @chlowell, but I guess not. I agree that there's no need for a new migration since we've encapsulated all of the changes here.

**Pull request merged**
