### PR TITLE
Fix merging issues.

### PR DESCRIPTION
**Pull request by BillWagner**
When merging and updating, a couple sections got duplicated. The result is bold text on the live site.

### CODE REVIEW

**Comment by BillWagner** [comment]
WIP label applied while I look at this on the staging site.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.flowcontrol?branch=pr-en-us-988)

**Comment by mairaw** [comment]
Oh no, sorry I've missed that.

**Comment by BillWagner** [comment]
Looks good on staging.  Ready for review.

**Comment by mairaw** [comment]
LGTM

**Comment by BillWagner** [comment]
Thanks! I'll :shipit:

**Pull request merged**
