### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by pkulikov**

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
Thanks for fixing this typo, @pkulikov. I'll merge your PR after the internal build completes successfully.

**Comment by pkulikov** [comment]
Reopen to reset the build

**Comment by rpetrusha** [comment]
Sorry, @pkulikov. In looking at your PR, I confused the original with your change and so thought you removed the `i` rather than  added it. But the original is correct. Or am I missing something?

**Review by svick — APPROVED** [review]

**Comment by pkulikov** [comment]
Let me off-topic a little bit. @svick @rpetrusha is the mentioned [How to: Use Operator Overloading to Create a Complex Number Class](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-use-operator-overloading-to-create-a-complex-number-class) article useful at all?

- It might be misleading, because one maybe should use the built-in [System.Numerics.Complex](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.complex?view=netframework-4.7.2) struct
- An example of the operator overloading can be found in the [operator keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/operator) article

What about deleting this How-to and redirecting it to the operator keyword article? (of course in different PR)

**Comment by rpetrusha** [comment]
Thanks, @svick. I'd forgotten about the convention for representing a complex number, especially since Complex.ToString doesn't use it. 

To respond to your question, @pkulikov, [How to: Use Operating Overloading...](https://review.docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators?branch=pr-en-us-7265) is a low page-view topic that was written for .NET Framework 3.5 (if not earlier), when Complex did not exist (it was added in .NET Framework 4.0). So I think that the topic can be removed and redirected to this topic. Would you like to open the PR to do that?

I'll merge this PR now.

**Comment by pkulikov** [comment]
@rpetrusha 
> Would you like to open the PR to do that?

For sure ;). Thank you for the historical context.

> ...and redirected to this topic. 

Which topic do you refer to by "this topic"? I thought about the operator keyword topic.

**Pull request merged**
