### PR TITLE
Corrected LINQ to XML query

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/docs/issues/6677.

I also removed semicolons, since the code blocks here are expressions, not whole statements.

And while I'm here, I also removed "2" from the title and replaced the token for "LINQ to XML" with its value.

### CODE REVIEW

**Comment by svick** [comment]
I also noticed there's [a nigh duplicate article in the VB guide](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/linq/comparison-of-xpath-and-linq-to-xml). Does it really make sense to maintain mirrored articles for both languages like that?

**Comment by rpetrusha** [comment]
To respond to your question, @svick, no, it makes no sense at all to mirror articles for both languages, especially when most of the content is language-independent, as this article is. At some point, a decision was made to divide what had been a single topic into separate C# and VB topics, which makes little sense. 
Over the long run, these should be merged into a single doc set in the .NET guide, which should cover both languages, and any topics that are language-specific should remain in the C# and VB guides. But that's not going to happen tomorrow -- we have numerous instances of needless duplication and triplication in the documentation; see #4728.
The question is really how to deal with this in the short term. There are a couple of short-term solutions:
1. Accept your PR as is, and make the same essential changes to the VB topic. You could do that by adding it to this PR, or we could accept this PR and do it in  a separate PR.
2. Add the VB code examples to this topic, so that it covers both, change the second paragraph in the "Differences between XPath and LINQ to XML" section to mention the Visual Basic compiler along with the C# compiler in two places, and redirect URLs for the VB topic to the C# topic. That's a bit awkward, since VB developers end up in the C# doc set. But in this case I think it's acceptable -- the number of pages views for the VB topic is extremely low in comparison to the C# topic, we won't have to worry about making parallel changes to at least one topic, and it eliminates at least one duplicate topic from the doc set. This also at least gets the revision underway. It's the option I think that I'd prefer.

I'm tagging this as Request Changes to see how you'd like to proceed. Let me know how you'd like to proceed, and then I'll merge your PR.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
I'm tagging this as Request Changes, @svick, to see how you'd like to proceed. Let me know how you'd like to proceed, and then I'll merge your PR. I should have mentioned, incidentally, that your changes all look good.

**Comment by pkulikov** [comment]
@svick 

>I believe language switcher requires the use of snippets and the article does not currently use those.

It seems that language switcher only requires the following block in the metadata section:
```
dev_langs: 
  - "csharp"
  - "vb"
```

Check the [?. and ?[] null-conditional Operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators) source:
https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/null-conditional-operators.md

It contains no snippets but code blocks.

**Comment by rpetrusha** [comment]
Thanks for your response, @svick. I think that adding the dev_langs metadata should provide language switcher support. The only other issue is inline code. The convention that we've used in the past is to include the C# inline code first, with the Visual Basic code in parentheses. So, "Another example: `anElement.Ancestors().ToList()[0]` (`anElement.Ancestors().ToList()(0)` in Visual Basic..." Another, and better alternative IMO, is to modify the text so that the one-liners are code blocks:

Another example:
\`\`\`csharp
anElement.Ancestors().ToList()[0]
\`\`\`

\`\`\`vb
anElement.Ancestors().ToList()(0)
\`\`\`
returns the parent element

**Comment by svick** [comment]
@pkulikov Thanks, that's useful.

@rpetrusha Yeah, that makes sense. In the end, I didn't end up doing that, because I realized `.ElementAt(0)` is better than `.ToList()[0]` here. And by doing that, I can remove the paragraph about efficiency and it also means that I can keep the inline code as is, because it's now the same in both languages.

**Review by rpetrusha — APPROVED** [review]
This looks really good, @svick, and it builds very nicely. Thank you so much for the work that you've put into it. I'll merge now.

**Pull request merged**
