### PR TITLE
Replace Windows Runtime tokens

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
Thank you so much for continuing to replace tokens with their token text and remove the tokens, @NextTurn.

One issue that occurred to me is that token removal has localization costs -- each article that has tokens removed must be re-translated even though the text has not changed, which can incur significant cost. In general, removing these tokens has an enormous benefit -- it makes the text significantly more accessible to community members. What we would ask is that if token removal touches an especially large number of files -- somewhere in the neighborhood of 75 seems like a good limit -- that the tokens be left in place until some later date.

I'll merge your PR now.

**Comment by NextTurn** [comment]
In addition to token replacement, are there others actions that lead to retranslation?

**Comment by NextTurn** [comment]
Can't we suppress the localization process for such minor changes?

**Comment by rpetrusha** [comment]
Unfortunately, any change triggers re-localization, @NextTurn. There's no way to avoid it without completely redesigning the way our documentation is localized.

**Comment by NextTurn** [comment]
What about those style changes (blank line updates)?

Does it mean that we should avoid touching large articles if not necessary?

**Pull request merged**
