### PR TITLE
Modernizing ebook images update

### PR DESCRIPTION
**Pull request by ardalis**
Removing transparent backgrounds and updating graphics with current marketing versions.

### CODE REVIEW

**Comment by ardalis** [comment]
All set @nishanil

**Comment by nishanil** [comment]
cc @BethMassi

**Comment by nishanil** [comment]
@ardalis Looks like the cover image (.png) is dropped and .jpg was added? But, I don't see the index page updated to the new file. Can you retain png files instead?

**Comment by nishanil** [comment]
@ardalis Can you also update the Copyright year on the index page, please?

**Comment by BethMassi** [comment]
Images look good except for the front cover. The logo looks squashed. Can you just recolor the top of the box and remove "Microsoft"?

**Comment by ardalis** [comment]
Note: I don't have the source file for the cover image so I'm doing my best to tweak it. I updated the .NET logo and removed the Service Fabric logo.

**Comment by ardalis** [comment]
@nishanil I'm not sure what's meant by this: 
Also, the recommendation for "Azure Web App for Containers" is missed out in the images?

Is there a missing image? Is there some text in an image I need to change? Thanks.

**Comment by nishanil** [comment]
@ardalis  image1-3.png, image1-5, image1-6, image1-7 wherever "Windows Containers on Service Fabric" was there(under Cloud-Optimized section), it should be replaced with "Azure Web App for Containers" instead of removing the box.

**Comment by nishanil** [comment]
Try this one.
Recolored to match .NET Purple.. I added this image in the resources repo too.
web-application-guide-cover-image

**Comment by BethMassi** [comment]
Looks great!

**Comment by ardalis** [comment]
@nish should be all set now

**Review by nishanil — APPROVED** [review]
LGTM

**Pull request merged**
