### PR TITLE
Fix broken samples

### PR DESCRIPTION
**Pull request by BillWagner**
This PR unblocks a number of dependabot updates:

#19148 
#19150 
#19151 
#19156 
#19181

### CODE REVIEW

**Comment by BillWagner** [comment]
@adegeo Can you look at this build failure? It builds correctly using the command line on my machine. The errors seem to indicate a missing package.

**Comment by adegeo** [comment]
@BillWagner Could it be the NuGet restore not running on the visual studio instance? Once we validate https://github.com/dotnet/samples/pull/3755 triggers nuget restore, we could test here too.

**Comment by BillWagner** [comment]
closing and reopening for a new CI build test.

**Comment by BillWagner** [comment]
w00t!  @IEvangelist Can you approve so I can :shipit:?

**Review by IEvangelist — APPROVED** [review]
Looks good to me, :shipit: when you're ready.

**Pull request merged**
