### PR TITLE
Removing colons from the metadata

### PR DESCRIPTION
**Pull request by Duncanma**

### CODE REVIEW

**Comment by mairaw** [comment]
We should actually replace the colon with &#58 in the metadata section.

**Comment by mairaw** [comment]
I'll work on that later and remove from all the ones that currently have colons as we discussed. Thanks for catching that @DuncanmaMSFT!

**Comment by mairaw** [comment]
Metadata is fixed across the topics.

**Comment by richlander** [comment]
Can we try one of these solutions instead?

http://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-i-e-or-in-yaml

Escaping is such a poor authoring solution.

**Comment by mairaw** [comment]
Thanks for the suggestion @richlander. Escaping colons on the metadata was the suggestion from the docs.microsoft.com guidelines. I've tested with quotes and that worked too. Is that better?

**Comment by richlander** [comment]
LGTM

@mairaw Can you file an issue on the guidelines? Escaping is always something to be avoided within content. It's bowing down to the machine, right?

**Comment by mairaw** [comment]
Thanks @richlander. I agree. I'll do that.

**Pull request merged**
