### PR TITLE
moved includes to correct folder

### LINKED ISSUE #1253: Move include files to a central location
The export tool for the migrated content from MSDN had a weird behavior on where it'd put the include (token) files on the folder where the text was first used. We need to move the include files to a central location to be easier to find and use them.

### PR DESCRIPTION
**Pull request by mairaw**
The includes content for the migration guide was inside the docs folder. All other includes are in the top-level includes folder. So moving to that location.

Fixes #1253

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Kind'a tooooo many to do more than scan on the diff ... the build report will be a blessing on this one. :shipit:

**Comment by mairaw** [comment]
It's all broken now 💥 I'll check what I did wrong

**Comment by mairaw** [comment]
Getting better. Still needs work.

**Comment by conniey** [comment]
Can you show me a file where the markdown syntax was not being used? The PR is too large.. I couldn't find an example. :(

**Comment by mairaw** [comment]
Look at the diff for the 3rd commit only and you'll see:
https://github.com/dotnet/docs/pull/2674/commits/0e5f3beefe99d277750933bd89160cd2375f618e

**Comment by conniey** [comment]
Ahh, I see. The tool that I wrote to convert the [breaking changes](https://github.com/Microsoft/dotnet/tree/master/Documentation/compatibility) to pages supported by docs converted any markdown inside a table to HTML so it would be guaranteed to render properly. I don't think this change should break the table. I can update the tool to skip links

**Comment by mairaw** [comment]
Yeah, for some of the elements, I don't think there's a way around that like the list items. 

But is it okay for me to change the link texts on these or the change first needs to happen somewhere else? I just want to understand the workflow for these as well.

**Comment by conniey** [comment]
Yeah, it's fine to manually change those links. 👍  It won't break anything. I'll update the tool next time I generate the docs and not to change the links to HTML.

**Comment by mairaw** [comment]
@rpetrusha this is now ready for review

**Review by rpetrusha — APPROVED** [review]
@mairaw, I've gone over this fairly carefully and didn't see any issues. It's OK to merge when you're ready.

**Pull request merged**
