### PR TITLE
Format "+" and "*" as code

### PR DESCRIPTION
**Pull request by eduard-malakhov**
Format "+" and "*" as code to reconcile formatting across documents.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thank you for correcting the formatting of the addition and multiplication symbols, @eduard-malakhov. For consistency, would you mind also formatting `Fraction` and `double` as well, so that all program elements in the example description will be formatted?

**Review by JRAlexander — DISMISSED** [review]
I agree with @rpetrusha.

**Comment by eduard-malakhov** [comment]
Thank you @rpetrusha, sure. I've missed that.

**Comment by rpetrusha** [comment]
@eduard-malakhov, there's no need to close the PR. You can make just edit this PR, which is much easier. I'll reopen it.

**Comment by eduard-malakhov** [comment]
@rpetrusha Sorry for that, that was unintended.

**Comment by rpetrusha** [comment]
That's OK, @eduard-malakhov. When I saw the PR was closed, I first checked to make sure that I hadn't accidentally closed it...

**Comment by rpetrusha** [comment]
Thanks for making the additional changes, @eduard-malakhov! We'll merge your PR as soon as the internal build completes.

**Review by rpetrusha — APPROVED** [review]

**Comment by mairaw** [comment]
@rpetrusha I'm getting 404 on stage. Can you check?

**Comment by rpetrusha** [comment]
@mairaw, I'm also getting non-intermittent 404s on staging. I'll close and begin a new build.

**Pull request merged**
