### PR TITLE
Fix text that was causing translation error

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes https://github.com/dotnet/docs.zh-cn/issues/662

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
Looks good to me, :shipit: when you're ready.

**Comment by Youssef1313** [comment]
@tdykstra @IEvangelist Was this intended to be merged into live directly? The change doesn't exist in current `main`.

**Comment by IEvangelist** [comment]
> @tdykstra @IEvangelist Was this intended to be merged into live directly? The change doesn't exist in current `main`.

Hi @Youssef1313 - that is a great observation. I'm not actually sure, @tdykstra do you know - if not we should sync this?

**Comment by Youssef1313** [comment]
Pinging @tdykstra (there is https://github.com/dotnet/docs/pull/20476 as well).

**Comment by tdykstra** [comment]
Yes this was accidentally merged directly to live-- @BillWagner I think the best thing to do here is revert the PR and redo the change in a PR to main -- do you have a better idea?

**Pull request merged**
