### PR TITLE
Added linq join operators samples

### LINKED ISSUE #138: C# LINQ Samples - Join Operators

### PR DESCRIPTION
**Pull request by matthewreily**
fix #138 cc @BethMassi

### CODE REVIEW

**Comment by BethMassi** [comment]
@matthewreily @cartermp I noticed this before, but the sample data in Data.cs doesn't look like the right encoding and I'm getting funky characters show up. I'm wondering if we should change the data to ASCII or UTF8?

**Comment by matthewreily** [comment]
That's my fault.  The sample data is coming from the linq 101 samples and it has some funky characters in it.  I'll clean it up in all the linq samples.

**Comment by BethMassi** [comment]
Thanks @matthewreily

**Comment by matthewreily** [comment]
@BethMassi  I removed all of the funky characters and squashed commit.

**Comment by cartermp** [comment]
LGTM.  Thanks @matthewreily

**Pull request merged**
