### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by rpetrusha**
# Fixed broken link

## Summary

The link \<xref:System.Web.HttpApplication.Application_Start> was always incorrect, because the application-defined `Global` class inherited from `HttpApplication`, and an `Application_Start` class never existed.

## Suggested Reviewers

@mairaw

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Change looks good. Not related to your changes if you wanna address:
- Remove VS version
- Add a link to where the samples can be found (https://www.microsoft.com/en-us/download/details.aspx?id=21459)

**Comment by rpetrusha** [comment]
I've addressed your comments, @mairaw, if you want to take a look once the build finishes. There already was a download link in an alert box. I've replaced it with a "To download the sample" section.

**Comment by mairaw** [comment]
Ha, I totally missed it! I'll take a look once it finishes building, but I like the idea of being in a section vs a note.

**Comment by mairaw** [comment]
Merge when you're ready

**Pull request merged**
