### PR TITLE
Fixed a couple of links which had two "https://"

### PR DESCRIPTION
**Pull request by hbazerbashi**
Some links weren't working because they had two "https://".

Thanks,
Hasan.

### CODE REVIEW

**Review by JRAlexander — APPROVED** [review]
LGTM. Thanks for your contribution, @hbazerbashi! Very nice catch! I'll merge as soon I verify that it built correctly.

**Comment by hbazerbashi** [comment]
Thanks for the quick response and for the encouragement 😊 👍 

I also edited the link to "Walkthrough 2". It was pointing to a "TBD" link. Sorry I didn't get it the first time.

**Comment by JRAlexander** [comment]
No problem. I'll re-review and then verify. Thanks again for the help!!!

**Comment by hbazerbashi** [comment]
Hi, I'm just curious, when does the update show on the [documentation](https://docs.microsoft.com/en-us/dotnet/standard/modernize-with-azure-and-containers/walkthroughs-technical-get-started-overview) page?

**Comment by mairaw** [comment]
It should be live later today @hbazerbashi. We usually do a push to production once a day.

**Comment by hbazerbashi** [comment]
Thanks for the quick reply. This was a great experience, contributing the first time 😊

**Comment by mairaw** [comment]
Yay! We really strive for that and I hope we see more contributions from you in the future.

**Comment by JRAlexander** [comment]
That's wonderful to hear!

**Pull request merged**
