### PR TITLE
Added ternary operator name to the ternary operator docs

### PR DESCRIPTION
**Pull request by Scott-Lyons**
# Title
Added information to the ?: operator article to mention that it is called the ternary operator

## Summary
See 'Title'

Fixes N/A

### CODE REVIEW

**Review by BillWagner — CHANGES_REQUESTED** [review]
We've avoided using the term "ternary operator" because it relies on the fact that the conditional operator is the only operator that has three operands.

That said, the term "ternary operator" is a common search term because of its historical use in C, C++, and Java.  

How about a compromise of saying "commonly known as the ternary conditional operator" as a compromise?

**Comment by BillWagner** [comment]
@Scott-Lyons Thanks for submitting this. We really appreciate the contribution and the involvement.

I've proposed slightly different wording after discussion with @madstorgersen and @gafter   We've tried to avoid the term "ternary operator", but we realize a lot of people may use it in searches.

Let me know your thoughts on the proposed change, if you want to make it, or have me make the edit and merge your PR.

Thanks again.

**Review by jzeferino — APPROVED** [review]
LGTM, and @BillWagner thanks for the clarification.

**Review by BillWagner — APPROVED** [review]
After adding the suggestion from Mads and Gafter, this is ready to merge.

**Comment by Scott-Lyons** [comment]
@BillWagner Sorry for the late reply (especially as you've already merged), updated wording looks a lot better thanks!

**Pull request merged**
