### PR TITLE
Update Security section to use camelCase

### LINKED ISSUE #10173: The coding formatting must be changed
As an example the following code snippet must be changed from:

TcpClient TCP = new TcpClient("localhost",11000);

To:

var tcp = new TcpClient("localhost",11000);

In modern programming days, it's discouraged to use capital cases for local variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee15f916-5406-85fa-b7fb-a9e69fcd3efb
* Version Independent ID: b6aae569-8a56-0a44-7b8e-e54491418baf
* Content: [Encrypting Data](https://docs.microsoft.com/en-us/dotnet/standard/security/encrypting-data)
* Content Source: [docs/standard/security/encrypting-data.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/encrypting-data.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by Potapy4**
Fixes #10173

### CODE REVIEW

**Comment by NextTurn** [comment]
The entire page needs to be updated.

**Comment by Potapy4** [comment]
> The entire page needs to be updated.

Do you mean all articles in the `Cryptography Model` section?

**Comment by NextTurn** [comment]
The snippets in the file you changed need to be updated to use camel case for variables.

**Comment by Potapy4** [comment]
Alright, I also updated all code examples in this section so that camelCase is used everywhere.

**Comment by NextTurn** [comment]
Awesome! Thanks for the additional changes.

**Review by rpetrusha — APPROVED** [review]
Thank you, @Potapy4, for enforcing coding conventions in this section. And thanks for your review, @NextTurn. I'll merge the PR now. The changes should be live on docs.microsoft.com in the next day or two.

**Pull request merged**
