### PR TITLE
Fix code fragment

### LINKED ISSUE #12326: CardType is abstract
I think the sample class is incorrect:

    public abstract class CardType : Enumeration

If CardType is abstract, how can its members instantiate it:

    public static CardType Amex = new CardType(1, "Amex");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by mvelosop**
## Summary

Update incorrect code

Fixes https://github.com/dotnet/docs/issues/12326

### CODE REVIEW

**Comment by BillWagner** [comment]
See #12329 

@mvelosop I made a comment on that PR. What's your opinion on making the constructor private?

**Comment by mvelosop** [comment]
Hi @BillWagner, I'm sorry, I didn't realized there was a PR for this already.

I haven't really used "enumerations" out of eShop, so I probably have a newbie opinion here.

I think it makes sense to have a private constructor, since an enum or "enumeration" is not supposed to take arbitrary values.

I don't like the use of an enumeration class for CardType, as I think that's some kind of user configuration, however in eShop it's really only used as a DB seeder, so its use in this role could be acceptable.

I think enumeration classes fit perfectly for classes like OrderStatus, because it makes sense to only have very specific values, and hence have a private constructor (which it has not) .

However, changing the constructor to private would break some code in the case of CardType (a few news around, that should be fixed anyway) and I'm not sure if it would break something when EF it tries to rehydrate the properties.

I'm pretty sure @ardalis could add much more significant comments here.

That's my 2 cents!

**Review by rpetrusha — APPROVED** [review]
LGTM, @mvelosop. I'll merge your PR now.

**Comment by mairaw** [comment]
Closing this one in favor of the previously filed PR.

**Comment by mvelosop** [comment]
Fair enough! 😊

**Pull request closed without merging**
