### PR TITLE
remove Source label rule

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by BillWagner** [comment]
I support this message. I'd like to remove any labels we and our community don't find useful.

**Comment by mairaw** [comment]
@natke @mamccrea we're thinking of removing the green Source label from our repo:
https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22Source+-+Docs.ms%22

Any objections?

**Review by mamccrea — APPROVED** [review]
No objections.

**Review by Thraka — APPROVED** [review]
Sounds good :D

**Comment by Thraka** [comment]
Merging this as I have the v3 label updates coming in.

**Pull request merged**
