### PR TITLE
CC56598: Contirbutor changed Contributor guide link

### PR DESCRIPTION
**Pull request by gosali**
Hello, @pkulikov,

This proposed file change comes from https://github.com/dotnet/docs.zh-cn/pull/130/files . 
Line #11

Could you review this contribution and help to merge if agreed?

Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by rpetrusha** [comment]
@mairaw, @BillWagner, and @JRAlexander, this PR replaces the link to the contributor guide on our repo with the link to the general contributor guide. I'm not sure that our repo-specific contributor guide isn't preferable. Also, if we accept this change, we lose the link to the contributor's project, which has been helpful in directing contributions so far. Thoughts?

**Comment by BillWagner** [comment]
We shouldn't take this change, at least not now.  In time, the main contributor guide will have sections on repo-specific processes, but that's not in place yet. We can link to both for now,  or leave it as is.

**Comment by mairaw** [comment]
What I think we could do is to add a link to the docs one from the top of our contributing file.

**Comment by pkulikov** [comment]
I agree with @mairaw: that link to the global contributing guide is worth to be placed at the start of the [Process for contributing](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#process-for-contributing) section as a guideline for small changes. The general docs contributing guide is also good as it encourages not only content updates but review of existing PRs and reporting quality issues.

**Comment by JennieHubbard** [comment]
@gosali will you make the change in this pr, or do you prefer to close it once @mairaw  @BillWagner  @JRAlexander make their suggested change? 

@SonjaSaltzman

**Comment by carolinacmoravia** [comment]
Hello, @gosali,
Could you adress this, please?

**Comment by gosali** [comment]
@mairaw @BillWagner @JRAlexander If you have already applied your suggested change in the contributor guide, I will close this PR. Please let me know.
Thank you a lot.

@SonjaSaltzman, @JennieHubbard

**Comment by carolinacmoravia** [comment]
@mairaw @BillWagner @JRAlexander If you have already applied your suggested change in the contributor guide, I will close this PR. Please let me know.
Thank you a lot.

@SonjaSaltzman, @JennieHubbard

**Comment by mairaw** [comment]
Sorry this has slipped. No, I haven't made the change yet @gosali.

**Comment by mairaw** [comment]
Closing this in favor of #5881

**Comment by imba-tjd** [comment]
There is actually no link to this repo. Local repos don't have a ` CONTRIBUTING.md`  and the only "Contributing Guide" link returns 404. The PR @mairaw made has no effect to local repos. I don't know whether you knew this. Should we rediscuss?

**Pull request closed without merging**
