### PR TITLE
Review TODO code snippet references (docs)

### PR DESCRIPTION
**Pull request by tompratt-AQ**
# Title
Review TODO code snippet references and resolve them.

## Summary
This PR covers all of the 25 conceptual files (\docs) (48 instances) that are listed in the dotnet/docs Project ["TODO: review snippet reference"](https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22TODO%3A+review+snippet+reference%22&type=).  

## Suggested Reviewers
@mairaw

### CODE REVIEW

**Comment by tompratt-AQ** [comment]
The following comments apply to files that were edited in this PR:

[docs/framework/winforms/controls/how-to-access-the-managed-html-document-object-model.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/winforms/controls/how-to-access-the-managed-html-document-object-model.md)
Snippet doesn't exist and wasn't included in VS 2010.

[docs/framework/wcf/how-to-specify-a-client-binding-in-configuration.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/wcf/how-to-specify-a-client-binding-in-configuration.md)
Looks good in preview  but some snippets aren't currently rendering.

[docs/framework/wcf/feature-details/create-an-ajax-wcf-asp-net-client.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/wcf/feature-details/create-a-service-arbitrary-data-using-wcf.md)
[docs/framework/wcf/feature-details/create-a-service-arbitrary-data-using-wcf.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/wcf/feature-details/create-a-service-arbitrary-data-using-wcf.md)
In both of these files, I deleted Registry Key#4, because I couldn't find the file and there is no mention of it in the topic or examples.
 
[docs/framework/wcf/how-to-secure-a-service-with-windows-credentials.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/wcf/how-to-secure-a-service-with-windows-credentials.md)
All of the C# snippets have a corresponding VB snippet, except for #2.
  
[docs/framework/wcf/extending/how-to-inspect-and-modify-messages-on-the-service.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/wcf/extending/how-to-inspect-and-modify-messages-on-the-service.md)
I kept only the one config file, but C# and VB were slightly different than it. Do they all need to be kept because of that?

[docs/framework/wcf/creating-ws-i-basic-profile-1-1-interoperable-services.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/wcf/creating-ws-i-basic-profile-1-1-interoperable-services.md)
Only one config file now, so I changed the intro to the snippet from plural to singular. 

[docs/framework/interop/platform-invoke-examples.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/interop/platform-invoke-examples.md)
The C++ snippet exists in the current version, but was TODO here. I kept it - is that correct?

For all of these files, I added %20 to the directory name in all snippet links because the paths wouldn't resolve otherwise:
[docs/framework/data/adonet/query-expression-syntax-examples-restriction-linq-to-dataset.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/data/adonet/query-expression-syntax-examples-restriction-linq-to-dataset.md)
[docs/framework/data/adonet/single-table-queries-linq-to-dataset.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/data/adonet/single-table-queries-linq-to-dataset.md)
[docs/framework/data/adonet/method-based-query-syntax-examples-element-operators.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/data/adonet/method-based-query-syntax-examples-element-operators.md)
[docs/framework/data/adonet/ado-net-code-examples.md](https://github.com/dotnet/docs/blob/c50b3e328998b65ec47efe6d7457b36116813c77/docs/framework/data/adonet/ado-net-code-examples.md)
In this last file, 2 snippets don't exist anymore but were in VS 2010. I left a TODO message to that effect in case they can be found.

**Comment by rpetrusha** [comment]
@tompratt-AQ, note that there are publishing errors.

**Comment by rpetrusha** [comment]
@tompratt-AQ This looks good, aside from whatever build errors there may be. Assuming that you can fix them, I'll approve the PR.

**Review by rpetrusha — APPROVED** [review]

**Comment by tompratt-AQ** [comment]
Thanks. I'll work on these build errors. I'm not too surprised by them, given that I'm trying to resolve previously broken snippet links.

**Comment by mairaw** [comment]
I agree with @rpetrusha. We can also start renaming some samples if it makes it easier to link to them (for example, to not have spaces in the file name). We just need to make sure to rename where they're referenced if you do that.

**Comment by tompratt-AQ** [comment]
It's not really the file name in this case, it's the folder name.

For example, this path apparently builds but does not render the snippet on our doc page (“DataWorks SampleApp.OleDb” is the directory with the space):
[!code-csharp[DataWorks SampleApp.OleDb#1](../../../../samples/snippets/csharp/VS_Snippets_ADO.NET/DataWorks SampleApp.OleDb/CS/source.cs#1)]

I noticed that the path would resolve in my VS Code preview when I added%20, like this:
[!code-csharp[DataWorks SampleApp.OleDb#1](../../../../samples/snippets/csharp/VS_Snippets_ADO.NET/DataWorks%20SampleApp.OleDb/CS/source.cs#1)]

However, that causes a build error for “unable to resolve….cannot find reference”

Any ideas?

**Comment by tompratt-AQ** [comment]
Resolved all of the build errors that I could, and put back the TODO tags on snippets that still have errors due to a bug.

**Comment by tompratt-AQ** [comment]
Added too many spaces to a few links, and missed some link breaks.

**Review by mairaw — CHANGES_REQUESTED** [review]
Looks great overall! Left some comments.

**Comment by tompratt-AQ** [comment]
Thanks for the helpful review comments!
I made the fixes as suggested and added one additional file with several changes. There are now 22 Docs files (conceptual topics) remaining from the list. I will submit them in a separate PR before I start in on the XML files.

**Review by mairaw — APPROVED** [review]
Thank you @tompratt-AQ! Let's merge this.

**Pull request merged**
