### PR TITLE
Fix typo: AesCrytpServiceProvider -> AesCryptoServiceProvider

### PR DESCRIPTION
**Pull request by chlowell**
Corrects this document's filename and text.

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thanks @chlowell! I'll wait for the CI builds to finish before merging this PR.

**Review by mairaw — CHANGES_REQUESTED** [review]
One thing though. I just noticed that you also renamed the file. I haven't noticed that when I first looked. We'll need to change the references to that file as well. Let me know if you need help with that. Sorry for missing this on my first review.

**Comment by chlowell** [comment]
Thanks for catching that. I fixed all the migration guides, and another crypto typo in the app configuration docs.

**Review by mairaw — APPROVED** [review]
Looks great! Thanks for making the fixes @chlowell.

**Pull request merged**
