### PR TITLE
Create markdown-link-checker.yml

### PR DESCRIPTION
**Pull request by Youssef1313**
Trying to find a good working workflow that detects problem such as the ones being fixed in https://github.com/dotnet/docs/pull/20137.

### CODE REVIEW

**Comment by Youssef1313** [comment]
I can't get either of the two workflows I found to work.

@adegeo Any ideas?

**Comment by adegeo** [comment]
Hrm, not sure? But I dont think this would work anyhow. Does the tool check xref links? Those can be put inside of markdown links: `[some link text](xref:api-path)`

The build system at least tells us of any non HTTP link AFAIK.

**Comment by Youssef1313** [comment]
I think xrefs shouldn't be detected as relative link. These actions should only work in relative links.

**Comment by adegeo** [comment]
The way I got the initial snippets testing working to work was doing it in like your fork first. So I think the workflows only trigger when you're working on the branch they are in. So create branch1 with the workflow configured and ready, then do things in branch2 which has a PR into branch1 where the workflow exists. And I think your trigger needs to be `on: pull_request` not `on: push` as you want to test the links of the files when a bad PR comes in, not after it's merged.

**Comment by Youssef1313** [comment]
@adegeo The work flows indeed was triggered in my fork (they doesn't appear in PR but I can see in my fork). However, they doesn't seem to be doing any good.

One of the workflows (https://github.com/Youssef1313/docs/actions?query=workflow%3A%22Markdown+link+checker%22) passes  in 5 minutes, although they should report broken links.

The second one is actually very funny (https://github.com/Youssef1313/docs/actions?query=workflow%3A%22Check+Markdown+links%22), it fails after 6 hours with a timeout 😄

**Comment by adegeo** [comment]
No idea really.. does the workflow work with PRs checking just the files in it? I would look into how to configure that script. A lot of scripts allow you set them up through properties or env variables.

**Comment by Youssef1313** [comment]
@adegeo I'll try to play with it in my fork and see if I could get something to work. In the meanwhile, I'll close the PR and re-open if I could get to something working.

**Pull request closed without merging**
