### PR TITLE
Fixed Linux commands to install dotnet via apt

### PR DESCRIPTION
**Pull request by KarmyDev**
<s>apt-get is obsolete. Don't use it, use apt instead.</s> The package name isn't dotnet6 but dotnet-sdk-6.0 

## Summary

<s>Changed `apt-get` to `apt`.</s>
Changed `dotnet6` to `dotnet-sdk-6.0`.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32551) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32551) before we can accept your contribution.<br/><br/>:x: KarmyDev [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32551)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=32551) it.</sub>

**Comment by adegeo** [comment]
Hi @KarmyDev I missed this PR. Can you show me where apt-get is documented as deprecated? From what I saw via an initial search online, it isn't obsolete nor deprecated.

**Comment by KarmyDev** [comment]
After double-checking it appears I may have just heard it somewhere or it might just be a false memory that my brain somehow made. I'll modify the PR to only include the changed package name

**Comment by KarmyDev** [comment]
Upon closer inspection, I noticed that I was modifying apt install command under Ubuntu 22.04, while I had Linux based on Ubuntu 20.04. One way to fix this is to add separate header for 20.04, and put full command under it. However, as of today, the documentation on Linux installation via apt is already updated, so the easiest way would be to close this PR, that is, if there is nothing wrong with doing so.

**Comment by adegeo** [comment]
@KarmyDev Thanks a bunch for doing this, even though we're closing it. I appreciate your enthusiasm 😁

**Pull request closed without merging**
