### PR TITLE
Replace Visual C# token

### PR DESCRIPTION
**Pull request by ErlendLandro**
For #4801

### CODE REVIEW

**Comment by Mackiovello** [comment]
I should have split this PR into two or three different PRs to avoid changes to this many files at once.

**Review by BillWagner — APPROVED** [review]
Also great work @Mackiovello 

Thank you!  I'll :shipit: once you resolve the merge conflicts.

This one is small enough (as a focused search/replace) that I can review it as is without splitting. Thanks for offering to split it up though.

**Comment by Mackiovello** [comment]
There we go! Should be ready to merge now

**Comment by BillWagner** [comment]
@Mackiovello There is one build error. It looks like you missed one instance of this include in docs/framework/data/wcf/creating-the-data-service.md

**Pull request merged**
