### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by badersur**
Links to tutorials are repeated and I suggest restructuring the article a little bit; starting with supported platforms, any notes then the tutorials.

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1051](https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1051)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609202039202484-1051%5Cworkflow_report.html).

**Comment by mairaw** [comment]
I've close and reopened just to test something in our environment. Good catch @badersur!

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1051](https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1051)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C21%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609202358277584-1051%5Cworkflow_report.html).

**Comment by badersur** [comment]
Links to VS Code points to the old https://www.visualstudio.com/products/code-vs. I've updated it in my suggested PR #1052.

**Pull request merged**
