### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by sam951013**
I changed some words.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/b853af7f19af6180e67340e129475f9ecb3076fa/docs/core/install/windows.md) | [Install .NET on Windows](https://review.learn.microsoft.com/en-us/dotnet/core/install/windows?branch=pr-en-us-38677) |

### CODE REVIEW

**Comment by sam951013** [comment]
@dotnet-bot Can you help me Merge this PR?

**Comment by sam951013** [comment]
@adegeo

**Comment by adegeo** [comment]
Hi @sam951013 thank you for submitting an enhancement. Was there a specific reason you were changing this text? The link is about installing .NET as a whole, SDK or Runtime. So I don't want to call out just the SDK in the link title.

**Review by adegeo — CHANGES_REQUESTED** [review]
Hi @sam951013 thank you for submitting an enhancement. Was there a specific reason you were changing this text? The link is about installing .NET as a whole, SDK or Runtime. So I don't want to call out just the SDK in the link title.

**Pull request closed without merging**
