### PR TITLE
Rename ReRoutes to Routes

### LINKED ISSUE #18761: Ocelot renamed ReRoutes to Routes. /dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot is outdated
Hello,

Since version 16.0, Ocelot use Routes property instead of ReRoutes. See commit https://github.com/ThreeMammals/Ocelot/commit/3439be89271bb37b170429d69ca74978c941432e

This document describe an Ocelot usage with ReRoutes property that do not work with latest ocelot version.

Could you update this document please ?

Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

### PR DESCRIPTION
**Pull request by worming004**
With the this fix, we implement an ocelot's breaking change

Fixes #18761

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=19980) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=19980) before we can accept your contribution.<br/><br/>:x: worming004 [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=19980)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=19980) it.</sub>

**Comment by nishanil** [comment]
Thanks for the PR, @worming004 
I noticed Figure 6-32. also needs to be updated - it still refers to earlier Ocelot version. It's tricky to maintain this page as we moved away from Ocelot implementation in eShop. @sughosneo The master branch of eShop is on 2.2 and has Ocelot implementaiton. It may be good idea to test these changes there and then extract new images of that.
In the long run, we should consider updating this guide to the Envoy implementation.

**Comment by nishanil** [comment]
Ok. In that case it is best to leave the current implementation as-is and just update the version numbers of Ocelot in the "Important" section. That way we're explicitly stating that the implementation refers to the Ocelot version "x.x" and not latest. 
@worming004 Are you willing to update this PR?

@sughosneo Can you add a task in our backlogs to update this page to Envoy, please?

**Comment by sughosneo** [comment]
> Ok. In that case it is best to leave the current implementation as-is and just update the version numbers of Ocelot in the "Important" section. That way we're explicitly stating that the implementation refers to the Ocelot version "x.x" and not latest.
> @worming004 Are you willing to update this PR?
> 
> @sughosneo Can you add a task in our backlogs to update this page to Envoy, please?

@nishanil - Task is created in our backlog to update this page.

**Comment by sughosneo** [comment]
> > Ok. In that case it is best to leave the current implementation as-is and just update the version numbers of Ocelot in the "Important" section. That way we're explicitly stating that the implementation refers to the Ocelot version "x.x" and not latest.
> > @worming004 Are you willing to update this PR?
> > @sughosneo Can you add a task in our backlogs to update this page to Envoy, please?
> 
> @nishanil - Task is created in our backlog to update this page.

@worming004 - thanks for updating this PR.

**Review by nishanil — APPROVED** [review]
Looks good. Thanks @worming004

**Pull request merged**
