### PR TITLE
Update enumeration-classes-over-enum-types.md

### LINKED ISSUE #12326: CardType is abstract
I think the sample class is incorrect:

    public abstract class CardType : Enumeration

If CardType is abstract, how can its members instantiate it:

    public static CardType Amex = new CardType(1, "Amex");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by MarkMcGee1**
## Providing a fix for https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1529481

Describe your changes here.
  removed 'abstract' keyword

Fixes #12326

### CODE REVIEW

**Comment by MarkMcGee1** [comment]
@BillWagner, fyi, I'm submitting a fix based on localization feedback. thx, -Mark

**Comment by BillWagner** [comment]
Ping @CESARDELATORRE for a review.

This fix changes the semantics of the `CardType` class. Should the constructor be `private` to prevent arbitrary instances being created?

**Comment by mairaw** [comment]
Pinging @nishanil and @mvelosop instead

**Review by mvelosop — APPROVED** [review]
Thanks @MarkMcGee1, this fix is right, actually that's just like the current code! 😊

**Comment by mvelosop** [comment]
@BillWagner, I think your suggestion is completely valid for enumerations.

Probably CardType is not the best use case for enumerations, but it's OK, given the way is currently being used in eShop.

I'll change it in the eShop repo, along with OrderStatus, that's in the same situation and then fix the guide after checking everything works in the app.

Cheers!

**Comment by mvelosop** [comment]
@mairaw, this is good to merge when you're ready.

**Pull request merged**
