### PR TITLE
Stackalloc: added usage guidelines

### LINKED ISSUE #17207: Dos and don'ts of stackalloc
The `stackalloc` article might be updated according to the following blog post:
https://vcsjones.dev/2020/02/24/stackalloc/

@vcsjones are you fine with that? If yes, @BillWagner could you please assign this issue to me. I'll try to add one-two new paragraphs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecde487e-96e5-85c2-ff87-227994f705ad
* Version Independent ID: f77588b3-9b31-f8ce-fad5-bf937337eb8c
* Content: [stackalloc operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc)
* Content Source: [docs/csharp/language-reference/operators/stackalloc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/stackalloc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by pkulikov**
Fixes #17207
@vcsjones what do you think?

### CODE REVIEW

**Review by BillWagner — COMMENTED** [review]
This really looks good @pkulikov 

I'll merge tomorrow, but I'd like to give @vcsjones more time to review as well.

**Comment by pkulikov** [comment]
@BillWagner the latest commit is a companion to #17456

**Review by BillWagner — APPROVED** [review]
This slipped through the cracks on my side.  I apologize @pkulikov 

I'll :shipit: now.

**Comment by pkulikov** [comment]
Oh, @BillWagner, no worries; such times. Take care.

**Pull request merged**
