### PR TITLE
Replaced fwlinks in fsharp folder

### PR DESCRIPTION
**Pull request by pkulikov**
Replaced all found fwlinks in fsharp folder (related to #3391)
In addition, replaced msdn links found in neighborhood.

## Suggested Reviewers
@mairaw please review

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
Looks great @pkulikov. There are a couple of links that have the `https://docs.microsoft.com/en-us`, let's just remove those similar to how you did the azure ones below.

**Comment by pkulikov** [comment]
@mairaw just to confirm the rule for such links: if the full link starts with `https://docs.microsoft.com/en-us` and does not belong to this repository, that prefix part can be just thrown away (plus no `.md` suffix required)? Is that correct?

**Comment by mairaw** [comment]
Yes, that's right @pkulikov. I need to put that rule in our style guide.

**Comment by pkulikov** [comment]
Oh, by the way, as for the style guide, I have a list of minor things to improve (that was one of them). I'll create an issue for that later this week.

**Comment by mairaw** [comment]
Sure, sounds great!

**Comment by pkulikov** [comment]
@mairaw I've updated links, please check again.

**Review by mairaw — APPROVED** [review]
Thanks @pkulikov. There was only one broken link that I've fixed. I'll merge once build completes successfully. I really appreciate your help with these links.

**Comment by pkulikov** [comment]
@mairaw thank you for fixing that link.

**Comment by mairaw** [comment]
No worries @pkulikov. Thanks for the PR!

**Pull request merged**
