### PR TITLE
Updated note with correct adjustment rule information

### LINKED ISSUE #5172: Note about DateTime.ToUniversalTime is incorrect
The note box on this page states that `TimeZone.ToUniversalTime` and `DateTime.ToUniversalTime` only use the current adjustment rule.  This is correct for `TimeZone`, but not for `DateTime`.

For `DateTime`, that *used* to be the case, but only on Windows XP systems.  Windows Vista and newer, as well as all .NET Core implementations, behave correctly.   The note should be updated to correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 165831e9-1356-2549-bc9c-4b3f3270e8b5
* Version Independent ID: 86102ae6-80c7-3414-dfe9-9e2f372e1338
* Content: [Converting times between time zones](https://docs.microsoft.com/en-us/dotnet/standard/datetime/converting-between-time-zones)
* Content Source: [docs/standard/datetime/converting-between-time-zones.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/converting-between-time-zones.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

### PR DESCRIPTION
**Pull request by daveabrock**
Updated based on the comment from @mj1856. I went back and forth about eliminating this entirely, wondering if we should make assumptions about not using XP since it is not supported - but left it in for clarity. Let me know what you think!

Fixes #5172

### CODE REVIEW

**Comment by daveabrock** [comment]
Also, being a new contributor let me know rather you would want me to get this clarifying information from you first, or just submit a PR.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Submitting a PR is fine, @daveabrock, unless there's something you'd prefer to clarify first. In this case, since this is now an XP-only issue and XP is no longer supported, it's best to simply delete the note. Would you like to revise your PR to do that, or would you like us to do it for you?

**Comment by daveabrock** [comment]
Thanks for the clarification, @rpetrusha - I have deleted the note entirely.

**Comment by rpetrusha** [comment]
Thanks, @daveabrock. I'll merge your PR now. Your change should be live on docs.microsoft.com tomorrow.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
