### PR TITLE
Fix LocBaml link

### LINKED ISSUE #3623: Fix Link to Sample Application in Microsoft Document
Fix Link to Sample Application in Microsoft Document

Regarding this document - https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application  

in above document , in Create a Sample Application section
Link to LocBaml Tool Sample does not work 

edit by @mairaw: added docs info below 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [How to: Localize an Application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### PR DESCRIPTION
**Pull request by imba-tjd**
Fixes dotnet/docs.zh-cn#435
Fixes #3623

### CODE REVIEW

**Comment by Thraka** [comment]
Hi! Thanks a bunch for this fix. I've edited your comment to use the word "Fixes" which automatically causes those issues to be closed when this PR is merged.

**Review by Thraka — APPROVED** [review]

**Comment by imba-tjd** [comment]
@Thraka I know `fixes`, but I don't think it's appropriate to close the second issue.

**Comment by mairaw** [comment]
I think that should be fine @imba-tjd. I missed that the sample was merged back in May. I also updated the original FwLink to go to the new location. Is there anything else we're missing?

**Comment by imba-tjd** [comment]
@mairaw 🆗

**Pull request merged**
