### PR TITLE
Revisions to API portal

### PR DESCRIPTION
**Pull request by rpetrusha**
It seems best to keep the introductory section as short and simple as possible.

### CODE REVIEW

**Comment by stevehoag** [comment]
LGTM

**Comment by mairaw** [comment]
@rpetrusha, since you're already touching this topic, do you mind adding the metadata section on this one? It's the only one missing that.

**Comment by rpetrusha** [comment]
@mairaw Certainly. I didn't even think to check that it was present or not.

**Comment by mairaw** [comment]
LGTM. On the metadata section, remove the hyphen from the beginning of each line and change the ms.topic type to managed-reference and you're good to merge.

**Pull request merged**
