### PR TITLE
Introduce code spans

### PR DESCRIPTION
**Pull request by nxtn**
Proposal: Use code spans to correct line breaks after #10194.

### CODE REVIEW

**Comment by NextTurn** [comment]
I'll make more changes if you approve this.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks, @NextTurn, for the suggestion. Using code spans to prevent unwanted breaks works much better than the original `<br/>` tags. Could you apply them consistently in the **Matches** columns?

**Comment by NextTurn** [comment]
Code spans still can't break lines correctly... But they may resolve some problems in loc docs.

**Comment by NextTurn** [comment]
Done @rpetrusha. I'm not sure if these will help.

**Comment by rpetrusha** [comment]
Thanks, @NextTurn. They're a considerable improvement. I'll merge your PR now.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
