### PR TITLE
Use samples browser link

### PR DESCRIPTION
**Pull request by Youssef1313**
**DON'T YET MERGE**

@briacht Looks like the README is in https://github.com/dotnet/machinelearning-samples/tree/main/samples/modelbuilder/ObjectDetection_StopSigns/StopSignDetection instead of https://github.com/dotnet/machinelearning-samples/tree/main/samples/modelbuilder/ObjectDetection_StopSigns/? (opened https://github.com/dotnet/machinelearning-samples/pull/887 for that)

Also need to enable the "download zip" button for ease of download for page visitors (I pinged you in an issue containing some details on this) (trying to address it in the same PR).

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/machine-learning/tutorials/object-detection-model-builder.md](https://github.com/dotnet/docs/blob/ee3a56d4e196cce76e235f8619f9e844c78ad597/docs/machine-learning/tutorials/object-detection-model-builder.md) | [Tutorial: Detect stop signs in images with Model Builder](https://review.learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder?branch=pr-en-us-23413) |

### CODE REVIEW

**Review by luisquintanilla — APPROVED** [review]
Looks good to me.

**Comment by briacht** [comment]
@Youssef1313 Is there anything that I need to do here?

**Comment by Youssef1313** [comment]
@briacht Nope, already opened https://github.com/dotnet/machinelearning-samples/pull/887 to move the README to the parent directory, but still blocked on how to get the "Download ZIP" button there (this is being discussed in https://github.com/dotnet/docs/issues/23380 - once I know the correct way for doing this, I'll update https://github.com/dotnet/machinelearning-samples/pull/887 and this will be ready to get merged).

**Comment by briacht** [comment]
Awesome, thank you @Youssef1313 !

**Review by gewarren — APPROVED** [review]

**Pull request merged**
