### PR TITLE
Clean up byrefs formatting

### PR DESCRIPTION
**Pull request by cartermp**
* Bad header for C#
* Bad code sample

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @cartermp 

You can :shipit: when ready.

**Comment by cartermp** [comment]
Is our CI down after the rename from VSTS to Azure Devops?

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
@cartermp, the PR validates now, if you'd like to merge.

**Pull request merged**
