### PR TITLE
Add initialisms to text

### LINKED ISSUE #29938: The Capitalization Conventions page should mention 'initialisms' as well as acronyms
**Issue description**

The [Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) page should mention 'initialisms' as well as acronyms.

**Target framework**

Any and all.

### PR DESCRIPTION
**Pull request by SteveDunn**
## Summary

Add mention of initialisms to text

Fixes #29938

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks @SteveDunn 

I've reviewed this change, and I'll :shipit: now.

**Comment by Youssef1313** [comment]
@BillWagner Isn't this a copyrighted content that usually don't accept PRs?

**Comment by BillWagner** [comment]
Thanks @Youssef1313 I had missed that. I'll revert the PR.

I apologize @SteveDunn Your change is fine, but this material is copyrighted by the publisher. We have the right to publish, but not change the content.

**Comment by SteveDunn** [comment]
> Thanks @Youssef1313 I had missed that. I'll revert the PR.
> 
> I apologize @SteveDunn Your change is fine, but this material is copyrighted by the publisher. We have the right to publish, but not change the content.

Oh, that's a shame, but I fully understand. I really liked this book and was a reviewer of the original, but nowadays, I think that we need an alternative '**Application** Design Guidelines': guidelines for consistent and readable applications. Also, @BillWagner, we've spoken in the past about how some of the data is now out of date (particularly around what collections to accept/return from methods). You mentioned trying to get the latest revision of this content to publish. Has there been any success with this?

**Pull request merged**
