### PR TITLE
Create "Deploy a Worker Service to Azure" article

### LINKED ISSUE #24307: Migration guide: Promote your on-premises worker service to the cloud
Show how to migrate an on-premises worker, with configuration, and proper API access to the cloud.

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

New "Deploy a Worker Service to Azure" article.

Fixes #24307

## Internal preview

✔️ [Deploy a Worker Service to Azure](https://review.docs.microsoft.com/en-us/dotnet/core/extensions/cloud-service?branch=pr-en-us-24477)

### CODE REVIEW

**Comment by IEvangelist** [comment]
Attn: @bradygaster

**Comment by bradygaster** [comment]
This is a fantastic start to this doc. I love the consistent approach showing how to do this using VS, VSC, and the CLI tools. Really exciting.

**Comment by bradygaster** [comment]
When this goes live, I'd like to have it included as a featured doc in this page: https://docs.microsoft.com/en-us/dotnet/

Ideally, we could have a link to this doc in one of these two boxes, too. I think there's merit to this one being linked in the Azure box, but as we have some other Worker-as-microservice articles coming out, we should add them to the boxes, here, too. We need to let customers know that the Worker is great for building microservices, and with all the new docs we have a lot more opportunities to associate with these top-level ideas. 

image

**Review by CamSoper — APPROVED** [review]
I don't have anything to add, I walked through it and it looks good. 🤘🏻

**Pull request merged**
