### PR TITLE
Replace Xref links

### PR DESCRIPTION
**Pull request by JRAlexander**
[Internal Review link](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api?branch=pr-en-us-12389)

### CODE REVIEW

**Comment by JRAlexander** [comment]
Closing and reopening

**Comment by JRAlexander** [comment]
@mairaw - still warnings on all the xrefs... closing and reopening...

**Review by luisquintanilla — APPROVED** [review]
Looks good.

**Comment by JRAlexander** [comment]
Thanks, @luisquintanilla!!!

**Pull request merged**
