### PR TITLE
topic update

### PR DESCRIPTION
**Pull request by mairaw**
/cc @conniey 

This article always gets shown a lot at //Build at the .NET booth. Updating with latest screenshots and VS support info.

WIP on the title is so this doesn't get merged accidentally, but it's ready for review.

Review link: https://review.docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer?branch=pr-en-us-12067

### CODE REVIEW

**Comment by mairaw** [comment]
Also, are we going to be adding 4.8 to this tool?

**Comment by conniey** [comment]
Looks good. Thanks for updating it! :D

**Review by BillWagner — APPROVED** [review]
This LGTM @mairaw 

You can :shipit: when ready, or if you want to have another review, just ping.

**Comment by mairaw** [comment]
No need @BillWagner. Just wanted to hold the PR while the branches situation wasn't sorted out last Friday.

**Pull request merged**
