### PR TITLE
Tool list package id feature doc update

### PR DESCRIPTION
**Pull request by JiaqiWang18**
## Summary
Doc change for tool list package id feature: https://github.com/dotnet/sdk/pull/28333

Issue in SDK repo: https://github.com/dotnet/sdk/issues/23549

### CODE REVIEW

**Review by tdykstra — COMMENTED** [review]
Looks good, just one minor suggestion.

**Review by tdykstra — APPROVED** [review]

**Review by tdykstra — COMMENTED** [review]
This can't be merged until the change in https://github.com/dotnet/sdk/pull/28333 gets into a public release.

**Comment by RiverWalker92** [comment]
@IEvangelist  Does the 'DO NOT MERGE' label not apply anymore? I read this option in the docs, and wasted some good time, trying to figure out why my version of dotnet was not accepting it. I believe it is still not in the main SDK.

**Comment by IEvangelist** [comment]
You're right, this should not have been merged. I overlooked the label and had set this to auto-merge. I'm going to revert these changes, and we can wait to merge this.

**Pull request merged**
