### PR TITLE
Update `Search()` formatting to be consistent with earlier usage

### PR DESCRIPTION
**Pull request by eonarheim**
## Summary

Update formatting of `Search()` to be consistent with earlier usage

Fixes: N/A

### CODE REVIEW

**Comment by eonarheim** [comment]
I also noticed that the `SearchDirectoryArgs` sample is a struct doesn't extend `EventArgs`, I can open another pr for this or include it in this one. Not sure if that was intentional when other samples are classes and extend `EventArgs`.

image

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thank you for contributing to the dotnet/docs repo and standardizing the use of `Search`, @eonarheim. A better choice, though, would be to use `Search` rather than `Search()`; I'd appreciate it if you could make that change. As you noted, `SearchDirectoryArgs` should be a class that inherits from `EventArgs`, If you'd like, you can also make that change in this PR.

**Comment by eonarheim** [comment]
@rpetrusha I've made the requested changes, looks like the sample are stored in a separate repo so I've made a PR there as well https://github.com/dotnet/samples/pull/423

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
Thank you, @eonarheim, for submitting the additional PR in the dotnet/samples repo, as well as for making the additional changes to this PR. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

**Pull request merged**
