### PR TITLE
Documented all Explicit and Implicit operators for System.Decimal.

### PR DESCRIPTION
**Pull request by tompratt-AQ**
# Title
Documented all Explicit and Implicit operators for System.Decimal.

## Summary
Pulled information from CAPS and MSDN to document the 13 Explicit operators and 9 Implicit operators in System.Decimal. Each operator has 3 code examples (cpp, c#, vb) except one which had only 2. 

## Suggested Reviewers
@rpetrusha

### CODE REVIEW

**Comment by tompratt-AQ** [comment]
@rpetrusha could you restart this PR for me? It's been stuck on the checks since yesterday. Thanks.

**Comment by rpetrusha** [comment]
Closing and reopening to restart build

**Comment by rpetrusha** [comment]
@tompratt-AQ, could you check the build report and fix the broken xrefs please?

**Comment by tompratt-AQ** [comment]
I thought I was clear if "All checks have passed". Do I look under Warnings in the build report?  
The ones listed there don't look like links that I edited.

**Comment by rpetrusha** [comment]
@tompratt-AQ, yes, look in the warnings section in the build report for `api/System.Decimal.yml`. We should take the opportunity to fix broken links as long as we're making changes to the document.

**Comment by tompratt-AQ** [comment]
@rpetrusha Thanks for pointing that out Ron! I hadn't noticed System.Decimal in the list. I was able to track down and fix all the bad links that were listed.

**Comment by rpetrusha** [comment]
There's also a couple of somewhere in the UIntPtr.yml file, @tompratt-AQ. It would be nice if you could fix it:
- In UIntPtr.yml: `Invalid cross reference "&lt;xref:System.%2A&gt;"`

**Comment by tompratt-AQ** [comment]
@rpetrusha I actually spotted that one in the list (now that you've told me the secret!) and fixed it in the commit for PR #2752 that is being checked and built right now.

**Review by rpetrusha — CHANGES_REQUESTED** [review]

**Comment by tompratt-AQ** [comment]
@rpetrusha I addressed all of your suggested changes and found an existing identical exception block with "-or-" in the same topic that I copied and used exactly - so I'm hoping that will solve the formatting issue.

**Comment by rpetrusha** [comment]
This looks good, @tompratt-AQ. Thanks. I'll merge it now.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
