### PR TITLE
stubbed out home page based on recent comps

### PR DESCRIPTION
**Pull request by adkinn**

### CODE REVIEW

**Comment by mairaw** [comment]
@adkinn are you done with this PR?

**Comment by adkinn** [comment]
Yes, I am handing this off to @bradygaster now that I have the base structure in place.

**Comment by bradygaster** [comment]
LGTM

**Comment by bradygaster** [comment]
@mairaw @adkinn Once this is in I'll do some subsequent edits on it to get the content in that we know about to date. @richlander is also going to be tweaking some of this and finalizing the content. At least we'll have the page readied for the content and outbound links.

**Comment by mairaw** [comment]
Sure, I wasn't sure if you wanted to check-in the final product or not. Sometimes we'll create a branch off of master so multiple people can work on it and just merge the final version. But I just merged this in @bradygaster.

**Pull request merged**
