### PR TITLE
CC92049: Remoing 92,049 "<br /><br />"

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @rpetrusha,
This proposed file change comes from https://github.com/dotnet/docs.tr-tr/pull/7 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by mairaw** [comment]
I'm going to close this PR @v-makoud. The text is correct as-is in English. Not sure if it makes a difference in Turkish.

/cc @NextTurn

**Comment by NextTurn** [comment]
I think words on the sides of the `içinde` in Turkish is inverted, compared to `in` in English.

**Comment by NextTurn** [comment]
The words on both sides of the preposition `içinde` in Turkish are inverted, compared to the `in` in English.

**Comment by mairaw** [comment]
That's what I thought @NextTurn. @v-makoud so please make sure you tag this as a translation suggestion not a source issue.

**Comment by NextTurn** [comment]
There are no source issues. I created PRs in localized repos to make sure they are consistent with the English repo.

**Comment by mairaw** [comment]
Did my fix solve the localization issue @JasonCard?

**Comment by JasonCard** [comment]
@mairaw yes, we're in the process of bug fixing now, but I confirmed we can now translate these segments as one sentence.

**Comment by NextTurn** [comment]
The translation issues in the Anchors section were fixed. Thanks for your help @mairaw.

**Pull request closed without merging**
