### PR TITLE
Use conventional camelCasing for local var in C# sample

### PR DESCRIPTION
**Pull request by ancoope**
# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
Thanks @ancoope for this change. It reads much better like this. Would you mind making the same exact change to the VB snippet above the C# one so the two of them match? Thanks!

**Comment by ancoope** [comment]
Updated with requested VB change

**Review by mairaw — APPROVED** [review]
Thank you @ancoope! I'll just wait for the build to finish to   merge your PR.

**Comment by mairaw** [comment]
I'll close and reopen the PR because our build has failed with an exception.

**Comment by mairaw** [comment]
Thank you @ancoope! Build has passed now. Your fix should go live in the next day or so.

**Pull request merged**
