### PR TITLE
Add missing blazorwasm options

### PR DESCRIPTION
**Pull request by mairaw**
I've noticed the blazorwasm options were missing

Also, I've noticed some issues with the CLI options and descriptions. @danroth27 @KathleenDollard who would be the right person to follow up with? I could try to put a PR to fix.

For example: 
- auth option doesn't list MultiOrg as a possible value, but then other options mention that auth (I'm assuming on this PR that the auth values were correct)
- //// in one of the default value URLs
- a few typos

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
Looks good to me, :shipit: when you're ready.

**Comment by BillWagner** [comment]
@mairaw Did you want to wait for @danroth27 or is this ready to merge?

**Comment by mairaw** [comment]
It's up to you guys! I made some assumptions re. this as I indicated in the original description, which would be nice to confirm.

**Review by danroth27 — APPROVED** [review]
LGTM

**Pull request merged**
