### PR TITLE
Added context

### PR DESCRIPTION
**Pull request by SteveLasker**
for the various docker images and dynamic ports

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1048](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1048)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201856105989-1048%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1048](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1048)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201857350449-1048%5Cworkflow_report.html).

**Review by spboyer — APPROVED** [review]

**Comment by spboyer** [comment]
Thanks @SteveLasker for the additions 👍

**Comment by spboyer** [comment]
@BillWagner if this looks good to you, please merge.

**Comment by BillWagner** [comment]
Looks good.  :shipit:

**Pull request merged**
