### PR TITLE
Update NamedPipeServerStream.xml

### PR DESCRIPTION
**Pull request by hillmarcus**
Fixed bad links to Enum Types PipeDirection.In/Out/InOut

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @hillmarcus. I'll actually investigate why those are broken because the xref ID looks correct for those, so they should be working.

**Comment by mairaw** [comment]
This seems like a widespread issue with enum fields. Just found some other examples such as https://docs.microsoft.com/en-us/dotnet/api/system.datetime.dayofweek.

**Comment by hillmarcus** [comment]
Yeah, I noticed quite a few spots myself. Might be an issue with the
rendering engine. I tried messing around with the url to get some sort of
direct link to enum value, but I couldn't figure it out. I'm not entirely
sure there is a special url for enum value.

I figure my changes should make it look proper and take the user to the
enum page at least. If you think we should wait for a more proper fix, I
understand.

On Dec 22, 2017 5:19 PM, "Maira Wenzel" <notifications@github.com> wrote:

This seems like a widespread issue with enum fields. Just found some other
examples such as https://docs.microsoft.com/en-
us/dotnet/api/system.datetime.dayofweek.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/docs/pull/4011#issuecomment-353689290>, or mute
the thread

**Comment by mairaw** [comment]
The built content for the PR still looks broken:
image

I've opened an internal bug for this so I'll close this PR. Thanks for bringing this to our attention @hillmarcus!

**Pull request closed without merging**
