### PR TITLE
Fix rendering

### LINKED ISSUE #23131: Formatting is broken by the dollar sign in brackets.
Where the markdown file says ```use an anchor ("$"): "[a-z]+\\.contoso\\.com$". ```

The rendering on docs.microsoft.com is broken:

image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6578b3-bbe7-91cd-942c-4383d9c89045
* Version Independent ID: 51b0a006-5125-31f8-0eaa-0ea7e96cf678
* Content: [&lt;bypasslist&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/bypasslist-element-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/bypasslist-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/bypasslist-element-network-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #23131

Please check on staging before merging.

### CODE REVIEW

**Comment by adegeo** [comment]
Weird. I checked the site and its transforming the content to MATH equations after the page has finished loading.

**Comment by Youssef1313** [comment]
@adegeo I don't even know how to do this purposefully 😄

**Comment by adegeo** [comment]
Yeah. I'm in the middle of creating the site issue and in describing it in the issue I think I discovered it, it's the `$` character. It's been stripped from both ends, I wonder if that's a magic signal to say this is math.

**Comment by adegeo** [comment]
OK that is the problem.. I found some other articles that do this purposefully: https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/concepts-advanced-matrices.md

**Review by adegeo — APPROVED** [review]

**Comment by adegeo** [comment]
Thanks @Youssef1313 😄

**Pull request merged**
