### PR TITLE
Cloud Native - Updates to Ch 1...

### PR DESCRIPTION
**Pull request by robvet**
## Summary

    Table "Company" "Experience" is not right
    WeChat has popped into 3rd column

    In Header, the "Service Mesh" has to be replaced with "Service mesh" and "Front-End" with "Front-end" 
   Chapter 5 and 6 swapped including TOC.

### CODE REVIEW

**Comment by mairaw** [comment]
There are no changes in this PR?

**Comment by robvet** [comment]
Believe  there should be a merged md file in it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nishanil** [comment]
@robvet  This PR does not have any files right now. Can you close this PR sand send a new one with just the changes that we discussed? Most importantly, fix the table where the WeChat info is duplicated in col 3.

**Comment by robvet** [comment]
Closing due to issues. Will reopen new pull request for this content.

**Pull request closed without merging**
