### PR TITLE
More issue template updates

### PR DESCRIPTION
**Pull request by gewarren**
Fast follow to #39354.

Also renames to use numbers to order templates instead of letters.

### CODE REVIEW

**Comment by BillWagner** [comment]
@gewarren 

I like what's here, but you also need to change the name of the issue template in our docfx.json [here](https://github.com/dotnet/docs/blob/main/docfx.json#L132)

Otherwise, the feedback control won't work.

**Comment by gewarren** [comment]
> @gewarren
> 
> I like what's here, but you also need to change the name of the issue template in our docfx.json [here](https://github.com/dotnet/docs/blob/main/docfx.json#L132)
> 
> Otherwise, the feedback control won't work.

@BillWagner What do I need to update there?

**Comment by BillWagner** [comment]
> @BillWagner What do I need to update there? I didn't change the name of the z-customer-feedback.yml template.

You're right. I looked at the comment, but didn't notice that the first and last weren't renamed.

Approving.

**Review by BillWagner — APPROVED** [review]
This LGTM. Let's merge it.

**Pull request merged**
