### PR TITLE
JS Frameworks links updates

### PR DESCRIPTION
**Pull request by mcrio**
Update Angular link to point to latest version website.
Update JS Frameworks comparison link to point to a more recent comparison of different frameworks.

### CODE REVIEW

**Comment by BillWagner** [comment]
@CESARDELATORRE Can you look at and review this PR?

**Comment by mairaw** [comment]
@ardalis can you please look at this?

**Review by ardalis — APPROVED** [review]
Looks good; these are better links.

**Review by mairaw — APPROVED** [review]
Thank you @nikolajosipovic for changing the links and @ardalis for the review.

**Pull request merged**
