### PR TITLE
Update resources link to eShopOnContainers repo

### LINKED ISSUE #19245: Additional resources links are invalid, returns 404.
Additional resources links are invalid, returns 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245ea389-75e9-1321-3be4-dc8d8e47a925
* Version Independent ID: 1db547e8-a0b0-cf44-dba4-b65786c576fe
* Content: [Testing ASP.NET Core services and web apps](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

### PR DESCRIPTION
**Pull request by Marusyk**
## Summary

Update resources link to eShopOnContainers repo

Fixes #19245

### CODE REVIEW

**Comment by Marusyk** [comment]
@nishanil why did you merge the same PR created at a few hours ago, but skip this one?

**Comment by BillWagner** [comment]
@nishanil This PR is getting stale (and has conflicts now). Can you give it a review and check?

**Comment by nishanil** [comment]
@Marusyk Apologies for overlooking this PR. And, Thank You for helping us out here. 
We had internally triaged this bug and @sughosneo was working on this along with the others that were prioritized to go out that week. Closing this PR now.

**Comment by sughosneo** [comment]
> @Marusyk Apologies for overlooking this PR. And, Thank You for helping us out here.
> We had internally triaged this bug and @sughosneo was working on this along with the others that were prioritized to go out that week. Closing this PR now.

Thank you @nishanil for clarifying the details.

Yes @Marusyk, As a part of other changes, I have also fixed this item in a single PR without seeing the existing one of yours. Sorry about that. But keep sharing your feedback as issues or PRs. We will be happy to review and merge the changes in future. Thanks again for your help.

**Pull request closed without merging**
