### PR TITLE
typo: Double word "it"

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
The sentence could still use a little work

**Comment by mairaw** [comment]
Thanks for fixing the typos. I agree with you that the sentence still needs work. Added @mvelosop to review that.

**Comment by mvelosop** [comment]
Paragraph restructured, is it better like this? 😊

**Review by BillWagner — APPROVED** [review]
Mob editing by @nschonni @mvelosop with @mairaw as well. 🤗 all around.

I'll :shipit: now.  

Thanks for all the improvements.

**Pull request merged**
