### PR TITLE
First linq code sample

### PR DESCRIPTION
**Pull request by matthewreily**
Looking for some feedback on the structure of this example. I went out and grabbed one of the examples from the linq 101 msdn site https://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b.  With this sample I created 2 methods to show both the linq query and method syntax.  Is this how we should go about it or should we just show one version of the syntax?

### CODE REVIEW

**Comment by matthewreily** [comment]
This is for #90 @BethMassi

**Comment by BethMassi** [comment]
@matthewreily thanks for this. We want to be able to run these samples against the latest coreclr runtime so we need a couple things. First, we'll need to add a main entry point so I think we should have a program.cs file for each project.json we have. Something like: 

 public class Program
    {
        public void Main(string[] args)
        {
            var sample = new WhereClause1();
            sample.QuerySyntaxExample();
            sample.MethodSyntaxExample();
        }
    }     

Next, it looks like we'll need to specify "dnxcore50" in the frameworks section of the project.json. Then we should be able to "dnvm upgrade latest -r coreclr -u" and then "dnx run" in the sample folder. 

Can you fix your PR?

**Comment by BethMassi** [comment]
I created step-by-step instructions here: https://github.com/dotnet/core-docs/blob/master/samples/README.md

Hope this helps! :smile:

**Comment by matthewreily** [comment]
You are amazing @BethMassi! Thank you for your help.  I noticed one issue in the readme.md in regards to the version of system.console.  I recieved an error "Unable to locate Dependency System.Console >= 4.0.0-rc1-*" when running dnu restore.  I updated my project.json to use the 4.0.0-Beta-* version

**Pull request merged**
