### PR TITLE
Add .Net Framework 4.7 to the list.

### PR DESCRIPTION
**Pull request by RobertTheNerd**

### CODE REVIEW

**Comment by mairaw** [comment]
Hi @RobertTheNerd. Thanks for your contribution. I'm closing this PR since we recently changed this topic to actually remove the values for .NET Standard 1.6 and 2.0 for the 1.0 tooling line. You can see more information at the following issue: https://github.com/dotnet/docs/issues/1974

**Comment by tmlye** [comment]
@mairaw Could you please clarify why the values for .NET Standard 1.6 and 2.0 were removed? According to this [blogpost](https://blogs.msdn.microsoft.com/dotnet/2017/05/02/announcing-the-net-framework-4-7-general-availability/), 4.7 supports .NET Standard 1.6.

**Comment by svick** [comment]
@tmlye See https://github.com/dotnet/docs/issues/1974.

**Comment by tmlye** [comment]
@svick That thread does not answer my question completely. The blogpost I linked to was written on the 02.05.2017 (more recent than #1974), stating that 4.7 supports .NET Standard 1.6. If this is true, then why does the table not state that and why was this pull request denied?

**Comment by svick** [comment]
@tmlye I'm very confused. It seems you are right, .Net Framework 4.7 projects can reference .Net Standard 1.6 libraries using the .Net Core 1.0 tooling. (.Net Framework 4.7 does not actually implement the APIs that are new in .Net Standard 1.6, but I think that's not relevant here.)

I'm also sorry I just pointed you to an issue that way already linked here before, I should have paid more attention.

@mairaw Should this PR be reopened and merged, since the blog post linked by @tmlye says it's supported and since my testing shows it's indeed true?

**Pull request closed without merging**
