### PR TITLE
Bad Link

### PR DESCRIPTION
**Pull request by billmcilhargey**
Replacing with this as the suggested link "dotnet/fsharp/get-started/" - but double check to make sure it is the correct intended link

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
Thanks for catching this @computeronix. My suggestion would be to just add the missing period in front of the folder name like this: `[Get Started](./get-started/index.md)`

**Comment by computeronix** [comment]
@mairaw  that still would not resolve as the index.md does not exist

For example adding the ./get-started/index.md would create the link https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/index.md which still does not work

However we can do ./get-started/ and that seems to work?

**Comment by svick** [comment]
> For example adding the ./get-started/index.md would create the link https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/index.md which still does not work

It would not. The system removes the `.md` extension when publishing to docs.MS.

For example, consider the link just above: `[F# Interactive](tutorials/fsharp-interactive/index.md)`. On docs.MS, it points to https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/fsharp-interactive/index.

**Comment by computeronix** [comment]
ohh gotcha!  ok didn't know that  thanks for teaching me :)

Modified to the recommended by @mairaw

**Review by mairaw — APPROVED** [review]
Thank you for making the fix @computeronix and @svick for jumping in and helping explain how the internal links work.

**Pull request merged**
