### PR TITLE
fix: various typos in code samples

### PR DESCRIPTION
**Pull request by nschonni**
## Summary

Took a pass with cSpell. Kept the MD file changes in another PR. Could split this one between the VB and CS changes if it's easier

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [samples/snippets/standard/async/async-and-await/vb/readme.md](https://github.com/dotnet/docs/blob/9c0302751ffa1fd4f34ac5edbe77014e7dfc54c4/samples/snippets/standard/async/async-and-await/vb/readme.md) | [samples/snippets/standard/async/async-and-await/vb/readme](https://review.learn.microsoft.com/en-us/dotnet/samples/snippets/standard/async/async-and-await/vb/readme?branch=pr-en-us-31546) |

### CODE REVIEW

**Comment by BillWagner** [comment]
Hi @nschonni 

I took a brief look at this. I like the changes. How best should we resolve the CI build errors?  They fall into two concerns:

1. Missing a project file. Those should be easy to fix by creating a new `csproj` or `vbproj` file in the correct folder.
2. Missing .NET Framework 4.0. Our CI container doesn't have that version, and those (mostly WPF) samples need to have their projects upgraded. Visual Studio should do that automatically.

There's a few ways to handle this. The simplest is if you update the samples affected by this PR. Alternatively, we can update the builds in a new PR, merge that one, then revisit the builds on this one.

Let me know what you'd like to do.

**Comment by nschonni** [comment]
If you want to address the missing project files, I think it might be better done in another PR, since I'm not sure if you'd want to review if the samples should be kept.

**Comment by BillWagner** [comment]
Hi @nschonni 

I removed a large number of unused samples that were triggered in this PR.

A rebase should simplify things a lot. Or, you can open a new PR with the remaining samples. Whichever is easier for you.

**Comment by nschonni** [comment]
@BillWagner I think there are less errors now 😆

**Comment by adegeo** [comment]
@BillWagner @nschonni 
Upgraded the snippets script to allow bypassing these errors. Add a snippets file with the error, like so:

snippets.5000.json
```json
{
    "host": "dotnet",
    "expectederrors": [
        {
            "file": "samples/snippets/core/tutorials/netcore-hosting/csharp/HostWithHostFxr/src/NativeHost/inc.vs/nethost.h",
            "error": "ERROR: Too many projects found. A single project or solution must exist in this directory or one of the parent directories."
        }
    ]
}
```

You can use the build output logs from the previous run to find the errors you put in snippets file. The summary tab of the run has the output file at the end of the page:

image

In the file you can find the offending file and error message to put in the snippets file:
```
  {
    "ProjectFile": "",
    "InputFile": "samples/snippets/core/tutorials/netcore-hosting/csharp/HostWithHostFxr/src/NativeHost/inc.vs/nethost.h",
    "ExitCode": 2,
    "BuildOutput": "ERROR: Too many projects found. A single project or solution must exist in this directory or one of the parent directories.",
    "Settings": null,
    "Errors": [
      {
        "Line": "ERROR: Too many projects found. A single project or solution must exist in this directory or one of the parent directories.",
        "Error": "ERROR: Too many projects found. A single project or solution must exist in this directory or one of the parent directories."
      }
    ],
    "ErrorCount": 1
  },
```

`InputFile` and `Error` are the two fields you need to put in the snippets file.

The snippets file needs to be created at the level of the `InputFile` or in any parent directory.

**Review by IEvangelist — APPROVED** [review]

**Comment by BillWagner** [comment]
Hi @nschonni 

This has grown stale. None of us have done what's needed to move it forward. It's got a lot of conflicts now.

I think it might be best to close this, and start with fresh PRs using cSpell on smaller sets of files.

What do you think?

**Comment by nschonni** [comment]
@BillWagner I can try and rebase this again, but I don't plan to redo all of this for a new PR(s) or address the unrelated build failures that exist today

**Comment by BillWagner** [comment]
> @BillWagner I can try and rebase this again, but I don't plan to redo all of this for a new PR(s) or address the unrelated build failures that exist today

If the rebase is easy and doesn't take much time, let's do it. I'll use the admin switches to merge. I noticed that all the text changes seem to be in comments, so they won't break anything that works.

We keep adding more projects to the CI build, so hopefully there are fewer issues this time. I agree that it's not something I'd expect community contributors to add. Especially at this scale.

**Comment by nschonni** [comment]
@BillWagner rebased. There is still a handful of missing projects, but feel free if you want to push fixes to this branch

**Pull request merged**
