### PR TITLE
CC67142: Adding final ';' to the GetContactInformation method

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @rpetrusha ,
This proposed file change comes from https://github.com/dotnet/docs.ru-ru/pull/121.
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks, @v-maudel. However, the change is not correct. This is a method signature rather than a method call; implicitly, it would be followed by the method body. 

The original ru-RU version of this article incorrectly includes the semicolon after the method signature (see line 41 of the original version of the article in dotnet/docs.ru-ru#121). The author who submitted the PR removes it (see line 41 of the proposed revisied version) and doesn't add it to line 66, which corresponds to line 63 in this PR. So adding a semicolon is not something the original Russian language PR did.

I'll close this PR.

**Comment by v-maudel** [comment]
Hi @rpetrusha , 
My apologies, you are right, Actually, at looking again to the reported "error" I don't know what I was thinking when I submitted it in this way. 

Thanks and regards.

**Comment by rpetrusha** [comment]
There's no need to apologize, @v-maudel. I think we've all made similar (or worse) mistakes.

**Comment by v-maudel** [comment]
Thanks @rpetrusha .

**Pull request closed without merging**
