### PR TITLE
Couple changes to the cross-compilation doc

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
## Summary

Updated the wording a bit.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/deploying/native-aot/cross-compile.md](https://github.com/dotnet/docs/blob/c375c8002e800d09eff9bae64e9ae9f9ea6d3500/docs/core/deploying/native-aot/cross-compile.md) | [Cross-compilation](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/cross-compile?branch=pr-en-us-37635) |

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@dotnet/ilc-contrib could someone have a look?

**Review by jkotas — APPROVED** [review]
Thanks

**Review by BillWagner — APPROVED** [review]
This LGTM.

I'll :shipit: now.

**Comment by BillWagner** [comment]
closing and reopening for a fresh build. (The build warning isn't part of this PR, and has already been addressed)

**Pull request merged**
