### PR TITLE
Update GitHub Issue Classification to v 1.0.0-preview

### LINKED ISSUE #12082: Labels and Features
Can we explain somewhere what Labels and Features are? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

### LINKED ISSUE #12083: Improve readibility by replacing text with images
Select the appropriate machine learning algorithm
Classification algorithm

These sections can be improved by using images versus text currently. My hypothesis would be it would help improve readibility. The other tutorials Sentiment Analysis and Recommendation are already using this technique. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

### LINKED ISSUE #12084: TransformerChain<TLastTransformer>
Concepts introduced in this tutorial inconsistent with others. Concepts to introduce are IEstimator, ITransformer, IDV and PredictionEngine. Follow recommendation engine tutorial for reference. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

### LINKED ISSUE #12085: MapValueToKey not explained
MapValueToKey is not explained well. This section is a bit  complex to follow and understand: 

"
As we want to predict the Area GitHub label for a GitHubIssue, copy the Area column into the Label column. To do that, use the MLContext.Transforms.Conversion.MapValueToKey, which is a wrapper for the MapValueToKey transformation class. The MapValueToKey returns an EstimatorChain&lt;TLastTransformer&gt; that will effectively be a pipeline. Name this pipeline as you will then append the trainer to the EstimatorChain. Add the next line of code:
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

### PR DESCRIPTION
**Pull request by JRAlexander**
Update GitHub Issue Classification to v 1.0.0-preview

[Interal Review URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification?branch=pr-en-us-12059)

[Related Code Sample](https://github.com/dotnet/samples/pull/840)

Fixes https://github.com/dotnet/docs/issues/12082
Fixes https://github.com/dotnet/docs/issues/12083 
Fixes https://github.com/dotnet/docs/issues/12084
Fixes https://github.com/dotnet/docs/issues/12085

### CODE REVIEW

**Review by luisquintanilla — APPROVED** [review]

**Review by cjgronlund — COMMENTED** [review]
Please check the H3 with no subordinate content. I think it can be deleted.
image
Two-class classification is the wrong image here. This could be removed:
image

**Comment by JRAlexander** [comment]
@CJGrondlun - Do you explicitly approve this PR for BUILD ask mode?

**Comment by JRAlexander** [comment]
@cjgronlund  - Do you explicitly approve this PR for BUILD ask mode?

**Comment by cjgronlund** [comment]
Approve

**Review by cjgronlund — APPROVED** [review]

**Pull request merged**
