### PR TITLE
Update preprocessor-warning.md

### PR DESCRIPTION
**Pull request by ghost**
Link for warning CS1030.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks, @johnnyagerard, for adding a link to CS1030. The sentence still doesn't read very well. There are two alternatives:
- add back "a" before the link: "...generate a CS1030 level one compiler warning..."
- "...generate a \[level one compiler warning\](../../misc/cs1030.md)…"

**Comment by johnnyagerard** [comment]
@rpetrusha All right, I choosed your first option.

**Comment by rpetrusha** [comment]
Thanks, @johnnyagerard. In reviewing #7091, I realized the first option was the best, so I was just about to edit my comment.

**Review by rpetrusha — APPROVED** [review]
Thanks for making the additional change, @johnnyagerard. We'll merge your PR once the internal build completes.

**Pull request merged**
