### PR TITLE
Improved page title

### LINKED ISSUE #7941: Misleading page title?
As described in the first paragraph, the article describes the prerequisites for .NET Core development. So the title should be "Prerequisites for .NET Core development on Windows".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore21)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by rparakhiya**
Improved page title to reduce ambiguity. Fixes #7941

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
I still feel that changing the title is not the right thing for this page. The supported Windows versions and dependencies like C++ are not specific to development time. I think we can make changes to that page to make the distinction clearer but I don't think we should touch the title.

**Comment by rumitparakhiya** [comment]
How about adding a note under the section [Prerequisites with Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore21#prerequisites-with-visual-studio-2017), which states something like?:
> Visual studio is a preferred development environment for .Net and is not required for running .net based applications.

**Comment by mairaw** [comment]
Let me think on this one. I don't think we should say that Visual Studio is preferred.

**Comment by Thraka** [comment]
@mairaw I agree. Saying Visual Studio is preferred is saying that others are not, which is untrue.

**Comment by mairaw** [comment]
Thanks for trying to tackling that issue @rparakhiya. I've made some changes in PR #9419  to update for 2.2 while at the same time trying to fix this issue. Please take a look.
For that reason, I'm closing this PR.

**Pull request closed without merging**
