### PR TITLE
Update seedwork-domain-model-base-classes-interfaces.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Minor edit from jumping straight to this topic. @BillWagner  please review.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
@Rick-Anderson, would you mind making two other corrections?
- considered --> be considered
- "introduced" shouldn't be the hyperlink text for the www.artima.com; the hyperlink text should be Michael Feathers

**Comment by Rick-Anderson** [comment]
@rpetrusha  killed off another RO sentence.

**Comment by rpetrusha** [comment]
LGTM. This is OK to merge.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
@Rick-Anderson, the build has finished and this looks good. I'll merge now.

**Pull request merged**
