### PR TITLE
Move include files from internal folders to ~/includes.

### LINKED ISSUE #2179: Move include files from internal folders to the master\includes folder.
We need to remove include files from internal (primarily in C# and VB) and move them all here: https://github.com/dotnet/docs/tree/master/includes
 
If the file already exist in the main includes folder, we will keep the original file and delete the other instead of moving it.

If a file is moved, we will do the following:

1. Remove the metadata inside that looks like this:

translation.priority.ht: 
  - "cs-cz"
  - "de-de"
  - "es-es"
  - "fr-fr"
  - "it-it"
  - "ja-jp"
  - "ko-kr"
  - "pl-pl"
  - "pt-br"
  - "ru-ru"
  - "tr-tr"
  - "zh-cn"
  - "zh-tw"

2.  Fix all links to the file, using the format ~/includes/tokenname.md
 
Suggest reviewers
@mairaw

### PR DESCRIPTION
**Pull request by tompratt-AQ**
# Title
Move include files from internal folders to ~/includes folder.

## Summary
This is the first commit to this PR which will move all include files from internal folders to the master ~/includes folder. It will be done in the following way: 

1. If the include file does not exist in ~/includes, then it will be moved there and all links to it will be changed accordingly. 
2. If an include file with the same token already exists in ~/includes, then all references to the internal link will be changed and the internal file will be deleted.

This commit moves all of the files from:
docs/includes
docs/csharp/includes

## Issue
#2179  (This does not yet fix the issue. There will be a second PR to move a few remaining files)

## Suggested Reviewers
@mairaw

### CODE REVIEW

**Comment by GuardRex** [comment]
Thumbs way UP :+1: for `~/` linking! :heart:

**Comment by mairaw** [comment]
Build has failed with an exception (checked on the OPS portal since this was still processing). Let's try again.

**Comment by mairaw** [comment]
Awesome, it worked! Feel free to proceed with the rest of the changes, @tompratt-AQ!

**Comment by tompratt-AQ** [comment]
Great! Thanks for closing and re-opening the PR last night to get it unstuck.

**Comment by tompratt-AQ** [comment]
Commit 2 - Moves the include files from these internal folders to ~/includes.:
		docs/csharp/getting-started/includes
		docs/csharp/language-reference/compiler-messages/includes
		docs/csharp/language-reference/compiler-options/includes
		docs/csharp/language-reference/keywords/includes
		docs/csharp/language-reference/preprocessor-directives/includes

**Comment by mairaw** [comment]
Take a look at the merge conflict @tompratt-AQ

**Comment by tompratt-AQ** [comment]
Commit 3 - 
Fixes merge conflict in:
     docs/visual-basic/programming-guide/language-features/objects-and-classes/index.md 
Moves include files from this internal folder to ~/includes:   
     docs/csharp/misc/includes

**Comment by tompratt-AQ** [comment]
I tried to resolve it here using the Resolve conflicts button, but it won't let me save my changes. So, I made another commit including the conflicting file that should have the right changes.

**Comment by tompratt-AQ** [comment]
Commit 4 -
Updated file to really fix merge conflict (didn't happen in Commit 3):
     docs/visual-basic/programming-guide/language-features/objects-and-classes/index.md
Moved include files from this internal folder to ~/includes:
     docs/csharp/programming-guide/classes-and-structs/includes

**Comment by tompratt-AQ** [comment]
Commit 5 -
Updated file to really, really fix merge conflict (All includes are fixed in this file, they weren't before):
		docs/visual-basic/programming-guide/language-features/objects-and-classes/index.md
Moved include files from this internal folder to ~/includes:
		docs/csharp/programming-guide/concepts/linq/includes
		docs/csharp/programming-guide/concepts/threading/includes
		docs/csharp/programming-guide/events/includes

**Comment by tompratt-AQ** [comment]
Commit 6 (The final commit for this PR unless there are errors to fix)

Moved include files from this internal folder to ~/includes:
		docs/csharp/programming-guide/interop/includes
		docs/csharp/programming-guide/types/includes
		docs/visualbasic/developing-apps/customizing-extending-my/includes
		docs/visualbasic/developing-apps/includes
		docs/visualbasic/developing-apps/printing/includes
		docs/visualbasic/language-reference/objects/includes
		docs/visualbasic/misc/includes
		docs/visualbasic/reference/command-line-compiler/includes

**Comment by mairaw** [comment]
@tompratt-AQ should I remove the WIP label? Is this ready for review?

**Comment by tompratt-AQ** [comment]
@mairaw Yes, please remove the WIP label. This is ready for review. Because of an earlier merge conflict that I fixed, and other issues, Commit 6 (that I listed above) may not have been included in this PR. Once this PR goes through, I will confirm that and do a separate PR for the ~40 files in that group.

**Comment by tompratt-AQ** [comment]
@mairaw When you get a chance, please restart this one. Thanks.

**Comment by tompratt-AQ** [comment]
@mairaw This is ready for review. Thanks.

**Comment by tompratt-AQ** [comment]
@mairaw I don't have write access so I can't easily resolve this merge conflict. Is it possible for you or someone else to resolve this one file? 
My PR was attempting to move it from:
docs/includes/net-standard-table.md  -->  ~/includes/net-standard-table.md
And update 2 references to it in 2 files (docs/core/tutorials/libraries.md and docs/standard/library.md)
If that can't be done, then just undo any change to the file. I want to submit a second PR anyway to clean up a few more changes to Fix Issue #2179.  For some reason (PR too big, build issues) my last commit didn't get pushed and I can't easily reconcile it on my end.

**Comment by tompratt-AQ** [comment]
@mairaw Thanks so much for clearing up the merge conflict for me. This check does seem to be taking a long time though, I think you started it yesterday around 5pm. I wonder if it is stuck or just slow due to the number of changes?

**Comment by rpetrusha** [comment]
@tompratt-AQ, the build report shows that it partially succeeded and finished at 6:02 yesterday evening. I'll close and reopen.

**Comment by tompratt-AQ** [comment]
Thanks for restarting this Ron, glad to see it passed. It was reviewed by Maira previously and ok'd for merge.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
@tompratt-AQ, I've merged it.

**Pull request merged**
