### PR TITLE
Linux install instructions update due to 3.1 EOL

### PR DESCRIPTION
**Pull request by ayakael**
* Removes .NET 3.1 due to EOL
* Updates Alpine Linux

@adegeo

### CODE REVIEW

**Comment by adegeo** [comment]
Tables were changed to be simplified via recommendation of the product team. But to their credit, the original tables were designed back when we were documenting more of the unsupported distros too, but now that we just remove the distros when they're no longer supported, it doesn't make sense to have complex tables with ✔️ and ❌

**Review by adegeo — CHANGES_REQUESTED** [review]
Tables were changed to be simplified via recommendation of the product team. But to their credit, the original tables were designed back when we were documenting more of the unsupported distros too, but now that we just remove the distros when they're no longer supported, it doesn't make sense to have complex tables with ✔️ and ❌

So I would revert those changes 😁

**Comment by svick** [comment]
The Linux install instructions pages also include the `includes/versions-not-supported.md` file. I think that should also be updated.

**Comment by ayakael** [comment]
> The Linux install instructions pages also include the `includes/versions-not-supported.md` file. I think that should also be updated.

Many thanks, done :)

**Comment by ayakael** [comment]
> Tables were changed to be simplified via recommendation of the product team. But to their credit, the original tables were designed back when we were documenting more of the unsupported distros too, but now that we just remove the distros when they're no longer supported, it doesn't make sense to have complex tables with heavy_check_mark and x
> 
> So I would revert those changes grin

Reverted those changes, once tests passes I consider this ready.

**Review by adegeo — APPROVED** [review]
Thanks!

**Pull request merged**
