### PR TITLE
Fix multiple WCF binding config element docs

### PR DESCRIPTION
**Pull request by mconnew**
## Summary
For basicHttpContextBinding, mexHttpBinding, mexHttpsBinding, mexNamedPipeBinding, mexTcpBinding, netHttpBinding, netHttpsBinding, and udpBinding, fixed at least one of the following items:
* Removed description of namespace from attribute description table.
* Fixed description of the name attribute as it was confusing Binding.Name with StandardBindingElement.Name
* Removed envelopeVersion attribute and description

Similar issue to #15925

### CODE REVIEW

**Comment by mconnew** [comment]
I've just found more instances of this. I'm going to update this PR with the other fixes once I've done them.

**Comment by mconnew** [comment]
I've updated all the similar problems across all the binding config docs so this is ready for review.

**Review by mairaw — APPROVED** [review]
LGTM. Thanks @mconnew. Do we need to wait for @HongGit's review or can I merge this?

**Comment by mconnew** [comment]
@mairaw, you can merge this.

**Pull request merged**
