### PR TITLE
Doc on Pipelines types

### LINKED ISSUE #7516: New doc: Pipelines
Moved from https://github.com/aspnet/Docs/issues/5521

See https://github.com/aspnet/KestrelHttpServer/issues/1980 and [Bedrock update](https://github.com/aspnet/KestrelHttpServer/issues/1980#issuecomment-377123245)
Document the lower layers. 
The transports

@KPixel wrote

The outline/TOC could be as in the [tutorial](https://github.com/KPixel/Prototypes/tree/master/Pipelines):

1. Link to learn about the primitives Span and Memory
2. Introduction to the Pipe class
3. Simple Pipe sample
4. The Receive() loop
5. Pipes in ASP.NET Core 2.1
6. Introducing IDuplexPipe
7. Creating a pair of DuplexPipes
8. Duplex Connection

Considering how advanced certains sections can get, I don't know if we should split this into many articles (now), or leave it as-is (and refactor later as the extra advanced topics get covered).

More fundamentally, I think this doc belongs in the .NET doc. Probably next to the doc for Span/Memory 

Here is the issue tracking the doc for Span: https://github.com/dotnet/docs/issues/4400

### PR DESCRIPTION
**Pull request by KPixel**
## Pipelines types

This is a new page on Pipelines.

[Internal review URL Memory- and span-related types](https://review.docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/index?branch=pr-en-us-11347)
[Internal review URL Pipelines types](https://review.docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/pipelines?branch=pr-en-us-11347)

Fixes #7516

## Notes

1. I've included the HTML/JS that I used to generate the diagrams. I'm not sure what the policy is for that, but I think it would be nice to keep them in case we need to update the diagrams in the future (or create new ones).
2. The Pipelines API has many advanced features that are not discussed on this page (see aspnet/Docs#5521). I think it would make this page too heavy if we tried to address them.
3. What should I put in "#ms.author"?

### CODE REVIEW

**Comment by mairaw** [comment]
@Rick-Anderson can you help review this one?

**Comment by Rick-Anderson** [comment]
@mairaw  I created https://github.com/aspnet/AspNetCore.Docs/issues/11823 so the PU will review this on their next schedule hack-a-doc.

**Comment by mairaw** [comment]
Sounds good. I'll wait for their comments until I start reviewing these and applying some of our guidelines.

For example, the right identifier for C# code is csharp, sample code should be hosted in https://github.com/dotnet/samples, etc. 

@KPixel one thing is that our TOC format changed from .md to yml so you now have some merge conflicts.

**Comment by KPixel** [comment]
@mairaw I will update the TOC when needed.

Regarding moving sample codes to that separated repo, may I know what the rational is? It seems like a lot more work...

**Comment by mairaw** [comment]
The goal is to have CI running on all samples in that repo so we know when code breaks when a new version is released, etc. We're not there yet. The checks done here are all just for content, not for code.
I understand it introduces a bit of complexity.

**Comment by KPixel** [comment]
That's fine for samples, but snippets are often written with assumptions (like no "using namespace") that make them impossible to compile...

**Comment by mairaw** [comment]
little snippets are fine to be inside the content

**Comment by KPixel** [comment]
Ok, I will wait for the reviews to work on all that.

**Comment by davidfowl** [comment]
Hey @KPixel I'd like to take over this one. I started writing a detailed usage doc for pipelines that will supersede this one. Can we close this one for now. The plan I have is to:

- Document System.Buffers and System.IO.Pipelines as guides in the .NET docs
- Document the new Bedrock APIs and how to consume them in ASP.NET Core

**Comment by KPixel** [comment]
Hi @davidfowl Glad to see that you are making progress here.

If you are writing a new doc, can you take advantage of [the illustration that I put together](https://github.com/KPixel/dotnet-docs/blob/master/docs/standard/memory-and-spans/media/pipelines/duplex-connection.png)?
The [source code](https://github.com/KPixel/dotnet-docs/tree/master/docs/standard/memory-and-spans/media/pipelines/source) to change it is in the same folder (It is generated with SVG in Javascript).

**Comment by davidfowl** [comment]
@KPixel sure though that more fits the bedrock picture. Maybe we can do a modified version for IDuplexPipe as well? I plan to open a docs PR soon. I'm trying to get the content finished.

**Comment by KPixel** [comment]
Ok, feel free to let me know if I can do anything to help.

**Comment by davidfowl** [comment]
Feel free to provide any initial feedback on https://github.com/davidfowl/DocsStaging

**Comment by mairaw** [comment]
I'll close this one then @KPixel. We surely appreciate you taking the time to get this started!

**Pull request closed without merging**
