### PR TITLE
Fix over-localization of VB keywords

### LINKED ISSUE #19033: Keywords that should not be localized
This article contains keywords that should not be localized and some of those are being over-localized. It would be great if those keywords can be blocked from localization by using either in-line code, or [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2d0d24-a228-ab33-1c62-3b0a701ff318
* Version Independent ID: 9ef3c275-ce7b-808b-8acd-3d394296d897
* Content: [Keywords - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/keywords/)
* Content Source: [docs/visual-basic/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/keywords/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #19033

cc @JasonCard to review the correctness of the PR.

### CODE REVIEW

**Review by JasonCard — COMMENTED** [review]
Thank you, I've reviewed the list of "Reserved Keywords" and edited. 
The list of "Unreserved Keywords" should also be blocked from localization correct?

**Comment by Youssef1313** [comment]
> The list of "Unreserved Keywords" should also be blocked from localization correct?

Yes I forgot them. I've added them now.

**Review by JasonCard — APPROVED** [review]
Looks good to me, thank you!

**Comment by adegeo** [comment]
@JasonCard will this be confusing for the loc? The `In` keyword could also be used in a sentence:

`Use the In keyword to check if the specified item is in the list`

**Comment by JasonCard** [comment]
@adegeo Thank you for checking! Actually, I just realized that a lot of these keywords are common words like "In/Is/If/For/On" that could be used at beginning of sentence. Although, non-loc metadata is case sensitive, it's risky in that all instances of the same word would be blocked from translation in this article. So for example, in the sentence "For more information, ...", translator would not be able to translate "For", which would be bad, so we should not use no-loc metadata for this. So instead I would recommend to use inline code, like 'For' and 'In', for all instances of keywords that should not be translated in this article. This would also make it more clear for the reader and make sure those terms are not localized. 
cc @Youssef1313

**Comment by JasonCard** [comment]
@Youssef1313 Thank you for the fix to use inline code, looks good!

**Review by adegeo — APPROVED** [review]

**Pull request merged**
