### PR TITLE
add redirection for missing error

### PR DESCRIPTION
**Pull request by BillWagner**
See #24546 for background.

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
We probably need to rename `cs2003.md` in this PR to see the effect of the validation when #24546 is merged.

**Comment by BillWagner** [comment]
> We probably need to rename cs2003.md in this PR to see the effect of the validation when #24546 is merged.

Now that I see your latest commit, I'm wondering if we need this PR at all. Did I miss something?

I'm now seeing that you renamed "cs0003.md" to test, and then renamed it back. That would make this unnecessary.

**Comment by Youssef1313** [comment]
@BillWagner In case you want to double check that the validation works, I think we can use this PR as a text after #24546 is merged.

**Comment by BillWagner** [comment]
@Youssef1313 @gewarren 

This PR ran a few tests on the new workflow. It works well!  

Closing this PR.

**Pull request closed without merging**
