### PR TITLE
C57267: Adding spaces before code to avoid broken display

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @JRAlexander ,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: add to spaces after end of line so that code snippet can be seen.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by Thraka** [comment]
@v-maudel 

I think the better fix is to insert a blank line between the two lines. A double space at the end of a line is a specific markdown format to indicate that the line should be continued with a soft break on the next line instead of a paragraph. 

In this case, the author is trying to insert a code example, which is a block element. A blank line would be best.

**Review by Thraka — CHANGES_REQUESTED** [review]
@v-maudel 

I think the better fix is to insert a blank line between the two lines. A double space at the end of a line is a specific markdown format to indicate that the line should be continued with a soft break on the next line instead of a paragraph. 

In this case, the author is trying to insert a code example, which is a block element. A blank line would be best.

**Comment by v-maudel** [comment]
Thanks so much @Thraka ,
I've added a break-line between the title and the code now.

@JRAlexander

**Review by Thraka — APPROVED** [review]

**Comment by v-maudel** [comment]
Thanks @Thraka

**Pull request merged**
