### PR TITLE
fix last zz links

### LINKED ISSUE #3682: Fix xref links that were commented out during migration
During migration from MSDN to docs.microsoft.com, some of the content had their xref link commented out and changed with text inside inline code.

We should remove those from the docs:
https://github.com/dotnet/docs/search?q=%21--zz&type=Code

Search currently shows 88 files with that issue. In some cases though, we won't be able to fix the issue until the API is onboarded to docs. e.g. System.IO.WindowsRuntimeStreamExtensions is a UWP API that is not on docs yet. 

For people interested in helping with this task, we'd break it down into smaller tasks (like 5-10 links per PR).

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #3682 

There are two files left that I need to follow up with the PU team to identify proper replacement

Hide whitespace changes for easier diff

### CODE REVIEW

**Comment by mairaw** [comment]
The two other files that still have zz links are:

- [ ] https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization
@ViktorHofer those xref links (there are 4 commented out) don't resolve even for newer versions of .NET Core. Are we missing assemblies in our reflection or are those private/internal classes?

- [ ] https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/messaging-activities
@Lxiamail @zhenlan I couldn't figure out a good replacement for System.ServiceModel.Activities.CorrelationHandle.CallbackHandleName used in that article. Can you help me figure out how I could fix that article?

Thanks!

**Comment by ViktorHofer** [comment]
`CryptoSignedXmlRecursionException` should resolve fine now but the others are private/internals ones that are not exposed.

**Comment by mairaw** [comment]
And if it doesn't, are we missing assemblies here for .NET Core? /cc @safern

**Comment by safern** [comment]
> And if it doesn't, are we missing assemblies here for .NET Core? /cc @safern

@mairaw we could sync up offline and compare the expected list of assemblies, vs what you got, if that helps.

**Comment by Lxiamail** [comment]
@mairaw Can you give me a bit more context what "replacement for System.ServiceModel.Activities.CorrelationHandle.CallbackHandleName" we try to look for? What's the goal of updating this doc?

**Comment by Lxiamail** [comment]
@mairaw I would change "initialize a correlation using the special key value of System.ServiceModel.Activities.CorrelationHandle.CallbackHandleName" into "initialize a correlation using System.ServiceModel.Activities.CorrelationHandle"

**Comment by mairaw** [comment]
Thanks @Lxiamail! I'll resolve the merge conflicts and add your suggestion.

**Review by rpetrusha — APPROVED** [review]
Congratulations, @mairaw! Great work. This is ready to merge when you're ready.

**Pull request merged**
