### PR TITLE
Fix typo in Markdown formatting

### PR DESCRIPTION
**Pull request by p13i**

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
Thanks for correcting the formatting, @p13i. We'll merge you PR as soon as there's a successful build.

**Comment by rpetrusha** [comment]
Build from PR does not appear in OPS portal. Closing and reopening to begin new build.

**Comment by mairaw** [comment]
Build was not on the portal. Kicked off a new build.

**Comment by mairaw** [comment]
Thank you @p13i. I'll include this change in our next wave of updates and should be live later today or tomorrow.

**Pull request merged**
