### PR TITLE
Add third category and WCF Client area

### PR DESCRIPTION
**Pull request by gewarren**
- Adds behavioral change category (see https://github.com/dotnet/docs/issues/25257#issuecomment-887095743)
- Adds WCF Client as a feature area choice

### CODE REVIEW

**Comment by PriyaPurkayastha** [comment]
Looks good to me. cc @marklio since behavioral change is added as a classification type and definitions have been slightly tweaked. cc @HongGit for area WCF Client addition.

**Review by PriyaPurkayastha — APPROVED** [review]

**Comment by PriyaPurkayastha** [comment]
cc @mconnew

**Review by mconnew — APPROVED** [review]

**Review by RussKie — COMMENTED** [review]
👍 
Should we provide a link to https://learn.microsoft.com/dotnet/core/compatibility/categories in the description? E.g., as _[How do I decide?](https://learn.microsoft.com/dotnet/core/compatibility/categories)_.

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

You can :shipit: when ready.

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
