### PR TITLE
Include EventArgs in serialization support matrix

### PR DESCRIPTION
**Pull request by ViktorHofer**
Relates to https://github.com/dotnet/corefx/issues/25930

### CODE REVIEW

**Comment by ViktorHofer** [comment]
do not merge...

.NET Core version number isn't finalized yet.

**Comment by JRAlexander** [comment]
Added WIP to ensure no merge.

**Comment by danmosemsft** [comment]
It would be 2.0.6 and 2.0.5 is in the bag ready to go.

**Comment by mairaw** [comment]
So is this good to go now @ViktorHofer?

**Comment by ViktorHofer** [comment]
yes, should be fine now.

**Review by mairaw — APPROVED** [review]
LGTM

**Comment by mairaw** [comment]
@ViktorHofer I'll merge this now but I've noticed that certain APIs are not linked to docs. Are they missing and should be added? e.g. System.Collections.Generic.NonRandomizedStringEqualityComparer

/CC @weshaggard

**Comment by ViktorHofer** [comment]
Those types are expected to not be discoverable. One of your colleagues advised me in a previous PR to surround them with a code formatting block. Specifically the one you mentioned is internal in coreclr.

**Comment by mairaw** [comment]
Ah! Makes sense then @ViktorHofer.

**Pull request merged**
