### PR TITLE
fix: MD030/list-marker-space (docs/framework)

### PR DESCRIPTION
**Pull request by nschonni**
Spaces after list markers for unordered lists
Find: `^( *)\-   `
Replace: `$1- `
Filter: *.md

### CODE REVIEW

**Comment by BillWagner** [comment]
I looked at the "hide whitespace" diff, and overall this looks fine.

There's now merge conflicts that would need to be resolved before merging.

Also, this is a very large PR. If it's not too much trouble, breaking it up would be nice. (We'll merge as is, once the conflicts are addressed, if splitting it will be time consuming. I've already given it a good review.)

**Comment by nschonni** [comment]
@BillWagner I just did a quick rebase to get rid of the conflicts. I can try and split out the changes further by subfolder if prefered though

**Comment by BillWagner** [comment]
Thanks @nschonni 

I'll merge this as is. I did look through it this morning. You've done the work, and I've done the review. Let's not make extra work. 

Thanks for all the help and all the work.

**Comment by nschonni** [comment]
No problem either way, but I won't have a chance to split it for a few hours if that's what you'd prefer

**Review by BillWagner — APPROVED** [review]
I checked the review site, looked at the "hide whitespace" diff, and a spot check of other diffs.

It's ready to :shipit:

**Comment by BillWagner** [comment]
@nschonni Our messages crossed in the GitHub ether. It's all set.

**Pull request merged**
