### PR TITLE
Give developers a reason to switch

### PR DESCRIPTION
**Pull request by pbachmann**
"open-source", "cross-platform" and "interoperable" are basic necessities for any programming language so I have demoted them to the second paragraph.
"Succinct" may be accurate when one considers an entire program, but is not obvious when looking at say a C# lambda vs an F# one. "Robust" is too vague and "performant" is just another basic necessity. 

"Your focus remains on your problem domain, rather than the details of programming" and "data-oriented, where code involves transforming data with functions" may be accurate but are not going to cut through to many of the developers contemplating a switch to F#.

What are the banes of non-F# programmer's lives? 1. Clutter 2. Having to write documentation and 3. Having to read documentation that may or may not accurately describe the code.

F# solves developers' biggest headaches and this should be front and centre in explaining "What is F#".

## Summary

Give developers a reason to switch

### CODE REVIEW

**Comment by KathleenDollard** [comment]
I really appreciate this feedback. We have moved to "succinct, robust, performant" language across all of our communication, so I do not think we want to drop that language. However, I think your points are good and want to think and chat to @dsyme about this super important handful of paragraphs. Your title on this is good - we need to give another look at this.

Let's leave this open so we don't let this drop, and we may suggest text that combines these thoughts.

**Comment by pbachmann** [comment]
Thanks @KathleenDollard, 

I was well aware of the entrenched nature of the succinct/robust/performant paradigm and that it was unlikely to be tossed aside quickly, so am pleased that you have given my comments consideration.
The standard question given any budding entrepreneur may apply:

You're in an elevator and a manager of a software project complains to you about his team's inability to finish the job.
You say, "Change to F#".
He says, "Yeah, how will that help?".
You say... ?

"Much less clutter so programmers can see what they're doing" may be an answer. "The code essentially documents itself" may be an answer.

Is "*It's performant*" an answer? (btw. I thought it 'performant' meant speedy until I looked it up this morning and found it meant 'functioning well or as expected'.)

I look forward to reading @dsyme's deliberations.

**Comment by dsyme** [comment]
Useful ideas.  If we incorporate "universal" (which I quite like) then for the immediate text on the page, I suggest maybe this:

> F# is a universal programming language for writing succinct, robust and performant code.
> 
> F# allows you to write uncluttered, self-documenting code, where your focus remains on your problem domain, rather than the details of programming.
> 
> It does this without compromising on speed and compatibility - it is open-source, cross-platform and interoperable.

**Comment by pbachmann** [comment]
I like the hybrid response by @dsyme.

Perhaps I was too hard on "your focus remains on your problem domain, rather than the details of programming". Maybe the juxtaposition of that phrase with "uncluttered" consolidates both ideas in the minds of the target audience, inviting their minds to flit between the "how" and the "why":

* What does uncluttering do? Allows you to focus on your problem domain.
* How does F# help you focus on your problem domain? By allowing you to write uncluttered code.

Of course there are programmers who take great pride and pleasure in being mired "the details of programming", but they are a lost cause anyway.

**Comment by pbachmann** [comment]
I created a new commit based on @dsyme's comments. I don't know whether there a button I need to press now to pass it back to the reviewers.

**Comment by BillWagner** [comment]
Thanks @pbachmann 

I like this version. Once @KathleenDollard or @dsyme weigh in on the new text, I'll :shipit:

**Review by dsyme — APPROVED** [review]

**Pull request merged**
