### PR TITLE
C37842: Escaping asterisk that must be displayed as text

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @wiwagn,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: There are extra asterisks not being rendered properly, avoiding bold and italic type to be done. 
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks, @v-maudel, for attempting to correct the formatting in this article. The original text, though, was poorly formatted, and as a result, your fixes didn't address the formatting issue. I've formatted the text to reflect what I think the formatting should have been. (We'll see whether that was successful when the build completes.)

**Comment by rpetrusha** [comment]
//cc @CESARDELATORRE

**Review by rpetrusha — APPROVED** [review]
The build looks good now, and I think that this should address the localization issues, @v-maudel. So I'll merge.

**Comment by v-maudel** [comment]
Thanks so much @rpetrusha I didn't mind my changes were so bad!.

**Pull request merged**
