### PR TITLE
Update Live with current Master

### PR DESCRIPTION
**Pull request by rpetrusha**

### CODE REVIEW

**Comment by mairaw** [comment]
This has warnings now.

**Comment by BillWagner** [comment]
I tracked down the warning. This now takes a dependency on #7833 

It's because we merged #7907 

@JamesNK Is #7833 ready for a final review and merging?

**Comment by pkulikov** [comment]
@BillWagner #8028 provides a temporary fix

**Comment by JamesNK** [comment]
> @JamesNK Is #7833 ready for a final review and merging?

Yes

**Pull request merged**
