### PR TITLE
Update object-oriented-programming.md

### LINKED ISSUE #23543: Definition of Abstraction and Encapsulation are incorrect.
I'm sure that "Encapsulation means that a group of related properties, methods, and other members are treated as a single unit or object." But It's confusing to define that "Encapsulation means hiding the unnecessary details from type consumers." Because "hiding the unnecessary details from type consumers" is right for abstraction also. The difference is Encapsulation hides details from accessing, Abstraction hides details for unnecessaries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by davidbcoulson**
The definitions for Abstraction and Excapuslation were reversed.

Fixes #23543

edit by @billwagner: Add related issue being fixed.

### CODE REVIEW

**Comment by davidbcoulson** [comment]
Notice this was wrong wanted to update it.  Thank you

**Comment by BillWagner** [comment]
@davidbcoulson 

We've had a number of concerns on these definitions.  See #23543 to follow the discussion.

The correct fix is not to switch these, but to rewrite both more clearly to avoid any confusion.

Do you want to take that on, or should I close this PR? I don't want to place extra demands on your time, but your fix will only drive more confusion.

**Comment by davidbcoulson** [comment]
Morning Dotnet/Docs

just added a comment to the discussion.  They need to be switched.  All the
blogs and forums use these as a reference. Most are the same sentence. I
dont think we need more work on this. we just need to switch them back.

best,

David

**Review by davidbcoulson — COMMENTED** [review]
Thanks Bill, I feel this is a great definition. Happy to be apart of it.

**Review by BillWagner — APPROVED** [review]
Thanks for the updates and the discussion @davidbcoulson 

I think this is a huge improvement, and I'll :shipit: now.

You should see the changes on the live site in the next day or two, on our regular publishing cycle.

**Pull request merged**
