### PR TITLE
add missing space

### PR DESCRIPTION
**Pull request by mairaw**
There are hundreds of topics that use these two include files. 

However, not always the text following them has a space in between. Trying to fix the issue of concatenated sentences by adding a space to the include file itself.

For example:
https://docs.microsoft.com/en-us/dotnet/framework/wcf/configuring-bindings-for-wcf-services#servicemodel-elements
"For more information aboutdefault endpoints, "

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/ws2007federationhttpbinding#remarks
"For more information, see\<wsFederationHttpBinding>."

Example of internal review URLs:
[Topic 1](https://review.docs.microsoft.com/en-us/dotnet/framework/wcf/configuring-bindings-for-wcf-services?branch=pr-en-us-3121#servicemodel-elements)
[Topic 2](https://review.docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/httpdigest-element?branch=pr-en-us-3121#remarks)

### CODE REVIEW

**Comment by mairaw** [comment]
Adding the space in the include file didn't work

**Comment by rpetrusha** [comment]
@mairaw, were dependencies actually rebuilt? It looks as if the two topics whose links you've provided were not.

**Comment by mairaw** [comment]
@rpetrusha nope, that's why I put the WIP label. Let me see if closing and reopening the PR would trigger a full build. There could be logic in the build trimming includes too. So in this case, we'd have actually change where they're used, It's easy to find them with regular expressions. I was just hoping I could make the simpler fix. 😄

**Review by JRAlexander — DISMISSED** [review]
LGTM.

**Comment by mairaw** [comment]
resolved merge conflicts

**Review by BillWagner — APPROVED** [review]
I looked at a number of the referenced pages on the published site and the PR review site. In all the locations where I looked, this passed.

:shipit: when you are ready.

**Pull request merged**
