### PR TITLE
Fix XAML TODO snippets in \xml.

### PR DESCRIPTION
**Pull request by tompratt-AQ**
# Title
Fix XAML TODO snippets in \xml.

## Summary
This is the second batch of fixes for missing code snippets in the \xml branch as part of the
[TODO: Review snippet reference ](https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22TODO%3A+review+snippet+reference%22&type=)Task.

These are all references to xaml snippets (with 3 .config snippets, and one .js snippet). Most of the fixes were for incomplete or wrong spelling of directory names, and deleting links to snippets in the \XAML branch which don't exist and would be duplicates of snippets in the \csharp branch.

## Suggested Reviewers
@mairaw

### CODE REVIEW

**Comment by mairaw** [comment]
There is a merge conflict here @tompratt-AQ that I can't resolve with the UI. Can you please check?

**Comment by rpetrusha** [comment]
There's still a merge conflict in specifying-client-run-time-behavior.md, @tompratt-AQ.

**Comment by tompratt-AQ** [comment]
Apologies for the extra commits, but they would simply not Push.

**Review by rpetrusha — APPROVED** [review]
This looks good, @tompratt-AQ. I'll merge.

**Pull request merged**
