### PR TITLE
Added C# patterns reference 

### LINKED ISSUE #20584: Language reference: Patterns
As of C# 9, the pattern expressions are robust enough to justify their own page in "expressions and operators". This should cover:

- type pattern
- constant pattern
- null pattern as a useful special case of the constant pattern
- range patterns (`<`, `>`, `<=`, `>=`)
- property pattern (`when` patterns)
- `and`, `or`, and `not` pattern

In addition, the `switch` and `is` pages should link to this new page. They can cover less of the pattern syntax which likely moves to this new page.

### PR DESCRIPTION
**Pull request by pkulikov**
Fixes #20584
@BillWagner as far as I remember, you wanted to merge this without squash-merge.
After this is merged, I'll update relevant existing articles to reference the new article.

### CODE REVIEW

**Comment by pkulikov** [comment]
@BillWagner this is ready for your final review:)

**Comment by BillWagner** [comment]
Adding a link to the [internal review site](https://review.docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns?branch=pr-en-us-23623)

**Review by BillWagner — APPROVED** [review]
This is really well done. I'll :shipit: now.

Thanks for all the great work @pkulikov We *really* appreciate it!

**Comment by pkulikov** [comment]
@BillWagner what do you think of the following idea? When it goes live, could you please share it on Twitter - that way we can get some feedback from the first readers.

**Comment by pkulikov** [comment]
@BillWagner thank you very much for the reviews, guidance, and patience!

**Comment by BillWagner** [comment]
@pkulikov Will do!

**Pull request merged**
