### PR TITLE
Add how to find CUDA version

### LINKED ISSUE #24837: Update How to install GPU support in Model Builder
- Add / Update screenshots
- Review outdated content and update as necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0495cff9-97a6-68ba-504c-ec7fcbc69a9c
* Version Independent ID: 0c7c0298-37e3-f945-fee5-fc6ccd7a362d
* Content: [How to install GPU support in Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder)
* Content Source: [docs/machine-learning/how-to-guides/install-gpu-model-builder.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/install-gpu-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

### PR DESCRIPTION
**Pull request by jwood803**
Added how to find CUDA version from terminal

Fixes #24837

[Preview](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder?branch=pr-en-us-25074)

### CODE REVIEW

**Comment by jwood803** [comment]
@luisquintanilla I think this is ready for review. No changes seem needed to the main article but I thought showing how to get the current CUDA version would be helpful.

**Review by luisquintanilla — APPROVED** [review]
LGTM

**Comment by luisquintanilla** [comment]
Add to prereqs

- Install appropriate [driver](https://www.nvidia.com/drivers) for your GPU.

**Review by luisquintanilla — APPROVED** [review]
LGTM. Thanks @jwood803

**Pull request merged**
