### PR TITLE
Remove the Xamarin.Forms workload

### PR DESCRIPTION
**Pull request by bmaluijb**
I haven't seen any evidence besides this line that there is a relationship between .NET Core and Xamarin.Forms. Therefore, I doubt that this is an actual target workload for .NET Core. If I'm wrong, I'd love to know how to create a Xamarin.Forms project that uses the .NET Core runtime.

### CODE REVIEW

**Comment by mairaw** [comment]
@richlander @mhutch can one of you comment on this PR?

**Comment by mhutch** [comment]
Xamarin Forms apps on UWP use .NET Core.

**Comment by bmaluijb** [comment]
Alright, is there any documentation on that, that can be easily added so that it is clear why Xamarin.Forms is a workload for .NET Core?

**Comment by cartermp** [comment]
@bmaluijb It's more a matter of UWP itself using .NET Core under the hood.  Because Xamarin.Forms has a UWP target, it runs there as well.  The above line says this:

> Additional application models have been built on top of .NET Core to extend its functionality, such as:

I suppose if this were to say "Xamarin.Forms when targeting UWP" it would be accurate.

**Comment by bmaluijb** [comment]
@cartermp Sorry for the late reply. Bu yes, I think that "Xamarin.Forms when targeting UWP" would be accurate and less confusing than it is now.

**Comment by mairaw** [comment]
So do you wanna change the original link to that @bmaluijb? Thanks.

**Comment by bmaluijb** [comment]
I'll shoot over a new PR

**Pull request closed without merging**
