### PR TITLE
Link samples browser instead of GitHub

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by BillWagner** [comment]
@luisquintanilla This PR is getting stale. Can you give it a review and merge if appropriate?

**Comment by luisquintanilla** [comment]
Can't see preview / build output. Closing and reopening

**Review by luisquintanilla — COMMENTED** [review]
Thanks for this PR @Youssef1313 . This looks good to me, but I see some Markdown lint errors. When you get a chance, can you please look into those and when done I'll approve. Thanks!

**Comment by Youssef1313** [comment]
@luisquintanilla They are unrelated to my changes.
I have an open PR to fix those.

**Review by luisquintanilla — APPROVED** [review]

**Comment by luisquintanilla** [comment]
Thanks @Youssef1313 merging now.

**Pull request merged**
