### PR TITLE
Explicitly state default verbosity for `dotnet restore` 

### LINKED ISSUE #14952: What is the default verbosity?
It'd be good if you need to add the verbosity switch to know what the default level is so you can bump it up explicitly as needed. Happy to PR if someone tells me what it is. Will go digging if I have time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by benmccallum**
Fixes #14952

### CODE REVIEW

**Comment by benmccallum** [comment]
I thought about updating some of the other cmds. It looks like some are covered (build was, so I copied its wording) but maybe some aren't. Build seems to use a `normal` level though, so if they vary in the default I wouldn't know what to use for the missing ones unless I dug deeper.

**Review by mairaw — APPROVED** [review]
Thanks @benmccallum. I've been adding them as I've been reviewing the CLI commands to update for 3.0 because of issue #9373. So yeah, I need to investigate one by one what's the default value.

**Comment by mairaw** [comment]
And I'll double check I have the right one for build as well.

**Comment by mairaw** [comment]
minimal seems right for build:
image
image

**Pull request merged**
