### PR TITLE
Move snippets from samples repo to this repo

### PR DESCRIPTION
**Pull request by Thraka**
## Summary

Checking out what will be involved (and what may break) by moving the snippets into this repo.

- Copied the samples/snippets repo folder to this repo..
- Removed the dependent repo entry for samples.
- Modified the gitignore file to allow the samples folder.

### CODE REVIEW

**Review by tdykstra — COMMENTED** [review]
From all the "Cannot resolve '~/samples/..." messages it looks like you'll need to bring in additional folders besides snippets.

**Comment by Thraka** [comment]
I'm going through that list right now and actually moving the files to where they should be. I'll file PRs for those. This will get both repos into a better state and then I'll redo this PR. Once this PR gets a clean build, I think we can go ahead with the move.

Thoughts?

**Comment by tdykstra** [comment]
Sounds good 👍

**Comment by pkulikov** [comment]
@Thraka I see some tectonic changes are happening, that's great.

Typically, I put new code snippets into this folder:
https://github.com/dotnet/samples/tree/master/csharp/language-reference

Now, it looks to me, you want to move this folder into *this* repository in two steps:
- In **dotnet/samples** repo, move the *csharp* folder into the *snippets* folder and update references in this repo
- Move the remainings of the *snippets* folder from **dotnet/samples** repo to **dotnet/docs** repo

Is that correct understanding? If yes and this is WIP already, then I'm not submitting the changes to the docs that require adding/updating sample code until this PR is merged. After this is merged, all code samples would be in this repo and no more sync PRs (hooray!). Is that fine as well?

Do I need to know more about the new snippets structure?

**Comment by Thraka** [comment]
@pkulikov  That's pretty much the plan. We want to really design a clear separation between samples and snippets. Snippets are code fragments used solely by the documentation. Samples are fully working downloadable apps of some sort.

For "language" snippets instead of "technology" (ex: csharp lang snippets vs wpf snippets) we'll use the a root folder of **snippets/csharp**. That folder does already exist. You can just start using that right now for maximum compatibility.

**Pull request closed without merging**
