### PR TITLE
fix encoding issue

### PR DESCRIPTION
**Pull request by mairaw**
Converting text to Markdown to hopefully fix some encoding issues

See https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.5.1-4.6.1#aspnet

image

/cc @rpetrusha @conniey

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
LGTM, @mairaw. This should be good to merge when the build finishes.

**Comment by rpetrusha** [comment]
@conniey, Maira's encoding-related changes restore the file to its state before the migration, which suggests this issue will occur with every migration. Is there logic in the migration routine that changes backticks to \<code> elements? Can the backticks be left intact?

**Comment by mairaw** [comment]
Are you sure @rpetrusha? When I moved the files to the current folder, I've only changed the link in this particular file:
https://github.com/mairaw/docs/commit/7be0fae7d7e550051d8d500b2661edc19de631ac#diff-7648d80f1e846e96126e46bc444da7a4

**Comment by conniey** [comment]
I'll get back to you on that. I'm sure I can ignore all the backticks for encoding.

**Comment by rpetrusha** [comment]
@mairaw, I'm not quite sure what you mean.

**Pull request merged**
