### PR TITLE
Task75270

### PR DESCRIPTION
**Pull request by v-savila**
## Summary
toc.md conversion to yml

Fixes #I75270

### CODE REVIEW

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by BillWagner** [comment]
@v-savila This is a good start.

It appears that there are a lot of build errors in the YML files. Many seem to be related to the characters in the TOC for reference tokens.

**Comment by BillWagner** [comment]
One other question as we work on fixing the build errors. There are PRs open that add new files to the TOC. Are you picking those up as we merge them?  Should we tag you in them to make updates to this PR? (tagging my team, who also reviews and merges PRs)

/cc @mairaw @rpetrusha @Thraka  @JRAlexander

**Comment by v-savila** [comment]
@BillWagner I'll go through to fix those build errors. Yes, please tag me to update the TOCs of the new files to add.

/cc @mairaw @rpetrusha @Thraka @JRAlexander

**Comment by JRAlexander** [comment]
We'll get a list to you very soon. /cc @natke

**Comment by v-savila** [comment]
@BillWagner actually can we merge this PR now so that we can avoid merge conflicts. There was a toc.md that was updated a few hours ago so I had to do a workaround and add the latest toc.md back into my branch and will have to open new PR to do the conversion for that toc.md. Once you have your list of new files to update then you can open up a new ticket and I can get the TOC updated fo you.

/cc @mairaw @rpetrusha @Thraka @JRAlexander

**Comment by mairaw** [comment]
There are still some warnings here @v-savila. Can we fix those before merging?

**Comment by BillWagner** [comment]
@v-savila As Maira mentioned, we need to fix the build warnings before merging.  If you can update this within in the next few days, we can wait to merge other PRs that would update a TOC. 

Does that seem reasonable?

**Comment by v-savila** [comment]
@BillWagner @mairaw the warnings have been fixed except for 1 md file that has invalid cross references which is an issue that has been reported 23 days ago and not fixed yet, please see https://github.com/dotnet/docs/issues/11219.

**Comment by BillWagner** [comment]
Thanks @v-savila I will review closely after the latest build finishes.

**Review by BillWagner — APPROVED** [review]
Thanks @v-savila I browsed the review site, and this LGTM.  I'll :shipit: now.

**Comment by v-savila** [comment]
@BillWagner I've converted the toc md to yml that had a merge conflict in this PR, https://github.com/dotnet/docs/pull/11496, if you can review and merge as well. Thanks!

**Pull request merged**
