### PR TITLE
point learn F# to F# org learn page instead of docs page

### PR DESCRIPTION
**Pull request by jackfoxy**

### CODE REVIEW

**Comment by jackfoxy** [comment]
reference discussion at F#.org site https://github.com/fsharp/fsfoundation/issues/558#issuecomment-221645760

**Comment by cartermp** [comment]
LGTM.  @isaacabraham?  I think given the context of the F#.org discussion, it makes sense.

**Comment by isaacabraham** [comment]
FSharp.org should be there, but why not have both :) I only put the link to the docs as that mirrors what there is for C#.

**Comment by cartermp** [comment]
Currently there's no link to C# MSDN reference docs (at least not directly).  I think linking to both the fsharp.org site and the Visual F# Development portal is good.  To fit with the "theme" of these current docs, we could do it like this:

TOC.md:

```md
...
# [Learn F#](languages/fsharp/index.md)
## [F# Learning Resources](http://fsharp.org/learn.html)
## [F# Language Reference](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharp-language-reference)
...
``` 
With a corresponding `index.md` file in a new `languages/fsharp` folder (note the trailing `#` for docfx to render `F#` properly):

```md
# Learn F# #
* [F# Learn Resources](http://fsharp.org/learn.html)
* [F# Language Reference](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharp-language-reference)
```

Thoughts?

**Comment by jackfoxy** [comment]
@cartermp great!

**Comment by isaacabraham** [comment]
Yep, thumbs up here too. I was referring to the embedded documentation for C# in this repo which is basically language reference btw :)

**Comment by stevehoag** [comment]
The reason we did that is because the existing C# documentation on MSDN is very Windows focused, and we want to attract cross-plat developers to Core. The F# docs don't rely on Winforms or WPF the way the C# (and VB) docs do. So this is our first attempt at making C# platform-agnostic.

**Comment by isaacabraham** [comment]
@stevehoag that makes sense. Unifying the docs would be great in the longer term.

**Comment by jackfoxy** [comment]
Added F# lang index page as suggested and added link to the Visual F# Dev Portal

**Comment by richlander** [comment]
Including links to other F# sites sounds good. I'm not keen on putting links to our sites in the TOC. That seems to violate the principle of least surprise. The TOC should only be for pages on the site. I didn't realize that we've already done that for the F# link

Instead, can we focus on adding some minimal F# pages within these docs, provide a basic intro to F# and then provide links to the other resources?

**Comment by isaacabraham** [comment]
@richlander Agreed re: least surprise - are you suggesting that rather than include a direct link to e.g. MSDN, we include a link to it from within a "other resources" page?

I think something I'd personally be keen to avoid is duplication between documentation on *this* site and reference documentation within the proper MSDN docs site (particularly as both are now open source and accepting contributions). As long as it's clear that this site should contain just a few pages to give an overview of F# and maybe a couple of samples, and then the nitty gritty is elsewhere, I'm good with that.

**Comment by richlander** [comment]
> As long as it's clear that this site should contain just a few pages to give an overview of F# and maybe a couple of samples, and then the nitty gritty is elsewhere, I'm good with that.

That's exactly what I'm suggesting.

Thanks!

**Comment by cartermp** [comment]
I think this looks good.  If folks want to include some sparse documentation about what F# is, that can easily be done with this PR up.

**Comment by cartermp** [comment]
Merging.  Thanks, @jackfoxy!

**Pull request merged**
