### PR TITLE
Added overview of C# pointer related operators

### LINKED ISSUE #11116: Abridged Reference: Operators / Pointer related operators
The pointer related operators are:

- `&` (address-of)
- `*` (pointer indirection)
- `->` (pointer member access)

Pointer arithmetic with `++`, `--`, `+`, and `-` might also be included into the overview.

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

### PR DESCRIPTION
**Pull request by pkulikov**
Fixes #11116
Supported by dotnet/samples#916

@BillWagner this is ready for review.

One question-suggestion, though.

A big part of the overview is based on the following how-to's from the programming guide:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/how-to-obtain-the-value-of-a-pointer-variable
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/how-to-obtain-the-address-of-a-variable
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/how-to-access-a-member-with-a-pointer
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/how-to-access-an-array-element-with-a-pointer
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/how-to-increment-and-decrement-pointers
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/arithmetic-operations-on-pointers
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/pointer-comparison

Those how-to's contain a lot of reference material and now become the duplicates of the overview introduced by this PR. I suggest to remove all those how-to's and redirect them to the dedicated overview sections. If that's fine with you, what way do you prefer that be done: in scope of this PR or a separate one, after this one is merged?

### CODE REVIEW

**Comment by BillWagner** [comment]
closing and reopening to start a new build.

**Comment by BillWagner** [comment]
@pkulikov 

>  I suggest to remove all those how-to's and redirect them to the dedicated overview sections. If that's fine with you, what way do you prefer that be done: in scope of this PR or a separate one, after this one is merged?

I like that idea a lot. I think a separate PR will make it easier to merge. It might be wise to combine the PRs that remove all the related samples after both these are merged.

**Review by BillWagner — COMMENTED** [review]
This is really good work as well @pkulikov 

I had one suggestion to split up one sentence into three. See what you think.

I'll check the build and the review site once the latest build finishes.

**Comment by BillWagner** [comment]
The build looks good, and all the snippets are included correctly.  Let me know what you think of the one suggestion, and I'll :shipit:

**Comment by pkulikov** [comment]
@BillWagner thanks for review. I like your suggestion: it makes the text lighter. I've edited your suggestion a bit; please check the latest commit.

I'll submit a separate PR to redirect the programming guide how-to's and then a clean-up PR in the samples repo.

**Review by BillWagner — APPROVED** [review]
Thanks for all the hard work again @pkulikov 

This entire project is coming together quite nicely.  🚧 

I'll :shipit: as soon as the build completes.

**Pull request merged**
