### PR TITLE
Refresh .NET article: Determine installed versions of .NET Framework

### PR DESCRIPTION
**Pull request by dksimpson**
## Summary

Task 1385005: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1385005/

### CODE REVIEW

**Comment by rpetrusha** [comment]
@dksimpson, we've merged a PR that's created a huge number of merge commits. I'm not quite sure how to proceed, given that they're extensive and GitHub doesn't seem to do a good job of identifying them very precisely. Do you want to take a look?

**Comment by dksimpson** [comment]
@rpetrusha I've fixed the merge errors with a new commit. More commits to follow as I make additional edits.

**Comment by rpetrusha** [comment]
Thanks, @dksimpson. Let me know when your PR is ready for review.

**Comment by dksimpson** [comment]
Hi @rpetrusha, I've finished my updates - the PR is ready for your review.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
I've left a couple of minor comments, @dksimpson, but you've really done an outstanding job in improving the organization and flow of this article!

**Comment by dksimpson** [comment]
Hi @rpetrusha, thanks for your comments - I've incorporated your suggested updates. Ready for review.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
Thanks both for the revisions and the additional changes, @dksimpson. I've approved your PR, and I'll merge it now.

**Pull request merged**
