### PR TITLE
Update delimiters-for-documentation-tags.md

### PR DESCRIPTION
**Pull request by gewarren**
Changed link title for VS Options dialog box.

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
LGTM. Thanks @gewarren. 

 BTW, is that page not on TOC by design?

**Comment by gewarren** [comment]
@mairaw I just updated the link to the correct page. It is in the TOC though. Why do you think it's not?

**Comment by mairaw** [comment]
I’ll have to see it on my machine again. On my phone now, it’s hooked up to the TOC.

**Comment by BillWagner** [comment]
@mairaw It's in a sub-toc. (part of trying to shrink the nesting)

Merging now.

**Comment by mairaw** [comment]
I think it was user error. I think I was checking https://docs.microsoft.com/en-us//visualstudio/ide/reference/options-text-editor-csharp-formatting instead of https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-formatting (notice the double slash in the middle)

**Pull request merged**
