### PR TITLE
refresh "Walkthrough: My first WPF desktop application"

### PR DESCRIPTION
**Pull request by WilliamAntonRohm**
Freshness review per https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1409936

This PR replaces #11183 

All suggestions from that PR are incorporated herein

### CODE REVIEW

**Comment by WilliamAntonRohm** [comment]
@rpetrusha -- please review these updates -- I've incorporated your comments from #11183 

The article's code sample updates have been merged -- https://github.com/dotnet/samples/pull/757

The example solutions are in review -- https://github.com/Microsoft/WPF-Samples/pull/79

**Review by rpetrusha — APPROVED** [review]
This looks really good, @WilliamAntonRohm. Thanks for the major improvements you've made to this article. I'll approve the PR now, but I'll mark it as blocked until the PR in WPF-Samples is approved and merged.

**Comment by rpetrusha** [comment]
Making as blocked until microsoft/wpf-samples#79 is merged.

**Comment by rpetrusha** [comment]
Merging, since the related Microsoft/WPF-Samples#79 has merged.

**Pull request merged**
