### PR TITLE
Doc correction - Fix issue number  - #34333

### LINKED ISSUE #34333: fibonacci example
For the fibonacci example, I offer this:
```
let fib =
    (0, 1)
    |> Seq.unfold (fun state ->
        let cur, next = state
        if cur < 0 then  // overflow
            None
        else
            let next' = cur + next
            let state' = next, next'
            Some (cur, state') )
```
to replace this:
```
let fib =
    (1, 1) // Initial state
    |> Seq.unfold (fun state ->
        if (snd state > 1000) then
            None
        else
            Some(fst state + snd state, (snd state, fst state + snd state)))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67fae525-473a-3072-b024-6d91d0e033b9
* Version Independent ID: 6e162795-52bd-f9df-4105-6919c1c72c88
* Content: [Sequences - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences)
* Content Source: [docs/fsharp/language-reference/sequences.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/sequences.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

### PR DESCRIPTION
**Pull request by Adi9235**
## Summary

I have made the changes in file  ` docs/fsharp/language-reference/sequences.md`  and `samples/snippets/fsharp/fssequences/snippet14.fs` to solve the issue .

Fixes #34333 

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/fsharp/language-reference/sequences.md](https://github.com/dotnet/docs/blob/c76c2a0b426c927e7b656583d3846d4b90c53cb7/docs/fsharp/language-reference/sequences.md) | [Sequences](https://review.learn.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences?branch=pr-en-us-35592) |

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Review by IEvangelist — CHANGES_REQUESTED** [review]
I think we need to fix this...

**Comment by Adi9235** [comment]
Okkay let me fix this @IEvangelist by doing another commit

**Comment by Adi9235** [comment]
Hey @IEvangelist I have made the commit for correction of output could you please review it. Thanks

**Comment by Adi9235** [comment]
Hey @IEvangelist I have made the commit with updated limit .

**Comment by IEvangelist** [comment]
Let's ask @cartermp what he thinks about these proposed changes.

**Comment by Adi9235** [comment]
> Let's ask @cartermp what he thinks about these proposed changes.

Sure

**Comment by Adi9235** [comment]
Hey @IEvangelist is there any update on this?

**Comment by KathleenDollard** [comment]
@vzarytovskii

**Review by vzarytovskii — APPROVED** [review]
It's a bit more verbose, but verbosity adds clarity. I like it more than previous example. Thanks.

**Review by IEvangelist — APPROVED** [review]

**Comment by daveyostcom** [comment]
The code should restrict output to 20 numbers to correspond to the output shown.

**Pull request merged**
