### PR TITLE
2). Add sample files

### PR DESCRIPTION
**Pull request by jameshkramer**
@mairaw 
This PR is for user story #1576037.

It adds merged sample files, removes the corresponding C# and VB files, and adds appropriate redirection file entries.

cc: @tfosmark, @BillWagner 

Contributes to #4728

### CODE REVIEW

**Comment by mairaw** [comment]
Make sure to target our release branch when creating these @jameshkramer!

**Comment by jameshkramer** [comment]
@mairaw Oops!

**Comment by mairaw** [comment]
I've updated the release branch with the latest from master and it seems we now have some merge conflicts. Can you try to rebase your branch?

**Comment by jameshkramer** [comment]
@maira @BillWagner @KathleenDollard @tfosmark

It looks like the build has finally succeeded. Maira, I did not do the "How to:" to "How to" change. It wasn't clear to me that you wanted it done. - Jim

**Comment by jameshkramer** [comment]
@mairaw, please review this.

Thanks, Jim

cc: @tfosmark

**Comment by jameshkramer** [comment]
@mairaw, please review this.

Thanks, Jim

cc: @tfosmark

**Comment by mairaw** [comment]
Need a fresh build

**Review by mairaw — APPROVED** [review]
Thanks @jameshkramer. I've made some changes but this one is ready to go.

**Review by jameshkramer — COMMENTED** [review]
Maira, I thought you might want LINQ to XML in the sample file titles, but wasn't sure. I removed it because I thought users only needed to find sample files through the code samples that use them, not through search. Anyway I'm fine with your reinstating it. Sorry for the bother.

I didn't use redirect_document_id because it I saw very few occurrences of it in the file. I'll include it in the future.

All your changes seem fine to me.

**Pull request merged**
