### PR TITLE
AddHandler with lambda

### LINKED ISSUE #31428: AddHandler with Lambda
This page only explains adding handlers via addressof, but it seems also completely possible to give a lambda expression directly in the AddHandler statement instead of the addressof.
Please add this usage in the syntax and ideally also give an example and explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7771f230-ac9e-7310-e606-94bd9fc84f29
* Version Independent ID: 728dfc67-f3e9-64ea-8a91-c6d72c8cc54f
* Content: [AddHandler Statement - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/addhandler-statement)
* Content Source: [docs/visual-basic/language-reference/statements/addhandler-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/addhandler-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

### PR DESCRIPTION
**Pull request by marc-chevalier**
## Summary

Explain how to use AddHandler with a lambda.

Fixes #31428

### CODE REVIEW

**Comment by BillWagner** [comment]
Hi @marc-chevalier 

I've read the changes, and they look great. I can't merge this PR yet, because of the CI failure on the samples. (These older samples were imported from an internal system, and were built using an internal tool).

If you add a default *vbproj* file to the folder with the sample, that should address the issue. Then, I'll merge this.

**Comment by marc-chevalier** [comment]
I have very little practical knowledge of VB. Could you point me to some doc about how to do that, or such an example, please?

**Comment by BillWagner** [comment]
Hi @marc-chevalier 

I apologize, I didn't look as closely as I should have at the build report.  This one does have a project, but needs to use Visual Studio to build it.  (By default, we use the command line build option).

In the folder with the code, we need to add a snippets5000.json file with the following content:

```json
{
    "host": "visualstudio"
}
```

Then, the build should succeed.

**Comment by marc-chevalier** [comment]
Looks like I missed something.

**Review by BillWagner — APPROVED** [review]
Thanks again @marc-chevalier 

I had to upgrade the project to the latest .NET Framework (an automated migration). Now, it's fine, and I'll :shipit:

**Pull request merged**
