### PR TITLE
Remove the index page for whats new and redirect to 3.0 whats new

### LINKED ISSUE #12668: Fix Whats New section
Remove the What's New index page and point to 3.0.

The index page is useless and it will help the TOC look better and should redirect to the whats new 3.0 page.

### PR DESCRIPTION
**Pull request by Thraka**
## Summary

Remove the index page for whats new

Fixes #12668)

### CODE REVIEW

**Comment by mairaw** [comment]
We're not adding the redirects to the redirect file? adding @BillWagner since he has done a few of these

**Comment by Thraka** [comment]
I thought that the index files were going to stay in place or something like that? I searched through the repo and found other index files with redirects. But sure either way.

**Comment by BillWagner** [comment]
@Thraka @mairaw We landed at using the metadata redirect for those redirects that change every release (C# 8, .NET core 3.0, and so on).  That way, we can find them easier. 

I would add the `updateeachrelease` ms.custom value on this PR.  See https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/index.md

**Comment by Thraka** [comment]
@BillWagner Ahh yes. Thanks 👍

**Review by rpetrusha — APPROVED** [review]
LGTM, @Thraka. You can merge when you're ready.

**Pull request merged**
