### PR TITLE
How to compare strings: mention equality operators

### LINKED ISSUE #9619: It's not clear whether == and != operators use ordinal comparison
The "Default ordinal comparisons" section makes it clear that string.Equals uses an ordinal comparison, but there's no information about what the behavior of C#'s builtin == and != operators is. Do they use ordinal comparison too?

The only time the operators are mentioned is here:
> Avoid using the == and != operators when you test for equality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ecfc18-477b-f792-4136-2feb46bbc5d3
* Version Independent ID: 82f53ae8-a9d4-dea9-5acd-6d9202a40882
* Content: [How to: Compare strings - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings)
* Content Source: [docs/csharp/how-to/compare-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/compare-strings.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by pkulikov**
Fixes #9619

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks @pkulikov These changes are great. I'll :shipit: now.

**Comment by pkulikov** [comment]
@BillWagner thanks, could you please merge this.

**Comment by pkulikov** [comment]
Close/reopen for a new build.

**Comment by BillWagner** [comment]
Sorry about the delay on merging this @pkulikov 

I was waiting for the build to finish, and then it dropped off my radar.

**Comment by pkulikov** [comment]
@BillWagner no worries, thanks for fast responses to my PRs in general. As for this one, indeed, I've noticed later that the build was stuck.

**Pull request merged**
