### PR TITLE
Update live with current master

### PR DESCRIPTION
**Pull request by tdykstra**

### CODE REVIEW

**Comment by pkulikov** [comment]
@tdykstra that PR might result in a number of warnings because it relies on new snippets in the samples repo.

**Comment by tdykstra** [comment]
@pkulikov When will the snippets be added to the samples repo?

**Comment by pkulikov** [comment]
> @pkulikov When will the snippets be added to the samples repo?

They are added, already in master. The samples' master should be merged into live, first, to my knowledge of the build process.

**Review by natke — APPROVED** [review]

**Comment by mairaw** [comment]
I've kicked off a manual build of the live branch offline, When that finishes, you can rebuild this PR.

**Pull request merged**
