### PR TITLE
Avoid Blazor localization

### LINKED ISSUE #19309: French Blazor documentation "éblouissant"
There are still pages in the French documentation that says "éblouissant" instead of Blazor (again, for instance, the Italian documentation does not have this problem).

- https://docs.microsoft.com/fr-fr/dotnet/architecture/blazor-for-web-forms-developers/introduction
- https://docs.microsoft.com/fr-fr/dotnet/architecture/blazor-for-web-forms-developers/project-structure

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #19309

@JasonCard, Will this work that way?

### CODE REVIEW

**Comment by JasonCard** [comment]
@Youssef1313 Unfortunately, the no-loc metadata cannot be used in docfx.json file. It can only used in the YAML header metadata per each topic md file.

**Comment by Youssef1313** [comment]
Currently there are [21 files](https://github.com/dotnet/docs/search?l=Markdown&q=Blazor) mentioning Blazor based on the GitHub search. Should I update them all, or just the mentioned ones in the issue?

I'm also wondering if, at some point in the future, it'll be default behavior to not translate "Blazor". Just like "Visual Studio", it's not getting localized without any no-loc extensions. Keeping in mind that asp docs will likely have much much more occurrences of "Blazor" than here.

**Comment by JasonCard** [comment]
Yes, I'd suggest to add the no-loc metadata to those 21 files since those are topics about "Blazor" and contain multiple instances.
For ASP.NET Core documentation, no-loc metadata was added to all related topics ([example](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)).   

Yes, in the future, we hope to have new feature for Machine Translation engine to prevent over-localization of terms. We don't have an ETA on this feature yet, so using the no-loc metadata is the best solution for now.

**Comment by Youssef1313** [comment]
Great, I'll update them soon

**Review by JasonCard — APPROVED** [review]

**Review by BillWagner — APPROVED** [review]
Thanks @Youssef1313 and @JasonCard 

I'll :shipit: now.

**Pull request merged**
