### PR TITLE
Update WCF assemblies 

### LINKED ISSUE #3132: Official documentation on docs.microsoft.com says that no WCF types exist in netcore
@evil-shrike commented on [Fri Aug 25 2017](https://github.com/dotnet/wcf/issues/2235)

Docs (https://docs.microsoft.com) says that no any WCF exists in .net core!

> The requested page is not available for .NET Core 2.0. You have been redirected to a compatible version.

Just an example: https://docs.microsoft.com/ru-ru/dotnet/api/system.servicemodel.channelfactory?view=netframework-4.7&viewFallbackFrom=netcore-2.0

I understand that server-side WCF isn't implemented on netcore. But client types does exist in `System.ServiceModel.Primitives` packages. But the doc tells nothing about that.

### PR DESCRIPTION
**Pull request by TianqiZhang**
Fixes #3132 

[Internal review URL](https://review.docs.microsoft.com/en-us/dotnet/api/system.servicemodel?branch=pr-en-us-3208)

### CODE REVIEW

**Review by mairaw — APPROVED** [review]

**Comment by mairaw** [comment]
@TianqiZhang any clue why the namespace system.servicemodel is not found for .NET Core 2.0, when the APIs underneath exist in 2.0?

see here an example: https://review.docs.microsoft.com/en-us/dotnet/api/system.servicemodel?view=netcore-2.0&branch=pr-en-us-3208

**Comment by mairaw** [comment]
@zhenlan do you wanna take a look at this PR and see if you see the APIs you'd expect to be added here? I already found an issue with the namespace page for System.ServiceModel.

**Comment by TianqiZhang** [comment]
@mairaw just checked, it should be an incremental build issue, this namespace has no content change, only moniker change, so it did not re-build for the PR. If we merge this PR and do a force build, the monikers on page will be fixed.

**Comment by mairaw** [comment]
Cool. I'll merge and test on master then. Thanks @TianqiZhang!

**Comment by zhenlan** [comment]
Looks good. Thank you @mairaw!

**Pull request merged**
