### PR TITLE
Fix CA1835 code fix screenshot

### LINKED ISSUE #20820: Image shown for CA1835 docs are for the wrong fixer
---
**Issue moved from MicrosoftDocs/visualstudio-docs#5926**
- Please respond to @stephentoub.

---

_From @stephentoub on Monday, September 28, 2020 2:46:00 PM_

The docs at https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1835?view=vs-2019 in the "How to fix violations section" show applying the IDE0058 "Use discard" fixer rather than the fixer for CA1835:
image
A new image should be used that shows actually applying the desired CA1835.

cc: @carlossanlop, @jeffhandley 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030f8134-b8ab-5fc3-44dd-50935e50c6d2
* Version Independent ID: 856e4342-1385-ed6d-a8dd-1b08d1a93f10
* Content: [CA1835: Prefer the memory-based overloads of ReadAsync/WriteAsync methods in stream-based classes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1835?view=vs-2019)
* Content Source: [docs/code-quality/ca1835.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1835.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @carlossanlop
* Microsoft Alias: **calope**

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes https://github.com/dotnet/docs/issues/20820
When I created the screenshot, I didn't notice I was focusing the "expression value is never used" suggested change, instead of the actual CA1835 rule.
I made sure not to select `0` for the `offset` value because we are going to add an improvement to the rule to handle a special case: if `offset` is `0` and `count` is `buffer.Length`, then the suggestion will be to simply pass `buffer` (no `AsMemory` invocation). See https://github.com/dotnet/roslyn-analyzers/issues/4235
I also made sure to generate a screenshot in blue theme, because the original screenshot was in black theme and the rules say we should use the blue theme.

### CODE REVIEW

**Comment by carlossanlop** [comment]
I was just told that all the .NET SDK analyzers documentation got moved to this repo. I don't have permission to move issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/5926 to this repo, which still lives in the old visualstudio-docs repo, but if that's not an issue, we can leave it there.

**Comment by BillWagner** [comment]
closing and reopening for a fresh build.

**Comment by Youssef1313** [comment]
The screenshot may need to be updated again if https://github.com/dotnet/roslyn-analyzers/issues/4235 is done.

**Comment by carlossanlop** [comment]
Can I get a review, @dotnet/docs?

**Review by gewarren — APPROVED** [review]
LGTM

**Review by stephentoub — COMMENTED** [review]
This screenshot has a bug. If you tried to execute it, it would throw, because 5+buffer.Length is greater than buffer.Length.

**Pull request merged**
