### PR TITLE
Fixing additional build warnings

### PR DESCRIPTION
**Pull request by luisquintanilla**
Changed formatting from table to columns

[Preview Link](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work?branch=pr-en-us-25614)

AB#1865770

### CODE REVIEW

**Comment by luisquintanilla** [comment]
@adegeo can I please get a review on this one? The main update was formatting tables as rows / columns per contributor guide. Thanks!

**Review by briacht — APPROVED** [review]

**Review by adegeo — APPROVED** [review]
LGTM!

**Comment by adegeo** [comment]
I dont like that though, it's kind of ugly. You could do a data matrix which is similar and I think approved. You just need to add text to the 2nd column table header.

```
|               | header here  |
| --------- | -------------- |
| **Bold** | description... |
| **Bold** | description... |
| **Bold** | description... |
| **Bold** | description... |
```

**Comment by luisquintanilla** [comment]
Thanks @adegeo. I'll take a look.

**Pull request merged**
