### PR TITLE
Fix loc issue

### PR DESCRIPTION
**Pull request by Youssef1313**
This is how the article **currently** show in the localized versions:

image

I think the changes I made would fix that.

### CODE REVIEW

**Comment by Youssef1313** [comment]
This PR doesn't cover all the articles with this problem, but covered most of them.

**Comment by mairaw** [comment]
@JasonCard after we merge this PR, can you make sure to follow up and see if the issue is addressed for loc? Thanks.

**Review by mairaw — APPROVED** [review]
Thanks @Youssef1313!

**Comment by JasonCard** [comment]
@mairaw @Youssef1313 Thank you for working on this fix. Yes, I'll follow up to check if this issue is resolved.

**Comment by Youssef1313** [comment]
@mairaw, seems like this didn't fix the issue. :cry:
This is strange because <https://docs.microsoft.com/fr-fr/dotnet/framework/configure-apps/file-schema/runtime/> (and many others) renders correctly and the only difference I could find is the backslash thing.
<https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/index.md>.

cc: @JasonCard

**Comment by JasonCard** [comment]
@Youssef1313 @mairaw I'm sorry for the delayed update on this. I was monitoring for this fix to publish for loc, but after investigation found that all of our localized update commits to dotnet/docs loc repos were failing since 11/12. We've found the root cause, but having difficulty resolving the issue, so currently working on a workaround to have all affected files committed and published by Monday. Will update.

**Comment by JasonCard** [comment]
@Youssef1313 @mairaw It's [fixed now](https://docs.microsoft.com/fr-fr/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings), although MT engine is adding an extra space before closing brackets, so I will follow up to see if that can be fixed on MT engine side:
fr-fr_fixed

**Comment by JasonCard** [comment]
@Youssef1313 @mairaw We have a question, are the escape/backslash chars (\) before the opening brackets (<) necessary? If those are removed, then those elements will be blocked from translation. If those are needed, then we can request for feature to update our transformer to block them even in those cases.

**Comment by mairaw** [comment]
yes, they are; otherwise, they are not rendered @JasonCard 

Compare here on the preview:

Look like it will render:

with the escape:
\<configuration>

without the escape
<configuration>

**Comment by mairaw** [comment]
This is how it was written:
image

**Comment by JasonCard** [comment]
Thank you for confirming. I will request for a feature to update our transformer to block those even with the escape char, so no fix is needed on your end. Will update on this.

**Comment by JasonCard** [comment]
@mairaw Would it be possible to use the inline no-loc md extensions like below?

\# :::no-loc text=”\<specifiedPickupDirectory>"::: Element (Network Settings) 

\[\**:::no-loc text=”\<configuration>":::**](../configuration-element.md)\

cc @mayast

**Comment by mairaw** [comment]
Can you do one as a test @JasonCard?

**Comment by JasonCard** [comment]
@mairaw Okay, I've opened this PR as test [https://github.com/dotnet/docs/pull/16079](https://github.com/dotnet/docs/pull/16079).

**Pull request merged**
