### PR TITLE
Remove .NET Portability Analyzer links

### LINKED ISSUE #37203: Link to outdated software - .NET Portability Analyzer
Github project of .NET Portability Analyzer has been archived and is no longer developed, but there are some links in the docs still pointing to it as a way to verify 3rd party dll files for compatibility with the .NET
Not only on the page mentioned below, but also here: https://learn.microsoft.com/en-us/dotnet/core/porting/ and possibly other places.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1571bd84-84b9-ef24-f96f-304665e22bea
* Version Independent ID: f238803f-7e31-e6b1-0d23-cebb0672de95
* Content: [Analyze dependencies to port code - .NET Core](https://learn.microsoft.com/en-us/dotnet/core/porting/third-party-deps#net-framework-compatibility-mode)
* Content Source: [docs/core/porting/third-party-deps.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/third-party-deps.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @StephenBonikowsky
* Microsoft Alias: **stebon**

---
[Associated WorkItem - 189688](https://dev.azure.com/msft-skilling/Content/_workitems/edit/189688)

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #37203

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/porting/third-party-deps.md](https://github.com/dotnet/docs/blob/06d10e82b831b916ad39ee54e61f28399cb8b659/docs/core/porting/third-party-deps.md) | [Analyze your dependencies to port code from .NET Framework to .NET](https://review.learn.microsoft.com/en-us/dotnet/core/porting/third-party-deps?branch=pr-en-us-38729) |
| [docs/core/porting/upgrade-assistant-overview.md](https://github.com/dotnet/docs/blob/06d10e82b831b916ad39ee54e61f28399cb8b659/docs/core/porting/upgrade-assistant-overview.md) | [Overview of the .NET Upgrade Assistant](https://review.learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview?branch=pr-en-us-38729) |

### CODE REVIEW

**Review by BillWagner — COMMENTED** [review]
This LGTM @gewarren 

Let's :shipit:

**Comment by gewarren** [comment]
@BillWagner Did you mean to approve this?

**Comment by BillWagner** [comment]
@gewarren 

Yes, I looked good. If you explicit want other reviews, that's fine too.

**Comment by gewarren** [comment]
> @gewarren
> 
> Yes, I looked good. If you explicit want other reviews, that's fine too.

Thanks - can you actually approve it though? I think you just commented.

**Review by IEvangelist — APPROVED** [review]

**Pull request merged**
