### PR TITLE
Updated TOC

### PR DESCRIPTION
**Pull request by stevehoag**
Added Collections sub-topics; removed wrenches

### CODE REVIEW

**Comment by blackdwarf** [comment]
@stevehoag ok, the collections should not be there. We have a section below under "Application scenarios" for collections and they should be there.

**Comment by stevehoag** [comment]
@blackdwarf  I thought all of the content we're porting from MSDN was going to live under .NET Essentials. Not sure what the other Collections node under Application Scenarios was intended to be.

**Comment by blackdwarf** [comment]
@stevehoag that was where the porting docs were supposed to go. :)

**Comment by stevehoag** [comment]
@blackdwarf @mairaw The collection topics aren't application scenarios, they're concepts necessary to understand how .NET works. If the content ported from MSDN is supposed to be under Application Scenarios, what is supposed to be under .NET Core Essentials?

**Comment by cartermp** [comment]
I think there's a bit of a content split here.

* The articles describing what some of these collections are, which are definitely not application scenarios.
* The articles describing when to use certain collections could go under either Application Scenarios or .NET Essentials.
* The articles describing how to create certain types of concurrent collections are definitely Application Scenarios.

**Comment by blackdwarf** [comment]
@cartermp ok, let's say that we agree. @stevehoag can you make that change in this PR?

**Comment by stevehoag** [comment]
@blackdwarf  @cartermp So let's make sure we're clear - pure conceptual content goes under Essentials, and How-to articles go under Scenarios? And should we be following this convention for all content ported from MSDN?

Can we just make the changes in the TOC and leave the file structure as-is?

**Comment by stevehoag** [comment]
@blackdwarf  I moved the topics and made a couple of other minor changes. Please review.

**Comment by blackdwarf** [comment]
@stevehoag :shipit:

**Pull request merged**
