### PR TITLE
Remove duplicate feature System.Text.Json

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
Remove duplicate feature link from Systema.Text.Json

### CODE REVIEW

**Comment by ralmsdeveloper** [comment]
Resolve #21536

**Review by tdykstra — APPROVED** [review]
Thanks!

**Comment by tdykstra** [comment]
I merged before realizing that the PR is to the live branch -- we only do publishing PRs to live, all PRs that update docs should go to master.

**Comment by tdykstra** [comment]
@ralmsdeveloper I can make a replacement commit and PR -- let me know if you would rather do it.

**Comment by ralmsdeveloper** [comment]
@tdykstra I'm sorry!

I made a PR: https://github.com/dotnet/docs/pull/21543

**Pull request merged**
