### PR TITLE
Re-format code sample

### PR DESCRIPTION
**Pull request by coc2coc**
Re-format code sample

Missing close bracket, re-format with tab

### CODE REVIEW

**Comment by coc2coc** [comment]
how do i accept CLA, because when i click "Sign in with GitHub to agree" button, this page loops forever in url "https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=6810"

Regards,
Chinh
________________________________

**Comment by mairaw** [comment]
@coc2coc you can't even open that URL?

**Comment by coc2coc** [comment]
It's ok now. I suspect because i saved password on github so button "I agree" never show. I switched to another pc and it work

**Review by rpetrusha — APPROVED** [review]
Thanks, @coc2coc, for correcting the formatting of the code in this article. I've also added language identifiers so that keywords are colorized. I'll merge your PR now. Your changes should appear live on docs.microsoft.com in the next day or two.

**Pull request merged**
