### PR TITLE
Must start without debugging to add service

### PR DESCRIPTION
**Pull request by user135711**
Added line "Be sure to start the app without debugging or else the add service option will be deactivated."

### CODE REVIEW

**Review by CamSoper — COMMENTED** [review]
Thanks for the contribution! I've requested a clarification before we can publish.

**Review by CamSoper — CHANGES_REQUESTED** [review]
Can you please verify which version of VS you were using? I just tried with VS2017 (15.7.3) and I was able to add a service reference without even running the host. You can click the "discover" button and it apparently finds the assemblies in the current solution.
Otherwise, you're right - You need to start the host without debugging to add the service reference on the fly.

**Comment by user135711** [comment]
I believe it was on the preview release of Visual Studio 2017, but this
behavior and fix I found from a SO post from over a year ago, so I don't
know why it's working while debugging on yours. Are you sure you started
with F5? If it's working on your machine go ahead and close this pull
request. Just thought I'd save someone else debugging time.

**Comment by user135711** [comment]
Oh, you didn't even start the host. I see. I think the tutorial should be
updated to reflect that with instructions on using discover.

**Comment by CamSoper** [comment]
I agree! Would you like to make that change to this PR, or would you like us to close this PR and take it as a backlog item?

**Comment by user135711** [comment]
I can't do it this second. But maybe I might get a chance later.

**Pull request closed without merging**
