### PR TITLE
dotnet install: Add arch options

### LINKED ISSUE #36334: dotnet tool install: Missing architecture options  -a / --arch
This topic is missing the dotnet tool install options of `-a` and `--arch` for specifying the target architecture.

Example:
`dotnet tool install -g -a arm64 Microsoft.Web.LibraryManager.Cli`

`dotnet tool install -h` lists this option currently as the following in .NET 7 and 8 Preview:
  -a, --arch <arch>            The target architecture.

See also: 
Related topic similar topic covering architecture options: [dotnet-install scripts reference](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options)
Related issue dotnet/AspNetCore.Docs#29262

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 132884](https://dev.azure.com/msft-skilling/Content/_workitems/edit/132884)

### PR DESCRIPTION
**Pull request by wadepickett**
## Summary

Updating dotnet-tool-install.md to include architecture options `-a` and `--arch`

Fixes #36334 and contributes a first step required before this topic can be referenced in a fix for issue dotnet/AspNetCore.Docs#29262

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/39e0758c6aa20d2fa5e44f1b8af6fb54e01fcafd/docs/core/tools/dotnet-tool-install.md) | [dotnet tool install](https://review.learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install?branch=pr-en-us-36345) |

### CODE REVIEW

**Comment by wadepickett** [comment]
@tdykstra, I'm new to reading through the code for `dotnet install` to document features and options.  I referred to the following dotnet SDK source to determine the architecture options available here:
[sdk/eng/common/dotnet-install.sh at main · dotnet/sdk (github.com)](https://github.com/dotnet/sdk/blob/main/eng/common/dotnet-install.sh)
and here:
[sdk/eng/common/dotnet-install.ps1 at main · dotnet/sdk (github.com)](https://github.com/dotnet/sdk/blob/main/eng/common/dotnet-install.ps1)

I expected the architecture option of `ppc64le` as we have for dotnet-install script architecture options, but didn't find it in the source code, so I might be missing something.  For now, I have it in the PR but my confidence level is low for that one.

**Comment by tdykstra** [comment]
The `dotnet tool` commands are different from the `install-scripts` commands. Your text here is from the `--arch` description for `install-scripts`.

@baronfel, for `dotnet tool install` does it make sense to use the same `--arch` description that we have for `install-scripts`?

**Comment by baronfel** [comment]
no - the `--arch` option for tool install is the same `--arch` option used for other .NET CLI commands, like build, test, etc - it is the architecture portion of a `RuntimeIdentifier` (docs on that concept are [here](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog)), and is data-driven from the Runtime Identifier Catalog. Typical architectures might be `x64`, `arm`, `arm64`, `ppc64le`, `s390x`, and more.

**Comment by wadepickett** [comment]
@tdykstra,  I found your include that seems to already cover this description: `[!INCLUDE [arch](../../../includes/cli-arch.md)]`
However since it mentions the --runtime option which I think does not apply here, I just copied the portion that applied. It did not seem like this would be worth adding a 2nd similar include or breaking it up.

My confidence is still a bit low in the resulting description since I don't' know this area, but it seems right.  See what you think.  Thanks to you and @baronfel for the great help.

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
