### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by MNie**
# Title

Link about creating an azure function in f#
## Summary

Add link to a post which has a short introduction to creating an azure function in f#
## Details

As I saw there is already a link for hosting suave.io as an azurefunction on azure. But I think someone could be interest on how to create a simple azure function in F#.
## Suggested Reviewers

If you know who should review this, use '@' to request a review.

add link to simple introduction to creating an azure function in f# on azure

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/using-fsharp-on-azure/index?branch=pr-en-us-1151](https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/using-fsharp-on-azure/index?branch=pr-en-us-1151)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610140844436579-1151%5Cworkflow_report.html).

**Comment by BillWagner** [comment]
Closing and reopening to kick off the CI build again. (This PR should not have caused a build failure)

**Comment by saldana** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/using-fsharp-on-azure/index?branch=pr-en-us-1151](https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/using-fsharp-on-azure/index?branch=pr-en-us-1151)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: articles/standard/base-types/extract-day.html contains illegal link: core/api/System.DateTime.html#System.DateTime.Parse(System.String). The file core/api/System.DateTime.html doesn't contain a bookmark named System.DateTime.Parse(System.String), please check the src file docs/standard/base-types/extract-day.md and src linkedTo file api_ref/System.DateTime.yml or the template you applied...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C6%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611061818459768-1151%5Cworkflow_report.html).

**Comment by BillWagner** [comment]
@cartermp Do you want to approve and merge this?

**Comment by cartermp** [comment]
LGTM.  Thanks, @MNie!

**Pull request merged**
