### PR TITLE
Building .NET Core solutions using Visual Studio for Mac

### LINKED ISSUE #1743: Building .NET Core solutions using Visual Studio for Mac
* Prerequisites for .NET Core on Mac
* Getting started with .NET Core on macOS using Visual Studio for Mac
* Building a complete .NET Core solution on macOS using Visual Studio for Mac

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #1743

Notes
* Minor change to windows prepreqs in passing here
* Prereqs section: No single bullet there on one prereq unless you want it. I'm not a big fan of the *single bullet list.* Let me know.
* Took my liberties with the unit test part. IMO there's no super-fast way to do it. I didn't want to only do a `Fact` or skip to only a `Theory`. By the time you do both, it extends the experience to the max for a introductory tutorial. However in defense of this approach, there isn't enough unit testing in the world imo. Devs prob need to see how easy and useful they are.
* On the ASP.NET Core side, we did put links to open GH work issues for missing features. I did that here with the bit on the test runner not working in VS for Mac. I can pull that line if you like. If the line stays, I'm monitoring that issue, and I'll submit a PR to remove it and update the text/images when they get it fixed.
* ... and this one was a real pleasure. :grinning: I like Macs, and I don't get enough time to mess around with my Mac Mini. It performed beautifully here! *Tip of the* 🎩 *to Apple!* :beers:

### CODE REVIEW

**Comment by GuardRex** [comment]
cc/ @bleroy -- If you're reviewing, the drafts are finished.

**Comment by BillWagner** [comment]
I reviewed everything, and it LGTM.
@bleroy Do you want to review as well, or should we :shipit:?

**Review by BillWagner — APPROVED** [review]
I read through everything, and have no issues.

**Comment by bleroy** [comment]
I did give it a look, and it looks good to me.

**Comment by GuardRex** [comment]
Thanks guys ..... all new content here and my first time using the Mac with .NET Core, so I greatly appreciate the :eyes: on it.

**Comment by bleroy** [comment]
@BillWagner @mairaw I suppose the only question I would have is not about this PR specifically, but about what happened to the VS Mac work I did a few months ago (see https://github.com/dotnet/docs/commits/vs-mac-golden-path) as I can't find this in the current TOC.

**Comment by BillWagner** [comment]
@bleroy I'm going to defer to @mairaw on that one.

**Comment by GuardRex** [comment]
@bleroy This was a rather extensive rewrite starting with the direction you took. Elements of what you did come thru here, and I thank you for that and the docs on this PR benefit greatly from your work.

**Pull request merged**
