### PR TITLE
 Update PInvoke examples

### PR DESCRIPTION
**Pull request by nxtn**
Contributes to #11396, #11772

### CODE REVIEW

**Comment by NextTurn** [comment]
These examples can be migrated to the *samples* repo.

**Comment by NextTurn** [comment]
@rpetrusha

**Review by rpetrusha — APPROVED** [review]
I apologize, @NextTurn. I seem to have overlooked your PR. I'll merge it now.

**Comment by NextTurn** [comment]
@rpetrusha Shall we move the examples to the *samples* repo? If so, which directory should they be in?

**Comment by rpetrusha** [comment]
Yes, @NextTurn, moving them to the samples repo is an excellent idea. They could go in the snippets/standard/interop/pinvoke directory.

**Pull request merged**
