### PR TITLE
[DocsArchive-1.0.19259.5](2019-09-22-20-26-07)Auto archive content

### LINKED ISSUE #14801: Retire WIF content
The WIF content is no longer being maintained and is deprecated. It should be moved to the archive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d54b325-d292-fa24-7b3c-c4f3d823b28b
* Version Independent ID: 0a925f29-d208-58a9-ccff-06c920e9900b
* Content: [Windows Identity Foundation](https://docs.microsoft.com/en-us/dotnet/framework/security/)
* Content Source: [docs/framework/security/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/index.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

### PR DESCRIPTION
**Pull request by Khairunj**
## Migration of Windows Identity framework content

This request is to archive Windows Identity framework content to docs previous version site

Fixes #14801

### CODE REVIEW

**Comment by Khairunj** [comment]
@mairaw Let's discuss this PR tomorrow.  Don't merge it yet until archive repo PR is in live branch

**Comment by mairaw** [comment]
@Khairunj can the tool add the entries ordered by alphabetical order in .openpublishing.redirection.json? At least, that's what we do here to avoid some of the merge conflicts.

**Comment by Khairunj** [comment]
@mairaw At this moment I don't know if other teams will like archive tool to re-order or alphabetize the redirection entries.  Currently we just append at the end.   We will explore the option by providing a config value after i check with other teams.

**Review by mairaw — APPROVED** [review]
Thanks @Khairunj!

**Pull request merged**
