### PR TITLE
Update seedwork-domain-model-base-class-interface

### PR DESCRIPTION
**Pull request by mjavadhpour**
Fix martin fowler separatedInterface link.

# Fix link to Martin Fowler blog post

## Summary

Link to Martin Fowler blog post has special character (%20) and have error 404. this error fixes with removes this special character.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for spotting this and fixing it @mjhpour We appreciate it.

I've reviewed the change, and I'll :shipit: now. It should show up on our live site in the next day or so, on our regular publishing cycle.

Thanks again.

**Comment by mjhpour** [comment]
@BillWagner Thanks you too.

**Comment by mairaw** [comment]
pinging @CESARDELATORRE since this is in the e-books

**Comment by CESARDELATORRE** [comment]
Thanks! :)

**Pull request merged**
