### PR TITLE
CC6180: `if` statement in C#

### PR DESCRIPTION
**Pull request by carolinacmoravia**
@BillWagner,
It seems that `if` statement in C# should be updated. Could you check this proposed file change, please?
This comes from this contribution: https://github.com/dotnet/docs.fr-fr/pull/32/files. 
Many thanks in advance.

### CODE REVIEW

**Comment by mairaw** [comment]
I'm not so sure I agree with this proposal. @BillWagner what are your thoughts on this? The statement there is supposed to represent commands you'd run, not to be a program you could actually run.

**Comment by BillWagner** [comment]
I agree with @mairaw. I don't think the change helps, and it could cause confusion.

What was the author trying to fix?

**Comment by mairaw** [comment]
I think he was just trying to create a snippet that would compile. But I see that @nokura used that PR to merge master to live, which seems wrong. We should probably revert that change on the localized repo and close this PR.

**Comment by carolinacmoravia** [comment]
@BillWagner and @mairaw, thanks for your quick replies.
Closing this PR since it does not apply.

**Pull request closed without merging**
