### PR TITLE
Replace passwords with placeholder for credscan

### LINKED ISSUE #21773: Replace passwords with [PLACEHOLDER] for CredScan

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #21773.

### CODE REVIEW

**Comment by gewarren** [comment]
I'm not planning to add the project files for snippets 5000.

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

If it's not too much extra work on this PR, you could add project files so the two CI build errors are fixed.

**Comment by gewarren** [comment]
There were warnings for 5 missing projects. I deleted 3 of the snippets (unused) and added one project. The other snippet has a makefile, so I'm going to leave that one alone.

**Comment by gewarren** [comment]
Close/reopen for license/cla.

**Pull request merged**
