### PR TITLE
Fix inconsistent compiler switches (from / to -)

### LINKED ISSUE #4072: Inconsistent switch usage for C# compiler options
[This page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/debug-compiler-option) and all pages under [C# compiler options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically) are inconsistent in how they list compiler options.

The TOC and titles uses the - character. The headers all use '/'

We should pick one to be consistent.

### PR DESCRIPTION
**Pull request by sputier**
Related to issue #4072 

Edit by @mairaw: removed the keyword fixes to not close the issue just yet

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thanks @sputier for jumping in on the issue. The compiler options pages look great! One thing I realized is that there's one more task related to this, which is to fix the incoming links. Those are still using the /.

**Comment by sputier** [comment]
@mairaw : 👍  I planned to take a look at this today. I'll Create a new PR in the next hours for this :-)

**Comment by sputier** [comment]
@mairaw Should I change every occurences of the / switches (snippets, links, samples) ?

**Comment by mairaw** [comment]
I thought the only thing left was incoming links but if you find other things, please go ahead and change them. Thank you so much!

**Pull request merged**
