### PR TITLE
Update toc.yml

### PR DESCRIPTION
**Pull request by skycommand**
Add missing items

## Summary

There have been several items missing from the "Parallel processing, concurrency, and async" section. Their absence gave the impression that the section is entirely about parallel programming. This PR adds those items.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=28664) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=28664) before we can accept your contribution.<br/><br/>:x: skycommand [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=28664)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=28664) it.</sub>

**Comment by BillWagner** [comment]
ping @tdykstra

**Review by tdykstra — COMMENTED** [review]
@skycommand Thanks for your submission, but the articles in question aren't missing. Both the "Asynchronous programming patterns" and the "Threading" lines in the main TOC go to separate topic area TOCs. You see all the articles in a topic area TOC when you click the TOC line for that topic area.

**Comment by skycommand** [comment]
@tdykstra Hi. ☺ What's a "topic area"?

**Comment by tdykstra** [comment]
From the main TOC (https://docs.microsoft.com/en-us/dotnet/fundamentals/) select "Security".  You'll see that it doesn't expand the TOC node, it takes you to a different TOC. This security TOC has entries for security-related articles; for lack of a better term that's what I'm calling a topic area.

**Comment by tdykstra** [comment]
The sub-toc is provided by a separate toc.yml. In the case of Security, it's here: https://github.com/dotnet/docs/blob/main/docs/standard/security/toc.yml

**Comment by skycommand** [comment]
Yes... I see. It is weird, though. I can't comprehend its purpose. 🤷‍♀️

Still, since it is your website, you're at liberty to arrange it however you like. I'll be removing the forked branch now.

**Pull request closed without merging**
