### PR TITLE
Updated private protected section

### PR DESCRIPTION
**Pull request by jaliyaudagedara**
Updated private protected section to make it more clear.

### CODE REVIEW

**Comment by BillWagner** [comment]
@jaliyaudagedara I'm going to close this PR, because the change is technically incorrect.

`private protected` methods are *not* accessible from the containing class. 

We do appreciate contributions, and I look forward to other contributions from you. If the description of `private protected` led you to think these would be accessible from a containing class, we'd be happy to work with you to make that more clear.

**Comment by jaliyaudagedara** [comment]
Hi @BillWagner, 

oh, thanks for the clarification. But in, [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/access-modifiers), it says "**Access is limited to the containing class or types derived from the containing class within the current assembly**."

image

May be we need to correct that?

**Comment by BillWagner** [comment]
Thanks for responding.  I had the wrong definitions in my head this morning.

**Comment by jaliyaudagedara** [comment]
It happens, No worries @BillWagner!

**Comment by BillWagner** [comment]
I looked at the language spec, and I was using the term "containing type" incorrectly. (Not enough coffee, I was thinking it meant a nested class).  😿 

By correctly using the term to mean the class where the method is declared, your change is correct.  I'll :shipit: now.

It should show up on our live site in the next day or so, on the next publish cycle.

Thanks for submitting this, and for helping me catch my mistake reviewing. 🙌  We appreciate it.

**Review by BillWagner — APPROVED** [review]
This LGTM.

**Comment by jaliyaudagedara** [comment]
It's always a pleasure @BillWagner 👍. Keep up the great work!

**Pull request merged**
