### PR TITLE
Add no-locs

### LINKED ISSUE #22872: Do not translate short names in dotnet new
In the template argument table, the "short name" column should not be translated. I don't want to type `dotnet new réagir` on my french computer 😉 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #22872

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
LGTM, thanks @Youssef1313

**Comment by mairaw** [comment]
This broke the anchor links

**Comment by Youssef1313** [comment]
@mairaw Ops, sorry for that. Should the no-loc be added inside the square brackets instead?

**Comment by tdykstra** [comment]
@Youssef1313 maybe inline code style would work better in this case.

**Pull request merged**
