### PR TITLE
add January 2021

### PR DESCRIPTION
**Pull request by BillWagner**
This has that some workaround for the single-item in the 2021 TOC node.

[Internal review link](https://review.docs.microsoft.com/en-us/dotnet/whats-new/2021-01?branch=pr-en-us-22646)

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
I am curious about the TOC work around, is the idea to have a 2020 node and a 2021 node?
Looks good to me, :shipit: when you're ready.

**Comment by BillWagner** [comment]
@IEvangelist Yes, the goal is to have a TOC that looks like:

- 2021
  -  February
  - January
- 2020
  - December
  - November
  - October
  - September

Unfortunately, a node with a single child doesn't work.

**Comment by gewarren** [comment]
Looks like we need to update the breadcrumb.

image

**Comment by tdykstra** [comment]
>Unfortunately, a node with a single child doesn't work.

I just tried that and it seems to work fine -- https://review.docs.microsoft.com/en-us/dotnet/whats-new/2020-12?branch=tdykstra-patch-1

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
