### PR TITLE
Add missing enum fields in Event​Wait​Handle class document.

### PR DESCRIPTION
**Pull request by huww98**
## Summary

Clear unnessesary %2A, Add missing enum fields in Event​Wait​Handle class document.

### CODE REVIEW

**Comment by GuardRex** [comment]
@huww98 Thanks for helping with this. The updates where you removed the asterisk/wildcard (`%2A`) created a few invalid cross-references. Revert the `%2A` changes on these, and it should bring the cross-reference links back ...

\<xref:System.Threading.EventWaitHandle.SetAccessControl>
\<xref:System.Threading.EventWaitHandle.%23ctor>
\<xref:System.Threading.WaitHandle.SignalAndWait?displayProperty=fullName>
\<xref:System.Threading.WaitHandle.WaitAll?displayProperty=fullName>
\<xref:System.Threading.WaitHandle.WaitAny?displayProperty=fullName>
\<xref:System.Threading.EventWaitHandle.OpenExisting>
\<System.Threading.EventWaitHandle.%23ctor>

**Review by guardrex — CHANGES_REQUESTED** [review]
@huww98 Thanks for helping with this. The updates where you removed the asterisk/wildcard (`%2A`) created a few invalid cross-references. Revert the `%2A` changes on these, and it should bring the cross-reference links back ...

\<xref:System.Threading.EventWaitHandle.SetAccessControl>
\<xref:System.Threading.EventWaitHandle.%23ctor>
\<xref:System.Threading.WaitHandle.SignalAndWait?displayProperty=fullName>
\<xref:System.Threading.WaitHandle.WaitAll?displayProperty=fullName>
\<xref:System.Threading.WaitHandle.WaitAny?displayProperty=fullName>
\<xref:System.Threading.EventWaitHandle.OpenExisting>

**Comment by huww98** [comment]
I accidentally saw these `%2A` as `%20`(writespace)

**Comment by huww98** [comment]
@GuardRex I have revert these changes, and the cross-reference links seem OK now.

**Comment by GuardRex** [comment]
In the NOTE on line 587 ...

> There is no guarantee that every call to the <xref:System.Threading.EventWaitHandle.Set%2A> method will release a thread from an <xref:System.Threading.EventWaitHandle> whose reset mode is <xref:System.Threading.EventResetMode?displayProperty=fullName>. If two calls are too close together, so that the second call occurs before a thread has been released, only one thread is released. It is as if the second call did not happen. Also, if <xref:System.Threading.EventWaitHandle.Set%2A> is called when there are no threads waiting and the <xref:System.Threading.EventWaitHandle> is already signaled, the call has no effect.  

Should the "AutoReset" reset mode also be specified there? ...

> ... whose reset mode is <xref:System.Threading.EventResetMode.AutoReset?displayProperty=fullName>.

**Comment by GuardRex** [comment]
@huww98 Thanks ... looks great! :rocket: We'll get this merged after the build finishes.

**Review by guardrex — APPROVED** [review]

**Comment by huww98** [comment]
@GuardRex Now, it finished😉

**Pull request merged**
