### PR TITLE
Add missing filter operator for dotnet test

### PR DESCRIPTION
**Pull request by AndreyTretyak**
I've needed this operator and it' looks like it's working properly but it's not listed in the docs

### CODE REVIEW

**Comment by AndreyTretyak** [comment]
@mairaw could you please review?

**Comment by Thraka** [comment]
@AndreyTretyak Hi there. Sorry for the delay on this. We based this information on the docs provided by the vstest docs: https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md which doesn't have this listed. 

@nigurr @singhsarab can one of you comment? Thanks!

**Comment by Thraka** [comment]
Sent email to @nguerrera @singhsarab 

@AndreyTretyak sorry for the delayed response on this.

**Review by AbhitejJohn — APPROVED** [review]

**Comment by AbhitejJohn** [comment]
LGTM. 
/cc: @nohwnd

**Review by Thraka — APPROVED** [review]

**Pull request merged**
