### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by coolcane**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=24254) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=24254) before we can accept your contribution.<br/><br/>:x: whatever445 [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=24254)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=24254) it.</sub>

**Review by Youssef1313 — COMMENTED** [review]
Can you elaborate more on what you're trying to do here?

**Comment by BillWagner** [comment]
@whatever445 

Can you explain more here? As entered, this PR doesn't add any information for readers. If you can explain what you're trying to do, we'll help you work through the process. 

Otherwise, we'll close this PR.

**Comment by adegeo** [comment]
@BillWagner we should just close this

**Comment by BillWagner** [comment]
Closing as not on-topic.

**Pull request closed without merging**
