### PR TITLE
Fix the bug, print parsed number...

### LINKED ISSUE #22304: Typo in TryParse example
The last TryParse example in the first code block prints inputString on success instead of numValue, which seems incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91931f7-35de-15e0-4c20-53a3fa9246ec
* Version Independent ID: d9031bdc-890a-d5bd-c1ed-d767b0e27890
* Content: [How to convert a string to a number - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/how-to-convert-a-string-to-a-number)
* Content Source: [docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

Fix the bug, print parsed number...

Fixes #22304

### CODE REVIEW

**Comment by adegeo** [comment]
@IEvangelist I'm unsure why this error is showing. It's odd because there isn't a .NET Core 3.1.11 to even try to run against so I don't understand why it's choosing it. Can you add the following file to the project directory so I can try and debug it?

```json
{
    "host": "custom",
    "command": "dotnet build `\"$projectFile`\" -v d"
}

**Comment by IEvangelist** [comment]
> @IEvangelist David Pine FTE I'm unsure why this error is showing. It's odd because there isn't a .NET Core 3.1.11 to even try to run against so I don't understand why it's choosing it. Can you add the following file to the project directory so I can try and debug it?
> 
> ```json
> {
>     "host": "custom",
>     "command": "dotnet build \"$projectFile\" -v d"
> }
> ```

Sure thing, I should be able to add this a bit later today - thanks

**Comment by adegeo** [comment]
Duh, I can add it myself 😁

**Comment by adegeo** [comment]
So I get around to adding the config file to get some debug information about the build and then some joker goes and uploads the missing package we've been seeing and fixes the problem....

NuGet
image

**Comment by IEvangelist** [comment]
Interesting... that is very odd! So, this should be good to go then - thanks

**Review by BillWagner — APPROVED** [review]
This LGTM @IEvangelist 

You can :shipit: when ready.

**Pull request merged**
