### PR TITLE
Update xaml.md

### LINKED ISSUE #14334: Update xaml.md with links for desktop guide
`docs/desktop/wpf/fundamentals/xaml.md` needs to have all of the TODO links fixed.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #14334

/cc @Thraka

### CODE REVIEW

**Comment by Youssef1313** [comment]
@Thraka, Hope my changes are correct and not breaking something 😄

**Comment by mairaw** [comment]
I have a feeling that these were TODO sections because @Thraka is still working on bringing that content over.

**Comment by Youssef1313** [comment]
@mairaw, If that is the case, then this PR should be closed.

**Comment by Thraka** [comment]
Hey there @Youssef1313 Thanks for looking at this, I do however have this assigned to myself to work on. I do have to double check some other related things and do a little processing on each section. It will be easier for me to work from the commented TODO instead of from your edits directly. I'll close this. Cheers!

**Pull request closed without merging**
