### PR TITLE
Fixed TOC structure

### PR DESCRIPTION
**Pull request by svick**
CLR etc. don't belong under collections.

Also added missing link to Numerics in .Net Core.

### CODE REVIEW

**Comment by svick** [comment]
When adding the link to Numerics, I have followed the same structure as Collections, where essentials articles are under the apis article.

Is the [apis numerics article](https://github.com/dotnet/core-docs/blob/master/docs/apis/numerics/index.md) going to be useful, or should I remove it as duplicate of [the essentials article](https://github.com/dotnet/core-docs/blob/master/docs/essentials/numericsincore.md)?

**Comment by mairaw** [comment]
@stevehoag you were working on the numerics topics no?

**Comment by stevehoag** [comment]
@svick Yes, it seems like the api numeric article would be a duplicate. The essentials article should be comprehensive enough, and if not we should add to it rather than writing another article.
@mairaw I believe my work item was to change the filename to all lower case, and that's already been done.

**Comment by mairaw** [comment]
If you go to https://github.com/dotnet/core-docs/tree/master/docs/essentials @stevehoag, you'll see that the language independence topic still has a capital I.

**Comment by stevehoag** [comment]
@mairaw  okay, I just fixed it. Does the TOC need to be update as well, or is the TOC case-insensitive?

**Comment by mairaw** [comment]
I'd fix in the TOC too and in links like the one you have from the numerics topic.

**Comment by svick** [comment]
@stevehoag OK, added commit to remove apis/numerics.

**Comment by stevehoag** [comment]
That will be a major work item, since I also need to fix up filenames in numerous other topics that I wrote before we decided on the all lowercase standard.

@svick changes lgtm

**Comment by mairaw** [comment]
@cartermp @blackdwarf do we need to fix links when we rename the files to lowercase?

**Pull request merged**
