### PR TITLE
arrange mixed C# and VB code in order

### PR DESCRIPTION
**Pull request by YoungjaeKim**

### CODE REVIEW

**Comment by svick** [comment]
You're right that it doesn't make sense to mix the code like this.

But I think there's also no reason to split the code for each language into two blocks. Do you want to modify the code files ([default.xaml.cs](https://github.com/dotnet/docs/blob/master/samples/snippets/csharp/VS_Snippets_Wpf/EventOvwSupport/CSharp/default.xaml.cs) and [default.xaml.vb](https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_Wpf/EventOvwSupport/visualbasic/default.xaml.vb)) and the markdown file so that there's only one block for each language and add those changes to this PR?

**Comment by mairaw** [comment]
This is a result of changing publishing systems over time. This is what we had in the past:
https://msdn.microsoft.com/en-us/library/ms742806(v=vs.100).aspx#Adding and Implementing an Event Handler for a Routed Event

We'd add multiple snippets and the build system would add the ... for us in the middle. I agree with @svick's suggestion to just change the snippet tags in this case and have one snippet since the code block is empty. In cases where the code block isn't empty and we don't wanna show everything, then I'd just change to code inline.

**Review by mairaw — CHANGES_REQUESTED** [review]
@YoungjaeKim please let us know if you'd like to make the changes as suggested by @svick. If you can't, we can make the edits on your behalf. Just let us know. Thank you!

**Review by YoungjaeKim — COMMENTED** [review]
I edited cs and vb code files accordingly.

**Comment by svick** [comment]
You didn't put the VB change into this PR (it's in your `patch-3` branch, but not in `patch-1`, which is used by this PR).

And you also need to edit the markdown file, so that it does not include the B snippets anymore.

**Comment by mairaw** [comment]
Since this has been open for a while, I'll take a look at the changes still needed and make the edits so we can merge this.

**Review by mairaw — APPROVED** [review]
I think it looks good now. Thanks @YoungjaeKim. I'll file an issue to fix this throughout the docs.

**Pull request merged**
