### PR TITLE
Just re-writing to give more clarity

### PR DESCRIPTION
**Pull request by warnov**
In the current version there is a triple negation

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for contributing to the dotnet/docs repo, @warnov, and for improving the clarity of this topic. I apologize that it's taken us so long to respond to your PR. This is a topic that we've republished with permission from its original publisher, so we have to investigate whether we have the right to modify it. We'll respond again as soon as we find out.

**Comment by warnov** [comment]
Thanks a lot Ron for your answer. I'll understand if you aren't able to modify this article.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rpetrusha** [comment]
Unfortunately, @warnov, we're not able to modify the topic, so I'll have to close your PR. I do want to thank you for submitting it, though.

**Comment by svick** [comment]
@rpetrusha In that case, would it be possible to disable the Edit button on Framework Design Guidelines articles?

**Comment by rpetrusha** [comment]
I'll investigate, @svick.

**Comment by BillWagner** [comment]
@rpetrusha We can do this. We need to turn off the "open-to-public-contributors" flag for the appropriate directories in docfx.json.  I had done this for the C# language spec and VB language spec before the links worked correctly for dependent repos.  [Here is an example](https://github.com/dotnet/docs/commit/55b7907ef1f86fad0920e967d270422414970f93#diff-f14cdab6f1d762de4c71972b81dd008cL153)

**Pull request closed without merging**
