### PR TITLE
Update Xamarin.Android version to 8.0

### PR DESCRIPTION
**Pull request by JonDouglas**
# Title

Xamarin.Android has been renamed from 7.5 to 8.0 due to Android Oreo (Android 8.0) support.

## Summary

Xamarin.Android has recently bumped versions from 7.5 to 8.0 to align with Android 8.0 (Oreo)

## Details

Xamarin.Android has been bumped from 7.5 -> 8.0 in 15.4 preview 3. It will remain showing 7.5 in 15.4 preview 2 until preview 3 is released.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by mairaw** [comment]
@weshaggard we'd need to also update https://github.com/dotnet/standard/blob/master/docs/versions.md right? 

@JonDouglas do we need to add any special info to the .NET Standard topic about this version number change or do you think it's easy for xamarin developers to understand that?

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
>@weshaggard we'd need to also update https://github.com/dotnet/standard/blob/master/docs/versions.md right? 

Yes it would be good to update this for consistency.

**Comment by JonDouglas** [comment]
https://github.com/dotnet/standard/pull/488

Apologies, didn't know this was in two repositories.

**Review by mairaw — APPROVED** [review]
LGTM. But as I said, for customers using 7.5, will they easily know that the version number is changing or do we need this info somewhere?

And no need to apologize. You couldn't guess that!

**Comment by JonDouglas** [comment]
@mairaw I do not think anything else is needed. The chart is pretty straight-forward. I do not think any notes are needed as customers using Xamairn.Android 7.5 in the 15.4 preview 1 / preview 2 will be upgraded to 8.0 in 15.4 preview 3. 

There will be about a month starting today where users could potentially get confused. I would defer to your call whether it's important to make a note about that in this doc. I will be adding a note in the Xamarin.Android release notes regarding the bump in version numbers which developers can use as a reference. (i.e. 7.5 is also known as 8.0)

**Comment by mairaw** [comment]
Sounds good @JonDouglas! I think the release notes are enough then.  Thanks!

Our CI builds are having some issues today. I'll merge this as soon as I can validate everything is green.

**Pull request merged**
