### PR TITLE
Update breaking changes format

### LINKED ISSUE #21188: Header links useless
This consolidated page of breaking changes would be useful, but every same-text header on the page is assigned the same id.
This means all the header hyperlinks point to the first instance on the page.

Per HTML spec please make id attributes unique on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5971107-0c8c-13d3-b48a-96f9bf4ea6ea
* Version Independent ID: 802d3628-64eb-fb23-a258-af523b536bd2
* Content: [ASP.NET Core breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore)
* Content Source: [docs/core/compatibility/aspnetcore.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/aspnetcore.md)
* Product: **dotnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by gewarren**
- For .NET 5+ breaking changes, each change is an article in the TOC instead of an include file.
- This structure maintains the ability to lookup by either version or technology area.
- The [ApiPort tool](https://github.com/microsoft/dotnet-apiport) would need to be updated to work with this format, but it wouldn't have worked with the previous format either (e.g. it looked for H3s instead of H4s).

[Preview link](https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/?branch=pr-en-us-21664).

Fixes #21188.

### CODE REVIEW

**Comment by Youssef1313** [comment]
Filed https://github.com/microsoft/dotnet-apiport/issues/954 to the API port tool repository.

**Comment by gewarren** [comment]
> Filed [microsoft/dotnet-apiport#954](https://github.com/microsoft/dotnet-apiport/issues/954) to the API port tool repository.

Thank you @Youssef1313 !

**Review by BillWagner — APPROVED** [review]
This really looks great @gewarren 

I like the new format for describing breaking changes a lot.

**Comment by gewarren** [comment]
Thanks Bill! Will merge this now. What do you think about linking here from the [What's new in .NET 5.0 page](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five)?

**Pull request merged**
