### PR TITLE
Update value-types-table.md

### PR DESCRIPTION
**Pull request by hillmarcus**
Removed a typo causing an extra row to be in the type table

### CODE REVIEW

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Some of the table records has hyperlinks to redirect to its corresponding docs page, but others don't.
I suggest you add hyperlinks to those who don't already have.

**Comment by hillmarcus** [comment]
The ones that have links in the first column have pages in the `language-reference/keywords` folder, while those that don't have links are missing those pages. The links in the second column contain similar information only those link to the `language-reference/builtin-types` folder.

I'm not going to make any more changes for this pull request. Adding additional keyword pages should be another task for someone more involved in the project.

**Comment by Youssef1313** [comment]
I think it won't require adding any additional pages, I didn't search, but there should be a page somewhere in the docs about `byte` for example which don't have hyperlink, even if not in the `language-reference/keywords`. Anyway, I may add that change later if you're interested in it.

**Comment by pkulikov** [comment]
> there should be a page somewhere in the docs about `byte`

@Youssef1313 not anymore; PR #13054 has combined information about individual integral numeric types into one article, which is referenced in the table under consideration in the third column. So, I think missing hyperlinks are by design.

**Comment by BillWagner** [comment]
@hillmarcus @Youssef1313 Thanks for creating this, and the discussion.  As @pkulikov points out, you’re seeing the content during a time when some reorganization is happening.  [This project](https://github.com/dotnet/docs/projects/71) contains issues that maps out the proposed reorganization of the C# reference. 

There’s also more details in [this gist](https://gist.github.com/BillWagner/047cb97f6c0fe542d3a1299e994b2acd) for the entire project plan for an updated C# Guide.

As a result of some of these changes, the individual pages for many of the built in types are now consolidated (or in progress for that). 

Thanks for helping us improve!

**Review by BillWagner — APPROVED** [review]
Thanks for making this change @hillmarcus 
I'll :shipit: now.

Thanks for making your first contribution to docs! 🎆

**Pull request merged**
