### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by svick**

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-visual-studio?branch=pr-en-us-1045](https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-visual-studio?branch=pr-en-us-1045)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/type-providers/generating-fsharp-types-from-dbml?branch=pr-en-us-1045](https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/type-providers/generating-fsharp-types-from-dbml?branch=pr-en-us-1045)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1045](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1045)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201313384707-1045%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1045](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1045)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-visual-studio?branch=pr-en-us-1045](https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-visual-studio?branch=pr-en-us-1045)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/type-providers/generating-fsharp-types-from-dbml?branch=pr-en-us-1045](https://review.docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/type-providers/generating-fsharp-types-from-dbml?branch=pr-en-us-1045)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201553416463-1045%5Cworkflow_report.html).

**Comment by stevehoag** [comment]
Thanks for fixing these @svick! LGTM

**Review by mairaw — APPROVED** [review]
Thanks @svick!

**Pull request merged**
