### PR TITLE
Update LOC Snapshot from Live

### PR DESCRIPTION
**Pull request by v-alje**
## Summary

This pull request updates the LOC snapshot to the latest version of the content from live.

### CODE REVIEW

**Comment by v-alje** [comment]
@gewarren Is there someone who can resolve the merge conflict with this branch and merge live into it? It would be best if it could be reset to the status and content of the live branch.

**Comment by BillWagner** [comment]
Hi @v-alje 

Genevieve is out this week, and I can try to help.  How did you create this PR? I'm confused by the number of conflicts, and I'm not sure how these two branches diverged as much as they have.

**Comment by BillWagner** [comment]
> @BillWagner I just opened a pull request from live into release-loc-prod. If the branch can be deleted and recreated from live it would work as well. LOC just wants a snapshot of the latest version of live.

That's probably easiest (deleting this branch, and making a new release-loc-prod that matches the current live branch).

Do you want me to do that? (LMK, and I'll get it done today.

**Comment by v-alje** [comment]
@BillWagner Yes please.

**Comment by BillWagner** [comment]
closing per request.

**Comment by BillWagner** [comment]
@v-alje 

You should be all set. The `release-loc-prod` branch matches the current `live` branch now.

**Comment by v-alje** [comment]
@BillWagner Thank you!

**Pull request closed without merging**
