### PR TITLE
updated dotnet test command

### LINKED ISSUE #1472: Fix parameter names for dotnet test command
There are several argument names that have the incorrect name listed for this topic:
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-test

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #1472 

/cc @blackdwarf 

Related questions/comments:
1- do we need a topic specific for https://aka.ms/vstest-filtering that is not a super old blog post? 
2- help command says that configuration is Debug for most projects. What does `most` means here?
3- we probably need to add more info on how to use this command for beginner users

### CODE REVIEW

**Comment by blackdwarf** [comment]
@mairaw some answers:

* That would be very good
* `most` means what it means. It should mean "if you haven't changed it"
* Yes. 
*

**Comment by mairaw** [comment]
@blackdwarf  I did create an issue for question 1 (https://github.com/dotnet/docs/issues/1489). I won't be addressing that on this PR since we have a fallback plan for now. 
question 2 - I've changed the description on the topic because I think saying default for most project is not clear for customers. 
question 3 - I'll add a separate issue for that one.

Please let me know if my changes look accurate. Thanks!

**Comment by stevehoag** [comment]
LGTM :shipit:

**Comment by mairaw** [comment]
I've updated this to match RC4 version now. Removed the [--results-directory] option and replaced the sample with the current template from `dotnet new xunit`.

**Review by thesmithee — APPROVED** [review]

**Pull request merged**
