### PR TITLE
Standardize See Also section using bulleted lists

### PR DESCRIPTION
**Pull request by nemrism**
## Summary

- Use bulleted list in `See Also` section
- removed trailing spaces
- fixed minor markdown warnings

Contributes to #6923

### CODE REVIEW

**Comment by mairaw** [comment]
Thank you @nemrism for taking on this issue. I'll start reviewing this but I'll ask you not to add more files to this PR. Breaking down these large tasks in smaller chunks is usually easier for us. But I really appreciate your help on fixing this!

**Comment by mairaw** [comment]
I resolved a merge conflict here. So do a git pull to get the latest.

**Comment by mairaw** [comment]
Actually, I'll wait until you remove the WIP from the title to do my review.

**Comment by nemrism** [comment]
Ok @mairaw!
I'm currently getting through other sections without doing anything else on files than formatting the `See also` section.
Do you prefer that I commit the next chunks / folders in a new PR?

**Comment by mairaw** [comment]
Yes please @nemrism!

**Comment by nemrism** [comment]
@mairaw, removed WIP on this PR and created a new branch to continue on my fork
How many files should I target by PR?

**Review by mairaw — APPROVED** [review]
Looks great @nemrism. Thank you for doing this!

**Pull request merged**
