### PR TITLE
Delete unused images

### PR DESCRIPTION
**Pull request by Youssef1313**
@gewarren, FYI. (Related to #19777)

### CODE REVIEW

**Comment by Youssef1313** [comment]
Does the build detect if this breaks something?

**Comment by gewarren** [comment]
> Does the build detect if this breaks something?

Yes, build would flag a broken image link. How did you find these images?

**Comment by Youssef1313** [comment]
> How did you find these images?

@gewarren I wrote a small tool that gets the images from every subfolder, and searches if the image is referenced in any markdown or not.

**Review by nishanil — APPROVED** [review]
Looks good to me!

**Pull request merged**
