### PR TITLE
Documented serialization of value tuple types

### LINKED ISSUE #3019: ValueTuple documentation should discuss serialization
# ValueTuple documentation should discuss serialization

## General

The documentation should be revised to note that:

- .NET Standard, including 2.0, does not define serialization support for ValueTuples.
- ValueTuples are not serialized in .NET Core 1.x or the .NET Framework 4.7 and earlier.

@ViktorHofer

### PR DESCRIPTION
**Pull request by rpetrusha**
# Documented serialization of value tuple types

Fixes #3019 

## Suggested Reviewers

@ViktorHofer, @mairaw

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
I only checked one sentence but I expect that they are all the same. The information is very detailed, there is no room for guessing. Thanks!

I will reuse your explanation of when a .NET Standard type is serializable in future asks ;) I couldn't have explained it better.

**Comment by mairaw** [comment]
@rpetrusha aren't includes supported?

**Comment by rpetrusha** [comment]
@mairaw, I completely forgot about includes! But the text for each is slightly different -- each refers to the type being documented. That can't be included in an includes, can it?

**Review by BillWagner — APPROVED** [review]
This LGTM.  You can :shipit: when you are ready.

I created issue #3249 to add a 'How to' topic to show an example of getting the type object and checking the attribute.

**Comment by rpetrusha** [comment]
Thanks for creating the issue, @BillWagner; I've assigned it to myself and scheduled it for next month.

**Comment by mairaw** [comment]
If they're slightly different, then you can forget about my suggestion. 😄

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
Build failed. Closing and reopening to begin new build.

**Comment by mairaw** [comment]
Build failed on the portal. Starting again.

**Comment by mairaw** [comment]
One question somewhat related to this PR @ViktorHofer:
 https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization only lists the ValueTuple type but not its generic versions. Should we include those in the list there?

@rpetrusha this is good to merge now.

**Comment by ViktorHofer** [comment]
I removed the generic versions of ValueTuple and Tuple from the list intentionally as I wanted to shorten the list. If you think this might be misleading, feel free to add them back.

**Pull request merged**
