### PR TITLE
36). Add topic files 111 to 114

### PR DESCRIPTION
**Pull request by jameshkramer**
This PR is for user story #1576037.

It adds four article files, makes corresponding deletions from the C# and VB folders, and adds redirection entries.

Please merge #18259, #18299, #18325, #18413, #18439, and #18541 before merging this.

cc: @BillWagner @mairaw @tfosmark @marteeleigh

Contributes to #4728

### CODE REVIEW

**Comment by mairaw** [comment]
@jameshkramer can you resolve the merge conflicts here?

**Comment by jameshkramer** [comment]
GitHub does not allow me to resolve conflicts on this (button is grayed out).

**Comment by tfosmark** [comment]
@jameshkramer Please follow these instructions to resolve the conflicts via GitBash command line: https://review.docs.microsoft.com/en-us/help/contribute/resolve-merge-conflicts?branch=master#scenario-1---your-pull-request-has-a-merge-conflict

Thanks.

**Comment by mairaw** [comment]
Thanks @tfosmark! @jameshkramer let me know if you need help!

**Comment by jameshkramer** [comment]
@mairaw 

Thanks, Maira. Did you find some information somewhere about the what the conflicts are, or did you just guess about  #18724? Should I just merge locally with the current linq-to-xml, and push the results?

**Comment by mairaw** [comment]
Well, I had to resolved a bunch of conflicts on the linq-to-xml now because of that PR. For the changes that were related to that PR, I just ignored since we already simplified paths in the changes here.

**Review by BillWagner — APPROVED** [review]
This LGTM @jameshkramer 

I'll :shipit: now.

**Pull request merged**
