### PR TITLE
WIP Add migration docs for 2.2 and 3.0

### LINKED ISSUE #9259: Add migration doc from .NET Core 2.1 to 2.2
Need to define whether this is needed.

This is what we had for 2.1: https://docs.microsoft.com/en-us/dotnet/core/migration/20-21

@KathleenDollard @Andrew-MSFT @richlander can you comment on this one?

### LINKED ISSUE #14218: Add migration doc from .NET Core 2.2 to 3.1
Similar to what we had from 2.0 -> 2.1
https://docs.microsoft.com/en-us/dotnet/core/migration/20-21

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #14218 
Fixes #9259 

Creating the skeleton for the two topics. Need more information to finish this.

### CODE REVIEW

**Comment by wli3** [comment]
Here is DOTNET_SKIP_FIRST_TIME_EXPERIENCE related change. cc @KathleenDollard 

DOTNET_SKIP_FIRST_TIME_EXPERIENCE used to control many things including extracting package cache, disabling telemetry, disabling printing of welcome message, disabling aspnet certificate configuration, disabling global tools PATH configuration.

Started from 3.0.100 we separated the functionality of this flag to many smaller flag and stopped honoring it. The setup of extracting package cache is no longer needed. Disable telemetry is solely controlled by the existing flag DOTNET_CLI_TELEMETRY_OPTOUT=1. We shortened the welcome message and it will always shows the first time. Aspnet certificate configuration can be disabled by DOTNET_GENERATE_ASPNET_CERTIFICATE=0. Global tools PATH configuration can be disabled by DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=0

**Comment by KathleenDollard** [comment]
Maira, what Will said is correct and is the right info for docs. Here are a couple of edits and can you align the grammar in the bullets and anything else you see:

Prior to .NET Core 3.0.100, the .NET Core SDK used the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environmental variable to control many things including extracting package cache, disabling telemetry, disabling printing of welcome message, disabling aspnet certificate configuration, disabling global tools PATH configuration.

Started from 3.0.100 we separated the functionality of this flag to many smaller flag and stopped using the DOTNET_SKIP_FIRST_TIME_EXPERIENCE variable: 

- The setup of extracting package cache is no longer needed. 
- Disable telemetry is solely controlled by the existing flag DOTNET_CLI_TELEMETRY_OPTOUT=1.
- We shortened the welcome message and it will always shows the first time. 
- Aspnet certificate configuration can be disabled by DOTNET_GENERATE_ASPNET_CERTIFICATE=0. 
- Global tools PATH configuration can be disabled by DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=0

**Comment by mairaw** [comment]
Thanks, I'll add that info. Sorry I missed this earlier somehow.

**Comment by mairaw** [comment]
Closing this one since all I had was the skeleton topics. Someone will need to pick this up.

**Pull request closed without merging**
