### PR TITLE
Add note about image file execution options subkey

### LINKED ISSUE #7677: Need a troubleshooting guide for conditions that might prevent DPI Awareness changes in Visual Studio from working properly
If the dpiAwareness setting is present in the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\devenv.exe, then the DPI awareness transition in Visual Studio does not work properly (regardless of how the value is set). It seems that you need to explain that you need to remove this registry entry first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b74bf9-71c6-2559-66f7-2e17de0702ef
* Version Independent ID: 9ad214a4-3ae0-f7e6-bb89-86067d97059d
* Content: [Disable DPI-awareness in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio)
* Content Source: [docs/framework/winforms/disable-dpi-awareness-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/disable-dpi-awareness-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #7677

### CODE REVIEW

**Comment by gewarren** [comment]
@merriemcgaw Can you review the short troubleshooting section I added to address the GitHub issue 7677? https://review.docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio?branch=pr-en-us-8013#troubleshoot

**Review by merriemcgaw — APPROVED** [review]
Looks good to me.

**Review by rpetrusha — APPROVED** [review]
LGTM, @gewarren. You can merge when you're ready.

**Comment by gewarren** [comment]
@rpetrusha Thanks Ron!

**Pull request merged**
