### PR TITLE
fix: MD030/list-marker-space

### PR DESCRIPTION
**Pull request by nschonni**
Each commit contains the regex used for the updates. The last one is to manually fix remaining issues. Mainly orphan list markers

### CODE REVIEW

**Comment by mairaw** [comment]
@nschonni do you mind breaking this PR in smaller chunks? It will be hard to review such a large PR.

**Comment by nschonni** [comment]
@mairaw what were you thinking for the split? Each is one regex, but the first one is the one that contains the bulk of the changes

**Comment by mairaw** [comment]
Maybe each commit separately will be a bit easier?

**Comment by nschonni** [comment]
Ok, I'll try pulling out the first commit to it's own first, since that is probably the bulk of the noise. I'll push the other commits to a new PR

**Comment by nschonni** [comment]
I've split up the commits across the PRs. I can try to split up this large regex across a few commits if that helps

**Comment by nschonni** [comment]
@mairaw I tried splitting this by subfolder, but "framework" and "visual-basic" are still large

**Pull request closed without merging**
