### PR TITLE
Library guidance update - Dependencies

### PR DESCRIPTION
**Pull request by TylerBrinkley**
## Summary

Made language clearer.

### CODE REVIEW

**Comment by BillWagner** [comment]
Thanks for this, and all the other submissions @TylerBrinkley 

I reviewed this, and the original text is better. I'm closing this PR.  

If you disagree, give your thoughts in a comment, and we'll take another look.

**Comment by TylerBrinkley** [comment]
NuGet packages don't have application versions. @JamesNK thoughts?

**Comment by JamesNK** [comment]
Applicable is correct. Application was a typo.

Applicable is the language the NuGet docs use: https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#lowest-applicable-version

**Comment by mairaw** [comment]
Reopening then.

**Comment by BillWagner** [comment]
😿 My bad, and my apologies @TylerBrinkley  I read the change backwards this morning. 

I will approve this and :shipit: now.  

Thanks for contributing, and helping me see my earlier review mistake.

**Review by BillWagner — APPROVED** [review]

**Pull request merged**
