### PR TITLE
Improve minor syntax

### PR DESCRIPTION
**Pull request by johypark**
## Summary

After #20357, reading testing-library-with-visual-studio, and some C# docs,
I realized that I made a mistake in my previous pull request.
Now I know that most people and also docs prefer starting with a lower case for variables and with an upper case for classes.

So I fixed it again including UnitTest1.cs.
Sorry to confuse.

### CODE REVIEW

**Comment by tdykstra** [comment]
A common preference is to use language keywords when they are available, as your previous PR did.  I think we're fine with the previous changes.

**Comment by JohyPark** [comment]
I have read these documents: 
[Types (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/)
[Strings (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/)
[Why is “string” considered a simplified version of “String”?](https://stackoverflow.com/questions/32187486/why-is-string-considered-a-simplified-version-of-string)

**Comment by tdykstra** [comment]
There's no right or wrong answer here, but my preference is to keep the language keywords.

**Comment by JohyPark** [comment]
Thanks for the advice.

**Pull request closed without merging**
