### PR TITLE
Update DPI topic for VS 2019

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
LGTM. You can merge when the build completes successfully, @gewarren.

**Comment by gewarren** [comment]
@rpetrusha Thanks Ron! @OliaG can you review these updates for VS 2019 please? I assume this topic applies to VS 2019 too? https://review.docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio?branch=pr-en-us-11397#add-a-registry-entry

**Comment by gewarren** [comment]
Gentle ping for review.

**Comment by BillWagner** [comment]
@gewarren Ron had already approved this. Are you waiting for @OliaG ? I tagged her for review in case. In not, you can :shipit: when you are ready.

**Comment by gewarren** [comment]
Sorry yes, I was waiting for Olia. Thanks Bill!

**Review by OliaG — APPROVED** [review]
Looks great

**Comment by gewarren** [comment]
Thanks Olia!

**Pull request merged**
