### PR TITLE
fix: MD010/no-hard-tabs

### PR DESCRIPTION
**Pull request by nschonni**
- Remove Hard tabs
- Trim leading/trailing spaces
- tsql -> sql lanaguage blocks
- Escape <New ...>
- Disable inline for Antlr and tabs separate value lists code blocks

### CODE REVIEW

**Comment by BillWagner** [comment]
I reviewed this and I had one question:  The `sql` vs. `tsql` as the language identifier for SQL statements.  @mairaw do you know which is preferred? (Our style guide says `sql`, so we should update that if `tsql` is correct.)

**Comment by JRAlexander** [comment]
The ML.NET articles look fine.

**Comment by mairaw** [comment]
I've asked offline. I have the impression that sql is preferred and the only one truly supported (meaning, it will add the right colorization).

**Review by BillWagner — APPROVED** [review]
This LGTM @nschonni 

I'll :shipit: now.

**Pull request merged**
