### PR TITLE
typo: MD006/ul-start-left

### PR DESCRIPTION
**Pull request by nschonni**
- Consider starting bulleted lists at the beginning of the line
- Trim trailing/leading spaces
- Add colon before list

### CODE REVIEW

**Comment by BillWagner** [comment]
I defer to @mairaw I'm not sure on the H1 tags on the tab group headers. 

Other than that change, LGTM.

**Comment by mairaw** [comment]
I'm not sure either. Let me follow up offline.

**Comment by Thraka** [comment]
Tab groups are H1 style. I would remove that change from the PR

**Comment by nschonni** [comment]
OK, looks like Tabs are depricated https://docs.microsoft.com/en-us/contribute/validation-reference/tabbed-conceptual
I'll undo it and replace it with an inline markdownlint-disable comment

**Comment by mairaw** [comment]
They are deprecated but their current solution doesn't work for us, so we're not ready to move on.

It seems that using the levels should be ok.

**Comment by nschonni** [comment]
@mairaw do you want me to undo it or is it ok as-is?

**Comment by Thraka** [comment]
I would undo it as the general way to do it is a single #. If ### works, you a different style tab than other articles So if we had automation that changed all of the tabs into a new format it would probably not recognize ###

**Comment by nschonni** [comment]
Rebased and undid the tabs

**Pull request closed without merging**
