### PR TITLE
Make F# slices documentation more beginner friendly

### PR DESCRIPTION
**Pull request by luisquintanilla**
Make F# slices documentation more beginner friendly

- Add syntax explanation. (start/end conventions and `..` operator)

#21272 

[Preview Link](https://review.docs.microsoft.com/en-us/dotnet/fsharp/language-reference/slices?branch=pr-en-us-21659)

### CODE REVIEW

**Comment by duncanworthy** [comment]
@lucianodelucchi - new intro is definitely more beginner friendly

**Review by cartermp — COMMENTED** [review]
Intro is definitely more beginner-friendly now. Is this still WIP?

**Comment by luisquintanilla** [comment]
@cartermp. I just want to add a note and references to the `..` operator and syntax for slices. I'll do that later today. Once that's in, it should be good to go.

**Comment by luisquintanilla** [comment]
@cartermp This one's ready.

**Review by cartermp — APPROVED** [review]
Thanks!

**Pull request merged**
