### PR TITLE
Create overview article. Fixes #237

### LINKED ISSUE #237: Delegates: Write Overview Article
This is a sub-task for #63.

Write the Overview Article for delegates in C#.

### PR DESCRIPTION
**Pull request by BillWagner**
Fixes #237 
This should be merged after PR #246, as this text is based on that branch.

### CODE REVIEW

**Comment by cartermp** [comment]
You should add yourself as the author for this (and other articles).  Otherwise, LGTM.

**Comment by BillWagner** [comment]
@cartermp Done, on all articles in this series.

**Comment by cartermp** [comment]
@BillWagner mind rebasing?  I seem to have forgotten the rebase-for-clean-history pattern recently!

I'll merge once it's rebased.

**Comment by BillWagner** [comment]
@cartermp rebase done.

**Comment by cartermp** [comment]
:+1:

**Pull request merged**
