### PR TITLE
updating .net fx version

### PR DESCRIPTION
**Pull request by mairaw**
I've noticed that this topic hasn't been updated to reflect the launch of .NET 4.6.2.

/cc @richlander

### CODE REVIEW

**Comment by mairaw** [comment]
There was another topic mixing 4.6.1 and 4.6.2, I'm assuming it should all be 4.6.2. @cartermp

**Comment by cartermp** [comment]
LGTM!

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation?branch=pr-en-us-989)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.tasks.task?branch=pr-en-us-989)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.flowcontrol?branch=pr-en-us-989)

**Pull request merged**
