### PR TITLE
Linq to xml

### PR DESCRIPTION
**Pull request by jameshkramer**
@mairaw 

Just catching the branch up to master

### CODE REVIEW

**Comment by Thraka** [comment]
Is this branch needed for some reason?

**Comment by jameshkramer** [comment]
This branch is for [user story 1576037](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1576037). I was just catching it up to master prior to my making changes. I apologize if the PR is a waste of your time. I am new to the process. Advice is appreciated.

**Comment by mairaw** [comment]
I'll catch up to master manually. And then you can fetch upstream and do something like `git rebase upstream/linq-to-xml`

**Comment by mairaw** [comment]
Whenever you need to catch up with master, just let me know @jameshkramer. But you can see now that the branch is even with master: https://github.com/dotnet/docs/tree/linq-to-xml

**Comment by jameshkramer** [comment]
Thank you, @mairaw.

**Pull request merged**
