### PR TITLE
Commit to microservices ebook - Added alerts

### PR DESCRIPTION
**Pull request by erjain**
Add alerts to the Microservices eBook, explaining that each article is but an excerpt from the whole book. And provides an actionable link and thumbnail of the book.

### CODE REVIEW

**Comment by nishanil** [comment]
@erjain Looks good to me! I guess, the key takeaways page was missed out? Can you add it there too?

**Comment by erjain** [comment]
Hi @nishanil, I have updated the key takeaways.

**Review by nishanil — APPROVED** [review]
Great! Thanks. 
@IEvangelist  You good to merge?

**Comment by IEvangelist** [comment]
> Great! Thanks. @IEvangelist You good to merge?

This syntax is incorrect.

```md
[!INCLUDE [download-alert](..//includes/download-alert.md)]
```

It should be:

```md
[!INCLUDE [download-alert](../includes/download-alert.md)]
```

There is an extra slash.

**Comment by nishanil** [comment]
Ah, interesting. I checked the review site and it seemed to render fine. Let's fix it.

**Comment by erjain** [comment]
Hi @IEvangelist,  Thanks for the feedback. I have updated the files to remove the extra slash.

**Review by IEvangelist — APPROVED** [review]

**Pull request merged**
