### PR TITLE
Update using-on-windows-full-solution.md

### PR DESCRIPTION
**Pull request by indcoder**
The title explicitly mentions a complete .Net Core solution yet the first project it creates is a .Net Standard ¯\_(ツ)_/¯

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for submitting this PR, @indcoder. Your PR basically reverts the changes made in PR #3216, which changed the library project type from .NET Core to .NET Standard. The basic reason for that is the recommendation that developers target .NET Standard (so that the library is callable on all .NET implementations that support the standard) rather than .NET Core unless their library requires the functionality available in .NET Core but not available in .NET Standard. In the latter case, the library is usable only on .NET Core. 
The problem here, as your PR suggests, is that it's confusing; there's no indication why you'd be creating a .NET Standard project when you want to target .NET Core. My suggestion, rather than reverting the text, is to add a clarifying explanation, such as, "This creates a .NET Standard library that targets .NET Core as well as any other .NET implementation that supports version 2.0 of the .NET Standard.
Would you like to revise your PR to make that change?

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for contributing to the dotnet/docs repo and for opening this PR, @indcoder. I've left a comment for you to consider.

**Comment by mairaw** [comment]
@indcoder please let us know if you can make the changes requested by @rpetrusha. Otherwise, we'll create a new PR with the proposed changes.

**Comment by indcoder** [comment]
Sorry for the delay @rpetrusha @mairaw . Am travelling as part of the #dotnetconf recap meetups. Will return to base on 29th early morning. So will be doing the changes then.

**Comment by rpetrusha** [comment]
OK. Thanks for letting us know, @indcoder.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
Thanks, @indcoder. Your last change looks good, so I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

**Pull request merged**
