### PR TITLE
Create proj files and move deploy snippets

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for helping us improve here @Youssef1313 

I've reviewed the changes, and I'll :shipit: now.

Happy to have you back! 👋

**Comment by tdykstra** [comment]
@Youssef1313 If you're interested in doing more PRs that create project files, we have a need for them in the [samples/snippets folder of the dotnet-api-docs repo](https://github.com/dotnet/dotnet-api-docs/tree/master/samples/snippets). We're working on setting up CI builds now.  Also, I'm starting on an [issue to remove CAS types from all snippets that use them](https://github.com/dotnet/dotnet-api-docs/issues/837), so it would be a good test of the new CI system to verify that the CAS removal work doesn't break anything.

**Comment by Youssef1313** [comment]
@tdykstra I'd be glad to help. Should I start doing this folder by folder in dotnet-api-docs? How large PRs would you be expecting (50 files? 100 files?)?

**Comment by tdykstra** [comment]
Folder by folder sounds good, and I'd prioritize the C# snippets. The project file creation work doesn't have to be perfectly in sync with the CAS removal work.  The number of snippet files in question is > 1,000, and  I'm thinking of starting with 200 files per PR, adjusting up or down as I see how it goes.

Any snippets for the CAS types themselves (System.Security.Permissions namespace) can be ignored.

**Comment by Youssef1313** [comment]
It seems to be a big task. But I'll try to start soon :wink:

**Comment by tdykstra** [comment]
Yes, it's a very big task. You could limit it by waiting until my first PR removing CAS is merged, then start adding project files only for the changed snippets.

**Pull request merged**
