### PR TITLE
Regenerating compatibility diagnostic includes

### PR DESCRIPTION
**Pull request by conniey**
# Regenerating compatibility diagnostic includes

* Including changes from https://github.com/Microsoft/dotnet/pull/543
* Fixing resolution of docIds from System.Windows.Automation.AutomationElementIdentifiers

@rpetrusha Are these all the changes from .NET 4.7.1 too? Not much seems to have changed.

## Suggested Reviewers

@rpetrusha

### CODE REVIEW

**Comment by rpetrusha** [comment]
@conniey, there should be some additional changes. If nothing else, there were a number of topics for WCF that included "* Windows Communication Foundation"  as the category instead of "Windows Communication Foundation" -- that's what was causing duplicate categories.

**Comment by rpetrusha** [comment]
It strikes me that the issue is which branch is current, @conniey. The changes were in master -- that's the only branch that we should be working with, since I merged net471 into master.

**Review by rpetrusha — APPROVED** [review]
LGTM.

**Comment by conniey** [comment]
> If nothing else, there were a number of topics for WCF that included "* Windows Communication Foundation" as the category instead of "Windows Communication Foundation" -- that's what was causing duplicate categories.

Those were fixed in #3527

**Comment by rpetrusha** [comment]
@conniey, could you take a look at the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C25%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201710252112019665-3533%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9nwUxIoxMITFXie0mFtjQ144DnEYLKGL%2Fi2fk1klvvM%3D&st=2017-10-25T22%3A12%3A16Z&se=2017-11-25T22%3A17%3A16Z&sp=r)? I'll fix the ServiceBase.Run broken links, but I'm not sure why many of the others are broken?

**Comment by conniey** [comment]
@rpetrusha The latest [build warnings](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C25%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201710252236548165-3533%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WgCDJSm2ATwPdBlDKAtvTyoZpyucRH61vsw5abgcwII%3D&st=2017-10-25T23%3A28%3A06Z&se=2017-11-25T23%3A33%3A06Z&sp=r) only include the ServiceBase one.

**Pull request merged**
