### PR TITLE
typo: InteropServicxes.MarshalAs -> InteropServices.MarshalAsAttribute

### PR DESCRIPTION
**Pull request by nschonni**
## Summary

OpenBuild was failing from the typo. This change also isn't in master

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for submitting this fix, @nschonni. However, your PR targets Live rather than Master. Changing the target creates a merge conflict that is difficult to resolve. I'm going to close this PR. Would you mind submitting a new PR that targets Master?

**Comment by nschonni** [comment]
@rpetrusha the problem only exists in live because there was another PR that landed on live only.
Please reopen.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @nschonni I didn't realize that there was a divergence between live and master, which was caused, I'm sad to say, by my merging a PR that I didn't realize targeted live.

What we're going to do is bring the current content of live to master for this topic, since this entire paragraph diverges on live and master. We'll preserve the typo. After that, if you'd like, you can open a PR against master (or possibly reopen this PR and retarget it to master).

**Comment by nschonni** [comment]
@rpetrusha can I suggest you re-open this and change the target to `master` when you backport the fix.

**Comment by mairaw** [comment]
The problem is that live has a bunch of PRs that are not part of master so changing the base brings all of those. Might be better to create a new PR.

**Comment by nschonni** [comment]
@mairaw if you re-open this I can rebase and force push. If I force-push a closed PR it can't be re-opened

**Comment by mairaw** [comment]
I have created PR #9594 to fix this but I'll reopen and you can decide what to do.

**Comment by nschonni** [comment]
OK, I was just trying to avoid a second PR, but if you've already submitted it I'll close this. Thanks for re-opening though

**Pull request closed without merging**
