### PR TITLE
Remove redirected files

### LINKED ISSUE #1954: Review redirected files
We're getting some redirection warnings in our builds. The files that are being redirected need to be removed from the repo:

'W:\xoqc-s\docs/standard/base-types/alternation.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/anchors.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/backreference.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/backtracking.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/changing-formats.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/classes.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/compilation.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/composite-format.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/custom-datetime.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/custom-numeric.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/custom-timespan.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/define-custom.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/display-dates.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/display-milliseconds.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/enumeration-format.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/escapes.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/extract-day.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/extract-protocol.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/grouping.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/miscellaneous.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/object-model.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/options.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/pad-number.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/quantifiers.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/quick-ref.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/regex-behavior.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/regex-examples.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/roundtrip.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/scanning.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/standard-datetime.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/standard-numeric.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/standard-timespan.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/strip-characters.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/substitutions.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/thread-safety.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/base-types/verify-format.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/exceptions/exception-handling-fundamentals.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
'W:\xoqc-s\docs/standard/exceptions/exception-hierarchy.md' would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #1954 

@mairaw I trust the report is correct and removed the offending files. Let me know if you need additional checks before you merge this.

### CODE REVIEW

**Comment by mairaw** [comment]
I'm trusting that who did the redirects did that correctly 😄 but might be good to double check.

**Comment by GuardRex** [comment]
> I'm trusting that who did the redirects did that correctly

Yeah ... well tbh ... I don't feel good about throwing you under the bus if things go badly either! :grinning:

Let's **WIP** so I can take a closer look. I'll ping ya later on it.

**Comment by GuardRex** [comment]
scotty
"It's as I said, Mister Spock. Inventory registers every torpedo." - Montgomery 'Scotty' Scott (James Doohan) [Star Trek VI: The Undiscovered Country](http://www.paramount.com/movies/star-trek-vi-undiscovered-country) ©1991 [Paramount Pictures](http://www.paramount.com/)

All torpedos ... er ... redirect topics ... accounted for. We're good. :+1:

**Review by mairaw — APPROVED** [review]
Thanks @GuardRex!

**Pull request merged**
