### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
surface TLS
[Internal review URL](https://review.docs.microsoft.com/en-us/dotnet/framework/network-programming/index?branch=pr-en-us-4699)

### CODE REVIEW

**Comment by mairaw** [comment]
Generally the in this section is supposed to map to what's on the TOC. do you want to perhaps mention in the security entry or on the see also section instead?

**Comment by Rick-Anderson** [comment]
I moved it to see also. I came up with these two links  when I googled .net framework best practices or something like that.

**Review by mairaw — APPROVED** [review]
LGTM

**Comment by Rick-Anderson** [comment]
THis is what I googled
[.net framework network best practice](https://www.google.com/search?q=.net+framework+network+best+practice&oq=.net+framework+network+best+practice&aqs=chrome.0.69i59j69i60l3.5782j1j8&sourceid=chrome&ie=UTF-8)

**Comment by mairaw** [comment]
Build seemed stuck.

**Pull request merged**
