### PR TITLE
Updating CLI golden path documents for preview 3

### PR DESCRIPTION
**Pull request by bleroy**
# Title

Updating CLI golden path documents for preview 3.

## Summary

Two new documents are added that are updated versions of `/docs/core/tutorials/using-with-xplat-cli.md`. The tutorial is also split in two to isolate the core of the tutorial from more optional and advanced parts.

## Suggested Reviewers

@mairaw @blackdwarf @BillWagner @kendrahavens  @cartermp

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli-msbuild.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli-msbuild?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli-msbuild.md)
[docs/core/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli-msbuild-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli-msbuild-folders?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli-msbuild-folders.md)
[docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli.md)

<a name="docs/core/tutorials/using-with-xplat-cli-msbuild.md"></a>
### [docs/core/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli-msbuild.md)
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/deploying/index.md).



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611160307259292-1243%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli-msbuild.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli-msbuild?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli-msbuild.md)
[docs/core/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli-msbuild-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli-msbuild-folders?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli-msbuild-folders.md)
[docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli.md)

<a name="docs/core/tutorials/using-with-xplat-cli-msbuild.md"></a>
### [docs/core/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli-msbuild.md)
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/deploying/index.md).



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611160323308975-1243%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
I haven't had a chance to read these yet, but should this go to the cli-preview3 folder we're creating in PR #1233? The Core guide will stay with the Preview 2 content.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders?branch=pr-en-us-1243) | [Details](#user-content-docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md)
[docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/cli-preview3/tutorials/using-with-xplat-cli-msbuild?branch=pr-en-us-1243) | [Details](#user-content-docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md)
[docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli.md)

<a name="docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md"></a>
### [docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md)
 - **Line 300**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-test.md).

<a name="docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md"></a>
### [docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/docs/cli-preview3/sdk.md).
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/deploying/index.md).
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-run.md).
 - **Line 313**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tutorials/cli-console-app-tutorial-advanced.md).
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-build.md).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-restore.md).
 - **Line 39**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-new.md).


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611160605462451-1243%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/cli-preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-on-windows-vs-2017.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/cli-preview3/tutorials/using-on-windows-vs-2017?branch=pr-en-us-1243) | [Details](#user-content-docs/cli-preview3/tutorials/using-on-windows-vs-2017.md)
[docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders?branch=pr-en-us-1243) | [Details](#user-content-docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md)
[docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/cli-preview3/tutorials/using-with-xplat-cli-msbuild?branch=pr-en-us-1243) | [Details](#user-content-docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md)
[docs/cli-preview3/tutorials/using-on-windows-vs-2017-full-solution.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-on-windows-vs-2017-full-solution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/cli-preview3/tutorials/using-on-windows-vs-2017-full-solution?branch=pr-en-us-1243) | [Details](#user-content-docs/cli-preview3/tutorials/using-on-windows-vs-2017-full-solution.md)
[docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli.md)

<a name="docs/cli-preview3/tutorials/using-on-windows-vs-2017.md"></a>
### [docs/cli-preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-on-windows-vs-2017.md)
 - **Line 45**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tutorials/using-on-windows-vs-2017-full-solution).

<a name="docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md"></a>
### [docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild-folders.md)
 - **Line 300**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-test.md).

<a name="docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md"></a>
### [docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/cli-preview3/tutorials/using-with-xplat-cli-msbuild.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/docs/cli-preview3/sdk.md).
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/deploying/index.md).
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-run.md).
 - **Line 313**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tutorials/cli-console-app-tutorial-advanced.md).
 - **Line 118**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-build.md).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-restore.md).
 - **Line 39**: **[Warning]** Invalid file link:(~/docs/cli-preview3/tools/dotnet-new.md).



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C17%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611162356293494-1243%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-on-windows-vs-2017.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/using-on-windows-vs-2017?branch=pr-en-us-1243) | [Details](#user-content-docs/core/preview3/tutorials/using-on-windows-vs-2017.md)
[docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/using-on-windows-vs-2017-full-solution?branch=pr-en-us-1243) | [Details](#user-content-docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution.md)
[docs/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders?branch=pr-en-us-1243) | [Details](#user-content-docs/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders.md)
[docs/core/preview3/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-with-xplat-cli-msbuild.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tutorials/using-with-xplat-cli-msbuild?branch=pr-en-us-1243) | [Details](#user-content-docs/core/preview3/tutorials/using-with-xplat-cli-msbuild.md)
[docs/core/preview3/windows-prerequisites.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/windows-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/windows-prerequisites?branch=pr-en-us-1243) | [Details](#user-content-docs/core/preview3/windows-prerequisites.md)
[docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli?branch=pr-en-us-1243) | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli.md)

<a name="docs/core/preview3/tutorials/using-on-windows-vs-2017.md"></a>
### [docs/core/preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-on-windows-vs-2017.md)
 - **Line 45**: **[Warning]** Invalid file link:(~/docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution).






For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C17%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611170105263014-1243%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/preview3/tutorials/index.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/index.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/index.md)
[docs/core/preview3/tutorials/media/console-app-solution.png](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/media/console-app-solution.png) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/media/console-app-solution.png)
[docs/core/preview3/tutorials/media/new-project-console-app.png](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/media/new-project-console-app.png) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/media/new-project-console-app.png)
[docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/using-on-windows-vs-2017-full-solution.md)
[docs/core/preview3/tutorials/using-on-windows-vs-2017.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-on-windows-vs-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/using-on-windows-vs-2017.md)
[docs/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/using-with-xplat-cli-msbuild-folders.md)
[docs/core/preview3/tutorials/using-with-xplat-cli-msbuild.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/tutorials/using-with-xplat-cli-msbuild.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/tutorials/using-with-xplat-cli-msbuild.md)
[docs/core/preview3/windows-prerequisites.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/preview3/windows-prerequisites.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/preview3/windows-prerequisites.md)
[docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/core/tutorials/using-with-xplat-cli.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/core/tutorials/using-with-xplat-cli.md)
[docs/toc.md](https://github.com/dotnet/docs/blob/core-golden-path/docs/toc.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/toc.md)
[samples/core/console-apps/FibonacciBetterMsBuild/Fibonacci.csproj](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/FibonacciBetterMsBuild/Fibonacci.csproj) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/FibonacciBetterMsBuild/Fibonacci.csproj)
[samples/core/console-apps/FibonacciBetterMsBuild/FibonacciGenerator.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/FibonacciBetterMsBuild/FibonacciGenerator.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/FibonacciBetterMsBuild/FibonacciGenerator.cs)
[samples/core/console-apps/FibonacciBetterMsBuild/Program.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/FibonacciBetterMsBuild/Program.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/FibonacciBetterMsBuild/Program.cs)
[samples/core/console-apps/HelloMsBuild/Hello.csproj](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/HelloMsBuild/Hello.csproj) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/HelloMsBuild/Hello.csproj)
[samples/core/console-apps/HelloMsBuild/Program.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/HelloMsBuild/Program.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/HelloMsBuild/Program.cs)
[samples/core/console-apps/HelloMsBuild/README.md](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/HelloMsBuild/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/HelloMsBuild/README.md)
[samples/core/console-apps/NewTypesMsBuild/README.md](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/README.md)
[samples/core/console-apps/NewTypesMsBuild/src/NewTypes/NewTypes.csproj](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/src/NewTypes/NewTypes.csproj) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/src/NewTypes/NewTypes.csproj)
[samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/Cat.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/Cat.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/Cat.cs)
[samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/Dog.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/Dog.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/Dog.cs)
[samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/IPet.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/IPet.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Pets/IPet.cs)
[samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Program.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Program.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/src/NewTypes/Program.cs)
[samples/core/console-apps/NewTypesMsBuild/test/NewTypesTests/NewTypesTests.csproj](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/test/NewTypesTests/NewTypesTests.csproj) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/test/NewTypesTests/NewTypesTests.csproj)
[samples/core/console-apps/NewTypesMsBuild/test/NewTypesTests/PetTests.cs](https://github.com/dotnet/docs/blob/core-golden-path/samples/core/console-apps/NewTypesMsBuild/test/NewTypesTests/PetTests.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/core/console-apps/NewTypesMsBuild/test/NewTypesTests/PetTests.cs)

























For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C17%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611170136105569-1243%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
