### PR TITLE
Included net-5.0 specific updates for Blazor eBook

### PR DESCRIPTION
**Pull request by sughosneo**
This PR contains `.net5.0` related updates for the following pages : 

- `An introduction to Blazor for ASP.NET Web Forms developers`
- `Architecture comparison of ASP.NET Web Forms and Blazor`
- `Blazor app hosting models`
- `Project structure for Blazor apps`
- `App startup`
- `Work with data`
- `App configuration`
- `Security: Authentication and Authorization in ASP.NET Web Forms and Blazor`
- `Migrate from ASP.NET Web Forms to Blazor`

### CODE REVIEW

**Comment by sughosneo** [comment]
Please note, `Index` page is not yet modified. It will get updated once the other changes are approved.

**Comment by csharpfritz** [comment]
LGTM

**Comment by nishanil** [comment]
Thanks @csharpfritz ! @sughosneo You may want to update the Index page before we can merge this PR.

**Comment by sughosneo** [comment]
Thanks @csharpfritz and @nishanil 
 Index page has been updated now with changelog link. Please review.

**Review by nishanil — APPROVED** [review]

**Pull request merged**
