### PR TITLE
Experiment: CodeOwners

### PR DESCRIPTION
**Pull request by BillWagner**
Trying an experiment to see how we might use use the CODEOWNERS file to get reviews routed to the right person.

@mairaw @rpetrusha This experiment would work better if we had another ID or two participating. If you want to add a section each, we can learn more about how it works.

Note: I did not turn on any of the features that would block PRs unless an owner reviewed. I don't think that's necessary. I just want to see if it makes us more efficient reviewing PRs.

### CODE REVIEW

**Comment by rpetrusha** [comment]
I've added a couple of sections, @BillWager and @mairaw

**Comment by rpetrusha** [comment]
@BillWagner, does this need to be approved and merged?

**Comment by BillWagner** [comment]
@rpetrusha Yes, this needs to be approved and merged.  Then, as I understand, the suggestions will start showing up on new PRs (not on existing ones)

@mairaw Once you add anything you'd like, got ahead and review and merge.

**Review by rpetrusha — APPROVED** [review]
LGTM.

**Review by mairaw — APPROVED** [review]
Cool! Didn't know about this.

**Comment by rpetrusha** [comment]
I've added some entries for Maira and John, @BillWagner, so I'll merge now.

**Pull request merged**
