### PR TITLE
Updating Breaking Change includes to use home ~ links

### PR DESCRIPTION
**Pull request by conniey**
# Updating Breaking changes to use home links
**WIP**

There were some link warnings in #3520 that this PR should fix.
The build with the warnings is here: [Build Report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201710242302324929-3520%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8nWBmSJz%2BZRu0DrmyJ%2BRVL%2FU9XbYppFFxjzVAt1LBy4%3D&st=2017-10-24T23%3A54%3A24Z&se=2017-11-24T23%3A59%3A24Z&sp=r)

Also, some categories were shown twice. (ie. https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.0-4.7.1)

## Suggested Reviewers

@rpetrusha

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
@conniey, sorry, I was in such a hurry to merge that I didn't look at the broken links report. I'll approve and merge when this is finished after inspecting the report this time. The duplication of WCF still exists -- it's caused by an extra space between # and the category; I'll open a PR to remove it.

**Comment by conniey** [comment]
@rpetrusha I've updated the tool to trim the categories.. so it should be fixed and won't be a problem for existing docs in Microsoft/dotnet

**Comment by conniey** [comment]
@rpetrusha The output looks better and less of the text is being cut off. The reason for the text being cut off is that the code snippets are not wrapped in a table... so the longer a single line is, the more likely content is going to be cut off. (ie. https://review.docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.0-4.7.1?branch=pr-en-us-3527#aspnet)

One way to fix this is to make sure that the number of characters in a code snippet line are less than 100.

I will work on trying to maintain the spacing in the code snippet.

**Comment by rpetrusha** [comment]
The build has completed, @conniey, so I'm going to merge. There are some broken  links in the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C25%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201710251632106840-3527%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BYJrJo%2F1RmX%2FDFBXRZWvCBJoiIYSo0isHJtX9uYDahc%3D&st=2017-10-25T17%3A48%3A20Z&se=2017-11-25T17%3A53%3A20Z&sp=r), but we can handle those before submitting the next PR. I'll also open a PR to merge to live.

**Pull request merged**
