### PR TITLE
LinkFix docs (2021-10)

### PR DESCRIPTION
**Pull request by cmcclister**
This PR is the result of running a Link Repair script on the included content. This script is primarily being run to clean up links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes: 

 

- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 

- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 

- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 

  - This also includes cleanup of the appended query string for MSDN (redirectedfrom=MSDN). 

- Fixes articles that are redirected in `.openpublishing.redirection.json` and updates the link to the current final location (this has a lot of customer usability fixes). 

 

Please note the [Contributor Guide: Links](https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master) has been updated with the following link-type preference order: 

 

``` 

By order of preference, links hosted on Docs should be Relative if they are in the same repository and docset. If they are in a different docset, even if in the same repository, they should be Site Relative. Links to content hosted on Docs shouldn't use a complete URL, otherwise known as Fully Qualified Domain Names (FQDN). Using a complete URL from Docs to other content on Docs will cause that link to be non-functional in air-gap environments. 

```

### CODE REVIEW

**Comment by cmcclister** [comment]
@v-kents let me know if you can help me with the build errors. Thanks!

**Review by gewarren — CHANGES_REQUESTED** [review]
There were a bunch of comments I'd left in https://github.com/dotnet/docs/pull/26197, but for some reason that PR was closed without merging. Please incorporate all of those requested changes into this PR. Or, if it was closed by accident, you could just reopen that PR and then rerun the link script once it is merged.

**Comment by cmcclister** [comment]
#sign-off @v-kents I've made the requested changes, not sure how to resolve it here (still says change requested). cc @gewarren

**Review by IEvangelist — CHANGES_REQUESTED** [review]
Hi @v-kents and @cmcclister

There are several concerns that I raise with this automated PR that need to be addressed, and we also need the updates from @gewarren's feedback https://github.com/dotnet/docs/pull/26589#discussion_r734077107 to be incorporated.

**Pull request closed without merging**
