### PR TITLE
fix CLI command

### LINKED ISSUE #14833: Wrong switch for R2R images?
I'm not able to generate a R2R file with --self-contained true but /p:PublishSingleFile=true does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #14833

### CODE REVIEW

**Comment by mairaw** [comment]
@KathleenDollard can you please review this? Also, do you prefer if I'm explicit about the `--self-contained` option? If you set the runtime in the project file, I imagine you have to set the flag, right?

/cc @livarcocc @dsplaisted

**Comment by dsplaisted** [comment]
@nguerrera for how to enable `PublishReadyToRun`

**Review by rpetrusha — APPROVED** [review]
LGTM. I wonder, though, whether we should note that using `-r` by default creates a self-contained app and so doesn't require the `--self-contained` option.

**Comment by mairaw** [comment]
I had similar questioning but I was also trying to understand what happens when you define the runtime in the project instead. Otherwise, I could also just change the flag to not have that true value and it should work as well.

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
I think it might be worth a note. Being explicit still might not be clear because it might cause the reader to think to drop self contained when thy don't want it, but then find it is still self contained.

**Comment by mairaw** [comment]
Thanks @nguerrera. That's a good idea. And the implied `--self-contained` is only for when you supply the runtime via the command, correct?

**Comment by nguerrera** [comment]
Correct

**Comment by mairaw** [comment]
Finally got back to this one. I'll merge as soon as the build finishes successfully.

**Comment by Thraka** [comment]
Will this cause a merge conflict with #15354 because I moved *everything* around?

Also, please keep the numbers at 01, there are so many benefits to numbering in this way.

**Comment by Thraka** [comment]
@mairaw Let's close this one in favor of #15354. I incorporated the tweaks this one PR does

**Comment by mairaw** [comment]
No problem. Thanks Thraka.

**Pull request closed without merging**
