### PR TITLE
Update metadata and example

### PR DESCRIPTION
**Pull request by imba-tjd**
Summary:

* Add `dev_langs` to metadata
* Move snippets to file

Questions:

1. These files contain **quotation mark** in metadata while some others not. Shall I remove them?
2. `ms.topic: article` seems to be replaced by `ms.topic: conceptual`.

If so, `docs/styleguide/template.md` also needs minor updating.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by mairaw** [comment]
You're right @imba-tjd. I'll review the topics that are still using ms.topic article to remove them all in a separate PR.

**Comment by BillWagner** [comment]
@mairaw Can you look at this one? The conflicts are all in the metadata section, and it looks like the PR may have been caught in the recent changes you were making across many topics.

**Comment by mairaw** [comment]
@BillWagner yes they did. It should be fixed now.

**Comment by mairaw** [comment]
@meganbradley because I merged the master branch to this PR, the commit validation report is showing things that are not applicable to the PR itself.

**Review by mairaw — APPROVED** [review]
Thank you @imba-tjd for your contribution. Your changes should show up live within a day or so.

**Pull request merged**
