### PR TITLE
[WIP] Adding contextual (constraint) keyword 'unmanaged' 

### LINKED ISSUE #8673: Add contextual 'unmanaged' keyword
The `unmanaged` keyword (constraint) is not on the keywords list.

Example:
```
class ConcreteClass<T> where T : unmanaged
{

}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by hriaz17**
## Summary

I've added the unmanaged keyword under the contextual constraints section in the keywords list. Now I've started to work on the documentation for this keyword. I know it's a constraint on type parameters. 
I'm just looking for some examples or helpful links that would help me develop the documentation for this keyword. I'm also wondering how this word relates to 'unsafe' keyword?

Fixes #8673  (if available)

### CODE REVIEW

**Comment by pkulikov** [comment]
@harisriaz17 the current bits of docs about `unmanaged` constraint might help you:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#unmanaged-constraint

**Comment by rpetrusha** [comment]
@BillWagner, could you provide some guidance to @harisriaz17 as he begins work on this new topic?

**Comment by BillWagner** [comment]
Thanks for volunteering to create this content @harisriaz17 We really appreciate it. In addition to the references @pkulikov provided, the [speclet for the feature](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md) on the dotnet/csharplang repo provides more details.  The new article should include the following information:

1. An example of the syntax. Include that `unmanaged` is incompatible with `class` and implies `struct`.
1. Definition for "unmanaged" types (from the speclet)
1. A brief justification for the feature (also in the [speclet](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/blittable.md#motivation).
1. Links to generic class & method in the language spec.
1. links to the `where` generic constraint page.

**Comment by harisriaz17** [comment]
So it's been a long while (sorry for the delay) but I'm back to working on this PR. I've added plenty of new content to the documentation of this spec, and I think I'm nearly done, just deciding on the structure of the content.
@BillWagner in reference to your previous comment above, could you elaborate more on points 4 and 5?
In point 4, do you want me to update the unmanaged constraint spec with links to its generic implementation?.

Also with regards to the where generic constraint page in point 5, I'm not sure whether to place a link to it in unmanaged-constraint.md file or in the language spec for unmanaged constraint.......so please elaborate on that.

**Comment by BillWagner** [comment]
@harisriaz17 

For the generic types and methods link, I'd use [this anchor](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#constructed-types) which would translate into `~/_csharplang/spec/types.md#constructed-types`.

For the `where` link, I'd use `csharp/language-reference/keywords/where-generic-type-constraint.md`

Ping me again if you have further questions.

**Comment by BillWagner** [comment]
I'm closing this due to lack of response.  @harisriaz17 If you pick this up again, you can open a new PR or re-open this one.

**Pull request closed without merging**
