### PR TITLE
fsharp-6.md - What's new in F# 6.0

### PR DESCRIPTION
**Pull request by dsyme**
## Summary

Adds the What's New page for F# 6.0, work with @KathleenDollard

### CODE REVIEW

**Review by gewarren — COMMENTED** [review]
I was also wondering why F# 6 is written like that, but all the other referenced versions have ".0" appended to the version number. Is that intentional?

**Comment by dsyme** [comment]
Regarding F# 6 v F# 6.0 - it seems with .NET 5 we switched to whole numbers, and F# is now following this

**Review by luisquintanilla — COMMENTED** [review]
Looks great @dsyme. Added a few comments. Can't wait for the official release!

**Review by gewarren — APPROVED** [review]
Looks great, thanks.

[Preview](https://review.docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6?branch=pr-en-us-26497)

**Review by gewarren — COMMENTED** [review]
I left a few more comments for you to consider. Thanks!

**Review by gewarren — APPROVED** [review]

**Pull request merged**
