### PR TITLE
reorder entries

### PR DESCRIPTION
**Pull request by mairaw**
This has been in my backlog for a while. Lately, the entries in the redirect file have not been added in alphabetical order. So if I didn't mess this up, this fix this.

I've done this using @JamesNK Newtonsoft.JSON package 😉 

I also noticed a few bad/redundant redirects that I'll fix on a separate commit to make them easier to review

### CODE REVIEW

**Comment by mairaw** [comment]
Second commit updates the msdn links and fixes/updates some F# links @cartermp 
https://github.com/dotnet/docs/pull/9649/commits/4ae66f47c0287d3bcd965cf481a7cfedea1bfd05

**Comment by JamesNK** [comment]
Share the code for next time you want to sort the file :P

**Comment by mairaw** [comment]
I should. Just need to work a bit more on it before I can share. But your docs were helpful!

**Review by BillWagner — APPROVED** [review]
Sweet! 🍰 

You can :shipit: when ready.

**Pull request merged**
