### PR TITLE
add await finishedtask;

### PR DESCRIPTION
**Pull request by minsouk**
check this code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace CancelTest
{
    internal class Program
    {
        // case 1 nowait concurrent execution of main
        //static void Main(string[] args)
        //{
        //    var task = new Manager().Run();
        //    Console.WriteLine("main end");
        //    Console.ReadKey();
        //}

        // case 2 old wait
        //static void Main(string[] args)
        //{
        //    new Manager().Run().Wait();
        //    Console.WriteLine("main end");
        //    Console.ReadKey();
        //}

        // case 3 new wait
        //static async Task Main(string[] args)
        //{
        //    await new Manager().Run();
        //    Console.WriteLine("main end");
        //    Console.ReadKey();
        //}

        // case 4 wait polling 
        static void Main(string[] args)
        {
            var task = new Manager().Run();
            while (!task.Wait(50))
            {
                Console.Write(".");
            }
            Console.WriteLine("main end");
            Console.ReadKey();
        }

        internal class Manager
        {
            CancellationTokenSource tokenSource = new CancellationTokenSource();

            public async Task Run()
            {
                List<Task> tasks = new List<Task>();

                CancellationToken token = tokenSource.Token;
                var w1 = new Worker1(token);
                var w2 = new Worker2(token);

                var t1 = w1.DoWork(iteration: 10, errorPosition: null);
                tasks.Add(t1);

                var t2 = w2.DoWork(iteration: 10, errorPosition: 2);
                tasks.Add(t2);

                try
                {

                    // case 1 
                    ////////////////////////////////////////////////////
                    ///By waiting until the end of t1 with no error, the entire program waits even though t2 had an error first.
                    //await t1;
                    //await t2;

                    // case 2
                    ////////////////////////////////////////////////////
                    ///As I waited for t2 with an error first, I was lucky to recognize the error first. But no one can make an error first.
                    //await t2;
                    //await t1;

                    // case 3
                    ////////////////////////////////////////////////////
                    ///All tasks must be terminated to know if there was an error. It is inefficient if there is no error in any of the tasks.
                    //// not recommended 
                    ////Task.WaitAll(tasks.ToArray());
                    // recommended 
                    //await Task.WhenAll(tasks.ToArray());    

                    // case 4
                    ////////////////////////////////////////////////////
                    /// Can't recognize the error.
                    //while (tasks.Count > 0)
                    //{
                    //    Task finishedTask = await Task.WhenAny(tasks.ToArray());
                    //    if (finishedTask == t1)
                    //    {
                    //        Console.WriteLine("t1 completed");
                    //    }
                    //    else if (finishedTask == t2)
                    //    {
                    //        Console.WriteLine("t2 completed");
                    //    }
                    //    //await finishedTask;
                    //    tasks.Remove(finishedTask);
                    //}

                    // case 5
                    ////////////////////////////////////////////////////
                    ///If an error occurs gracefully, you can immediately acknowledge it and shut down the whole thing.
                    while (tasks.Count > 0)
                    {
                        Task finishedTask = await Task.WhenAny(tasks.ToArray());
                        if (finishedTask == t1)
                        {
                            Console.WriteLine("t1 completed");
                        }
                        else if (finishedTask == t2)
                        {
                            Console.WriteLine("t2 completed");
                        }
                        /////////////////////////////////////////////////////////// do not delete for exception !
                        await finishedTask;
                        /////////////////////////////////////////////////////////// 
                        tasks.Remove(finishedTask);
                    }

                    Console.WriteLine("t1 t2 normal completed");
                }
                catch (AggregateException aex)
                {
                    foreach (var a in aex.InnerExceptions)
                    {
                        Console.WriteLine($@"inner Exception : {a.Message}");
                    }
                    tokenSource.Cancel();
                }
                catch (Exception ex)
                {
                    Console.WriteLine($@"Exception : {ex.Message}");
                    tokenSource.Cancel();
                }
                finally
                {
                    tokenSource.Dispose();
                }

                Console.WriteLine("t1 t2 completed");
            }
        }

        internal class Worker1
        {
            CancellationToken ct;
            public Worker1(CancellationToken ct)
            {
                this.ct = ct;
            }
            public Task DoWork(int iteration, int? errorPosition)
            {
                var task = Task.Run(async () =>
                {
                    for (int i = 0; i < iteration; i++)
                    {
                        if (ct.IsCancellationRequested)
                        {
                            Console.WriteLine($@"{GetType()} cancel requested");
                            break;
                        }
                        if (i == errorPosition)
                            throw new Exception("simuation exception w1");

                        await Task.Delay(500);
                        Console.WriteLine("w1");
                    }
                }, ct);
                return task;
            }
        }

        internal class Worker2
        {
            CancellationToken ct;
            public Worker2(CancellationToken ct)
            {
                this.ct = ct;
            }
            public Task DoWork(int iteration, int? errorPosition)
            {
                var task = Task.Run(async () =>
                {
                    for (int i = 0; i < iteration; i++)
                    {
                        if (ct.IsCancellationRequested)
                        {
                            Console.WriteLine($@"{GetType()} cancel requested");
                            break;
                        }
                        if (i == errorPosition)
                            throw new Exception("simuation exception w2");
                        await Task.Delay(500);
                        Console.WriteLine("w2");
                    }
                }, ct);
                return task;
            }
        }

    }
}

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by IEvangelist** [comment]
Thanks for the PR @minsouk, however; this code is unnecessary as the `Task.WhenAny` returns a `Task`, it has already finished, thus it doesn't need to be awaited again.

**Comment by minsouk** [comment]
I know the part you mentioned. If so, can you guide me how to check exception in main? Review the test code.

**Comment by minsouk** [comment]
Task finishedTask = await Task.WhenAny(tasks.ToArray());
Here, await handles waiting asynchronously.

await finishedTask;
Here, await waits for the task to be completed, but because it is a task that has already been completed due to the nature of WhenAny, it is not affected by execution time and is only needed for exception handling. Please check again.
Therefore, please do not delete await finishedTask for handling exceptions in the future.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
namespace Asynchronious
{

    class Program
    {
        public static void Main(String[] args)
        {
            // Exception can be handled *********************************
            // new Test().Call1();

            // Exception cannot be handled ********************************
            new Test().Call2();

            Console.Write("End");
            Console.ReadLine();
        }
    }

    class Test
    {
        public Task ShowAsync()
        {
            return Task.Run(async () =>
            {
                Console.WriteLine("sub function");
                await Task.Delay(1000);
                throw new Exception("Exception");
            });
        }

        public async void Call1()
        {
            List<Task> tasks = new List<Task>();   
            tasks.Add(ShowAsync());   
            try
            {
                Task task = await Task.WhenAny(tasks.ToArray());
                await task; 
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        public async void Call2()
        {
            List<Task> tasks = new List<Task>();
            tasks.Add(ShowAsync());
            try
            {
                Task task = await Task.WhenAny(tasks.ToArray());
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

    }
}

**Comment by minsouk** [comment]
// here is full test code


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AwaitException
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;

    namespace AsyncBreakfast
    {
        // These classes are intentionally empty for the purpose of this example. They are simply marker classes for the purpose of demonstration, contain no properties, and serve no other purpose.
        internal class Bacon { }
        internal class Coffee { }
        internal class Egg { }
        internal class Juice { }
        internal class Toast { }

        class Program
        {
            static async Task Main(string[] args)
            {
                Coffee cup = PourCoffee();
                Console.WriteLine("coffee is ready");
                try
                {
                    var eggsTask = FryEggsAsync(2);
                    var baconTask = FryBaconAsync(3);
                    var toastTask = MakeToastWithButterAndJamAsync(0);

                    var breakfastTasks = new List<Task> { eggsTask, baconTask, toastTask };
                    while (breakfastTasks.Count > 0)
                    {
                        // await to get finished tasks from the Task Collection
                        Task finishedTask = await Task.WhenAny(breakfastTasks);
                        if (finishedTask == eggsTask)
                        {
                            Console.WriteLine("eggs are ready");
                        }
                        else if (finishedTask == baconTask)
                        {
                            Console.WriteLine("bacon is ready");
                        }
                        else if (finishedTask == toastTask)
                        {
                            Console.WriteLine("toast is ready");
                        }
                        // Check if the actual operation is completed without exception
                        await finishedTask;
                        breakfastTasks.Remove(finishedTask);
                    }

                    Juice oj = PourOJ();
                    Console.WriteLine("oj is ready");
                    Console.WriteLine("Breakfast is ready!");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($@"ex {ex.Message}");
                }
            }

            static async Task<Toast> MakeToastWithButterAndJamAsync(int number)
            {
               
               var  toast = await ToastBreadAsync(number);
                    ApplyButter(toast);
                    ApplyJam(toast);
                
                return toast; 
            }

            private static Juice PourOJ()
            {
                Console.WriteLine("Pouring orange juice");
                return new Juice();
            }

            private static void ApplyJam(Toast toast) =>
                Console.WriteLine("Putting jam on the toast");

            private static void ApplyButter(Toast toast) =>
                Console.WriteLine("Putting butter on the toast");

            private static async Task<Toast> ToastBreadAsync(int slices)
            {
                double s = 1 / slices;
                Console.WriteLine($@"슬라이스를 {s} 조각으로 나누었습니다. ");
                for (int slice = 0; slice < slices; slice++)
                {
                    Console.WriteLine("Putting a slice of bread in the toaster");
                }

                await Task.Delay(3000);
                Console.WriteLine("Remove toast from toaster");
                return new Toast();
            }

            private static async Task<Bacon> FryBaconAsync(int slices)
            {
                Console.WriteLine($"putting {slices} slices of bacon in the pan");
                Console.WriteLine("cooking first side of bacon...");
                await Task.Delay(3000);
                for (int slice = 0; slice < slices; slice++)
                {
                    Console.WriteLine("flipping a slice of bacon");
                }
                Console.WriteLine("cooking the second side of bacon...");
                await Task.Delay(3000);
                Console.WriteLine("Put bacon on plate");

                return new Bacon();
            }

            private static async Task<Egg> FryEggsAsync(int howMany)
            {
                Console.WriteLine("Warming the egg pan...");
                await Task.Delay(3000);
                Console.WriteLine($"cracking {howMany} eggs");
                Console.WriteLine("cooking the eggs ...");
                await Task.Delay(3000);
                Console.WriteLine("Put eggs on plate");

                return new Egg();
            }

            private static Coffee PourCoffee()
            {
                Console.WriteLine("Pouring coffee");
                return new Coffee();
            }
        }
    }
}

**Comment by minsouk** [comment]
> Thanks for the PR @minsouk, however; this code is unnecessary as the `Task.WhenAny` returns a `Task`, it has already finished, thus it doesn't need to be awaited again. I'll let @BillWagner close this one.

check my comment. 
Task finishedTask = await Task.WhenAny(tasks.ToArray());
Here, "await" Asynchronously wait for tasks to be retrieved from the Task Collection

await finishedTask;
Here, "await" waits for the task to be completed, it is not affected by execution time and is only needed for exception handling. Please check again. Therefore, please do not delete await finishedTask for handling exceptions in the future.

**Review by BillWagner — APPROVED** [review]
Thanks for updating this @minsouk 

Yes, the `finishedTask` has completed or faulted, so the `await` will complete synchronously. The `await` will extract the first exception in the `AggregateException` stored in a `Faulted` Task. This is a great change for correct error handling.

I'll :shipit: now.

**Comment by minsouk** [comment]
Please edit this page as well.
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Pull request merged**
