### PR TITLE
Added linq projection samples for fix #151

### LINKED ISSUE #151: C# LINQ Samples -  Projection Operators
Add LINQ samples for projection operators #90

### PR DESCRIPTION
**Pull request by matthewreily**
Adding C# linq samples for projection operators.  fix #151 that corresponds to parent task #90
cc @BethMassi @cartermp

### CODE REVIEW

**Comment by BethMassi** [comment]
@matthewreily Are you using ReSharper by any chance? I found some unnecessary @ signs in a few of the code examples. I recall R# uses that by convention, but in this case it's unnecessary and is clearer without it (especially for newbies).

**Comment by matthewreily** [comment]
guilty :) and I agree with making it clearer

**Comment by matthewreily** [comment]
fixed and squashed

**Comment by BethMassi** [comment]
LGTM

**Pull request merged**
