### PR TITLE
Standardize See also section to use bulleted list

### PR DESCRIPTION
**Pull request by nemrism**
## Summary

* use bulleted lists in `See also` section
* use sentence case in heading
* fix minor Markdown warnings
* applied to whole /docs/fsharp folders

Contributes to #6923

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thank you so much @nemrism! Another great PR!

**Comment by nemrism** [comment]
You're welcome @mairaw 
Actually, this PR only concerns the F# Guide area

**Comment by nemrism** [comment]
My bad! It wasn't supposed to be part of that commit.

**Comment by mairaw** [comment]
Don’t worry!

**Comment by nemrism** [comment]
Be happy 👍

**Pull request merged**
