### PR TITLE
Add link for Best-Fit mapping definitions

### PR DESCRIPTION
**Pull request by srutzky**
While true that not _all_ Best-Fit mappings are documented, several of them are documented, and those mapping files exist on the Unicode.org website.

I created a Note box with this info. I also moved the fragment about them not being documented out of the paragraph describing how they vary and into that new Note box since that particular detail was not truly on topic for that paragraph.

**PLEASE NOTE:** since these mappings are stored on the Unicode.org website and not within Microsoft's direct control, it would be reasonable to question the accuracy of these mapping files (at least with regards to Microsoft's implementation of the Unicode specification, which isn't always "complete", just like any vendors implementation of JavaScript / CSS / etc). To that end, I tested one of them (for Code Page 1252 -- Latin1) within SQL Server and found a 100% agreement between the mapping file and the behavior within SQL Server. This is documented in the following answer of mine on DBA.StackExchange, which includes a link to my test script on PasteBin if you want to run the test yourself:

[Automatic Translation when Converting Unicode to non-Unicode / NVARCHAR to VARCHAR](https://dba.stackexchange.com/a/122375/30859)

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @srutzky! @rpetrusha can you review this one? In general, it looks good to me, but I wanted you to double check.

Also, not 100% sure that two consecutive notes help with the flow of the text:
image

**Comment by srutzky** [comment]
@mairaw Yer welcome, and thanks 😄  . Regarding the two notes, back-to-back, I did that because:

1. They were too different of subject matter to be combined.
1. I had checked several other pages (though mostly in the SQL Server area) and found other instances of back-to-back notes.
1. There didn't seem to be much better placement for them, at least not the second one -- the one I added. Maybe the first could move, but didn't seem all that bad where it was (it's original placement).

But if you want to move the first one, that's up to you.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for adding this note, @srutzky. This is a significant improvement for the fallback section. I agree with @mairaw, though, that back-to-back notes impedes the flow of the text, although I know that there are many instances of it in our docs. But it strikes me that the text reads much better if your note follows, rather than precedes, the paragraph that begins, "Best-fit strategies vary for different code pages..." Would you mind moving it? Or if you'd prefer, we can move it for you.

**Comment by srutzky** [comment]
@rpetrusha (and @mairaw). You're welcome. And not a problem on making that change. It's not my documentation, so it doesn't _need_ to look a certain way for me. My main concern is just the accuracy of the info 😄 . So, I have made the requested change. Please review.

ALSO, I meant to add a note in my original comment regarding proof that the mapping files, or at least one of them, are trustworthy. I have updated the original comment (for visibility to new readers who likely won't read down this far into the comments) to include that info.

**Comment by rpetrusha** [comment]
Thanks for making this additional change, @srutzky. We'll merge your PR now. Your changes should appear live on docs.microsoft.com in the next day or two.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
