### PR TITLE
fix: Replace strong with markdown syntax

### PR DESCRIPTION
**Pull request by nschonni**
Replace some closing BR tags as well

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by nschonni** [comment]
Rebased and fixed a few stuck ".The" since that was a merge conflict I ran into

**Comment by nschonni** [comment]
@mairaw anything else for this one?

**Comment by nschonni** [comment]
@rpetrusha do you want to take a look at this?

**Comment by nschonni** [comment]
@Thraka can you take a look at this?

**Review by mairaw — APPROVED** [review]
LGTM. Apologies for the delay here.

**Pull request merged**
