### PR TITLE
Improvements to trim warnings description and fixes

### PR DESCRIPTION
**Pull request by vitek-karas**
## Summary

Improves the description of trim warnings and adds several new recommendations.
* Frame it around types of warnings, not the specific code used to handle such warnings
* Add a subsection on how to mark functionality as incompatible
  * Recommendations on how to produce a good warning message
  * Recommendation to use const string fields to avoid message duplication
* Suppressions
  * Move them to the end - should be the last resort
  * Format the text as a warning to make it very clear that suppressions are potentially dangerous
  * Make it stand out that `UnconditionalSuppressMessage` must be used over the other methods of suppressing warnings
  * Add a recommendation on refactoring suppressions to only a small piece of code

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/deploying/trimming/fixing-warnings.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/fixing-warnings.md) | [Introduction to trim warnings](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/fixing-warnings?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2067.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2067.md) | [IL2067: 'target parameter' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to 'target method'. The parameter 'source parameter' of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2067?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2068.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2068.md) | ["IL2068: 'target method' method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The parameter 'source parameter' of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to."](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2068?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2069.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2069.md) | [IL2069: Value stored in field 'target field' does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The parameter 'source parameter' of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2069?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2070.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2070.md) | [docs/core/deploying/trimming/trim-warnings/il2070](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2070?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2072.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2072.md) | [IL2072: 'target parameter' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to 'target method'. The return value of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2072?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2073.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2073.md) | ["IL2073: 'target method' method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The return value of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to."](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2073?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2074.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2074.md) | [IL2074: Value stored in field 'target field' does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The return value of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2074?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2075.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2075.md) | [docs/core/deploying/trimming/trim-warnings/il2075](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2075?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2077.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2077.md) | [IL2077: 'target parameter' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to 'target method'. The field 'source field' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2077?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2078.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2078.md) | ["IL2078: 'target method' method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The field 'source field' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to."](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2078?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2079.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2079.md) | [IL2079: Value stored in field 'target field' does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The field 'source field' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2079?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2080.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2080.md) | [docs/core/deploying/trimming/trim-warnings/il2080](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2080?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2082.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2082.md) | [IL2082: 'target parameter' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to 'target method'. The implicit 'this' argument of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2082?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2083.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2083.md) | ["IL2083: 'target method' method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The implicit 'this' argument of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to."](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2083?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2084.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2084.md) | [IL2084: Value stored in field 'target field' does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The implicit 'this' argument of method 'source method' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2084?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2085.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2085.md) | [docs/core/deploying/trimming/trim-warnings/il2085](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2085?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2087.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2087.md) | [IL2087: 'target parameter' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to 'target method'. The generic parameter 'source generic parameter' of 'source method or type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2087?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2088.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2088.md) | ["IL2088: 'target method' method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The generic parameter 'source generic parameter' of 'source method or type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to."](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2088?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2089.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2089.md) | [IL2089: Value stored in field 'target field' does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The generic parameter 'source generic parameter' of 'source method or type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2089?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2090.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2090.md) | [docs/core/deploying/trimming/trim-warnings/il2090](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2090?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2091.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2091.md) | [IL2091: 'target generic parameter' generic argument does not satisfy 'DynamicallyAccessedMembersAttribute' in 'target method or type'. The generic parameter 'source target parameter' of 'source method or type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2091?branch=pr-en-us-37514) |
| [docs/core/deploying/trimming/trim-warnings/il2117.md](https://github.com/dotnet/docs/blob/c9238a440a97362b40b521a3b6ec0cb2c4d615b7/docs/core/deploying/trimming/trim-warnings/il2117.md) | ["IL2116: Methods 'method1' and 'method2' are both associated with lambda or local function 'method'. This is currently unsupported and may lead to incorrectly reported warnings."](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2117?branch=pr-en-us-37514) |

</details>

### CODE REVIEW

**Review by sbomer — APPROVED** [review]
Changes LGTM overall, thanks!

My main concern (true even before this PR) is the duplication between this article and https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0. I think we should either merge them into one article, or keep this one short and sweet (make it read like a quick intro), and move out some of the details like the recommendation to use a const string into the other article. Thoughts? cc @agocke

**Comment by vitek-karas** [comment]
> My main concern (true even before this PR) is the duplication between this article and https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0. I think we should either merge them into one article, or keep this one short and sweet (make it read like a quick intro), and move out some of the details like the recommendation to use a const string into the other article. 

I definitely agree that there's duplication. Also, this page is now getting pretty long and might be a good idea to break it anyway. And finally - personally, I think a better structure would be to talk about the process of making something trim compatible by discussing code patterns which are problematic and how to go about solving those. Currently the docs are mostly written as if "just go fix a few warnings, no big deal", which I think is not a good approach in setting the right expectations.

In any case I'm very interested in what you think would be a good approach - and I plan to work on this more.

The other problem which we need to address is "the sample". We should add a proper full sample and refer to it from the docs. By "proper" I mean mostly that:
* A full project which actually builds - so that it's verified by CI and can be "copy-pasted" where applicable
* Some believable problem to solve and the naming which results from that
* Potentially have multiple versions of the project to showcase the "progress" in making code trim compatible (before/after kind of thing).

**Comment by vitek-karas** [comment]
@adegeo is there some other requirement to meet for this to get merged? I assume I need a review from one of the editors, right?

**Comment by adegeo** [comment]
I'll run it through the editing tools today.

**Comment by adegeo** [comment]
@vitek-karas I ran it through our tools then hand edited it here and there for clarity. Please review it to make sure I didn't mess anything up, and then we can merge it through.

**Review by adegeo — APPROVED** [review]

**Comment by vitek-karas** [comment]
Thanks a lot @adegeo  - I only made one small change, as the original felt weird to me.

**Review by agocke — APPROVED** [review]
LGTM

**Pull request merged**
