### PR TITLE
Porting base types content from MSDN

### LINKED ISSUE #217: Porting .NET MSDN docs to Core - Base Types
We need to port the relevant content from MSDN that applies to .NET Core.

The base types docs are still applicable to .NET Core. This is the starting point for base types:
https://msdn.microsoft.com/en-us/library/7wchwf6k(v=vs.110).aspx

### PR DESCRIPTION
**Pull request by stevehoag**
Previously reviewed; moving in stages (59 total topics) Fixes #217

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.security.accesscontrol?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.io.bufferedstream?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.datetimeconverter?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.schema.columnattribute?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.xml.xpath.xpathitem?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.ilgenerator?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.xml.xsl?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.synchronizationlockexception?branch=pr-en-us-1016)

**Comment by stevehoag** [comment]
Last commit didn't build - closing and reopening to trigger another build.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.diagnostics.debug?branch=pr-en-us-1016)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.ireflect?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.ireflect?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.ireflectabletype?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.ireflectabletype?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.localvariableinfo?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.localvariableinfo?branch=pr-en-us-1016)  
  Please see 3488 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:System.Text.DecoderFallbackBuffer.Fallback(System.Byte[],System.Int32)(System.Byte[],System.Int32)" sourcefile="docs/standard/basetypes/characterencoding.md" sourcestartlinenumber="1153" sourceendlinenumber="1153">DecoderFallbackBuffer.Fallback</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609142041448657-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.tuple-6?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.tuple-6?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.tuple-7?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.tuple-7?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.tuple-8?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.tuple-8?branch=pr-en-us-1016)  
  Please see 3094 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:System.String.Format(System.IFormatProvider, System.String, System.Object)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="31" sourceendlinenumber="31">String.Format(IFormatProvider, String, Object[])</a>", "<a href="xref:System.ICustomFormatter.Format(System.String, System.Object, System.IFormatProvider)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="39" sourceendlinenumber="39">ICustomFormatter.Format</a>", "<a href="xref:System.String.Format(System.IFormatProvider, System.String, System.Object)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="39" sourceendlinenumber="39">String.Format(IFormatProvider, String, Object[])</a>", "<a href="xref:System.String.Format(System.IFormatProvider, System.String, System.Object)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="53" sourceendlinenumber="53">String.Format(IFormatProvider, String, Object[])</a>", "<a href="xref:System.StringSystem.String.Format(System.IFormatProvider, System.String, System.Object)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="199" sourceendlinenumber="199">String.Format(IFormatProvider, String, Object[])</a>", "<a href="xref:System.StringSystem.String.Format(System.IFormatProvider, System.String, System.Object)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="201" sourceendlinenumber="201">String.Format(IFormatProvider, String, Object[])</a>", "<a href="xref:System.ICustomFormatter.Format(System.String, System.Object, System.IFormatProvider)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="221" sourceendlinenumber="221">ICustomFormatter.Format</a>", "<a href="xref:System.ICustomFormatter.Format(System.String, System.Object, System.IFormatProvider)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="238" sourceendlinenumber="238">ICustomFormatter.Format</a>", "<a href="xref:System.StringSystem.String.Format(System.IFormatProvider, System.String, System.Object)" sourcefile="docs/standard/basetypes/definecustom.md" sourcestartlinenumber="238" sourceendlinenumber="238">String.Format(IFormatProvider, String, Object[])</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609142120216899-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.synchronizationlockexception?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.synchronizationlockexception?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.tasks.concurrentexclusiveschedulerpair?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.tasks.concurrentexclusiveschedulerpair?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.tasks.parallel?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.tasks.parallel?branch=pr-en-us-1016)  
  Please see 3092 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/backreference.md.). Referenced by file: docs/standard/basetypes/grouping.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609142155491875-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.genericuriparseroptions?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.genericuriparseroptions?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.calendar?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.calendar?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.calendaralgorithmtype?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.calendaralgorithmtype?branch=pr-en-us-1016)  
  Please see 3089 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:System.Enum.ToString(System.IFormatProvider)" sourcefile="docs/standard/basetypes/extractday.md" sourcestartlinenumber="372" sourceendlinenumber="372">Enum.ToString</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609142238591301-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition.compositioncontractmismatchexception?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition.compositioncontractmismatchexception?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition.compositionerror?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition.compositionerror?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition.compositionexception?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition.compositionexception?branch=pr-en-us-1016)  
  Please see 3127 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/@System.String). Referenced by file: docs/standard/basetypes/manipulatingstrings.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609142308080388-1016%5Cworkflow_report.html).

**Comment by stevehoag** [comment]
Build failed - closing and reopening to trigger build

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.asynccallback?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.asynccallback?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.attribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.attribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.attributetargets?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.attributetargets?branch=pr-en-us-1016)  
  Please see 3128 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/System.Text.RegularExpressions.MatchCollection.Item(System.Int32)). Referenced by file: docs/standard/basetypes/objectmodel.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609150033319274-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.contextstaticattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.contextstaticattribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.convert?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.convert?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.converter-2?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.converter-2?branch=pr-en-us-1016)  
  Please see 3124 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/System.Text.RegularExpressions.MatchCollection). Referenced by file: docs/standard/basetypes/objectmodel.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609150102166345-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1.enumerator?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1.enumerator?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.synchronizedcollection-1?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.synchronizedcollection-1?branch=pr-en-us-1016)  
  Please see 3387 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/System.Text.RegularExpressions.MatchCollection). Referenced by file: docs/standard/basetypes/objectmodel.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609151629066494-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.ienummoniker?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.ienummoniker?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.ienumstring?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.ienumstring?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.ienumvariant?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.ienumvariant?branch=pr-en-us-1016)  
  Please see 3094 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/9). Referenced by file: docs/standard/basetypes/quickref.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609151707200433-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.services.client.dataservicerequest?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.services.client.dataservicerequest?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.services.client.dataservicerequestargs?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.services.client.dataservicerequestargs?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.services.client.dataservicerequestexception?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.services.client.dataservicerequestexception?branch=pr-en-us-1016)  
  Please see 3084 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/9). Referenced by file: docs/standard/basetypes/quickref.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609151710579102-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlnotificationtype?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlnotificationtype?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlparameter?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlparameter?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlparametercollection?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlparametercollection?branch=pr-en-us-1016)  
  Please see 3093 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/regularexpressions). Referenced by file: docs/standard/basetypes/threadsafety.md at line: 0...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609151750074166-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comunregisterfunctionattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comunregisterfunctionattribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comvisibleattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comvisibleattribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.connectdata?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.connectdata?branch=pr-en-us-1016)  
  Please see 3087 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609151809417159-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.fileextensionsattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.fileextensionsattribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.filteruihintattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.filteruihintattribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.ivalidatableobject?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.ivalidatableobject?branch=pr-en-us-1016)  
  Please see 3122 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609152025153004-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.methodinfo?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.methodinfo?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.missing?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.missing?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.module?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.module?branch=pr-en-us-1016)  
  Please see 3106 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C15%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609152113515005-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.threadstateexception?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.threadstateexception?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.timeout?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.timeout?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.timer?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.threading.timer?branch=pr-en-us-1016)  
  Please see 3113 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C16%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609161613082410-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.schema?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.schema?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.stringlengthattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.stringlengthattribute?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.timestampattribute?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.timestampattribute?branch=pr-en-us-1016)  
  Please see 3114 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C16%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609161639592437-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.umalquracalendar?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.umalquracalendar?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.unicodecategory?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization.unicodecategory?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.globalization?branch=pr-en-us-1016)  
  Please see 3180 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C16%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609161711009487-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.composition?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.container?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.container?branch=pr-en-us-1016)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.containerfilterservice?branch=pr-en-us-1016](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.containerfilterservice?branch=pr-en-us-1016)  
  Please see 3118 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C16%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609162025377732-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1016](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1016)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1016](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1016)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1016](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1016)  
  Please see 1 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C19%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609191716210921-1016%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1016](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/alternation?branch=pr-en-us-1016)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1016](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/anchors?branch=pr-en-us-1016)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1016](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/basetypes/backreference?branch=pr-en-us-1016)  
  Please see 1 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C19%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609191806359191-1016%5Cworkflow_report.html).

**Comment by stevehoag** [comment]
Has rendering issues that can't be fixed. Resubmitted as #1053

**Pull request closed without merging**
