### PR TITLE
Repo chores 10/2020

### PR DESCRIPTION
**Pull request by gewarren**
Contributes to #20675.

- Cleans up orphaned files.
- Removes redirection file hops.
- Replaces redirected and non-relative links.

### CODE REVIEW

**Comment by gewarren** [comment]
@luisquintanilla There's one deleted image in the /spark folder, which is why you were tagged.

**Comment by luisquintanilla** [comment]
@gewarren thanks 🙂

**Comment by gewarren** [comment]
@adegeo Could you take a look when you get a chance?

**Comment by gewarren** [comment]
@dotnet/docs Could I get a review on this PR? It's only 5 files changed now.

**Review by tdykstra — APPROVED** [review]
LGTM

**Comment by gewarren** [comment]
Thanks Tom!

**Pull request merged**
