### PR TITLE
Removed tools.md as content has been split over other files. 

### PR DESCRIPTION
**Pull request by DavidCBerry13**
Removed tools.md file (content is now split over other files)
Added appropriate redirect

### CODE REVIEW

**Comment by DavidCBerry13** [comment]
@CamSoper @gewarren - This is the PR for tools.md problem.  I tested my redirect and that looks like it is working as it should be.

**Review by gewarren — APPROVED** [review]
Thanks for following up on this!

**Comment by gewarren** [comment]
Looks like this needs to be updated too:

https://github.com/dotnet/docs/blob/442c2a9707181ccb16d5200ea090cd89c15fbab4/docs/azure/index.yml#L238

**Comment by gewarren** [comment]
Replaced by #22413.

**Pull request closed without merging**
