### PR TITLE
replace wrong example

### LINKED ISSUE #4413: DES Sample uses Incorrect Class
# Issue Title

The sample for System.Security.Cryptography.DES uses TripleDES class not DES class

# General

Looking at the sample on https://docs.microsoft.com/en-gb/dotnet/api/system.security.cryptography.des?view=netframework-4.7.1 - this sample used the TripleDES class, not the DES class.

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #4413 

@bartonjs can you take a look? Current [DES docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.des) have a sample for the wrong algorithm. This would bring the samples just like they existed in https://msdn.microsoft.com/en-us/library/system.security.cryptography.des(v=vs.90).aspx#Examples. 

Are you ok with that or do you prefer to just pull the sample here?

[Internal review URL](https://review.docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.des?branch=pr-en-us-4445)

/cc @doctordns

### CODE REVIEW

**Comment by bartonjs** [comment]
I'd just pull the samples for DES, personally.  But I have no strong objection to just making docs look like MSDN until we overhaul.

**Comment by mairaw** [comment]
That was my initial idea @bartonjs. But given that we weren't going to remove the samples from the APIs, I thought that re-adding the sample was better. But I'm fine either way.

**Comment by doctordns** [comment]
Since DES is effectively depricated, I see no problem both removing samples and decorating the XML with 'This API Depricated see https://... for more details".

**Comment by mairaw** [comment]
I pulled the examples section from this one. I'm still not sure how we're going to surface the recommend API suggestions for deprecated algorithms. But we'll start working on that shortly.

**Review by rpetrusha — APPROVED** [review]
LGTM. You can merge this when you're ready, @mairaw.

**Pull request merged**
