### PR TITLE
Call out code style enforcement as experimental

### PR DESCRIPTION
**Pull request by jmarolf**
## Summary

Calls out that enforcing code style on build is experimental

### CODE REVIEW

**Comment by jmarolf** [comment]
CC: @mavasani @mikadumont

**Review by mavasani — APPROVED** [review]

**Review by mikadumont — COMMENTED** [review]
I believe the proper doc syntax for notes is the following:

[!NOTE] This feature is currently experimental and may change between the .NET 5 and .NET 6 releases.

**Comment by mavasani** [comment]
@jmarolf Do you plan to do a follow-up PR for mentioning the new property page for [enforcing code style on build](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enforcecodestyleinbuild) (or will that need to go into VS docs repo)? Eventually, once we release `Microsoft.CodeAnalysis.NetAnalyzers` 5.0.0 NuGet package post .NET 5.0 GA, we should also mention the NuGet package here as an alternative.

**Comment by jmarolf** [comment]
@mavasani good idea, I'll submit a PR to the VS docs repo after this

**Pull request merged**
