### PR TITLE
Update project-json.md

### PR DESCRIPTION
**Pull request by anders-liu**
# Title

Add an overivew of a whole project.json file
## Summary

Add an overivew of a whole project.json file, because it makes people easy to understand the hirarchy of a project.json object.

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.security.windowsclientcredential?branch=pr-en-us-983)

**Comment by BillWagner** [comment]
@anders-liu Thank you for contributing this. It's a great addition to the information on project.json.

I've reviewed it and I think it's ready to merge.  @blackdwarf can you review for accuracy on the elements in the overview section?

**Comment by mairaw** [comment]
I can review that. I'll make sure it matches what we have listed in the doc.

**Comment by mairaw** [comment]
It looks good. I have some changes to make to this topic, so I'll update the section along with my changes on a different PR. Thanks @anders-liu!

**Pull request merged**
