### PR TITLE
chore: Add cSpell dictionary for MSDocs Authoring

### PR DESCRIPTION
**Pull request by nschonni**
Does not suppress all spelling issues, but covers some beyond the built-in dictionary while editing documents in VS Code with the MS Docs authoring extension pack.

### CODE REVIEW

**Comment by nschonni** [comment]
This can also be run from the commandline
- `npm i -g cspell`
- I needed to extend the heap occasionally if i tried to run large folders with `export NODE_OPTIONS=--max_old_space_size=8196`
- running it using `cspell "**/*.*"` with quotes around the globs. using particular folders is probably more resonable `cspell "docs/core/**/*.*"

**Review by mairaw — APPROVED** [review]
Really cool @nschonni. Thanks for doing this. Does this mean we went through the whole repo now?

**Comment by nschonni** [comment]
Pretty much. Just realized I missed the "includes" but I think that's mostly it now.
I may have missed some things since i'm doing this at the end of the day to turn off my brain, so i might have scrolled over some in the output

**Comment by mairaw** [comment]
Awesome! Thanks so much.

**Pull request merged**
