### PR TITLE
offline book toc changes

### PR DESCRIPTION
**Pull request by ghogen**
This fixes the offline book toc - the root node needs to be a real topic, and this lets the offline book build tool pull in the content.

### CODE REVIEW

**Comment by ghogen** [comment]
This fixes issue #13795 offline book content missing
@BillWagner

**Comment by ghogen** [comment]
@rpetrusha  can you look at this, since Bill is out of the office?

**Comment by ghogen** [comment]
The diff looks extensive, but it's just the top level empty node being removed, and everything else shifting indentation by one tab

**Review by BillWagner — APPROVED** [review]
Thanks for making this fix @ghogen 

I'll :shipit: now.

**Pull request merged**
