### PR TITLE
Update primer.md

### PR DESCRIPTION
**Pull request by mairaw**
Fixed broken link

/cc @BethMassi @blackdwarf

### CODE REVIEW

**Comment by mairaw** [comment]
I just noticed the same happened with issue #174. The person only edited the first paragraph but somehow the last line was included in the PR (?!?).

**Comment by cartermp** [comment]
I'm inclined to think it's a difference between `\n` and `\r\n' in the file and git's diff is interpreting the lines are different.  At any rate, I don't think it's a problem so long as the text itself isn't accidentally changed.

**Comment by cartermp** [comment]
:shipit: LGTM

**Comment by mairaw** [comment]
I think so too @cartermp. I reviewed the last line and it looks the same to me.

But if you guys prefer, I can delete this one and try again.

**Comment by cartermp** [comment]
No need.  If it were lots of paragraphs I'd say deleting and re-doing might be worth it, but since it's just one paragraph I think it's fine.

**Pull request merged**
