### PR TITLE
fix broken links and some titles

### PR DESCRIPTION
**Pull request by mairaw**
While I was reviewing some of the changes on the master branch to push content into production, I've noticed two things:
- PR #1348 changed some links from index.md to toc.md and those links don't work
- During conversion/migration of the VB topics, the command-line compiler titles were renamed to avoid file name issues with "/" during export. So I'm fixing the names so they're back to the correct names

/cc @stevehoag

### CODE REVIEW

**Comment by stevehoag** [comment]
@mairaw Thanks for finding and fixing these!

The changes look good, but I am concerned that I'm not seeing the TOC changes on stage. If that's expected, then go ahead and :shipit:

**Comment by mairaw** [comment]
Not expected. which changes are you not seeing @stevehoag?

**Comment by stevehoag** [comment]
For example, drill down under VB/Programming Guide/Programming Concepts/LINQ. That should show the LINQ sub-TOC, but it doesn't - I'm still seeing the deep nesting.

**Comment by mairaw** [comment]
That's odd. This is [URL](https://review.docs.microsoft.com/en-us/dotnet/articles/visual-basic/programming-guide/concepts/linq/?branch=pr-en-us-1565) you're looking at?

I see this:
image

**Comment by mairaw** [comment]
That's why I've started working on the breadcrumb too, so it'll look like this when PR #1568 gets merged:
image

**Comment by stevehoag** [comment]
The link in your first comment doesn't display a TOC at all.
The screenshot for #1568 is what I expect to see (and what I saw on stage before merging my TOC changes).
So maybe merging both of your PRs will get us back to the desired state?

**Comment by mairaw** [comment]
Maybe. Let's try that @stevehoag.

BTW, the full path on the breadcrumb was a temporary glitch. I saw it live on docs too and then it went away after a few hours/days. We need to manually do the breadcrumb to get that nice breadcrumb path.

**Pull request merged**
