### PR TITLE
fix constructor remarks formatting.

### PR DESCRIPTION
**Pull request by BillWagner**
/cc @dend

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
LGTM!

**Comment by dend** [comment]
LGTM!

**Comment by rpetrusha** [comment]
Closing and reopening, since the PR isn't listed in the OPS build log.

**Comment by mairaw** [comment]
I can't see the change on staging. Do you guys see it? @rpetrusha @BillWagner 

https://review.docs.microsoft.com/en-us/dotnet/api/system.string.-ctor?view=netframework-4.7&branch=pr-en-us-3141

**Comment by rpetrusha** [comment]
@mairaw @billwagner These changes just aren't reflected in the [built page](https://review.docs.microsoft.com/en-us/dotnet/api/system.string.-ctor?view=netframework-4.7&branch=pr-en-us-3141). I don't understand why that would be or why a full rebuild would be required. Should we merge anyway?

**Comment by BillWagner** [comment]
@dend See the preceding comment. Any thoughts?

**Comment by mairaw** [comment]
I saw this happening once. I'd merge and see what happens. The changes are pretty trivial.

**Comment by mairaw** [comment]
I found one more instance of the same issue, so decided to fix it here too. Sorry for the wonky commits in the middle.

**Pull request merged**
