### PR TITLE
xref fix for 'using-bindings-to-configure-services-and-clients.md'

### PR DESCRIPTION
**Pull request by VenomShifter**
**Note**: I have not tested the xref link locally, but the [WSHttpBinding page](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.wshttpbinding) does exist. so it should work.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for contributing to the dotnet/docs repo and for attempting to fix this link, @RutgerM. An internal build report indicates that the link is still broken. However, it's now clear why the link is broken: type and member name comparisons are case-sensitive. So the type name should be **WSHttpBinding**, not **WsHttpBinding**. Would you mind changing it, or would you like us to do it for you?

**Comment by RutgerM** [comment]
@rpetrusha I'm not that familiar with all those tools you guys use, but I think it is fixed now.

**Review by mairaw — CHANGES_REQUESTED** [review]
The change in the text looks good but the file shouldn't be renamed to your email. Can you fix that @RutgerM?

**Comment by RutgerM** [comment]
@mairaw Woops. I did not notice that! Must have been my password manager. I'll make sure to triple check everything if I ever make another pull request.

**Review by mairaw — APPROVED** [review]
Thanks for fixing that. Once build finishes and we verify the link is working, we'll merge this PR.

**Comment by mairaw** [comment]
I've also created an issue to fix these throughout our content: #3682

**Comment by RutgerM** [comment]
@mairaw If you want, I could pick up a few of those to speed up the migration. I'll make sure to triple check that nothing silly happens again.

**Comment by mairaw** [comment]
Sure, it would be great to have your help! We would want to break down the PR in smaller sets anyway. Just comment on the issue if you'd want to do that, so others know you'll be working on that.

**Comment by rpetrusha** [comment]
Thank you for fixing the link and for responding so quickly, @RutgerM. The broken link is fixed, so we'll merge your PR now. Changes should appear live on docs.microsoft.com tomorrow or the following day.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
