### PR TITLE
Moved and revised the article about C# tuples

### LINKED ISSUE #10726: Abridged Reference: builtin value types
This new article will include:

**Simple types**
- bool
- enum

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

### LINKED ISSUE #11171: Comment about very large tuples
Should not the article provide a comment about very large tuples, for example:

var a1 = ("New York", 7891957, tete: 7781984, 7894862, 7071639, 7322564, 8008278, 7891957, 7781984,
                 7894862, 7071639, 7322564, 8008278, 7891957, tata: 7781984, 7894862, 7071639, 7322564,
                 8008278, 7891957, 7781984, 7071639, 7322564, 8008278, 7891957, 7781984, 7894862, 7071639,
                 7322564, 8008278, 7891957, 7781984, 7071639, 7322564, 8008278, 7891957, 7781984, 
                 toto: 7894862, 7071639, 7322564, 8008278, "string", 7781984, 7071639, 7322564, 8008278,
                 7891957, 7781984, 7894862, 7071639, 7322564, true, 7891957, 7781984, 7071639, 
                 7322564, 8008278, 7891957, 7781984, 7894862, 7071639, 7322564, 8008278, 7891957, 7781984,
                7894862, 7071639, 7322564, 8008278);

This kind of tuple handles internally sequencies of the 8th element &lt;TRest&gt;, so you can address any element directly, for example:

var a2 = a1.Item342;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #12956: Ambiguous sentence
"It's a compile time error to compare two tuples for equality (or inequality) when they have different shapes. The compiler won't attempt any deconstruction of nested tuples in order to compare them." Will the compiler never attempt an deconstruction of nested tuples or only if they have different shapes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#deconstruction)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by pkulikov**
Fixes #10726 (hooray!)
Fixes #12956
Fixes #11171

### CODE REVIEW

**Comment by pkulikov** [comment]
@adegeo the snippets build reports five errors:

> ##[error]😵 Project missing. A project (and optionally a solution file) must be in this directory or one of the parent directories to validate and build this code.
> ##[error]😵 Project missing. A project (and optionally a solution file) must be in this directory or one of the parent directories to validate and build this code.
> ##[error]😵 Project missing. A project (and optionally a solution file) must be in this directory or one of the parent directories to validate and build this code.
> ##[error]😵 Project missing. A project (and optionally a solution file) must be in this directory or one of the parent directories to validate and build this code.
> ##[error]😵 Project missing. A project (and optionally a solution file) must be in this directory or one of the parent directories to validate and build this code.

 I assume those are for the source code files **being deleted** by this PR. Is that correct? How to resolve those errors?

**Comment by tdykstra** [comment]
@adegeo Weren't we going to implement these as warnings that wouldn't prevent merging?

**Comment by BillWagner** [comment]
@pkulikov  We need to fix the tooling for this set of CI build errors.

I'll work on it today.

@tdykstra The CI build should be set to non-blocking, so we can still merge this PR, once it's been reviewed.

**Review by BillWagner — APPROVED** [review]
Woohoo!  This is great work @pkulikov 

I've reviewed the changes, and I'll :shipit: now.

**Pull request merged**
