### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by gewarren**
Random acrolinx fixes.

### CODE REVIEW

**Comment by gewarren** [comment]
@BillWagner Could you review please? Also, how do we get the csharplang warning to go away?

**Comment by BillWagner** [comment]
@gewarren  #16214 fixes the warning. 

Reviewing this PR now.

**Review by BillWagner — APPROVED** [review]
these all LGTM @gewarren 

You can :shipit: when ready.

**Comment by gewarren** [comment]
Thanks for the review Bill!

**Pull request merged**
