### PR TITLE
chore: Run Markdownlint with GitHub Actions

### PR DESCRIPTION
**Pull request by nschonni**
## Summary
More as a discussion point, since this is something i'm sure there is a policy on using/not using GitHub Actions. General idea was that you could ignore these failures if you don't care about them, but can help outside of the OpenPublishing builds.

### CODE REVIEW

**Comment by nschonni** [comment]
Here is the demo of it working on my fork (although currently failing from a few Markdownlint issues) https://github.com/nschonni/dotnet-docs/commit/12a44f9c3c47d174e818d5ddfba6db71ffc81417/checks?check_suite_id=264969966

**Comment by mairaw** [comment]
That's an interesting idea @nschonni. Let me discuss that with the team.

**Review by mairaw — APPROVED** [review]
Thanks for doing this @nschonni. We've discussed internally and decided to accept this on a trial run. We'll run this for a week or two and evaluate if we'll keep it or not.

@natke @marymch FYI

**Comment by nschonni** [comment]
@mairaw curious to hear how the trial has gone

**Comment by mairaw** [comment]
Hey @nschonni, I think it's working well with a couple of false positives and some interesting side effects if you close and reopen a PR. Some folks don't like the automated runs but I think most of our team would like to continue with this.

**Comment by nschonni** [comment]
Thanks! Do you think that pinning to a specific version would help. EX: create a specific Action for MSDocs that wraps this and keeps a particular version of Markdownlint(-cli) in use till all projects are ready for new rules? I know I've gotten bitten/annoyed when new rules get added and previously passing things now fail, and you have to update your config just till you can look at them

**Pull request merged**
