### PR TITLE
Fix Code sample is missing issue

### PR DESCRIPTION
**Pull request by mairaw**
According to this CATS report:
https://contentqacats.azurewebsites.net/CheckResults/2019080900284/Report/Failed/Missing%20code%20samples

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
LGTM, @mairaw. This is ready to merge.

**Comment by mairaw** [comment]
I found one issue. Hang on!

**Comment by rpetrusha** [comment]
The builds look good, @mairaw.

**Comment by mairaw** [comment]
Now the regular expression from the code matches the description 🎉

**Pull request merged**
