### PR TITLE
Update live with current master

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by mairaw** [comment]
@fenxu why are we excluding those TOCs from PDF build? builds fail otherwise?

**Comment by dend** [comment]
@mairaw @fenxu I think as a start, we should enable this like it is (what Feng has in the commit), but I do agree that we need to fix the issue with large TOCs as well, as there is no reason for users not to be able to download that information, *especially* when they previously could download the entire .NET Core reference in one file.

**Comment by fenxu** [comment]
@mairaw Currently it's just a workaround before we are able to generate large toc's pdf. This change will make the other tocs generate and unblock the whole pdf process in a way. Certainly, just as @dend said, we should fix this issue ASAP to make all the download link valid. We are focus on that!

**Comment by mairaw** [comment]
Great, thanks for the context @fenxu and @dend!

**Comment by mairaw** [comment]
BTW @fenxu, we're still having some of the weird issues with builds. Build on GH is still in processing, build on OPS has failed and I can't see the report. I thought we had fixed that?

**Pull request merged**
