### PR TITLE
Update writing-an-ef-data-provider.md

### LINKED ISSUE #2770: Entity Framework Sample Provider example is missing
**Describe the bug**
This page https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/writing-an-ef-data-provider has a link to a "Entity Framework Sample Provider" under the section "Sample". However, this link redirects to the "Browse code samples"-page. Searching for "entity framework sample provider" does not return any results.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/writing-an-ef-data-provider
2. Scroll down to 'Sample'
3. Click on the link "Entity Framework Sample Provider"
4. Search for "entity framework sample provider" in Browse code samples-page.

**Expected behavior**
I expect it to be easier to find the Entity Framework Sample Provider. Either through a direct link or through searching in the browse code samples-page. At the moment I cannot find it anywhere.

### PR DESCRIPTION
**Pull request by JeremyLikness**
Update to link to newer documentation. This fixes [issue 2770 in the MicrosoftDocs repo](https://github.com/MicrosoftDocs/feedback/issues/2770).

## Summary

Added a note to the top of the document to link to the more current documentation.

Fixes 2770 in the MicrosoftDocs repo.

### CODE REVIEW

**Comment by mairaw** [comment]
This note would be true to all the EF docs on dotnet/docs. We met once with @gewarren @stevestein and the previous PM to start the conversation around organizing/cleaning up these docs but it never happened.

I'm wondering if in this case, it would be better to delete this article and redirect it to the most up-to-date one.

**Comment by JeremyLikness** [comment]
That works for me. Should I close this PR? Or do you want me to change it to redirect? I don't know how to redirect docs, so this will be a learning opportunity.

**Comment by mairaw** [comment]
You can change the PR if you'd like. 

Redirections are added to https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json, in alphabetical order, by source_path.
Then you can delete the article and check any references to the article from the TOC, etc.

Happy to help as well.

**Comment by JeremyLikness** [comment]
> You can change the PR if you'd like.
> 
> Redirections are added to https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json, in alphabetical order, by source_path.
> Then you can delete the article and check any references to the article from the TOC, etc.
> 
> Happy to help as well.

@mairaw it looks like there is a whole section there that is based on older version of EF. There are 8 other pages in the section that do not have corresponding documents. Should I redirect them all to the same target?

**Comment by mairaw** [comment]
Is the target a good replacement? Also, all this set had copies on the docs archive. So if you think they're not useful anymore, we could also just send the other ones to the docs archive version.

**Comment by JeremyLikness** [comment]
Addressed with #19848

**Pull request closed without merging**
