### PR TITLE
Add console to supported languages

### PR DESCRIPTION
**Pull request by ChrisMaddock**
This is used throughout this repo - so I believe it is supported? 😄

### CODE REVIEW

**Comment by mairaw** [comment]
I think that csharp-interactive is officially supported by docs but console, although we use it, it's not really supported by our platform but it's supported in Markdown. Any non-officially supported identifier will be displayed as-is (vs. others that get special labels). We should probably note that if we don't.

Thoughts @BillWagner?

**Comment by BillWagner** [comment]
`console` probably shouldn't be used.  `text` would be better for plain unformatted text, as I believe that's one of the listed languages.

For shells, both `powershell` and `bash` are supported. I did not see any identifiers for `console` or `cmd`. 

As an implementation detail, if the tag specified is not understood by highlight.js, I think it defaults to unformatted. That's why `console` works for basic text. (if there is no tag, highlight.js tried to determine the language from hints in the syntax).

ping @DuncanmaMSFT because I'm not certain, but I think our parser uses [highlight.js](https://highlightjs.org/) with some extensions.

**Comment by DuncanmaMSFT** [comment]
Ok, lots to comment on here. So, what @BillWagner said was accurate, just rephrasing below to be as clear as possible (cc @ChrisMaddock @mairaw )

- if the Docs code doesn't recognize a language name, we just output whatever you put in, as is
- if highlight.js doesn't recognize a language name, we do *not* auto-detect (because that can often produce bad results and we want to discourage people skipping the language or putting ones that don't match our list) and **the code is shown unformatted**
- so, putting Text or Output or Console will show that text above the code block
- if you want a language choice for cmd, we can add that, but we'd need some idea of what should be highlighted. Normally, for example, we only highlight what is actually included *in* a language. So `csc File.cs` wouldn't have any highlighting, but something like cd or dir would. Maybe that isn't that useful.
- and finally, yes we are using highlight.js, but that GitHub project is basically dead, so we are working in my fork of it here: http://github.com/duncanmamsft/highlight.js 

This list, that is being edited in this PR, is supposed to be the official list of what we support. I don't suggest we add Console unless we actually add support for it. We could add guidance to this document though that says "put Output when showing the output of a command or program" and/or "put Text when the code block represents plain unformatted text content"

**Review by BillWagner — APPROVED** [review]
Thanks for making these changes @ChrisMaddock 

I'll propose we go with "Console".  It is used for all the docs that were migrated from MSDN, and based on @DuncanmaMSFT 's comments, it's (one possible) right choice.

@mairaw If you agree, go ahead and :shipit:

Thanks for making this change and driving the conversation @ChrisMaddock We appreciate it.

**Comment by mairaw** [comment]
Sorry I missed the comments. I agree. I'll merge now.

**Pull request merged**
