### PR TITLE
Remove net-v45-md.md

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Comment by BillWagner** [comment]
@NextTurn 

This build failed, https://github.com/NextTurn/docs/blob/v45/docs/standard/collections/thread-safe/index.md uses the include you removed.

I notice that the include you reference in the title is different than the include you removed.  Once you make the correct updates, I'll look again.

**Comment by NextTurn** [comment]
What a mistake.

**Comment by NextTurn** [comment]
I've made the update. Good to go?

**Review by rpetrusha — APPROVED** [review]
Yes. It's good to go. Thanks for removing the token, @NextTurn.

**Pull request merged**
