### PR TITLE
Update Azure Cosmos DB articles for Orleans

### PR DESCRIPTION
**Pull request by seesharprun**
- [x] Use `IsResourceCreationEnabled` to bypass manual resource creation
 - [x] Update to use autoscale throughput at the container level

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/orleans/grains/grain-persistence/azure-cosmos-db.md](https://github.com/dotnet/docs/blob/dc57986529f2f0a427b1bdab5fab8dc7ecd9e3f7/docs/orleans/grains/grain-persistence/azure-cosmos-db.md) | [Azure Cosmos DB for NoSQL grain persistence](https://review.learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/azure-cosmos-db?branch=pr-en-us-37745) |
| [docs/orleans/quickstarts/deploy-scale-orleans-on-azure.md](https://github.com/dotnet/docs/blob/dc57986529f2f0a427b1bdab5fab8dc7ecd9e3f7/docs/orleans/quickstarts/deploy-scale-orleans-on-azure.md) | [CustomerIntent: As a developer, I want to host my Orleans application in Azure so that I can take advantage of the scaling capabilities for the database and application services.](https://review.learn.microsoft.com/en-us/dotnet/orleans/quickstarts/deploy-scale-orleans-on-azure?branch=pr-en-us-37745) |

### CODE REVIEW

**Comment by seesharprun** [comment]
@IEvangelist,  can you review?

**Comment by seesharprun** [comment]
@markjbrown, can you review?

**Comment by markjbrown** [comment]
I think docs look good.

Is there a reason why Orleans uses connection string? Seems like this would prevent users from using default identity with their apps and Cosmos.  Thanks!

**Comment by seesharprun** [comment]
> I think docs look good.
> 
> Is there a reason why Orleans uses connection string? Seems like this would prevent users from using default identity with their apps and Cosmos. Thanks!

The current quickstart uses connection string, but I agree we shouldn't use it moving forward.

I have an [action item](https://github.com/dotnet/docs/issues/36975#issuecomment-1781304117) to switch to AZD and managed identity sometime after Ignite.

**Comment by seesharprun** [comment]
#sign-off

**Review by IEvangelist — APPROVED** [review]

**Pull request merged**
