### PR TITLE
Newer version of dotnet based on install doc

### PR DESCRIPTION
**Pull request by wallymathieu**
# Title

Using version from [install docs](https://www.microsoft.com/net/core#linuxubuntu)

## Summary

Since the install documentation references a newer version of dotnet, it could be helpful to use that in this documentation as well, in order to lead people on the right path.

## Suggested Reviewers

@enricosada

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @wallymathieu! @blackdwarf can you help validate this?

**Comment by enricosada** [comment]
@wallymathieu i think is ok, because install docs use .NET 1.1 (preview2.1)

As a note, ihmo using .NET 1.1 (`Current`) for install docs is bad for new users instead of using `LTS` because is more stable with more docs (there where issues with cli tools for example for some time). But that;s another issue 😄

**Comment by blackdwarf** [comment]
Let's not do this this way. We need to actually make a change for the CLI docs to explain the difference between LTS and Current and modify all of the according docs, including the CI one with this explanation. If this change goes in, users will be getting 1.1 runtime and will not be able to test 1.0 apps (potentially) or similar.

**Comment by wallymathieu** [comment]
Perhaps list how to configure it for both 1.0 and 1.1 ? That could be useful.

**Comment by blackdwarf** [comment]
@wallymathieu for sure. But it is a bigger change because it also needs to point to the explanation on what those two are and how are they different. :)

**Comment by mairaw** [comment]
I'll be closing this one for now then. We have an issue tracking the CI doc update #1454. Thanks guys!

**Pull request closed without merging**
