### PR TITLE
Remove RHEL minor RIDs

### PR DESCRIPTION
**Pull request by tmds**
Binary compatibility exist at the RHEL major level, e.g. RHEL7.
The implementation includes minors (e.g. 7.1) only to map them to their parent (e.g. 7.1 -> 7).
These minors are not meant for end-users, so we shouldn't include them in the documentation.

### CODE REVIEW

**Comment by JRAlexander** [comment]
@leecow - Thoughts?

**Comment by leecow** [comment]
The idea seems fine (would be the same for CentOS) but would need for code owners to weigh in on any functional ramifications.

**Comment by mairaw** [comment]
Who would that be @leecow?

**Comment by leecow** [comment]
@RussKeldorph , @danmosemsft would be the place to start. Also @eerhardt may have an opinion.

**Review by eerhardt — APPROVED** [review]
This makes sense to me. We already have just `centos.7-x64`, and don't list the minor versions for CentOS. Makes sense to do the same for RHEL.

We also are "normalizing" the RID in code, so even on RHEL 7.3, the code outputs `rhel.7`.

https://github.com/dotnet/core-setup/blob/5ff1240bef06a9a0a6544fcef93808ac26028e43/src/managed/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs#L168-L189

**Review by BillWagner — APPROVED** [review]
Approving based on product team approvals.

Thanks for making this change @tmds I'll :shipit: now.

You should see the changes in the next few days, on our regular publishing cycle.

Thanks again.

**Pull request merged**
