### PR TITLE
Revised shift operators articles

### PR DESCRIPTION
**Pull request by pkulikov**
Supported by dotnet/samples#637

### CODE REVIEW

**Review by BillWagner — COMMENTED** [review]
I reviewed this, and everything looks great.

Once the samples PR is merged, and this has a clean build, I'll approve this PR and :shipit:

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build after merging dotnet/samples#637.

**Comment by pkulikov** [comment]
@rpetrusha @BillWagner thanks for review; this is ready to go.

**Review by BillWagner — APPROVED** [review]
Thanks @pkulikov 

As noted before, this is ready to :shipit:

**Pull request merged**
