### PR TITLE
Add link to feedback section

### PR DESCRIPTION
**Pull request by gewarren**
A suggestion for the feedback paragraph.

### CODE REVIEW

**Comment by gewarren** [comment]
Well nevermind then! In works in the rendered docs, but not in build apparently.

**Comment by gewarren** [comment]
Will try Ying's suggestion of using an absolute path link.

**Comment by gewarren** [comment]
@tdykstra The link seems to work now. LMK what you think.

https://review.docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?branch=pr-en-us-16785

**Review by tdykstra — APPROVED** [review]
Looks good!

**Pull request merged**
