### PR TITLE
Update and rename datepicker-syles-and-templates.md to datepicker-sty…

### PR DESCRIPTION
**Pull request by acidshards**
Rename datepicker-syles-and-templates.md to datepicker-styles-and-templates.md

### CODE REVIEW

**Comment by svick** [comment]
I think [the TOC](https://github.com/acidshards/docs/blob/patch-1/docs/framework/wpf/controls/toc.md) also needs to be updated.

**Review by BillWagner — CHANGES_REQUESTED** [review]
Thanks for catching this, and fixing it.

I'll merge once we add the redirect node, because of the file name change.  I left a comment with instructions on how to do that.

**Comment by BillWagner** [comment]
Because this PR changes a file name, we need to add a redirect node [here](https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json#L880), or anywhere in this file.

The new node should be:

```json
        {
            "source_path": "docs/framework/wpf/controls/datepicker-syles-and-templates.md",
            "redirect_url": "/dotnet/framework/wpf/controls/datepicker-styles-and-templates",
            "redirect_document_id": true
        }
```

**Comment by mairaw** [comment]
We also need to update incoming links to that topic:
image

**Comment by BillWagner** [comment]
@acidshards including redirects and internal links, this is now looking like a larger PR. 

If you want to make those changes, we'd be thrilled to take them. If not, let us know and we'll accept these improvements, and add a new PR to fix the redirections and internal links.  

Thanks again for spotting this and fixing it.

**Review by BillWagner — APPROVED** [review]

**Comment by BillWagner** [comment]
Thanks again for the contribution @acidshards I just :shipit:.  It will appear on the live site in a day or so.

**Comment by GuardRex** [comment]
@BillWagner @mairaw I'll knock out the links real quick 🏃. Also, the redirect file is starting to get messy again, so I'll fix that up, too.

**Pull request merged**
