### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cartermp**
Added a section for code style, linking to the corefx code style and adding a preference for static methods over instance methods for things which don't require object instantiation.

### CODE REVIEW

**Comment by BethMassi** [comment]
We should also update the sample code in step 4 to prefer the static call. Maybe we should just add a direct link to a sample itself now that we have some :)

**Comment by cartermp** [comment]
Agreed.  I'll make the change and rebase.

**Comment by BethMassi** [comment]
LGTM except there's a misspelling on step 6 (should be "folder")

**Comment by cartermp** [comment]
Actually fixed that in #107.  We could merge that and then I can pull/rebase and push to this again with the spelling fixes.

**Comment by BethMassi** [comment]
OIC. Ok just merged #107

**Comment by cartermp** [comment]
Blegh messed up the commit, rebasing again

**Comment by cartermp** [comment]
Okay, rebased and good to go!

**Pull request merged**
