### PR TITLE
Document StackTraceSupport property

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This property was added in https://github.com/dotnet/runtime/pull/88235.

Cc @dotnet/ilc-contrib 

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/deploying/trimming/trimming-options.md](https://github.com/dotnet/docs/blob/d90ffd53097892596c240420d363b48e593e3f97/docs/core/deploying/trimming/trimming-options.md) | [Trimming options](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?branch=pr-en-us-36080) |

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@dotnet/ilc-contrib could someone have a look?

**Review by vitek-karas — APPROVED** [review]

**Comment by adegeo** [comment]
@MichalStrehovsky Sorry for the delay. Is this only in .NET 8?

**Comment by adegeo** [comment]
@vitek-karas

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Sorry for the delay. Is this only in .NET 8, if so, it should be clarified in the description.

Added the .NET 8+ note.

**Pull request merged**
