### PR TITLE
Remove word

### PR DESCRIPTION
**Pull request by philippgille**
Removed an unnecessary `the`.

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks for your contribution @philippgille. Even though it's a simple fix, to me it feels like it changes the meaning of the sentence slightly, The before would be similar to saying "They're particularly useful when dealing with the variety of Linux distros." There are so many versions and we don't always have an entry for the specific distro you're using. Any thoughts on that?

**Review by rpetrusha — DISMISSED** [review]

**Comment by philippgille** [comment]
@mairaw Thanks for sharing your thoughts. I know what you mean. The previous sentence wanted to emphasize that there are so many Linux distributions. But in that case, the sentence is still wrong in my opinion and should be changed in the following way:
- Original: "*They're particularly useful when dealing with the multiple Linux distros.*"
- Changed: "*They're particularly useful when dealing with the huge amount of existing Linux distros.*"

But I'm still of the opinion that my change was correct. Because the sentence should focus on why the new portable RIDs are useful for developers. The sentence starts with *"They're particularly useful"*, so the usefulness is the core content of the sentence. And the portable RIDs are useful to a developer even if she's just targeting *a couple* of Linux distribitions, or in other words, *multiple*. It's not only useful if the developer targets *the huge amount of existing Linux distributions*.

So if we ask the question "When are the portable RIDs useful for a developer?", the answer is "*They're particularly useful when dealing with multiple Linux distros.*".

**Comment by mairaw** [comment]
Thank you for your response @philippgille. I didn't want to imply your change was wrong. It was just different than what I was thinking when I wrote that sentence. I'll have to close and reopen to kick off the build again and then I'll merge. 
I'll try to find a better place to explain that you can use the portable RIDs with Linux distros not listed in the article.  For example, someone was asking what to use with AMI. Thanks!

**Comment by philippgille** [comment]
Thanks @mairaw !

**Review by mairaw — APPROVED** [review]

**Pull request merged**
