### PR TITLE
Porting language independence topic from MSDN

### PR DESCRIPTION
**Pull request by stevehoag**
Content previously reviewed

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.xml.xmlnamespacescope?branch=pr-en-us-981)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.xml.linq.xobjectchangeeventargs?branch=pr-en-us-981)

**Comment by stevehoag** [comment]
@mairaw  Build is clean and topic has been checked on stage - okay to merge?

**Comment by mairaw** [comment]
Your alias is stevehoag not shoag. I just fixed that in the GC topics.

**Comment by mairaw** [comment]
Rule 33 is missing the text

**Comment by mairaw** [comment]
There's a broken VB block in the middle of the text.

**Comment by stevehoag** [comment]
@mairaw Fixed the alias and Rule 33. I can't find the broken VB block - can you be more specific?

**Comment by mairaw** [comment]
I see this on stage: 
image

**Comment by mairaw** [comment]
and this one has a weird indentation:
image

at some point all these snippets should be converted to real snippets and not be inline so we can run them through CI

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.collections.readonlycollectionbase?branch=pr-en-us-981)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.componentmodel.dataannotations.creditcardattribute?branch=pr-en-us-981)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.securityheaderlayout?branch=pr-en-us-981)

**Comment by stevehoag** [comment]
@mairaw All issues addressed.

**Comment by mairaw** [comment]
If all the issues are addressed, it should be good to go. I can't tell if the OPS build warnings are all related to the issues I've fixed in GC already. I'm filing a bug to have the file name for those.

**Comment by stevehoag** [comment]
Closes #230

**Comment by mairaw** [comment]
The Closes #nnn only works if you put it on the commit message or you edit the first comment on the PR. You'll have to close #230 manually.

**Pull request merged**
