### PR TITLE
removed links to dotnet.github.io

### PR DESCRIPTION
**Pull request by mairaw**
Found a few more references to the old site. I think the only one missing now is in the index.md file that links to https://dotnet.github.io/support/. Need to find out where to link that one to.

### CODE REVIEW

**Comment by blackdwarf** [comment]
@mairaw please link that one to https://www.microsoft.com/net/community.

**Comment by mairaw** [comment]
Thanks @blackdwarf. Good to merge then?

**Comment by stevehoag** [comment]
LGTM

**Comment by bradygaster** [comment]
LGTM too

**Pull request merged**
