### PR TITLE
Added overview of C# arithmetic operators

### LINKED ISSUE #10736: Abridged Reference: operators / arithmetic operators
The arithmetic operators are:

- `++` (prefix and postfix)
- `--` (prefix and postfix)
- `+` (unary and binary addition of numeric operands)
- `-` (unary and binary subtraction of numeric operands)
- `*` (multiplication)
- `/` (division)
- `%` (remainder)
- corresponding compound assignment operators
- `checked`/`unchecked`

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

As noted in the comments on #10731 this includes increment and decrement operators even though those are in the primary operators list in the spec.

### PR DESCRIPTION
**Pull request by pkulikov**
Fixes #10736
Supported by dotnet/samples#743

@BillWagner though, it's still a draft, could you please take a look and let me know if a structure is fine and all the necessary content is listed. 

What is left: ~~the section about arithmetic overflow and removal/redirection of individual operator articles. The articles about the following operators will be removed: `++`, `--`, `/`, `/=`, `%`, and `%=`.~~

[internal review link](https://review.docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators?branch=pr-en-us-11452)

### CODE REVIEW

**Comment by BillWagner** [comment]
Thanks for opening the draft PR @pkulikov 

I like the direction and the structure.  Since this is the first combined page, I have a couple experiments we should try before finalizing the changes:

- Let's try adding the operator characters in the H2 headings. I *think* that would help using the navigation in the upper right of the page. On the other hand, I want to make sure it's still easy to use each H2 as an anchor. 

Coming soon:  #11443 is converting the TOCs to YML. A good featuer that's enabled by this change is that we can add tags for filtering the TOC.  For instance, in this one, we can add the following:

```yml
- name: Arithmetic operators
  href: ./arithmetic-operators.md
  displayName: ++, --, +, -, *, /
```

We'll need to coordinate the TOC changes between these two PRs. And, I may need to check with the dev team to know how to escape any special characters in the displayName field.

**Comment by pkulikov** [comment]
@BillWagner 

> Let's try adding the operator characters in the H2 headings. I _think_ that would help using the navigation in the upper right of the page. On the other hand, I want to make sure it's still easy to use each H2 as an anchor.

My thoughts as well. I've just pushed a commit with updated H2 headers (in various formats, which one is better?). Is a review web-page enough for you to check if H2 anchors work, @BillWagner ?

I guess I need to wait for #11443 to be merged, or that's not clear yet?

**Comment by BillWagner** [comment]
> My thoughts as well. I've just pushed a commit with updated H2 headers (in various formats, which one is better?). Is a review web-page enough for you to check if H2 anchors work, @BillWagner ?

The review site helped a lot.  For both visual and anchor considerations I like the variant tried on the remainder operator *Remainder operator %*.  

Visually: It has the operator name, which gives readers a subtle way to learn the official names. And, the symbol is always at the end, so it's easy to stop in the navigation system.

For anchors: The build system replaces spaces with `-`, and that's the anchor. Any invalid anchor characters are removed. (This made the *Unary + and - operators* become `unary--and----operators`. That's not easy to figure out).  In addition, later anchors that would be duplicates get numeric suffixes. So, *++ operator* became `-operator`, *\* operator* became `-operator-1` and */ operator* became `-operator-2`.

BTW, trying the different variants in one commit was great :zap:. It made it easy to see all the variations at once.

> I guess I need to wait for #11443 to be merged, or that's not clear yet?

That's not clear. If #11443 is merged first, this will show merge conflicts because you'll modify a toc.md that's been deleted. If this merges first, we'll make sure these additions / modifications make it into that PR. So, we'll just see which one is done first. 🏎

**Comment by pkulikov** [comment]
@BillWagner thanks for checking H2 headers. Let's go with "Remainder operator %" format and corresponding `remainder-operator-` anchor.

One observation, though. When I navigate through the links in Visual Studio Code, the leading and trailing `-` symbols in the anchor are ignored. That means both `#remainder-operator-` and `#remainder-operator` lead to the same section of an .md file. However, the behavior is different (more limited) in the web: if I append `-` to the URL with anchor, the link doesn't lead to the section, but only to the containing page. So, we must be careful with linking operator H2 headers.

As for the overview text, it's finished and ready for your review. Samples are in dotnet/samples#743. Meanwhile, I'll setup redirects of individual operator articles.

**Comment by BillWagner** [comment]
closing and reopening to start a new build while I review

**Comment by BillWagner** [comment]
@pkulikov

I really like the way this is turning out.  

Ping @MadsTorgersen @LadyNaggaga for comments.

Background: this PR is one of the first in our effort to [shrink the C# Language reference](https://github.com/dotnet/docs/projects/71), by leveraging the spec for details. We're also adding more interactivity to the language reference, enabling readers to experiment with small snippets that demonstrate language features.

**Comment by pkulikov** [comment]
@BillWagner redirects are done. Please take another look.

**Review by BillWagner — APPROVED** [review]
Thanks for all this work @pkulikov 
This is a great first step in the project. I'm really happy with the result.  🥂 

I'll gladly :shipit: now.

**Comment by pkulikov** [comment]
@BillWagner thanks for all the discussions, trust, and reviews.

**Pull request merged**
