### PR TITLE
updates for the hub page

### PR DESCRIPTION
**Pull request by adkinn**
# Image updates for the Hub page

## Summary
new images files, added hover attributes and removed locales from docs links

## Suggested Reviewers
@mairaw

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-1231) | [Details](#user-content-index.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C14%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611142059166225-1231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
@adkinn have you seen the results on stage? isn't the featured content supposed to have images showing up now?

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-1231) | [Details](#user-content-index.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C15%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611150001100257-1231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-1231) | [Details](#user-content-index.md)

<a name="index.md"></a>
### [index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-5.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-6.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-mobile-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-mobile-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-mobile-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/featured-3.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-7.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/featured-2.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-5.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-6.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/featured-1.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-4.svg).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C15%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611150013491195-1231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-1231) | [Details](#user-content-index.md)

<a name="index.md"></a>
### [index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-5.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-6.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-mobile-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-mobile-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-mobile-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/featured-3.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-7.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/featured-2.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-web-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-desktop-4.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-5.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-6.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-gs-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-cloud-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/featured-1.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-1.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-2.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-3.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/articles/images/hub/net-docs-gaming-4.svg).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C15%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611150112335749-1231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.md](https://github.com/dotnet/docs/blob/hubPageUpdate/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-1231) | [Details](#user-content-index.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C15%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611150126493018-1231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
