### PR TITLE
Unix epoch converter

### LINKED ISSUE #19760: System.Text.JSON cant de serialize Unix Epoch WITH a TimeZone e.g  /Date(1590863400000+0530)/
In my .net core API i am using Httpclient Response in Streams  

```
 var options = new JsonSerializerOptions();
                    //options.PropertyNameCaseInsensitive = true;
                    options.Converters.Add(new DateTimeConverter());

                    using (var contentStream = await webResponse.Content.ReadAsStreamAsync().ConfigureAwait(false))
                    {
                        return await textJSON.JsonSerializer.DeserializeAsync<TResponse>(contentStream, options, cancellationToken); // DefaultJsonSerializerOptions.Options
                    }



    public class DateTimeConverter : JsonConverter<DateTime>
    {
        public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            Debug.Assert(typeToConvert == typeof(DateTime));
             return DateTime.Parse(reader.GetString());  // not working for Date string e.g  /Date(1590863400000+0530)/
           
        }

        public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ssZ"));
        }

    }  
```

Kindly Provide  guidance for this to handle it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41b02f-8fe9-44a1-544f-b6016f1ff4b3
* Version Independent ID: 77358796-3ee2-9b86-7e0a-92c60ebc371a
* Content: [DateTime and DateTimeOffset support in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support)
* Content Source: [docs/standard/datetime/system-text-json-support.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/system-text-json-support.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @layomia
* Microsoft Alias: **laakinri**

### LINKED ISSUE #23566: Information about Microsoft Date format in System.Text.Json
Should migration guide contain information about https://github.com/dotnet/runtime/issues/30776 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #19760 
Fixes #23566

### CODE REVIEW

**Review by adegeo — APPROVED** [review]
Sorry for the delay. LGTM, do we want to take the opportunity to migrate the old snippets out of the SAMPLES folder and clean up the article with new snippets?

**Comment by tdykstra** [comment]
>do we want to take the opportunity to migrate the old snippets out of the SAMPLES folder and clean up the article with new snippets?

These snippets were never in the SAMPLES folder.

**Review by layomia — APPROVED** [review]

**Comment by domagojmedo** [comment]
@tdykstra what about Unix epoch without timezone? Regex won't catch it and that's the one old Json serializer will generate.

**Comment by tdykstra** [comment]
> what about Unix epoch without timezone?

@layomia I modified the time zone converter code as follows, if this looks good to you I'll add it alongside the time zone version.

```
sealed class UnixEpochDateConverter : JsonConverter<DateTime>
{
    static readonly DateTime s_epoch = new DateTime(1970, 1, 1, 0, 0, 0);
    static readonly Regex s_regex = new Regex("^/Date\\(([^+-]+)\\)/$", RegexOptions.CultureInvariant);

    public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {

        string formatted = reader.GetString();
        Match match = s_regex.Match(formatted);

        if (
                !match.Success
                || !long.TryParse(match.Groups[1].Value, System.Globalization.NumberStyles.Integer, CultureInfo.InvariantCulture, out long unixTime))
        {
            throw new Exception("Unexpected value format, unable to parse DateTime.");
        }

        return s_epoch.AddMilliseconds(unixTime);
    }

    public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
    {
        long unixTime = Convert.ToInt64((value - s_epoch).TotalMilliseconds);

        string formatted = FormattableString.Invariant($"/Date({unixTime})/");
        writer.WriteStringValue(formatted);
    }
}
```

**Comment by adegeo** [comment]
@tdykstra sorry, I wasn't being clear. I meant the other samples referenced in the same article. No worries.

**Comment by tdykstra** [comment]
Oh, I see what you mean now, I'll get them next time 😄

**Comment by domagojmedo** [comment]
@tdykstra will DateTime converter be added?

**Comment by layomia** [comment]
@tdykstra LGTM, just one suggestion for the exception on the read side: change to `throw new JsonException();`. Same thing for the existing `DateTimeOffset` converter.

**Pull request merged**
