### PR TITLE
Standardize See also sections

### PR DESCRIPTION
**Pull request by nxtn**
The same as #10064 

Contributes to #6923 

Hide white space changes for easier diff.

Used regex
pattern `^((\*|-)? )?(?<link>\[.*\]\(.*\)|<xref:.*>) *$`
replacement `- ${link}`

I'll check others next time.

@mairaw

### CODE REVIEW

**Comment by BillWagner** [comment]
Thanks for doing this work @NextTurn 

Can you address the merge conflicts?  We're back from a holiday  weekend, and we'll work to get this merged later today once those are addressed.

**Comment by NextTurn** [comment]
You got to office so early.

**Comment by BillWagner** [comment]
@NextTurn I work remotely. I'm in the Eastern US.

**Review by mairaw — APPROVED** [review]
Thanks @NextTurn for addressing these changes. I've resolved the merge conflicts for you so we could merge.

**Pull request merged**
