### PR TITLE
Update code snippets Image Classification tutorial

### PR DESCRIPTION
**Pull request by luisquintanilla**
Update code snippets Image Classification tutorial

[Image Classification API Preview URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning?branch=pr-en-us-15837)
[Issue Classification Preview URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification?branch=pr-en-us-15837)
[Image Classification Preview URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification?branch=pr-en-us-15837)
[Iris Clustering Preview URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/iris-clustering?branch=pr-en-us-15837)
[Anomaly Detection Preview URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sales-anomaly-detection?branch=pr-en-us-15837)
[TF Text Classification Preview URL](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/text-classification-tf?branch=pr-en-us-15837)

### CODE REVIEW

**Comment by luisquintanilla** [comment]
Retriggering build

**Comment by luisquintanilla** [comment]
@natke ready for review when you get a chance. Thanks.

**Comment by Youssef1313** [comment]
I'm wondering why you extensively reference code by line numbers ? I think using the `<SnippetNAME>` tags are much less likely to break. The line numbers break easily.

**Comment by luisquintanilla** [comment]
Thanks for the suggestion @Youssef1313 . You're right. Although that reduces breaking changes, it is not very readable for users not using Docs and just looking to get the sample.

**Review by natke — APPROVED** [review]

**Pull request merged**
