### PR TITLE
CC44268: Different ubuntu distributions

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @jralexander,  

This proposed file change comes from this Community Contribution:  https://github.com/dotnet/docs.ru-ru/pull/80. 
Please, help to check this proposed file change into the article and help to merge if you agree with fix. If not, please let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR, or if I should close this PR as by-design. In case of using another PR, please let me know of your PR number, so we can confirm and close this PR. 

Many thanks in advance.

Edit by @mairaw: removed PR template text

### CODE REVIEW

**Comment by mairaw** [comment]
@carolinacmoravia the original PR had more than that change. It also changed liblttng ust0 to liblttng-ust0. Any reasons not to include that too? 

@leecow can you verify this PR and also comment on the changing from liblttng ust0 to liblttng-ust0?

/cc @TheSima

**Comment by carolinacmoravia** [comment]
Hello, @mairaw, 

The suggestion sent by the contributor for source article was the proposed file change I commited. Thank you.

**Comment by mairaw** [comment]
That's not what I see in his PR @carolinacmoravia 

image

**Comment by carolinacmoravia** [comment]
Hello, @mairaw,

Thanks for your comment. I comitted the change I forgot by mistake. Thank you.

**Comment by leecow** [comment]
It should be `liblttng-ust0`

**Comment by TheSima** [comment]
Hello! 
@mairaw, please look at for what branch I created PR. It's "live" brench.
@carolinacmoravia, you last commit e8bb63d5255a5ebc635913fa5ca0e32002e6ce8c is excess for "master" brench.

**Comment by mairaw** [comment]
Now I see that the change was already in for liblttng-ust0 in the English repo but wrong in the Russian version.

@TheSima also, if you prefer to make the change and get the recognition, I can close this PR, since you found the issue. 

@leecow and the change from libkrb5 to libkrb5-3 is correct, right?

**Comment by TheSima** [comment]
@mairaw, my PR has a lot of rows changes. I think that this is unnecessary, use my PR. 
Only if you use two lines. I don't know why when I change the two lines he created such a massive difference. Maybe it's because of the language.

**Comment by TheSima** [comment]
@leecow libkrb5 was added in [PR](https://github.com/dotnet/docs/pull/3344).
But now libkrb5 not available in [Ubuntu packages](https://packages.ubuntu.com/search?keywords=libkrb5&searchon=names&suite=artful&section=all), last version is libkrb5-3.
What do you think about it?

**Comment by mairaw** [comment]
@TheSima, yes I think the diff is because of the languages. I'm not sure. I'll see if I can find out.

@leecow, as @TheSima pointed out, @Petermarcu added those a while back. The list you provided above is significantly different than what we have in the topic: https://github.com/dotnet/docs/blob/master/docs/core/linux-prerequisites.md#ubuntu

**Comment by mairaw** [comment]
I was going to follow-up offline on this but folks are off for the holidays already. Will need to come back to this in the new year.

**Comment by carolinacmoravia** [comment]
Thanks all for your replies. Awaiting for feedback.
Cc: @swgupt

**Comment by mairaw** [comment]
@leecow @Petermarcu ping after the holidays. Peter added the libkrb5 library on a recent PR but the list shared by Lee has very different libraries. Who has the definite list and can confirm whether this PR is good or not?

**Comment by carolinacmoravia** [comment]
Thanks all for your replies. Awaiting for feedback.
Cc: @swgupt

**Comment by carolinacmoravia** [comment]
Thanks all for your replies. Awaiting for feedback.
Cc: @swgupt

**Comment by mairaw** [comment]
@Petermarcu @leecow can you confirm this is the right change? Thanks!

**Comment by Petermarcu** [comment]
@janvorli

**Comment by janvorli** [comment]
Yes, this is a correct change. I am sorry for providing incorrect name for that library in the past. In all other cases, the dev and runtime package names differ just by the -dev suffix. This one is different for some reason and I haven't realized that.

**Comment by mairaw** [comment]
Thanks for confirming @janvorli!

**Review by mairaw — APPROVED** [review]

**Pull request merged**
