### PR TITLE
Updating ReadableExpressions screenshot and description

### PR DESCRIPTION
**Pull request by SteveWilkes**
Updating ReadableExpressions screenshot and description to be correct for the newly-released version 3.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for creating this PR @SteveWilkes I'm glad the project continues to improve.

I've reviewed the changes, and I'll :shipit: now.

**Comment by SteveWilkes** [comment]
Thanks very much, @BillWagner - further improvements are in the pipeline!

All the best,

Steve

**Comment by zspitz** [comment]
@SteveWilkes You may want to consider updating the [corresponding Visual Basic page](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio) as well.

**Comment by SteveWilkes** [comment]
Thanks @zspitz - I've got another PR at the moment so I've included those changes there :)

**Pull request merged**
