### PR TITLE
Update migration guides

### PR DESCRIPTION
**Pull request by chlowell**
@rpetrusha this includes everything as of Microsoft/dotnet#645

### CODE REVIEW

**Comment by rpetrusha** [comment]
The build is not listed in the OPS build portal. Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
Closing for a longer time, then reopening; the previous close/reopen did not initiate a new build.

**Comment by mairaw** [comment]
webhooks seem to be working at least

**Comment by rpetrusha** [comment]
Closing and reopening one last time before opening an LSI.

**Comment by rpetrusha** [comment]
Build failed for unspecified reasons. Closing and reopening.

**Comment by rpetrusha** [comment]
Build has failed once again. Closing and reopening to resume build (hopefully).

**Comment by rpetrusha** [comment]
@chlowell, we've split repos (see #4789), and the dotnet/docs repo now contains a sizable number of fixes that affect the migration. Could you do a fresh migration from the master branch of dotnet/docs, and then open a new PR? in the meantime, I'll close this PR.

**Pull request closed without merging**
