### PR TITLE
C76692: Adding break-lines (two spaces) at the end of rows

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @BillWagner,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: Missing break lines at the end of the spotted lines are preventing to show the content in one line instead of one line for every string

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by mairaw** [comment]
@v-maudel this makes the \ appear in the docs which is not our intention here. Does using \ at the end of sentences cause any issues for loc? Because we don't want to add the two spaces at the end back.

**Comment by BillWagner** [comment]
Should these just be code-fenced?  Would this be the correct presentation:

```xml
<system.ServiceModel>
<bindings>
<netMsmqBinding>
<binding>
<security>
<message>
```

**Comment by v-maudel** [comment]
Hi @BillWagner @mairaw , the proposed fix from Bill should work. Also I want to mention that in the localized page the last \ is visible. 
image
Maybe, if the \ shouldn't be visible we can remove it and that's perhaps fix the issue but I need to check it with the Bugfixing team first. I'm checking with the team, will let you know asap. 

Regards.

**Comment by mairaw** [comment]
For now, the code fence works. One day though I'd like to recover what we had on [MSDN](https://msdn.microsoft.com/en-us/library/6ebf0240-d7be-4493-b0fe-f00fd5989d77(v=vs.90)?toc=xxx) that we lost through the migrations.

**Review by mairaw — CHANGES_REQUESTED** [review]
Again, let's code fence this instead of adding spaces. And let's match the indentation we had in MSDN (node names are fine):

image

**Review by mairaw — APPROVED** [review]

**Comment by nemrism** [comment]
Almost all my changes in PRs pushed to solve #2037 & #2038 use the \ at end of lines...
Do you know if it still break the localization?

/cc @BillWagner / @v-maudel

**Pull request merged**
