### PR TITLE
Update and rename bc42358

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by BillWagner** [comment]
This now has merge conflicts. I'll review once those are addressed.

**Comment by Youssef1313** [comment]
@BillWagner, I've fixed the merge conflicts.

**Review by BillWagner — APPROVED** [review]
This LGTM. I'll :shipit: now.

**Comment by Youssef1313** [comment]
@BillWagner, Thanks for making Await as code fence. I'm wondering how can it be guaranteed that the localized repos has the exact same error message as the compiler shows it ?

**Comment by BillWagner** [comment]
That's a good question for @JasonCard

**Comment by JasonCard** [comment]
Hi @Youssef1313,
For loc repos to recycle the localized error message, you need to make sure the error message in English content is exactly the same as the actual error message in product including placeholders. Please let me know if you'd like me to follow up on specific error messages to see if existing translation can be recycled.

**Pull request merged**
