### PR TITLE
Update the 404 link for NETStandard.Library source

### PR DESCRIPTION
**Pull request by lamLeX**
## Details
 Update the link to NETStandard.Library source which is now in https://github.com/dotnet/standard/blob/master/netstandard/pkg/targets/NETStandard.Library.targets

### CODE REVIEW

**Comment by svick** [comment]
[The old file](https://github.com/dotnet/corefx/blob/71de1aac5cf3e5dc87714ae0cc829e1fa98f7c5d/pkg/NETStandard.Library/NETStandard.Library.packages.targets) contained a list of packages that are part of the metapackage, which is what I think made it useful. What is the point of linking to [the new file](https://github.com/dotnet/standard/blob/master/netstandard/pkg/targets/NETStandard.Library.targets)? I don't see one, so I think the link should be removed.

**Comment by BillWagner** [comment]
@svick That's a very good point.
@ericstj Can you comment on that point above? Is there a better place where the link should be re-directed?

**Comment by mairaw** [comment]
@Nirmal4G suggested this link (https://github.com/dotnet/standard/blob/master/netstandard/pkg/NETStandard.Library.dependencies.props) on a PR that was closed this morning since I'm working on this same topic. Should that be the new target?

**Comment by BillWagner** [comment]
@mairaw That would be the correct link.
@lamLeX Do you want to update the target on this PR? If not, we'll make the edit and accept the PR with the updated target.

**Comment by lamLeX** [comment]
@svick is correct. Most of the links for NETStardard has been moved to dotnet/standard repo. Since I couldn't find the original, I thought the new link I proposed is the correct one as it has the same name. 

@BillWagner: Is https://github.com/dotnet/standard/blob/master/netstandard/pkg/NETStandard.Library.dependencies.props correct? If so, I could update my target on this PR.

**Comment by BillWagner** [comment]
@lamLeX Yes, you have the correct target in the above comment. Thank you again.

**Review by BillWagner — APPROVED** [review]
Thanks for updating this @lamLeX 
This looks great. I'll :shipit: now.

**Comment by BillWagner** [comment]
Thank you for the updates.
I'll merge this as soon as the build finishes.

**Comment by lamLeX** [comment]
Thank all for helping me.
Contributing is a way I learn new thing.

**Pull request merged**
