### PR TITLE
Remove TDD language from tutorial

### LINKED ISSUE #6464: TDD misunderstood
Hi there,

It seems that you've misunderstood TDD in terms of fail first.  Yes, a test must fail the first time, but it is not because it is written wrong, it's because the business logic should not yet have been implemented. Once the test fails you then fix your business logic or method and once you've done that properly your test will pass.

My recommendation:

- Start by implementing the stubs of WordCount
- Write the correct tests the first time. The test will fail because you haven't implemented the actual WordCount only empty stubs.
- Implement WordCount so that the tests pass

= TDD

Writing a wrong test that fails and then correcting the test to pass is not TDD - I'm pretty sure it doesn't have a name or purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d01d28-eba7-401c-5716-1361edfa928d
* Version Independent ID: f235603a-edcc-257a-901e-b0709cf81053
* Content: [Building a complete .NET Core solution on macOS using Visual Studio for Mac](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution)
* Content Source: [docs/core/tutorials/using-on-mac-vs-full-solution.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-mac-vs-full-solution.md)
* Product: **dotnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #6464

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
These changes LGTM @guardrex 

I'll :shipit: now.  Thanks again for all your contributions to docs!  🎆

**Comment by allanlykkechristensen** [comment]
Thanks for taking the feedback onboard, much appreciated. I have to say that I still don't quite understand why you write "It's important to make a new test fail once to confirm its testing logic is correct."  It's like saying that it is important to write your code wrong and the write it correct. Why would I knowingly want to write wrong code?

**Comment by guardrex** [comment]
> It's like saying that it is important to write your code wrong and the write it correct. 

It's *helps* to ensure that the logic of the test is sound. On a couple of occasions, this step worked to my advantage. I wrote a test that required some complex config/set up, wrote the assertion to fail, and 😮 the bleed'in thing *PASSED!* Orf! :smile: Upon further examination, I wrote some bad test logic that I needed to fix. This scenario hasn't played out often for me, but it has saved me a couple of times. There's no ironclad guarantee that this step will save a dev. However, it can help.

**Comment by guardrex** [comment]
> when you've already implemented the code and doing the testing afterwards.

Yes, that's right. Exactly so.

**Pull request merged**
