### PR TITLE
removed translation tags from all files in repo

### PR DESCRIPTION
**Pull request by mikeblome**
Synced to master and removed ht and mt translation tags, without reformatting.

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Yay! You did it! Thanks @mikeblome! I'll merge as soon as build finishes.

**Comment by mairaw** [comment]
One of my PRs conflicted with yours. 😢 I'll rebase.

**Comment by mikeblome** [comment]
It’s easy for me to rerun and submit a new pr

**Comment by mairaw** [comment]
There are 3000+ merge conflicts. It'll be easier to run again the script.

**Pull request closed without merging**
