### PR TITLE
Reviewed the CLI topic

### LINKED ISSUE #1057: What does "IL code" mean in Core tools page?
In [Driver's section](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/#driver) of .NET Core Command Line Tools topic:

> ### Driver
> The driver is named dotnet. It is the first part of what you invoke. The driver has two responsibilities:
> 1. Executing IL code
> 2. Executing the verb

What does IL code and IL assembly mean? CC: @mairaw

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #1057 plus some other edits

/cc @blackdwarf

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/index?branch=pr-en-us-1124](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/index?branch=pr-en-us-1124)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C7%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610070128116552-1124%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/index?branch=pr-en-us-1124](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/index?branch=pr-en-us-1124)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C7%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610070129588492-1124%5Cworkflow_report.html).

**Comment by BillWagner** [comment]
LGTM.  Should we :shipit:?

**Comment by mairaw** [comment]
I wanted to make sure I'm using the right terminology here about the app types but I guess we can ship this and review it more carefully later on with @blackdwarf

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/index?branch=pr-en-us-1124](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/index?branch=pr-en-us-1124)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C13%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610131812579756-1124%5Cworkflow_report.html).

**Pull request merged**
