### PR TITLE
Updates for latest design

### PR DESCRIPTION
**Pull request by jasongroce**
# Updates to images for hub page

The design team has provided new images for this hub page; the original ones were placeholders until the icon designer came to the team.

## Summary

There are **21** updated SVG files, and the index.md file had to be updated to:
* Use a different card style (with images above instead of to the side)
* Apply the background accent style to images in the new card style

## Suggested Reviewers

@mairaw

### CODE REVIEW

**Comment by jasongroce** [comment]
@mairaw Can you take a look at this? The design team created new images for the hub, and then they also wanted to modify the card style to accommodate these. I don't know what your release schedule is like, but I just wanted to be able to provide a potential ETA to Design on this. Thanks!

**Comment by mairaw** [comment]
Sorry @jasongroce. I've been super busy. I can review this now.

**Review by mairaw — APPROVED** [review]
LGTM! @nokura FYI, the hub page is changing design.

**Comment by jasongroce** [comment]
Thanks @mairaw !

**Pull request merged**
