### PR TITLE
Update docs to state F# support for the .NET Core SDK

### PR DESCRIPTION
**Pull request by cartermp**
This addressed part of #1020.  /cc @mairaw

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.net.http.cookieusepolicy?branch=pr-en-us-1022](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.net.http.cookieusepolicy?branch=pr-en-us-1022)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.net.http.delegatinghandler?branch=pr-en-us-1022](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.net.http.delegatinghandler?branch=pr-en-us-1022)  
  [https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.fieldattributes?branch=pr-en-us-1022](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.fieldattributes?branch=pr-en-us-1022)  
  Please see 3429 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C14%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609141759039865-1022%5Cworkflow_report.html).

**Comment by mairaw** [comment]
Should we create the branch for the 1.0.0 release then to be safe? Before we start making changes that reflect the 1.0.1 release.

**Comment by cartermp** [comment]
Ah, good point.  Since we don't have versioning for the docs right now that's probably a good idea.

**Comment by mairaw** [comment]
Ok, branch created: https://github.com/dotnet/core-docs/tree/1.0.0

**Review by mairaw — APPROVED** [review]
LGTM

**Pull request merged**
