### PR TITLE
Format codes based on .editorconfig, Part 22

### PR DESCRIPTION
**Pull request by nxtn**
As you can see in the "Revert due to compilation errors" commits, a number of projects can't be compiled. It's too early to enable the build checks.

### CODE REVIEW

**Comment by NextTurn** [comment]
OK. The passing rate is 15%. :)

**Review by BillWagner — APPROVED** [review]
Thanks again @NextTurn 

We'll :shipit: now.

**Comment by BillWagner** [comment]
@NextTurn 
> It's too early to enable the build checks.

We haven't set this check as a blocking check yet. We knew this would expose a number of issues. In most cases, PRs modify one or two samples, and the build errors provide information that help us improve.

In the work you're doing for formatting code, we can tell by inspection that the change won't introduce new errors. 

ping @dotnet/docs  Should we formally agree to merge these editorconfig PRs without mandating a build fix?

The other option is to combine source code configuration fixes with creating buildable projects that address both concerns.

**Comment by tdykstra** [comment]
I vote for

>combine source code configuration fixes with creating buildable projects that address both concerns.

**Pull request merged**
