### PR TITLE
38). Add topic files 119 to 122

### PR DESCRIPTION
**Pull request by jameshkramer**
This PR is for user story #1576037.

It adds four article files, makes corresponding deletions from the C# and VB folders, and adds redirection entries. It also provides fixes to toc.yml and some article files.

Please merge #18299, #18325, #18413, #18439, #18541, #18580, and #18589 before merging this.

cc: @BillWagner @mairaw @tfosmark @marteeleigh

Contributes to #4728

### CODE REVIEW

**Review by BillWagner — COMMENTED** [review]
I gave this a quick look, and it looks good. Once the conflicts are resolved, I'll do a more thorough review and merge it.

Thanks again @jameshkramer

**Comment by mairaw** [comment]
@jameshkramer can you resolve the merge conflicts here?

**Comment by jameshkramer** [comment]
@mairaw  @BillWagner 

I resolved the conflicts - Jim

**Review by mairaw — CHANGES_REQUESTED** [review]
Changes look good but left some suggestions for some improvements

**Comment by jameshkramer** [comment]
@mairaw @BillWagner 

Maira, I made the changes you requested - Jim

**Review by mairaw — APPROVED** [review]
LGTM

**Pull request merged**
