### PR TITLE
BlockingCollection Overview

### PR DESCRIPTION
**Pull request by stevehoag**
Ported from MSDN

### CODE REVIEW

**Comment by svick** [comment]
Why does the text use VB generics syntax, when all code is in C#? (It seems that was inherited from the MSDN version.)

**Comment by stevehoag** [comment]
There is an issue with rendering C# generic syntax - escaping the brackets with a backslash doesn't work, so C# syntax doesn't show the generic parameters. Once that issue is resolved I'll fix up all of the topics.

We should be aware, however, that eventually we will also support VB and potentially other languages. On MSDN we could show language-specific versions of topics, but we can't do that in Markdown. We should make sure that everyone is okay with C# syntax being the default.

**Comment by mairaw** [comment]
I'm okay with the C# syntax being the default while we don't have language filtering capabilities and so on

**Comment by cartermp** [comment]
Yup.  It's also definitely the only language that's wholly first-class for .NET Core at the moment.  When we get F# support up to par and VB supported we can adjust these.

**Comment by stevehoag** [comment]
Fixed in #377

**Pull request closed without merging**
