### PR TITLE
Rename NullableContextOptions to Nullable

### PR DESCRIPTION
**Pull request by KexyBiscuit**
## Summary

Rename `NullableContextOptions` to `Nullable`.

See also dotnet/roslyn#35901.

### CODE REVIEW

**Review by drewnoakes — APPROVED** [review]

**Comment by BillWagner** [comment]
See #12417 

This PR addresses the changes in the C# Guide.

**Review by BillWagner — APPROVED** [review]
Thanks for making these updates @KexyBiscuit I'm grateful.

I've read through the changes and I'll :shipit: now.

Thanks again for helping to keep our docs up to date!  🎆

**Comment by rainersigwald** [comment]
This is the correct change moving forward, but I have a concern: the `Nullable` rename has not yet shipped in a .NET Core SDK preview. `3.0.100-preview5-011568` still uses the name `NullableContextOptions`, so `dotnet` CLI users might use these new instructions and then see confusing errors (the inverse of the confusing errors that VS 16.2-p1 users see with the old name).

**Comment by BillWagner** [comment]
@rainersigwald 

Good point.  I'll add more clarifying language in a new PR.

**Pull request merged**
