### PR TITLE
Normalize trailing spaces in samples, Part 1

### PR DESCRIPTION
**Pull request by nxtn**
Regex: ` +$`
Files: *.cs

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks @NextTurn 

I did a spot review of changes, and a spot review of the review site. This looks great.

I'll :shipit:

**Comment by Thraka** [comment]
With so many files changed, it's quite possible that a verbatim string would have been clipped by this regex replace.

**Comment by NextTurn** [comment]
Fair point. So I wrote a naive regex to find all verbatim strings with trailing spaces.

`@\$?"(""|[^"])* \r\n(""|[^"])*"`

#### dotnet/docs

```
docs\samples\snippets\csharp\roslyn-sdk\SemanticQuickStart\Program.cs
docs\samples\snippets\csharp\roslyn-sdk\SyntaxQuickStart\HelloSyntaxTree\Program.cs
docs\samples\snippets\csharp\roslyn-sdk\SyntaxQuickStart\SyntaxWalker\Program.cs
docs\samples\snippets\csharp\roslyn-sdk\SyntaxTransformationQuickStart\ConstructionCS\Program.cs
docs\samples\snippets\csharp\VS_Snippets_CLR\conceptual.regularexpressions.bestpractices\cs\design2.cs
docs\samples\snippets\csharp\VS_Snippets_Data\dp entityservices concepts\cs\entitysql.cs
docs\samples\snippets\csharp\VS_Snippets_Data\dp entityservices concepts\cs\source.cs
docs\samples\snippets\csharp\VS_Snippets_Data\dp entityservices concepts 2\cs\entitysql.cs
docs\samples\snippets\csharp\VS_Snippets_Data\DP ObjectServices Concepts\CS\Source.cs
dotnet-api-docs\samples\snippets\csharp\api\system.xml\xmlexception\Program.cs
```

#### dotnet/dotnet-api-docs

```
dotnet-api-docs\samples\snippets\csharp\api\system.xml\xmlexception\Program.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_ADO.NET\DataWorks DbConnectionStringBuilder.Remove\CS\source.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_ADO.NET\system_data_isolationlevel\cs\source.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Atlas\System.Web.UI.ScriptReference\CS\customcontrol.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_CLR\Cryptography.XML.XmlDsigXsltTransform\CS\sample.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_CLR_System\system.globalization.idnmapping.getascii\cs\conversion1a.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_CLR_System\system.Linq.Enumerable\CS\enumerable.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Data\DP ObjectServices Concepts\CS\Source.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Data\eSQLBasicExamples\CS\Program.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Data\XmlTextReader.LineNum\CS\readlinenum.cs
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Winforms\Control.Validating\CS\validating.cs
```

#### dotnet/samples

*None.*

**Comment by NextTurn** [comment]
The matches consist of the followings:

#### C#

<details>
<summary>
docs\samples\snippets\csharp\roslyn-sdk\SemanticQuickStart\Program.cs
</summary>

```cs
@"using System;
using System.Collections.Generic;
using System.Text;
 
namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(""Hello, World!"");
        }
    }
}"
```

</details>

<details>
<summary>
docs\samples\snippets\csharp\roslyn-sdk\SyntaxQuickStart\HelloSyntaxTree\Program.cs
</summary>

```cs
@"using System;
using System.Collections;
using System.Linq;
using System.Text;
 
namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(""Hello, World!"");
        }
    }
}"
```

</details>

<details>
<summary>
docs\samples\snippets\csharp\roslyn-sdk\SyntaxQuickStart\SyntaxWalker\Program.cs
</summary>

```cs
@"using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
 
namespace TopLevel
{
    using Microsoft;
    using System.ComponentModel;
 
    namespace Child1
    {
        using Microsoft.Win32;
        using System.Runtime.InteropServices;
 
        class Foo { }
    }
 
    namespace Child2
    {
        using System.CodeDom;
        using Microsoft.CSharp;
 
        class Bar { }
    }
}"
```

</details>

<details>
<summary>
docs\samples\snippets\csharp\roslyn-sdk\SyntaxTransformationQuickStart\ConstructionCS\Program.cs
</summary>

```cs
@"using System;
using System.Collections;
using System.Linq;
using System.Text;
 
namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(""Hello, World!"");
        }
    }
}"
```

</details>

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Atlas\System.Web.UI.ScriptReference\CS\customcontrol.cs
</summary>

```cs
@"
Sys.Application.add_load(function(sender, args) {{
var {0}_borderAnimation = new BorderAnimation('{1}');    
var panelElement = document.getElementById('{0}');
     if (args.get_isPartialLoad()) {{
        {0}_borderAnimation.animate(panelElement);
    }}
}})
"
```

</details>

#### C# fragments (due to regex flaws)

<details>
<summary>
docs\samples\snippets\csharp\VS_Snippets_CLR\conceptual.regularexpressions.bestpractices\cs\design2.cs
</summary>

```cs
@"));       
         int index = 0;
         for (int ctr = mailBox.Length - 1; ctr >= 0; ctr--) {
            index++;

            input = mailBox.Substring(ctr, index); 
            sw = Stopwatch.StartNew();
            Match m = Regex.Match(input, pattern, RegexOptions.IgnoreCase);
            sw.Stop();
            if (m.Success)
               Console.WriteLine("
```

</details>

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_CLR_System\system.globalization.idnmapping.getascii\cs\conversion1a.cs
</summary>

```cs
@");
            if (position >= 0) 
               name = name.Substring(position + 1);

            string punyCode = idn.GetAscii(name);
            string name2 = idn.GetUnicode(punyCode);
            Console.WriteLine("
```

</details>

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Winforms\Control.Validating\CS\validating.cs
</summary>

```cs
@") )
      {
         errorMessage = "";
         return true;
      }
   }
   
   errorMessage = "
```

</details>

#### XML

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\api\system.xml\xmlexception\Program.cs
</summary>

```cs
@"<Contacts>  
            <Contact>  
                <Name>Jim Wilson</Name>  
            </Contact>  
          </Contcts>"
```

</details>

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_CLR\Cryptography.XML.XmlDsigXsltTransform\CS\sample.cs
</summary>

```cs
@"
    <xs:transform xmlns:xs='http://www.w3.org/1999/XSL/Transform' version='1.0'>
        <xs:template match='/'>
            <xs:apply-templates/>
        </xs:template>
        <xs:template match='ElementToTransform'> 
            <transformedElement/>
        </xs:template>
    </xs:transform>"
```

</details>

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_Data\XmlTextReader.LineNum\CS\readlinenum.cs
</summary>

```cs
@"<book> 
         <misc>
           <style>paperback</style> 
           <pages>240</pages>
         </misc> 
        </book>"
```

</details>

#### Plain Text

<details>
<summary>
dotnet-api-docs\samples\snippets\csharp\VS_Snippets_CLR_System\system.Linq.Enumerable\CS\enumerable.cs
</summary>

```cs
@"The collection does not contain exactly 
                                one element whose length is greater than 15."
```

</details>

#### SQL

*All other matches.*

**Pull request merged**
