### PR TITLE
fix broken uid links

### PR DESCRIPTION
**Pull request by mairaw**
OPS build logs had warnings about broken API links so this should fix them.

/cc @stevehoag

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.labeltarget?branch=pr-en-us-985)

**Comment by stevehoag** [comment]
LGTM

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.compilerservices.configuredtaskawaitable.configuredtaskawaiter?branch=pr-en-us-985)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.compilerservices.configuredtaskawaitable-1.configuredtaskawaiter?branch=pr-en-us-985)

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.compilerservices.configuredtaskawaitable.configuredtaskawaiter?branch=pr-en-us-985)

**Comment by mairaw** [comment]
All warnings are gone now.

**Pull request merged**
