### PR TITLE
Edit pass on ASP.NET Core migration eBook PR

### PR DESCRIPTION
**Pull request by scottaddie**

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @scottaddie 

Thanks for doing this work.

**Comment by BillWagner** [comment]
Ping @nschonni 

Can you help us with a fix for the markdownlint warning in this PR? It looks like there is an issue interpreting an example regular expression as an invalid markdown link.

**Comment by nschonni** [comment]
If you look at the [rendered page](https://github.com/dotnet/docs/blob/395666aec1a76675a55cab97621afe4be6dbd251/docs/standard/base-types/regular-expression-example-scanning-for-hrefs.md), it's tripping on the unescaped `|` in ``(?:\["'\](?<1>\[^"'\]*)["']|(?<1>\S+))``, which I think @DavidAnson flagged in another PR was going to start breaking in the new version as that breaks markdown tables in general

**Comment by DavidAnson** [comment]
Right, here is the PR @nschonni is referring to: https://github.com/dotnet/docs/pull/21977

**Review by nishanil — APPROVED** [review]

**Pull request merged**
