### PR TITLE
Refresh six I/O task articles

### PR DESCRIPTION
**Pull request by v-thepet**
## Summary

Refresh
how-to-read-and-write-to-a-newly-created-data-file.md
how-to-open-and-append-to-a-log-file.md
how-to-read-text-from-a-file.md
how-to-read-characters-from-a-string.md
how-to-write-characters-to-a-string.md
composing-streams.md

Per User Story 
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1374049/?triage=true

### CODE REVIEW

**Comment by v-thepet** [comment]
@rpetrusha - @rpetrusha - Ready for review per Tasks 
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385010/?triage=true
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385011/?triage=true
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385014/?triage=true
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385015/?triage=true
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385018/?triage=true
https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385021/?triage=true
Thanks.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for improving these topics, @v-thepet. I've left a few comments on the text in these topics, but mostly comments about changes to the code samples.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
f

**Comment by v-thepet** [comment]
@rpetrusha - I've updated the links to point to the new, now-merged code samples. Please take a look at the new samples in how-to-read-text-from-a-file.md, how-to-read-characters-from-a-string.md, and how-to-write-characters-to-a-string.md. Then this PR should be ready for merge. Thanks!

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
Thanks for your work on these topics, @v-thepet. You've significantly improved them. I'll merge your PR now.

**Pull request merged**
