### PR TITLE
Fix broken link

### LINKED ISSUE #12305: Broken link
Hi the link in the section:
Experiments are highly configurable. See the AutoML API docs for a full list of configuration settings.
does not work and returns a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bb37d9-1c4d-5d5f-2ed6-2ef77f2cd627
* Version Independent ID: 80ed0d4d-63d3-49f0-ae42-d1f132137352
* Content: [How to use the ML.NET automated ML API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api)
* Content Source: [docs/machine-learning/how-to-guides/how-to-use-the-automl-api.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/how-to-use-the-automl-api.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

### PR DESCRIPTION
**Pull request by JRAlexander**
Fixes #12305

Preview link: https://review.docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api?branch=pr-en-us-12331

### CODE REVIEW

**Review by luisquintanilla — APPROVED** [review]

**Comment by mairaw** [comment]
It's weird that this is giving a warning. The link should work: https://xref.docs.microsoft.com/autocomplete?text=Microsoft.ML.AutoML
The other possibility would be to change it to https://docs.microsoft.com/dotnet/api/microsoft.ml.automl

**Comment by natke** [comment]
I think I know why this happened. The moniker was changed after this article was published.

**Review by natke — CHANGES_REQUESTED** [review]
The xref is not working, and I am not sure why.

**Comment by JRAlexander** [comment]
Thanks, I've been investigating since it built. No clue so far.

**Comment by Thraka** [comment]
@JRAlexander Since this PR is alive to fix an issue, put the labels (P0, DOC-BUG) on the issue and leave the PR clean.

**Comment by natke** [comment]
You could use one of these URLs instead: 
- https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl?view=automl-dotnet
- https://docs.microsoft.com/en-us/dotnet/api/?view=automl-dotnet

In fact, the second one would probably be better, as they it future proof against new namespaces being added to this API

**Comment by JRAlexander** [comment]
That still doesn't fix the underlying problem. Once the xref is fixed, I'll circle back around and replace the url with it.

**Comment by Thraka** [comment]
What about changing it to a `<xref:` style link?

**Comment by JRAlexander** [comment]
Testing that. If that doesn't work we'll use the URL for now to fix the link and investigate further offline.

**Review by natke — APPROVED** [review]

**Comment by JRAlexander** [comment]
Thanks @natke and @luisquintanilla!!

**Pull request merged**
