### PR TITLE
Thread-Safe Collections

### PR DESCRIPTION
**Pull request by stevehoag**
Ported from MSDN

### CODE REVIEW

**Comment by svick** [comment]
Does talking about `Synchronized` non-generic collections so much here make sense? I doubt that information would be useful to people writing for .Net Core.

**Comment by stevehoag** [comment]
Are you saying that they aren't supported, or just that they won't commonly be used in .NET Core? If the latter, does having this info dtract from the article?

**Comment by svick** [comment]
I believe they are supported, but I think they will be used only very rarely.

I think it does detract from the article: if I'm looking for general info about Thread-Safe Collections, I don't want it to start with several paragraphs telling me about an old obscure feature I shouldn't use. At the very least, I think that section shouldn't be the first section of the article.

**Comment by cartermp** [comment]
@svick makes a good point here.  The first section of the article reads to me as "in the past you did this, but you should really do this other thing".  That's going to be irrelevant for anyone new to .NET.  May be worth moving that down to the bottom.

**Comment by stevehoag** [comment]
Makes sense. I think these articles were written for 4.0 when all of this was new, and they've never been updated. I'll fix it.

**Comment by stevehoag** [comment]
Fixed in #376

**Pull request closed without merging**
