### PR TITLE
Changes for .NET Core 1.0.1 release

### LINKED ISSUE #862: Windows prerequisites topic questions
I have a few questions about the following topic:
https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites

- We mention Windows 7+, etc. The + sign is not a common convention for international customers so I think we should change to Windows 7 and later versions or something like that. 
- Why do we specifically call out the nano server? Isn't that already covered by Server 2012 R2+?
- I was a bit confused by the VS instructions. Do you need to first install Update 3 to later upgrade to 3.3?

/cc @BillWagner

### PR DESCRIPTION
**Pull request by mairaw**
Addresses changes needed for #1020 (maybe there are more changes needed?)
Fixes #862 

/cc @richlander, @BillWagner, @leecow

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1041](https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1041)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites?branch=pr-en-us-1041](https://review.docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites?branch=pr-en-us-1041)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1041](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1041)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609200024340532-1041%5Cworkflow_report.html).

**Comment by BillWagner** [comment]
closing and reopening to restart the build.

**Comment by BillWagner** [comment]
Looks good to me. Let's :shipit: once the build completes successfully.

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1041](https://review.docs.microsoft.com/en-us/dotnet/articles/core/getting-started?branch=pr-en-us-1041)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites?branch=pr-en-us-1041](https://review.docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites?branch=pr-en-us-1041)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1041](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1041)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609200212078425-1041%5Cworkflow_report.html).

**Pull request merged**
