### PR TITLE
These two links are 404s

### PR DESCRIPTION
**Pull request by johnkors**
No idea where they _should_ go, but at the moment they lead into the great land of 404.

### CODE REVIEW

**Comment by svick** [comment]
I think the right URLs are https://dotnetfoundation.org/net-core and https://dotnetfoundation.org/asp-net-core. Do you want to update your PR with those links?

**Comment by rpetrusha** [comment]
@johnkors, the URLs that @svick lists are correct.

**Comment by johnkors** [comment]
Thanks, updated!

**Review by rpetrusha — APPROVED** [review]
Thanks for making these corrections, @johnkors. I'll merge.

**Comment by johnkors** [comment]
No probs! Btw, 

I recommend setting up something like [LinkCrawler](https://github.com/hmol/LinkCrawler) (from @hmol) so you catch these 404s yourself :)

**Pull request merged**
