### PR TITLE
Fix #19203

### LINKED ISSUE #19203: Spacing to make the code more clear.
I recommend adding a line return after each section of code to make the page easier to read. Like this:

Dim MyString As String = "This is my string"
Dim stringLength As Integer

' Explicitly set the string to Nothing.
MyString = Nothing

' stringLength = 0
stringLength = Len(MyString)

' This line, however, causes an exception to be thrown.
stringLength = MyString.Length

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e57009-1296-4ae4-c497-332326352dfe
* Version Independent ID: c3957d71-7ed9-9c27-9f31-746e012a08e2
* Content: [Nothing and Strings - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/strings/nothing-and-strings)
* Content Source: [docs/visual-basic/programming-guide/language-features/strings/nothing-and-strings.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/strings/nothing-and-strings.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

VB spacing concerns. Added lines before comments for readability.

Fixes #19203

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @IEvangelist 

You can :shipit: when ready.

**Comment by adegeo** [comment]
@BillWagner The CI isn't passing :) We're going to use this as a test case next wed for a config file to control the compile options used to test the code (choosing visual studio msbuild over dotnet core msbuild)

**Comment by IEvangelist** [comment]
> @BillWagner The CI isn't passing :) We're going to use this as a test case next wed for a config file to control the compile options used to test the code (choosing visual studio msbuild over dotnet core msbuild)

Hi @adegeo - did you use this for the test cases yesterday?

**Comment by adegeo** [comment]
I decided to work on some other stuff yesterday. I'm going to hit it this morning.

**Comment by adegeo** [comment]
@IEvangelist OK, do the following once #19295 is merged:

01. Close the PR.
02. Add a file adjacent to the project named `snippets.5000.json` with the following content:
    ```json
    {
        "host": "visualstudio"
    }
    ```
03. Commit and upload the change to your branch.
04. Reopen the PR.

**Pull request closed without merging**
