### PR TITLE
Fix display speed functionality in Console app tutorial

### PR DESCRIPTION
**Pull request by adudsic**
## Summary

1. Update variable name "line" to "word" to match previous **ShowTeleprompter()** code block.
2. Revise **ReadKey** code. 

    **Explanation:** I created the app per instructions (```dotnet new console -o myApp```) and opened it in Visual Studio 2017. Project properties shows that the **Target framework** is *.NET Core 2.1*. Arrow keys did not affect output speed.

    The topic [ConsoleKeyInfo.KeyChar Property](https://docs.microsoft.com/en-us/dotnet/api/system.consolekeyinfo.keychar?view=netcore-2.1#System_ConsoleKeyInfo_KeyChar) doesn't list keys that can or cannot be captured, but it *does* say that it applies to .NET Framework 4.7.2.

    The **KeyChar** topic in .NET Framework 4.7.2 documents **KeyChar** as part of the Windows.Forms namespace, but I'm assuming it will likely behave the same as **KeyChar** in the Console namespace.  According to the **Remarks** in the .NET Framework 4.7.2 [KeyPressEventArge.KeyChar Property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keypresseventargs.keychar?view=netframework-4.7.2) topic, you cannot use the **KeyChar** property to get the arrow keys.

    Proposed code change causes left and right arrow keys to function as intended.

### CODE REVIEW

**Comment by pkulikov** [comment]
@adudsic 
>Arrow keys did not affect output speed.

Those arrow keys are the ones for navigation to left/right? I think the tutorial is implemented to react on the keys with `<` (less than) and `>` (greater than). Moreover, those keys should be pressed with a `Shift` key. 

However, if the arrow-to-left and arrow-to-right keys work and are less cumbersome, let's continue with them. Then the following sentence in the tutorial should be updated to refer to the arrow keys:
>You can speed up or slow down the pace by pressing the ‘<’ or ‘>’ keys.

Moreover, the referenced C# project in the **dotnet/samples** should be updated as well:
https://github.com/dotnet/samples/tree/master/csharp/getting-started/console-teleprompter

**Comment by adudsic** [comment]
Wow; I didn't even think of the greater-than/less-than keys. I immediately thought the reference was to the inverted-T navigation arrows. However, my office neighbor assumed the text meant "greater than" and "less than" keys.

**Question:** What do you want to do, A or B?
    A. Continue with code that gets the greater-than and less-than keys; or 
    B. Update to code that gets the left-arrow nav and right-arrow nav keys.

If A. (which may be better--code is already good as-is, and we're certain that all keyboards have those keys), then I suggest revising the texts as you did in your explanation above so that parenthetically you name the keys. I.e.: The three times in the text when keys are referred to would be revised as follows:
    **Reference 1:** "You can speed up or slow down the pace by pressing the ‘<’ (less than) or ‘>’ (greater than) keys."
    **Reference 2:** "...watch for the ‘<’ (less than) and ‘>’ (greater than) keys."
    **Reference 3:** "...when the user presses the ‘<’ (less than) or ‘>’ (greater than) keys."

If B. (which I agree think are a bit less cumbersome), then I would revise references as follows:
    **Reference 1:** "You can speed up or slow down the pace by pressing the ‘<’ (left arrow) or ‘>’ (right arrow) keys."
    **Reference 2:** "...watch for the ‘<’ (left arrow) and ‘>’ (right arrow) keys."
    **Reference 3:** "...when the user presses the ‘<’ (left arrow) or ‘>’ (right arrow) keys."

**Comment by pkulikov** [comment]
I would go with the variant A as it introduces the least amount of changes. 
@BillWagner what do you think?

**Comment by BillWagner** [comment]
This is a great conversation.

> Question: What do you want to do, A or B?
> A. Continue with code that gets the greater-than and less-than keys; or
> B. Update to code that gets the left-arrow nav and right-arrow nav keys.

I agree that **A** is preferred. This tutorial should work on a PC, Mac, or Linux box. That should include Docker containers and a remote shell. That will be easiest if we stay with the < (greater than> and > (less than> keys.

**Review by BillWagner — APPROVED** [review]
Thanks for creating this change @adudsic 

And thanks for contributing to the discussion @pkulikov 

This is a great set of changes, and I'll :shipit: now.

Thanks again.

**Pull request merged**
