### PR TITLE
Dotnet refresh create service app - remove inline code

### PR DESCRIPTION
**Pull request by dksimpson**
## Summary

Task 1409933: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1409933/

Replace inline C# code with repo code to correspond with VB code sections. 
Replace inline code with highlighted repo code in Startup parameters section. See PR: https://github.com/dotnet/samples/pull/755

### CODE REVIEW

**Comment by dksimpson** [comment]
The new repo code is in this PR: #https://github.com/dotnet/samples/pull/755
Once its approved and merged, we can merge this PR.

**Comment by dksimpson** [comment]
Related PR #dotnet/samples#755 has now been merged. 
Therefore this PR can be safely merged.
#sign-off

**Comment by dksimpson** [comment]
Hi @rpetrusha, this PR can now be merged.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Review by rpetrusha — APPROVED** [review]
Thanks, @dksimpson. Your changes look good. I apologize for the delay in responding to your PR, which I'll merge now.

**Pull request merged**
