### PR TITLE
Add link to and sample code application to post

### LINKED ISSUE #1000: Include sample code for Building Docker .NET Images
This topic https://github.com/dotnet/core-docs/blob/master/docs/core/docker/building-net-docker-images.md

docs not have the code it uses for its sample in the repo. It should.

The contributing guide references where to put samples, and based on those guidelines, this sample should go under samples/core.  I'll recommend making a new samples/core/docker directory for all the xplat Docker based samples.

The topic should provide a link to the GitHub folder where the sample code resides. That makes it easy for customers to download the sample, or explore any of the files online.

This would give a single directory where building samples may include building Docker images, or starting containers to execute tests.  Our CI system does not currently execute any Docker specific commands, but that has been requested.

In addition, where code has been included in the topic, we can replace the inline code with included regions from the sample code. (See the F# Tour or the C# Tour for examples of the syntax).

/cc @dend for discussion of any enhancements needed for the CI build system.

### PR DESCRIPTION
**Pull request by spboyer**
Added sample code for https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images

Fixes #1000 

@BillWagner to review

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/docker-update/docs/core/docker/building-net-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images?branch=pr-en-us-1215) | [Details](#user-content-docs/core/docker/building-net-docker-images.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C8%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611082014392565-1215%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by BillWagner** [comment]
Closing and re-opening to kick off the CI build for samples.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/docker-update/docs/core/docker/building-net-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images?branch=pr-en-us-1215) | [Details](#user-content-docs/core/docker/building-net-docker-images.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C8%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611082100563211-1215%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/docker-update/docs/core/docker/building-net-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images?branch=pr-en-us-1215) | [Details](#user-content-docs/core/docker/building-net-docker-images.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C8%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611082115474429-1215%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/docker-update/docs/core/docker/building-net-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images?branch=pr-en-us-1215) | [Details](#user-content-docs/core/docker/building-net-docker-images.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611090108177229-1215%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/docker-update/docs/core/docker/building-net-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images?branch=pr-en-us-1215) | [Details](#user-content-docs/core/docker/building-net-docker-images.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611090325362552-1215%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/docker-update/docs/core/docker/building-net-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images?branch=pr-en-us-1215) | [Details](#user-content-docs/core/docker/building-net-docker-images.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611090328003239-1215%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
