### PR TITLE
Use latest markdown engine

### PR DESCRIPTION
**Pull request by mairaw**
Trying the alternative solution for issue #1951.

/cc @svick

### CODE REVIEW

**Comment by mairaw** [comment]
I just checked the results on our private repo where the engineering team has tested this and it seems to fix the issue:
image

**Comment by svick** [comment]
Yeah, if it can be fixed without a huge, potentially buggy PR, then that sounds like the better option to me.

**Comment by mairaw** [comment]
Still build **sigh**

**Comment by mairaw** [comment]
OPS portal shows this has finished building and PR is still processing. I'll close and reopen to see if we can get CI to pass.

**Comment by mairaw** [comment]
/cc @BillWagner @rpetrusha 

It looks like this fixes the issue. See:
- https://review.docs.microsoft.com/en-us/dotnet-new/api/Microsoft.Build.Utilities.MuxLogger?branch=pr-en-us-1999&view=netframework-4.7
- https://review.docs.microsoft.com/en-us/dotnet-new//articles/framework/wpf/app-development/wpf-windows-overview?branch=pr-en-us-1999&view=netframework-4.7#order-of-precedence-for-sizing-properties

Can I merge?

**Review by BillWagner — APPROVED** [review]
:shipit: :shipit: 🎆

**Pull request merged**
