### PR TITLE
Snippet spacing and indentation touch-ups

### PR DESCRIPTION
**Pull request by guardrex**
I noticed on https://github.com/dotnet/docs/pull/2151/ that snippets needed a touch of line spacing and indentation work. This makes a quick pass to drop extra line spaces, fix indentation, and standardize output comments. I'll come back on another PR later to get the programming-guide batch done.

Note: The `if` keyword doc states ...

> For a single statement, the braces are optional but recommended.

... but a number of the snippets don't adhere to this advice. Let me know if you'd like to see those snippets outside of the `if` keyword example (of not using braces) converted to using braces.

Addresses #2156

### CODE REVIEW

**Comment by rpetrusha** [comment]
@GuardRex, I'm not sure whether others will agree, but personally, since braces are optional, I'd be inclined to leave existing `if` statements as is. I suspect that there are thousands of statements that are unbracketed in all of the examples.

**Comment by GuardRex** [comment]
It was just the statement "but recommended" followed by a number of snippets without them that seemed contradictory. I didn't change any of them.

I was just trying to get the indentation and line spacing happy. Truly, I showed up to just do ONE file that I spotted chatting with @svick. lol ... then saw a 2nd ... a 10th ... pretty soon 250+ files later (yikes!), here we are. This was a quick PR to put together, so if @mairaw wants to close and come back later, I'm good.

**Comment by mairaw** [comment]
Actually, we need to fix some of those in a different way. All of the C# and VB content got migrated and broken down into thousand of little snippets instead of a central location as we did for the .NET reference.
We might have to ask them to do a new "export" of the C# and VB content on a separate branch that uses the central location for snippets and then we do a diff of that content somehow and delete those inner snippets. My vote would be to fix this the right way soon instead of changing these little snippets.

**Comment by GuardRex** [comment]
... in which case we close here, correct? It's no worries ... this actually didn't take long, so it isn't a big deal to close it.

**Pull request closed without merging**
