### PR TITLE
[BULK UPDATE] DocuTune - Add ms.custom tags for horizontals

### PR DESCRIPTION
**Pull request by dbradish-microsoft**
Add ms.custom tags for horizontals

CorrelationId: c81e3608-8fcd-4296-8dea-28909aaeded4
PointOfContact: @dbradish-microsoft

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md) | [What OS to target with .NET containers](https://review.learn.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/net-container-os-targets?branch=pr-en-us-39865) |
| [docs/core/compatibility/3.0.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/3.0.md) | [Breaking changes in .NET Core 3.0](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/3.0?branch=pr-en-us-39865) |
| [docs/core/compatibility/containers/8.0/app-user.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/containers/8.0/app-user.md) | [New non-root 'app' user in Linux images](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/app-user?branch=pr-en-us-39865) |
| [docs/core/compatibility/containers/8.0/debian-version.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/containers/8.0/debian-version.md) | [docs/core/compatibility/containers/8.0/debian-version](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/debian-version?branch=pr-en-us-39865) |
| [docs/core/compatibility/containers/8.0/multi-platform-tags.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/containers/8.0/multi-platform-tags.md) | [Multi-platform container tags are Linux-only](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/multi-platform-tags?branch=pr-en-us-39865) |
| [docs/core/compatibility/cryptography.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/cryptography.md) | [Cryptography breaking changes](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography?branch=pr-en-us-39865) |
| [docs/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux.md) | [Default TLS cipher suites for .NET on Linux](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux?branch=pr-en-us-39865) |
| [docs/core/compatibility/cryptography/7.0/x500-distinguished-names.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/cryptography/7.0/x500-distinguished-names.md) | [docs/core/compatibility/cryptography/7.0/x500-distinguished-names](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/7.0/x500-distinguished-names?branch=pr-en-us-39865) |
| [docs/core/compatibility/deployment/8.0/monitor-image.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/deployment/8.0/monitor-image.md) | [.NET Monitor only includes distroless images](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/monitor-image?branch=pr-en-us-39865) |
| [docs/core/compatibility/networking/7.0/ping-custom-payload-linux.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/compatibility/networking/7.0/ping-custom-payload-linux.md) | ["Breaking change: Custom ping payloads on Linux"](https://review.learn.microsoft.com/en-us/dotnet/core/compatibility/networking/7.0/ping-custom-payload-linux?branch=pr-en-us-39865) |
| [docs/core/deploying/native-aot/cross-compile.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/deploying/native-aot/cross-compile.md) | [Cross-compilation](https://review.learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/cross-compile?branch=pr-en-us-39865) |
| [docs/core/diagnostics/debug-linux-dumps.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/diagnostics/debug-linux-dumps.md) | [docs/core/diagnostics/debug-linux-dumps](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-linux-dumps?branch=pr-en-us-39865) |
| [docs/core/diagnostics/dotnet-dump.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/diagnostics/dotnet-dump.md) | [Dump collection and analysis utility (dotnet-dump)](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump?branch=pr-en-us-39865) |
| [docs/core/diagnostics/dotnet-sos.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/diagnostics/dotnet-sos.md) | [dotnet-sos diagnostic tool - .NET CLI](https://review.learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-sos?branch=pr-en-us-39865) |
| [docs/core/docker/container-images.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/docker/container-images.md) | [.NET container images](https://review.learn.microsoft.com/en-us/dotnet/core/docker/container-images?branch=pr-en-us-39865) |
| [docs/core/install/how-to-detect-installed-versions.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/how-to-detect-installed-versions.md) | [How to check that .NET is already installed](https://review.learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?branch=pr-en-us-39865) |
| [docs/core/install/linux-alpine.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-alpine.md) | [docs/core/install/linux-alpine](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-alpine?branch=pr-en-us-39865) |
| [docs/core/install/linux-centos.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-centos.md) | [Install the .NET SDK or the .NET Runtime on CentOS Linux](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-centos?branch=pr-en-us-39865) |
| [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-debian.md) | [Install .NET on Debian](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-debian?branch=pr-en-us-39865) |
| [docs/core/install/linux-fedora.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-fedora.md) | [Install the .NET SDK or the .NET Runtime on Fedora](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-fedora?branch=pr-en-us-39865) |
| [docs/core/install/linux-opensuse.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-opensuse.md) | [docs/core/install/linux-opensuse](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-opensuse?branch=pr-en-us-39865) |
| [docs/core/install/linux-package-mixup.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-package-mixup.md) | [Troubleshoot .NET errors related to missing files on Linux](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?branch=pr-en-us-39865) |
| [docs/core/install/linux-rhel.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-rhel.md) | [Install .NET on RHEL and CentOS Stream](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-rhel?branch=pr-en-us-39865) |
| [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-scripted-manual.md) | [Install .NET on Linux by using an install script or by extracting binaries](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual?branch=pr-en-us-39865) |
| [docs/core/install/linux-sles.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-sles.md) | [docs/core/install/linux-sles](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-sles?branch=pr-en-us-39865) |
| [docs/core/install/linux-ubuntu-1604.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-ubuntu-1604.md) | [Install .NET SDK or .NET Runtime on Ubuntu 16.04](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-1604?branch=pr-en-us-39865) |
| [docs/core/install/linux-ubuntu-1804.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-ubuntu-1804.md) | [Install .NET on Ubuntu 18.04](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-1804?branch=pr-en-us-39865) |
| [docs/core/install/linux-ubuntu-2004.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-ubuntu-2004.md) | [Install .NET SDK or .NET Runtime on Ubuntu 20.04](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2004?branch=pr-en-us-39865) |
| [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux-ubuntu.md) | [Get Ubuntu version](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu?branch=pr-en-us-39865) |
| [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/17044f546c8cdc4ccc22cc4b71b1cae2bc595822/docs/core/install/linux.md) | [docs/core/install/linux](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux?branch=pr-en-us-39865) |

</details>

> **Note**
> This table shows preview links for the 30 files with the most changes. For preview links for other files in this PR, select <strong>OpenPublishing.Build Details</strong> within [checks](https://github.com/dotnet/docs/pull/39865/checks).

### CODE REVIEW

**Review by psfinaki — APPROVED** [review]
F# ok

**Comment by adegeo** [comment]
Hello @dbradish-microsoft can you please let me know what this is for? It seems odd to tag include files. What is the criteria?

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Comment by gewarren** [comment]
Ping @dbradish-microsoft. Can you explain what this is for?

**Comment by adegeo** [comment]
I also pinged internally, but no response.

**Comment by dbradish-microsoft** [comment]
#sign-off

[gewarren](https://github.com/gewarren), This PR does not require ms.author review as it is part of a DocuTune bulk update to keep ms.custom values correct for horizontals (Azure CLI, Azure PowerShell, Terraform, Bicep, ARM Templates, Python, Java, JavaScript, SDK for Go etc.).

**Review by adegeo — APPROVED** [review]
My stuff looks fine.

**Pull request merged**
