### PR TITLE
Fix the docker-compose example

### PR DESCRIPTION
**Pull request by timotei**
# Title
Fix the docker-compose example

## Summary
Fix the names of the microservices

### CODE REVIEW

**Comment by GuardRex** [comment]
@timotei Yes, indeed. *Thank you* for fixing these incorrect references in the topic.

There is one more on line 249 that refers to "basket." Would you like me to accept and merge this and patch it later, or would you like to fix line 249, too?

> -   Links the web service to the basket and ordering service with the depends\_on setting. This causes the service to wait until those services are started.

... should be ...

> -   Links the web service to the catalog and ordering service with the depends\_on setting. This causes the service to wait until those services are started.

**Comment by timotei** [comment]
@GuardRex Oh, true. Haven't reached that part in the book, so missed it xD

I fixed it in this PR

**Comment by GuardRex** [comment]
Thank you @timotei! ... We'll get this merged as soon as the build finishes. Thanks again for updating the topic.

**Review by guardrex — APPROVED** [review]
:shipit: :rocket:

**Pull request merged**
