### PR TITLE
Update REST tutorial to reflect DateTime parsing feature

### LINKED ISSUE #17545: Update REST client tutorial?
@BillWagner `System.Text.Json.JsonSerializer` is able to parse the timestamp string into a `DateTime` value, so no additional action is required.

https://github.com/dotnet/docs/blob/a87a04817a847efe4c64621529a60e1a8478a222/docs/csharp/tutorials/console-webapiclient.md#L358

### PR DESCRIPTION
**Pull request by nxtn**
Fixes #17545

I was thinking about this:

image

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks @NextTurn 

I'll :shipit: now.

**Comment by NextTurn** [comment]
@BillWagner Any suggestions?

**Comment by BillWagner** [comment]
@NextTurn I liked what you did. I merged this. Did I miss a question?

**Comment by NextTurn** [comment]
@BillWagner I was wondering if you had any improvement, because I'm quite... casual on this. ;)

**Pull request merged**
