### PR TITLE
remove incorrect line

### PR DESCRIPTION
**Pull request by Narvey**
see https://stackoverflow.com/a/47275268/1739000.

### CODE REVIEW

**Comment by mairaw** [comment]
@saurabh500, @corivera do you guys own System.Data.Linq.Mapping.DatabaseAttribute? Can you check if we should remove these remarks? Thanks!

**Comment by JRAlexander** [comment]
Closing and reopening as build appears hung.

**Review by jzeferino — APPROVED** [review]
LGTM.

**Comment by rpetrusha** [comment]
@saurabh500, @corivera, can you confirm that we should remove these remarks? Thanks!

**Comment by saurabh500** [comment]
Neither of us own S.D.Linq 
Not sure what to say :)

**Comment by mairaw** [comment]
@karelz can you help us find the owners of System.Data.Linq?

**Comment by OmarTawfik** [comment]
IIUC, this belongs to the SQL APIs. Maybe @saurabh500 or @corivera can help here?

**Comment by mairaw** [comment]
They already said they don't own this @OmarTawfik 😄

**Comment by OmarTawfik** [comment]
Sorry for the confusion! :'D
I don't know who owns this then. Not listed on corefx owners page. I'll ask around.

**Comment by karelz** [comment]
It is either Linq experts or Data experts :) - it depends on which expertise is needed more for the area.

**Comment by saurabh500** [comment]
@karelz looking at the SO link given above and the  documentation change proposed, I am wondering if the SO behavior is a bug. 

@divega any idea about the owners of S.D.Linq

**Comment by mairaw** [comment]
Any luck on tracking the owners of System.Data.Linq @OmarTawfik?

**Comment by OmarTawfik** [comment]
Nop. I confirmed it is not my team. I'd say the Data/SQL team would be better suited to answer this.

**Comment by divega** [comment]
Asked the owners offline.

**Comment by Jinhuafei** [comment]
@Narvey that statement is still valid. That's the default DB name, if there is no 'Initial Catalog' or 'Database' or AttachDBFileName' in your connection string.

**Comment by mairaw** [comment]
Thank you @Jinhuafei for the feedback and apologies on the delay to get a response @Narvey. We were trying to get one of the experts on this area to comment. With that, I'll be closing this PR.

**Comment by Narvey** [comment]
@Jinhuafei then why did it override my connection string?

**Comment by Jinhuafei** [comment]
@Narvey Do you pass the connection string when creating datacontext? Does the connection string contain 'Initial Catalog'?

**Pull request closed without merging**
