### PR TITLE
US 1583733 Add missing language IDs - 15

### PR DESCRIPTION
**Pull request by v-thpra**
US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "output" for output displayed in the console. Used "console for console commands.
- Used "console" for sqlmetal command examples.
- Used "sql" for examples of stored procedures in LINQ to SQL.

Contributes to #2192

### CODE REVIEW

**Comment by mairaw** [comment]
For outputs displayed on the console, I'd also use console. Only when it's a different output, I'd use output.

**Comment by v-thpra** [comment]
Good policy regarding console vs. output. I made the changes in this PR, and I'll review the other PRs that I've done to see if more changes are needed.

**Comment by v-thpra** [comment]
@mairaw All changes and conflicts have been addressed. This should be ready to merge. Thanks!

**Review by rpetrusha — APPROVED** [review]
Thanks, @v-thpra, especially for changing `output` to `console`. I'll merge your PR now.

**Pull request merged**
