### PR TITLE
SEOImages: User Story 1463880, Part 2

### PR DESCRIPTION
**Pull request by damabe**
## Summary

Updating image file names and references to improve SEO.
Fixes #1463880

Contributes to #10839

### CODE REVIEW

**Comment by damabe** [comment]
@mairaw Please have a look at this PR. There is still one warning, but I'm not familiar with what caused it. I don't believe it was because of the image updates for this user story.

**Comment by mairaw** [comment]
No @damabe, that's an existing warning. Please ignore.

**Comment by mairaw** [comment]
It'll take a bit longer to review this one because it's a bit larger. So other PRs I'd keep to less files being changes to make it easier. 

Also, some of the extensions are uppercase. Ideally, all file names when being moved/renamed, will be lowercase.

**Comment by damabe** [comment]
@mairaw Understood. Will do.

**Comment by Lxiamail** [comment]
@damabe @mairaw Looks like the changed files don't fall into my ownership area (WCF/serialization). I'm afraid that I can't add too much value to the review.

**Comment by mairaw** [comment]
@Lxiamail no worries. There might be some files in this PR that impact WCF but I removed you as a reviewer. We're driving these SEO improvements across our docs but I can be the one reviewing that.

**Comment by damabe** [comment]
@mairaw I've changed the uppercase file extensions to lowercase.

**Comment by damabe** [comment]
@mairaw I've corrected the CATS errors: https://contentqacats.azurewebsites.net/CheckResults/2019031300051/Report/. There are 3 errors for image file names that are too short. They are not part of the SEO hyphen in image name spreadsheet. Please let me know if you want me to go through these and remove the titles from the image references.

**Comment by mairaw** [comment]
No need @damabe. We'll take this issue on a later time.

**Comment by damabe** [comment]
Updated items based on other PR reviews. CATS: https://contentqacats.azurewebsites.net/CheckResults/2019032800065/Report/

**Comment by mairaw** [comment]
@damabe can you resolve these merge conflicts? I can't do it via the web interface. Thanks!

**Comment by damabe** [comment]
@mairaw The merge conflicts have been resolved here.

**Comment by mairaw** [comment]
There seems to be some warnings now. Can you take a look?

**Comment by damabe** [comment]
@mairaw Resolved the invalid link warning. Updated CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019050100020/Report/

There are three issues that were not part of the SEO spreadsheet work.

**Comment by damabe** [comment]
Sorry. Updated CATS Report: https://contentqacats.azurewebsites.net/CheckResults/2019050100024/Report/

**Pull request closed without merging**
