### PR TITLE
Added additional COR_PRF_HIGH* flags

### PR DESCRIPTION
**Pull request by rpetrusha**
## Added additional COR_PRF_HIGH* flags

@maoni0 and @mjsabby, could you please review this? Also, @Maoni0, what are the APIs for the  updating generational bounds callbacks?

### CODE REVIEW

**Comment by Maoni0** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo2-getgenerationbounds-method is the API for getting the generation bounds. the doc says "That is, it can be called from any callback except those that occur between ICorProfilerCallback2::GarbageCollectionStarted and ICorProfilerCallback2::GarbageCollectionFinished.". I don't actually see a reason why it can't be called during those callbacks.

**Review by Maoni0 — APPROVED** [review]
:shipit:

**Comment by rpetrusha** [comment]
Thanks for the review, @Maoni0!

**Review by BillWagner — APPROVED** [review]
This LGTM @rpetrusha 

You can :shipit: when ready.

**Pull request merged**
