### PR TITLE
Add MSTest analyzers documentation

### LINKED ISSUE #38767: MSTest analyzers
Hi docs team,

I am part of the owning team of [MSTest](https://github.com/microsoft/testfx) and we are starting to work on adding static code analysis with our package. We would like to add documentation about the rules and we are wondering where to put this doc.

Shall we add them under https://github.com/dotnet/docs/tree/main/docs/fundamentals/code-analysis with an `MSTest` section? Shall we add them under testing https://github.com/dotnet/docs/tree/112c8874e67461c995a65872ab938556aaa2d73b/docs/core/testing?

Thanks!

cc @MarcoRossignoli @nohwnd

### PR DESCRIPTION
**Pull request by Evangelink**
## Summary

Add MSTest analyzers documentation following the pattern used for CA rules in https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/performance-warnings.

Fixes #38767

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/testing/unit-testing-mstest-analyzers-design.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-design.md) | [MSTest design rules](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-design?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0001.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-MSTEST0001.md) | [MSTEST0001: Explicitly enable or disable tests parallelization](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0001?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0002.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-MSTEST0002.md) | ["MSTEST0002: Test classes should have valid layout"](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0002?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0003.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-MSTEST0003.md) | [MSTEST0003: Test methods should have valid layout](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0003?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0004.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-MSTEST0004.md) | [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0004](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0004?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0005.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-MSTEST0005.md) | [MSTEST0005: Test context property should have valid layout](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0005?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-MSTEST0006.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-MSTEST0006.md) | ["MSTEST0006: Avoid '[ExpectedException]'"](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0006?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-performance.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-performance.md) | [MSTest performance rules](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-performance?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers-usage.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers-usage.md) | [docs/core/testing/unit-testing-mstest-analyzers-usage](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-usage?branch=pr-en-us-38845) |
| [docs/core/testing/unit-testing-mstest-analyzers.md](https://github.com/dotnet/docs/blob/22543514df8c1ff431f834a72e267412219aaa94/docs/core/testing/unit-testing-mstest-analyzers.md) | [MSTest code analysis](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers?branch=pr-en-us-38845) |

### CODE REVIEW

**Comment by Evangelink** [comment]
@adegeo Would you mind letting me know the structure I should/could follow for these analyzers rules? So that I can update here and also update the rules help link. Thanks :)

**Comment by Evangelink** [comment]
Ping @IEvangelist @adegeo

**Review by IEvangelist — APPROVED** [review]

**Comment by Evangelink** [comment]
Nice thanks @IEvangelist! Question, we discussed with @adegeo that it's ok for analyzer to have a folder layout to simplify URL handling for rules. Could you please let me know what's the expected setup so I can help?

**Comment by IEvangelist** [comment]
> Nice thanks @IEvangelist! Question, we discussed with @adegeo that it's ok for analyzer to have a folder layout to simplify URL handling for rules. Could you please let me know what's the expected setup so I can help?

Yeah, this was approved and merged. You could update this with a new PR to adjust the file structure, but it's not necessary as the TOC reflects that desired layout.

**Pull request merged**
