### PR TITLE
Collapse relative links, Part 30

### PR DESCRIPTION
**Pull request by nxtn**
Contributes to #10653

### CODE REVIEW

**Comment by IEvangelist** [comment]
Were you able to use the new tooling this time @NextTurn?

**Comment by NextTurn** [comment]
No before I figure out how to do https://github.com/dotnet/docs/issues/10653#issuecomment-631194226. You probably don't want to click on 5K files.

**Review by BillWagner — APPROVED** [review]
This also LGTM @NextTurn 

I'll :shipit: now.

**Comment by IEvangelist** [comment]
> No before I figure out how to do [#10653 (comment)](https://github.com/dotnet/docs/issues/10653#issuecomment-631194226). You probably don't want to click on 5K files.

Do you want batching capabilities? From the extension you could configure only 50 files to be updated at a time? I already added the right-click on a folder option.

**Comment by NextTurn** [comment]
@IEvangelist Thanks for reminding. I didn't notice the latter update.

I'm now updating my local repository to prepare for the following changes. According to the current network speed, you will see the next PR in a few days.

<details>
<summary>
FTR this was the tool that I used for the first 30 PRs.
</summary>

```cs
Regex regex = new Regex(@"\]\((\.\./[^\(\)]+)\)");
foreach (string path in Directory.EnumerateFiles(@"docs", "*.md", SearchOption.AllDirectories))
{
    string directory = Path.GetDirectoryName(path);
    string[] lines = File.ReadAllLines(path);
    bool modified = false;
    for (int i = 0; i < lines.Length; i++)
    {
        string line = lines[i];
        foreach (Match match in regex.Matches(line))
        {
            string before = match.Groups[1].Value;
            string full = Path.Combine(directory, before);
            string after = Path.GetRelativePath(directory, full).Replace('\\', '/');

            if (before != after)
            {
                lines[i] = lines[i].Replace(before, after);
                modified = true;
            }
        }
    }

    if (modified)
    {
        File.WriteAllLines(path, lines);
    }
}
```

</details>

**Pull request merged**
