### PR TITLE
More consistent formatting for ilasm options

### PR DESCRIPTION
**Pull request by svick**

### CODE REVIEW

**Comment by svick** [comment]
The document also says that `:` and `=` are equivalent, but the options documentation uses both. Should it choose one of them and stick to it? (I don't have a preference about which one should be used in that case.)

**Review by mairaw — APPROVED** [review]
LGTM @svick. Re. picking one, I don't care either. Consistency is good though.

**Comment by svick** [comment]
@mairaw Ok, I have picked colon.

**Comment by mairaw** [comment]
Great! Thanks @svick.

**Pull request merged**
