### PR TITLE
Add docs-verifier

### PR DESCRIPTION
**Pull request by Youssef1313**
[First release](https://github.com/MSDocsBuild/build-verifier/releases/tag/v0.0.1) of the docs-verifier (the extended action of markdown-links-verifier).

### CODE REVIEW

**Comment by gewarren** [comment]
Is this doing anything other than checking links yet?

**Comment by Youssef1313** [comment]
@gewarren Yup. Basic redirection verification.

https://github.com/MSDocsBuild/build-verifier/blob/d535b55271cc491d5cce733f2447e12ff21db0fa/src/RedirectionVerifier/RedirectionsVerifier.cs

The algorithm is to be enhanced in a future version.

**Comment by Youssef1313** [comment]
🎉 `Error: No redirection is found for 'docs/csharp/misc/cs0003.md'.`

**Comment by BillWagner** [comment]
This is cool @Youssef1313 

I'll open a PR that removes the item in the TOC and adds a redirect. then, once that's merged, we can close and reopen this as a test.

**Comment by BillWagner** [comment]
I think the build is stuck. Closing & reopening.

**Review by BillWagner — APPROVED** [review]
Thanks for putting this together @Youssef1313 

I'll :shipit: now.

**Comment by gewarren** [comment]
@Youssef1313 - We've created a [new repo](https://github.com/dotnet/docs-actions) in the dotnet organization to house GitHub Actions that are specific to docs. We'll be locking down our docs repos to restrict the use of actions that aren't defined in the dotnet organization. Would you mind moving your build-verifier action to this repo? Also, it might be better to name it docs-verifier or link-verifier to differentiate it from the action that checks for build warnings.

**Comment by Youssef1313** [comment]
Sure. Doing that in https://github.com/dotnet/docs-actions/pull/3.

**Pull request merged**
