### PR TITLE
added ms.workload values for reporting

### PR DESCRIPTION
**Pull request by Mikejo5000**
# Title

added ms.workload values for reporting

## Summary

Added metadata attribute "ms.workload" with values of "dotnet" and "dotnetcore"

Fixes #Issue_Number

NA

## Details

This is to provide easier reporting on docs related to VS workloads.

## Suggested Reviewers

@mairaw

### CODE REVIEW

**Comment by mairaw** [comment]
@Mikejo5000 this looks good for the .NET Core workload. But what does the dotnet workload value represents? Those topics under the standard folder apply for both Core and Desktop.

**Comment by mairaw** [comment]
Is that field multi-value? The idea would be that we manually enter the core values to the standard folder later?

**Comment by Mikejo5000** [comment]
@mairaw The field is multi-value. My first thought for the \standard folder was to just use "dotnet" and add "dotnetcore" when verified on .NET Core. I'm rethinking that now; it is probably best to add "dotnetcore" to the \standard topics now, and remove that value later if it is determined that .NET Core is not supported. That will likely be much more accurate, correct? I'll update the PR here.

**Comment by mairaw** [comment]
That seems better. Thanks @Mikejo5000!

**Review by mairaw — APPROVED** [review]

**Comment by Mikejo5000** [comment]
@mairaw Thanks, Maira!

**Pull request merged**
