### PR TITLE
Standardize See also section headings

### PR DESCRIPTION
**Pull request by nxtn**
Used regex
pattern `^## See (A|a)lso *$`
replacement `## See also`

Contributes to #808 

Thanks @pkulikov

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thanks @NextTurn. I'll merge this huge PR since it's a pretty straightforward change. 😄

**Comment by mairaw** [comment]
Argh, I can't merge... Can you first resolve the merge conflicts you now have? Thanks!

**Comment by NextTurn** [comment]
Done. Just some line endings.

**Comment by NextTurn** [comment]
Removed line ending changes to avoid further conflicts.

**Pull request merged**
