### PR TITLE
Ignore parametr /r on sign

### PR DESCRIPTION
**Pull request by TerAnYu**
/r  - This parameter is ignored and is not processed

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for contributing to the dotnet/docs repo, @TerAnYu, and for submitting this PR. We're checking with the owners of SignTool.exe about whether the /r switch has any effect or not. As soon as we hear from them, we'll respond in detail to your PR.

**Comment by rpetrusha** [comment]
The product unit reports that they're unable to repro this issue, @TerAnYu. That is, the `/r` switch works as documented. Consequently, I'm going to close your PR.

**Comment by TerAnYu** [comment]
Thanks for the answer. Where to write a bug report, because this function does nothing in reality. System Windows 7 Pro x64 Russian.
The utility version 10.0.16299.91

**Comment by rpetrusha** [comment]
Sorry for the belated response, @TerAnYu. You might open an issue on http://www.github.com/microsoft/dotnet.

**Pull request closed without merging**
