### PR TITLE
Update WPF app walkthrough with extra steps

### PR DESCRIPTION
**Pull request by gewarren**
- add extra steps about creating the project and adding pages
- added tips about properties window
- added a few screenshots
- add watermark.png for easy download

### CODE REVIEW

**Comment by gewarren** [comment]
@rpetrusha this is ready for review when you get a chance. The link to the watermark.png image currently results in a 404, but I think it's because it's looking in the master branch, and will hopefully work after this is merged:

https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/media/watermark.png

**Comment by gewarren** [comment]
https://review.docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?branch=pr-en-us-4941

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for doing this so quickly, @gewarren! I've left a couple of comments and suggestions, but it's substantially improved!

**Comment by gewarren** [comment]
@rpetrusha I addressed all your comments. Thanks for the great review!

**Review by rpetrusha — APPROVED** [review]
Thank, @gewarren. You've significantly improved this topic! I'll merge your PR now.

**Pull request merged**
