### PR TITLE
Fixed Kelvin output, make culture independent

### PR DESCRIPTION
**Pull request by paulroho**
## Summary

- Fixed wrong expected output for Kelvin in the sample usage
- Defined current culture in the sample usage to work out-of-the-box for international locales

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for correcting the Visual Basic example as well, @paulroho! Could you also change this assignment to:
```
CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("en-US")
``` 
Thanks.

**Comment by rpetrusha** [comment]
@paulroho, as in #3157, this should be `CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("en-US")` instead of `CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US")`.

**Comment by paulroho** [comment]
Sorry @rpetrusha. Fixed it.

**Review by rpetrusha — APPROVED** [review]
Thanks, @paulroho! We'll merge your PR now.

**Pull request merged**
