### PR TITLE
Replace licenseUrl with license in recommended NuGet metadata

### PR DESCRIPTION
**Pull request by JamesNK**
Do you agree with this advice @karann-msft?

### CODE REVIEW

**Comment by karann-msft** [comment]
In general yes. The overall experience is still being worked on and nuget.org will be fully ready in January. If you would like to move to license expression today, use the latest nuget exe (4.9.x) since it looks at the expression and inserts the generated license url which will point to a template of the license text. At the moment this is the url that is being surfaced on nuget.org and in the search api. By January, nuget.org would interpret the expression directly from the metadata. The url is still useful for old clients or clients that don't recognize the new license yet. Also, Nuget.org can accept license type expression but not file just yet.

**Review by rpetrusha — APPROVED** [review]
LGTM, @JamesNK. You can merge when you're ready.

**Comment by JamesNK** [comment]
The NuGet team has said there are a couple of issues with the new metadata, and it is not quite ready to be recommended.

The change is fine, it should just wait a month or two before being published.

**Comment by JamesNK** [comment]
re: https://github.com/NuGet/Announcements/issues/32 @anangaur

This is now a recommended thing from NuGet so ready to merge

**Comment by mairaw** [comment]
@JamesNK any updates on this one? When do you think this will be published?

**Comment by JamesNK** [comment]
@mairaw No changes needed. Merged!

**Comment by mairaw** [comment]
I think we posted at the same time. 😄 Thanks!

**Pull request merged**
