### PR TITLE
try fix #4349 (error in formatting)

### LINKED ISSUE #4349: System.Uri constructor exceptions formatting error
On the Uri constructor page, constructor (uri, string) and (uri, uri) there is a formatting issue. This happens for many different .NET versions.

Urls:
* https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.7.1#System_Uri__ctor_System_Uri_System_String_
* https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.7.1#System_Uri__ctor_System_Uri_System_Uri_

Screenshot:
thumbnail_image001

I'm not exactly sure how to fix this, otherwise I would've fixed it and created a PR ;-) . I created another PR for another type (#4348).

### PR DESCRIPTION
**Pull request by Styxxy**
try fixing #4349 : error in formatting

I don't know if this helps.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for noticing the problem and trying to fix it by submitting this PR, @Styxxy. Unfortunately, it doesn't fix the problem, and I have no idea why. Let me try to look at the markdown a bit more closely later today and hopefully figure out what we need to do to get this text to resolve as links.

**Comment by Styxxy** [comment]
@rpetrusha
I copied from other place (in same file) that actually rendered correctly. Hoped that would fix it. I'm curious what could be the problem.

**Review by rpetrusha — APPROVED** [review]
Inexplicably, the problem turned out to be a blank line after the closing \</block> tag, @Styxxy. I've removed the blank line, and now the links resolve correctly.
Again, thank you so much for submitting this PR and trying to fix the links. We'll merge your PR now. The changes should appear live on docs.microsoft.com in the next day or two.

**Comment by Styxxy** [comment]
@rpetrusha Super! :)

**Pull request merged**
