### PR TITLE
chore: Remove BOM from Markdown files

### PR DESCRIPTION
**Pull request by nschonni**
Just ran a script from https://ngeor.wordpress.com/2017/08/02/strip-the-bom/ to strip the BOM character from the MD files because they YAML frontmater doesn't render on GH when the BOM is included in the file. It also causes false positives for the validation service
```
find . -type f -iname "*.md" -exec node -e "var f = process.argv[1]; var contents = fs.readFileSync(f, 'utf8'); if (contents.charCodeAt(0) === 0xFEFF) { fs.writeFileSync(f, contents.slice(1), 'utf8'); } " \{\} \;
```
Feel free to run this internally instead if easier.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for making this change @nschonni 

I'm glad you found a script to fix this.

I'll :shipit: now.

**Comment by NextTurn** [comment]
What about the the BOM in XML files in dotnet/dotnet-api-docs repo? Is there any usage?

**Comment by mairaw** [comment]
If you remove them, the mdoc tool (our reflection tool) adds them back. So @joelmartinez can first let us know if there's any use for those. But it's not worth to open a PR for that now.

**Comment by joelmartinez** [comment]
@mairaw yes that is correct, mdoc will add them back every time. It's use is … that's just the way the tool has saved files for many years :)

**Comment by nschonni** [comment]
When you say it will add them back, are you talking about the Markdown files here, or XML in the other repo?

**Comment by joelmartinez** [comment]
@nschonni ahh, my apologies for the ambiguity … I meant to the XML files. _mdoc_ doesn't touch any markdown files.

**Comment by nschonni** [comment]
:+1: thanks for confirming

**Pull request merged**
