### PR TITLE
Delete orphaned markdown files

### PR DESCRIPTION
**Pull request by gewarren**
Contributes to #15560

### CODE REVIEW

**Comment by mairaw** [comment]
We shouldn't delete those files. @BillWagner probably knows best the plan for the error messages in C#.

**Comment by mairaw** [comment]
Some might be not in TOC by accident (like I see some in framework/additional-apis). Content in that folder should never be deleted because they are added because of compliance issues.

For framework/misc, these were security topics that were not added by the TOC by design. I had a plan to move them to standard/security and perhaps add them to the TOC under a legacy node or something. I'd recommend that we close this PR and discuss the plan.

**Comment by mairaw** [comment]
Indeed. I think it's good to have the list!

**Comment by gewarren** [comment]
> For the csharp/misc folder: The long term plan is to keep these, and not have them in the TOC. They should be found only by search by error code.
> @gewarren Is there a way to ignore a specific folder with the clean-repo tool? All these files are in two folders (csharp/misc and csharp/language-reference/compiler-messages)

@BillWagner There is not [currently that functionality](https://github.com/gewarren/cleanrepo/issues/16), but it's easy enough to revert changes to files in specific folders after running the tool.

**Pull request closed without merging**
