### PR TITLE
Update garbage-collector.md

### PR DESCRIPTION
**Pull request by Maoni0**
added some clarification to the standalone GC configs. describes the behavior in .net8 and prior vs .net9. also added a header for each config since there are multiple in this section.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/runtime-config/garbage-collector.md](https://github.com/dotnet/docs/blob/2ecefd4cbac96cd026d9f15339eb6e9d20b24d15/docs/core/runtime-config/garbage-collector.md) | [Runtime configuration options for garbage collection](https://review.learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector?branch=pr-en-us-41554) |

### CODE REVIEW

**Comment by Maoni0** [comment]
CC @cshung.

**Comment by cshung** [comment]
I confirm the content is accurate.

**Comment by Maoni0** [comment]
do you have any feedback, @gewarren ?

**Review by gewarren — APPROVED** [review]
Preview is [here](https://review.learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector?branch=pr-en-us-41554#standalone-gc). LGTM with the changes I made.

**Pull request merged**
