### PR TITLE
Add bullets to see also section

### PR DESCRIPTION
**Pull request by jpreese**
## Summary

In the same camp as https://github.com/MicrosoftDocs/visualstudio-docs/pull/1358 for unit testing sections

### CODE REVIEW

**Review by jzeferino — APPROVED** [review]
LGTM

**Comment by mairaw** [comment]
Thank you for your PR @jpreese. I'm discussing with my team whether we want to adopt bulleted lists across the board for the See also section. I'll get back to you!

**Comment by mairaw** [comment]
We've discussed and decided we'll adopt bulleted lists from now on. I've created an issue to keep track of this (#6923). Thanks!

**Review by mairaw — APPROVED** [review]

**Comment by jpreese** [comment]
Sounds good to me. I would agree with the approach as, at least from the docs I've viewed, the majority use bullets. Also, FWIW, it *is* an unordered list and should be easier to format instead of needing to remember to force a linebreak with double spaces.

**Pull request merged**
