### PR TITLE
Tagged a few VS-focused topics for VS reporting

### PR DESCRIPTION
**Pull request by Mikejo5000**
## Summary

Based on a metadata title seach, tagged a few VS-focused topics with "vs-dotnet" to help with our reporting. I only tagged topics that appeared to be higher priority scenarios for VS.

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
LGTM, @Mikejo5000. You can merge when you're ready.

**Comment by Mikejo5000** [comment]
#sign-off

**Comment by Mikejo5000** [comment]
@rpetrusha Thanks, Ron. Can I merge in this repo by sign-off? Not sure I have merge permissions...

**Comment by mairaw** [comment]
Nope, we'll merge it for you @Mikejo5000. We don't have API Merger on ours.

**Pull request merged**
