### PR TITLE
Converted 59 Basetypes topics from MSDN

### PR DESCRIPTION
**Pull request by stevehoag**
Will add to TOC in another PR

### CODE REVIEW

**Comment by mairaw** [comment]
Ok, this will be tricky to review. Have you at least run docfx on this to make sure you get no warnings, etc.?

**Comment by richlander** [comment]
Please make the TOC updates and the content changes in the same PR. It leaves the repo in an inconsistent state.

We should chat about your workflow. You shouldn't have any merges, let alone two.

**Comment by svick** [comment]
I realize this is inherited from MSDN, but I don't understand what are "base types" supposed to be here. I would expect that phrase to mean the type another type inherits from, but that doesn't seem to be the meaning used here.

Also, running docfx on this produces 144 warnings about invalid file links.

**Comment by richlander** [comment]
This is the heritage: https://msdn.microsoft.com/en-us/library/7wchwf6k(v=vs.110).aspx.

I prefer the following nomenclature:

- Type system (for describing class, interfaces and enums)
- Primitives (for describing string, int, decimal)
- Fundamental data types and utilities (for describing List<T>, Linq, HttpClient)

**Comment by stevehoag** [comment]
Closing this PR - will resubmit once content is moved to concepts.

**Pull request closed without merging**
