### PR TITLE
Clarifications on Struct Initialization

### PR DESCRIPTION
**Pull request by anonymousgituser**
Clarifying how struct initialization behaves with respect to members of a struct.

# Clarifications on Struct Initialization

## Summary

This PR is to further explain and clarify the behavior of structs with respect to constructors and initialization in the "using structs" page.

## Details

1. Clarified options for initializing a struct.
2. Described default initialization behavior.
3. Clarified behavior of CS0171.

## Suggested Reviewers

Authorship is currently ascribed to @BillWagner, @mikeblome, @mairaw, @guardrex, and @tompratt-AQ

### CODE REVIEW

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build; this PR doesn't appear in the OPS build report.

**Review by BillWagner — APPROVED** [review]
Thanks for submitting this @anonymousgituser We appreciate it.

I've reviewed the changes, and I'll merge this once the builds finishes. (We've had some issues with our CI system recently).

Once it's merged, the changes will show up on the live site within a day or two on our regular publish cycle.

Thanks again.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by mairaw** [comment]
Thanks @anonymousgituser! Build looks good and we'll merge your PR now. Your fix should go live in the next day or so.

**Comment by anonymousgituser** [comment]
Thanks @rpetrusha, @BillWagner, and @mairaw for your help!

**Pull request merged**
