### PR TITLE
Remove 'Publish events that conform to .NET Guidelines' guildeline and redirect to events article in the standard

### LINKED ISSUE #41927: Duplicated content
### Type of issue

Outdated article

### Description

Much of the information in this section is older and outdated. The corresponding content in the [standard](https://learn.microsoft.com/en-us/dotnet/standard/events/) section is more recent.

These articles could be deleted and redirected to that location.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md

### Document Version Independent Id

1fd093e9-f47c-ffdd-91e9-5039c3ccde61

### Article author

@BillWagner

### Metadata

* ID: 38e8321f-5516-e451-5429-750d49f0ebed 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

### PR DESCRIPTION
**Pull request by BartoszKlonowski**
This pull request closes #41927 
It completely removes the *Publish events that conform to .NET Guidelines* article and sets a redirection to the overview article in the standard for the events.

### CODE REVIEW

**Comment by BillWagner** [comment]
Hi @BartoszKlonowski 

Can you remove the article from the TOC as well?  See https://github.com/dotnet/docs/blob/main/docs/csharp/toc.yml#L649-L650

**Review by BillWagner — APPROVED** [review]
Thanks again @BartoszKlonowski 

This LGTM. Let's :shipit:

**Comment by BillWagner** [comment]
I went ahead and merged this. I'll do a fast follow using our tools to fixup the links to the removed article.

@BartoszKlonowski If you're interested, the [cleanrepo](https://github.com/dotnet/docs-tools/tree/main/cleanrepo) tool in our docs-tools repo is how we fix those up.

**Comment by BartoszKlonowski** [comment]
@BillWagner Oh, that looks super useful, good to know about!
And sorry for all this back and forth with this one 🙏

**Pull request merged**
