### PR TITLE
Add missing muxer CLI arguments

### LINKED ISSUE #12543: dotnet command help missing --runtimeconfig option
See https://github.com/dotnet/core-setup/blob/61f83f1f764a8a2840a21779e386c2ad11fca75d/src/corehost/cli/fxr/command_line.cpp#L22-L31 for the available options (https://github.com/dotnet/core-setup/blob/086e6eddfa2639f074f9512bf10e374391ffafde/src/corehost/cli/fxr/fx_muxer.cpp#L724-L742 for the 2.2 version).

The documentation is missing the `--runtimeconfig` option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore1x#feedback)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by dasMulli**
## Summary

Added `--depsfile` and `--runtimeconfig` arguments to `dotnet` command.

Fixes #12543 

cc @mairaw

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
The changes look great to me. I'd like to just confirm with @KathleenDollard she's ok with this PR and see what we need to do to get these options to show up for `dotnet --help` as well.

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
kindly ping @KathleenDollard

**Comment by KathleenDollard** [comment]
@dsplaisted Can you review this or suggest someone else to check it from a technical perspective.

**Comment by dsplaisted** [comment]
@jeffschwMSFT @vitek-karas for review.

It would probably be helpful to have some sort of description about what the deps.json file and runtimeconfig.json files are used for.  Perhaps a link to any documentation we have about them.

**Comment by mairaw** [comment]
We don't have docs on those yet. Maybe there's some docs on product repos?

**Comment by vitek-karas** [comment]
We have a rough description here: https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md

The structure is not ideal, but at least something (it has both too much and too few details...).

**Comment by mairaw** [comment]
@dasMulli can you add the link as suggested? I'll open a new issue to take care of @KathleenDollard's feedback on the original issue.

**Comment by dasMulli** [comment]
Added the link and some text, is this what you had in mind?

**Review by mairaw — APPROVED** [review]
Thanks @dasMulli for doing this work and apologies for letting this one linger here. I made some small edits so we could merge this.

**Pull request merged**
