### PR TITLE
Replace HTML entity with its representation

### PR DESCRIPTION
**Pull request by mgw854**
# Fixed escaped HTML entity by replacing it with its representation

## Summary

There was an HTML entity displaying in its escaped form (`&#124`) in the documents I was reading. This should instead should be the character represented by the entity, the vertical bar `|`.

### CODE REVIEW

**Review by guardrex — CHANGES_REQUESTED** [review]
@mgw854 Thanks for helping with the broken rendering here. Normal escaping won't work with the inline code markdown (the backticks) ... it just displays the escape character `\`. Here's a screenshot of the rendered table with the commit ...

capture

Since the vertical bar would break the table on it's own (without the backticks), we've been using a workaround. The styling of code will apply with \<code>\</code> tags, so placing the HTML-encoded character inside of those should work.

```
... but they are evaluated using `&` and <code>&#124;</code>, which can be overloaded.
```

**Comment by mgw854** [comment]
@GuardRex ,

Thank you for the prompt review! I trusted GitHub's Markdown preview, but didn't consider if the rendered output would be different. I've made the change as you've suggested.

**Comment by GuardRex** [comment]
@mgw854 Excellent -- thanks. We'll get this merged as soon as the build finishes.

**Comment by GuardRex** [comment]
@mgw854 

capture

Yep! That licked it! :smile: Thanks again ... :shipit:

**Review by guardrex — APPROVED** [review]

**Pull request merged**
