### PR TITLE
Update Live with current Master

### PR DESCRIPTION
**Pull request by rpetrusha**

### CODE REVIEW

**Comment by pkulikov** [comment]
@mairaw @rpetrusha @BillWagner could you please merge the master dotnet/samples into live and republish this repo to make the new snippets published:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#range-operator-

**Comment by mairaw** [comment]
Of course @pkulikov! Usually the workflow is to push samples first.

**Comment by mairaw** [comment]
The missing code issue is fixed.

**Comment by pkulikov** [comment]
Thank you @mairaw!

**Pull request merged**
