### PR TITLE
Add Blazor to "Create your application: Web card"

### PR DESCRIPTION
**Pull request by guardrex**
There's a little open space in the Web card. Any interest in a **_Blazor!_** link there?

cc: @danroth27

### CODE REVIEW

**Comment by guardrex** [comment]
btw --- some build warnings ...


Warning | User | codesnippet-not-found | docs/standard/serialization/system-text-json-converters-how-to.md | Cannot  resolve  '~/samples/snippets/core/system-text-json/csharp/ConvertInferredTypesToObject.cs'  relative to  'docs/standard/serialization/system-text-json-converters-how-to.md'. | 195 | 12/14/2019 20:44:42
-- | -- | -- | -- | -- | -- | --
Warning | User | codesnippet-not-found | docs/standard/serialization/system-text-json-converters-how-to.md | Cannot  resolve  '~/samples/snippets/core/system-text-json/csharp/ConvertDictionaryTkeyEnumTValue.cs'  relative to  'docs/standard/serialization/system-text-json-converters-how-to.md'. | 225 | 12/14/2019 20:44:42
Warning | User | codesnippet-not-found | docs/standard/serialization/system-text-json-converters-how-to.md | Cannot  resolve  '~/samples/snippets/core/system-text-json/csharp/ConvertPolymorphic.cs'  relative to  'docs/standard/serialization/system-text-json-converters-how-to.md'. | 261 | 12/14/2019 20:44:42

**Comment by mairaw** [comment]
I think it's a good idea to add Blazor there. @BillWagner thoughts?

@tdykstra to check the warnings for the JSON articles

**Comment by mairaw** [comment]
I guess the PR for the warnings is here: https://github.com/dotnet/samples/pull/1845/files

I'll try to merge that and see if that fixes it.

**Comment by BillWagner** [comment]
This LGTM @guardrex 

@mairaw I'll close and reopen to see if a fresh build helps.

**Review by BillWagner — APPROVED** [review]
Thanks for making this addition @guardrex 

I'll :shipit: once we have the build warnings addressed.

**Pull request merged**
