### PR TITLE
Initial bits of ported and modernized Reactive Extensions (Rx) content

### LINKED ISSUE #21150: Get all the reactive extensions docs pulled out of MSDN
Let's do this!

https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh242985(v=vs.103)

Part of the conversation and driving factors with Rodney Littles II 🤘🏼

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

Describe your changes here.

Fixes #21150

## Internal preview

✔️ [Reactive Extensions](https://review.docs.microsoft.com/en-us/dotnet/reactive-extensions/?branch=pr-en-us-21325)

### CODE REVIEW

**Comment by bartdesmet** [comment]
Good start, though I only had a quick scan over the current docs. There's a lot that can be improved (the original docs weren't great), but we can go step-by-step. Tagging @idg10 who has written great Rx content for one of his C# books as well.

**Comment by IEvangelist** [comment]
😢 With a very heavy-heart, I have to communicate that I am not permitted to add **Reactive Extensions** content to the .NET docs. After much internal communication, I have learned that we're required to only maintain officially supported .NET bits. Although this content was originally Microsoft's, it has since become a part of the .NET Foundation - and belongs to the community.

I will happily work with whomever would be interested in taking these efforts and porting them into whatever other repos may already exist.

/cc: @bartdesmet @idg10 @RLittlesII

**Comment by cabauman** [comment]
@IEvangelist I'd be happy to continue your efforts for the Reactive UI website repository. I've already done a lot of non-committed work on it but took a break the last few months. I love what you've done with this PR, so it would be great to combine our efforts to get it off the ground again.

**Comment by IEvangelist** [comment]
> @IEvangelist I'd be happy to continue your efforts for the Reactive UI website repository. I've already done a lot of not-yet-committed work on it but took a break the last few months. I love what you've done with this PR, so it would be a pleasure to combine our efforts to get it off the ground again.

Happy to collaborate, just tag me and I'd be thrilled to do whatever it takes to make this happen. Thank you so much!

**Pull request closed without merging**
