### PR TITLE
Update statically-resolved-type-parameters.md

### PR DESCRIPTION
**Pull request by ebresafegaga**
inline functions can be parameterized with a standard generic type parameter.

### CODE REVIEW

**Review by cartermp — CHANGES_REQUESTED** [review]
This isn't quite right. Adding the standard generic type parameters will no longer use static type parameters, forcing the compiler to specialize the function to a specific type. This should be added to the sentence.

**Comment by ebresafegaga** [comment]
> This isn't quite right. Adding the standard generic type parameters will no longer use static type parameters, forcing the compiler to specialize the function to a specific type. This should be added to the sentence.

Yes, that's true.  But can an inline function have standard generic type parameters (CLR generics) without any static type parameters on it?  The docs says this is not possible at all.

**Comment by cartermp** [comment]
It can, yes. But not in the context of static types, which is probably why this was explicitly called out as not possible here. I think it could get reworded, but it need to be explicit about the fact that this forces specialization with CLR generics and thus doesn't let you do things like generic arithmetic

**Comment by adegeo** [comment]
@cartermp What should we do with this PR?

**Comment by cartermp** [comment]
As it stands we'll need more clarification in this PR to take it further. Right now the document is correct, though could be improved. The current change would no longer make it correct.

**Comment by IEvangelist** [comment]
Hi @ebresafegaga - just working backwards through open PRs. Are you going to make the adjustments that Phillip suggested, or continue the discussion?

**Comment by adegeo** [comment]
Closing as abandoned.

**Pull request closed without merging**
