### PR TITLE
Add link to new EPA docs for Oct 2023 Windows Server release

### PR DESCRIPTION
**Pull request by alvinashcraft**
## Summary

I'm creating this as a draft. The changes are all set, but please do not merge until after my topic in the win32 repo is published on Tuesday.

Adding a link to a new EPA doc to be published on Oct 17th: Supporting Extended Protection for Authentication (EPA) in a service. You can view [my PR](https://github.com/MicrosoftDocs/win32-pr/pull/1737) for the new doc to be added when the Windows Server bits are available.

Fixes #Issue_Number (if available): No GitHub issue number. This is for an internal request on the Windows team.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/framework/wcf/feature-details/extended-protection-for-authentication-overview.md](https://github.com/dotnet/docs/blob/00a17913bfc2d271989b1cf9113a504617698311/docs/framework/wcf/feature-details/extended-protection-for-authentication-overview.md) | [Extended Protection for Authentication Overview](https://review.learn.microsoft.com/en-us/dotnet/framework/wcf/feature-details/extended-protection-for-authentication-overview?branch=pr-en-us-37471) |

### CODE REVIEW

**Comment by alvinashcraft** [comment]
The linked doc in the win32-pr repo will be published by 10am PT today, Oct 17th.

**Comment by alvinashcraft** [comment]
The new linked article is now live: https://learn.microsoft.com/windows/win32/secauthn/epa-support-in-service

**Comment by alvinashcraft** [comment]
Hi @HongGit. Please reach out if you see any problems with this PR. Thanks!

**Comment by BillWagner** [comment]
closing and reopening for a fresh build.

**Comment by alvinashcraft** [comment]
Hi @BillWagner, thanks for checking in. For some reason, I thought this change went in with another PR by @HongGit after I emailed them, but I don't see the link on the live topic. If this could be reviewed and merged, that would be awesome. It's ready to go. I'm OOF this week, so I'll be a little slow to reply if you have questions.

**Review by BillWagner — APPROVED** [review]
This LGTM.

I'll :shipit: now.

**Pull request merged**
