### PR TITLE
Expand the syntax description (#7628)

### LINKED ISSUE #7628: Incorrect description of escaping rules
The document has:

> Any values containing a semicolon, single quotation marks, or double quotation marks must be enclosed in double quotation marks.

It is wrong, because a value containing a doulbe quote **cannot** be enclosed in double quotes and **must** be enclosed in single quotation marks.

The correct rule is to escape a value with a character that is not present in the value, i.e. escape double quotes with single quotes and vice versa, e.g.: 

1. `"don't"`
2. `'He said "No!"'`.

Otherwise *ADO.NET* throws the exception:

> Format of the initialization string does not conform to specification starting at index (such and such).

Which makes one wonder: where is the specification mentioned in the error message?

**Edit**: Furthermore and contrary to the document, it is not at all necessary to escape values with single or double quotes. For example, the following connection string is correct: `Name=An"t'on`. Escaping is required only for the semicolon and Unicode control characters. When, however, escaping *is* used, the escaping character shall not occur in the value.

To summarise—the escaping rules are as follows:
1. If the value contains neither the semicolon nor one of the [Unicode control characters](https://msdn.microsoft.com/en-us/library/aa311591%28vs.71%29.aspx?f=255&MSPPError=-2147217396), do not escape.
2. Otherwise, enclose the value in double or single quotation marks, but make sure the escaping character does not occur in the value.
3. If the value contains both single and double quotation marks, it cannot be used in a connection string.

Examples of  valid connection strings:

    Server=a=b=c
    Server=no"'scape"necess'ry
    Server="escape;specalcharacters"
    Server='escape;specalcharacters'
    Server='es;cape"quotation'
    Server="es;cape'apostrophe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ea979-365a-bfce-31ed-638781065bca
* Version Independent ID: 3672ed45-e05f-a292-16a0-9779254492be
* Content: [Connection Strings in ADO.NET](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings)
* Content Source: [docs/framework/data/adonet/connection-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

### PR DESCRIPTION
**Pull request by ant-222**
I have analysed the parser of connection strings, made some tests, and corrected and clarified the description of connection string syntax.

## Summary

1. Remove the wrong statement that single and double quotation marks in values must be escaped.
2. Clarify and expand the rules for escaping (enclosing) values.

Fixes #7628

### CODE REVIEW

**Comment by douglaslMS** [comment]
@ant-222 Are you a Microsoft developer, or a community member?

**Comment by ant-222** [comment]
@douglaslMS A community member.

**Comment by douglaslMS** [comment]
@ant-222 Thanks for clarifying. Let me just run this by someone more knowledgeable than myself.

**Review by douglaslMS — APPROVED** [review]

**Comment by douglaslMS** [comment]
Also reviewed and approved by David Engel. Merging now.

**Pull request merged**
