### PR TITLE
Revert "Incorrect image referenced in Dockerfile"

### PR DESCRIPTION
**Pull request by Thraka**
Reverts dotnet/docs#13231

@TracyGH Can you clarify why you got the error in the original issue? This tutorial doesn't use ASP.NET at all and the original command works as intended if you're following the tutorial.

### CODE REVIEW

**Comment by TracyGH** [comment]
@Thraka - When I tried to complete the tutorial, I received the error shown in the GitHub issues referenced in the original PR.  Both threads suggested updating 'runtime' to 'aspnet' and that fixed it for me.  Below is the project I used to complete the tutorial.
image

**Comment by Thraka** [comment]
Hi! I can see how you got that error, because you created an ASP.NET Core app, but the tutorial is built on using a .NET Core app.

Perhaps if I can understand why you used the tutorial but didn't follow it, I can update the article to help solve the problem you ran into. Did you perhaps arrive at this tutorial because you had an existing ASP.NET Core website you want to dockerize?

**Comment by TracyGH** [comment]
@Thraka - Also, [Docker's version of the same tutorial](https://docs.docker.com/engine/examples/dotnetcore/) appears to use 'aspnet' rather than 'runtime'.

image

**Review by mairaw — APPROVED** [review]
Approving while you figure out what's wrong 😄

**Comment by Thraka** [comment]
@TracyGH Did you see the ASP.NET Core tutorial on docker? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-2.2

This tutorial is for .NET Core. I would think that the article I just linked to and docker's article are the same. My article here deals with .NET Core, specifically a console app and not a web app. For a console app you would use the `runtime` image as stated in this tutorial.

**Comment by TracyGH** [comment]
Hi @Thraka - Thank-you for the clarification!  Yes, that seems to be the issue.  I was using the 2 (.NET Core & ASP.NET Core) interchangeably, and Docker appears to do the same thing on their tutorial (see image below).  
For me, I think it may be a keyword search issue.  When Googling for things like 'asp.net docker container', the .NET Core article shows up but not the asp.net relevant one you referenced above.  

image

**Comment by Thraka** [comment]
OK. I thought that was probably the issue but I wanted to make sure. It's a problem that won't be fixed until [.NET 5 is released](https://devblogs.microsoft.com/dotnet/introducing-net-5/) and the Core designation is dropped :)

Thanks for working with me on making sure I understood what happened!

**Pull request merged**
