### PR TITLE
fixed broken link

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by mairaw** [comment]
@BillWagner I just noticed that the https://docs.microsoft.com/en-us/dotnet/csharp/local-functions-vs-lambdas is not hooked up to the TOC. Where should it go?

**Comment by BillWagner** [comment]
@mairaw That document is linked from [What's new in C# 7, local functions](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#local-functions)

Ideally, it would be a side bar, but that functionality isn't in place.

**Comment by mairaw** [comment]
let's leave it like this for now then. Do you approve the changes @BillWagner?

**Comment by mairaw** [comment]
Merge conflicts resolved.

**Review by BillWagner — APPROVED** [review]
LGTM. Let's :shipit:

**Pull request merged**
