### PR TITLE
Fixed missing code snippets in csharp-7.md

### PR DESCRIPTION
**Pull request by NikolayIT**
# Title

Fixed missing code snippets in csharp-7.md

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by rpetrusha** [comment]
@NikolayIT, I'm not sure what your PR fixes. All of the code snippets appear in [What's new in C# 7](https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new/csharp-7). Since the snippet tags are an extension to our open publishing system, the code won't appear if you view the markdown file in GitHub. Is that what you were expecting?

**Comment by svick** [comment]
@rpetrusha It improves how snippets appear on GitHub. Right now, if you click the snippet link in https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7.md#out-variables, you get to https://github.com/dotnet/docs/blob/master/samples/snippets/csharp/new-in-7/program.cs#03_OutVariableOldStyle, which is 404. This PR would change it to https://github.com/dotnet/docs/blob/master/samples/snippets/csharp/new-in-7/Program.cs#03_OutVariableOldStyle, which at least shows the correct file.

Though I have no idea if this is what @NikolayIT intended.

**Comment by NikolayIT** [comment]
Yes currently if I read the docs in GitHub code snippets are not working properly 😄

**Comment by mairaw** [comment]
Gotcha! Thanks for clarifying that @svick and @NikolayIT. I can repro that.

**Review by mairaw — APPROVED** [review]

**Comment by mairaw** [comment]
@NikolayIT it seems that you deleted the repo where this PR was coming from and our builds got stuck. Do you want to submit that again or do you want us to do that for you?

**Pull request closed without merging**
