### PR TITLE
Updated vscode command palette shortcut

### PR DESCRIPTION
**Pull request by Zeroto**
The default shortcut for the command palette is `ctrl/command+shift+p` (`F1` also works).

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for making this correction and for contributing to the dotnet/docs repo, @Zeroto. There's one additional mention of the Command Palette shortcut keys on line 85; could you correct that as well?

**Comment by Zeroto** [comment]
@rpetrusha I've also fixed that line.

**Comment by rpetrusha** [comment]
Opening and closing to begin new build.

**Comment by rpetrusha** [comment]
Thanks for making the additional change, @Zeroto. We'll merge your PR as soon as there's a successful build. Once we merge, changes should appear on docs.microsoft.com within the next day or two.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
