### PR TITLE
Remove empty .resx, Part 4

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Comment by NextTurn** [comment]
Same as Part 3.

**Comment by BillWagner** [comment]
@NextTurn Can you look at the build errors on this PR? Many of them are real errors introduced by removing controls declared in the XAML.

**Comment by NextTurn** [comment]
@BillWagner I think the "not declared/defined/found" errors are due to designer codes not being generated. IIUC specifying the host as Visual Studio may fix these.

**Comment by BillWagner** [comment]
Tagging @adegeo for review.

**Comment by NextTurn** [comment]
*Microsoft.Ink.dll* doesn't exist on the CI server. Everything else is OK.

**Comment by adegeo** [comment]
We should revert the changes to WinformWPFInk as it doesn't work on .NET Core nor newer SDK style projects. It compiles fine on my machine only when in the old framework style project format.

**Comment by NextTurn** [comment]
> We should revert the changes to WinformWPFInk as it doesn't work on .NET Core nor newer SDK style projects. It compiles fine on my machine only when in the old framework style project format.

I don't think so. I can successfully compile this project with *Microsoft.Ink.dll* downloaded from [a third-party website](https://www.dllme.com/dll/files/microsoft_ink_dll.html).

**Comment by NextTurn** [comment]
There is something wrong with the `vsmcustomcontrolvb2` project on my machine. I've added reference assemblies.

> C:\Program Files\dotnet\sdk\3.1.300\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [docs\samples\snippets\visualbasic\VS_Snippets_Wpf\vsmcustomcontrol\visualbasic\vsmcustomcontrolvb2_suh2x50y_wpftmp.vbproj]

**Comment by adegeo** [comment]
Well yes, if I downloaded the DLL it would work too, but that doesn't help the CI system verify the code :)

The DLL is **winforms specific**. I looked around and I believe the DLL is from the XP era (Windows Tablet Edition SDK). Really the sample needs to be updated to use the latest ink tech for winforms. However, searching the docs here, only the SAVE/LOAD method snippets for WPF are used, which work fine. So this whole snippet should be rewritten or really all the winforms stuff ripped out of it. Why the snippet authors merged winforms + wpf into the same project and further into the same code file, I don't know.

Why (on my machine) the system can't find the DLL when using newer SDK projects that target .NET Framework, I have no idea. But if I revert the changes back to a .NET Framework project, it compiles fine on my machine.

To solve your compile problem, you probably just need to download the 4.8 developer pack: https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer

(Or don't target 4.8 on the project. I actually used 4.0 but it still wouldn't compile with the SDK-style project)

**Comment by NextTurn** [comment]
@adegeo I tweaked the path to *Microsoft.Ink.dll* according to [Managed Library and Controls (Tablet PC)](https://docs.microsoft.com/windows/win32/tablet/managed-library-and-controls--tablet-pc) and the project compiles on CI now. 🚀

**Comment by NextTurn** [comment]
> docs\samples\snippets\visualbasic\VS_Snippets_Wpf\vsmcustomcontrol\visualbasic\Window1.xaml(14,23): warning BC40004: WithEvents variable 'MouseLeave' conflicts with event 'MouseLeave' in the base class 'UIElement' and should be declared 'Shadows'. [docs\samples\snippets\visualbasic\VS_Snippets_Wpf\vsmcustomcontrol\visualbasic\vsmcustomcontrolvb2_z3g42gjw_wpftmp.vbproj]
docs\samples\snippets\visualbasic\VS_Snippets_Wpf\vsmcustomcontrol\visualbasic\Window1.xaml(15,23): warning BC40004: WithEvents variable 'MouseEnter' conflicts with event 'MouseEnter' in the base class 'UIElement' and should be declared 'Shadows'. [docs\samples\snippets\visualbasic\VS_Snippets_Wpf\vsmcustomcontrol\visualbasic\vsmcustomcontrolvb2_z3g42gjw_wpftmp.vbproj]

There are two warnings left.

**Review by adegeo — APPROVED** [review]

**Comment by adegeo** [comment]
@NextTurn  Thanks for all the hard work and adapting to our new processes!

**Pull request merged**
