### PR TITLE
Policheck: add "regions" to "countries"

### PR DESCRIPTION
**Pull request by garycentric**
In comments about IBAN/BBAN codes and `bbanpattern`, I added _regions_ to two instances of _countries_ to address geopolitical concerns and the resulting [style guideline for _country_](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=33582). This change was discussed in bugs [14707](https://dev.azure.com/msft-skilling/Content/_workitems/edit/14707) and [14580](https://dev.azure.com/msft-skilling/Content/_workitems/edit/14580). This work is for [user story 2001296](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2001296).

### CODE REVIEW

**Comment by garycentric** [comment]
#sign-off

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32657) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32657) before we can accept your contribution.<br/><br/>:x: garycentric [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32657)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=32657) it.</sub>

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32657) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32657) before we can accept your contribution.<br/><br/>:x: garycentric [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=32657)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=32657) it.</sub>

**Review by BillWagner — APPROVED** [review]
Thanks @garycentric 

This LGTM. I'll :shipit: now.

**Pull request merged**
