### PR TITLE
Update Docker Images in the table to latest (3.1)

### LINKED ISSUE #16500: Update Docker Images in the table to latest (3.1)
Update Docker Images in the table to latest (3.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888b22d0-7261-c6fd-e4b3-07a4c1f66d06
* Version Independent ID: ddfcec03-a396-8851-49cd-629b9c7edc8a
* Content: [What OS to target with .NET containers](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/net-container-os-targets#feedback)
* Content Source: [docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

### PR DESCRIPTION
**Pull request by Marusyk**
## Summary

Update Docker Images in the table to latest (3.1)

Fixes #16500

### CODE REVIEW

**Review by Thraka — APPROVED** [review]
LGTM

**Comment by mairaw** [comment]
I think this PR should be closed. The book is specific for 2.2 for now: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/

**Comment by Thraka** [comment]
I'm not going to merge, I just approved it and would wait for the code owner to reply

**Comment by nishanil** [comment]
There is a WIP PR https://github.com/dotnet/docs/pull/16202 that updates the entire book. The table will be updated as part of that. I suggest closing this one.

**Comment by mairaw** [comment]
Awesome @nishanil! Closing this one then. Thanks for trying to help @Marusyk!

**Pull request closed without merging**
