### PR TITLE
Minor spelling fix: test-asp-net-core-mvc-apps.md

### PR DESCRIPTION
**Pull request by antonymott**
# Summary

In Test Naming section: you -> your

Fixes #Issue_Number (if available)
none

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thanks for fixing that typo @antonymott. Your change looks great. But the issue you referenced doesn't seem related to this. Did you intend to link to a different issue or was this just a site malfunction? Thanks!

**Comment by antonymott** [comment]
Thanks @mairaw. Not sure how the referenced issue got in there, as I was only fixing that minor typo, not referencing any existing issue.
Really appreciate the docs/articles: informative, well written and reflect favorably on MS and the .net community. Have a great day!

**Comment by mairaw** [comment]
Thank you! Just removed the reference then.

**Comment by mairaw** [comment]
And really appreciate your comments ❤️

**Pull request merged**
