### PR TITLE
fixes firstFinishedTask typo

### LINKED ISSUE #22313: typo
rename firstFinishedTask  to just finishedTask on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d15bb1b-5f7f-20f3-78c3-d2b5bce950ed
* Version Independent ID: 80bee493-257b-5c64-4f28-cfb4e9bae560
* Content: [Process asynchronous tasks as they complete](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete)
* Content Source: [docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by LeoGaunt**
## Changes firstFinishedTask to finishedTask

Fixes #22313

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
The parallel VB article could be fixed too.

**Comment by LeoGaunt** [comment]
@Youssef1313 Looking closer there's 2 other articles as well as this one that use firstFinishedTask instead of finishedTask

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=22385) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=22385) before we can accept your contribution.<br/><br/>:x: LeoGaunt [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=22385)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=22385) it.</sub>

**Review by BillWagner — APPROVED** [review]
Thanks for making these updates @LeoGaunt 

I've reviewed the changes, and I'll :shipit: now.  You should see the changes live in the next day or two on our regular publishing cycle.

Thanks again! 🎆

**Pull request merged**
