### PR TITLE
Adding content to .NET Primer

### PR DESCRIPTION
**Pull request by thesmithee**
Adding content to .NET primer, so far just generics, type safety and delegates and lambdas.

/cc @richlander

### CODE REVIEW

**Comment by richlander** [comment]
A few things don't seem right with this PR:

- The author is mess up again.
- Some of the commits seem duplicated.
- Seems like a lot of commits.

**Comment by blackdwarf** [comment]
OK, so rebased and the commit situation is now much more sane. :) Each commit is actually a logical whole, so it shouldn't be a problem.

**Comment by richlander** [comment]
LGTM

**Comment by blackdwarf** [comment]
Great, merging.

**Pull request merged**
