### PR TITLE
updated netstandard version

### PR DESCRIPTION
**Pull request by mairaw**
This has been on my to-do list for a while to check if we still had any references to .NET Standard 1.5 and change them to 1.6.

/cc @blackdwarf

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/migrating-from-dnx?branch=pr-en-us-1169](https://review.docs.microsoft.com/en-us/dotnet/articles/core/migrating-from-dnx?branch=pr-en-us-1169)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1169](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1169)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C24%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610241836536391-1169%5Cworkflow_report.html).

**Comment by blackdwarf** [comment]
LGTM

/cc @cartermp for more in-depth look

**Comment by cartermp** [comment]
LGTM!

**Comment by mairaw** [comment]
Thanks guys!

**Pull request merged**
