### PR TITLE
Updated AppContext switches article

### PR DESCRIPTION
**Pull request by rpetrusha**
## Updated AppContext switches article

Contributes to #11630

### CODE REVIEW

**Comment by mairaw** [comment]
I've checked this article off from the list I'm tracking for the release at #11630

**Review by mairaw — APPROVED** [review]
LGTM

But what happened to the other one?

**Comment by rpetrusha** [comment]
What other one, @mairaw?

**Comment by rpetrusha** [comment]
I haven't checked anything off the list at #11630 -- I'll do that now.

**Pull request merged**
