### PR TITLE
Remove text that was causing loc issues

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes https://github.com/dotnet/docs.pl-pl/issues/206

### CODE REVIEW

**Review by gewarren — APPROVED** [review]
It would be good to understand why "(zero seconds)" caused a loc issue?

**Comment by tdykstra** [comment]
Because zero isn't zero seconds, it's a number that gets interpreted to mean "use the default", which is 300 seconds.

**Comment by gewarren** [comment]
Oops, this should be reverted. The base branch was live.

**Comment by BillWagner** [comment]
> Oops, this should be reverted. The base branch was live.

Or just cherry-pick it into master.

**Pull request merged**
