### PR TITLE
Add "enable_uhf_ppe" feature flag to docfx.json.

### PR DESCRIPTION
**Pull request by jeahyoun**
## Summary

This PR enables the feature flag to use the new UHF. See the work item here (https://ceapex.visualstudio.com/Engineering/UX%20Team/_backlogs/board/Stories) and the related feature ticket here (https://ceapex.visualstudio.com/Engineering/UX%20Team/_workitems/edit/18194).

This change can be merged into master for testing on our review site. The feature is not live yet so this merge would have no effect on production presentation.

[Internal review site](https://review.docs.microsoft.com/dotnet/index?branch=pr-en-us-5919)

edit by @billwagner: Add internal review link

### CODE REVIEW

**Comment by BillWagner** [comment]
Add "WIP" to title.

**Comment by mairaw** [comment]
It seems this should be merged @BillWagner.

**Comment by BillWagner** [comment]
@mairaw I've got an offline question to @jeahyoun. Waiting to hear back.

**Comment by jeahyoun** [comment]
Hey @BillWagner, I see a note that you have an offline question, but I didn't see any notification of this. I'm not sure if something slipped through the cracks (I didn't see anything in my email, in Teams, or in the VSTS ticket). I hope I didn't miss anything from you. If you resend, I can address this. Thanks!

**Comment by BillWagner** [comment]
@jeahyoun I just resent the email.

**Comment by adkinn** [comment]
@BillWagner @mairaw @jeahyoun any open questions here? We've shipped our code and we'd like to start the test.

**Comment by BillWagner** [comment]
I don't have any concerns. When ready to merge, just remove the "WIP" label. We'll merge and see how that looks on the master branch on review.  If there are no issues, we'll push live.

**Comment by adkinn** [comment]
@BillWagner done and thanks!

**Review by BillWagner — APPROVED** [review]
Thanks for confirming all the testing work.

I'll :shipit: now @jeahyoun @adkinn

**Pull request merged**
