### PR TITLE
Migration update: datetime group

### PR DESCRIPTION
**Pull request by guardrex**
* Handle includes and in-text *.NET Framework* refs
* List ❤️
* Table 🐄🔔
* Sentence case titles
* Pesky double-spaces removed

... and I capitalized the word "Earth" :grinning:

### CODE REVIEW

**Comment by GuardRex** [comment]
@tompratt-AQ Can you help? ... I'd :heart: to get these in asap.

**Comment by tompratt-AQ** [comment]
Sure, I'll take a look.

**Review by tompratt-AQ — CHANGES_REQUESTED** [review]
Just one small nit - not your change - but we can clean it up anyway:  In this file: cs/standard/datetime/converting-between-datetime-and-offset.md, there are two tables. Both tables have DateTime.Kind property in the header, but only one table marks it as a property (using '). I lean against marking it as a property since we say the word property. But, I'm ok wither way as long as they are both the same.

**Comment by GuardRex** [comment]
> converting-between-datetime-and-offset.md

`converting-between-time-zones.md` .... yes ... I see what u mean. In addition, the first column of the first table doesn't distinguish the rows in any way. I'll make them both inline code without the "property" naming. See if this works here. Regarding the first table, I'd suggest we hit that on the next pass unless you think there's a quick/good way to fix it.

**Review by tompratt-AQ — COMMENTED** [review]
I'm guessing that the first table was meant to have the same values in that column as the second table (Local, and then Unspecified). But, there is no way to tell for sure in this pass.

**Comment by GuardRex** [comment]
@tompratt-AQ yeah ... I hate this 1st table. Let's hold for a sec while I look at it. A table with a first column that doesn't distinguish its rows is an **ABOMINATION before the :pray: server gods :pray:**, and I'd hate to be cast into the fires of **Perl HELL** 👿 for letting this pass. Let me see what I can do with it.

**Comment by GuardRex** [comment]
@tompratt-AQ I feel a bit more comfortable with this update based on ...

https://msdn.microsoft.com/en-us/library/bb381744(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.datetime.tolocaltime(v=vs.110).aspx

What da ya tinks?

**Review by tompratt-AQ — APPROVED** [review]
Thanks for fixing that table. Your changes look correct to me.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
