### PR TITLE
Update migration guides

### PR DESCRIPTION
**Pull request by chlowell**
@rpetrusha Here's the generated output. I noticed some manual edits to the existing docs (URL changes and escaping) which the generator doesn't match but this should take you most of the way. I think the table of contents needs 4.8 links as well.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for doing this so quickly, @chlowell. I'll review the PR tomorrow and use it to make fixes in the microsoft/dotnet repo.

**Comment by rpetrusha** [comment]
I've resolved all of the build issues here and made parallel changes in the microsoft/dotnet repo, @chlowell. Do you want to try a new migration just to make sure?

**Comment by chlowell** [comment]
Looks good to me.

**Comment by rpetrusha** [comment]
Closing, since this PR is replaced by #11915

**Pull request closed without merging**
