### PR TITLE
Add new APIs

### PR DESCRIPTION
**Pull request by mairaw**
Docs for new APIscan hits

@dotnet/dotnet-wcf for System.ServiceModel
@davidsh for System.Net

Internal review links:
- https://review.docs.microsoft.com/en-us/dotnet/framework/additional-apis/system.net.rtcstate?branch=pr-en-us-15651
- https://review.docs.microsoft.com/en-us/dotnet/framework/additional-apis/system.servicemodel.channels.message.bodytostring?branch=pr-en-us-15651
- https://review.docs.microsoft.com/en-us/dotnet/framework/additional-apis/system.servicemodel.channels.message.writestartheaders?branch=pr-en-us-15651

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Adding @HongGit

**Review by davidsh — APPROVED** [review]
LGTM for System.Net

**Review by BillWagner — APPROVED** [review]
These look fine to me @mairaw 

Once you're satisfied with product team reviews, you can :shipit:

**Comment by mconnew** [comment]
Can you explain why these api's are being added to documentation as they are internal?

**Comment by mairaw** [comment]
APIscan @mconnew. Are you familiar with that? Otherwise, I can send you some info offline.

**Comment by HongGit** [comment]
@mairaw can you please share the info with me?  I am also interested in this topic.

**Review by HongGit — APPROVED** [review]

**Comment by mconnew** [comment]
@mairaw, can you please send me the info offline.

**Review by HongGit — COMMENTED** [review]
@mariaw could we hold off on this PR?  We have some questions we need to sort it out before checkin this PR?

**Review by HongGit — APPROVED** [review]

**Comment by mairaw** [comment]
Yes @HongGit. I'm not merging this until I get a clear resolution on our internal thread.

**Review by mconnew — APPROVED** [review]

**Pull request merged**
