### PR TITLE
typo: Exectue -> Execute

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by mairaw — DISMISSED** [review]
For this one, I think the same typo will have to be fixed in the samples repo too:
https://github.com/dotnet/samples/search?q=ExectueRefTypeQuery&unscoped_q=ExectueRefTypeQuery

**Comment by nschonni** [comment]
Opened https://github.com/dotnet/samples/pull/1022

**Comment by nschonni** [comment]
Other PR has been merged

**Review by BillWagner — APPROVED** [review]
I merged the corresponding samples PR.

I'll approve and :shipit: now.

**Pull request merged**
