### PR TITLE
Fix for MSBuild Error MSB1003

### PR DESCRIPTION
**Pull request by bharathkumarms**
To build and run .NET core application, the proj file is required. So, prior to ‘dotnet restore’, ‘dotnet migrate’ command has to be executed.

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by bharathkumarms** [comment]
Hi There, Please clarify, if I have merge access to master branch.

**Comment by cartermp** [comment]
cc @BillWagner 

I'm not sure this change is appropriate at this time, given that the tooling one migrates to is still in preview.  Offering official guidance to migrate doesn't seem right since the project.json-based tooling is still shipping in the LTS release of the .NET Core SDK.

However, this could be modified to be a conditional statement; e.g., "If you have created a project before using the `project.json`-based tooling, you will have to migrate it using the `dotnet migrate` command".

**Comment by bharathkumarms** [comment]
@cartermp 

Thanks. I wish to drop it and fix other open issues.

**Comment by mairaw** [comment]
Thanks @bharathkumarms! We'll bring the changes containing the csproj steps at a later time. Closing this for now.

**Pull request closed without merging**
