### PR TITLE
Adding missing . to project path example

### LINKED ISSUE #6103: Unknown switch error when running example code
Executing the line
dotnet run --project /projects/proj1/proj1.csproj
returns an error saying unknown switch. I think it should be corrected to:
dotnet run --project ./projects/proj1/proj1.csproj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3f4227-cd9b-7b1c-7e1b-ffb3d42ae496
* Version Independent ID: 7e78f9f5-f77c-828d-ef76-8ef8593d5803
* Content: [dotnet run command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-run.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-run.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by Thraka**
## Summary

Added missing relative path qualifier.

Fixes #6103

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
"the alone -- argument" is awkward. Perhaps instead, "since it is preceded by the \`--\` option."?

**Comment by Thraka** [comment]
@rpetrusha I wasn't sure about that either. When i was reading the article originally, the clause caught me off guard and my internal response was "Which -- option?" 

Maybe changing it to something like "blank '--' argument" ??

**Comment by rpetrusha** [comment]
That sounds good, @Thraka, except I'd describe it as an option rather than an argument to be consistent with the rest of the topic.

**Review by rpetrusha — APPROVED** [review]
LGTM, @Thraka. You can merge when you're ready.

**Comment by Thraka** [comment]
@rpetrusha ping

**Comment by Thraka** [comment]
ok thanks!

**Pull request merged**
