### PR TITLE
Changed link

### PR DESCRIPTION
**Pull request by msschl**
## Summary

Changed link to https://docs.microsoft.com/aspnet/core/ so that the link works from github.

### CODE REVIEW

**Comment by mairaw** [comment]
I'll close this PR @msschl. The reason why we use that kind of link is to make the links work in between the offline books in Visual Studio.  It has the downside of not working in GitHub, unfortunately.

**Comment by NextTurn** [comment]
What about the present docs.ms links? Should they be changed to that kind?

**Comment by mairaw** [comment]
We try to only use this format for the content that has offline books. The others we keep with the domain. I can try to clarify that in our style guide. But the content that has offline books is ASP.NET, VS, Windows, SQL and EF.

**Pull request closed without merging**
