### PR TITLE
Fix link to runtime.json

### LINKED ISSUE #15502: runtime.json link is broken
Links lead to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#feedback)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by johnallers**
Fixes #15502

### CODE REVIEW

**Comment by Youssef1313** [comment]
May you add:
Fixes #15502
for the issue to be closed automatically after this is merged ?

**Comment by johnallers** [comment]
@Youssef1313 Done.

**Review by mairaw — CHANGES_REQUESTED** [review]
Thank you @johnallers for jumping on the issue and fixing the broken links. I ran link checker and there are two other additional links that are broken with the same problem in this article (missing the src folder):
- In the see also section
- In the Linux section

Can you fix those too? Otherwise, I can help. Just let me know. Thanks!

**Comment by johnallers** [comment]
@mairaw Oh, I missed those! The PR has been updated to address that.

**Review by mairaw — APPROVED** [review]
Thank you for making the additional changes. Your contributions should be live within a day.

**Pull request merged**
