### PR TITLE
Getting started again

### PR DESCRIPTION
**Pull request by BillWagner**
Update the getting started scenarios for Nov 2016

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/testing-library-with-visual-studio.md) | :x:Error | | [Details](#user-content-docs/csharp/getting-started/testing-library-with-visual-studio.md)
[docs/csharp/getting-started/debugging-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/debugging-with-visual-studio-2017.md) | :warning:Warning | | [Details](#user-content-docs/csharp/getting-started/debugging-with-visual-studio-2017.md)
[docs/csharp/getting-started/library-with-visual-studio_2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/library-with-visual-studio_2017.md) | :warning:Warning | | [Details](#user-content-docs/csharp/getting-started/library-with-visual-studio_2017.md)
[docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md)
[docs/csharp/getting-started/media/add-lib-ref.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/add-lib-ref.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/add-lib-ref.jpg)
[docs/csharp/getting-started/media/add_reference.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/add_reference.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/add_reference.jpg)
[docs/csharp/getting-started/media/breakpoint_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/breakpoint_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/breakpoint_2017.jpg)
[docs/csharp/getting-started/media/breakpoint_settings.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/breakpoint_settings.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/breakpoint_settings.jpg)
[docs/csharp/getting-started/media/class_library.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/class_library.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/class_library.jpg)
[docs/csharp/getting-started/media/codewindow_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/codewindow_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/codewindow_2017.jpg)
[docs/csharp/getting-started/media/console_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/console_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/console_2017.jpg)
[docs/csharp/getting-started/media/emptystring.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/emptystring.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/emptystring.jpg)
[docs/csharp/getting-started/media/failed_test.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/failed_test.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/failed_test.jpg)
[docs/csharp/getting-started/media/failed_test2.JPG](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/failed_test2.JPG) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/failed_test2.JPG)
[docs/csharp/getting-started/media/first_test.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/first_test.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/first_test.jpg)
[docs/csharp/getting-started/media/lib_project.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/lib_project.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/lib_project.jpg)
[docs/csharp/getting-started/media/lib_release.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/lib_release.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/lib_release.jpg)
[docs/csharp/getting-started/media/select_core.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/select_core.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/select_core.jpg)
[docs/csharp/getting-started/media/setbreakpoint_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/setbreakpoint_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/setbreakpoint_2017.jpg)
[docs/csharp/getting-started/media/showcase-toolbar.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/showcase-toolbar.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/showcase-toolbar.jpg)
[docs/csharp/getting-started/media/simple_hello.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/simple_hello.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/simple_hello.jpg)
[docs/csharp/getting-started/media/solution-explorer.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/solution-explorer.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/solution-explorer.jpg)
[docs/csharp/getting-started/media/solution.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/solution.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/solution.jpg)
[docs/csharp/getting-started/media/step_into.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/step_into.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/step_into.jpg)
[docs/csharp/getting-started/media/step_into_2.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/step_into_2.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/step_into_2.jpg)
[docs/csharp/getting-started/media/testproject.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/testproject.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/testproject.jpg)
[docs/csharp/getting-started/media/unit_test_code_window.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/unit_test_code_window.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/unit_test_code_window.jpg)
[docs/csharp/getting-started/media/use-library.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/use-library.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/use-library.jpg)
[docs/csharp/getting-started/media/vs_devenv_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/vs_devenv_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/vs_devenv_2017.jpg)
[docs/csharp/getting-started/media/vs_newproject_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/vs_newproject_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/vs_newproject_2017.jpg)
[docs/csharp/getting-started/media/vs_with_solution.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/vs_with_solution.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/vs_with_solution.jpg)
[docs/csharp/getting-started/publishing-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/publishing-with-visual-studio-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/publishing-with-visual-studio-2017.md)
[docs/csharp/getting-started/with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/with-visual-studio-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/with-visual-studio-2017.md)
[samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs](https://github.com/BillWagner/docs/blob/getting-started-again/samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs)
[samples/snippets/csharp/getting_started/with_visual_studio_2017/showcase.cs](https://github.com/BillWagner/docs/blob/getting-started-again/samples/snippets/csharp/getting_started/with_visual_studio_2017/showcase.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/snippets/csharp/getting_started/with_visual_studio_2017/showcase.cs)
[samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs](https://github.com/BillWagner/docs/blob/getting-started-again/samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs)

<a name="docs/csharp/getting-started/testing-library-with-visual-studio.md"></a>
### [docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/testing-library-with-visual-studio.md)
 - **Line Unspecified**: **[Error]** Unable to resolve [!CODE-csharp[Test#1](../../../samples/snippets/csharp/getting_started/library-with_visual_studio/testlib1.cs#1)]

. Can not find reference ../../../samples/snippets/csharp/getting_started/library-with_visual_studio/testlib1.cs. at line 78.
 - **Line 18**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/library-with-visual-studio.md).

<a name="docs/csharp/getting-started/debugging-with-visual-studio-2017.md"></a>
### [docs/csharp/getting-started/debugging-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/debugging-with-visual-studio-2017.md)
 - **Line Unspecified**: **[Warning]** Invalid cross reference &quot;&lt;a href=&quot;xref:System.Console.ReadLine()&quot; sourcefile=&quot;docs/csharp/getting-started/debugging-with-visual-studio-2017.md&quot; sourcestartlinenumber=&quot;122&quot; sourceendlinenumber=&quot;122&quot;&gt;Console.ReadLine&lt;/a&gt;&quot;, &quot;&lt;a href=&quot;xref:System.Console.ReadLine()&quot; sourcefile=&quot;docs/csharp/getting-started/debugging-with-visual-studio-2017.md&quot; sourcestartlinenumber=&quot;124&quot; sourceendlinenumber=&quot;124&quot;&gt;Console.ReadLine&lt;/a&gt;&quot;.

<a name="docs/csharp/getting-started/library-with-visual-studio_2017.md"></a>
### [docs/csharp/getting-started/library-with-visual-studio_2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/library-with-visual-studio_2017.md)
 - **Line 20**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/..../standard/library.md).
 - **Line Unspecified**: **[Warning]** Invalid cross reference &quot;&lt;a href=&quot;xref:System.Char.IsUpperCase(System.Char)&quot; sourcefile=&quot;docs/csharp/getting-started/library-with-visual-studio_2017.md&quot; sourcestartlinenumber=&quot;54&quot; sourceendlinenumber=&quot;54&quot;&gt;Char.IsUpperCase&lt;/a&gt;&quot;.


































For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611161313407797-1247%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/testing-library-with-visual-studio.md) | :x:Error | | [Details](#user-content-docs/csharp/getting-started/testing-library-with-visual-studio.md)
[docs/csharp/getting-started/debugging-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/debugging-with-visual-studio-2017.md) | :warning:Warning | | [Details](#user-content-docs/csharp/getting-started/debugging-with-visual-studio-2017.md)
[docs/csharp/getting-started/library-with-visual-studio_2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/library-with-visual-studio_2017.md) | :warning:Warning | | [Details](#user-content-docs/csharp/getting-started/library-with-visual-studio_2017.md)
[docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md)
[docs/csharp/getting-started/media/add-lib-ref.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/add-lib-ref.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/add-lib-ref.jpg)
[docs/csharp/getting-started/media/add_reference.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/add_reference.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/add_reference.jpg)
[docs/csharp/getting-started/media/breakpoint_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/breakpoint_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/breakpoint_2017.jpg)
[docs/csharp/getting-started/media/breakpoint_settings.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/breakpoint_settings.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/breakpoint_settings.jpg)
[docs/csharp/getting-started/media/class_library.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/class_library.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/class_library.jpg)
[docs/csharp/getting-started/media/codewindow_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/codewindow_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/codewindow_2017.jpg)
[docs/csharp/getting-started/media/console_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/console_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/console_2017.jpg)
[docs/csharp/getting-started/media/emptystring.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/emptystring.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/emptystring.jpg)
[docs/csharp/getting-started/media/failed_test.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/failed_test.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/failed_test.jpg)
[docs/csharp/getting-started/media/failed_test2.JPG](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/failed_test2.JPG) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/failed_test2.JPG)
[docs/csharp/getting-started/media/first_test.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/first_test.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/first_test.jpg)
[docs/csharp/getting-started/media/lib_project.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/lib_project.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/lib_project.jpg)
[docs/csharp/getting-started/media/lib_release.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/lib_release.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/lib_release.jpg)
[docs/csharp/getting-started/media/select_core.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/select_core.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/select_core.jpg)
[docs/csharp/getting-started/media/setbreakpoint_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/setbreakpoint_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/setbreakpoint_2017.jpg)
[docs/csharp/getting-started/media/showcase-toolbar.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/showcase-toolbar.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/showcase-toolbar.jpg)
[docs/csharp/getting-started/media/simple_hello.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/simple_hello.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/simple_hello.jpg)
[docs/csharp/getting-started/media/solution-explorer.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/solution-explorer.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/solution-explorer.jpg)
[docs/csharp/getting-started/media/solution.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/solution.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/solution.jpg)
[docs/csharp/getting-started/media/step_into.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/step_into.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/step_into.jpg)
[docs/csharp/getting-started/media/step_into_2.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/step_into_2.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/step_into_2.jpg)
[docs/csharp/getting-started/media/testproject.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/testproject.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/testproject.jpg)
[docs/csharp/getting-started/media/unit_test_code_window.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/unit_test_code_window.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/unit_test_code_window.jpg)
[docs/csharp/getting-started/media/use-library.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/use-library.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/use-library.jpg)
[docs/csharp/getting-started/media/vs_devenv_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/vs_devenv_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/vs_devenv_2017.jpg)
[docs/csharp/getting-started/media/vs_newproject_2017.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/vs_newproject_2017.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/vs_newproject_2017.jpg)
[docs/csharp/getting-started/media/vs_with_solution.jpg](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/media/vs_with_solution.jpg) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/media/vs_with_solution.jpg)
[docs/csharp/getting-started/publishing-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/publishing-with-visual-studio-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/publishing-with-visual-studio-2017.md)
[docs/csharp/getting-started/with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/with-visual-studio-2017.md) | :white_check_mark:Succeeded | | [Details](#user-content-docs/csharp/getting-started/with-visual-studio-2017.md)
[samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs](https://github.com/BillWagner/docs/blob/getting-started-again/samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs)
[samples/snippets/csharp/getting_started/with_visual_studio_2017/showcase.cs](https://github.com/BillWagner/docs/blob/getting-started-again/samples/snippets/csharp/getting_started/with_visual_studio_2017/showcase.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/snippets/csharp/getting_started/with_visual_studio_2017/showcase.cs)
[samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs](https://github.com/BillWagner/docs/blob/getting-started-again/samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs) | :white_check_mark:Succeeded | | [Details](#user-content-samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs)

<a name="docs/csharp/getting-started/testing-library-with-visual-studio.md"></a>
### [docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/testing-library-with-visual-studio.md)
 - **Line Unspecified**: **[Error]** Unable to resolve [!CODE-csharp[Test#1](../../../samples/snippets/csharp/getting_started/with_visual_studio/testlib1.cs#1)]

. Can not find reference ../../../samples/snippets/csharp/getting_started/with_visual_studio/testlib1.cs. at line 78.
 - **Line 18**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/library-with-visual-studio.md).

<a name="docs/csharp/getting-started/debugging-with-visual-studio-2017.md"></a>
### [docs/csharp/getting-started/debugging-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/debugging-with-visual-studio-2017.md)
 - **Line Unspecified**: **[Warning]** Invalid cross reference &quot;&lt;a href=&quot;xref:System.Console.ReadLine()&quot; sourcefile=&quot;docs/csharp/getting-started/debugging-with-visual-studio-2017.md&quot; sourcestartlinenumber=&quot;122&quot; sourceendlinenumber=&quot;122&quot;&gt;Console.ReadLine&lt;/a&gt;&quot;, &quot;&lt;a href=&quot;xref:System.Console.ReadLine()&quot; sourcefile=&quot;docs/csharp/getting-started/debugging-with-visual-studio-2017.md&quot; sourcestartlinenumber=&quot;124&quot; sourceendlinenumber=&quot;124&quot;&gt;Console.ReadLine&lt;/a&gt;&quot;.

<a name="docs/csharp/getting-started/library-with-visual-studio_2017.md"></a>
### [docs/csharp/getting-started/library-with-visual-studio_2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/library-with-visual-studio_2017.md)
 - **Line 20**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/..../standard/library.md).
 - **Line Unspecified**: **[Warning]** Invalid cross reference &quot;&lt;a href=&quot;xref:System.Char.IsUpperCase(System.Char)&quot; sourcefile=&quot;docs/csharp/getting-started/library-with-visual-studio_2017.md&quot; sourcestartlinenumber=&quot;54&quot; sourceendlinenumber=&quot;54&quot;&gt;Char.IsUpperCase&lt;/a&gt;&quot;.


































For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611161340507960-1247%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/getting-started/debugging-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/debugging-with-visual-studio-2017.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/debugging-with-visual-studio-2017?branch=pr-en-us-1247) | [Details](#user-content-docs/csharp/getting-started/debugging-with-visual-studio-2017.md)
[docs/csharp/getting-started/library-with-visual-studio_2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/library-with-visual-studio_2017.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/library-with-visual-studio_2017?branch=pr-en-us-1247) | [Details](#user-content-docs/csharp/getting-started/library-with-visual-studio_2017.md)
[docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/testing-library-with-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/testing-library-with-visual-studio?branch=pr-en-us-1247) | [Details](#user-content-docs/csharp/getting-started/testing-library-with-visual-studio.md)
[docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/consuming-library-with-visual-studio-2017?branch=pr-en-us-1247) | [Details](#user-content-docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md)
[docs/csharp/getting-started/publishing-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/publishing-with-visual-studio-2017.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/publishing-with-visual-studio-2017?branch=pr-en-us-1247) | [Details](#user-content-docs/csharp/getting-started/publishing-with-visual-studio-2017.md)
[docs/csharp/getting-started/with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/with-visual-studio-2017.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-2017?branch=pr-en-us-1247) | [Details](#user-content-docs/csharp/getting-started/with-visual-studio-2017.md)

<a name="docs/csharp/getting-started/debugging-with-visual-studio-2017.md"></a>
### [docs/csharp/getting-started/debugging-with-visual-studio-2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/debugging-with-visual-studio-2017.md)
 - **Line Unspecified**: **[Warning]** Invalid cross reference &quot;&lt;a href=&quot;xref:System.Console.ReadLine()&quot; sourcefile=&quot;docs/csharp/getting-started/debugging-with-visual-studio-2017.md&quot; sourcestartlinenumber=&quot;122&quot; sourceendlinenumber=&quot;122&quot;&gt;Console.ReadLine&lt;/a&gt;&quot;, &quot;&lt;a href=&quot;xref:System.Console.ReadLine()&quot; sourcefile=&quot;docs/csharp/getting-started/debugging-with-visual-studio-2017.md&quot; sourcestartlinenumber=&quot;124&quot; sourceendlinenumber=&quot;124&quot;&gt;Console.ReadLine&lt;/a&gt;&quot;.

<a name="docs/csharp/getting-started/library-with-visual-studio_2017.md"></a>
### [docs/csharp/getting-started/library-with-visual-studio_2017.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/library-with-visual-studio_2017.md)
 - **Line 20**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/..../standard/library.md).
 - **Line Unspecified**: **[Warning]** Invalid cross reference &quot;&lt;a href=&quot;xref:System.Char.IsUpperCase(System.Char)&quot; sourcefile=&quot;docs/csharp/getting-started/library-with-visual-studio_2017.md&quot; sourcestartlinenumber=&quot;54&quot; sourceendlinenumber=&quot;54&quot;&gt;Char.IsUpperCase&lt;/a&gt;&quot;.

<a name="docs/csharp/getting-started/testing-library-with-visual-studio.md"></a>
### [docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/BillWagner/docs/blob/getting-started-again/docs/csharp/getting-started/testing-library-with-visual-studio.md)
 - **Line 18**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/library-with-visual-studio.md).




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611161418046699-1247%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by BillWagner** [comment]
Already reviewed internally.  Time to :shipit:

**Pull request merged**
