### PR TITLE
Remove Visual Basic samples page

### PR DESCRIPTION
**Pull request by rpetrusha**
## Remove Visual Basic samples page

I thought it best to remove this page because:
- It's major role is to point to Code Gallery, which will be retired.
- Its links don't provide focused access to Visual Basic examples, but instead link to Visual Studio examples on Code Gallery and to developers examples on Code Gallery.

### CODE REVIEW

**Comment by KathleenDollard** [comment]
Retiring this page makes sense. 

Will there be Visual Basic samples in the new samples system? Is there a way to link to that? I'm wondering what the new experience will be for programmers looking for VB samples.

**Comment by rpetrusha** [comment]
If we use existing samples from Code Gallery, @KathleenDollard, they'll have to be migrated. Perhaps we should meet to discuss sample migration?

**Comment by mairaw** [comment]
There's a link on the new samples system but it only has two samples so far.
https://docs.microsoft.com/en-us/samples/browse/?languages=vb

**Review by mairaw — APPROVED** [review]
LGTM

**Pull request merged**
