### PR TITLE
Alphabetize removed types

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
Looks good to me, :shipit: when you're ready.

**Comment by gewarren** [comment]
Thanks David!

**Comment by IEvangelist** [comment]
> Thanks David!

Hey, @gewarren did you use the VS Code extension to select and sort these? If not, just wanted you to know it's there : https://docs.microsoft.com/en-us/contribute/docs-authoring/sort-selection

**Comment by gewarren** [comment]
> > Thanks David!
> 
> Hey, @gewarren did you use the VS Code extension to select and sort these? If not, just wanted you to know it's there : https://docs.microsoft.com/en-us/contribute/docs-authoring/sort-selection

No, I did not! But I should have. One problem may be that for the xref links that aren't displayed with their full name, the "displayed" alphabetical order is actually different to the markdown alphabetical order. For example:

System.Apple
System.Cantaloupe.Seed
System.Pineapple

Displays as:

Apple
Seed
Pineapple

**Pull request merged**
