### PR TITLE
Added 'Data Types' child TOC to main TOC

### LINKED ISSUE #8915: Search not finding documents
[I was trying to find out a detail about VB.Net structures, so went to the main VB page, typed "structures" into the search box, and found no relevant matches - only for F#! There's perfectly good page called "structures" at https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/structures  I'd attach a screen shot but it doesn't work.

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675b0c08-6b7f-b01b-4b1a-eda4618d6430
* Version Independent ID: db682cf0-c8e9-a054-7b24-3cc19aaf0a98
* Content: [Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/index)
* Content Source: [docs/visual-basic/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

### PR DESCRIPTION
**Pull request by rpetrusha**
## Added 'Data Types' child TOC to main TOC

This PR:

- Adds the Visual Basic **Data Types** TOC to the main .NET TOC.
- Deletes the child **Data Types** TOC.

Fixes #8915 

@KathleenDollard @pkulikov @ptoye

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @rpetrusha 

You can :shipit: when ready.

**Comment by ptoye** [comment]
I still don't think it's right. Starting from  https://docs.microsoft.com/en-us/dotnet/visual-basic/ , which would seem to me to be a reasonable starting point for a search for a VB language topic, searching for "structures" doesn't find https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/structures which is the main page for the subject.

I don't know how the topics are indexed, but surely something's still wrong here.

**Comment by KathleenDollard** [comment]
@rpetrusha what is our general handling of plurals. 

Structure is the actual thing we're talking about, but I realize someone might look for the plural, and it should still find it.

**Comment by mairaw** [comment]
I can't repro what @ptoye described. The topic shows up for me on the filter:
image
Unless I'm misunderstanding his comment.

**Comment by KathleenDollard** [comment]
That is weird. I thought I repro'd before posting. 

@ptoye can you try this again?

**Comment by ptoye** [comment]
Seems OK now. I'm sure it wasn't when I tried it last! Thanks all for your help.

**Pull request merged**
