### PR TITLE
Remove dotnet_style_namespace_match_folder from IDE0055

### PR DESCRIPTION
**Pull request by patricksadowski**
## Summary

`dotnet_style_namespace_match_folder` has been documented twice, so we should only let one rule win.

### CODE REVIEW

**Review by gewarren — APPROVED** [review]
Thanks @patricksadowski. I'm just wondering if it's better to add the `CompilerVisibleProperty` items to the property file (as is shown in the section you're deleting) for IDE0130, or to add the project directory and root namespace properties directly to the .editorconfig file. @Youssef1313 for thoughts on that too.

**Comment by gewarren** [comment]
> I noticed that IDE0130, IDE0160, and IDE0161 define preferences for namespaces. Maybe a common subcategory would be appropriate. Please let me know if I should do that in another PR.

Are the subcategories defined anywhere in the source code, or is that purely a docs thing? If the latter, then I'm okay with combining them.

**Comment by Youssef1313** [comment]
> Thanks @patricksadowski. I'm just wondering if it's better to add the `CompilerVisibleProperty` items to the property file (as is shown in the section you're deleting) for IDE0130, or to add the project directory and root namespace properties directly to the .editorconfig file. @Youssef1313 for thoughts on that too.

Using `CompilerVisibleProperty` makes more sense to me. I'd even prefer to remove the `.editorconfig` approach in favor of `CompilerVisibleProperty`. Reasons:

1. Requires the user to hard-code `build_property.ProjectDir` and `build_property.RootNamespace` unnecessarily.
2. Due to (1), this isn't scalable in a multi-project solution where every project is in a different directory and have different root namespace. In constrast, the `CompilerVisibleProperty` is copy-pasteable directly in a `Directory.Build.props` to apply to the whole solution.

**Comment by patricksadowski** [comment]
Sorry, I couldn't respond that quickly. Thanks for adding a commit and merging.

> Are the subcategories defined anywhere in the source code, or is that purely a docs thing? If the latter, then I'm okay with combining them.

I have no idea where the information for this documentation came from. Any hint?

**Comment by gewarren** [comment]
@mavasani Are the IDE rule subcategories (e.g. "Language rules (Namespace naming preferences)") defined anywhere in the source code, or are they arbitrary groupings?

**Comment by mavasani** [comment]
Yes, the sub-categories for CodeStyle language rules should be defined for each code style option in code via the mapped OptionGroups:

https://github.com/dotnet/roslyn/blob/5de1a7fdb56ed6e42beddcf4c44df559f7cd909b/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs#L339-L353

https://github.com/dotnet/roslyn/blob/5de1a7fdb56ed6e42beddcf4c44df559f7cd909b/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L258-L266

For example: https://github.com/dotnet/roslyn/blob/5de1a7fdb56ed6e42beddcf4c44df559f7cd909b/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L250-L253

```csharp
 public static readonly Option2<CodeStyleOption2<bool>> PreferTopLevelStatements = CreateOption(
            CSharpCodeStyleOptionGroups.CodeBlockPreferences,
            "csharp_style_prefer_top_level_statements",
            CSharpSyntaxFormattingOptions.Default.PreferTopLevelStatements);
```

**Comment by patricksadowski** [comment]
@gewarren That would mean a group change for my mentioned rules.
| Rule | Option | Docs group | Code group |
|---|---|:-:|:-:|
| IDE0130 | `dotnet_style_namespace_match_folder` | _Namespace naming preferences_ | _Expression-level preferences_ |
| IDE0160, IDE0161 | `csharp_style_namespace_declarations` | _namespace preferences_ | _Code-block preferences_ |

I assume more differences between docs and source code, so I used a little tool. The tool extracted the definitions from the mentioned classes which are included in the NuGet package `Microsoft.CodeAnalysis.CSharp.Workspaces/4.5.0` (2023-02-24). Here is a list of not matching groups. The group in brackets shows the current assigned group in docs.

```
this. and Me. preferences
    dotnet_style_qualification_for_field ('this.' and 'Me.' qualifiers)
    dotnet_style_qualification_for_property ('this.' and 'Me.' qualifiers)
    dotnet_style_qualification_for_method ('this.' and 'Me.' qualifiers)
    dotnet_style_qualification_for_event ('this.' and 'Me.' qualifiers)
Language keywords vs BCL types preferences
    dotnet_style_predefined_type_for_locals_parameters_members (language keywords instead of framework type names for type references)
    dotnet_style_predefined_type_for_member_access (language keywords instead of framework type names for type references)
Expression-level preferences
    dotnet_style_coalesce_expression (null-checking preferences)
    dotnet_style_null_propagation (null-checking preferences)
    dotnet_style_prefer_is_null_check_over_reference_equality_method (null-checking preferences)
    dotnet_style_namespace_match_folder (Namespace naming preferences)
    csharp_style_throw_expression (null-checking preferences)
    csharp_style_unused_value_expression_statement_preference ()
    csharp_style_unused_value_assignment_preference ()
    csharp_style_prefer_null_check_over_type_check (null-checking preferences)
    visual_basic_style_prefer_isnot_expression (pattern matching preferences)
    visual_basic_style_prefer_simplified_object_creation ()
    visual_basic_style_unused_value_expression_statement_preference ()
    visual_basic_style_unused_value_assignment_preference ()
Parameter preferences
    dotnet_code_quality_unused_parameters ()
Field preferences
    dotnet_style_readonly_field (modifier preferences)
Organize usings
    file_header_template (file header preferences)
Suppression preferences
    dotnet_remove_unnecessary_suppression_exclusions ()
Code-block preferences
    csharp_prefer_braces (code block preferences)
    csharp_prefer_simple_using_statement (code block preferences)
    csharp_style_namespace_declarations (namespace preferences)
'using' directive preferences
    csharp_using_directive_placement (`using` directive preferences)
```

@mavasani Where can I find the code style rule of a code style option in code? For example `dotnet_style_namespace_match_folder`. Where is this option assigned to `IDE0130`?

**Comment by gewarren** [comment]
Thanks for that tool and output @patricksadowski! I opened #35098 to track the updated subcategories.

This is a good place to match IDE rule IDs to code style optoins: https://github.com/dotnet/roslyn/blob/a6bccdade39e27abb4ce7fd3c39fe1a9b0657701/src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs#L747-L877

**Pull request merged**
