### PR TITLE
Invoking SetCookie instead of Add

### PR DESCRIPTION
**Pull request by slobo80**
The example incorrectly is invoking Add( method instead of SetCookie

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

### CODE REVIEW

**Comment by rpetrusha** [comment]
Thanks for pointing to this inconsistency, @slobo80. As your PR #1917 notes, though, HttpResponse.SetCookie is for internal use only. Given that, we don't want to provide an example that calls the internal-only member. 
Rather than modifying the code, would you mind revising the comment that precedes the code? It can read something like, "Because the **HttpResponse.SetCookie** method is intended for internal use only, you should not call it in your code. Instead, you can all the **HttpResponse.Cookies.Add** method, as the following example shows." Thanks.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Changes requested in previous comment.

**Comment by GuardRex** [comment]
@rpetrusha ... and note on the VB side?

https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_WebNet/Classic%20HttpResponse.SetCookie%20Example/VB/source.vb

**Comment by GuardRex** [comment]
VB code shows `SetCookie` ...

https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_WebNet/Classic%20HttpResponse.SetCookie%20Example/VB/source.vb

**Comment by rpetrusha** [comment]
Sorry, @slobo80, I looked at the C# code but not the VB code. Would you mind changing the VB code as well to call Add instead of SetCookie? If that's too much trouble, let us know, and we can close this PR and open one ourselves.

**Comment by slobo80** [comment]
Submitted a new PR for the VB code.

**Pull request closed without merging**
