### PR TITLE
Document the `SymbolPackageFormat` property

### PR DESCRIPTION
**Pull request by loic-sharma**
The `SymbolPackageFormat` property is used to create "snupkg" symbol packages, which is what nuget.org accepts. 

/cc @karann-msft @cristinamanum

### CODE REVIEW

**Comment by rpetrusha** [comment]
@JamesNK, can you review this PR?

**Comment by JamesNK** [comment]
Sorry, I'm not familiar with that setting.

**Comment by loic-sharma** [comment]
Here’s nuget’s documentation on this topic: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#creating-a-symbol-package

I sent a change to improve that documentation too: https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg?branch=pr-en-us-1305

**Comment by loic-sharma** [comment]
The changes to NuGet's documentation are now live, you can see the `SymbolPackageFormat` in the example: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#creating-a-symbol-package

**Review by Thraka — APPROVED** [review]
I've used this property and it is documented properly.

**Pull request merged**
