### PR TITLE
fix: docs/framework/whats-new/index.md

### PR DESCRIPTION
**Pull request by nschonni**
Replace "Back to top" links flagged by open build

### CODE REVIEW

**Comment by nschonni** [comment]
Hmm, looks like the build still isn't happy with this

**Comment by nschonni** [comment]
OK, second approach seems like it made OpenBuild happy

**Comment by mairaw** [comment]
I think I'd just remove the Back to top links. I think they were used at a time it was hard to navigate the topic. We now have the In this article menu to replace that.

**Comment by nschonni** [comment]
That's fine if you want to fix it a different way, I was just digging in the build and this seemed like the easiest way to fix the warning

**Comment by nschonni** [comment]
@mairaw I removed the "Back to Top" links

**Review by BillWagner — APPROVED** [review]
This LGTM @nschonni 

I'll :shipit: now.

**Pull request merged**
