### PR TITLE
Expand ITaskItem.GetMetadata return value docs

### PR DESCRIPTION
**Pull request by richardszalay**
Makes explicit the return value when no metadata can be found.

## Summary

The behavior of ItaskItem.GetMetadata was previously ambiguous when called with no metadata is found (ie. Exception vs null vs empty string). I double checked the source before adding the note.

### CODE REVIEW

**Comment by BillWagner** [comment]
closing and re-opening to force a new build.

**Comment by BillWagner** [comment]
@mairaw do you know who should check this change to make sure it's accurate for all implementations of ITaskItem?

**Comment by aaronfranke** [comment]
This PR has a ton of commits and many of them are minor fixups like typo corrections.

Consider rebasing the commits. `git rebase -i 9525fbefa49e98ac1a07788070ea9d0da92e1969` will allow you to rebase that commit. Change the word "pick" to "fixup" for every minor typo-fixing commit. I'm not sure what the policy is for C# docs, but decent-sized commits helps with keeping track of changes.

**Comment by BillWagner** [comment]
@aaronfranke Thanks for the suggestions.  This is an anomaly, and not @richardszalay 's doing.

While this PR was open, we rewrote quite a bit of history as part of splitting the repo See #4789 for details.

We (the core contributor team) will fix this up and merge it.

**Comment by mairaw** [comment]
Hi @richardszalay! Sorry for the delay on reviewing your PR. Unfortunately, your PR got caught in the middle of the process we were doing for #4789. The API documentation now lives under a different repo: https://github.com/dotnet/dotnet-api-docs

Would you mind opening a new PR there and we can get this reviewed?

Thanks!

**Comment by richardszalay** [comment]
No problem, will do!

**Comment by mairaw** [comment]
@richardszalay would you still like to create the PR on https://github.com/dotnet/dotnet-api-docs? Otherwise, we'll take care of creating the PR on your behalf.

**Comment by richardszalay** [comment]
@mairaw Thanks the for the prod, I'd forgotten about this PR. I've created a new PR at [dotnet-api-docs/#331](https://github.com/dotnet/dotnet-api-docs/pull/331)

**Comment by mairaw** [comment]
Thank you @richardszalay!

**Pull request closed without merging**
