### PR TITLE
FIx a broken link in warnaserror-compiler-option

### PR DESCRIPTION
**Pull request by eduard-malakhov**

### CODE REVIEW

**Comment by BillWagner** [comment]
tagging @dend 

Can you suggest a fix that would use the xref syntax instead of the link?

**Comment by eduard-malakhov** [comment]
Hi, I've changed it to xref. but I'm not sure if it compiles correctly. I can't check it locally.

**Comment by BillWagner** [comment]
@eduard-malakhov I'll check it when the build finishes.  Thanks for updating the PR.

**Comment by mairaw** [comment]
We might have to add the VS SDK repo as a dependent repo for the xref service to work.

**Comment by BillWagner** [comment]
Paging @dend 

I looked at the review site, and the link directs to MSDN, which then redirects to the correct docs.microsoft.com location.  Is that what you'd expect?

**Comment by mairaw** [comment]
No @BillWagner. This might be in our yml files. Let me check.

**Comment by mairaw** [comment]
Yep, the link is in this file: https://github.com/dotnet/docs/blob/master/_zip/vs.140.zip 

I wouldn't worry too much about it since it's redirecting to the right place. We'll be removing those zip files and changing to the xref service once we split. But the link seems to be working on production already.

**Review by BillWagner — APPROVED** [review]
Thanks for fixing this @eduard-malakhov 

I'll :shipit: now.  

Thanks for all the contributions you've been making!  We really appreciate it.

**Pull request merged**
