### PR TITLE
adding PowerShell filter

### PR DESCRIPTION
**Pull request by mairaw**
The page https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.supportsdaylightsavingtime?view=netframework-4.7.1 now has a PowerShell example that is always displayed. Trying to see if adding this to the metadata file would enable the filter on that API only.

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
@mairaw, I thought that I'd approve this so that you can merge when you're ready.

**Comment by mairaw** [comment]
So changing from code-ps to code-powershell seems to have worked. The example is now correctly identified as PowerShell. Now the other setting in the metadata file took no effect. Not sure if it's because we need a full build or the metadata value is wrong. @eisenbergeffect who can help here?

**Comment by mairaw** [comment]
So changing from code-ps to code-powershell seems to have worked. The example is now correctly identified as PowerShell. Now the other setting in the metadata file took no effect. Not sure if it's because we need a full build or the metadata value is wrong. @eisenbergeffect who can help here?

**Comment by mairaw** [comment]
So changing from code-ps to code-powershell seems to have worked. The example is now correctly identified as PowerShell. Now the other setting in the metadata file took no effect. Not sure if it's because we need a full build or the metadata value is wrong. @eisenbergeffect who can help here?

**Comment by EisenbergEffect** [comment]
I would ask @adkinn He's my goto when there's issues with dev_langs.

**Comment by adkinn** [comment]
Yep, "powershell" is the right name, "ps" is not.

**Comment by mairaw** [comment]
My tests confirmed that. 😄 
But my question was: how do I enable a different set of filters for a single API @adkinn?

**Comment by adkinn** [comment]
Ah yes, ok. This touches on two issues that we are currently looking to improve:
- The code dropdown is not based on content, it's just hard-coded during the build.
- reference uses the "langs" property name, not "dev_langs" like conceptual

The way to add PowerShell as an option to the language dropdown today would be to add a "langs" value here: https://github.com/dotnet/docs/blob/master/add/metadata/System/TimeZoneInfo.meta.md

I'm not sure if you need to add or overwrite though:
Add
langs:
- powershell

Overwrite
langs:
- csharp
- vb
- powershell

My guess is overwrite.

**Comment by mairaw** [comment]
That's what I tried to do. So it might be a case where we need a full build. I'll merge and see.

**Comment by doctordns** [comment]
@mairaw the change means the sample is now correctly rendered on that page as 'PowerShell'. Great. But the langage drop down is still broken (no PowerShell language and a C++ dropdown even through there are no C++ samples. 

But the sample is on the wrong page - we need to move that sample from https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.supportsdaylightsavingtime?view=netframework-4.7.1 to
https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=netframework-4.7.1

I am not sure why my edit to the XML showed up there.

**Comment by doctordns** [comment]
Actually - I found It was my bad - I put the sample in the wrong bit of the XML. Just submitted a PR to fix that.

**Pull request merged**
