### PR TITLE
Ported changes from similar article to this article.

### LINKED ISSUE #7646: Escaping rules incorrectly described
This document has the description of the connection-string format copied from [Connection Strings in ADO.NET](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-strings.md). It has the same errors as described in issue [#7628](https://github.com/dotnet/docs/issues/7628) about that document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a687d311-41e3-4f63-4ff3-632e3efbcda5
* Version Independent ID: 190e7115-3bd4-7ab7-8512-2110def4ee48
* Content: [Connection Strings](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/connection-strings)
* Content Source: [docs/framework/data/adonet/ef/connection-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/connection-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

### PR DESCRIPTION
**Pull request by douglaslMS**
## Summary

Porting the changes made describing connection string syntax in PR #7972 to fix issue #7628 to this second, similar article about connection strings.

Fixes #7646

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
LGTM, @douglaslMS. You can merge when ready.

**Comment by ant-222** [comment]
@douglaslMS, notice that the important terminology clarification proposed in issue #7770 and accepted in PR #8091 has not been ported. Since *Entity Framework* is a wrapper around *ADO.NET*, its connection strings wrap *ADO.NET* connections strings and have *exactly* the same syntax. What is the use of maintaining two slightly differing copies of the same description? I fear it will only confuse readers. Have you considered removing the duplicated text about connection-string syntax and adding a reference to the [document](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-strings.md) where it is described? The two copies will inevitably diverge (as they do already), which is no good for both maintainers and readers.

Of course, *EF* has its own supported keywords, which this document should focus on.

*P.S.:* Now that I have learned the connection string  syntax, I see that the following statement:

> The value of the `Provider Connection String` must be surrounded by quotes.

is incorrect. Counterexamples:

1. A connection string consisting of a singly parameter and not terminated with a semicolon.

2. A connection string that contain double quotes and therefore must enclosed in single quotation marks.

**Comment by douglaslMS** [comment]
@ant-222 

1. Your suggestion to have the syntax info in only one place is a good one. I will remove that text from the EF connection strings doc, and point to the main ADO.NET connection strings doc.
2. Your previous comment seems to be suggesting further clarifications to the updates that you submitted earlier. Will you please open a PR to update the main ADO.NET connection strings doc ONLY with these clarifications? Make sure you pull from master first so you're working with the latest version.

Thanks.

**Comment by ant-222** [comment]
@douglaslMS, OK, I will make another PR to fix this:

> The value of the Provider Connection String must be surrounded by quotes.

I should like, however, to add a link to the article on connection-string syntax, along the lines of:

> Make sure to use correct escaping when encoding the underlying ADO.NET connection string.

where *correct escaping* would refer to that other article.

**Comment by ant-222** [comment]
@douglaslMS, I have created a PR as promised.

**Comment by douglaslMS** [comment]
@ant-222 I see that, thank you, and will review it as soon as possible.

**Pull request merged**
