### PR TITLE
Fixed spelling

### PR DESCRIPTION
**Pull request by sabahshariq**
Fixed spelling after cleaning up previous commit.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Looks great now! Thanks @ThePiranha. For quick edits, this is probably the quickest way to get the PR done: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents. GitHub would automatically create a new working branch for you, so you don't have to reset master every time.

**Comment by ThePiranha** [comment]
Thanks again! @mairaw , your guide on cleaning up the commits from earlier pull request really helped me to get started.

**Comment by mairaw** [comment]
Good to know! Let us know if you ever need some help with that. Sometimes we get into some messy situations with git.

**Comment by ThePiranha** [comment]
image
and Thank you for considering this PR.

**Pull request merged**
