### PR TITLE
Remove CA1071 from what's new

### PR DESCRIPTION
**Pull request by gewarren**
See #22084, but we shouldn't be publicizing this article yet.

### CODE REVIEW

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Also remove the link under "Related rules" heading in CA1067.

**Comment by BillWagner** [comment]
@gewarren Do you want to convert this to a draft PR so we don't accidentally publish it?

**Comment by gewarren** [comment]
@BillWagner from my standpoint, this is ready to merge. I already removed the article from the TOC and index in #22085. I'll update the title of this PR to be more accurate.

**Review by BillWagner — APPROVED** [review]
LGTM. You can :shipit: when ready.

**Pull request merged**
