### PR TITLE
Remove duplicate topic

### PR DESCRIPTION
**Pull request by richlander**
This file appears to be a duplicate: `docs/framework/install/net-framework-3-5-on-windows-8-plus.md`

I am hoping the build will validate this.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
@richlander, in order to delete the topic, there are two additional housekeeping details that are needed. First, the topic should be removed from the TOC (~/docs/framework/install/toc.md); it's the child of the 3.5 installation topic. Second, we need to redirect from the deleted topic to the 3.5 installation topic; the redirection file is ~/.openpublishing.redirection.json.

**Comment by mairaw** [comment]
This fix has been on my backlog for a while. There is also content on this second page that needs to be ported to the parent one because there's no troubleshooting info on the parent topic. I'll take care of the feedback from @rpetrusha and move the info needed to the parent topic.

**Comment by mairaw** [comment]
@rpetrusha I've made the required changes and the changes I've been wanting to make. Please take a look.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
This is ready to merge when you want, @mairaw.

**Pull request merged**
