### PR TITLE
Use includes for ml samples

### PR DESCRIPTION
**Pull request by BillWagner**
Relies on dotnet/samples#57

### CODE REVIEW

**Comment by BillWagner** [comment]
closing and reopening to trigger a new build. (Samples are merged)

**Review by JRAlexander — APPROVED** [review]
LGTM. Nit: I used "walkthrough" in an earlier version, and those need to be changed to "tutorial".

**Comment by d4m3** [comment]
Just to add, I had to change the Build Language Version to 7.1/7.2 to use with async main (wasn't listed in documentation), to make the change:
Right Click solution project > properties > Build > Advanced > Language version

**Comment by BillWagner** [comment]
@d4m3 Thanks for pointing that out. We'll get that updated as well.

**Pull request merged**
