### PR TITLE
Added a very detailed example

### PR DESCRIPTION
**Pull request by PtrStruct**
I decided to add a visual representation of the difference between reference types & value types.
Show just how they work on the stack as well as on the heap.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by pkulikov** [comment]
@PtrStruct @BillWagner I have several concerns about this PR:
- there should be (I don't know if such already exists) an article in the C# programming guide that explains difference between value and reference types. Then, that article can be linked from the C# reference topics (from both value type and reference type topics). The example from this PR would fit that article.
- explanation should be moved out of comments to the text that explains the example. That makes localization possible.
- at last, stack and heap (the implementation detail) can be omitted when describing the difference between value and reference types. Check related discussion in the following issue: #4561 (especially [this comment of @BillWagner](https://github.com/dotnet/docs/issues/4561#issuecomment-371172346))

**Comment by PtrStruct** [comment]
@pkulikov I did look around the msdn and after doing so, I found this article to be the most fitting one.
There was one showing both types and minor differences, but that was for Visual Basic.
I am making some changes regarding your concern with the comments not being text.

**Comment by BillWagner** [comment]
@PtrStruct 

Thank you for adding this.  However, as @pkulikov mentioned, there are a number of concerns.

First, [this example](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/index#example) and the introduction in the article on classes and structs covers much of this information. 

Second, as I stated in [this comment](https://github.com/dotnet/docs/issues/4561#issuecomment-371172346) value types are "on the stack" except when they aren't. They aren't on the stack when they are members of a reference type, in an array or other collection, captured by a closure, and so on. Your explanation is correct for the cases it covers, but it is misleading by not discussing those other cases.

I suggest we close this PR, you look at the classes and structs article referenced above. Then, if there is important information that you feel is lacking, submit a PR updating that topic.

What are your thoughts?

**Comment by PtrStruct** [comment]
I understand, thanks.
You may close this PR.

**Comment by BillWagner** [comment]
Thanks @PtrStruct 

I'll close this.

**Pull request closed without merging**
