### PR TITLE
Aggregate Canonical Functions topic layout update

### LINKED ISSUE #2738: Aggregate Canonical Functions topic requires attention
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/aggregate-canonical-functions
*docs/framework/data/adonet/ef/language-reference/aggregate-canonical-functions.md*

The topic requires attention with inline code, and table rendering is broken.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #2738

Mostly adjusting the inline code elements of the table and fixing the broken table.

### CODE REVIEW

**Comment by GuardRex** [comment]
Ready for :eyes:

**Review by rpetrusha — CHANGES_REQUESTED** [review]
@GuardRex, this is a vast improvement -- the topic is now readable! None of the C# code, though, is actually C# code. In the source, all the C# code that uses aggregate canonical functions is commented out, and none of the C# code has been assigned snippet labels. You can decide whether you want to add them and include the C# code or not;  the C# code assigns the SQL query string to a string variable named `queryString`.
Also, could you add SQL language tags to the  SQL statements that appear starting with the "Collection-based aggregates" section and below?

**Comment by GuardRex** [comment]
I see what u mean. I'm going tooooo fast trying to get back to my mop-up list. I'll take care of it.

**Comment by GuardRex** [comment]
@rpetrusha Alright ... cook'in with gas now. Try [this version (internal reviewers)](https://review.docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/aggregate-canonical-functions?branch=pr-en-us-2745). External reviewers should use the PR diff.

**Review by rpetrusha — APPROVED** [review]

**Comment by rpetrusha** [comment]
This looks really good, @GuardRex. I'll merge it now.

**Pull request merged**
