### PR TITLE
Updating images

### LINKED ISSUE #16179: Image labels
Image labels don't show when using Dark or High Contrast theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8adaedc-37da-e381-a87e-6649bc6cb3c8
* Version Independent ID: 779340cf-274b-5af9-54f0-b9b90c54f143
* Content: [Tutorial: Automated visual inspection using transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning?wt.mc_id=docsexp6_personal-blog-marouill#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification-api-transfer-learning.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification-api-transfer-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

### PR DESCRIPTION
**Pull request by luisquintanilla**
[Preview Link Image Classification](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning?branch=pr-en-us-16215)
[Preview Link Object Detection](https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx?branch=pr-en-us-16215)
Fixes #16179

### CODE REVIEW

**Comment by Youssef1313** [comment]
New images resolution is lower than the old, was that intended ?

**Comment by lqdev** [comment]
@Youssef1313 which image in particular?

**Comment by Youssef1313** [comment]
> 
> 
> @Youssef1313 which image in particular?

Both of them:

image

image

**Comment by luisquintanilla** [comment]
Thanks @Youssef1313 . Good catch. I've updated them.

**Review by natke — APPROVED** [review]

**Pull request merged**
