### PR TITLE
Fixed mismatch of class name in text and snippet

### LINKED ISSUE #20773: MainClass4?
[Enter feedback here]
MainClass4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ac12d2-0496-d7df-491e-f75a0ff6beb5
* Version Independent ID: 6a8127dd-1d58-63e3-3963-685d9228f1ad
* Content: [public keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/public)
* Content Source: [docs/csharp/language-reference/keywords/public.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/public.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by TheEskhaton**
## Summary

I've changed the name of the class in the snippet to match the class name in the text.

Fixes #20773

### CODE REVIEW

**Comment by TheEskhaton** [comment]
I've obviously overlooked that `MainClass` and `MainClass4` were in the same namespace.

Would it be a good solution to change the namespace of the class, or alternatively, change the class name to something else entirely in both the text and snippet, like `Program`?

**Comment by IEvangelist** [comment]
Hi @TheEskhaton - Yes, I'd suggest *Program* if that is available in this example snippet without conflict. Thank you very much!

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=22227) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=22227) before we can accept your contribution.<br/><br/>:x: TheEskhaton [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=22227)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=22227) it.</sub>

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏

**Pull request merged**
