### PR TITLE
Update for Debian Bookworm

### LINKED ISSUE #36309: Debian Bookwarm not mentioned
Subj, but wget downloads the repository installing package if I replace 11 with 12. Refresh needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by dandev486**
## Summary

Adds installation instructions for Debian Bookworm.

Fixes #36309

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/5cc49d9b5127cf045efe1d8c5bd06cf3ecbbf426/docs/core/install/linux-debian.md) | [Install the .NET SDK or the .NET Runtime on Debian](https://review.learn.microsoft.com/en-us/dotnet/core/install/linux-debian?branch=pr-en-us-36569) |

### CODE REVIEW

**Comment by adegeo** [comment]
Thanks @dandev486 

@rbhanda @leecow Do you know the answer to the question?

**Comment by leecow** [comment]
I don't know that we have a dependency on a specific version so much as it just needs to be there. We do check for specific versions (see [here](https://github.com/dotnet/runtime/blob/bc43b7ece88885d4f0246c73313c5e19864e15db/src/installer/pkg/sfx/installers/dotnet-runtime-deps/dotnet-runtime-deps-debian.proj#L9)) to ensure it's installed. @NikolaMilosavljevic  for any additional clarification.

**Comment by adegeo** [comment]
@leecow If I understand you, and that file reference correctly, you're saying that as long as any `libicu` referenced in that file is installed, including 52, it's OK?

**Comment by leecow** [comment]
Yes, that's my understanding.

**Comment by adegeo** [comment]
@dandev486 OK looking at the package repository for bookworm it seems 72 is the lowest version available, so I think it's safe to say that's the requirement.

**Review by adegeo — APPROVED** [review]

**Pull request merged**
