### PR TITLE
Update the section on resilience and static clients

### PR DESCRIPTION
**Pull request by IEvangelist**
Reverts dotnet/docs#39073

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/fundamentals/networking/http/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/406a897a25551d8b647ee68227690ab03ddd03e5/docs/fundamentals/networking/http/httpclient-guidelines.md) | [Guidelines for using HttpClient](https://review.learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines?branch=pr-en-us-39105) |

### CODE REVIEW

**Review by martintmk — APPROVED** [review]

**Review by CarnaViire — APPROVED** [review]
Thanks

**Review by BillWagner — APPROVED** [review]
Hi @IEvangelist 

This LGTM. Let's :shipit:

**Comment by martintmk** [comment]
Just FYI, the change to expose `ResilienceHandler` didn't make it into `8.0.1`. So we'll need to wait for `8.0.2`.

**Comment by martintmk** [comment]
@IEvangelist The 8.2.0 is out, so this is mergeable 👍 

https://www.nuget.org/packages/Microsoft.Extensions.Http.Resilience/8.2.0

**Review by martintmk — APPROVED** [review]

**Pull request merged**
