### PR TITLE
Updating .NET Microservices Architecture for Containerized .NET Applications eBook

### PR DESCRIPTION
**Pull request by ardalis**
## Summary

Making updates reflecting current guidance.

### CODE REVIEW

**Comment by ardalis** [comment]
@nishanil review please when you have a moment.

**Comment by mairaw** [comment]
Can you resolve the conflicts @ardalis?

**Comment by nishanil** [comment]
@ardalis the file that has merge conflict should be dropped from this PR. The file was already updated as part of ASP.NET book update.

**Comment by ardalis** [comment]
Review and should be good.

**Review by nishanil — APPROVED** [review]
Reviewed the messaging. It looks good.

**Comment by ardalis** [comment]
Should be ready to merge @nishanil

**Pull request merged**
