### PR TITLE
Move P/Invokes to NativeMethods class

### PR DESCRIPTION
**Pull request by nxtn**
Contributes to #11396 

In .NET Framework Guide.

[CA1060: Move P/Invokes to NativeMethods class](https://docs.microsoft.com/visualstudio/code-quality/ca1060-move-p-invokes-to-nativemethods-class)

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
I apologize that I've allowed this PR to languish, @NextTurn. I've made a few additional changes in the VB code -- I've eliminated unnecessary Import statements, and I found that the Static keyword is not valid in a Declare statement, so I've removed them. I'll merge now.

**Comment by NextTurn** [comment]
`System` namespace is for `IntPtr`.

**Comment by rpetrusha** [comment]
The System namespace only needs to be imported in VB code in early versions of the .NET Framework; it's imported automatically starting in .NET Framework 2.0.

**Comment by NextTurn** [comment]
It seems that `Microsoft.VisualBasic` is also automatically imported? I can't find the information in docs. Shall we remove these Imports statements in other snippets?

**Comment by rpetrusha** [comment]
Yes, @NextTurn, both System and Microsoft.VisualBasic are automatically imported, so the `Imports` statements for them (and actually should be) removed.

**Pull request merged**
