### PR TITLE
initial core install mgmnt content

### PR DESCRIPTION
**Pull request by leecow**
## Summary

Content describing when it is appropriate to remove previous versions of the SDK and Runtime.

### CODE REVIEW

**Comment by BillWagner** [comment]
@mairaw @leecow I finished editing this.  It's ready for a final review.

**Comment by BillWagner** [comment]
Well, this is no longer WIP, but I can't remove that message without doing more changes. (force push after a rebase -i says that nothing has changed, so no push needed)

@mairaw After reviewing this, we can :shipit:

**Comment by leecow** [comment]
LGTM. Thanks, Bill.

**Review by mairaw — APPROVED** [review]
LGTM

**Pull request merged**
