### PR TITLE
Fixing rendering issue - take 3

### PR DESCRIPTION
**Pull request by stevehoag**
Content previously reviewed - trying again starting with last known good
set of changes

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047)  
  Please see 27 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/basetypes/quickref.md). Referenced by file: docs/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201825217123-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047)  
  Please see 27 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/customnumeric.md)...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201849037872-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047)  
  Please see 27 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/customnumeric.md)...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201907181711-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/alternation?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/anchors?branch=pr-en-us-1047)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047](https://review.docs.microsoft.com/en-us/dotnet/articles/basetypes/backreference?branch=pr-en-us-1047)  
  Please see 27 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/index.md)...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201923235112-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/quickref.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201939487434-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/quickref.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609202006443729-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/quickref.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609202030082670-1047%5Cworkflow_report.html).

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/basetypes/quickref.md). Referenced by file: docs/standard/basetypes/alternation.md at line: 327...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609202050486140-1047%5Cworkflow_report.html).

**Comment by stevehoag** [comment]
Still failing after failed Win Samples CI build

**Pull request closed without merging**
