### PR TITLE
Update architecture landing page

### PR DESCRIPTION
**Pull request by gewarren**
Contributes to #17502.

Internal preview URL: https://review.docs.microsoft.com/en-us/dotnet/architecture/?branch=pr-en-us-17503

I didn't do a straight lift-and-shift to the new YAML format. The [guidance](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-landing-page?branch=master#landing-page-template) says not to duplicate the TOC, for one thing. Also, cards are supposed to start with a verb, and I didn't think the differentiation of e-book vs. preview e-book is really that important to the reader. I thought grouping by concept was more useful.

### CODE REVIEW

**Comment by gewarren** [comment]
Should this ebook also be part of these docs?

https://dotnet.microsoft.com/learn/desktop/architecture#ebook-modernizing-existing-desktop-apps-swimlane

**Review by Thraka — APPROVED** [review]
Just FYI there is an update to an article that isn't landing page/toc related. Don't know if it snuck in or not.

**Comment by gewarren** [comment]
> Just FYI there is an update to an article that isn't landing page/toc related. Don't know if it snuck in or not.

Thanks, that was intentional. I link to that article from the landing page.

**Comment by gewarren** [comment]
@nishanil Does the new landing page look okay to you? We are required by senior leadership to change the format of landing pages to this new "card" style. But I also rearranged the links, so I want to make sure the new arrangement is okay.

**Comment by nishanil** [comment]
> @mairaw Should this e-book also be part of these docs?
> 
> https://dotnet.microsoft.com/learn/desktop/architecture#ebook-modernizing-existing-desktop-apps-swimlane

Yes, it needs to be part of docs. Olia has some PRs that we will merge when it is ready.

**Comment by nishanil** [comment]
Yes, I have a few suggestions on the cards:
-  Can we replace "Concept" to "Guidance" or a similar text in all cards? 
-  Rename `Develop .NET apps for Azure` to `Develop Cloud-Native .NET apps for Azure` and add Microservices books and the learn module there instead of another section `Develop Microservices-based apps`
- `Migrate your .NET web app or service to Azure App Service` is linked twice in two different cards
- Can we also link this page `https://dotnet.microsoft.com/apps/cloud/migrate-to-azure` in the Migrate card? There are other resources on that page that will be helpful for customers.
- Currently, two books are in preview - shouldn't those be explicitly called in the title for e.g. `Architecting cloud-native .NET apps for Azure (Preview)` ?

**Comment by gewarren** [comment]
@nishanil Thanks for reviewing.

> Can we replace "Concept" to "Guidance" or a similar text in all cards?
"Guidance" is not one of the options, unfortunately. I think "concept" fits best of the available list types: https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-landing-page?branch=master#linklisttype

**Comment by mairaw** [comment]
You can finish this work @gewarren and we'll add the new desktop e-book to this page after this PR is merged. We have a release branch for that work right now: https://github.com/dotnet/docs/tree/desktop-ebook

**Pull request merged**
