### PR TITLE
Move .NET Standard to 'Concepts'

### PR DESCRIPTION
**Pull request by richlander**
.NET Standard is a general concept, not specific to .NET Core.

### CODE REVIEW

**Comment by cartermp** [comment]
LGTM

**Comment by blackdwarf** [comment]
Please then move the folder with the content as well. Like this it seems wrong, since the URL will reflect the path on FS.

**Comment by richlander** [comment]
I don't understand.

**Comment by blackdwarf** [comment]
@richlander nvm you did that already, I got confused in the diff view. :(

**Pull request merged**
