### PR TITLE
Replace "Windows Communication Foundation (WCF)" token with plain text, part 4

### PR DESCRIPTION
**Pull request by ErlendLandro**
For #4801 

Replaces tokens in the `docs/framework/wcf/feature-details` directory

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks for the continued work here @Mackiovello 

One comment (mostly for Ron to keep track of): This PR does not remove the include file.

This is ready to merge. 

/cc @rpetrusha

**Comment by Mackiovello** [comment]
I will make the remaining changes in another PR. The remaining instances are scattered across a number of directories, so it would be easier to merge these four existing PRs first and then I'll create another PR with the remaining changes and delete the file. That also means that we will not have any merge conflicts.

**Comment by rpetrusha** [comment]
That sounds like a good way to proceed, @Mackiovello. Thanks.

**Comment by rpetrusha** [comment]
Thanks, @Mackiovello, for these 4 PRs. I've merged the first three, and will merge this one now.

**Pull request merged**
