### PR TITLE
System.Numerics: mention that vectors are rows

### LINKED ISSUE #4356: System.Numerics needs clarification that points/vectors are treated as rows
@geoeo in the #4345 PR has raised an issue that current documentation of [System.Numerics](https://docs.microsoft.com/en-us/dotnet/api/system.numerics?view=netcore-2.0) namespace doesn't say if an individual point/vector is treated as a row or as a column. 

That knowledge is essential when we want to chain two non-commutative transformations. Let's say two transformations are defined by matrices `M1` and `M2`. If a vector `v` is a row, then it's transformed by `v * M1 * M2`. If `v` is a column, then it's transformed by `M2 * M1 * v`. So to get combined transformation matrix, `M1 * M2` or `M2 * M1`, we need to know if vectors are rows or columns.

`System.Numerics` treats vectors as rows. I suggest to make the common remarks paragraph that might be placed to Matrix4x4, Matrix3x2, Vector[234] struct descriptions. 

@BillWagner if that sounds as a good plan, I'm willing to realize it. In meantime, we agreed with @geoeo that PR #4345 might be closed.

### PR DESCRIPTION
**Pull request by pkulikov**
Added remark that vectors are treated as rows at the `System.Numerics` namespace.

Fixes #4356 

## Suggested Reviewers
@mairaw @rpetrusha 
@geoeo as you've noticed the issue, please review as well. I've placed the clarifying paragraph at the **Remarks** section of each geometry-related struct page.

### CODE REVIEW

**Review by geoeo — CHANGES_REQUESTED** [review]
I think its a little too convoluted. For me, what I was looking for is simply stating that a vector and matrix are multiplied by v*M.( Instead of the more common M*v)

I would change this to:

The `System.Numerics` namespace represents vectors as rows for vector-matrix multiplication. Transforming a vector v by a matrix M is done by v*M

**Comment by pkulikov** [comment]
@geoeo thank you for feedback, I've simplified the sentence.

**Comment by geoeo** [comment]
Sorry I have one more nitpick: I think it should be mentioned that it only applies when doing geometric transformations. After that I think it will be clear.

> The `System.Numerics` namespace represents vectors as rows for vector-matrix multiplication, so the product of a vector *v* and a matrix *M* is *vM*.

> The `System.Numerics` namespace represents vectors as rows for 2D/3D/4D vector-matrix multiplication, so the product of a vector *v* and a matrix *M* is *vM*.

**Comment by pkulikov** [comment]
@geoeo I think that's a good point given the generic type `Vector<T>` in the same name space.

**Comment by pkulikov** [comment]
@geoeo I've made one more refinement.

**Review by BillWagner — APPROVED** [review]
Thanks for this update @pkulikov It looks good.

I'll approve the PR now.  @rpetrusha Do you want to review as well? If not, you can :shipit:.

**Review by rpetrusha — APPROVED** [review]
LGTM as well. Thanks, @pkulikov, for submitting yet another PR, and @geoeo for your work on this issue. I'll merge; the changes should go live on docs.microsoft.com in the next day or two.

**Pull request merged**
