### PR TITLE
Comparisons and Sorts

### PR DESCRIPTION
**Pull request by stevehoag**
Fixed missing title

### CODE REVIEW

**Comment by mairaw** [comment]
Snippet code formatting seems to have issues

**Comment by stevehoag** [comment]
Any idea what is wrong here? I simply cut and pasted the code block from MSDN and added triple quotes before and after. Is there a different/better way to do this?

**Comment by cartermp** [comment]
@stevehoag you may have to manually format.  Markdown is pretty WYSIWYG, so it could be that some formatting on the MSDN page could not be preserved.  You should also mark the triple back-quote with `csharp` as such:

```
```csharp
```

Both GitHub and docfx can apply styles that way.

I copy source into VS Code and view the document with the Markdown viewer (`ctrl-shift-v`), as the formatting for source will be identical on docfx and GitHub.

**Comment by stevehoag** [comment]
I figured out the code formatting issue. VS Code uses straight apostrophes ('), GitHub is expecting backticks (`) to mark code. I don't see any way to configure this in VS Code - maybe inserting the ASCII code?

**Pull request closed without merging**
