### PR TITLE
Add `--duration` doc for dotnet-trace fixes #32088

### LINKED ISSUE #32088: dotnet-trace docs do not mention the `--duration` parameter
dotnet-trace docs never mention the `--duration` parameter, which exists and is very useful

for instance, you can use it like this:

```
dotnet-trace collect -p 123 --duration 00:00:00:05
```

The above command will run the trace for 5 sconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57216dad-d87d-eeef-adc8-82bfe4251343
* Version Independent ID: 3e7ab61f-5a06-b92c-5c74-0fae43adb35e
* Content: [dotnet-trace diagnostic tool - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace)
* Content Source: [docs/core/diagnostics/dotnet-trace.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/dotnet-trace.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

### PR DESCRIPTION
**Pull request by alex-jitbit**
## Summary

Adds the missing `--duration` command option description

Fixes #32088

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
Looks good, except --duration should be added in the Synopsis section also.

**Comment by BillWagner** [comment]
@alex-jitbit 

Can you make the one change requested? Then, we'll merge this.

**Comment by alex-jitbit** [comment]
@BillWagner Added. But are you sure that option works with other? I have teste with `collect` only. If you are - then fine

**Review by BillWagner — APPROVED** [review]
This now LGTM.

I'll :shipit: when the build finishies.

**Comment by BillWagner** [comment]
> @BillWagner Added. But are you sure this option works with other commands too? I have tested it with `collect` only. If you are - then fine

It does only apply for the `collect` subcommand. Rather than the opening paragraph, we meant the *synoposis* location. I made the edit, and I'll :shipit: now.

**Pull request merged**
