### PR TITLE
Add note on suppressing trimming warnings

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Inspired by the suppression justification from https://github.com/dotnet/linker/pull/2891.

Cc @vitek-karas @sbomer @tlakollo @eerhardt

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]
Thanks a lot!

I'm still terrible at thinking about trimming the right way - I think what the linker does today, not what it "Should do" in theory.

**Comment by MichalStrehovsky** [comment]
> I'm still terrible at thinking about trimming the right way - I think what the linker does today, not what it "Should do" in theory.

The more aggressive constant propagation in .NET 7 already puts the IL linker into these territories today. It doesn't kick in often, but when it does, statically used properties and methods get removed.

**Review by eerhardt — APPROVED** [review]

**Review by sbomer — APPROVED** [review]
Thank you!

**Comment by MichalStrehovsky** [comment]
@adegeo is this okay to merge?

**Review by IEvangelist — APPROVED** [review]

**Pull request merged**
