### PR TITLE
Create CS8964

### PR DESCRIPTION
**Pull request by Rageking8**
## Summary

Create new undocumented `CS`-coded error page.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/csharp/language-reference/compiler-messages/cs8964.md](https://github.com/dotnet/docs/blob/266379059f92eea26a52f0c6639272c930f7aca3/docs/csharp/language-reference/compiler-messages/cs8964.md) | [Compiler Error CS8964](https://review.learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs8964?branch=pr-en-us-37291) |

### CODE REVIEW

**Comment by BillWagner** [comment]
Hi @Rageking8 

The content looks great, but before we merge this, a new link needs to get added to the local TOC for compiler messages. Can you add a node here: https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/toc.yml#L1902-L1903

Then, it's ready.

**Comment by Rageking8** [comment]
@BillWagner I presume you meant add a new entry directly below where you highlighted, hopefully that is correct. If not, do let me know and I will fix it ASAP. Thanks again for the swift review.

(also did a slight nit fix)

**Review by BillWagner — APPROVED** [review]
This looks great @Rageking8 

I'll :shipit: now.

**Comment by Rageking8** [comment]
@BillWagner Sorry just wanted to clarify something, AFAICT C8964 is a compiler error so should it still be in the compiler warning level 4 section (in `toc.yml`)(and not the compiler error section)? Not too sure about the procedure here, thanks.

**Comment by BillWagner** [comment]
> @BillWagner Sorry just wanted to clarify something, AFAICT C8964 is a compiler error so should it still be in the compiler warning level 4 section (in `toc.yml`)(and not the compiler error section)? Not too sure about the procedure here, thanks.

That's my bad. Yes, it should be in the error section. 

I can make a quick PR, or you can, and I'll merge it before we publish overnight.

**Comment by Rageking8** [comment]
> > @BillWagner Sorry just wanted to clarify something, AFAICT C8964 is a compiler error so should it still be in the compiler warning level 4 section (in `toc.yml`)(and not the compiler error section)? Not too sure about the procedure here, thanks.
> 
> That's my bad. Yes, it should be in the error section. 
> 
> I can make a quick PR, or you can, and I'll merge it before we publish overnight.
> 

I would not be able to post a fix before the cutoff, would appreciate if you can do the PR. Thanks!

**Comment by BillWagner** [comment]
I got it. Thanks.

**Pull request merged**
