### PR TITLE
Update how-to-determine-which-versions-are-installed.md

### LINKED ISSUE #18684: .NET Framework 4.8 Windows 10 2004 Release Key
The documentation currently gives `528209` as the value of the release key for the Windows 10 May 2020 Update.  This does not match with the release key in the actual release which is `528372`.

win10
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

### PR DESCRIPTION
**Pull request by nnpcYvIVl**
Closes #18684

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
Looks good to me, :shipit: when you're ready.

**Comment by gewarren** [comment]
@nakarnam Is this PR correct? Thanks!

**Comment by nakarnam** [comment]
yes its correct.

**Comment by gewarren** [comment]
@nnpcYvIVl and @nakarnam Thank you!

**Pull request merged**
