### PR TITLE
fix image names

### PR DESCRIPTION
**Pull request by spaette**
corrected for renamed .png files

docs/architecture/containerized-lifecycle/Microsoft-platform-tools-containerized-apps/index.md
docs/architecture/containerized-lifecycle/what-is-docker.md

renamed files

docs/architecture/containerized-lifecycle/Microsoft-platform-tools-containerized-apps/media/index
microsoft-tools-contanerized-docker-app.png -> microsoft-tools-containerized-docker-app.png

docs/architecture/containerized-lifecycle/media/what-is-docker
comparison-vms-docker-conatiners.png -> comparison-vms-docker-containers.png

#### Internal previews

| 📄 File(s) | 🔗 Preview link(s) |
|:--|:--|
| _docs/architecture/containerized-lifecycle/Microsoft-platform-tools-containerized-apps/index.md_ | [Preview: docs/architecture/containerized-lifecycle/Microsoft-platform-tools-containerized-apps/index](https://review.learn.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/Microsoft-platform-tools-containerized-apps/index?branch=pr-en-us-33864) |
| _docs/architecture/containerized-lifecycle/what-is-docker.md_ | [Preview: docs/architecture/containerized-lifecycle/what-is-docker](https://review.learn.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/what-is-docker?branch=pr-en-us-33864) |

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=33864) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=33864) before we can accept your contribution.<br/><br/>:x: spaette [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=33864)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=33864) it.</sub>

**Comment by spaette** [comment]
@BillWagner 

I don't know who has write authority to merge PRs for this repo.

**Comment by spaette** [comment]
@nishanil 

Might you approve running the workflows?

**Comment by spaette** [comment]
@IEvangelist 

Can this be reviewed and possibly merged?

**Review by IEvangelist — APPROVED** [review]

**Comment by spaette** [comment]
@IEvangelist 

_cf_: https://github.com/dotnet/docs/pull/33864#issuecomment-1417915835

All CLA requirements met.

However https://github.com/dotnet/docs/pull/33864#issuecomment-1466076389 appears to request that the CLA be completed a second time.

**Comment by IEvangelist** [comment]
Hi @spaette - you have to comment with your approval in order to agree.

**Comment by spaette** [comment]
@dotnet-policy-service agree

**Comment by spaette** [comment]
> comment with your approval

Done, though duplicate licence/cla checks seems unnecessary.

FWIW, 2nd licence/cla check's Details link points to a bad page.

**Comment by spaette** [comment]
@IEvangelist 

Apologies for my query, but are merges generally put in a queue for msftbot or would a Member manually merge?

**Comment by IEvangelist** [comment]
> @IEvangelist
> 
> Apologies for my query, but are merges generally put in a queue for msftbot or would a Member manually merge?

Members have to approve and merge.

**Pull request merged**
