### PR TITLE
Update direct-client-to-microservice-communication-versus-the-API-Gat…

### PR DESCRIPTION
**Pull request by allanchua101**
…eway-pattern.md

Included an on-going tutorial series that focuses on building API Gateways and all the benefits that you get out of it. The series got a total of 15k views in a month.

## Summary

Describe your changes here.

Added ASP.net Core API Gateway Building Tutorial Series with 5+ (continuously growing article series) 

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by CESARDELATORRE — APPROVED** [review]
I approve to add this reference. It is related to the same approaches and specific technologies (Ocelot) for the API Gateway pattern, so it can help as hands-on material.

**Review by BillWagner — APPROVED** [review]
Approving per @CESARDELATORRE 

I'll :shipit: now.

You should see the changes on the live site in the next day or two, on our regular publishing cycle.

**Comment by allanchua101** [comment]
OMG, I’m so happy about this, I’m really glad to share material to the dotnet community. Let me know how can I help around the docs guys thanks!!

**Comment by mairaw** [comment]
Thank you so much @allanchua101. If you're interested in helping out, look at the [up-for-grabs issues](https://github.com/dotnet/docs/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs) or the more organized view at our community project: https://github.com/dotnet/docs/projects/35 and see if there's anything that interests you.

**Comment by allanchua101** [comment]
@mairaw, I’ll definitely give the issue list a look tommorow ^_^ thanks guys

**Pull request merged**
