### PR TITLE
Add item to stop using APTCA

### PR DESCRIPTION
**Pull request by blowdart**
And changed tense

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
How can I not approve a PR with these commit messages?

:shipit: 🥇 

Thanks @blowdart

**Comment by mairaw** [comment]
Wanted to change the ms.date on this topic, so gave an editing pass on this. One question though @blowdart, is that opening paragraph correct?

**Comment by blowdart** [comment]
Yea it's correct enough without dipping into the weeds

**Review by mairaw — APPROVED** [review]
Thank you @blowdart! We'll merge as soon as my changes finish building.

**Pull request merged**
