### PR TITLE
migrate msdn topics

### PR DESCRIPTION
**Pull request by ryanmajidi**
migrate missed topics with mdoc issues from msdn to docs.

Needs placed in TOC

### CODE REVIEW

**Comment by ryanmajidi** [comment]
@mairaw Where do you want to put these topics in the toc?

**Comment by mairaw** [comment]
It would be similar to the changes I've done here:
https://github.com/dotnet/docs/pull/15035/files#diff-0a52fb18728469ccaf66774fe38d8f98

They are in alphabetical order: first by namespace, class, then member

**Comment by Youssef1313** [comment]
There are some empty code snippets, and some metadata that I believe they're not used in the current system.

**Comment by mairaw** [comment]
Yes @Youssef1313, I'll clear those up before merging. Thank you!

**Comment by ryanmajidi** [comment]
@mairaw Can you please review the toc?

**Comment by mairaw** [comment]
Thanks @ryanmajidi. I'll make some changes soon so we can merge this.

**Review by mairaw — APPROVED** [review]
I'll merge as soon as builds look good.

**Pull request merged**
