### PR TITLE
.NET 6 dotnet new updates

### PR DESCRIPTION
**Pull request by vlada-shubina**
## Summary

Updates for .NET 6 for `dotnet new`.
https://github.com/dotnet/templating/issues/3203

- `dotnet new`: new `--no-update-check` option
- `--uninstall` now allows relative path - removed notes 
- `--list` and `--search` now allow more natural argument order: `dotnet new --list me`
- various updates to tutorials and articles

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
Looks great, I left mostly grammar comments.

**Review by DavidKarlas — APPROVED** [review]
I agree that we should only show `dotnet new --search text` examples.

**Review by bekir-ozturk — CHANGES_REQUESTED** [review]

**Review by bekir-ozturk — APPROVED** [review]

**Comment by bekir-ozturk** [comment]
Hey @tdykstra,
 Was this good to merge or should we have kept it for release day?
 Should we revert?

**Comment by tdykstra** [comment]
If the functionality documented is in RC2, no need to revert.

**Pull request merged**
