### PR TITLE
Freshness try catch

### PR DESCRIPTION
**Pull request by msebolt**
Freshness update, code sample tested, only wording and Acrolinx changes.  

Work done per task at https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1409985/.

### CODE REVIEW

**Comment by msebolt** [comment]
@mairaw @rpetrusha For review/merge status updates.

**Comment by msebolt** [comment]
See corresponding code refresh at https://github.com/dotnet/samples/pull/627.

**Comment by msebolt** [comment]
Also, one of the code review requirements was to run stand-alone without any need of additional files, though I found the sample text file needed in this example simple enough to be outside this scope.  Please let me know if this is not the case.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks for revising this, @msebolt. I've left a number of comments and suggestions.

**Comment by msebolt** [comment]
@rpetrusha Thank you for the suggestions.  All changes made.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
Thanks for making the additional round of changes, @msebolt. I'll merge your PR now.

**Review by rpetrusha — APPROVED** [review]

**Pull request merged**
