### PR TITLE
Use action verbs

### PR DESCRIPTION
**Pull request by nxtn**
https://github.com/dotnet/docs/pull/10466#pullrequestreview-204496774

Is there an issue to track these?

/cc @rpetrusha

### CODE REVIEW

**Comment by rpetrusha** [comment]
No, there's not an issue to track it, @NextTurn.

**Comment by NextTurn** [comment]
Is this PR ready to merge?

**Comment by rpetrusha** [comment]
Thanks for making these changes, @NextTurn, and especially for changing the titles in cross-references to the Get Started topics. Your PR is tagged as a draft. Is it ready to merge? If it is, I'll approve it and merge it.

**Comment by NextTurn** [comment]
The "Ready for review" button is missing. I've no idea what to do.

**Comment by rpetrusha** [comment]
I have a "Ready for review" button. Shall I merge?

**Comment by NextTurn** [comment]
Thanks. Please merge it then.

**Review by rpetrusha — APPROVED** [review]
Thanks, @NextTurn. I'll merge now.

**Pull request merged**
