### PR TITLE
SEOImages: User Story 1463880, Part 9

### PR DESCRIPTION
**Pull request by damabe**
## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

Contributes to #10839

### CODE REVIEW

**Comment by damabe** [comment]
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031400003/Report/

**Comment by damabe** [comment]
@mairaw Sorry...didn't finish typing before I sent...

There is one warning that I wanted to ask you about. It is caused because I changed an image name that is referenced in another article. I changed the reference in that article but had to revert it because it caused another 15 or so failures in that article. Would you prefer I leave the warning as is and correct it (with the additional failures that it will cause) in my next PR? Or change them all here? I ask because it will cause the number of file changes to nearly double and don't want to make the PR unreasonable.

**Comment by mairaw** [comment]
If you create another PR with the changes, I can mark this one in a way that we merge both together. Definitely keeping the number small and reasonable is easier for me.

**Comment by damabe** [comment]
I'll do that one next. Thanks!

**Review by mairaw — APPROVED** [review]
I've resolved the merge conflicts and it looks great. Thanks @damabe!

**Pull request merged**
