### PR TITLE
Remove noise words from filename and update navigation

### PR DESCRIPTION
**Pull request by mvelosop**
## Summary

Remove noise words from filename and update navigation

I thought I had done this but it was not in master after merging, so here I go "again".

I might have lost the "context" while reviewing the definitely too large previous PR 😔

### CODE REVIEW

**Comment by mairaw** [comment]
No worries @mvelosop. Given that those changes were now pushed live, should we just keep as-is?

**Comment by mvelosop** [comment]
Now that it's done, I'd go on to remove the noise words @mairaw, but as you decide is just fine 😉

**Review by mairaw — APPROVED** [review]
Sounds good. Since it's new content, probably there's not a lot of people already linking to the new page. Otherwise, we'd have to set up redirection. That's why this kind of changes I prefer to tackle within the same PR.

**Comment by mvelosop** [comment]
@mairaw, I'm not sure how to handle this!

I tried solving the merge conflict in my laptop and it's just a file renaming, without conflicts.

Does the conflict have something to do with a restriction to renaming because of what you said?

**Comment by mvelosop** [comment]
Or... perhaps we just let it be!

**Comment by mairaw** [comment]
Let's leave as is. Closing this one.

**Pull request closed without merging**
