### PR TITLE
Add link to github issue to TLS doc

### PR DESCRIPTION
**Pull request by Rick-Anderson**
@mairaw

### CODE REVIEW

**Comment by mairaw** [comment]
Build has failed. Trying again.

**Review by mairaw — APPROVED** [review]
LGTM

**Comment by svick** [comment]
What's the point of adding this for this one article? And won't this become obsolete once the feedback system is migrated from Livefyre to GitHub issues anyway?

**Comment by mairaw** [comment]
We'll remove it in the future @svick. Just because of the nature of this change, we wanna make sure folks can easily find a way to ask questions.

**Pull request merged**
