### PR TITLE
Fix Bug 976235 : [LSI]Link to enum fields were incorrectly migrated.

### LINKED ISSUE #1932: Link that should be to an enum field is to the enum instead
It seems that during API reference migration, some links to enum fields were changed to links to the enum type itself.

For example, compare the documentation for `MethodBase.Invoke(Object, Object[])` [on MSDN](https://msdn.microsoft.com/en-us/library/a89hcwhh(v=vs.110).aspx#Remarks), which talks about the `BindingFlags.Default` field as "Default":

While [docs.ms](https://docs.microsoft.com/en-us/dotnet/api/System.Reflection.MethodBase.Invoke?view=netframework-4.7#System_Reflection_MethodBase_Invoke_System_Object_System_Object___) talks about "BindingFlags" instead:

This is an issue with [the source](https://github.com/dotnet/docs/blob/17edc15/xml/System.Reflection/MethodBase.xml#L654), it does not contain any mention of `Default`.

The same issue happens again on the page with `ReflectionPermissionFlag`. Though `BindingFlags.Default` in parameters of the `MethodBase.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)` overload is fine.

### PR DESCRIPTION
**Pull request by yishengjin1413**
Fixes #1932

### CODE REVIEW

**Review by mairaw — APPROVED** [review]

**Comment by mairaw** [comment]
We'll wait for CI to finish to merge this. Thanks @yishengjin1413!

@rpetrusha is there any topic that comes to mind that you'd like to double check that it was included in this PR? You mentioned we should mention String.Empty several times in our docs. Can you please merge this once it finishes building and builds look good?

**Comment by rpetrusha** [comment]
@yishengjin1413, although this PR fixes the link targets, the link text remains confusing, since it now shows the enumeration field name but not the enumeration type. So, for example, it's unclear what `Null` refers to. Can you modify the enumeration fields to include `displayProperty=fullName`?

**Comment by yishengjin1413** [comment]
@rpetrusha, do you mean modify all the enumeration filelds to include ```displayProperty=fullName```?

In caps, the topic did not show the fullname, please see ```Whitespace``` in this [page](https://msdn.microsoft.com/en-US/library/mt693101(VS.140).aspx). So would you give me some rules on how to determine whether to use fullname for the enumeration field? Since I can't get this logic from CAPS.

**Comment by rpetrusha** [comment]
@yishengjin1413, I'm sorry that I wasn't more clear. Yes, that's what I meant.

**Comment by mairaw** [comment]
Given that these links are not rendered with full names on MSDN (see for example https://msdn.microsoft.com/en-us/library/hh367887(v=vs.110).aspx and search for CurrentPage), I think the migration work done here is correct (see [diff](https://github.com/TerryTry1/docs/commit/c0a40af0bced7d83e3b734e40894b810f1f141cb#diff-105e85270d6a1c75bd92391edef310f7))
Unless I'm missing something @rpetrusha? Do you just want to add `displayProperty=fullName` to all field links independently of how they looked on msdn before?

It would be important to get this PR merged.

**Comment by rpetrusha** [comment]
Yes, @mairaw, that's precisely what I wanted to do -- regardless of how enumeration names appeared on MSDN, use displayProperty=fullName for each enumeration members. This is always clearer, in many cases removes ambiguity (as in the `Null` I mentioned earlier and in hundreds of other cases), and saves customers from having to follow the link to find out what enumeration the enumeration member belongs to. I can't think of a single down side to having displayProperty=fullName.

**Comment by mairaw** [comment]
Sounds good @rpetrusha. Can you do this change for us then and also add `?displayProperty=fullName`  to all the field values you're fixing @yishengjin1413?

**Review by mairaw — APPROVED** [review]
I've resolved the merge conflicts. I think we should merge this once build finishes.

**Pull request merged**
