### PR TITLE
Fixed spelling

### PR DESCRIPTION
**Pull request by sabahshariq**
## Summary

Fixed spelling in the sentence.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
Thanks @ThePiranha. The change itself looks good but this PR has so many commits that are not related to this change. Given how simple it is, it should only have one commit. Do you wanna try to clean this?

**Comment by mairaw** [comment]
And please let me know if you need any help figuring out how to do this. One option would be for you to reset --hard your local fork with upstream and then do the new commit and git push -f.

**Comment by ThePiranha** [comment]
Yes Maira that would be great. I trying to clean up this. Okay let me try the solution you provided.

**Comment by mairaw** [comment]
@ThePiranha When working with git locally, this is usually my process for starting new work (variations on this method are possible of course):

1. Follow the steps to have a local clone, including setting up upstream as indicated [here](https://docs.microsoft.com/en-us/contribute/get-started-setup-local)
2. git status (to make sure that are no unstaged changes)
3. git checkout master
4. git fetch upstream
5. git rebase upstream/master
6. git checkout -b working-branch-name

Then for the rest of the workflow, I use VS Code since we have some nice extensions for it:
https://docs.microsoft.com/en-us/contribute/get-started-setup-tools#visual-studio-code

For quick edits, I just use the GitHub UI: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

I hope this helps! And thanks for contributing!

**Comment by ThePiranha** [comment]
> @ThePiranha When working with git locally, this is usually my process for starting new work (variations on this method are possible of course):
> 
> 1. Follow the steps to have a local clone, including setting up upstream as indicated [here](https://docs.microsoft.com/en-us/contribute/get-started-setup-local)
> 2. git status (to make sure that are no unstaged changes)
> 3. git checkout master
> 4. git fetch upstream
> 5. git rebase upstream/master
> 6. git push
> 7. git checkout -b working-branch-name
> 
> Then for the rest of the workflow, I use VS Code since we have some nice extensions for it:
> https://docs.microsoft.com/en-us/contribute/get-started-setup-tools#visual-studio-code
> 
> For quick edits, I just use the GitHub UI: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
> 
> I hope this helps! And thanks for contributing!

Thanks @mairaw I will follow the steps.

**Pull request closed without merging**
