### PR TITLE
What's new in .NET 8 Preview 1

### LINKED ISSUE #33830: Create a What's new in .NET 8 Preview 1 page
See https://github.com/dotnet/core/issues/8133.

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #33830 

[Preview](https://review.learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8?branch=pr-en-us-33844)

### CODE REVIEW

**Comment by gewarren** [comment]
@JonDouglas Here's a skeleton for the What's new in .NET 8 docs page.

https://review.learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8?branch=pr-en-us-33844

**Comment by gewarren** [comment]
@BillWagner Can you publish this on Tuesday 2/21 please?

**Comment by JonDouglas** [comment]
Thank you so much everyone!

**Comment by jongalloway** [comment]
There are broken links in release blog posts, can we get this merged and published?

**Review by BillWagner — APPROVED** [review]
LGTM

**Pull request merged**
