### PR TITLE
[WIP] Remove references to MSDN where applicable #2037

### PR DESCRIPTION
**Pull request by isaacrlevin**
#2037 

Removing references to MSDN   (below are sections complete)

* docs\csharp\language-reference

### CODE REVIEW

**Comment by isaac2004** [comment]
@mairaw here is a running PR... If you want it done a different way, let me know

**Comment by mairaw** [comment]
Thank you @isaac2004!  My only comment so far is that we avoid using absolute URLs for our links (one of the reasons is that otherwise, links in the offline books for VS won't work). 
One easy way to do this is to change the `https://docs.microsoft.com/dotnet` part of the link with `~/docs` and add the .md extension.

**Comment by isaac2004** [comment]
@mairaw sounds good I can change those

**Comment by mairaw** [comment]
Build seems stuck. Closing and reopening the PR.

**Comment by mairaw** [comment]
@isaac2004 I just resolved some merge conflicts that were flagged in the PR. You can see how I change the links in those topics.

**Comment by mairaw** [comment]
@isaac2004 I'd love to merge this. Do you want to address the feedback or do you want me to finish this PR for you? I'm fine either way.

**Comment by isaac2004** [comment]
@mairaw it is a big one, I am done with that one section in the OP. There are 100s of files left to scub

**Review by mairaw — APPROVED** [review]
I think this is ready to merge now. Thanks @isaac2004. I'll push these changes live tomorrow.

**Pull request merged**
