### PR TITLE
Document dotnet restore --runtime

### PR DESCRIPTION
**Pull request by Thealexbarney**
Adds documentation for the `runtime` option in the `dotnet-restore` command.

Feedback on the language used would be appreciated. I included a reason to use this option, so the description is relatively long.

### CODE REVIEW

**Comment by GuardRex** [comment]
Hi @Thealexbarney -- *Thanks for catching this!* :+1: We have a major update to the commands landing soon, and I'll roll this into that PR.

**Comment by GuardRex** [comment]
@Thealexbarney Were going to try to squeeze this in there ... and :pray: server gods :pray: hopefully don't hit us with a merge conflict! :grinning:

It needs a quick spot of work tho. Can you refactor a bit more along the lines of ...

> Specifies a runtime for the package restore. This is used to restore packages for runtimes not explicitly listed in the `<RuntimeIdentifiers>` tag in the *.csproj* file. For a list of Runtime Identifiers (RIDs), see the [RID catalog](../rid-catalog.md). Provide multiple RIDs by specifying this option multiple times.

We want to have sentences that don't end in a preposition ("for"). The file extension should be italics (surrounded by \* with the dot). The "you can use" phrase is non-essential. You have a double-space in there before the last sentence. The last sentence can be refactored to go from a state verb ("be") to an action verb ("provide"). As you can tell, we're going for *grammatastic*:tm: (*new word!* lol) docs as much as we can.

Patch it up in a commit and we'll take it with *many THANKS!* :+1:

**Comment by Thealexbarney** [comment]
I've updated the PR with the new language

**Review by guardrex — APPROVED** [review]

**Comment by GuardRex** [comment]
Thanks @Thealexbarney!

**Pull request merged**
