### PR TITLE
revising the Data folder name formatting

### PR DESCRIPTION
**Pull request by JRAlexander**
To be consistent, changing the Data Folder name formatting from quotes to italics.

### CODE REVIEW

**Comment by pkulikov** [comment]
@JRAlexander other two tutorials should be updated with the same change as well for consistency.

**Comment by JRAlexander** [comment]
@pkulikov, Absolutely. I am planning to do that as soon as I confer about this formatting change. Trying to solve a localization issue. Thanks!

**Comment by mairaw** [comment]
I believe that when we're talking about input strings on VS, we use quotes. Let's check!

**Comment by mairaw** [comment]
I believe the conclusion we came up is that we won't change the style for those. Should we close this @JRAlexander?

**Comment by JRAlexander** [comment]
Decided to leave as is. Closing.

**Pull request closed without merging**
