### PR TITLE
Update Enumeration code in Microservices ebook

### PR DESCRIPTION
**Pull request by svick**
Contributes to https://github.com/dotnet/docs/issues/6812.

This resolves points 1 and 2 of https://github.com/dotnet/docs/issues/6812, synchronizes the code with dotnet-architecture/eShopOnContainers (see https://github.com/dotnet-architecture/eShopOnContainers/pull/704) and makes few other small improvements.

### CODE REVIEW

**Comment by pkulikov** [comment]
@svick, just FYI, this PR and #6209 might be related

**Comment by BillWagner** [comment]
I'll wait to merge this until dotnet-architecture/eShopOnContainers#704 is merged.

ping @CESARDELATORRE

**Comment by mairaw** [comment]
@CESARDELATORRE ping

**Comment by mairaw** [comment]
@svick do you want to take a look at the merge conflicts?

**Comment by svick** [comment]
@mairaw I have resolved the merge conflicts.

**Comment by CESARDELATORRE** [comment]
This PR in docs is related to a PR in eShopOnContainers which is still not reviewed/approved:
https://github.com/dotnet-architecture/eShopOnContainers/pull/704

This PR will need to wait until the code PR in eShopOnContainers is reviewed/approved, ok?
We'll be working on reviewing many PRs during the upcoming weeks.
Thanks,

**Comment by BillWagner** [comment]
@CESARDELATORRE @mvelosop Can you look at this and related PR dotnet-architecture/eShopOnContainers#704

Thanks

**Comment by mvelosop** [comment]
Hi @BillWagner, I'll take a look at this.

**Comment by mvelosop** [comment]
Hi @BillWagner, I left some comments in PR https://github.com/dotnet-architecture/eShopOnContainers/pull/704

**Pull request closed without merging**
