### PR TITLE
remove two articles

### LINKED ISSUE #16745: "Build .NET Core from source" article is outdated
The `dotnet/cli` repository has moved. I'm not sure if only changing the link will solve the issue. The instructions to build might have some changes.

The same applies to the first heading ("Build the CLR from source"), the repository link has been updated to the new `dotnet/runtime`, but I'm not sure if the instructions to build has changed or not.

I also think the article should have a heading "Build libraries from source". The `dotnet/runtime` repository has now the CLR and the libraries. Current layout has "Build the CLR" but not "Build libraries".
cc: @jkotas 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b95543-2043-fa28-08f1-54fceeec1301
* Version Independent ID: 945584fb-faa9-140d-c193-69ea9c646b51
* Content: [Build .NET Core from source - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/build/#build-the-cli-from-source)
* Content Source: [docs/core/build/index.md](https://github.com/dotnet/docs/blob/master/docs/core/build/index.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #16745 

What I did:
- removed https://docs.microsoft.com/en-us/dotnet/core/build/ with no redirect
- redirected distribution-packaging to the root of core. Couldn't find a better placement for this one with the removal of the other article.
- removed https://docs.microsoft.com/en-us/dotnet/project-json given it's been a few years now that we've shipped .NET Core with no redirect

Let me know what you think!

### CODE REVIEW

**Comment by mairaw** [comment]
@richlander added you in case you have any thoughts on the removal of those articles

**Comment by Youssef1313** [comment]
@mairaw, Why not add a redirect to the dotnet/runtime repo instructions ?

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
A relative link is broken in *distribution-packing.md* after it was renamed. It should be fixed

**Review by BillWagner — APPROVED** [review]
This LGTM @mairaw 

Once you address the one new warning, you can :shipit:

**Review by jkotas — APPROVED** [review]

**Pull request merged**
