### PR TITLE
removed library from netstandard

### PR DESCRIPTION
**Pull request by mairaw**
I've missed a couple of .NET Standard Library instances on PR #2198. Trying to fix that now.

@BillWagner please review the topics that are part of the micro-services book. I wasn't sure if that part is talking about libraries in general or not, so for now, just changed the case.

@GuardRex for this one, since you already have the latest VS for Mac installed, can you make sure its UI is still calling that entry .NET Standard Library? if it is, we should probably file an issue for that.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
I checked all the changes, and this is a great step for consistency.  LTGM. @mairaw You can merge it when you are ready.

**Comment by GuardRex** [comment]
@mairaw The UI screenshots I have in *docs/docs/core/tutorials/using-on-mac-vs-full-solution.md* reflect the release version. I'll double-check the UI this morning and open the issue with them on Bugzilla (and one for us to track in our doc issues linked to it).

**Comment by GuardRex** [comment]
@mairaw v7.0.1 (build 24), yes, it's there. Will this be called a ".NET Core Library" now?

mac1

mac2

**Comment by mairaw** [comment]
Interesting @GuardRex. The terminology is not consistent with traditional VS where those are called Class Library. You do have both: .NET Core Class Library and .NET Standard Class Library. I'll merge this then.

**Pull request merged**
