### PR TITLE
Converted absolute URLs to API syntax

### PR DESCRIPTION
**Pull request by mairaw**
My attempt on fixing the build warnings for this topic.

/cc @bradygaster

### CODE REVIEW

**Comment by mairaw** [comment]
Builds are only complaining about the only I didn't change because I didn't know the right uid.

**Comment by bradygaster** [comment]
@mairaw @richlander you guys think this is ready to merge?

**Comment by richlander** [comment]
@bradygaster I think that @mairaw was looking for some advice from you and others on whether this change was a good direction. I have no such advice to give, one way or the other.

**Comment by mairaw** [comment]
I'll merge and test this. The only one who was on the thread with @chenkennt about this change was @bradygaster, that's why I cc'd him. :smile:

**Pull request merged**
