### PR TITLE
Update VS refs in MDA topics

### PR DESCRIPTION
**Pull request by gewarren**
Lots of whitespace removal - recommend viewing diff in CodeFlow.

[Preview URL](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fdotnet%2Fframework%2Fdebug-trace-profile%2Fdiagnosing-errors-with-managed-debugging-assistants%3Fbranch%3Dpr-en-us-7034&data=02%7C01%7C%7C2a9fe5ec809849d63afc08d602ee4107%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636699619641487735&sdata=80Vn8epIkm9SxokAKykTTozvxS2s12ZTIaMXETDc5yI%3D&reserved=0)

Contributes to  #6923 and #7172

### CODE REVIEW

**Comment by gewarren** [comment]
https://review.docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/contextswitchdeadlock-mda?branch=pr-en-us-7034
https://review.docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/diagnosing-errors-with-managed-debugging-assistants?branch=pr-en-us-7034
https://review.docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/pinvokestackimbalance-mda?branch=pr-en-us-7034

**Comment by BillWagner** [comment]
I requested @mairaw review this. I think everything looks good, but I wasn't certain about a few styles.  Namely:

- Should numbers like `0` be code fenced?
- Should MDA names be code fenced, or otherwise highlighted for loc?

**Comment by mairaw** [comment]
Even though I'm set as the owner of this I don't have much knowledge about MDA. I'd keep MDA names such as virtualCERCall code fenced. 
I think we don't need to code fence the numbers.

**Review by mairaw — APPROVED** [review]
LGTM. Thanks @gewarren!

**Comment by gewarren** [comment]
@mairaw Thank you!

**Pull request merged**
