### PR TITLE
eShopOnWeb eBook 2.1 Updates [WIP]

### PR DESCRIPTION
**Pull request by ardalis**
A PR to manage updates to the https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/ ebook

### CODE REVIEW

**Comment by BillWagner** [comment]
@ardalis This PR got caught in some infrastructure work for #4789  We split the docs repo into three, then rewrote history to trim its size.

I've found the easiest way to recover work is to create a patch from the existing branch, create a new clean fork and apply that patch.

@mairaw or I will publish detailed instructions later today.

**Comment by mairaw** [comment]
I just fixed this now @BillWagner and @ardalis. @terrajobst showed me an even easier way to get those fixed, so I'll do that myself on other busted PRs.

**Comment by mairaw** [comment]
I saw that you opened a new one @ardalis. Should I close this one then?

You had to reset --hard your local branch with my updates to get the fix.

**Comment by ardalis** [comment]
Yes, please.

**Pull request closed without merging**
