### PR TITLE
:clipboard: standard metadata updates

### PR DESCRIPTION
**Pull request by mairaw**
Related to #5062

We should merge #5099 first and then see how that with these changes combined look like. But wanted to keep that global change on a separate PR.

### CODE REVIEW

**Comment by pkulikov** [comment]
@mairaw sometimes I've seen `ms.assetid` being removed from the metadata as well. Whenever I touch metadata, should I keep it or might be removed as well? For example, in #5057 it's removed, but not here.

**Comment by mairaw** [comment]
Good question @pkulikov. I've been removing them from content that was created directly on Docs like Core or F#. But I'm keeping that metadata for folders that contain migrated content since that's the key to find the topic in our old system. We should be able to remove them entirely once we address all migration issues. /cc @rpetrusha @BillWagner

**Comment by pkulikov** [comment]
@mairaw thank you for the answer, that's clear. So, it's kind of pre-history for those docs in C# and standard folders.

**Review by rpetrusha — APPROVED** [review]
I've just spot-checked a random assortment of files, and everything seemed to be good, @mairaw. You can merge this when you're ready.

**Pull request merged**
