### PR TITLE
Remove table, as it confuses customers

### PR DESCRIPTION
**Pull request by gkaleta**
Please remove this chart as it confused customers more than it helps. Also it is not up to date if you decide to keep it.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by IEvangelist** [comment]
Hmmm, I'm not actually sure. @nishanil this is for you to decide, I think that @DavidCBerry13 recently added similar content to the .NET Azure area. What do you both think about consolidating / updating?

**Comment by masnider** [comment]
+1  Since the table leaves out so much detail (and several products) we have also seen it confuse and disappoint customers.

One example, which caused a disruption with a critical partner (Accenture) https://github.com/dotnet/docs/issues/15055

A PR I raised to address that feedback was rejected: https://github.com/dotnet/docs/pull/21258

**Comment by DavidCBerry13** [comment]
I'm good with removing the table.  I think the intent was good but the info has become dated and confusing for people.

**Comment by IEvangelist** [comment]
Hey, @nishanil and @CamSoper -- please chime in here, what do you think?

**Comment by CamSoper** [comment]
Yeah this is done to death elsewhere, and with pictures. Let's kill the table.

**Review by IEvangelist — APPROVED** [review]

**Comment by masnider** [comment]
Thanks everyone!

**Pull request merged**
