### PR TITLE
Update dotnet-6.md

### PR DESCRIPTION
**Pull request by alexsolntsev**
We have published an article that can help popularize .NET updates. To prove our relevance and reliability, I would like to refer to the Shopping Cart page of ASP.NET documentation, where nopCommerce have been presented as an example: https://docs.microsoft.com/en-us/aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/shopping-cart#summary 

Also, read testimonials from Microsoft MVPs of nopCommerce: https://www.nopcommerce.com/why-for-developers-testimonials

## Summary

We have added a sentence with a link to the article about effectiveness measures of .NET 6 integration into nopCommerce, eCommerce platform.

### CODE REVIEW

**Comment by alexsolntsev** [comment]
Hi @adegeo,

Do you need some more information from us?

**Comment by alexsolntsev** [comment]
Hi,

I have noticed that my PR is in Milestone June 2022 but the milestone is closed. Will it be reviewed?

**Comment by adegeo** [comment]
Hi @alexsolntsev sorry, I've not been doing well with my github notifications!

I'm not sure this link is really needed, considering it's listing a few features that were performance improved and then links to a more in-depth blog post by the .NET team about all of the features that were improved.

I usually see this type of link on the marketing page or something specific to upgrading, like with what was done on the ASP.NET page.

@richlander what do you think?

**Comment by richlander** [comment]
Sorry, but we cannot accept this. We haven't even linked to our own blog posts here (which might be a good idea).  We also don't accept content (actual content or links) that might be motivated by a desire to advertise from our content.

**Pull request closed without merging**
