### PR TITLE
Remove or fix TODO Snippet references.

### PR DESCRIPTION
**Pull request by tompratt-AQ**
# Title
Remove or fix TODO Snippet references in XML branch.

## Summary
This is the six batch of fixes for missing code snippets in the XML branch as part of the ["TODO: Review snippet reference" Task](https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22TODO%3A+review+snippet+reference%22&type=).

It includes the following:

1. Removed TODO snippet links for topics that did not have an example in VS2010.
2. Removed the ##Examples header when there was no intro for the example.
3. Fixed references to XAML snippets, or deleted references to files that were moved.
4. Deleted a duplicate .cs snippet file.

## Suggested Reviewers
@mairaw

### CODE REVIEW

**Comment by tompratt-AQ** [comment]
The second commit "Fix final TODO snippets that are not aspx or ascx." removes the TODO snippet links from these 3 files:

1. xml/System.Security/NamedPermissionSet.xml  (NO code examples in VS 2010)
2. xml/System.ServiceModel.Activities/WorkflowServiceHost.xml  (Only the ctor example matches this class, the others linked to the wrong class and the TODO links don't exist now or in VS2010.)
3. xml/System.Web.UI/ScriptResourceAttribute.xml (The TODO .js snippet links are duplicates of what is already there.)

After this PR (2138),  [PR 2131](https://github.com/dotnet/docs/pull/2131) and [PR 2128 ](https://github.com/dotnet/docs/pull/2128) are merged, the remaining TODO code snippets all link to .aspx and .ascx files. Once [Issue 982841](https://mseng.visualstudio.com/VSChina/_workitems?id=982841) is closed and aspx snippets can resolve correctly, then the remainder of our [Migration Task: TODO Review Snippet Reference](https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22TODO%3A+review+snippet+reference%22&type=) can be resolved.

**Review by rpetrusha — APPROVED** [review]
LGTM.

**Comment by rpetrusha** [comment]
Is this ready to merge, @tompratt-AQ?

**Comment by tompratt-AQ** [comment]
@rpetrusha  Yes it is. You've approved the changes. Thanks.

**Pull request merged**
