### PR TITLE
Update and rename bc32051.md to bc36645.md

### LINKED ISSUE #14765: Example for compiler error BC32051 does not generate BC32051
## Example for compiler error BC32051 does not generate BC32051

The example for [BC32051](https://docs.microsoft.com/dotnet/visual-basic/misc/bc32051) generates BC36645 rather than BC32051.

The source code is:

```
Public Sub DoSomething(Of T)(arg1 As T(), arg2 As T)
End Sub

Public Sub Main()
    DoSomething(6, 42)
End Sub
```
The compiler output is:

> c:\Visual Studio Projects\bc32051\bc32051ex.vb(7) : error BC36645: Data type(s) of the type parameter(s) in method 'Public Sub DoSomething(Of T)(arg1 As T(), arg2 As T)' cannot be inferred from these arguments. Specifying the data type(s) explicitly might correct this error.
>
>   DoSomething(6, 42)
>   ~~~~~~~~~~~

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #14765

This PR may need a review from the compiler team to confirm that bc32051 doesn't exist

### CODE REVIEW

**Comment by KathleenDollard** [comment]
@jaredpar We have this PR in docs to update an error identifier. Can you confirm this is correct?

**Comment by BillWagner** [comment]
ping @jaredpar

**Review by jaredpar — APPROVED** [review]

**Comment by Youssef1313** [comment]
@BillWagner Anything left for this be merged?

**Comment by BillWagner** [comment]
Thanks for the ping @Youssef1313 

I'll :shipit: now.

**Pull request merged**
