### PR TITLE
ML tutorials: use Path.Combine to generate file paths

### LINKED ISSUE #5970: OS-Agnostic Paths
First:  GREAT tutorial.  This helped me immensely!

But, the paths are currently being built in a Windows-centric manner:

const string _datapath = @".\Data\taxi-fare-train.csv";
const string _testdatapath = @".\Data\taxi-fare-test.csv";
const string _modelpath = @".\Data\Model.zip";

As I worked through the tutorial, I coded them like this, so they work in Windows and Linux:

static string _datapath = Path.Combine(Environment.CurrentDirectory, "Data", "taxi-fare-train.csv");
static string _testdatapath = Path.Combine(Environment.CurrentDirectory, "Data", "taxi-fare-test.csv");
static string _modelpath = Path.Combine(Environment.CurrentDirectory, "Data", "Model.zip");

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York taxi fares (regression)](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

### PR DESCRIPTION
**Pull request by pkulikov**
Supported by dotnet/samples#130

Fixes #5970

### CODE REVIEW

**Review by JRAlexander — COMMENTED** [review]
Reviewing now. Samples first.

**Comment by pkulikov** [comment]
As samples are merged, let's trigger a new build.

**Comment by pkulikov** [comment]
@JRAlexander I've made changes after your last comment. so please, review them as well.

**Review by JRAlexander — APPROVED** [review]
LGTM. Thanks. @pkulikov, for your contribution! I'll merge this straightaway and you should see changes live within the next few days.

**Pull request merged**
