### PR TITLE
Add install instructions for CentOS 8

### LINKED ISSUE #18019: Add linux package manager install instructions for CentOS 8
.NET Core [is available on CentOS 8 AppStream](https://pkgs.org/download/dotnet-sdk-3.1). It seems like we should have a page for that, like we do [for RHEL 8](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-rhel8).

@leecow @rbhanda @dleeapho 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b603e29-5301-fcb8-d3e2-13db7ec842ed
* Version Independent ID: aa2f9276-c77a-5e60-a02b-d96cb511d8f9
* Content: [Install .NET Core on CentOS 7 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-centos7)
* Content Source: [docs/core/install/linux-package-manager-centos7.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-centos7.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by omajid**
This is basically the exact same set of instructions as RHEL 8, with the steps for registration and links to official RHEL docs removed.

Fixes: #18019

### CODE REVIEW

**Comment by Thraka** [comment]
Question, and this applies to RHEL 8 too really, what about installing Core 2.1 runtimes? Are those natively included in the distros? Core 2.1 is LTS.

**Comment by omajid** [comment]
> Question, and this applies to RHEL 8 too really

I copied the RHEL 8 page without thinking ...

> what about installing Core 2.1 runtimes? Are those natively included in the distros? Core 2.1 is LTS.

Yes, they are. RHEL 8 includes 2.1 (LTS, supported), 3.0 (out of support, but packages are available) and 3.1 (LTS, supported).

Shall I amend this PR to fix both docs?

**Comment by Thraka** [comment]
Sure. At this point though, I'm wondering if I should redesign this area to have all up distro pages that include instructions per version, instead of pages that are distro-version specific...

**Comment by omajid** [comment]
> Sure.

Okay, I will fix this PR, then.

> I'm wondering if I should redesign this area to have all up distro pages that include instructions per version, instead of pages that are distro-version specific...

Yeah, that may be a better approach, or it may be worse, hard to say without looking at it. If you have a prototype page, I will happily skim it and give you my feedback.

**Comment by Thraka** [comment]
Nothing yet. I am discussing changes to this area over at #17925

**Review by Thraka — APPROVED** [review]
Thanks!!!

**Pull request merged**
