### PR TITLE
Update live with current Master

### PR DESCRIPTION
**Pull request by BillWagner**
Because all the samples moved, this should go live quickly.

/cc @mairaw

### CODE REVIEW

**Comment by mairaw** [comment]
We got a build failure from the sample CI @BillWagner, @dend.  Can this be merged like that?

**Comment by BillWagner** [comment]
This is the problem I ran into yesterday. The build failure message says it's building on Windows 64. According to @dend that's not configured yet. It should be building on Ubuntu 64.

**Comment by mairaw** [comment]
Ah ok. So go ahead and merge. We're already getting LiveFyre comments about some broken links.

**Comment by dend** [comment]
Windows build failures can be ignored at this time.

**Pull request merged**
