### PR TITLE
Fixing up the primer

### PR DESCRIPTION
**Pull request by thesmithee**
Fix up the primer as explained in #334. Some of the main .NET items such as GC and the likes should become a part (in some way or form) of the new "What is .NET?" article. The primer is focusing on those points that are most usable to new users that are just exploring the platform.

/cc @mairaw @cartermp @richlander

---

This change is [Reviewable](https://reviewable.io/reviews/dotnet/core-docs/339)

### CODE REVIEW

**Comment by cartermp** [comment]
LGTM modulo minor feedback.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/concepts/primer.md, line 12 \[r1\]](https://reviewable.io:443/reviews/dotnet/core-docs/339#-KDZdjl4n81HYPTrhiWL:-KDZdjl4n81HYPTrhiWM:-1763354302) ([raw file](https://github.com/dotnet/core-docs/blob/8993370d857a9661dfbbbc6b1867a26b8ae0c793/docs/concepts/primer.md#L12)):*
I'd remove *salient*.  I don't know what that word means.

---

*[docs/concepts/primer.md, line 165 \[r1\]](https://reviewable.io:443/reviews/dotnet/core-docs/339#-KDZdLoO_UNRDI0AFkv4:-KDZdLoO_UNRDI0AFkv5:1356387049) ([raw file](https://github.com/dotnet/core-docs/blob/8993370d857a9661dfbbbc6b1867a26b8ae0c793/docs/concepts/primer.md#L165)):*
"It's" is incorrect here - "Its main goal is to allow [...]" may be better if it's reworded to avoid that kind of confusion, though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/core-docs/339#-:-KDZeB_kGu0KgewiODA-:1379386683)*

**Comment by mairaw** [comment]
Review done. Next time I'll try this reviewable site.

**Comment by blackdwarf** [comment]
@cartermp you don't know what salient means? :)

**Comment by cartermp** [comment]
@blackdwarf I still haven't looked it up yet, so I'm assuming it's related to salt.

**Comment by blackdwarf** [comment]
@cartermp nope, it means "important" essentially. https://www.bing.com/search?q=salient&form=EDGNTC&qs=PF&cvid=8a8e0a869bed49d78d1dabc1b7607b2c&pq=salient.

**Comment by mairaw** [comment]
I didn't see @cartermp's comment before about the salient term :smile: 
Notice I have given the same feedback so you should change it @blackdwarf LOL

**Comment by stevehoag** [comment]
You make a salient point :-)

**Comment by blackdwarf** [comment]
@stevehoag I'm a very salient person. :) I will change it, ok. :)

**Comment by cartermp** [comment]
@blackdwarf so would you say you're acting in a *solvent* manner?

**Comment by blackdwarf** [comment]
@cartermp on the contrary, I would say I like to *reify* stuff in general.

**Comment by cartermp** [comment]
LGTM

**Comment by blackdwarf** [comment]
OK, merging this in then. :)

**Pull request merged**
