### PR TITLE
Update toc.yml ("Blob storage", "File storage", and so on)

### PR DESCRIPTION
**Pull request by hyoshioka0128**
## Summary
Update toc.yml (Typo "Azure storage"→"Azure Storage")

https://github.com/dotnet/docs/blob/main/docs/fsharp/toc.yml
#PingMSFTDocs

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by BillWagner** [comment]
@gewarren I thought I saw a comment where you were tracking down the official product name here.

**Comment by gewarren** [comment]
> @gewarren I thought I saw a comment where you were tracking down the official product name here.

You are probably thinking of the related PR #31359. It looks like "Azure Files" is the official name, but this node seems to encompass more than that. I think it should be "Azure storage".

**Comment by pkulikov** [comment]
> I think the node should be "Azure storage".

Then what about the names of the items of this node? Now, they are "Blob Storage", "File Storage", etc., in all of them, the word "storage" is capitalized. Should it be sentence-cased?

**Comment by gewarren** [comment]
> Then what about the names of the items of this node? Now, they are "Blob Storage", "File Storage", etc., in all of them, the word "storage" is capitalized. Should it be sentence-cased?

Yes, that would be great, thanks!

**Comment by pkulikov** [comment]
@hyoshioka0128 as per discussion above, could you please revert your change and update the titles of the items of "Azure storage" to "Blob storage", "File storage", and so on?

**Comment by hyoshioka0128** [comment]
@pkulikov - Thanks!
　(1)revert
　(2)update the titles ("Blob storage", "File storage", and so on)
　
I'm poor English. Please let me know if I am wrong so I can correct it.

**Comment by pkulikov** [comment]
> (2)update the titles ("Blob storage", "File storage", and so on)

@hyoshioka0128 thanks! as for the point (2), I've meant those entries (they should be "Blob storage", "File storage"...):
image

**Comment by hyoshioka0128** [comment]
@pkulikov  - Thanks!
 Update "Blob Storage" →"Blob storage"

**Comment by pkulikov** [comment]
@hyoshioka0128 thanks!
@gewarren I think this is ready for review.

**Review by gewarren — APPROVED** [review]

**Pull request merged**
