### PR TITLE
Update build-aspnet-core-applications-linux-containers-aks-kubernetes.md

### LINKED ISSUE #11588: YAML containers spec spelling error
spec:
      containers:
        - mane:

"- mane" should be "- name"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 112420c9-17f7-eeb4-4418-001a7f8526c0
* Content: [Build ASP.NET Core 2.1 applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/master/docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by anichin**
Log in to the Azure Container Registry before trying to push the image.

Fixes #11588

### CODE REVIEW

**Comment by Thraka** [comment]
@CESARDELATORRE I think this is correct, do you want to review it?

@anichin Do you want to also fix #11588 ?

**Comment by Thraka** [comment]
@anichin Thanks! We'll wait for @CESARDELATORRE to just double check that he's OK with the login info. I don't see why not. Thanks again!

**Comment by anichin** [comment]
Sounds good. Thank you!

**Comment by Thraka** [comment]
@mvelosop Perhaps you can verify?

**Comment by mvelosop** [comment]
Hi @Thraka, @anichin,

LGTM, so you can merge when you're ready 😊

**Review by aanichin-markit — APPROVED** [review]
This should be good to merge

**Comment by aanichin-markit** [comment]
"At least 1 approving review is required by reviewers with write access" - I guess I do not have write access. Can someone else merge this?

**Comment by anichin** [comment]
This should be good to merge

**Review by Thraka — APPROVED** [review]

**Comment by Thraka** [comment]
@anichin thanks for this!

**Pull request merged**
