### PR TITLE
Updated examples to use the new parameter

### LINKED ISSUE #9935: Example uses the obsolete parameter. Please change it to the supported parameter.
So you say SharedRuntime is obsolete, but then in the Examples section you provide an example for the obsolete flag, but not its replacement???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by Kubik2000**
Fix  #9935

## Summary

Updated examples to use the new parameter

Fixes #9935

### CODE REVIEW

**Review by jzeferino — APPROVED** [review]

**Comment by Thraka** [comment]
@Kubik2000 Thanks a bunch for doing this! Since you have this open, could you also update references in the samples that use `-sharedruntime` and `--shared-runtime`? Also, near the top, line 33 is a paragraph that talks about shared runtime, can you change to say `-runtime` instead? These should be quick to fix.

Let me know if you can't or cannot do that. Thanks again!!

**Comment by Kubik2000** [comment]
@Thraka sure I will update those too

**Comment by Kubik2000** [comment]
@Thraka it will still be caled shared runtime and just the parameter will be new.
I have updated the one on line 33.
The rest of the shared runtime are just name not parameter.
The the samples that use -sharedruntime and --shared-runtime are already fixed, at least I did not found any more usages of the parameter in the repo.

**Comment by Thraka** [comment]
@Kubik2000 Cool, thanks a bunch!

**Review by Thraka — APPROVED** [review]

**Pull request merged**
