### PR TITLE
Added include, slightly simplified developer installation guide

### LINKED ISSUE #4318: Add clarity to .NET Framework installation for developers
# Add clarity to .NET Framework installation for developers

## General

The [Install the .NET Framework for Developers](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers) could benefit from some reformatting and in some cases rewriting to clarify existing content or make it more noticeable. 

See PR #2968. 

/cc @mairaw

### PR DESCRIPTION
**Pull request by rpetrusha**
## Added include, slightly simplified developer installation guide

Fixes #4318

### CODE REVIEW

**Review by mairaw — CHANGES_REQUESTED** [review]
LGTM but left some comments. See what you think.

**Comment by rpetrusha** [comment]
I've addressed your comments, @mairaw, if you'd like to take a look again.

**Review by mairaw — APPROVED** [review]
Looks great @rpetrusha! The only thing I'd add would be a red box on the new screenshot showing where the options are.

**Comment by mairaw** [comment]
Also, we could add an example of the error message you get if you don't have the targeting pack installed to help people troubleshoot:
"error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend."

**Comment by rpetrusha** [comment]
Great suggestions, @mairaw. I've addressed them, if you want to take a look. (In the meantime, I've marked this as **verify-build-before-merge**.

**Comment by mairaw** [comment]
I'm merging this now @rpetrusha.

**Pull request merged**
