### PR TITLE
Add MSBuild breaking changes

### LINKED ISSUE #24228: GetTargetFrameworkProperties and GetNearestTargetFramework have been removed
## GetTargetFrameworkProperties and GetNearestTargetFramework have been removed

The GetTargetFrameworkProperties target and GetNearestTargetFramework task have been removed from the .NET SDK

https://github.com/dotnet/sdk/issues/13519
https://github.com/dotnet/sdk/pull/15027/files
https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#targets-required-to-be-referenceable 

### Version introduced

.NET Core SDK 6.0.100-preview1

### Old behavior
GetTargetFrameworkProperties target and GetNearestTargetFramework task were not used but were still present.  Custom MSBuild logic could have taken a dependency on them.

### New behavior
This task and target have been removed.

### Reason for change
These were deprecated in MSBuild 15.5 and so are being removed in in .NET 6.

### Recommended action

Use GetTargetFrameworks instead.  See https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#targets-required-to-be-referenceable 

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [x] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [x] SDK
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs
"Not detectable via API analysis"

---
#### Issue metadata

* Issue type: breaking-change

### LINKED ISSUE #24229: Generating errors for duplicate files in publish output
## Generating errors for duplicate files in publish output

We added a new error (NETSDK1148) in cases where files from different source paths would be copied to the same file path in the publish output.  This can happen when a project and its project references include a file with the same name that is included in the publish output.

https://github.com/dotnet/sdk/issues/10850
https://github.com/dotnet/sdk/pull/14020

### Version introduced

6.0.100-preview1

### Old behavior
Both files would be copied to the same destination.  The second one would overwrite the first one, so which file "won" was mostly arbitrary.

In some cases, the build would fail, for example when trying to create a single-file app the bundler would fail with an ArgumentException:

>C:\Program Files\dotnet\sdk\5.0.100-preview.5.20258.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(962,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [C:\repro\repro.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.5.20258.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(962,5): error MSB4018: System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath [C:\repro\repro.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.5.20258.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(962,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\repro\repro.csproj]

### New behavior
We remove duplicate files copied to the publish folder if both the source and destination are the same.  If there are any remaining duplicates, we generate a NETSDK1148 error, listing the files which are duplicated.

### Reason for change
Duplicate files in the publish output were sometimes causing build breaks and in other situations causing unpredictable behavior.

### Recommended action
Ideally, projects should be updated to avoid situations where multiple files with the same name will be copied to the publish output.

Additionally, the following property can be set to suppress the check for duplicate files:
`<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>`

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [ x] SDK
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs
"Not detectable via API analysis"
---
#### Issue metadata

* Issue type: breaking-change

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #24228, fixes #24229.

- [Duplicate publish output files preview](https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output?branch=pr-en-us-24294)
- [GetTargetFrameworkProperties preview](https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/msbuild/6.0/gettargetframeworkproperties-and-getnearesttargetframework-removed?branch=pr-en-us-24294)

### CODE REVIEW

**Comment by dsplaisted** [comment]
@gewarren I just made some edits to the description of #24228

**Comment by dsplaisted** [comment]
I still need to make some edits to the duplicate publish output description.

**Comment by dsplaisted** [comment]
I've retitled and edited #24229, and asked some other folks to review it also.

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
