### PR TITLE
removed asp.net 5 references

### PR DESCRIPTION
**Pull request by mairaw**
/cc @BillWagner, not sure if this readme file is an auto-generated file or not.

### CODE REVIEW

**Comment by BillWagner** [comment]
@mairaw Yes, that readme.md is auto generated.  I'm fine with the changes you made, but I'm wondering what the standard of success is here long term: I can update the file be rerunning the generator, but I don't know if we want to do that on every update. What are your thoughts here?

**Comment by mairaw** [comment]
Good question @BillWagner. Let's discuss this. The only reason I've updated it is because I saw the old branding there. Not sure if you'd prefer to rerun the generator and see if you'd get a different result this time?

**Comment by svick** [comment]
Is the README even useful there?

If you create a new project in VS, it's nice that the created project points you to documentation.
But if you're following a tutorial in the documentation, you probably don't need to be pointed at the documentation again.

**Comment by BillWagner** [comment]
The readme.md itself is not useful in this sample. As @svick points out, anyone following along would generate their own copy with the current content.

I'm curious if others think there is merit in having the sample directory exactly match the final state for a reader following along. That would be the justification for re-running the generators and updating the generated files.

Thoughts? /cc @mairaw

**Comment by richlander** [comment]
LGTM

Looks like one of the https URLs got downgraded to http

**Comment by richlander** [comment]
Looks good. Will leave the remainder of the conversation to you.

**Comment by mairaw** [comment]
Good catch @richlander. I also noticed the link to the blog post wasn't working so I've fixed that.

@BillWagner, I'd think that if it's just an artifact that won't be needed it's more trouble than is worth to keep the readme. @Rick-Anderson, do you guys have any guidelines around that for the asp.net samples?

**Comment by BillWagner** [comment]
@mairaw I'd be fine removing the template generated readme. I'm making changes in the samples, so let's merge this, and I"ll address that file in those changes.

I'll make those changes once @Rick-Anderson weighs in.

**Comment by mairaw** [comment]
Sounds good @BillWagner!

**Pull request merged**
