### PR TITLE
Patch 3

### LINKED ISSUE #7770: Consufing terminology: syntax and format
The document uses the terms *syntax* and *format* in what I think is a confusing manner. It says:

&gt; The syntax depends on the data provider

and then

&gt; The format of a connection string is a semicolon-delimited list of key/value parameter pairs

I propose to:

1. avoid the term *format* altogether to prevent its confusion with *syntax* because the distinction is not obvious.

1. say that *all* connection strings share the same syntax, and

1. say that it is only the set of recognised keys (or keywords) that is specific to each provider.

I am willing to prepare a pull request with these modifications after issue #7628 is solved, to avoid a possible merging conflict.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ea979-365a-bfce-31ed-638781065bca
* Version Independent ID: 3672ed45-e05f-a292-16a0-9779254492be
* Content: [Connection Strings in ADO.NET](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings)
* Content Source: [docs/framework/data/adonet/connection-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

### PR DESCRIPTION
**Pull request by ant-222**
## Summary

1. Remove the mention of the term `format` and use the term `syntax` for the general structure of connection strings, because only parameter names (keywords) differ from provider to provider. Where`syntax` was used to mean the set of supported keywords, say so explicitly.

2. Correct the wrong statement that the connection string is parsed and analysed for errors during the opening of the connection, and supply instead a more detailed description of what is checked when.

3. Remove explicit reference to exceptions wrt. syntax checking because exceptions are the standard and default way of error handling throughout .NET.

4. Remove the duplicate statement about new features in ADO.NET 2.0 (per-provider connection-string builders) from the beginning of the document. It is still present at the end.

Fixes #7770 .

### CODE REVIEW

**Comment by douglaslMS** [comment]
@ant-222 Thank you for your careful review and revisions.

**Comment by douglaslMS** [comment]
@mairaw I would like to make some minor changes for style in the new text - for example, fix the passive voice. If it's OK, let's merge this PR first, and I'll take another look and submit a new PR later today.

**Comment by ant-222** [comment]
@mairaw Passive voice is often a prose smell (cf. [code smell](http://wiki.c2.com/?CodeSmell)), so I am looking forward to seeing your corrections. If you will be so kind as to make them in my branch so I can review them, I shall be most grateful. But feel free to apply them on top of my PR if you think it more convenient. Thanks to you and @douglaslMS for your help and collaboration.

**Review by douglaslMS — APPROVED** [review]

**Comment by douglaslMS** [comment]
@ant-222 I was only looking at a few small changes in style - for example, we try to use short sentences rather than dependent clauses. These are not only simpler to read, but they also make the pages easier to translate (that is, to localize). I may take a second look at the page after your updates are published.

**Comment by ant-222** [comment]
OK, thanks for merging, @douglaslMS .

**Pull request merged**
