### PR TITLE
System.EnterpriseServices

### PR DESCRIPTION
**Pull request by pappasa**
## Summary

System.EnterpriseServices is not supported in .NET Core

### CODE REVIEW

**Comment by rpetrusha** [comment]
@cartermp, could you take a look, especially since unmerged #9483 reorganizes the list of unavailable technologies into a separate page.

**Review by cartermp — APPROVED** [review]
Thanks @pappasa, can you sign the CLA?

**Comment by pkulikov** [comment]
@cartermp @pappasa it looks like original additions should be moved to this file:
https://github.com/dotnet/docs/blob/master/docs/core/porting/net-framework-tech-unavailable.md

**Review by mairaw — CHANGES_REQUESTED** [review]
You're right @pkulikov. The addition should be made on the file that Petr pointed out since this area of the docs got reorganized (https://github.com/dotnet/docs/blob/master/docs/core/porting/net-framework-tech-unavailable.md)

**Comment by BillWagner** [comment]
@pappasa Do you have time to move these changes to the file referenced above? If not, let us know and we'll move the content to the correct location.

**Comment by mairaw** [comment]
I've implemented the feedback comments and I'll merge this as soon as the build finishes successfully. Thanks for opening the PR @pappasa!

**Review by mairaw — APPROVED** [review]

**Pull request merged**
