### PR TITLE
add links to core getting-started tutorials

### PR DESCRIPTION
**Pull request by tdykstra**

### CODE REVIEW

**Comment by tdykstra** [comment]
/cc: @richlander added paragraph with tutorial links to about/index.md and standard/index.md

**Comment by richlander** [comment]
I'd liked your idea so much ... can you do the same with welcome.md, too?

**Comment by tdykstra** [comment]
@richlander done

**Comment by richlander** [comment]
Sweet. Thanks!

**Comment by mairaw** [comment]
Should we start using included for such cases?

**Comment by tdykstra** [comment]
@mairaw yes, do includes work with docs.ms.com, are relative links in an include relative to the include file location rather than the articles it's included in, and what's the syntax?

**Comment by mairaw** [comment]
I know they work, but haven't actually used them. The syntax looks like this:

```
[!INCLUDE[sample include file](./includes/sampleinclude.md)]
```

We can chat this week with the EMS team who has been doing this for longer and check how the relative links work with the includes.

**Pull request merged**
