### PR TITLE
update filter

### PR DESCRIPTION
**Pull request by mairaw**
an attempt to make the language filter to work

### CODE REVIEW

**Review by jzeferino — COMMENTED** [review]
This LGTM.

**Comment by jzeferino** [comment]
@mairaw  Something strange in my browser while opening [TimeZoneInfo.meta.md ](https://github.com/dotnet/docs/blob/1409bba8dc4e520603e2c8594847ad680a5f0446/add/metadata/System/TimeZoneInfo.meta.md):

screen shot 2017-12-01 at 11 34 51 pm

**Comment by mairaw** [comment]
That's probably because of the star there @jzeferino. Given this is used for build purposes only, it's probably not an issue.

**Comment by rpetrusha** [comment]
The language filter still doesn't work, @mairaw.

**Comment by mairaw** [comment]
Let me try a full build and see if that helps with anything. 😢 

/cc @TianqiZhang

**Comment by rpetrusha** [comment]
The full build didn't help, @mairaw. PowerShell still doesn't appear in the language filter.

**Comment by mairaw** [comment]
I know @rpetrusha. 😢 I'm following up with @TianqiZhang offline.

**Comment by mairaw** [comment]
Closing for now.

**Pull request closed without merging**
