### PR TITLE
Rename error messages

### PR DESCRIPTION
**Pull request by Youssef1313**
Contributes to #2363.

> 4. Improve the discoverability of Visual Basic error topics in both GitHub and on docs.microsoft.com by renaming the files to have only the Visual Basic error/warning number rather than the message string. This also requires that we create redirects for the 203 existing files in the language reference directory.

I've renamed 10 files only in this PR for easier review. ~~**I didn't made the redirects for those yet.**~~ Wanted to make sure if entries in *.openpublishing.redirection* are ordered in some specific way ?

### CODE REVIEW

**Comment by Thraka** [comment]
In general the * .openpublishing.redirection* is ordered alphabetically.

**Comment by rpetrusha** [comment]
This looks really good, @Youssef1313. Thank you so much for doing it. 

Once you add the redirects, we can merge. As @Thraka indicated, redirects should be in alphabetical order. 

Renaming just a handful of files (10-20 is a good number) in a single PR would be useful -- it enormously simplifies the review process.

**Comment by mairaw** [comment]
As I was about to reply, I noticed the last entry wasn't added in alphabetical order, so created PR #15071.

**Comment by Youssef1313** [comment]
GitHub shows merge conflicts that I can't see locally, and not allowing to resolve them using web interface. I'll try to fix it and add the redirections, if I couldn't I will open a new PR with the current changes and the redirection.

**Comment by Thraka** [comment]
Did you try to `pull --rebase` from master?

**Comment by mairaw** [comment]
I've rebased your PR @Youssef1313.

**Review by mairaw — CHANGES_REQUESTED** [review]
Now that is rebased, make sure you reset your local copy with what's on https://github.com/Youssef1313/docs/tree/rename-error-messages and add the missing redirects. Let me know if you need any help.

**Comment by Youssef1313** [comment]
@mairaw, Thanks for fixing the conflicts for me :)
I've updated the redirections.

**Review by mairaw — APPROVED** [review]
Thank you so much @Youssef1313!

**Pull request merged**
