### PR TITLE
Update blazor-long-polling-fallback.md

### LINKED ISSUE #26158: Client side configuration of long polling does not work
Cant enable Long Polling with the provided work around in rc1.

when i insert the client side code i get an error: 

```
Uncaught (in promise) Error: Blazor has already started.
    at Object.Kn [as start] (blazor.server.js:1)
    at start (localhost/:59)
    at localhost/:62
```

full _Layout.cshtml of the starting template:
```

@using Microsoft.AspNetCore.Components.Web
@namespace BlazorApp3.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="BlazorApp3.styles.css" rel="stylesheet" />
    <component type="typeof(HeadOutlet)" render-mode="Server" />
</head>
<body>
    @RenderBody()

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    
    <script src="_framework/blazor.server.js"></script>
    <script>
        (function start() {
            Blazor.start({
                configureSignalR: builder => builder.withUrl('_blazor', 1 | 4) // WebSockets and LongPolling
            });
        })()
    </script>
</body>
</html>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f41f72-9607-cf69-ba74-a13b0ba7c287
* Version Independent ID: ef609510-d010-8cd5-fbd6-b056fd5f1744
* Content: [Breaking change: Blazor server: Disable LongPolling fallback transport - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback)
* Content Source: [docs/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

### PR DESCRIPTION
**Pull request by TanayParikh**
## Summary

Update blazor long polling documentation

Fixes: https://github.com/dotnet/docs/issues/26158

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Approved with tiny nits.

**Comment by TanayParikh** [comment]
I've had multiple reports of users running into this issue, so I'm hoping to get this merged/visible ASAP. Once merged, how long would it take to propagate to the production site?

**Review by gewarren — APPROVED** [review]

**Comment by guardrex** [comment]
@TanayParikh ... Did  the `autostart` bit get left out of the Announcement my mistake?

https://github.com/aspnet/Announcements/issues/470

**Comment by gewarren** [comment]
> I've had multiple reports of users running into this issue, so I'm hoping to get this merged/visible ASAP. Once merged, how long would it take to propagate to the production site?

Normally we publish every weekday evening PST, but I can push it live straight away if you like.

**Comment by TanayParikh** [comment]
> Did the `autostart` bit get left out of the Announcement my mistake?

Yes it did, that's my bad, will fix. Thanks!

**Comment by TanayParikh** [comment]
> > I've had multiple reports of users running into this issue, so I'm hoping to get this merged/visible ASAP. Once merged, how long would it take to propagate to the production site?
> 
> Normally we publish every weekday evening PST, but I can push it live straight away if you like.

Yes please, that'd be greatly appreciated!

**Comment by guardrex** [comment]
Pinging u on that PR right now. 🏃

**Pull request merged**
