### PR TITLE
C98650: Fixing bookmark to avoid issues on localized pages

### PR DESCRIPTION
**Pull request by v-maudel**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: The lack of tags reference at the beginning of the line prevents bookmarks correct functionality. Kindly consider adding the proposed fixes in order to match bookmarks that are working.
@pkulikov

### CODE REVIEW

**Comment by pkulikov** [comment]
@v-maudel thanks! Could you please update the *bitwise-and-shift-operators.md* file as well: it has a similar H2 title as well.

**Comment by v-maudel** [comment]
@pkulikov , I just was fixing it as well :D 
https://github.com/dotnet/docs/pull/13013

**Comment by pkulikov** [comment]
> @pkulikov , I just was fixing it as well :D
> #13013

Thanks @v-maudel

**Review by rpetrusha — APPROVED** [review]
These changes look good, @v-maudel. I'll merge your PR now.

**Comment by v-maudel** [comment]
Thanks @rpetrusha @pkulikov

**Pull request merged**
