### PR TITLE
Br45 delete unused files

### PR DESCRIPTION
**Pull request by jameshkramer**
This PR is for user story #1576037.

The changes in the PR are as follows:

- Some additional VB files are deleted. Most of these files are VB parent node topics whose content was discarded rather than merged.
- There are new redirection entries for the newly-deleted files.
- Some redirection entries that existed prior to this project are modified to point to merged articles. Most of these are for C# parent node articles that were discarded when the C# section was modernized.
- Redirection entries are sorted to match the order of the articles in the new LINQ to XML section (the order in docs/standard/linq/toc.yml). I did this to make future support easier, and also to facilitate my checking of redirection entries. Unfortunately this makes a comparison to the prior version of the redirections file nearly useless.

I think it will be difficult to validate the changes by inspection, though I don't want to discourage trying. However I think testing is probably the best approach, and is needed in any case.

I will only be able to work four hours per week on this effort. 

cc: @BillWagner @mairaw @gewarren @tfosmark @marteeleigh

Contributes to #4728

### CODE REVIEW

**Comment by BillWagner** [comment]
I gave this a quick look this morning.

There are a number of build warnings for the redirections that should be addressed before we merge this.

**Comment by jameshkramer** [comment]
@BillWagner 

I corrected some things, but there are more fixes to come, so please don't review yet.

Jim

**Comment by BillWagner** [comment]
@jameshkramer You can convert this PR to "draft" status, which will let everyone know it's not ready yet. Then, when you are ready, convert it out of draft status and we'll review.

**Comment by jameshkramer** [comment]
@BillWagner 

Bill, thanks for the tip!

**Comment by jameshkramer** [comment]
@BillWagner @KathleenDollard @gewarren 

I've reviewed all the warnings about redirection targets appearing in multiple redirections. The cause for most of the duplication is the elimination of topics for TOC parent nodes. On the C# side, the elimination was done prior to this LINQ to XML conversion project. For Visual Basic, the elimination is being done in this project.

I believe everything is now as it should be. I've made no further changes since my push on 07-21. Let's proceed.

Thanks,

Jim

**Comment by gewarren** [comment]
@jameshkramer The warnings are appearing because `redirect_document_id` is set to true on more than one redirect. It can only be set to true on one redirect. For the others, you can either just remove the line or set it to false (which it defaults to if not specified).

```json
    {
      "source_path": "docs/csharp/programming-guide/concepts/linq/linq-to-xml.md",
      "redirect_url": "/dotnet/standard/linq/linq-xml-overview",
      "redirect_document_id": true
    },
    {
      "source_path": "docs/csharp/programming-guide/concepts/linq/linq-to-xml-programming-overview.md",
      "redirect_url": "/dotnet/standard/linq/linq-xml-overview",
      "redirect_document_id": true
    },
    {
      "source_path": "docs/csharp/programming-guide/concepts/linq/programming-guide-linq-to-xml.md",
      "redirect_url": "/dotnet/standard/linq/linq-xml-overview",
      "redirect_document_id": true
    },
    {
      "source_path": "docs/csharp/programming-guide/concepts/linq/getting-started-linq-to-xml.md",
      "redirect_url": "/dotnet/standard/linq/linq-xml-overview",
      "redirect_document_id": true
    },
    {
      "source_path": "docs/csharp/programming-guide/concepts/linq/linq-to-xml-overview.md",
      "redirect_url": "/dotnet/standard/linq/linq-xml-overview",
      "redirect_document_id": true
    },
```

**Comment by jameshkramer** [comment]
@gewarren 

Genevieve, yes, of course, thanks! I'll fix it.

Jim

**Comment by jameshkramer** [comment]
@BillWagner @KathleenDollard @gewarren

The warnings are gone, and I've reopened this PR for review.

Jim

**Review by gewarren — APPROVED** [review]
LGTM

**Comment by jameshkramer** [comment]
Before we review the current linq-to-xml, shouldn't we rebase it to the current master? Maira used to merge linq-to-xml and master, but I am willing to give it a try if requested--just let me know. Or I will go ahead and review linq-to-xml as is, if requested.

Thanks,

Jim

cc: @BillWagner @mairaw @gewarren @KathleenDollard @tfosmark @marteeleigh

**Pull request merged**
