### PR TITLE
Standardize sample projects, Part 21

### PR DESCRIPTION
**Pull request by nxtn**
What should we do with these warnings:

```
numericupdown.cs(241,51): warning CS0108: 'NumericUpDown.BackgroundProperty' hides inherited member 'Control.BackgroundProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(242,51): warning CS0108: 'NumericUpDown.BorderBrushProperty' hides inherited member 'Control.BorderBrushProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(243,51): warning CS0108: 'NumericUpDown.BorderThicknessProperty' hides inherited member 'Control.BorderThicknessProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(244,51): warning CS0108: 'NumericUpDown.FontFamilyProperty' hides inherited member 'Control.FontFamilyProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(245,51): warning CS0108: 'NumericUpDown.FontSizeProperty' hides inherited member 'Control.FontSizeProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(246,51): warning CS0108: 'NumericUpDown.FontStretchProperty' hides inherited member 'Control.FontStretchProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(247,51): warning CS0108: 'NumericUpDown.FontStyleProperty' hides inherited member 'Control.FontStyleProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(248,51): warning CS0108: 'NumericUpDown.FontWeightProperty' hides inherited member 'Control.FontWeightProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(249,51): warning CS0108: 'NumericUpDown.ForegroundProperty' hides inherited member 'Control.ForegroundProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(250,51): warning CS0108: 'NumericUpDown.HorizontalContentAlignmentProperty' hides inherited member 'Control.HorizontalContentAlignmentProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(251,51): warning CS0108: 'NumericUpDown.PaddingProperty' hides inherited member 'Control.PaddingProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(255,51): warning CS0108: 'NumericUpDown.VerticalContentAlignmentProperty' hides inherited member 'Control.VerticalContentAlignmentProperty'. Use the new keyword if hiding was intended.
numericupdown.cs(257,22): warning CS0108: 'NumericUpDown.Background' hides inherited member 'Control.Background'. Use the new keyword if hiding was intended.
numericupdown.cs(258,22): warning CS0108: 'NumericUpDown.BorderBrush' hides inherited member 'Control.BorderBrush'. Use the new keyword if hiding was intended.
numericupdown.cs(259,26): warning CS0108: 'NumericUpDown.BorderThickness' hides inherited member 'Control.BorderThickness'. Use the new keyword if hiding was intended.
numericupdown.cs(260,27): warning CS0108: 'NumericUpDown.FontFamily' hides inherited member 'Control.FontFamily'. Use the new keyword if hiding was intended.
numericupdown.cs(261,23): warning CS0108: 'NumericUpDown.FontSize' hides inherited member 'Control.FontSize'. Use the new keyword if hiding was intended.
numericupdown.cs(262,28): warning CS0108: 'NumericUpDown.FontStretch' hides inherited member 'Control.FontStretch'. Use the new keyword if hiding was intended.
numericupdown.cs(263,26): warning CS0108: 'NumericUpDown.FontStyle' hides inherited member 'Control.FontStyle'. Use the new keyword if hiding was intended.
numericupdown.cs(264,27): warning CS0108: 'NumericUpDown.FontWeight' hides inherited member 'Control.FontWeight'. Use the new keyword if hiding was intended.
numericupdown.cs(265,22): warning CS0108: 'NumericUpDown.Foreground' hides inherited member 'Control.Foreground'. Use the new keyword if hiding was intended.
numericupdown.cs(266,36): warning CS0108: 'NumericUpDown.HorizontalContentAlignment' hides inherited member 'Control.HorizontalContentAlignment'. Use the new keyword if hiding was intended.
numericupdown.cs(267,26): warning CS0108: 'NumericUpDown.Padding' hides inherited member 'Control.Padding'. Use the new keyword if hiding was intended.
numericupdown.cs(271,34): warning CS0108: 'NumericUpDown.VerticalContentAlignment' hides inherited member 'Control.VerticalContentAlignment'. Use the new keyword if hiding was intended.
```

### CODE REVIEW

**Comment by BillWagner** [comment]
I'll defer to @adegeo for the review.

**Comment by adegeo** [comment]
If its just warnings, it's fine.

**Review by adegeo — APPROVED** [review]

**Comment by adegeo** [comment]
@NextTurn Let's avoid WPF/WinForms updates right now, I'm working on migrating them to a new repo.

**Comment by NextTurn** [comment]
This is going to cause an inconsistency because I removed these duplicated properties in the corresponding VB project.

**Pull request merged**
