### PR TITLE
Getting Started with F# in Visual Studio Code with Ionide: add visual aid for an often missed step

### PR DESCRIPTION
**Pull request by carlpaten**
# Add visual aid for an often missed step

## Summary

This pull request updates an [existing article](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-vscode), clarifying what it means to "open Visual Studio Code in a new directory" with the help of a screenshot.

## Details

We're teaching an undergraduate functional programming class using F# and VS Code. We recommend students use this article to get up and running.

At least 10% of the students who followed this tutorial ran into the same problem. They didn't open a folder in VS Code before creating a new project, and as a result project creation succeeds but the project is nowhere to be found.

I'm going to try to add an error message to the Ionide plug-in for this condition. In the meanwhile, this pull request tries to remedy this by adding a screenshot that explains what to look for.

## Suggested Reviewers

@cartermp

### CODE REVIEW

**Comment by cartermp** [comment]
LGTM pending successful build and CLA.  Thanks, @lilred!

**Comment by lilred** [comment]
I'm not sure how to sign the CLA :0

**Comment by cartermp** [comment]
Hmmm, you should have received an email on your primary GitHub email.  If you don't see one, ping back here and we can get it sorted out.  It's a really simple process, but the web hook may not have triggered.

**Comment by lilred** [comment]
[One e-mail came in](imgur.com/2ywtao9), but it didn't look like it had anything to do with a CLA.

**Comment by cartermp** [comment]
Hmmm.  cc @martinwoodward - looks like the CLA bot didn't trigger, or it may not be set up on this repo?

Either way @lilred, you can access it here: https://cla.dotnetfoundation.org

Once it's been signed then I'll merge it.

**Comment by lilred** [comment]
I'm down to sign the CLA but which project should I pick in the dropdown?

**Comment by cartermp** [comment]
Since the dos isn't listed there, I'd just pick ".NET Core 5", since that's general enough.

**Comment by lilred** [comment]
Done!

**Comment by cartermp** [comment]
Awesome.  Thanks!  I've emailed the relevant folks to see if we can get the CLA stuff sorted out.

**Comment by lilred** [comment]
Thanks! Out of curiosity, when can I expect this change to be reflected on the Docs website? The README says "on a certain cadence", but that could be anything between hours and months.

**Comment by cartermp** [comment]
Generally in the next few days - we merge into the live branch within 1-5 days.

**Pull request merged**
