### PR TITLE
Converted msdn links to site-relative for offline scenarios

### PR DESCRIPTION
**Pull request by mikeblome**
This PR fixes up msdn shortid urls that were missed in earlier runs

### CODE REVIEW

**Review by mikeblome — COMMENTED** [review]
@mairaw @BillWagner  Link report showed 93, two above baseline of 91, and I attempted to fix one of those inline, so should just be one additional that I introduced possibly. I request that we accept anyway as a net plus in terms of correct links.

**Comment by mairaw** [comment]
Thanks so much for working on this @mikeblome. We'll review it as soon as possible!

**Review by mairaw — APPROVED** [review]
Thanks @mikeblome. I did a couple of fixes as well that might bring us back to 91. We'll wait for builds to finish before merging.

**Comment by mairaw** [comment]
Related to #2037

**Pull request merged**
