### PR TITLE
Dead link

### PR DESCRIPTION
**Pull request by user135711**
Closest possible link I found is [Programming with Application Domains and Assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/) but that's the head topic of the side bar which seems unnecessary to link to. Edit the link as desired.

### CODE REVIEW

**Comment by pkulikov** [comment]
The link to the older version (.NET Framework 4) works:
https://msdn.microsoft.com/en-us/library/bd36055b-56bd-43eb-b4d8-820c37172131(v=vs.100)

Should that one replace the broken one?

**Comment by mairaw** [comment]
Actually that topic seemed to be rolled into this one now:
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/application-domains#programming-with-application-domains

So you can link like this: "application-domains.md#programming-with-application-domains"

**Review by mairaw — APPROVED** [review]
Thank you @user135711. I'll fix the remaining ones. Your fix should go live within a day.

**Comment by mairaw** [comment]
Related to #2037

**Pull request merged**
