### PR TITLE
Added generation operator samples

### PR DESCRIPTION
**Pull request by matthewreily**
Added samples for #136 and and parent task #90 @BethMassi @cartermp

### CODE REVIEW

**Comment by matthewreily** [comment]
Good catch.  Should I go back and fix the other samples as well?

**Comment by BethMassi** [comment]
Probably should. @cartermp had a quick trigger finger on the last PR merge so I didn't get my comment in there in time :smile:

**Comment by matthewreily** [comment]
haha will do

**Comment by cartermp** [comment]
Whoops!

**Comment by matthewreily** [comment]
fixed and squashed previous commit

**Comment by BethMassi** [comment]
LGTM @matthewreily thanks again!

**Pull request merged**
