### PR TITLE
Remove dev_langs metadata

### LINKED ISSUE #2426: dev_langs metadata
While updating one topic today, I saw that we have jsharp as a dev_lang metadata value and lots of topics on winforms for example are missing other dev_langs. We should update it to remove jsharp and add the appropriate ones. Maybe we can even set those at a global level?

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #2426 

* Removes `dev_langs` from all repo topics.
* Adds global langs to *docfx.json*.

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Looks good on the surface. Let's see if it looks good after it's built.

**Comment by mairaw** [comment]
Language picker was no longer showing up for the topics so made some changes to docfx.json to see if it fixes.

**Comment by GuardRex** [comment]
@mairaw Works on the examples, e.g. ...

https://review.docs.microsoft.com/en-us/dotnet/api/system.appdomainsetup.applicationbase?branch=pr-en-us-2595&view=netframework-4.7

... but should these work on the declarations? ... I never thought to look before, and the DDL doesn't seem to change them.

**Comment by mairaw** [comment]
@GuardRex api content is already like this in production. and we don't have support for VB, F#  or C++ yet. I'm going to test how this looks for conceptual now.

**Comment by mairaw** [comment]
I think this will need a full rebuild. Let's merge this one to a different branch instead of master to see if I can get the desired behavior working after a forced rebuild or if there's something wrong with our settings.

**Pull request merged**
