### PR TITLE
Fix repo lint error

### PR DESCRIPTION
**Pull request by adegeo**
## Summary

Fix the repo lint error introduced by #26148

@BillWagner

### CODE REVIEW

**Review by tdykstra — COMMENTED** [review]
We would have to do this in every article that uses tabs -- maybe it's preferable to just turn off md024 and md025 globally?

**Comment by luisquintanilla** [comment]
Thanks @adegeo 

I merged this PR because there were no build issue other than the lint error which I didn't know you could make go away by adding the comment you added and as far as I know, the tab formatting is correct because the preview displayed correctly.

**Comment by adegeo** [comment]
@tdykstra I think we could turn it off if the build system catches it, I suspect it might!

**Comment by adegeo** [comment]
@luisquintanilla The lint errors carry over to every other PR. So we can't ignore them 😄

**Comment by adegeo** [comment]
@dotnet/docs Please comment on disabling these markdown linter checks. I think @tdykstra is correct, it's the best way to just ensure tabbed content doesn't mess things up. The build system does catch additional H1

**Comment by gewarren** [comment]
> @dotnet/docs Please comment on disabling these markdown linter checks. I think @tdykstra is correct, it's the best way to just ensure tabbed content doesn't mess things up. The build system does catch additional H1

I'm fine with that!

**Review by luisquintanilla — APPROVED** [review]

**Pull request merged**
