### PR TITLE
Update task-asynchronous-programming-model.md

### PR DESCRIPTION
**Pull request by Youssef1313**
Related to: https://github.com/dotnet/samples/pull/1601

This can't be merged before the samples PR is merged.

### CODE REVIEW

**Review by rpetrusha — APPROVED** [review]
Your changes look good, @Youssef1313, except for the link to the downloadable sample. It's best to link to the Samples Browser at <https://docs.microsoft.com/en-us/samples/dotnet/samples/async-and-await-vb/>, which will work once dotnet/samples#1601 is merged.

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Sorry, @Youssef1313. I'd meant to request changes.

**Comment by rpetrusha** [comment]
Thanks for the additional changes, @Youssef1313. And thanks for all of your efforts to improve the documentation. Since I'm retiring at the end of the day, I suspect that this is the last PR of yours that I'll review and approve. I've enjoyed working with you.

**Review by rpetrusha — APPROVED** [review]

**Comment by Youssef1313** [comment]
> Thanks for the additional changes, @Youssef1313. And thanks for all of your efforts to improve the documentation. Since I'm retiring at the end of the day, I suspect that this is the last PR of yours that I'll review and approve. I've enjoyed working with you.

Sad to hear that :(
I too have enjoyed contributing to docs.

**Pull request merged**
