### PR TITLE
Mentioning NCache cache in Azure using cache through pattern

### PR DESCRIPTION
**Pull request by mohsinnasir**
## Summary
Mentioning NCache cache in Azure using cache through pattern
Image uploading showing the architecture of cache through pattern
Mentioning of how to keep your cache fresh always using SQL dependency
Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by nishanil** [comment]
Thanks for the PR! 
@robvet Can you check if you want this included in the book?

**Comment by mohsinnasir** [comment]
@nishanil any update regarding this PR?

**Comment by mohsinnasir** [comment]
@nishanil if there are any changes required kindlytell me or kindly accept the PR?

**Comment by nishanil** [comment]
@mohsinnasir Since we haven't evaluated this product ourselves and do not have a version of eShop that includes this implementation (as per the recommendation in this PR), we will not be able to include this as part of this guidance.  I think it's best to link this product under the `Additional Resources` section instead of elaborating it out. We took similar approaches to the Microservices book in the past.

**Comment by robvet** [comment]
Hello @mohsinnasir. Thanks for reaching out with your suggestion. Do beleive nCache is solid caching product. Howver, it's not a "managed PaaS Service." It requires a VM in order to implement in the cloud. We're closely following the tenants of the CNCF (Cloud Native Computing Foundation) in advocating cloud-based managed services for backing service requirements, like caching, messaging, data storage, etc.

**Comment by BillWagner** [comment]
@robvet based on your comments, should this be closed?

**Comment by nishanil** [comment]
Closing this PR.

**Pull request closed without merging**
