### PR TITLE
Seems these should be `that` instead of `what`

### PR DESCRIPTION
**Pull request by nycdotnet**
## Summary

I think that the author meant `that` when they said `what`.

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
The "what" is correct, @nycdotnet -- the attribute specifies what assets are used/excluded etc. What makes these phrase difficult to parse is that "The" should be added before the attribute name (e.g., "The `IncludeAssets` attribute..."). Would you like to make those changes?

**Comment by nycdotnet** [comment]
Sure.  Will also switch what to which in that case.

**Review by rpetrusha — APPROVED** [review]
I've made the additional changes, @nycdotnet, so I'll merge your PR once the internal build completes successfully.

**Comment by nycdotnet** [comment]
Thanks!  sorry I didn’t get back to this.

**Pull request merged**
