### PR TITLE
added disambiguation to VB helpviewer keywords

### PR DESCRIPTION
**Pull request by mikeblome**
This PR touches all files in the visual-basic folder, adding a [VB] disambiguation tag to helpviewer_keywords so that offline help index entries are less confusing.

### CODE REVIEW

**Comment by mairaw** [comment]
Build was not showing in the OPS portal. I've opened a LSI to investigate this since it's been happening with a certain frequency.

**Review by mairaw — APPROVED** [review]
LGTM. Let's see what the build looks like.

**Comment by mairaw** [comment]
Build finished with warnings but this PR is not showing the status 😢 
https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C8%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201709080038197090-3086%5Cworkflow_report.html

**Comment by mikeblome** [comment]
@mairaw The only warnings I see are in the CSharp and API docs. Would I have introduced those in this PR? I only touched topics in visual-basic.

**Comment by mairaw** [comment]
No, no. 155 is the current number of warnings we have in our repo. So your PR didn't introduce any.

**Comment by rpetrusha** [comment]
The build doesn't appear in the OPS portal. Closing and reopening to begin new build.

**Comment by mairaw** [comment]
I'm thinking I'll merge this to a local branch in the repo and open a new PR because this thing is busted.

**Comment by mairaw** [comment]
Same comment/question I made in #3224

**Comment by mairaw** [comment]
Closing in favor of #3472

**Pull request closed without merging**
