### PR TITLE
Random cleanup

### PR DESCRIPTION
**Pull request by gewarren**
- Use xref links
- Remove phcart as author

### CODE REVIEW

**Comment by cartermp** [comment]
> Remove phcart as author

It's been a pleasure!

(also: more than happy to continue as a community contributor/helper for various F# stuff, since I still have a bunch of context in my brain 😄 )

**Comment by gewarren** [comment]
> (also: more than happy to continue as a community contributor/helper for various F# stuff, since I still have a bunch of context in my brain 😄 )

Awesome, thanks! I only removed your MS alias. Eventually that will start to throw build warnings.

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

You can :shipit: when ready.

**Comment by gewarren** [comment]
Thanks Bill!

**Pull request merged**
