### PR TITLE
Document --deterministic fsharp compiler option

### PR DESCRIPTION
**Pull request by davidglassborow**
# Document --deterministic fsharp compiler option

## Summary

This documents the compiler option added in https://github.com/Microsoft/visualfsharp/pull/2954.

## Details

See PR for full details of what was done.

## Suggested Reviewers

@cartermp

### CODE REVIEW

**Comment by svick** [comment]
Since the PR was merged recently, is this option present in the latest released version of `fsc`? I think the docs should be about the latest released version, not about what's in `master`.

**Comment by davidglassborow** [comment]
@svick I'm not exactly sure when it will be in the released fsc, @cartermp manages the F# team at MS so I'll let him advise.

**Comment by cartermp** [comment]
This feature will be merged into VS 2017 Update 3, which will land in a few months.  I'm fine with blocking on merging until that time frame, so long as this is tagged appropriately.  We do weekly triage and we'll catch it then.   Sound good @davidglassborow?

**Comment by davidglassborow** [comment]
Sounds fine @cartermp, just give me a shout if you need the wording changed.

**Comment by mairaw** [comment]
@cartermp I know this is blocked, but do you approve this PR or do we need to change anything? Just wanted to check whether this is ready to go, once it's go-time.

**Review by cartermp — APPROVED** [review]
Looks good to go for me.  We'll merge this once 15.3 ships.

**Comment by mairaw** [comment]
Removing blocked label and merging this. Thanks @davidglassborow!

**Pull request merged**
