### PR TITLE
Fix link formatting

### PR DESCRIPTION
**Pull request by nxtn**
Remove italics from e-book links as suggested by @mvelosop

https://github.com/dotnet/docs/pull/11314#issuecomment-473381097

### CODE REVIEW

**Comment by NextTurn** [comment]
So I have to go through all 50 PRs to fix all of these?

**Comment by mairaw** [comment]
I believe @mvelosop said it was fine to actually remove italic from those links. But what do you mean you to go through 50 PRs?

**Comment by NextTurn** [comment]
Do you mean removing italics from all links? Then I'll update this PR to remove them.

**Review by mvelosop — CHANGES_REQUESTED** [review]
LGTM @NextTurn, just a few minor fixes, so you can merge when you're ready.

I also removed a bunch of `<br/>` I must have skipped during a general review, some weeks ago, my fault 🙁!

**Review by mvelosop — CHANGES_REQUESTED** [review]
Hi @mairaw, @NextTurn, just discovered that [Ctrl+Enter] adds a comment even though the "Request changes" radio button was selected so the review details are in the previous comment.

**Comment by mvelosop** [comment]
LGTM @NextTurn, so I'm merging now!

**Review by mvelosop — APPROVED** [review]

**Pull request merged**
