### PR TITLE
Improve titles of some F# articles

### PR DESCRIPTION
**Pull request by svick**
1. Fix articles with `:` in `title` using `"`
2. Make `title` and first heading of articles consistent:
   - Replace `-` with `:`
   - For `getting-started-visual-studio.md`, change the `title` entirely

### CODE REVIEW

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.targetinvocationexception?branch=pr-en-us-1003)

**Comment by mairaw** [comment]
LGTM. I'll just close and reopen to see if CI passes.

**Comment by cartermp** [comment]
LGTM!

**Comment by qinezh** [comment]
Open Publishing Build Service: The pull request content has been published and here are some sample preview links:
- Docset 1: [core-docs](https://stage.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.assemblycontenttype?branch=pr-en-us-1003)

**Pull request merged**
