### PR TITLE
Fix typo in unit-testing-with-dotnet-test.md

### PR DESCRIPTION
**Pull request by chyczewski-maciej**
# Fixed a typo in the name of a directory in the tutorial.

## Details
I have fixed a typo in the name of the directory we have to create to follow the tutorial. 
In latter steps the directory is named "PrimeService.Tests", not "PrimeServices.Tests".

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Thank you for the fix @thrundi! I'll merge this as soon as our builds are green.

**Comment by GuardRex** [comment]
@thrundi @mairaw This also occurs in *docs/core/testing/unit-testing-with-mstest.md* (Line 46 I think) because that topic has the same text as this one. @thrundi, do you want to squeeze a 2nd commit on this PR before the merge to fix that one? If not, no worries ... I'll pick it up a new PR this evening.

**Comment by thrundi** [comment]
@GuardRex @mairaw  I have fixed the typo @GuardRex has mentioned. 

Should I squash the commits and force push it on the branch or just leave it as two separate commits?

**Comment by mairaw** [comment]
Thanks for the catch @GuardRex and @thrundi for making the additional fix. You can leave them separate. We can squash them when we merge.

**Comment by GuardRex** [comment]
@thrundi Yes ... thanks from me, too. I missed it on the last revision. I'm glad u caught it. :sweat_smile:

**Pull request merged**
