### PR TITLE
The input support only String, Boolean, Single

### PR DESCRIPTION
**Pull request by baruchiro**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by BillWagner** [comment]
@natke Here's another ML.NET customer PR to consider.

**Comment by natke** [comment]
Thank you for the PR @baruchiro. Do you think it's important to specify this here, as the AutoML layer is going to do the feature extraction automatically?

**Comment by natke** [comment]
Closing this, as the data type of the features is inferred.

**Comment by baruchiro** [comment]
> Thank you for the PR @baruchiro. Do you think it's important to specify this here, as the AutoML layer is going to do the feature extraction automatically?

it was a long time ago. But when you say that the feature is automatically extracted, the user thinks he doesn't have to do anything.
But he has to match his data to the three types I mentioned.

**Comment by natke** [comment]
Thank you for the clarification @baruchiro. I've re-opened this and will merge when it is built.

**Review by natke — APPROVED** [review]

**Pull request merged**
