### PR TITLE
Remove Syntax Reference and point to Language Reference

### PR DESCRIPTION
**Pull request by cartermp**
Note: links will be broken until the [language reference from migration branch](https://github.com/dotnet/docs/blob/migration/docs/csharp/language-reference/index.md) is merged into master.

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/index.md](https://github.com/cartermp/core-docs/blob/remove-syntax-reference/docs/csharp/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/index?branch=pr-en-us-1225) | [Details](#user-content-docs/csharp/index.md)
[docs/toc.md](https://github.com/cartermp/core-docs/blob/remove-syntax-reference/docs/toc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/toc.json?branch=pr-en-us-1225) | [Details](#user-content-docs/toc.md)

<a name="docs/csharp/index.md"></a>
### [docs/csharp/index.md](https://github.com/cartermp/core-docs/blob/remove-syntax-reference/docs/csharp/index.md)
 - **Line 53**: **[Warning]** Invalid file link:(~/docs/csharp/language-reference/index.md).

<a name="docs/toc.md"></a>
### [docs/toc.md](https://github.com/cartermp/core-docs/blob/remove-syntax-reference/docs/toc.md)
 - **Line Unspecified**: **[Warning]** Invalid file link:(~/docs/csharp/language-reference/index.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C11%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611112052021277-1225%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
should we add redirect instead of deleting the file? and should we make the changes on the migration branch instead?

**Comment by cartermp** [comment]
I say delete - it was an empty file and there were no other files underneath it.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/index.md](https://github.com/cartermp/core-docs/blob/remove-syntax-reference/docs/csharp/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/index?branch=pr-en-us-1225) | [Details](#user-content-docs/csharp/index.md)
[docs/toc.md](https://github.com/cartermp/core-docs/blob/remove-syntax-reference/docs/toc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/toc.json?branch=pr-en-us-1225) | [Details](#user-content-docs/toc.md)



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C15%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611152057540018-1225%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by cartermp** [comment]
@BillWagner, look good?

**Comment by BillWagner** [comment]
I'm good.  Let's :shipit:

And, I agree that deleting it is OK, because none of the redacted files had been written yet

**Pull request merged**
