### PR TITLE
Address #CA1816 warning in implement `DisposeAsync` article

### LINKED ISSUE #24104: `GC.SuppressFinalize(this);` in `DisposeAsync` violates CA1816
The `GC.SuppressFinalize(this);` in `DisposeAsync` violates https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1816. 

Should the CA1816 be updated or we should not really call `GC.SuppressFinalize(this);` in `DisposeAsync`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-the-async-dispose-pattern)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

- Move code to local _snippets_ directory
  - Delete root-level folder from samples
  - Rename and create anew
- Update source to explicitly and temporarily disable CA1816
- Update article to point to new location / file names

Fixes #24104

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
It feels strange to have a suppression like this. Is the rule incorrect, in which case an issue against dotnet/roslyn-analyzers should be filed? or the rule is correct, in which case the implementation should potentially be corrected?

**Comment by IEvangelist** [comment]
> It feels strange to have a suppression like this. Is the rule incorrect, in which case an issue against dotnet/roslyn-analyzers should be filed? or the rule is correct, in which case the implementation should potentially be corrected?

I agree that this should be brought up with the Roslyn team, I replied to the customer with that in this https://github.com/dotnet/docs/issues/24104#issuecomment-836747255. For right now, this is the fix - we should suppress this until we hear back.

**Review by Youssef1313 — COMMENTED** [review]
Actually, the CA rule was fixed in https://github.com/dotnet/roslyn-analyzers/pull/3679 😄 
Is the warning still existing in the latest version? If yes, is it still there for .NET 6 Preview?

**Comment by IEvangelist** [comment]
> Actually, the CA rule was fixed in [dotnet/roslyn-analyzers#3679](https://github.com/dotnet/roslyn-analyzers/pull/3679) 😄
> Is the warning still existing in the latest version? If yes, is it still there for .NET 6 Preview?

Oh wow, great job! Yes, it still is a warning... I'm not sure when it is planned to be released. But as soon as it is made public, I can remove the suppression.

**Review by BillWagner — APPROVED** [review]
This LGTM @IEvangelist 

You can :shipit: when ready.

**Pull request merged**
