### PR TITLE
fix examples

### LINKED ISSUE #5927: Error in example cli command
Executing 'dotnet new mvc -au None -f netcoreapp2.0' gives me the error 

Error: Invalid parameter(s):
-f netcoreapp2.0
    'netcoreapp2.0' is not a valid value for -f (Framework).

dotnet --info 

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #5927 

/cc @jfreitas

### CODE REVIEW

**Comment by mairaw** [comment]
@KathleenDollard @dsplaisted can you guys help with this question from @jfreitas? The way I'd do this is to use the global.json file set to 2.0.0 and then to 2.1.300 and use the command. But not sure if there's an easier way.

**Comment by dsplaisted** [comment]
I think @abpiskunov or @natemcmaster may be able to tell us if there's an easier way to create an ASP.NET app targeting 2.0 instead of 2.1 with the latest SDK, or route the question to someone who can.

**Review by BillWagner — APPROVED** [review]
This LGTM @mairaw 

You can :shipit: when ready.

**Comment by natemcmaster** [comment]
Installing and older SDK and using global.json is the most supported way to do that. You can also do this by installing old templates into your new SDK by running
```
dotnet new --install Microsoft.DotNet.Web.ProjectTemplates.2.0 --nuget-source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
```

**Comment by mairaw** [comment]
Thanks @natemcmaster. That indeed works! By talking to @KathleenDollard yesterday, we want to cover that scenario on the docs, but I think it'll take me some time to understand how this works exactly and with which templates, so I'll need some help. Can I merge the changes as-is and then address the templates changes on our next sprint, Kathleen?

**Comment by KathleenDollard** [comment]
Seems ok with me.

**Comment by mairaw** [comment]
New issue opened: #5961

**Pull request merged**
