### PR TITLE
Update net-core-container-scenarios.md

### PR DESCRIPTION
**Pull request by CESARDELATORRE**
Just a minor update to test editing from the Github repo and my user at GitHub

# Just changed from "web apps" to "web applications"

## Summary

Just a minor update to test editing from the Github repo and my user at GitHub

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
Seems to be working 😄 we'll just wait for builds to finish to merge.

**Comment by GuardRex** [comment]
@CESARDELATORRE 

> update to test editing from the Github repo

You don't want this merged, correct? ... it's just a test?

**Comment by CESARDELATORRE** [comment]
It is okay if it is merged as it is a very simple change that doesn't change the meaning or even improves it. So I see it changed in the final content.

**Comment by GuardRex** [comment]
Guidelines adherence calls for "app" over "application."

**Comment by mairaw** [comment]
Microsoft's style guide says in general both terms are acceptable. Where do you see that guidance @GuardRex?

**Comment by GuardRex** [comment]
The [@]tdykstra and [@]Rick-Anderson style manual :grinning:. I asked about this earlier, but perhaps they're only applying that on their side of the docs. Forgive me for jumping in; once I'm told 'do it this way,' I take it too literally sometimes.

**Comment by GuardRex** [comment]
Yes, forgive me. He said he goes that way regularly. https://github.com/aspnet/Docs/pull/2531#issuecomment-279119540

I follow [@]Rick-Anderson advice whenever possible ... Life goes smoother that way! :beers: lol

**Comment by mairaw** [comment]
No worries. Merging this now.

**Pull request merged**
