### PR TITLE
Update snapshot-isolation-in-sql-server.md

### PR DESCRIPTION
**Pull request by pmasl**
Added references to SQL docs

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by douglaslMS — CHANGES_REQUESTED** [review]
@pmasl To link from docs in one repo to docs in another repo - for example, from Framework docs to SQL docs - just begin the url with a reference to the root of the other repo. So `[Transaction Locking and Row Versioning Guide](/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)`. Can you please make this revision in your updates?

**Comment by pmasl** [comment]
I can't see a preview, to know if the rel links resolve, or if full http URLs are needed.

**Comment by pmasl** [comment]
@douglaslMS  it's done, thanks

**Comment by douglaslMS** [comment]
@pmasl These types of links don't work in our preview anyway. I will accept your changes and check the page after it's republished. If by chance I didn't get the syntax quite right, I'll (1) fix it and (2) learn a lesson!

**Review by douglaslMS — APPROVED** [review]

**Comment by mairaw** [comment]
You need to remove the .md in those urls.

**Comment by douglaslMS** [comment]
@mairaw I overlooked that. I will fix this.

**Comment by pmasl** [comment]
Thank you both!

**Comment by douglaslMS** [comment]
@mairaw I have fixed the link format in a new PR [8441](https://github.com/dotnet/docs/pull/8441). Reverting stuff scares me too much, so I used a new PR.

**Pull request merged**
