### PR TITLE
typo: indiate -> indicate

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by rpetrusha** [comment]
@nschonni, there's more wrong here than the misspelling, so I'll mark it as awaiting feedback.

@HongGit, the text "failure, however it is unsure of the transaction outcome and request its status." is problematic; I think it should read "failure; however, it is unsure of the transaction outcome and requests its status." Is that OK?

**Review by HongGit — APPROVED** [review]

**Review by HongGit — COMMENTED** [review]
hold on, I am still reviewing this.

**Comment by HongGit** [comment]
@rpetrusha, I agree with your change. I also approved the change from indicate -> indicate.

Thanks!

**Review by jzeferino — APPROVED** [review]

**Review by rpetrusha — APPROVED** [review]
Thanks, @HongGit, for your response. I'll merge your PR when the build completes, @nschonni.

**Pull request merged**
