### PR TITLE
Spark.NET: fix bulleted lists

### PR DESCRIPTION
**Pull request by mamccrea**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by mairaw — APPROVED** [review]
It shouldn't matter if you use - or *, it's just a matter of personal preference.

marrdownlint is complaining about the lack of a newline at the end of index.md.

**Comment by Youssef1313** [comment]
Both `*` and `-` will render the same, but I'd be with the `-` as the majority of docs uses it.

**Comment by JasonWHowell** [comment]
@mairaw 
> It shouldn't matter if you use - or *, it's just a matter of personal preference.
> 
> marrdownlint is complaining about the lack of a newline at the end of index.md.

Why did it complain here then? 
https://github.com/dotnet/docs/runs/261447610

```
docs/spark/what-is-spark.md: 68: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 69: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 70: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 76: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 77: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 78: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 79: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 80: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 81: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 87: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 88: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 89: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 90: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 91: MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/spark/what-is-spark.md: 97: MD047/single-trailing-newline Files should end with a single newline 
```

**Review by JasonWHowell — COMMENTED** [review]
Previews look good. 
Pending discussion with Maira if she wants to turn off this linting requirement for asterisks instead of dashes.

**Review by JasonWHowell — APPROVED** [review]

**Comment by Youssef1313** [comment]
@JasonWHowell , It complains when there is inconsistency in the file ( you sometimes use `-` and sometimes use `*`). This linting requirement is to be consistent by using only `-` or only `*`.

**Comment by JasonWHowell** [comment]
@Youssef1313 Good to know. I wish the error would say that - pretty vague.
Maybe we can improve the error -https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md004---unordered-list-style

**Pull request merged**
