### PR TITLE
Q2 Content performance updates

### LINKED ISSUE #21154: Q2 doc performance
High-traffic doc with primary KPI in bottom 25% with dwell rate of 1.95%.  One verbatim - "maybe a bit overwhelming for the first time experimenter"

The internal TOC is very long -- organize the format specifiers into groups of H3 headings instead of all H2 headings.

[Internal work item](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1790123)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52741095-f1fd-71b8-15f8-b526480f0d83
* Version Independent ID: 12b2c626-2479-1090-83fd-583c6d600ed8
* Content: [Standard date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#feedback)
* Content Source: [docs/standard/base-types/standard-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #21154

[Internal review URL](https://review.docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings?branch=pr-en-us-21314)

Fixes [AB#1790123](https://dev.azure.com/mseng/TechnicalContent/_queries/edit/1790123/?triage=true)

### CODE REVIEW

**Review by IEvangelist — APPROVED** [review]
This is awesome, much better. The only thing I suggest, is since you're touching all the headings - they should be in sentence case.

**Comment by tdykstra** [comment]
>headings - they should be in sentence case.

Do you know if there is a VS Code tool to automate that? There are a lot of headings in this file.

**Comment by adegeo** [comment]
> > headings - they should be in sentence case.
> 
> Do you know if there is a VS Code tool to automate that? There are a lot of headings in this file.

I don't know of any personally. What I would do is this:

- <kbd>CTRL-F</kbd> to open the find window
- Change mode to regex
- Enter `^## ` to get all of the headings
- Click once back in the doc to set focus, on an empty line so the caret isn't on a word.
- <kbd>CTRL+SHIFT+L</kbd> to create a cursor on every line matching the **find**.
- <kbd>SHIFT+END</kbd> to select the whole line of the header
- <kbd>F1</kbd>and select **Transform to lower case** <kbd>ENTER</kbd>

Now you only have to go to each header and capitalize the first letter instead of every word.

**Comment by tdykstra** [comment]
@adegeo Thanks for the suggestion and @IEvangelist Thanks for the review!

**Pull request merged**
