### PR TITLE
Update index based on comment

### PR DESCRIPTION
**Pull request by cartermp**
Fixed based on a comment.  Moved Tutorials up.

### CODE REVIEW

**Comment by cartermp** [comment]
@mairaw @GuardRex @BillWagner This is just a minor change based on a comment.  I'm also unable to log in to reply to them for some reason.  No ability to create a new account or log in with my existing one...the comment is here if you're able to log in: https://docs.microsoft.com/en-us/dotnet/articles/fsharp/

**Comment by GuardRex** [comment]
> if you're able to log in

@cartermp I took care of it. :+1:

**Comment by mairaw** [comment]
That happened when we removed the empty/wrench topics. If we need to link to tutorials, we might consider adding content to https://github.com/dotnet/docs/blob/master/docs/fsharp/tutorials/index.md.

**Review by mairaw — APPROVED** [review]

**Comment by cartermp** [comment]
Thanks!

**Pull request merged**
