### PR TITLE
Fix Issue 1190

### LINKED ISSUE #1190: An item with the same key has already been added. Key: Microsoft.NETCore.App
File [project.json](https://github.com/dotnet/docs/blob/master/samples/core/getting-started/unit-testing-using-dotnet-test/test/PrimeService.Tests/project.json) of the test project contains 2 items with the same key on Lines [6](https://github.com/dotnet/docs/blob/master/samples/core/getting-started/unit-testing-using-dotnet-test/test/PrimeService.Tests/project.json#L6) and [19](https://github.com/dotnet/docs/blob/master/samples/core/getting-started/unit-testing-using-dotnet-test/test/PrimeService.Tests/project.json#L19):

Visual Studio 2015 shows the following error:
image

Here is the project.json file structure reference: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#frameworks

I think there should be only one dependency: either package-level or framework-specific.

### PR DESCRIPTION
**Pull request by BillWagner**
This fixes parsing errors in Project.json in the unit testing tutorial.

Fixes #1190

### CODE REVIEW

**Comment by mairaw** [comment]
Do we also need to add a note to the beginning of this topic that it applies to .NET Core 1.0? Since source code uses 1.0?

/cc @blackdwarf

**Comment by BillWagner** [comment]
closing and re-opening to  start a build again.

**Comment by BillWagner** [comment]
@blackdwarf Can you speak to @mairaw 's question above? I'd like to finish this one out.

**Comment by blackdwarf** [comment]
@BillWagner sorry 'bout that. Yep, we should.

**Comment by BillWagner** [comment]
Thanks @blackdwarf.

Updated.

@mairaw is this ready to merge now?

**Review by mairaw — APPROVED** [review]

**Comment by BillWagner** [comment]
closing and reopening to force a new build.

**Pull request merged**
