### PR TITLE
Improved formatting

### PR DESCRIPTION
**Pull request by FrankAtHexagon**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=20262) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=20262) before we can accept your contribution.<br/><br/>:x: FrankAtHexagon [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=20262)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=20262) it.</sub>

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Based on the guidelines, I think paths should be made italic, not code fenced.

**Comment by adegeo** [comment]
@FrankAtHexagon Thanks for the submission! As pointed out, the paths actually are supposed to be surrounded by `_` characters which creates an _italic_ style.

**Review by adegeo — CHANGES_REQUESTED** [review]
@FrankAtHexagon Thanks for the submission! As pointed out, the paths actually are supposed to be surrounded by `_` characters which creates an _italic_ style.

**Comment by FrankAtHexagon** [comment]
Alright, thanks for your input. Are drives (like `C:`) considered a path? I feel like the colon makes the drive hard to read if it's just italicized, like _C:_.

This file also already contains many instances of paths being inline code style and not italicized. I understand that this file may be old, but there's quite a bit to be changed.

**Comment by adegeo** [comment]
@FrankAtHexagon Sorry for the delay in getting back to you! Yeah you're right, great point! I'll merge this as-is, however, you need to sign the CLA that the dnfadmin account comment above.

**Comment by FrankAtHexagon** [comment]
Signed.

**Comment by adegeo** [comment]
Thanks again.

**Review by adegeo — APPROVED** [review]

**Pull request merged**
