### PR TITLE
Surface Forwarded Headers in Docker topic

### PR DESCRIPTION
**Pull request by guardrex**
@JRAlexander This patch suggestion came about because a community member, @nrandell, didn't see our topic that pertains to the use of Forwarded Headers Middleware for a containerized app.

We have a link to the topic, [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer), on our [Docker index page in the ASP.NET Core docs](https://docs.microsoft.com/aspnet/core/host-and-deploy/docker), but that wasn't enough to surface the existence of the topic.

Please feel free to close this, move it, hack it ... I'm guessing a bit that this would be a good spot. I placed it immediately before the first experience walk-through.

Cross-ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/556

[Internal Review Topic](https://review.docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images?branch=pr-en-us-5764#forward-the-request-scheme-and-original-ip-address)

cc/ @jmprieur @Rick-Anderson @scottaddie 

Thanks to @nrandell for surfacing the problem. :rocket:

### CODE REVIEW

**Comment by guardrex** [comment]
FYI: Couple of warnings popped up that don't pertain to this PR.

**docs/core/additional-tools/dotnet-svcutil-guide.md**
Invalid file link:(~/docs/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe)

**docs/core/additional-tools/dotnet-svcutil-guide.md**
Invalid file link:(~/docs/core/additional-tools/wcf-web-service-reference-guide)

**docs/framework/wcf/samples/custom-lifetime.md**
1 invalid cross reference(s) "<xref:System.ServiceModel.Dispatcher.IShareableInstanceContextLifetime>"

**Comment by JRAlexander** [comment]
Thanks, @guardrex! I'll review today.

**Comment by JRAlexander** [comment]
I have a community PR on this same topic. As soon as that merges, I'll add this.

**Comment by guardrex** [comment]
@JRAlexander Side-note of possible interest: Since the `dotnet new` templates configure HTTPS Redirection Middleware, we're going to surface that devs can't expect an OOB template app to run on an unconfigured (for HTTPS) host. We're still working on final language: https://github.com/aspnet/Docs/pull/6886

**Comment by JRAlexander** [comment]
@guardrex - Did you settle on final language?

**Comment by guardrex** [comment]
Not really. It's all still in a bit of flux on https://github.com/aspnet/Docs/issues/6538.

However, what I propose on this PR is still valid from an ASP.NET Core perspective. We're still pushing Forwarded Headers Middleware for proxied apps, and the linked topic on this PR is the place to go to get that info.

I'm not a Docker cat, so I can't say if there are hidden *gotchas*, but at least this will get a reader here over to the right topic *that should in theory* get the scheme, IP, port, and host forwarded for a containerized app.

**Comment by JRAlexander** [comment]
Makes sense to me.

**Review by JRAlexander — APPROVED** [review]
LGTM. Thanks,@guardrex, for your contribution. I';ll merge this and you should see it live in a day or two.

**Pull request merged**
