### PR TITLE
Added quick filters in metadata

### PR DESCRIPTION
**Pull request by bryandenosky**
# Title

Added quick filters in metadata

## Summary

https://mseng.visualstudio.com/CSI/_workitems/edit/1064027

## Suggested Reviewers

@jdanyow @adkinn

### CODE REVIEW

**Comment by mairaw** [comment]
Looks ok to me. @adkinn ok to merge?

**Comment by adkinn** [comment]
@mairaw yep, all good

**Review by mairaw — APPROVED** [review]

**Comment by mairaw** [comment]
ah damn it! just noticed it was going straight to live. It should have been to master first. 😢

**Comment by mairaw** [comment]
Applied the change to the master branch now so the two branches don't get out of sync. We only fast forward changes from master to live.

**Pull request merged**
