### PR TITLE
grammar correction

### PR DESCRIPTION
**Pull request by a-elnajjar**
-use is instead of or are
-remove 'a'

### CODE REVIEW

**Review by rpetrusha — CHANGES_REQUESTED** [review]
Thanks, @a-elnajjar, for the grammar corrections. The second -- the change from "a service" to "service", however, produces a more awkward sentence. If you can revert your change, I'll merge your PR.

**Review by a-elnajjar — COMMENTED** [review]
revert to 'a service'

**Comment by a-elnajjar** [comment]
@rpetrusha I reverted the 2nd change :)

**Review by rpetrusha — APPROVED** [review]
Thanks, @a-elnajjar, for making the additional correction. We'll merge your PR now. The change should appear live on docs.microsoft.com in the next day or two.

**Pull request merged**
