### PR TITLE
Model Builder Azure Image Classification Tutorial

### PR DESCRIPTION
**Pull request by luisquintanilla**
Model Builder Azure Image Classification Tutorial

Preview Link: https://review.docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-model-builder?branch=pr-en-us-17825

[AB#1594288](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1594288)

### CODE REVIEW

**Comment by IEvangelist** [comment]
Hi @luisquintanilla - just working backwards through open PRs. Is this one ready to go?

**Comment by luisquintanilla** [comment]
Hey @IEvangelist 

I'm going to close this one for now. Still in the process of reworking it. I'll reopen when we have a new one ready. Thanks

**Comment by IEvangelist** [comment]
You could have left it open as a draft. :smile:

**Comment by luisquintanilla** [comment]
Lol by rework I basically meant do a complete rewrite so at it won't even be the same doc 😁. Thanks though.

**Pull request closed without merging**
